/*
 Highcharts JS v11.1.0 (2023-08-20)

 Annotations module

 (c) 2009-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/annotations",["highcharts"],function(r){b(r);b.Highcharts=r;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function r(b,l,h,f){b.hasOwnProperty(l)||(b[l]=f.apply(null,h),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:l,module:b[l]}})))}b=b?b._modules:
{};r(b,"Extensions/Annotations/AnnotationChart.js",[b["Core/Utilities.js"]],function(b){function l(a,c){a=this.initAnnotation(a);this.options.annotations.push(a.options);e(c,!0)&&(a.redraw(),a.graphic.attr({opacity:1}));return a}function h(){const a=this;a.plotBoxClip=this.renderer.clipRect(this.plotBox);a.controlPointsGroup=a.renderer.g("control-points").attr({zIndex:99}).clip(a.plotBoxClip).add();a.options.annotations.forEach((c,d)=>{if(!a.annotations.some(a=>a.options===c)){const e=a.initAnnotation(c);
a.options.annotations[d]=e.options}});a.drawAnnotations();c(a,"redraw",a.drawAnnotations);c(a,"destroy",function(){a.plotBoxClip.destroy();a.controlPointsGroup.destroy()});c(a,"exportData",function(c){function d(a){let c;if(e&&(c=e(a),!1!==c))return c;c=b+" "+a;return m?{columnTitle:c,topLevelColumnTitle:c}:c}const e=(this.options.exporting&&this.options.exporting.csv||{}).columnHeaderFormatter,m=!c.dataRows[1].xValues,b=a.options.lang&&a.options.lang.exportData&&a.options.lang.exportData.annotationHeader,
g=c.dataRows[0].length,v=a.options.exporting&&a.options.exporting.csv&&a.options.exporting.csv.annotations&&a.options.exporting.csv.annotations.itemDelimiter,k=a.options.exporting&&a.options.exporting.csv&&a.options.exporting.csv.annotations&&a.options.exporting.csv.annotations.join;a.annotations.forEach(a=>{a.options.labelOptions&&a.options.labelOptions.includeInDataExport&&a.labels.forEach(a=>{if(a.options.text){const d=a.options.text;a.points.forEach(a=>{const e=a.x,n=a.series.xAxis?a.series.xAxis.index:
-1;let m=!1;if(-1===n){a=c.dataRows[0].length;var p=Array(a);for(var x=0;x<a;++x)p[x]="";p.push(d);p.xValues=[];p.xValues[n]=e;c.dataRows.push(p);m=!0}m||c.dataRows.forEach(a=>{!m&&a.xValues&&void 0!==n&&e===a.xValues[n]&&(k&&a.length>g?a[a.length-1]+=v+d:a.push(d),m=!0)});if(!m){a=c.dataRows[0].length;p=Array(a);for(x=0;x<a;++x)p[x]="";p[0]=e;p.push(d);p.xValues=[];void 0!==n&&(p.xValues[n]=e);c.dataRows.push(p)}})}})});let u=0;c.dataRows.forEach(a=>{u=Math.max(u,a.length)});const z=u-c.dataRows[0].length;
for(let a=0;a<z;a++){const e=d(a+1);m?(c.dataRows[0].push(e.topLevelColumnTitle),c.dataRows[1].push(e.columnTitle)):c.dataRows[0].push(e)}})}function f(){this.plotBoxClip.attr(this.plotBox);this.annotations.forEach(a=>{a.redraw();a.graphic.animate({opacity:1},a.animationConfig)})}function k(a){const c=this.annotations,e="annotations"===a.coll?a:q(c,function(c){return c.options.id===a});e&&(v(e,"remove"),g(this.options.annotations,e.options),g(c,e),e.destroy())}function d(){this.annotations=[];this.options.annotations||
(this.options.annotations=[])}function a(a){this.chart.hasDraggedAnnotation||a.apply(this,Array.prototype.slice.call(arguments,1))}const {addEvent:c,erase:g,find:q,fireEvent:v,pick:e,wrap:m}=b,z=[];var A;(function(e){e.compose=function(e,g,p){b.pushUnique(z,g)&&(c(g,"afterInit",d),g=g.prototype,g.addAnnotation=l,g.callbacks.push(h),g.collectionsWithInit.annotations=[l],g.collectionsWithUpdate.push("annotations"),g.drawAnnotations=f,g.removeAnnotation=k,g.initAnnotation=function(a){a=new (e.types[a.type]||
e)(this,a);this.annotations.push(a);return a});b.pushUnique(z,p)&&m(p.prototype,"onContainerMouseDown",a)}})(A||(A={}));return A});r(b,"Extensions/Annotations/AnnotationDefaults.js",[b["Core/Utilities.js"]],function(b){const {defined:l}=b;return{visible:!0,animation:{},crop:!0,draggable:"xy",labelOptions:{align:"center",allowOverlap:!1,backgroundColor:"rgba(0, 0, 0, 0.75)",borderColor:"#000000",borderRadius:3,borderWidth:1,className:"highcharts-no-tooltip",crop:!1,formatter:function(){return l(this.y)?
""+this.y:"Annotation label"},includeInDataExport:!0,overflow:"justify",padding:5,shadow:!1,shape:"callout",style:{fontSize:"0.7em",fontWeight:"normal",color:"contrast"},useHTML:!1,verticalAlign:"bottom",x:0,y:-16},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1,fill:"rgba(0, 0, 0, 0.75)",r:0,snap:2},controlPointOptions:{events:{},style:{cursor:"pointer",fill:"#ffffff",stroke:"#000000","stroke-width":2},height:10,symbol:"circle",visible:!1,width:10},events:{},zIndex:6}});r(b,"Extensions/Annotations/EventEmitter.js",
[b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,l){const {doc:h,isTouchDevice:f}=b,{addEvent:k,fireEvent:d,objectEach:a,pick:c,removeEvent:g}=l;class q{addEvents(){function c(a){k(a,f?"touchstart":"mousedown",a=>{e.onMouseDown(a)},{passive:!1})}const e=this;c(this.graphic.element);(e.labels||[]).forEach(a=>{a.options.useHTML&&a.graphic.text&&c(a.graphic.text.element)});a(e.options.events,(a,c)=>{function d(d){"click"===c&&e.cancelClick||a.call(e,e.chart.pointer.normalize(d),e.target)}if(-1===
(e.nonDOMEvents||[]).indexOf(c))e.graphic.on(c,d);else k(e,c,d,{passive:!1})});if(e.options.draggable&&(k(e,"drag",e.onDrag),!e.graphic.renderer.styledMode)){const a={cursor:{x:"ew-resize",y:"ns-resize",xy:"move"}[e.options.draggable]};e.graphic.css(a);(e.labels||[]).forEach(c=>{c.options.useHTML&&c.graphic.text&&c.graphic.text.css(a)})}e.isUpdating||d(e,"add")}destroy(){this.removeDocEvents();g(this);this.hcEvents=null}mouseMoveToRadians(a,c,d){let e=a.prevChartY-d,m=a.prevChartX-c;d=a.chartY-d;
a=a.chartX-c;this.chart.inverted&&(c=m,m=e,e=c,c=a,a=d,d=c);return Math.atan2(d,a)-Math.atan2(e,m)}mouseMoveToScale(a,c,d){c=(a.chartX-c||1)/(a.prevChartX-c||1);a=(a.chartY-d||1)/(a.prevChartY-d||1);this.chart.inverted&&(d=a,a=c,c=d);return{x:c,y:a}}mouseMoveToTranslation(a){let c=a.chartX-a.prevChartX;a=a.chartY-a.prevChartY;let d;this.chart.inverted&&(d=a,a=c,c=d);return{x:c,y:a}}onDrag(a){if(this.chart.isInsidePlot(a.chartX-this.chart.plotLeft,a.chartY-this.chart.plotTop,{visiblePlotOnly:!0})){const c=
this.mouseMoveToTranslation(a);"x"===this.options.draggable&&(c.y=0);"y"===this.options.draggable&&(c.x=0);this.points.length?this.translate(c.x,c.y):(this.shapes.forEach(a=>a.translate(c.x,c.y)),this.labels.forEach(a=>a.translate(c.x,c.y)));this.redraw(!1)}}onMouseDown(a){a.preventDefault&&a.preventDefault();if(2!==a.button){var e=this,g=e.chart.pointer;a=g.normalize(a);var b=a.chartX,q=a.chartY;e.cancelClick=!1;e.chart.hasDraggedAnnotation=!0;e.removeDrag=k(h,f?"touchmove":"mousemove",function(a){e.hasDragged=
!0;a=g.normalize(a);a.prevChartX=b;a.prevChartY=q;d(e,"drag",a);b=a.chartX;q=a.chartY},f?{passive:!1}:void 0);e.removeMouseUp=k(h,f?"touchend":"mouseup",function(a){const g=c(e.target&&e.target.annotation,e.target);g&&(g.cancelClick=e.hasDragged);e.cancelClick=e.hasDragged;e.hasDragged=!1;e.chart.hasDraggedAnnotation=!1;d(c(g,e),"afterUpdate");e.onMouseUp(a)},f?{passive:!1}:void 0)}}onMouseUp(){var a=this.chart;const c=this.target||this,d=a.options.annotations;a=a.annotations.indexOf(c);this.removeDocEvents();
d[a]=c.options}removeDocEvents(){this.removeDrag&&(this.removeDrag=this.removeDrag());this.removeMouseUp&&(this.removeMouseUp=this.removeMouseUp())}}return q});r(b,"Extensions/Annotations/ControlPoint.js",[b["Extensions/Annotations/EventEmitter.js"],b["Core/Utilities.js"]],function(b,l){const {merge:h,pick:f}=l;class k extends b{constructor(d,a,c,g){super();this.graphic=void 0;this.nonDOMEvents=["drag"];this.chart=d;this.target=a;this.options=c;this.index=f(c.index,g)}destroy(){super.destroy();this.graphic&&
(this.graphic=this.graphic.destroy());this.options=this.target=this.chart=null}redraw(d){this.graphic[d?"animate":"attr"](this.options.positioner.call(this,this.target))}render(){const d=this.chart,a=this.options;this.graphic=d.renderer.symbol(a.symbol,0,0,a.width,a.height).add(d.controlPointsGroup).css(a.style);this.setVisibility(a.visible);this.addEvents()}setVisibility(d){this.graphic[d?"show":"hide"]();this.options.visible=d}update(d){const a=this.chart,c=this.target,g=this.index;d=h(!0,this.options,
d);this.destroy();this.constructor(a,c,d,g);this.render(a.controlPointsGroup);this.redraw()}}"";return k});r(b,"Extensions/Annotations/MockPoint.js",[b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,l){const {series:{prototype:h}}=b,{defined:f,fireEvent:k}=l;class d{static fromPoint(a){return new d(a.series.chart,null,{x:a.x,y:a.y,xAxis:a.series.xAxis,yAxis:a.series.yAxis})}static pointToPixels(a,c){const d=a.series,b=d.chart;let k=a.plotX||0,e=a.plotY||0;b.inverted&&(a.mock?
(k=a.plotY,e=a.plotX):(k=b.plotWidth-(a.plotY||0),e=b.plotHeight-(a.plotX||0)));d&&!c&&(a=d.getPlotBox(),k+=a.translateX,e+=a.translateY);return{x:k,y:e}}static pointToOptions(a){return{x:a.x,y:a.y,xAxis:a.series.xAxis,yAxis:a.series.yAxis}}constructor(a,c,d){this.plotY=this.plotX=void 0;this.mock=!0;this.series={visible:!0,chart:a,getPlotBox:h.getPlotBox};this.target=c||null;this.options=d;this.applyOptions(this.getOptions())}applyOptions(a){this.command=a.command;this.setAxis(a,"x");this.setAxis(a,
"y");this.refresh()}getLabelConfig(){return{x:this.x,y:this.y,point:this}}getOptions(){return this.hasDynamicOptions()?this.options(this.target):this.options}hasDynamicOptions(){return"function"===typeof this.options}isInsidePlot(){const a=this.plotX,c=this.plotY,d=this.series.xAxis,b=this.series.yAxis,h={x:a,y:c,isInsidePlot:!0,options:{}};d&&(h.isInsidePlot=f(a)&&0<=a&&a<=d.len);b&&(h.isInsidePlot=h.isInsidePlot&&f(c)&&0<=c&&c<=b.len);k(this.series.chart,"afterIsInsidePlot",h);return h.isInsidePlot}refresh(){var a=
this.series;const c=a.xAxis;a=a.yAxis;const d=this.getOptions();c?(this.x=d.x,this.plotX=c.toPixels(d.x,!0)):(this.x=void 0,this.plotX=d.x);a?(this.y=d.y,this.plotY=a.toPixels(d.y,!0)):(this.y=null,this.plotY=d.y);this.isInside=this.isInsidePlot()}refreshOptions(){var a=this.series;const c=a.xAxis;a=a.yAxis;this.x=this.options.x=c?this.options.x=c.toValue(this.plotX,!0):this.plotX;this.y=this.options.y=a?a.toValue(this.plotY,!0):this.plotY}rotate(a,c,d){if(!this.hasDynamicOptions()){const b=Math.cos(d);
d=Math.sin(d);const g=this.plotX-a,e=this.plotY-c,m=g*d+e*b;this.plotX=g*b-e*d+a;this.plotY=m+c;this.refreshOptions()}}scale(a,c,d,b){if(!this.hasDynamicOptions()){const g=this.plotY*b;this.plotX=(1-d)*a+this.plotX*d;this.plotY=(1-b)*c+g;this.refreshOptions()}}setAxis(a,c){c+="Axis";a=a[c];const d=this.series.chart;this.series[c]="object"===typeof a?a:f(a)?d[c][a]||d.get(a):null}toAnchor(){const a=[this.plotX,this.plotY,0,0];this.series.chart.inverted&&(a[0]=this.plotY,a[1]=this.plotX);return a}translate(a,
c,d,b){this.hasDynamicOptions()||(this.plotX+=d,this.plotY+=b,this.refreshOptions())}}"";return d});r(b,"Extensions/Annotations/ControlTarget.js",[b["Extensions/Annotations/ControlPoint.js"],b["Extensions/Annotations/MockPoint.js"],b["Core/Utilities.js"]],function(b,l,h){var f;(function(k){function d(){const a=this.controlPoints,c=this.options.controlPoints||[];c.forEach((d,e)=>{d=h.merge(this.options.controlPointOptions,d);d.index||(d.index=e);c[e]=d;a.push(new b(this.chart,this,d))})}function a(a){const c=
a.series.getPlotBox(),d=a.series.chart;var e=a.mock?a.toAnchor():d.tooltip&&d.tooltip.getAnchor.call({chart:a.series.chart},a)||[0,0,0,0];e={x:e[0]+(this.options.x||0),y:e[1]+(this.options.y||0),height:e[2]||0,width:e[3]||0};return{relativePosition:e,absolutePosition:h.merge(e,{x:e.x+(a.mock?c.translateX:d.plotLeft),y:e.y+(a.mock?c.translateY:d.plotTop)})}}function c(){this.controlPoints.forEach(a=>a.destroy());this.options=this.points=this.controlPoints=this.chart=null;this.annotation&&(this.annotation=
null)}function g(){const a=this.options;return a.points||a.point&&h.splat(a.point)}function f(){const a=this.getPointsOptions(),c=this.points,d=a&&a.length||0;let e,b;for(e=0;e<d;e++){b=this.point(a[e],c[e]);if(!b){c.length=0;return}b.mock&&b.refresh();c[e]=b}return c}function v(a,c){if(a&&a.series)return a;c&&null!==c.series||(h.isObject(a)?c=new l(this.chart,this,a):h.isString(a)?c=this.chart.get(a)||null:"function"===typeof a&&(c=a.call(c,this),c=c.series?c:new l(this.chart,this,a)));return c}
function e(a){this.controlPoints.forEach(c=>c.redraw(a))}function m(){this.controlPoints.forEach(a=>a.render())}function z(a,c,d,e,b){if(this.chart.inverted){const a=c;c=d;d=a}this.points.forEach((m,g)=>this.transformPoint(a,c,d,e,b,g),this)}function A(a,c,d,e,b,m){let g=this.points[m];g.mock||(g=this.points[m]=l.fromPoint(g));g[a](c,d,e,b)}function u(a,c){this.transform("translate",null,null,a,c)}function F(a,c,d){this.transformPoint("translate",null,null,a,c,d)}const C=[];k.compose=function(b){h.pushUnique(C,
b)&&h.merge(!0,b.prototype,{addControlPoints:d,anchor:a,destroyControlTarget:c,getPointsOptions:g,linkPoints:f,point:v,redrawControlPoints:e,renderControlPoints:m,transform:z,transformPoint:A,translate:u,translatePoint:F})}})(f||(f={}));return f});r(b,"Extensions/Annotations/Controllables/Controllable.js",[b["Extensions/Annotations/ControlTarget.js"],b["Core/Utilities.js"]],function(b,l){const {merge:h}=l;class f{constructor(b,d,a,c){this.graphic=void 0;this.annotation=b;this.chart=b.chart;this.collection=
"label"===c?"labels":"shapes";this.controlPoints=[];this.options=d;this.points=[];this.index=a;this.itemType=c;this.init(b,d,a)}attr(...b){this.graphic.attr.apply(this.graphic,arguments)}attrsFromOptions(b){const d=this.constructor.attrsMap,a={},c=this.chart.styledMode;let g,k;for(g in b)k=d[g],"undefined"===typeof d[g]||c&&-1!==["fill","stroke","stroke-width"].indexOf(k)||(a[k]=b[g]);return a}destroy(){this.graphic&&(this.graphic=this.graphic.destroy());this.tracker&&(this.tracker=this.tracker.destroy());
this.destroyControlTarget()}init(b,d,a){this.annotation=b;this.chart=b.chart;this.options=d;this.points=[];this.controlPoints=[];this.index=a;this.linkPoints();this.addControlPoints()}redraw(b){this.redrawControlPoints(b)}render(){this.renderControlPoints()}rotate(b,d,a){this.transform("rotate",b,d,a)}scale(b,d,a,c){this.transform("scale",b,d,a,c)}setControlPointsVisibility(b){this.controlPoints.forEach(d=>{d.setVisibility(b)})}shouldBeDrawn(){return!!this.points.length}translateShape(b,d,a){var c=
this.annotation.chart;const g=this.annotation.userOptions,k=c.annotations.indexOf(this.annotation);c=c.options.annotations[k];this.translatePoint(b,d,0);a&&this.translatePoint(b,d,1);c[this.collection][this.index].point=this.options.point;g[this.collection][this.index].point=this.options.point}update(b){var d=this.annotation;const a=h(!0,this.options,b);b=this.graphic.parentGroup;const c=this.constructor;this.destroy();d=new c(d,a,this.index,this.itemType);h(!0,this,d);this.render(b);this.redraw()}}
b.compose(f);"";return f});r(b,"Extensions/Annotations/Controllables/ControllableDefaults.js",[],function(){return{defaultMarkers:{arrow:{tagName:"marker",attributes:{id:"arrow",refY:5,refX:9,markerWidth:10,markerHeight:10},children:[{tagName:"path",attributes:{d:"M 0 0 L 10 5 L 0 10 Z","stroke-width":0}}]},"reverse-arrow":{tagName:"marker",attributes:{id:"reverse-arrow",refY:5,refX:1,markerWidth:10,markerHeight:10},children:[{tagName:"path",attributes:{d:"M 0 5 L 10 0 L 10 10 Z","stroke-width":0}}]}}}});
r(b,"Extensions/Annotations/Controllables/ControllablePath.js",[b["Extensions/Annotations/Controllables/Controllable.js"],b["Extensions/Annotations/Controllables/ControllableDefaults.js"],b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,l,h,f){function k(a){return function(c){this.attr(a,"url(#"+c+")")}}function d(){this.options.defs=e(c,this.options.defs||{})}function a(a,c){const d={attributes:{id:a}},b={stroke:c.color||"none",fill:c.color||"rgba(0, 0, 0, 0.75)"};d.children=c.children&&c.children.map(function(a){return e(b,
a)});c=e(!0,{attributes:{markerWidth:20,markerHeight:20,refX:0,refY:0,orient:"auto"}},c,d);c=this.definition(c);c.id=a;return c}const {defaultMarkers:c}=l,{addEvent:g,defined:q,extend:v,merge:e,uniqueKey:m}=f,z=[],A=k("marker-end"),u=k("marker-start"),F="rgba(192,192,192,"+(h.svg?.0001:.002)+")";class C extends b{static compose(c,b){f.pushUnique(z,c)&&g(c,"afterGetContainer",d);f.pushUnique(z,b)&&(b.prototype.addMarker=a)}constructor(a,c,d){super(a,c,d,"shape");this.type="path"}toD(){var a=this.options.d;
if(a)return"function"===typeof a?a.call(this):a;a=this.points;const c=a.length,d=[];var b=c;let e=a[0],m=b&&this.anchor(e).absolutePosition,g=0;if(m)for(d.push(["M",m.x,m.y]);++g<c&&b;)e=a[g],b=e.command||"L",m=this.anchor(e).absolutePosition,"M"===b?d.push([b,m.x,m.y]):"L"===b?d.push([b,m.x,m.y]):"Z"===b&&d.push([b]),b=e.series.visible;return b&&this.graphic?this.chart.renderer.crispLine(d,this.graphic.strokeWidth()):null}shouldBeDrawn(){return super.shouldBeDrawn()||!!this.options.d}render(a){const c=
this.options,d=this.attrsFromOptions(c);this.graphic=this.annotation.chart.renderer.path([["M",0,0]]).attr(d).add(a);c.className&&this.graphic.addClass(c.className);this.tracker=this.annotation.chart.renderer.path([["M",0,0]]).addClass("highcharts-tracker-line").attr({zIndex:2}).add(a);this.annotation.chart.styledMode||this.tracker.attr({"stroke-linejoin":"round",stroke:F,fill:F,"stroke-width":this.graphic.strokeWidth()+2*c.snap});super.render();v(this.graphic,{markerStartSetter:u,markerEndSetter:A});
this.setMarkers(this)}redraw(a){if(this.graphic){const c=this.toD(),d=a?"animate":"attr";c?(this.graphic[d]({d:c}),this.tracker[d]({d:c})):(this.graphic.attr({d:"M 0 -9000000000"}),this.tracker.attr({d:"M 0 -9000000000"}));this.graphic.placed=this.tracker.placed=!!c}super.redraw(a)}setMarkers(a){const c=a.options,d=a.chart,b=d.options.defs,g=c.fill,k=q(g)&&"none"!==g?g:c.stroke;["markerStart","markerEnd"].forEach(function(g){var f=c[g];let n,t,y;if(f){for(y in b)if(n=b[y],(f===(n.attributes&&n.attributes.id)||
f===n.id)&&"marker"===n.tagName){t=n;break}t&&(f=a[g]=d.renderer.addMarker((c.id||m())+"-"+f,e(t,{color:k})),a.attr(g,f.getAttribute("id")))}})}}C.attrsMap={dashStyle:"dashstyle",strokeWidth:"stroke-width",stroke:"stroke",fill:"fill",zIndex:"zIndex"};return C});r(b,"Extensions/Annotations/Controllables/ControllableRect.js",[b["Extensions/Annotations/Controllables/Controllable.js"],b["Extensions/Annotations/Controllables/ControllablePath.js"],b["Core/Utilities.js"]],function(b,l,h){({merge:h}=h);class f extends b{constructor(b,
d,a){super(b,d,a,"shape");this.type="rect";this.translate=super.translateShape}render(b){const d=this.attrsFromOptions(this.options);this.graphic=this.annotation.chart.renderer.rect(0,-9E9,0,0).attr(d).add(b);super.render()}redraw(b){if(this.graphic){const d=this.anchor(this.points[0]).absolutePosition;if(d)this.graphic[b?"animate":"attr"]({x:d.x,y:d.y,width:this.options.width,height:this.options.height});else this.attr({x:0,y:-9E9});this.graphic.placed=!!d}super.redraw(b)}}f.attrsMap=h(l.attrsMap,
{width:"width",height:"height"});return f});r(b,"Extensions/Annotations/Controllables/ControllableCircle.js",[b["Extensions/Annotations/Controllables/Controllable.js"],b["Extensions/Annotations/Controllables/ControllablePath.js"],b["Core/Utilities.js"]],function(b,l,h){({merge:h}=h);class f extends b{constructor(b,d,a){super(b,d,a,"shape");this.type="circle";this.translate=super.translateShape}redraw(b){if(this.graphic){const d=this.anchor(this.points[0]).absolutePosition;if(d)this.graphic[b?"animate":
"attr"]({x:d.x,y:d.y,r:this.options.r});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!d}super.redraw.call(this,b)}render(b){const d=this.attrsFromOptions(this.options);this.graphic=this.annotation.chart.renderer.circle(0,-9E9,0).attr(d).add(b);super.render()}setRadius(b){this.options.r=b}}f.attrsMap=h(l.attrsMap,{r:"r"});return f});r(b,"Extensions/Annotations/Controllables/ControllableEllipse.js",[b["Extensions/Annotations/Controllables/Controllable.js"],b["Extensions/Annotations/Controllables/ControllablePath.js"],
b["Core/Utilities.js"]],function(b,l,h){const {merge:f,defined:k}=h;class d extends b{constructor(a,c,d){super(a,c,d,"shape");this.type="ellipse"}init(a,c,d){k(c.yAxis)&&c.points.forEach(a=>{a.yAxis=c.yAxis});k(c.xAxis)&&c.points.forEach(a=>{a.xAxis=c.xAxis});super.init(a,c,d)}render(a){this.graphic=this.annotation.chart.renderer.createElement("ellipse").attr(this.attrsFromOptions(this.options)).add(a);super.render()}translate(a,c){super.translateShape(a,c,!0)}getDistanceFromLine(a,c,d,b){return Math.abs((c.y-
a.y)*d-(c.x-a.x)*b+c.x*a.y-c.y*a.x)/Math.sqrt((c.y-a.y)*(c.y-a.y)+(c.x-a.x)*(c.x-a.x))}getAttrs(a,c){var d=a.x,b=a.y;const f=c.x,e=c.y;c=(d+f)/2;a=(b+e)/2;const m=Math.sqrt((d-f)*(d-f)/4+(b-e)*(b-e)/4);b=180*Math.atan((e-b)/(f-d))/Math.PI;c<d&&(b+=180);d=this.getRY();return{cx:c,cy:a,rx:m,ry:d,angle:b}}getRY(){const a=this.getYAxis();return k(a)?Math.abs(a.toPixels(this.options.ry)-a.toPixels(0)):this.options.ry}getYAxis(){return this.chart.yAxis[this.options.yAxis]}getAbsolutePosition(a){return this.anchor(a).absolutePosition}redraw(a){if(this.graphic){const d=
this.getAbsolutePosition(this.points[0]);var c=this.getAbsolutePosition(this.points[1]);c=this.getAttrs(d,c);if(d)this.graphic[a?"animate":"attr"]({cx:c.cx,cy:c.cy,rx:c.rx,ry:c.ry,rotation:c.angle,rotationOriginX:c.cx,rotationOriginY:c.cy});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!d}super.redraw(a)}setYRadius(a){const c=this.annotation.userOptions.shapes;this.options.ry=a;c&&c[0]&&(c[0].ry=a,c[0].ry=a)}}d.attrsMap=f(l.attrsMap,{ry:"ry"});return d});r(b,"Extensions/Annotations/Controllables/ControllableLabel.js",
[b["Extensions/Annotations/Controllables/Controllable.js"],b["Core/Templating.js"],b["Extensions/Annotations/MockPoint.js"],b["Core/Utilities.js"]],function(b,l,h,f){function k(a,d,b,g,f){const e=f&&f.anchorX;f=f&&f.anchorY;let m,p,h=b/2;c(e)&&c(f)&&(m=[["M",e,f]],p=d-f,0>p&&(p=-g-p),p<b&&(h=e<a+b/2?p:b-p),f>d+g?m.push(["L",a+h,d+g]):f<d?m.push(["L",a+h,d]):e<a?m.push(["L",a,d+g/2]):e>a+b&&m.push(["L",a+b,d+g/2]));return m||[]}const {format:d}=l,{extend:a,isNumber:c,pick:g}=f,q=[];class v extends b{static alignedPosition(a,
c){const d=a.align,b=a.verticalAlign;let e=(c.x||0)+(a.x||0),m=(c.y||0)+(a.y||0),g,f;"right"===d?g=1:"center"===d&&(g=2);g&&(e+=(c.width-(a.width||0))/g);"bottom"===b?f=1:"middle"===b&&(f=2);f&&(m+=(c.height-(a.height||0))/f);return{x:Math.round(e),y:Math.round(m)}}static compose(a){f.pushUnique(q,a)&&(a.prototype.symbols.connector=k)}static justifiedOptions(a,c,d,b){const e=d.align,g=d.verticalAlign,m=c.box?0:c.padding||0,f=c.getBBox();c={align:e,verticalAlign:g,x:d.x,y:d.y,width:c.width,height:c.height};
d=(b.x||0)-a.plotLeft;b=(b.y||0)-a.plotTop;let h;h=d+m;0>h&&("right"===e?c.align="left":c.x=(c.x||0)-h);h=d+f.width-m;h>a.plotWidth&&("left"===e?c.align="right":c.x=(c.x||0)+a.plotWidth-h);h=b+m;0>h&&("bottom"===g?c.verticalAlign="top":c.y=(c.y||0)-h);h=b+f.height-m;h>a.plotHeight&&("top"===g?c.verticalAlign="bottom":c.y=(c.y||0)+a.plotHeight-h);return c}constructor(a,c,d){super(a,c,d,"label")}translatePoint(a,c){super.translatePoint(a,c,0)}translate(a,c){var d=this.annotation.chart;const b=this.annotation.userOptions;
var e=d.annotations.indexOf(this.annotation);e=d.options.annotations[e];d.inverted&&(d=a,a=c,c=d);this.options.x+=a;this.options.y+=c;e[this.collection][this.index].x=this.options.x;e[this.collection][this.index].y=this.options.y;b[this.collection][this.index].x=this.options.x;b[this.collection][this.index].y=this.options.y}render(a){const c=this.options,d=this.attrsFromOptions(c),b=c.style;this.graphic=this.annotation.chart.renderer.label("",0,-9999,c.shape,null,null,c.useHTML,null,"annotation-label").attr(d).add(a);
this.annotation.chart.styledMode||("contrast"===b.color&&(b.color=this.annotation.chart.renderer.getContrast(-1<v.shapesWithoutBackground.indexOf(c.shape)?"#FFFFFF":c.backgroundColor)),this.graphic.css(c.style).shadow(c.shadow));c.className&&this.graphic.addClass(c.className);this.graphic.labelrank=c.labelrank;super.render()}redraw(a){var c=this.options,b=this.text||c.format||c.text;const e=this.graphic,g=this.points[0];e?(e.attr({text:b?d(String(b),g.getLabelConfig(),this.annotation.chart):c.formatter.call(g,
this)}),c=this.anchor(g),(b=this.position(c))?(e.alignAttr=b,b.anchorX=c.absolutePosition.x,b.anchorY=c.absolutePosition.y,e[a?"animate":"attr"](b)):e.attr({x:0,y:-9999}),e.placed=!!b,super.redraw(a)):this.redraw(a)}anchor(a){const c=super.anchor.apply(this,arguments),d=this.options.x||0,b=this.options.y||0;c.absolutePosition.x-=d;c.absolutePosition.y-=b;c.relativePosition.x-=d;c.relativePosition.y-=b;return c}position(c){var d=this.graphic;const b=this.annotation.chart;var e=b.tooltip;const f=this.points[0];
var k=this.options;const l=c.absolutePosition,p=c.relativePosition;let q;c=f.series.visible&&h.prototype.isInsidePlot.call(f);if(d&&c){const {width:h=0,height:m=0}=d;k.distance&&e?q=e.getPosition.call({chart:b,distance:g(k.distance,16),getPlayingField:e.getPlayingField},h,m,{plotX:p.x,plotY:p.y,negative:f.negative,ttBelow:f.ttBelow,h:p.height||p.width}):k.positioner?q=k.positioner.call(this):(e={x:l.x,y:l.y,width:0,height:0},q=v.alignedPosition(a(k,{width:h,height:m}),e),"justify"===this.options.overflow&&
(q=v.alignedPosition(v.justifiedOptions(b,d,k,q),e)));k.crop&&(d=q.x-b.plotLeft,k=q.y-b.plotTop,c=b.isInsidePlot(d,k)&&b.isInsidePlot(d+h,k+m))}return c?q:null}}v.attrsMap={backgroundColor:"fill",borderColor:"stroke",borderWidth:"stroke-width",zIndex:"zIndex",borderRadius:"r",padding:"padding"};v.shapesWithoutBackground=["connector"];return v});r(b,"Extensions/Annotations/Controllables/ControllableImage.js",[b["Extensions/Annotations/Controllables/Controllable.js"],b["Extensions/Annotations/Controllables/ControllableLabel.js"]],
function(b,l){class h extends b{constructor(b,h,d){super(b,h,d,"shape");this.type="image";this.translate=super.translateShape}render(b){const f=this.attrsFromOptions(this.options),d=this.options;this.graphic=this.annotation.chart.renderer.image(d.src,0,-9E9,d.width,d.height).attr(f).add(b);this.graphic.width=d.width;this.graphic.height=d.height;super.render()}redraw(b){if(this.graphic){var f=this.anchor(this.points[0]);if(f=l.prototype.position.call(this,f))this.graphic[b?"animate":"attr"]({x:f.x,
y:f.y});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!f}super.redraw(b)}}h.attrsMap={width:"width",height:"height",zIndex:"zIndex"};return h});r(b,"Core/Chart/ChartNavigationComposition.js",[],function(){var b;(function(b){b.compose=function(b){b.navigation||(b.navigation=new h(b));return b};class h{constructor(b){this.updates=[];this.chart=b}addUpdate(b){this.chart.navigation.updates.push(b)}update(b,h){this.updates.forEach(d=>{d.call(this.chart,b,h)})}}b.Additions=h})(b||(b={}));return b});
r(b,"Extensions/Annotations/NavigationBindingsUtilities.js",[b["Core/Utilities.js"]],function(b){const {defined:l,isNumber:h,pick:f}=b,k={backgroundColor:"string",borderColor:"string",borderRadius:"string",color:"string",fill:"string",fontSize:"string",labels:"string",name:"string",stroke:"string",title:"string"};return{annotationsFieldsTypes:k,getAssignedAxis:function(d){return d.filter(a=>{var c=a.axis.getExtremes();const d=c.min;c=c.max;const b=f(a.axis.minPointOffset,0);return h(d)&&h(c)&&a.value>=
d-b&&a.value<=c+b&&!a.axis.options.isInternal})[0]},getFieldType:function(d,a){d=k[d];a=typeof a;l(d)&&(a=d);return{string:"text",number:"number","boolean":"checkbox"}[a]}}});r(b,"Extensions/Annotations/NavigationBindingsDefaults.js",[b["Extensions/Annotations/NavigationBindingsUtilities.js"],b["Core/Utilities.js"]],function(b,l){const {getAssignedAxis:h}=b,{isNumber:f,merge:k}=l;return{lang:{navigation:{popup:{simpleShapes:"Simple shapes",lines:"Lines",circle:"Circle",ellipse:"Ellipse",rectangle:"Rectangle",
label:"Label",shapeOptions:"Shape options",typeOptions:"Details",fill:"Fill",format:"Text",strokeWidth:"Line width",stroke:"Line color",title:"Title",name:"Name",labelOptions:"Label options",labels:"Labels",backgroundColor:"Background color",backgroundColors:"Background colors",borderColor:"Border color",borderRadius:"Border radius",borderWidth:"Border width",style:"Style",padding:"Padding",fontSize:"Font size",color:"Color",height:"Height",shapes:"Shape options"}}},navigation:{bindingsClassName:"highcharts-bindings-container",
bindings:{circleAnnotation:{className:"highcharts-circle-annotation",start:function(d){var a=this.chart.pointer.getCoordinates(d);d=h(a.xAxis);a=h(a.yAxis);const c=this.chart.options.navigation;if(d&&a)return this.chart.addAnnotation(k({langKey:"circle",type:"basicAnnotation",shapes:[{type:"circle",point:{x:d.value,y:a.value,xAxis:d.axis.index,yAxis:a.axis.index},r:5}]},c.annotationsOptions,c.bindings.circleAnnotation.annotationsOptions))},steps:[function(d,a){var c=a.options.shapes;c=c&&c[0]&&c[0].point||
{};if(f(c.xAxis)&&f(c.yAxis)){var b=this.chart.inverted;const a=this.chart.xAxis[c.xAxis].toPixels(c.x);c=this.chart.yAxis[c.yAxis].toPixels(c.y);b=Math.max(Math.sqrt(Math.pow(b?c-d.chartX:a-d.chartX,2)+Math.pow(b?a-d.chartY:c-d.chartY,2)),5)}a.update({shapes:[{r:b}]})}]},ellipseAnnotation:{className:"highcharts-ellipse-annotation",start:function(b){var a=this.chart.pointer.getCoordinates(b);b=h(a.xAxis);a=h(a.yAxis);const c=this.chart.options.navigation;if(b&&a)return this.chart.addAnnotation(k({langKey:"ellipse",
type:"basicAnnotation",shapes:[{type:"ellipse",xAxis:b.axis.index,yAxis:a.axis.index,points:[{x:b.value,y:a.value},{x:b.value,y:a.value}],ry:1}]},c.annotationsOptions,c.bindings.ellipseAnnotation.annotationOptions))},steps:[function(b,a){a=a.shapes[0];const c=a.getAbsolutePosition(a.points[1]);a.translatePoint(b.chartX-c.x,b.chartY-c.y,1);a.redraw(!1)},function(b,a){a=a.shapes[0];var c=a.getAbsolutePosition(a.points[0]);const d=a.getAbsolutePosition(a.points[1]);b=a.getDistanceFromLine(c,d,b.chartX,
b.chartY);c=a.getYAxis();b=Math.abs(c.toValue(0)-c.toValue(b));a.setYRadius(b);a.redraw(!1)}]},rectangleAnnotation:{className:"highcharts-rectangle-annotation",start:function(b){b=this.chart.pointer.getCoordinates(b);var a=h(b.xAxis),c=h(b.yAxis);if(a&&c){b=a.value;var d=c.value;a=a.axis.index;c=c.axis.index;var f=this.chart.options.navigation;return this.chart.addAnnotation(k({langKey:"rectangle",type:"basicAnnotation",shapes:[{type:"path",points:[{xAxis:a,yAxis:c,x:b,y:d},{xAxis:a,yAxis:c,x:b,y:d},
{xAxis:a,yAxis:c,x:b,y:d},{xAxis:a,yAxis:c,x:b,y:d},{command:"Z"}]}]},f.annotationsOptions,f.bindings.rectangleAnnotation.annotationsOptions))}},steps:[function(b,a){var c=a.options.shapes;c=c&&c[0]&&c[0].points||[];var d=this.chart.pointer.getCoordinates(b);b=h(d.xAxis);d=h(d.yAxis);b&&d&&(b=b.value,d=d.value,c[1].x=b,c[2].x=b,c[2].y=d,c[3].y=d,a.update({shapes:[{points:c}]}))}]},labelAnnotation:{className:"highcharts-label-annotation",start:function(b){var a=this.chart.pointer.getCoordinates(b);
b=h(a.xAxis);a=h(a.yAxis);const c=this.chart.options.navigation;if(b&&a)return this.chart.addAnnotation(k({langKey:"label",type:"basicAnnotation",labelOptions:{format:"{y:.2f}",overflow:"none",crop:!0},labels:[{point:{xAxis:b.axis.index,yAxis:a.axis.index,x:b.value,y:a.value}}]},c.annotationsOptions,c.bindings.labelAnnotation.annotationsOptions))}}},events:{},annotationsOptions:{animation:{defer:0}}}}});r(b,"Extensions/Annotations/NavigationBindings.js",[b["Core/Chart/ChartNavigationComposition.js"],
b["Core/Defaults.js"],b["Core/Templating.js"],b["Core/Globals.js"],b["Extensions/Annotations/NavigationBindingsDefaults.js"],b["Extensions/Annotations/NavigationBindingsUtilities.js"],b["Core/Utilities.js"]],function(b,l,h,f,k,d,a){function c(a,c){const b=p.Element.prototype,d=b.matches||b.msMatchesSelector||b.webkitMatchesSelector;let e=null;if(b.closest)e=b.closest.call(a,c);else{do{if(d.call(a,c))return a;a=a.parentElement||a.parentNode}while(null!==a&&1===a.nodeType)}return e}function g(){this.chart.navigationBindings&&
this.chart.navigationBindings.deselectAnnotation()}function q(){this.navigationBindings&&this.navigationBindings.destroy()}function v(){const a=this.options;a&&a.navigation&&a.navigation.bindings&&(this.navigationBindings=new I(this,a.navigation),this.navigationBindings.initEvents(),this.navigationBindings.initUpdate())}function e(){const a=this.navigationBindings;if(this&&a){let c=!1;this.series.forEach(a=>{!a.options.isInternal&&a.visible&&(c=!0)});if(this.navigationBindings&&this.navigationBindings.container&&
this.navigationBindings.container[0]){const b=this.navigationBindings.container[0];E(a.boundClassNames,(a,d)=>{if(d=b.querySelectorAll("."+d))for(let b=0;b<d.length;b++){const e=d[b],n=e.className;"normal"===a.noDataState?-1!==n.indexOf("highcharts-disabled-btn")&&e.classList.remove("highcharts-disabled-btn"):c?-1!==n.indexOf("highcharts-disabled-btn")&&e.classList.remove("highcharts-disabled-btn"):-1===n.indexOf("highcharts-disabled-btn")&&(e.className+=" highcharts-disabled-btn")}})}}}function m(){this.deselectAnnotation()}
function z(){this.selectedButtonElement=null}function A(a){function c(a){const c=this,d=c.chart.navigationBindings,e=d.activeAnnotation;b&&b.call(c,a);e!==c?(d.deselectAnnotation(),d.activeAnnotation=c,c.setControlPointsVisibility(!0),D(d,"showPopup",{annotation:c,formType:"annotation-toolbar",options:d.annotationToFields(c),onSubmit:function(a){if("remove"===a.actionType)d.activeAnnotation=!1,d.chart.removeAnnotation(c);else{const b={};d.fieldsToOptions(a.fields,b);d.deselectAnnotation();a=b.typeOptions;
"measure"===c.options.type&&(a.crosshairY.enabled=0!==a.crosshairY.strokeWidth,a.crosshairX.enabled=0!==a.crosshairX.strokeWidth);c.update(b)}}})):D(d,"closePopup");a.activeAnnotation=!0}const b=a.prototype.defaultOptions.events&&a.prototype.defaultOptions.events.click;let d,e;y(!0,a.prototype.defaultOptions.events,{click:c,touchstart:function(a){d=a.touches[0].clientX;e=a.touches[0].clientY},touchend:function(a){d&&4<=Math.sqrt(Math.pow(d-a.changedTouches[0].clientX,2)+Math.pow(e-a.changedTouches[0].clientY,
2))||c.call(this,a)}})}const {setOptions:u}=l,{format:F}=h,{doc:C,win:p}=f,{getFieldType:x}=d,{addEvent:w,attr:K,defined:r,fireEvent:D,isArray:H,isFunction:B,isNumber:n,isObject:t,merge:y,objectEach:E,pick:L}=a,J=[];class I{static compose(c,b){a.pushUnique(J,c)&&(w(c,"remove",g),A(c),E(c.types,a=>{A(a)}));a.pushUnique(J,b)&&(w(b,"destroy",q),w(b,"load",v),w(b,"render",e));a.pushUnique(J,I)&&(w(I,"closePopup",m),w(I,"deselectButton",z));a.pushUnique(J,u)&&u(k)}constructor(a,c){this.selectedButton=
this.boundClassNames=void 0;this.chart=a;this.options=c;this.eventsToUnbind=[];this.container=this.chart.container.getElementsByClassName(this.options.bindingsClassName||"");this.container.length||(this.container=C.getElementsByClassName(this.options.bindingsClassName||""))}initEvents(){const a=this,c=a.chart,b=a.container,d=a.options;a.boundClassNames={};E(d.bindings||{},c=>{a.boundClassNames[c.className]=c});[].forEach.call(b,c=>{a.eventsToUnbind.push(w(c,"click",b=>{const d=a.getButtonEvents(c,
b);d&&!d.button.classList.contains("highcharts-disabled-btn")&&a.bindingsButtonClick(d.button,d.events,b)}))});E(d.events||{},(c,b)=>{B(c)&&a.eventsToUnbind.push(w(a,b,c,{passive:!1}))});a.eventsToUnbind.push(w(c.container,"click",function(b){!c.cancelClick&&c.isInsidePlot(b.chartX-c.plotLeft,b.chartY-c.plotTop,{visiblePlotOnly:!0})&&a.bindingsChartClick(this,b)}));a.eventsToUnbind.push(w(c.container,f.isTouchDevice?"touchmove":"mousemove",function(c){a.bindingsContainerMouseMove(this,c)},f.isTouchDevice?
{passive:!1}:void 0))}initUpdate(){const a=this;b.compose(this.chart).navigation.addUpdate(c=>{a.update(c)})}bindingsButtonClick(a,c,b){const d=this.chart,e=d.renderer.boxWrapper;let n=!0;this.selectedButtonElement&&(this.selectedButtonElement.classList===a.classList&&(n=!1),D(this,"deselectButton",{button:this.selectedButtonElement}),this.nextEvent&&(this.currentUserDetails&&"annotations"===this.currentUserDetails.coll&&d.removeAnnotation(this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=
!1));n?(this.selectedButton=c,this.selectedButtonElement=a,D(this,"selectButton",{button:a}),c.init&&c.init.call(this,a,b),(c.start||c.steps)&&d.renderer.boxWrapper.addClass("highcharts-draw-mode")):(d.stockTools&&d.stockTools.toggleButtonActiveClass(a),e.removeClass("highcharts-draw-mode"),this.mouseMoveEvent=this.nextEvent=!1,this.selectedButton=null)}bindingsChartClick(a,b){a=this.chart;const d=this.activeAnnotation,e=this.selectedButton;a=a.renderer.boxWrapper;d&&(d.cancelClick||b.activeAnnotation||
!b.target.parentNode||c(b.target,".highcharts-popup")?d.cancelClick&&setTimeout(()=>{d.cancelClick=!1},0):D(this,"closePopup"));e&&e.start&&(this.nextEvent?(this.nextEvent(b,this.currentUserDetails),this.steps&&(this.stepIndex++,e.steps[this.stepIndex]?this.mouseMoveEvent=this.nextEvent=e.steps[this.stepIndex]:(D(this,"deselectButton",{button:this.selectedButtonElement}),a.removeClass("highcharts-draw-mode"),e.end&&e.end.call(this,b,this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1,this.selectedButton=
null))):(this.currentUserDetails=e.start.call(this,b))&&e.steps?(this.stepIndex=0,this.steps=!0,this.mouseMoveEvent=this.nextEvent=e.steps[this.stepIndex]):(D(this,"deselectButton",{button:this.selectedButtonElement}),a.removeClass("highcharts-draw-mode"),this.steps=!1,this.selectedButton=null,e.end&&e.end.call(this,b,this.currentUserDetails)))}bindingsContainerMouseMove(a,c){this.mouseMoveEvent&&this.mouseMoveEvent(c,this.currentUserDetails)}fieldsToOptions(a,c){E(a,(a,b)=>{const d=parseFloat(a),
e=b.split("."),t=e.length-1;!n(d)||a.match(/px|em/g)||b.match(/format/g)||(a=d);if("undefined"!==a){let b=c;e.forEach((c,d)=>{const n=L(e[d+1],"");t===d?b[c]=a:(b[c]||(b[c]=n.match(/\d/g)?[]:{}),b=b[c])})}});return c}deselectAnnotation(){this.activeAnnotation&&(this.activeAnnotation.setControlPointsVisibility(!1),this.activeAnnotation=!1)}annotationToFields(a){function c(b,d,n,f,h){let y;n&&r(b)&&-1===g.indexOf(d)&&(0<=(n.indexOf&&n.indexOf(d))||n[d]||!0===n)&&(H(b)?(f[d]=[],b.forEach((a,b)=>{t(a)?
(f[d][b]={},E(a,(a,n)=>{c(a,n,e[d],f[d][b],d)})):c(a,0,e[d],f[d],d)})):t(b)?(y={},H(f)?(f.push(y),y[d]={},y=y[d]):f[d]=y,E(b,(a,b)=>{c(a,b,0===d?n:e[d],y,d)})):"format"===d?f[d]=[F(b,a.labels[0].points[0]).toString(),"text"]:H(f)?f.push([b,x(h,b)]):f[d]=[b,x(d,b)])}const b=a.options,d=I.annotationsEditable,e=d.nestedOptions,n=L(b.type,b.shapes&&b.shapes[0]&&b.shapes[0].type,b.labels&&b.labels[0]&&b.labels[0].type,"label"),g=I.annotationsNonEditable[b.langKey]||[],f={langKey:b.langKey,type:n};E(b,
(a,t)=>{"typeOptions"===t?(f[t]={},E(b[t],(a,b)=>{c(a,b,e,f[t],b)})):c(a,t,d[n],f,t)});return f}getClickedClassNames(a,c){let b=c.target;c=[];let d;for(;b&&b.tagName&&((d=K(b,"class"))&&(c=c.concat(d.split(" ").map(a=>[a,b]))),b=b.parentNode,b!==a););return c}getButtonEvents(a,b){const c=this;let d;this.getClickedClassNames(a,b).forEach(a=>{c.boundClassNames[a[0]]&&!d&&(d={events:c.boundClassNames[a[0]],button:a[1]})});return d}update(a){this.options=y(!0,this.options,a);this.removeEvents();this.initEvents()}removeEvents(){this.eventsToUnbind.forEach(a=>
a())}destroy(){this.removeEvents()}}I.annotationsEditable={nestedOptions:{labelOptions:["style","format","backgroundColor"],labels:["style"],label:["style"],style:["fontSize","color"],background:["fill","strokeWidth","stroke"],innerBackground:["fill","strokeWidth","stroke"],outerBackground:["fill","strokeWidth","stroke"],shapeOptions:["fill","strokeWidth","stroke"],shapes:["fill","strokeWidth","stroke"],line:["strokeWidth","stroke"],backgroundColors:[!0],connector:["fill","strokeWidth","stroke"],
crosshairX:["strokeWidth","stroke"],crosshairY:["strokeWidth","stroke"]},circle:["shapes"],ellipse:["shapes"],verticalLine:[],label:["labelOptions"],measure:["background","crosshairY","crosshairX"],fibonacci:[],tunnel:["background","line","height"],pitchfork:["innerBackground","outerBackground"],rect:["shapes"],crookedLine:[],basicAnnotation:["shapes","labelOptions"]};I.annotationsNonEditable={rectangle:["crosshairX","crosshairY","labelOptions"],ellipse:["labelOptions"],circle:["labelOptions"]};"";
return I});r(b,"Shared/BaseForm.js",[b["Core/Renderer/HTML/AST.js"],b["Core/Utilities.js"]],function(b,l){const {addEvent:h,createElement:f}=l;class k{constructor(b,a){this.iconsURL=a;this.container=this.createPopupContainer(b);this.closeButton=this.addCloseButton()}createPopupContainer(b,a="highcharts-popup highcharts-no-tooltip"){return f("div",{className:a},void 0,b)}addCloseButton(b="highcharts-popup-close"){const a=this,c=this.iconsURL,d=f("div",{className:b},void 0,this.container);d.style["background-image"]=
"url("+(c.match(/png|svg|jpeg|jpg|gif/ig)?c:c+"close.svg")+")";["click","touchstart"].forEach(b=>{h(d,b,a.closeButtonEvents.bind(a))});return d}closeButtonEvents(){this.closePopup()}showPopup(d="highcharts-annotation-toolbar"){const a=this.container,c=this.closeButton;this.type=void 0;a.innerHTML=b.emptyHTML;0<=a.className.indexOf(d)&&(a.classList.remove(d),a.removeAttribute("style"));a.appendChild(c);a.style.display="block";a.style.height=""}closePopup(){this.container.style.display="none"}}return k});
r(b,"Extensions/Annotations/Popup/PopupAnnotations.js",[b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,l){function h(b,m,l,q,u,F){if(m){var e=this.addInput,p=this.lang,x,w;g(q,(d,e)=>{x=""!==l?l+"."+e:e;c(d)&&(!a(d)||a(d)&&c(d[0])?(w=p[e]||e,w.match(/\d/g)||u.push([!0,w,b]),h.call(this,b,m,x,d,u,!1)):u.push([this,x,"annotation",b,d]))});F&&(v(u,a=>a[1].match(/format/g)?-1:1),k&&u.reverse(),u.forEach(a=>{!0===a[0]?d("span",{className:"highcharts-annotation-title"},void 0,a[2]).appendChild(f.createTextNode(a[1])):
(a[4]={value:a[4][0],type:a[4][1]},e.apply(a[0],a.splice(1)))}))}}const {doc:f,isFirefox:k}=b,{createElement:d,isArray:a,isObject:c,objectEach:g,pick:q,stableSort:v}=l;return{addForm:function(a,b,c,g){if(a){var e=this.container,m=this.lang,k=d("h2",{className:"highcharts-popup-main-title"},void 0,e);k.appendChild(f.createTextNode(m[b.langKey]||b.langKey||""));k=d("div",{className:"highcharts-popup-lhs-col highcharts-popup-lhs-full"},void 0,e);var p=d("div",{className:"highcharts-popup-bottom-row"},
void 0,e);h.call(this,k,a,"",b,[],!0);this.addButton(p,g?m.addButton||"Add":m.saveButton||"Save",g?"add":"save",e,c)}},addToolbar:function(a,b,c){const e=this.lang,g=this.container,h=this.showForm;-1===g.className.indexOf("highcharts-annotation-toolbar")&&(g.className+=" highcharts-annotation-toolbar");a&&(g.style.top=a.plotTop+10+"px");d("span",void 0,void 0,g).appendChild(f.createTextNode(q(e[b.langKey]||b.langKey,b.shapes&&b.shapes[0].type,"")));let k=this.addButton(g,e.removeButton||"Remove",
"remove",g,c);k.className+=" highcharts-annotation-remove-button";k.style["background-image"]="url("+this.iconsURL+"destroy.svg)";k=this.addButton(g,e.editButton||"Edit","edit",g,()=>{h.call(this,"annotation-edit",a,b,c)});k.className+=" highcharts-annotation-edit-button";k.style["background-image"]="url("+this.iconsURL+"edit.svg)"}}});r(b,"Extensions/Annotations/Popup/PopupIndicators.js",[b["Core/Renderer/HTML/AST.js"],b["Core/Globals.js"],b["Extensions/Annotations/NavigationBindingsUtilities.js"],
b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,l,h,f,k){function d(a){const b=p("div",{className:"highcharts-popup-lhs-col"},void 0,a);a=p("div",{className:"highcharts-popup-rhs-col"},void 0,a);p("div",{className:"highcharts-popup-rhs-col-wrapper"},void 0,a);return{lhsCol:b,rhsCol:a}}function a(a,d,f,g){const n=this,t=n.lang,h=d.querySelectorAll(".highcharts-popup-lhs-col")[0];d=d.querySelectorAll(".highcharts-popup-rhs-col")[0];const y="edit"===f;f=y?a.series:a.options.plotOptions||
{};if(a||!f){var k,l=[];y||w(f)?w(f)&&(l=m.call(this,f)):l=e.call(this,f,g);D(l,(a,b)=>{a=a.indicatorFullName.toLowerCase();b=b.indicatorFullName.toLowerCase();return a<b?-1:a>b?1:0});h.children[1]&&h.children[1].remove();var E=p("ul",{className:"highcharts-indicator-list"},void 0,h),q=d.querySelectorAll(".highcharts-popup-rhs-col-wrapper")[0];l.forEach(d=>{const {indicatorFullName:e,indicatorType:f,series:g}=d;k=p("li",{className:"highcharts-indicator-list"},void 0,E);k.appendChild(u.createTextNode(e));
["click","touchstart"].forEach(d=>{C(k,d,function(){const d=q.parentNode.children[1];{const d=g.params||g.options.params;q.innerHTML=b.emptyHTML;p("h3",{className:"highcharts-indicator-title"},void 0,q).appendChild(u.createTextNode(r(g,f).indicatorFullName));p("input",{type:"hidden",name:"highcharts-type-"+f,value:f},void 0,q);A.call(n,f,"series",a,q,g,g.linkedParent&&g.linkedParent.options.id);d.volumeSeriesID&&A.call(n,f,"volume",a,q,g,g.linkedParent&&d.volumeSeriesID);c.call(n,a,"params",d,f,q)}d&&
(d.style.display="block");y&&g.options&&p("input",{type:"hidden",name:"highcharts-id-"+f,value:g.options.id},void 0,q).setAttribute("highcharts-data-series-id",g.options.id)})})});0<E.childNodes.length?E.childNodes[0].click():y||(b.setElementHTML(q.parentNode.children[0],t.noFilterMatch||""),q.parentNode.children[1].style.display="none")}}function c(a,b,d,e,f){if(a){var n=this.addInput;G(d,(d,g)=>{var t=b+"."+g;x(d)&&t&&(K(d)&&(n.call(this,t,e,f,{}),c.call(this,a,t,d,e,f)),t in H?(t=q.call(this,e,
t,f),v.call(this,a,b,t,e,g,d)):"params.volumeSeriesID"===t||w(d)||n.call(this,t,e,f,{value:d,type:"number"}))})}}function g(b,c){const d=this;var e=c.querySelectorAll(".highcharts-popup-lhs-col")[0];c=this.lang.clearFilter;e=p("div",{className:"highcharts-input-wrapper"},void 0,e);const n=this.addInput("searchIndicators","input",e,{value:"",type:"text",htmlFor:"search-indicators",labelClassName:"highcharts-input-search-indicators-label"}),f=p("a",{textContent:c},void 0,e);n.classList.add("highcharts-input-search-indicators");
f.classList.add("clear-filter-button");C(n,"input",function(){a.call(d,b,d.container,"add",this.value);f.style.display=this.value.length?"inline-block":"none"});["click","touchstart"].forEach(c=>{C(f,c,function(){n.value="";a.call(d,b,d.container,"add","");f.style.display="none"})})}function q(a,b,c){var d=b.split(".");d=d[d.length-1];a="highcharts-"+b+"-type-"+a;const e=this.lang;p("label",{htmlFor:a},null,c).appendChild(u.createTextNode(e[d]||b));c=p("select",{name:a,className:"highcharts-popup-field",
id:"highcharts-select-"+b},null,c);c.setAttribute("id","highcharts-select-"+b);return c}function v(a,b,c,d,e,f,g){"series"===b||"volume"===b?a.series.forEach(a=>{const d=a.options,e=d.name||d.params?a.name:d.id||"";"highcharts-navigator-series"!==d.id&&d.id!==(g&&g.options&&g.options.id)&&(x(f)||"volume"!==b||"column"!==a.type||(f=d.id),p("option",{value:d.id},void 0,c).appendChild(u.createTextNode(e)))}):d&&e&&B[e+"-"+d].forEach(a=>{p("option",{value:a},void 0,c).appendChild(u.createTextNode(a))});
x(f)&&(c.value=f)}function e(a,b){const c=this.chart&&this.chart.options.lang,d=c&&c.navigation&&c.navigation.popup&&c.navigation.popup.indicatorAliases,e=[];let n;G(a,(a,c)=>{var f=a&&a.options;if(a.params||f&&f.params){const {indicatorFullName:g,indicatorType:t}=r(a,c);if(b){if(c=b.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),c=new RegExp(c,"i"),f=d&&d[t]&&d[t].join(" ")||"",g.match(c)||f.match(c))n={indicatorFullName:g,indicatorType:t,series:a},e.push(n)}else n={indicatorFullName:g,indicatorType:t,series:a},
e.push(n)}});return e}function m(a){const b=[];a.forEach(a=>{a.is("sma")&&b.push({indicatorFullName:a.name,indicatorType:a.type,series:a})});return b}function r(a,b){const c=a.options;let d=F[b]&&F[b].prototype.nameBase||b.toUpperCase();c&&c.type&&(b=a.options.type,d=a.name);return{indicatorFullName:d,indicatorType:b}}function A(a,b,c,d,e,f){c&&(a=q.call(this,a,b,d),v.call(this,c,b,a,void 0,void 0,void 0,e),x(f)&&(a.value=f))}const {doc:u}=l,{seriesTypes:F}=f,{addEvent:C,createElement:p,defined:x,
isArray:w,isObject:K,objectEach:G,stableSort:D}=k;var H;(function(a){a[a["params.algorithm"]=0]="params.algorithm";a[a["params.average"]=1]="params.average"})(H||(H={}));const B={"algorithm-pivotpoints":["standard","fibonacci","camarilla"],"average-disparityindex":["sma","ema","dema","tema","wma"]};return{addForm:function(b,c,e){c=this.lang;let f;if(b){this.tabs.init.call(this,b);var n=this.container.querySelectorAll(".highcharts-tab-item-content");d(n[0]);g.call(this,b,n[0]);a.call(this,b,n[0],"add");
f=n[0].querySelectorAll(".highcharts-popup-rhs-col")[0];this.addButton(f,c.addButton||"add","add",f,e);d(n[1]);a.call(this,b,n[1],"edit");f=n[1].querySelectorAll(".highcharts-popup-rhs-col")[0];this.addButton(f,c.saveButton||"save","edit",f,e);this.addButton(f,c.removeButton||"remove","remove",f,e)}},getAmount:function(){let a=0;this.series.forEach(b=>{(b.params||b.options.params)&&a++});return a}}});r(b,"Extensions/Annotations/Popup/PopupTabs.js",[b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,
l){function h(){return g("div",{className:"highcharts-tab-item-content highcharts-no-mousewheel"},void 0,this.container)}function f(b,c){const d=this.container,f=this.lang;let h="highcharts-tab-item";0===c&&(h+=" highcharts-tab-disabled");c=g("span",{className:h},void 0,d);c.appendChild(a.createTextNode(f[b+"Button"]||b));c.setAttribute("highcharts-data-tab-type",b);return c}function k(a,b){const c=this.container.querySelectorAll(".highcharts-tab-item-content");a.className+=" highcharts-tab-item-active";
c[b].className+=" highcharts-tab-item-show"}function d(a){const b=this;this.container.querySelectorAll(".highcharts-tab-item").forEach((d,f)=>{0===a&&"edit"===d.getAttribute("highcharts-data-tab-type")||["click","touchstart"].forEach(a=>{c(d,a,function(){{var a=b.container;const c=a.querySelectorAll(".highcharts-tab-item");a=a.querySelectorAll(".highcharts-tab-item-content");for(let b=0;b<c.length;b++)c[b].classList.remove("highcharts-tab-item-active"),a[b].classList.remove("highcharts-tab-item-show")}k.call(b,
this,f)})})})}const {doc:a}=b,{addEvent:c,createElement:g}=l;return{init:function(a){if(a){a=this.indicators.getAmount.call(a);var b=f.call(this,"add");f.call(this,"edit",a);h.call(this);h.call(this);d.call(this,a);k.call(this,b,0)}}}});r(b,"Extensions/Annotations/Popup/Popup.js",[b["Shared/BaseForm.js"],b["Core/Globals.js"],b["Core/Defaults.js"],b["Extensions/Annotations/Popup/PopupAnnotations.js"],b["Extensions/Annotations/Popup/PopupIndicators.js"],b["Extensions/Annotations/Popup/PopupTabs.js"],
b["Core/Utilities.js"]],function(b,l,h,f,k,d,a){function c(a,b){const c=Array.prototype.slice.call(a.querySelectorAll("input")),d=Array.prototype.slice.call(a.querySelectorAll("select")),e=a.querySelectorAll("#highcharts-select-series > option:checked")[0];a=a.querySelectorAll("#highcharts-select-volume > option:checked")[0];const f={actionType:b,linkedTo:e&&e.getAttribute("value")||"",fields:{}};c.forEach(a=>{const b=a.getAttribute("highcharts-data-name");a.getAttribute("highcharts-data-series-id")?
f.seriesId=a.value:b?f.fields[b]=a.value:f.type=a.value});d.forEach(a=>{var b=a.id;"highcharts-select-series"!==b&&"highcharts-select-volume"!==b&&(b=b.split("highcharts-select-")[1],f.fields[b]=a.value)});a&&(f.fields["params.volumeSeriesID"]=a.getAttribute("value")||"");return f}const {doc:g}=l,{getOptions:q}=h,{addEvent:r,createElement:e,extend:m,fireEvent:z,pick:A}=a;class u extends b{constructor(a,b,c){super(a,b);this.chart=c;this.lang=(q().lang.navigation||{}).popup||{};r(this.container,"mousedown",
()=>{const a=c&&c.navigationBindings&&c.navigationBindings.activeAnnotation;if(a){a.cancelClick=!0;const b=r(g,"click",()=>{setTimeout(()=>{a.cancelClick=!1},0);b()})}})}addInput(a,b,c,d){var f=a.split(".");f=f[f.length-1];const h=this.lang;b="highcharts-"+b+"-"+A(d.htmlFor,f);f.match(/^\d+$/)||e("label",{htmlFor:b,className:d.labelClassName},void 0,c).appendChild(g.createTextNode(h[f]||f));c=e("input",{name:b,value:d.value,type:d.type,className:"highcharts-popup-field"},void 0,c);c.setAttribute("highcharts-data-name",
a);return c}closeButtonEvents(){if(this.chart){const a=this.chart.navigationBindings;z(a,"closePopup");a&&a.selectedButtonElement&&z(a,"deselectButton",{button:a.selectedButtonElement})}else super.closeButtonEvents()}addButton(a,b,d,f,h){const k=e("button",void 0,void 0,a);k.appendChild(g.createTextNode(b));h&&["click","touchstart"].forEach(a=>{r(k,a,()=>{this.closePopup();return h(c(f,d))})});return k}showForm(a,b,c,d){b&&(this.showPopup(),"indicators"===a&&this.indicators.addForm.call(this,b,c,
d),"annotation-toolbar"===a&&this.annotations.addToolbar.call(this,b,c,d),"annotation-edit"===a&&this.annotations.addForm.call(this,b,c,d),"flag"===a&&this.annotations.addForm.call(this,b,c,d,!0),this.type=a,this.container.style.height=this.container.offsetHeight+"px")}}m(u.prototype,{annotations:f,indicators:k,tabs:d});return u});r(b,"Extensions/Annotations/Popup/PopupComposition.js",[b["Extensions/Annotations/Popup/Popup.js"],b["Core/Utilities.js"]],function(b,l){function h(){this.popup&&this.popup.closePopup()}
function f(a){this.popup||(this.popup=new b(this.chart.container,this.chart.options.navigation.iconsURL||this.chart.options.stockTools&&this.chart.options.stockTools.gui.iconsURL||"https://code.highcharts.com/11.1.0/gfx/stock-icons/",this.chart));this.popup.showForm(a.formType,this.chart,a.options,a.onSubmit)}function k(a,b){this.inClass(b.target,"highcharts-popup")||a.apply(this,Array.prototype.slice.call(arguments,1))}const {addEvent:d,wrap:a}=l,c=[];return{compose:function(b,q){l.pushUnique(c,
b)&&(d(b,"closePopup",h),d(b,"showPopup",f));l.pushUnique(c,q)&&a(q.prototype,"onContainerMouseDown",k)}}});r(b,"Extensions/Annotations/Annotation.js",[b["Core/Animation/AnimationUtilities.js"],b["Extensions/Annotations/AnnotationChart.js"],b["Extensions/Annotations/AnnotationDefaults.js"],b["Extensions/Annotations/Controllables/ControllableRect.js"],b["Extensions/Annotations/Controllables/ControllableCircle.js"],b["Extensions/Annotations/Controllables/ControllableEllipse.js"],b["Extensions/Annotations/Controllables/ControllablePath.js"],
b["Extensions/Annotations/Controllables/ControllableImage.js"],b["Extensions/Annotations/Controllables/ControllableLabel.js"],b["Extensions/Annotations/ControlPoint.js"],b["Extensions/Annotations/ControlTarget.js"],b["Extensions/Annotations/EventEmitter.js"],b["Extensions/Annotations/MockPoint.js"],b["Extensions/Annotations/NavigationBindings.js"],b["Extensions/Annotations/Popup/PopupComposition.js"],b["Core/Utilities.js"]],function(b,l,h,f,k,d,a,c,g,q,r,e,m,z,A,u){function v(a){const b=a.graphic;
a=a.points.some(a=>!1!==a.series.visible&&!1!==a.visible);b&&(a?"hidden"===b.visibility&&b.show():b.hide())}function C(a,b){const c={};["labels","shapes"].forEach(d=>{const e=a[d];e&&(c[d]=b[d]?M(b[d]).map(function(a,b){return G(e[b],a)}):a[d])});return c}const {getDeferredAnimation:p}=b,{destroyObjectProperties:x,erase:w,fireEvent:H,merge:G,pick:D,splat:M}=u;class B extends e{static compose(b,c,d){l.compose(B,b,c);g.compose(d);a.compose(b,d);z.compose(B,b);A.compose(z,c)}constructor(a,b){super();
this.shapesGroup=this.labelsGroup=this.labelCollector=this.group=this.graphic=this.animationConfig=void 0;this.chart=a;this.points=[];this.controlPoints=[];this.coll="annotations";this.index=-1;this.labels=[];this.shapes=[];this.options=G(this.defaultOptions,b);this.userOptions=b;b=C(this.options,b);this.options.labels=b.labels;this.options.shapes=b.shapes;this.init(a,this.options)}addClipPaths(){this.setClipAxes();this.clipXAxis&&this.clipYAxis&&this.options.crop&&(this.clipRect=this.chart.renderer.clipRect(this.getClipBox()))}addLabels(){const a=
this.options.labels||[];a.forEach((b,c)=>{b=this.initLabel(b,c);G(!0,a[c],b.options)})}addShapes(){const a=this.options.shapes||[];a.forEach((b,c)=>{b=this.initShape(b,c);G(!0,a[c],b.options)})}destroy(){function a(a){a.destroy()}const b=this.chart;this.labels.forEach(a);this.shapes.forEach(a);this.clipYAxis=this.clipXAxis=null;w(b.labelCollectors,this.labelCollector);super.destroy();this.destroyControlTarget();x(this,b)}destroyItem(a){w(this[a.itemType+"s"],a);a.destroy()}getClipBox(){if(this.clipXAxis&&
this.clipYAxis)return{x:this.clipXAxis.left,y:this.clipYAxis.top,width:this.clipXAxis.width,height:this.clipYAxis.height}}initProperties(a,b){this.setOptions(b);const c=C(this.options,b);this.options.labels=c.labels;this.options.shapes=c.shapes;this.chart=a;this.points=[];this.controlPoints=[];this.coll="annotations";this.userOptions=b;this.labels=[];this.shapes=[]}init(a,b,c=this.index){a=this.chart;b=this.options.animation;this.index=c;this.linkPoints();this.addControlPoints();this.addShapes();
this.addLabels();this.setLabelCollector();this.animationConfig=p(a,b)}initLabel(a,b){a=G(this.options.labelOptions,{controlPointOptions:this.options.controlPointOptions},a);b=new g(this,a,b);b.itemType="label";this.labels.push(b);return b}initShape(a,b){a=G(this.options.shapeOptions,{controlPointOptions:this.options.controlPointOptions},a);b=new B.shapesMap[a.type](this,a,b);b.itemType="shape";this.shapes.push(b);return b}redraw(a){this.linkPoints();this.graphic||this.render();this.clipRect&&this.clipRect.animate(this.getClipBox());
this.redrawItems(this.shapes,a);this.redrawItems(this.labels,a);this.redrawControlPoints(a)}redrawItem(a,b){a.linkPoints();a.shouldBeDrawn()?(a.graphic||this.renderItem(a),a.redraw(D(b,!0)&&a.graphic.placed),a.points.length&&v(a)):this.destroyItem(a)}redrawItems(a,b){let c=a.length;for(;c--;)this.redrawItem(a[c],b)}remove(){return this.chart.removeAnnotation(this)}render(){const a=this.chart.renderer;this.graphic=a.g("annotation").attr({opacity:0,zIndex:this.options.zIndex,visibility:this.options.visible?
"inherit":"hidden"}).add();this.shapesGroup=a.g("annotation-shapes").add(this.graphic);this.options.crop&&this.shapesGroup.clip(this.chart.plotBoxClip);this.labelsGroup=a.g("annotation-labels").attr({translateX:0,translateY:0}).add(this.graphic);this.addClipPaths();this.clipRect&&this.graphic.clip(this.clipRect);this.renderItems(this.shapes);this.renderItems(this.labels);this.addEvents();this.renderControlPoints()}renderItem(a){a.render("label"===a.itemType?this.labelsGroup:this.shapesGroup)}renderItems(a){let b=
a.length;for(;b--;)this.renderItem(a[b])}setClipAxes(){const a=this.chart.xAxis,b=this.chart.yAxis,c=(this.options.labels||[]).concat(this.options.shapes||[]).reduce((c,d)=>{d=d&&(d.point||d.points&&d.points[0]);return[a[d&&d.xAxis]||c[0],b[d&&d.yAxis]||c[1]]},[]);this.clipXAxis=c[0];this.clipYAxis=c[1]}setControlPointsVisibility(a){function b(b){b.setControlPointsVisibility(a)}this.controlPoints.forEach(b=>{b.setVisibility(a)});this.shapes.forEach(b);this.labels.forEach(b)}setLabelCollector(){const a=
this;a.labelCollector=function(){return a.labels.reduce(function(a,b){b.options.allowOverlap||a.push(b.graphic);return a},[])};a.chart.labelCollectors.push(a.labelCollector)}setOptions(a){this.options=G(this.defaultOptions,a)}setVisibility(a){const b=this.options,c=this.chart.navigationBindings,d=D(a,!b.visible);this.graphic.attr("visibility",d?"inherit":"hidden");d||(a=function(a){a.setControlPointsVisibility(d)},this.shapes.forEach(a),this.labels.forEach(a),c.activeAnnotation===this&&c.popup&&"annotation-toolbar"===
c.popup.type&&H(c,"closePopup"));b.visible=d}update(a,b){const c=this.chart,d=C(this.userOptions,a),e=c.annotations.indexOf(this);a=G(!0,this.userOptions,a);a.labels=d.labels;a.shapes=d.shapes;this.destroy();this.initProperties(c,a);this.init(c,a);c.options.annotations[e]=a;this.isUpdating=!0;D(b,!0)&&c.redraw();H(this,"afterUpdate");this.isUpdating=!1}}B.ControlPoint=q;B.MockPoint=m;B.shapesMap={rect:f,circle:k,ellipse:d,path:a,image:c};B.types={};B.prototype.defaultOptions=h;B.prototype.nonDOMEvents=
["add","afterUpdate","drag","remove"];r.compose(B);"";return B});r(b,"masters/modules/annotations.src.js",[b["Core/Globals.js"],b["Extensions/Annotations/Annotation.js"]],function(b,l){b.Annotation=l;l.compose(b.Chart,b.Pointer,b.SVGRenderer)})});//# sourceMappingURL=annotations.js.map