/*
 Highcharts JS v11.1.0 (2023-08-20)

 Highcharts Drilldown module

 Author: Torstein Honsi
 License: www.highcharts.com/license

*/
'use strict';(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/drilldown",["highcharts"],function(l){a(l);a.Highcharts=l;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function l(a,r,h,l){a.hasOwnProperty(r)||(a[r]=l.apply(null,h),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:r,module:a[r]}})))}a=a?a._modules:
{};l(a,"Extensions/Breadcrumbs/BreadcrumbsDefaults.js",[],function(){return{lang:{mainBreadcrumb:"Main"},options:{buttonTheme:{fill:"none",height:18,padding:2,"stroke-width":0,zIndex:7,states:{select:{fill:"none"}},style:{color:"#334eff"}},buttonSpacing:5,floating:!1,format:void 0,relativeTo:"plotBox",rtl:!1,position:{align:"left",verticalAlign:"top",x:0,y:void 0},separator:{text:"/",style:{color:"#666666",fontSize:"0.8em"}},showFullPath:!0,style:{},useHTML:!1,zIndex:7}}});l(a,"Extensions/Breadcrumbs/Breadcrumbs.js",
[a["Extensions/Breadcrumbs/BreadcrumbsDefaults.js"],a["Core/Chart/Chart.js"],a["Core/Templating.js"],a["Core/Utilities.js"]],function(a,r,h,l){function v(){if(this.breadcrumbs){const f=this.resetZoomButton&&this.resetZoomButton.getBBox(),e=this.breadcrumbs.options;f&&"right"===e.position.align&&"plotBox"===e.relativeTo&&this.breadcrumbs.alignBreadcrumbsGroup(-f.width-e.buttonSpacing)}}function J(){this.breadcrumbs&&(this.breadcrumbs.destroy(),this.breadcrumbs=void 0)}function K(){const f=this.breadcrumbs;
if(f&&!f.options.floating&&f.level){var e=f.options,k=e.buttonTheme;k=(k.height||0)+2*(k.padding||0)+e.buttonSpacing;e=e.position.verticalAlign;"bottom"===e?(this.marginBottom=(this.marginBottom||0)+k,f.yOffset=k):"middle"!==e?(this.plotTop+=k,f.yOffset=-k):f.yOffset=void 0}}function w(){this.breadcrumbs&&this.breadcrumbs.redraw()}function G(f){!0===f.resetSelection&&this.breadcrumbs&&this.breadcrumbs.alignBreadcrumbsGroup()}const {format:L}=h,{addEvent:x,defined:H,extend:A,fireEvent:I,isString:Q,
merge:y,objectEach:D,pick:E}=l,z=[];class F{static compose(f,e){l.pushUnique(z,f)&&(x(r,"destroy",J),x(r,"afterShowResetZoom",v),x(r,"getMargins",K),x(r,"redraw",w),x(r,"selection",G));l.pushUnique(z,e)&&A(e.lang,a.lang)}constructor(f,e){this.elementList={};this.isDirty=!0;this.level=0;this.list=[];e=y(f.options.drilldown&&f.options.drilldown.drillUpButton,F.defaultOptions,f.options.navigation&&f.options.navigation.breadcrumbs,e);this.chart=f;this.options=e||{}}updateProperties(f){this.setList(f);
this.setLevel();this.isDirty=!0}setList(f){this.list=f}setLevel(){this.level=this.list.length&&this.list.length-1}getLevel(){return this.level}getButtonText(f){const e=this.chart,k=this.options;var a=e.options.lang;const q=E(k.format,k.showFullPath?"{level.name}":"\u2190 {level.name}");a=a&&E(a.drillUpText,a.mainBreadcrumb);f=k.formatter&&k.formatter(f)||L(q,{level:f.levelOptions},e)||"";(Q(f)&&!f.length||"\u2190 "===f)&&H(a)&&(f=k.showFullPath?a:"\u2190 "+a);return f}redraw(){this.isDirty&&this.render();
this.group&&this.group.align();this.isDirty=!1}render(){const f=this.chart,e=this.options;!this.group&&e&&(this.group=f.renderer.g("breadcrumbs-group").addClass("highcharts-no-tooltip highcharts-breadcrumbs").attr({zIndex:e.zIndex}).add());e.showFullPath?this.renderFullPathButtons():this.renderSingleButton();this.alignBreadcrumbsGroup()}renderFullPathButtons(){this.destroySingleButton();this.resetElementListState();this.updateListElements();this.destroyListElements()}renderSingleButton(){const f=
this.chart;var e=this.list;const a=this.options.buttonSpacing;this.destroyListElements();const g=this.group?this.group.getBBox().width:a;e=e[e.length-2];!f.drillUpButton&&0<this.level?f.drillUpButton=this.renderButton(e,g,a):f.drillUpButton&&(0<this.level?this.updateSingleButton():this.destroySingleButton())}alignBreadcrumbsGroup(f){if(this.group){var e=this.options;const k=e.buttonTheme,q=e.position,m="chart"===e.relativeTo||"spacingBox"===e.relativeTo?void 0:"scrollablePlotBox";var a=this.group.getBBox();
e=2*(k.padding||0)+e.buttonSpacing;q.width=a.width+e;q.height=a.height+e;a=y(q);f&&(a.x+=f);this.options.rtl&&(a.x+=q.width);a.y=E(a.y,this.yOffset,0);this.group.align(a,!0,m)}}renderButton(f,e,a){const k=this,q=this.chart,m=k.options,r=y(m.buttonTheme);e=q.renderer.button(k.getButtonText(f),e,a,function(e){const a=m.events&&m.events.click;let g;a&&(g=a.call(k,e,f));!1!==g&&(e.newLevel=m.showFullPath?f.level:k.level-1,I(k,"up",e))},r).addClass("highcharts-breadcrumbs-button").add(k.group);q.styledMode||
e.attr(m.style);return e}renderSeparator(f,e){const a=this.chart,g=this.options.separator;f=a.renderer.label(g.text,f,e,void 0,void 0,void 0,!1).addClass("highcharts-breadcrumbs-separator").add(this.group);a.styledMode||f.css(g.style);return f}update(a){y(!0,this.options,a);this.destroy();this.isDirty=!0}updateSingleButton(){const a=this.chart,e=this.list[this.level-1];a.drillUpButton&&a.drillUpButton.attr({text:this.getButtonText(e)})}destroy(){this.destroySingleButton();this.destroyListElements(!0);
this.group&&this.group.destroy();this.group=void 0}destroyListElements(a){const e=this.elementList;D(e,(f,g)=>{if(a||!e[g].updated)f=e[g],f.button&&f.button.destroy(),f.separator&&f.separator.destroy(),delete f.button,delete f.separator,delete e[g]});a&&(this.elementList={})}destroySingleButton(){this.chart.drillUpButton&&(this.chart.drillUpButton.destroy(),this.chart.drillUpButton=void 0)}resetElementListState(){D(this.elementList,a=>{a.updated=!1})}updateListElements(){function a(a,e,d){a.translate(e-
a.getBBox().width,d)}function e(a,e){return r*a.getBBox().width+r*e}const k=this.elementList,g=this.options.buttonSpacing,q=this.list,m=this.options.rtl,r=m?-1:1;let h=this.group?e(this.group,g):g,t,l;for(let f=0,v=q.length;f<v;++f){const d=f===v-1;let b,c;l=q[f];k[l.level]?(t=k[l.level],b=t.button,t.separator||d?t.separator&&d&&(t.separator.destroy(),delete t.separator):(h+=r*g,t.separator=this.renderSeparator(h,g),m&&a(t.separator,h,g),h+=e(t.separator,g)),k[l.level].updated=!0):(b=this.renderButton(l,
h,g),m&&a(b,h,g),h+=e(b,g),d||(c=this.renderSeparator(h,g),m&&a(c,h,g),h+=e(c,g)),k[l.level]={button:b,separator:c,updated:!0});b&&b.setState(d?2:0)}}}F.defaultOptions=a.options;"";return F});l(a,"Extensions/Drilldown.js",[a["Core/Animation/AnimationUtilities.js"],a["Core/Axis/Axis.js"],a["Core/Chart/Chart.js"],a["Core/Color/Color.js"],a["Series/Column/ColumnSeries.js"],a["Core/Globals.js"],a["Core/Defaults.js"],a["Core/Series/Point.js"],a["Core/Series/Series.js"],a["Core/Series/SeriesRegistry.js"],
a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Axis/Tick.js"],a["Core/Utilities.js"],a["Extensions/Breadcrumbs/Breadcrumbs.js"]],function(a,r,h,l,C,J,K,w,G,L,x,H,A,I){function v(d,b,c,a){d[c?"addClass":"removeClass"]("highcharts-drilldown-point");a||d.css({cursor:b})}function y(d){const b=this.series;b.xAxis&&!1===b.chart.options.drilldown.allowPointDrilldown?b.xAxis.drilldownCategory(this.x,d):this.runDrilldown(void 0,void 0,d)}function D(d){const b=[];(d=d.drilldownLevels)&&d.length&&(b[0]||b.push({level:0,
levelOptions:d[0].seriesOptions}),d.forEach(function(d){d.levelNumber+1>b[b.length-1].level&&b.push({level:d.levelNumber+1,levelOptions:B({name:d.lowerSeries.name},d.pointOptions)})}));return b}function E(d){const b=z(this.chart.options.drilldown.animation);d&&(d.hide(),N(function(){d&&d.added&&d.fadeIn()},Math.max(b.duration-50,0)))}const {animObject:z}=a,{noop:F}=J,{defaultOptions:f}=K;({seriesTypes:a}=L);const {addEvent:e,defined:k,diffObjects:g,extend:q,fireEvent:m,merge:B,objectEach:R,pick:t,
removeEvent:S,syncTimeout:N}=A;A=a.pie;a=a.map;let O=1;q(f.lang,{});f.drilldown={activeAxisLabelStyle:{cursor:"pointer",color:"#0022ff",fontWeight:"bold",textDecoration:"underline"},activeDataLabelStyle:{cursor:"pointer",color:"#0022ff",fontWeight:"bold",textDecoration:"underline"},animation:{duration:500},drillUpButton:{position:{align:"right",x:-10,y:10}},mapZooming:!0};x.prototype.Element.prototype.fadeIn=function(d){this.attr({opacity:.1,visibility:"inherit"}).animate({opacity:t(this.newOpacity,
1)},d||{duration:250})};h.prototype.addSeriesAsDrilldown=function(d,b){const c=this;if(c.mapView){d.series.isDrilling=!0;c.series.forEach(b=>{var d;b.options.inactiveOtherPoints=!0;null===(d=b.dataLabelsGroup)||void 0===d?void 0:d.destroy();delete b.dataLabelsGroup});if(c.options.drilldown&&!c.mapView.projection.hasGeoProjection&&f.drilldown){var a=g(c.options.drilldown,f.drilldown);k(a.mapZooming)||(c.options.drilldown.mapZooming=!1)}if(c.options.drilldown&&c.options.drilldown.animation&&c.options.drilldown.mapZooming){c.mapView.allowTransformAnimation=
!0;a=z(c.options.drilldown.animation);if("boolean"!==typeof a){const e=a.complete,p=function(a){a&&a.applyDrilldown&&c.mapView&&(c.addSingleSeriesAsDrilldown(d,b),c.applyDrilldown(),c.mapView.allowTransformAnimation=!1)};a.complete=function(){e&&e.apply(this,arguments);p.apply(this,arguments)}}d.zoomTo(a)}else c.addSingleSeriesAsDrilldown(d,b),c.applyDrilldown()}else c.addSingleSeriesAsDrilldown(d,b),c.applyDrilldown()};h.prototype.addSingleSeriesAsDrilldown=function(d,b){let c=d.series,a=c.xAxis,
e=c.yAxis,f,k=[],M=[],u,n,h;h=this.styledMode?{colorIndex:t(d.colorIndex,c.colorIndex)}:{color:d.color||c.color};this.drilldownLevels||(this.drilldownLevels=[]);u=c.options._levelNumber||0;(n=this.drilldownLevels[this.drilldownLevels.length-1])&&n.levelNumber!==u&&(n=void 0);b=q(q({_ddSeriesId:O++},h),b);f=c.points.indexOf(d);c.chart.series.forEach(function(b){b.xAxis===a&&(b.options._ddSeriesId=b.options._ddSeriesId||O++,b.options.colorIndex=b.colorIndex,b.options._levelNumber=b.options._levelNumber||
u,n?(k=n.levelSeries,M=n.levelSeriesOptions):(k.push(b),b.purgedOptions=B({_ddSeriesId:b.options._ddSeriesId,_levelNumber:b.options._levelNumber,selected:b.options.selected},b.userOptions),M.push(b.purgedOptions)))});d=q({levelNumber:u,seriesOptions:c.options,seriesPurgedOptions:c.purgedOptions,levelSeriesOptions:M,levelSeries:k,shapeArgs:d.shapeArgs,bBox:d.graphic?d.graphic.getBBox():{},color:d.isNull?l.parse(h.color).setOpacity(0).get():h.color,lowerSeriesOptions:b,pointOptions:c.options.data[f],
pointIndex:f,oldExtremes:{xMin:a&&a.userMin,xMax:a&&a.userMax,yMin:e&&e.userMin,yMax:e&&e.userMax},resetZoomButton:n&&n.levelNumber===u?void 0:this.resetZoomButton},h);this.drilldownLevels.push(d);a&&a.names&&(a.names.length=0);b=d.lowerSeries=this.addSeries(b,!1);b.options._levelNumber=u+1;a&&(a.oldPos=a.pos,a.userMin=a.userMax=null,e.userMin=e.userMax=null);b.isDrilling=!0;c.type===b.type&&(b.animate=b.animateDrilldown||F,b.options.animation=!0)};h.prototype.applyDrilldown=function(){const d=this,
b=this.drilldownLevels;let a;b&&0<b.length&&(a=b[b.length-1].levelNumber,this.drilldownLevels.forEach(function(b){d.mapView&&d.options.drilldown&&d.options.drilldown.mapZooming&&(d.redraw(),b.lowerSeries.isDrilling=!1,d.mapView.fitToBounds(b.lowerSeries.bounds),b.lowerSeries.isDrilling=!0);b.levelNumber===a&&b.levelSeries.forEach(function(c){if(!d.mapView)c.options&&c.options._levelNumber===a&&c.remove(!1);else if(c.options&&c.options._levelNumber===a&&c.group){let a={};d.options.drilldown&&(a=d.options.drilldown.animation);
c.group.animate({opacity:0},a,function(){c.remove(!1);b.levelSeries.filter(b=>Object.keys(b).length).length||(d.resetZoomButton&&(d.resetZoomButton.hide(),delete d.resetZoomButton),d.pointer.reset(),m(d,"afterDrilldown"),d.mapView&&(d.series.forEach(b=>{b.isDirtyData=!0;b.isDrilling=!1}),d.mapView.fitToBounds(void 0,void 0)),m(d,"afterApplyDrilldown"))})}})}));d.mapView||(this.resetZoomButton&&(this.resetZoomButton.hide(),delete this.resetZoomButton),this.pointer.reset(),m(this,"afterDrilldown"),
this.redraw(),m(this,"afterApplyDrilldown"))};h.prototype.drillUp=function(d){if(this.drilldownLevels&&0!==this.drilldownLevels.length){m(this,"beforeDrillUp");var b=this,a=b.drilldownLevels,e=a[a.length-1].levelNumber,f=b.series,P=b.drilldownLevels.length,k=function(d,a){let c;f.forEach(function(b){b.options._ddSeriesId===d._ddSeriesId&&(c=b)});c=c||b.addSeries(d,!1);c.type===a.type&&c.animateDrillupTo&&(c.animate=c.animateDrillupTo);if(d===g.seriesPurgedOptions)return c},h=d=>{d.remove(!1);b.series.forEach(b=>
{b.colorAxis&&(b.isDirtyData=!0);b.options.inactiveOtherPoints=!1});b.redraw()},u=a.length,n;for(b.symbolCounter=b.colorCounter=0;u--;){let c,p;var g=a[u];if(g.levelNumber===e){a.pop();c=g.lowerSeries;if(!c.chart)for(n=f.length;n--;)if(f[n].options.id===g.lowerSeriesOptions.id&&f[n].options._levelNumber===e+1){c=f[n];break}c.xData=[];c.xAxis&&c.xAxis.names&&(0===P||u===P)&&(c.xAxis.names.length=0);g.levelSeriesOptions.forEach(b=>{(b=k(b,c))&&(p=b)});m(b,"drillup",{seriesOptions:g.seriesPurgedOptions||
g.seriesOptions});p&&(p.type===c.type&&(p.drilldownLevel=g,p.options.animation=b.options.drilldown.animation,c.animateDrillupFrom&&c.chart&&c.animateDrillupFrom(g)),p.options._levelNumber=e);n=c;b.mapView||n.remove(!1);p&&p.xAxis&&(n=g.oldExtremes,p.xAxis.setExtremes(n.xMin,n.xMax,!1),p.yAxis.setExtremes(n.yMin,n.yMax,!1));g.resetZoomButton&&(b.resetZoomButton=g.resetZoomButton);this.mapView?(n=b.options.drilldown&&b.options.drilldown.animation&&b.options.drilldown.mapZooming,g.levelNumber===e&&d?
c.remove(!1):(c.dataLabelsGroup&&(c.dataLabelsGroup.destroy(),delete c.dataLabelsGroup),b.mapView&&p&&(n&&(c.isDrilling=!0,p.isDrilling=!0,b.redraw(!1),b.mapView.fitToBounds(c.bounds,void 0,!0,!1)),b.mapView.allowTransformAnimation=!0,m(b,"afterDrillUp",{seriesOptions:p?p.userOptions:void 0}),n?b.mapView.setView(void 0,1,!0,{complete:function(){Object.prototype.hasOwnProperty.call(this,"complete")&&h(c)}}):(b.mapView.allowTransformAnimation=!1,c.group?c.group.animate({opacity:0},b.options.drilldown.animation,
function(){h(c);b.mapView&&(b.mapView.allowTransformAnimation=!0)}):(h(c),b.mapView.allowTransformAnimation=!0)),p.isDrilling=!1,b.ddDupes&&(b.ddDupes.length=0),m(b,"drillupall")))):(m(b,"afterDrillUp"),this.redraw(),this.ddDupes&&(this.ddDupes.length=0),m(b,"drillupall"))}}}};e(h,"afterInit",function(){const d=this;d.drilldown={chart:d,fadeInGroup:E,update:function(b,c){B(!0,d.options.drilldown,b);t(c,!0)&&d.redraw()}}});e(h,"render",function(){(this.xAxis||[]).forEach(function(d){d.ddPoints={};
d.series.forEach(function(b){let c,a=b.xData||[],e=b.points;for(c=0;c<a.length;c++){var f=b.options.data[c];"number"!==typeof f&&(f=b.pointClass.prototype.optionsToObject.call({series:b},f),f.drilldown&&(d.ddPoints[a[c]]||(d.ddPoints[a[c]]=[]),f=c-(b.cropStart||0),d.ddPoints[a[c]].push(e&&0<=f&&f<e.length?e[f]:!0)))}});R(d.ticks,H.prototype.drillable)})});e(I,"up",function(d){const b=this.chart;d=this.getLevel()-d.newLevel;let a=1<d;for(let c=0;c<d;c++)c===d-1&&(a=!1),b.drillUp(a)});e(h,"afterDrilldown",
function(){var a=this.options.drilldown;a=a&&a.breadcrumbs;this.breadcrumbs||(this.breadcrumbs=new I(this,a));this.breadcrumbs.updateProperties(D(this))});e(h,"afterDrillUp",function(){this.breadcrumbs&&this.breadcrumbs.updateProperties(D(this))});e(h,"update",function(a){const b=this.breadcrumbs,c=a.options.drilldown&&a.options.drilldown.breadcrumbs;b&&c&&b.update(a.options.drilldown.breadcrumbs)});C.prototype.animateDrillupTo=function(a){if(!a){const b=this,a=b.drilldownLevel;this.points.forEach(function(b){const a=
b.dataLabel;b.graphic&&b.graphic.hide();a&&(a.hidden="hidden"===a.attr("visibility"),a.hidden||(a.hide(),b.connector&&b.connector.hide()))});N(function(){if(b.points){let c=[];b.data.forEach(function(b){c.push(b)});b.nodes&&(c=c.concat(b.nodes));c.forEach(function(b,c){c=c===(a&&a.pointIndex)?"show":"fadeIn";const d="show"===c?!0:void 0,e=b.dataLabel;if(b.graphic&&b.visible)b.graphic[c](d);e&&!e.hidden&&(e.fadeIn(),b.connector&&b.connector.fadeIn())})}},Math.max(this.chart.options.drilldown.animation.duration-
50,0));delete this.animate}};C.prototype.animateDrilldown=function(a){let b=this,c=this.chart,d=c.drilldownLevels,e,f=z(c.options.drilldown.animation),g=this.xAxis,h=c.styledMode;a||(d.forEach(function(a){b.options._ddSeriesId===a.lowerSeriesOptions._ddSeriesId&&(e=a.shapeArgs,h||(e.fill=a.color))}),e.x+=t(g.oldPos,g.pos)-g.pos,this.points.forEach(function(a){const c=a.shapeArgs;h||(c.fill=a.color);a.graphic&&a.graphic.attr(e).animate(q(a.shapeArgs,{fill:a.color||b.color}),f)}),c.drilldown&&c.drilldown.fadeInGroup(this.dataLabelsGroup),
delete this.animate)};C.prototype.animateDrillupFrom=function(a){let b=z(this.chart.options.drilldown.animation),c=this.group,d=c!==this.chart.columnGroup,e=this;e.trackerGroups.forEach(function(b){if(e[b])e[b].on("mouseover")});d&&delete this.group;this.points.forEach(function(f){function p(){g.destroy();c&&d&&(c=c.destroy())}const g=f.graphic,h=a.shapeArgs;g&&h&&(delete f.graphic,e.chart.styledMode||(h.fill=a.color),b.duration?g.animate(h,B(b,{complete:p})):(g.attr(h),p()))})};A&&q(A.prototype,
{animateDrillupTo:C.prototype.animateDrillupTo,animateDrillupFrom:C.prototype.animateDrillupFrom,animateDrilldown:function(a){const b=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],c=this.chart.options.drilldown.animation;this.is("item")&&(c.duration=0);if(this.center){const d=b.shapeArgs,e=d.start,f=(d.end-e)/this.points.length,g=this.chart.styledMode;a||(this.points.forEach(function(a,h){const p=a.shapeArgs;g||(d.fill=b.color,p.fill=a.color);if(a.graphic)a.graphic.attr(B(d,{start:e+
h*f,end:e+(h+1)*f}))[c?"animate":"attr"](p,c)}),this.chart.drilldown&&this.chart.drilldown.fadeInGroup(this.dataLabelsGroup),delete this.animate)}}});a&&q(a.prototype,{animateDrilldown(a){const b=this,c=this.chart,d=this.group;c&&d&&b.options&&(a&&c.mapView?(d.attr({opacity:.01}),c.mapView.allowTransformAnimation=!1,b.options.inactiveOtherPoints=!0,b.options.enableMouseTracking=!1):(d.animate({opacity:1},c.options.drilldown.animation,function(){b.options&&(b.options.inactiveOtherPoints=!1,b.options.enableMouseTracking=
t(b.userOptions&&b.userOptions.enableMouseTracking,!0),b.isDirty=!0,c.redraw())}),c.drilldown&&c.drilldown.fadeInGroup(this.dataLabelsGroup)))},animateDrillupFrom(){const a=this.chart;a&&a.mapView&&(a.mapView.allowTransformAnimation=!1);this.options&&(this.options.inactiveOtherPoints=!0)},animateDrillupTo(a){const b=this.chart,c=this.group;b&&c&&(a?(c.attr({opacity:.01}),this.options&&(this.options.inactiveOtherPoints=!0)):(c.animate({opacity:1},b.options.drilldown.animation),b.drilldown&&b.drilldown.fadeInGroup(this.dataLabelsGroup)))}});
w.prototype.doDrilldown=function(){this.runDrilldown()};w.prototype.runDrilldown=function(a,b,c){const d=this.series.chart,e=d.options.drilldown;let f=(e.series||[]).length,g;d.ddDupes||(d.ddDupes=[]);for(d.colorCounter=d.symbolCounter=0;f--&&!g;)e.series[f].id===this.drilldown&&-1===d.ddDupes.indexOf(this.drilldown)&&(g=e.series[f],d.ddDupes.push(this.drilldown));m(d,"drilldown",{point:this,seriesOptions:g,category:b,originalEvent:c,points:"undefined"!==typeof b&&this.series.xAxis.getDDPoints(b).slice(0)},
function(b){const c=b.point.series&&b.point.series.chart,d=b.seriesOptions;c&&d&&(a?c.addSingleSeriesAsDrilldown(b.point,d):c.addSeriesAsDrilldown(b.point,d))})};r.prototype.drilldownCategory=function(a,b){this.getDDPoints(a).forEach(function(c){c&&c.series&&c.series.visible&&c.runDrilldown&&c.runDrilldown(!0,a,b)});this.chart.applyDrilldown()};r.prototype.getDDPoints=function(a){return this.ddPoints&&this.ddPoints[a]||[]};H.prototype.drillable=function(){const a=this.pos,b=this.label,c=this.axis,
f="xAxis"===c.coll&&c.getDDPoints,g=f&&c.getDDPoints(a),h=c.chart.styledMode;f&&(b&&g&&g.length?(b.drillable=!0,b.basicStyles||h||(b.basicStyles=B(b.styles)),b.addClass("highcharts-drilldown-axis-label"),b.removeOnDrillableClick&&S(b.element,"click"),b.removeOnDrillableClick=e(b.element,"click",function(b){b.preventDefault();c.drilldownCategory(a,b)}),h||b.css(c.chart.options.drilldown.activeAxisLabelStyle)):b&&b.drillable&&b.removeOnDrillableClick&&(h||(b.styles={},b.element.removeAttribute("style"),
b.css(b.basicStyles)),b.removeOnDrillableClick(),b.removeClass("highcharts-drilldown-axis-label")))};e(w,"afterInit",function(){this.drilldown&&!this.unbindDrilldownClick&&(this.unbindDrilldownClick=e(this,"click",y));return this});e(w,"update",function(a){a=a.options||{};a.drilldown&&!this.unbindDrilldownClick?this.unbindDrilldownClick=e(this,"click",y):!a.drilldown&&void 0!==a.drilldown&&this.unbindDrilldownClick&&(this.unbindDrilldownClick=this.unbindDrilldownClick())});e(G,"afterDrawDataLabels",
function(){const a=this.chart.options.drilldown.activeDataLabelStyle,b=this.chart.renderer,c=this.chart.styledMode;this.points.forEach(function(d){const e=d.options.dataLabels,f=t(d.dlOptions,e&&e.style,{});d.drilldown&&d.dataLabel&&("contrast"!==a.color||c||(f.color=b.getContrast(d.color||this.color)),e&&e.color&&(f.color=e.color),d.dataLabel.addClass("highcharts-drilldown-data-label"),c||d.dataLabel.css(a).css(f))},this)});e(G,"afterDrawTracker",function(){const a=this.chart.styledMode;this.points.forEach(function(b){b.drilldown&&
b.graphic&&v(b.graphic,"pointer",!0,a)})});e(w,"afterSetState",function(){const a=this.series.chart.styledMode;this.drilldown&&this.series.halo&&"hover"===this.state?v(this.series.halo,"pointer",!0,a):this.series.halo&&v(this.series.halo,"auto",!1,a)});e(h,"drillup",function(){this.resetZoomButton&&(this.resetZoomButton=this.resetZoomButton.destroy())});e(h,"drillupall",function(){this.resetZoomButton&&this.showResetZoom()})});l(a,"masters/modules/drilldown.src.js",[a["Core/Globals.js"],a["Extensions/Breadcrumbs/Breadcrumbs.js"]],
function(a,l){a.Breadcrumbs=l;l.compose(a.Chart,a.defaultOptions)})});//# sourceMappingURL=drilldown.js.map