/*
 Highcharts JS v11.1.0 (2023-08-20)

 Exporting module

 (c) 2010-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';var g=g||{};g.scope={};g.ASSUME_ES5=!1;g.ASSUME_NO_NATIVE_MAP=!1;g.ASSUME_NO_NATIVE_SET=!1;g.SIMPLE_FROUND_POLYFILL=!1;g.ISOLATE_POLYFILLS=!1;g.defineProperty=g.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){if(a==Array.prototype||a==Object.prototype)return a;a[c]=d.value;return a};
g.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var d=a[c];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};g.global=g.getGlobal(this);g.polyfills={};g.propertyToPolyfillSymbol={};g.POLYFILL_PREFIX="$jscp$";g.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");
g.polyfill=function(a,c,d,b){c&&(g.ISOLATE_POLYFILLS?g.polyfillIsolated(a,c,d,b):g.polyfillUnisolated(a,c,d,b))};g.polyfillUnisolated=function(a,c){var d=g.global;a=a.split(".");for(var b=0;b<a.length-1;b++){var h=a[b];h in d||(d[h]={});d=d[h]}a=a[a.length-1];b=d[a];c=c(b);c!=b&&null!=c&&g.defineProperty(d,a,{configurable:!0,writable:!0,value:c})};
g.polyfillIsolated=function(a,c,d){var b=a.split(".");a=1===b.length;var h=b[0];h=!a&&h in g.polyfills?g.polyfills:g.global;for(var w=0;w<b.length-1;w++){var f=b[w];f in h||(h[f]={});h=h[f]}b=b[b.length-1];d=g.IS_SYMBOL_NATIVE&&"es6"===d?h[b]:null;c=c(d);null!=c&&(a?g.defineProperty(g.polyfills,b,{configurable:!0,writable:!0,value:c}):c!==d&&(g.propertyToPolyfillSymbol[b]=g.IS_SYMBOL_NATIVE?g.global.Symbol(b):g.POLYFILL_PREFIX+b,b=g.propertyToPolyfillSymbol[b],g.defineProperty(h,b,{configurable:!0,
writable:!0,value:c})))};g.polyfill("Array.prototype.includes",function(a){return a?a:function(a,d){var b=this;b instanceof String&&(b=String(b));var h=b.length;d=d||0;for(0>d&&(d=Math.max(d+h,0));d<h;d++){var c=b[d];if(c===a||Object.is(c,a))return!0}return!1}},"es7","es3");
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/export-data",["highcharts","highcharts/modules/exporting"],function(c){a(c);a.Highcharts=c;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function c(a,b,h,c){a.hasOwnProperty(b)||(a[b]=c.apply(null,h),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:b,module:a[b]}})))}
a=a?a._modules:{};c(a,"Extensions/ExportData/ExportDataDefaults.js",[],function(){"";return{exporting:{csv:{annotations:{itemDelimiter:"; ",join:!1},columnHeaderFormatter:null,dateFormat:"%Y-%m-%d %H:%M:%S",decimalPoint:null,itemDelimiter:null,lineDelimiter:"\n"},showTable:!1,useMultiLevelHeaders:!0,useRowspanHeaders:!0},lang:{downloadCSV:"Download CSV",downloadXLS:"Download XLS",exportData:{annotationHeader:"Annotations",categoryHeader:"Category",categoryDatetimeHeader:"DateTime"},viewData:"View data table",
hideData:"Hide data table"}}});c(a,"Extensions/DownloadURL.js",[a["Core/Globals.js"]],function(a){const {isSafari:b}=a,c=a.win,d=c.document,f=c.URL||c.webkitURL||c,D=a.dataURLtoBlob=function(a){if((a=a.replace(/filename=.*;/,"").match(/data:([^;]*)(;base64)?,([0-9A-Za-z+/]+)/))&&3<a.length&&c.atob&&c.ArrayBuffer&&c.Uint8Array&&c.Blob&&f.createObjectURL){const d=c.atob(a[3]);var b=new c.ArrayBuffer(d.length);b=new c.Uint8Array(b);for(let a=0;a<b.length;++a)b[a]=d.charCodeAt(a);a=new c.Blob([b],{type:a[1]});
return f.createObjectURL(a)}};a=a.downloadURL=function(a,h){var f=c.navigator;const q=d.createElement("a");if("string"===typeof a||a instanceof String||!f.msSaveOrOpenBlob){a=`${a}`;f=/Edge\/\d+/.test(f.userAgent);if(b&&"string"===typeof a&&0===a.indexOf("data:application/pdf")||f||2E6<a.length)if(a=D(a)||"",!a)throw Error("Failed to convert to blob");if("undefined"!==typeof q.download)q.href=a,q.download=h,d.body.appendChild(q),q.click(),d.body.removeChild(q);else try{const b=c.open(a,"chart");if("undefined"===
typeof b||null===b)throw Error("Failed to open window");}catch(N){c.location.href=a}}else f.msSaveOrOpenBlob(a,h)};return{dataURLtoBlob:D,downloadURL:a}});c(a,"Extensions/ExportData/ExportData.js",[a["Core/Renderer/HTML/AST.js"],a["Extensions/ExportData/ExportDataDefaults.js"],a["Core/Globals.js"],a["Core/Defaults.js"],a["Extensions/DownloadURL.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,c,h,w,f,D,q){function b(){const a=this.getCSV(!0);O(P(a,"text/csv")||"data:text/csv,\ufeff"+
encodeURIComponent(a),this.getFilename()+".csv")}function d(){const a='<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head>\x3c!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>Ark1</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--\x3e<style>td{border:none;font-family: Calibri, sans-serif;} .number{mso-number-format:"0.00";} .text{ mso-number-format:"@";}</style><meta name=ProgId content=Excel.Sheet><meta charset=UTF-8></head><body>'+
this.getTable(!0)+"</body></html>";O(P(a,"application/vnd.ms-excel")||"data:application/vnd.ms-excel;base64,"+t.btoa(unescape(encodeURIComponent(a))),this.getFilename()+".xls")}function V(a){let e="";const c=this.getDataRows(),b=this.options.exporting.csv,d=x(b.decimalPoint,","!==b.itemDelimiter&&a?(1.1).toLocaleString()[1]:"."),A=x(b.itemDelimiter,","===d?";":","),h=b.lineDelimiter;c.forEach((a,b)=>{let p,r=a.length;for(;r--;)p=a[r],"string"===typeof p&&(p='"'+p+'"'),"number"===typeof p&&"."!==d&&
(p=p.toString().replace(".",d)),a[r]=p;a.length=c.length?c[0].length:0;e+=a.join(A);b<c.length-1&&(e+=h)});return e}function N(a){function c(a,b){return a.data.filter(a=>"undefined"!==typeof a.y&&a.name).length&&b&&!b.categories&&!a.keyToAxis?a.pointArrayMap&&a.pointArrayMap.filter(a=>"x"===a).length?(a.pointArrayMap.unshift("x"),a.pointArrayMap):["x","y"]:a.pointArrayMap||["y"]}function b(a,b,e){const c={},d={};b.forEach(function(b){var m=(a.keyToAxis&&a.keyToAxis[b]||b)+"Axis";m=W(e)?a.chart[m][e]:
a[m];c[b]=m&&m.categories||[];d[b]=m&&m.dateTime});return{categoryMap:c,dateTimeValueAxisMap:d}}function e(b,e,c){if(h.columnHeaderFormatter){const a=h.columnHeaderFormatter(b,e,c);if(!1!==a)return a}return b?b instanceof X?a?{columnTitle:1<c?e:b.name,topLevelColumnTitle:b.name}:b.name+(1<c?" ("+e+")":""):b.options.title&&b.options.title.text||(b.dateTime?y:R):R}const d=this.hasParallelCoordinates,A=this.time,h=this.options.exporting&&this.options.exporting.csv||{},q=this.xAxis,k={},f=[],Q=[],l=[];
var u=this.options.lang.exportData;const R=u.categoryHeader,y=u.categoryDatetimeHeader,B=[];let n,C,z=0;this.series.forEach(function(m){const p=m.xAxis,r=m.options.keys||c(m,p),u=r.length,n=!m.requireSorting&&{},G=q.indexOf(p);let F=b(m,r),y,f;if(!1!==m.options.includeInDataExport&&!m.options.isInternal&&!1!==m.visible){Y(B,function(a){return a[0]===G})||B.push([G,z]);for(f=0;f<u;)C=e(m,r[f],r.length),l.push(C.columnTitle||C),a&&Q.push(C.topLevelColumnTitle||C),f++;y={chart:m.chart,autoIncrement:m.autoIncrement,
options:m.options,pointArrayMap:m.pointArrayMap,index:m.index};m.options.data.forEach(function(a,e){const c={series:y};let l;d&&(F=b(m,r,e));m.pointClass.prototype.applyOptions.apply(c,[a]);l=c.x;H(k[l])&&k[l].seriesIndices.includes(y.index)&&(a=Object.keys(k).filter(a=>k[a].seriesIndices.includes(y.index)&&l).filter(a=>0===a.indexOf(String(l))),l=l.toString()+","+a.length);a=m.data[e]&&m.data[e].name;f=0;if(!p||"name"===m.exportKey||!d&&p&&p.hasNames&&a)l=a;n&&(n[l]&&(l+="|"+e),n[l]=!0);k[l]||(k[l]=
[],k[l].xValues=[]);k[l].x=c.x;k[l].name=a;k[l].xValues[G]=c.x;H(k[l].seriesIndices)||(k[l].seriesIndices=[]);for(k[l].seriesIndices=[...k[l].seriesIndices,y.index];f<u;)e=r[f],a=c[e],k[l][z+f]=x(F.categoryMap[e][a],F.dateTimeValueAxisMap[e]?A.dateFormat(h.dateFormat,a):null,a),f++});z+=f}});for(w in k)Object.hasOwnProperty.call(k,w)&&f.push(k[w]);let t,v;u=a?[Q,l]:[l];for(z=B.length;z--;){t=B[z][0];v=B[z][1];n=q[t];f.sort(function(a,b){return a.xValues[t]-b.xValues[t]});var w=e(n);u[0].splice(v,
0,w);a&&u[1]&&u[1].splice(v,0,w);f.forEach(function(a){let b=a.name;n&&!H(b)&&(n.dateTime?(a.x instanceof Date&&(a.x=a.x.getTime()),b=A.dateFormat(h.dateFormat,a.x)):b=n.categories?x(n.names[a.x],n.categories[a.x],a.x):a.x);a.splice(v,0,b)})}u=u.concat(f);E(this,"exportData",{dataRows:u});return u}function Z(a){const b=a=>{if(!a.tagName||"#text"===a.tagName)return a.textContent||"";const c=a.attributes;let e=`<${a.tagName}`;c&&Object.keys(c).forEach(a=>{e+=` ${a}="${c[a]}"`});e+=">";e+=a.textContent||
"";(a.children||[]).forEach(a=>{e+=b(a)});return e+=`</${a.tagName}>`};a=this.getTableAST(a);return b(a)}function aa(a){function b(a,b,c,e){let d=x(e,"");b="highcharts-text"+(b?" "+b:"");"number"===typeof d?(d=d.toString(),","===f&&(d=d.replace(".",f)),b="highcharts-number"):e||(b="highcharts-empty");c=S({"class":b},c);return{tagName:a,attributes:c,textContent:d}}let c=0;var e=[];const d=this.options,f=a?(1.1).toLocaleString()[1]:".",h=x(d.exporting.useMultiLevelHeaders,!0);a=this.getDataRows(h);
const q=h?a.shift():null,k=a.shift();!1!==d.exporting.tableCaption&&e.push({tagName:"caption",attributes:{"class":"highcharts-table-caption"},textContent:x(d.exporting.tableCaption,d.title.text?d.title.text:"Chart")});for(let b=0,e=a.length;b<e;++b)a[b].length>c&&(c=a[b].length);e.push(function(a,c,e){const f=[];let p=0;e=e||c&&c.length;let l=0;var n;if(n=h&&a&&c){a:if(n=a.length,c.length===n){for(;n--;)if(a[n]!==c[n]){n=!1;break a}n=!0}else n=!1;n=!n}if(n){for(n=[];p<e;++p){var k=a[p];var r=a[p+
1];k===r?++l:l?(n.push(b("th","highcharts-table-topheading",{scope:"col",colspan:l+1},k)),l=0):(k===c[p]?d.exporting.useRowspanHeaders?(r=2,delete c[p]):(r=1,c[p]=""):r=1,k=b("th","highcharts-table-topheading",{scope:"col"},k),1<r&&k.attributes&&(k.attributes.valign="top",k.attributes.rowspan=r),n.push(k))}f.push({tagName:"tr",children:n})}if(c){a=[];p=0;for(e=c.length;p<e;++p)"undefined"!==typeof c[p]&&a.push(b("th",null,{scope:"col"},c[p]));f.push({tagName:"tr",children:a})}return{tagName:"thead",
children:f}}(q,k,Math.max(c,k.length)));const t=[];a.forEach(function(a){const e=[];for(let d=0;d<c;d++)e.push(b(d?"td":"th",null,d?{}:{scope:"row"},a[d]));t.push({tagName:"tr",children:e})});e.push({tagName:"tbody",children:t});e={tree:{tagName:"table",id:`highcharts-data-table-${this.index}`,children:e}};E(this,"aftergetTableAST",e);return e.tree}function ba(){this.toggleDataTable(!1)}function ca(b){var c=(b=x(b,!this.isDataTableVisible))&&!this.dataTableDiv;c&&(this.dataTableDiv=da.createElement("div"),
this.dataTableDiv.className="highcharts-data-table",this.renderTo.parentNode.insertBefore(this.dataTableDiv,this.renderTo.nextSibling));if(this.dataTableDiv){var e=this.dataTableDiv.style,d=e.display;e.display=b?"block":"none";b?(this.dataTableDiv.innerHTML=a.emptyHTML,(new a([this.getTableAST()])).addToDOM(this.dataTableDiv),E(this,"afterViewData",{element:this.dataTableDiv,wasHidden:c||d!==e.display})):E(this,"afterHideData")}this.isDataTableVisible=b;c=this.exportDivElements;d=(e=this.options.exporting)&&
e.buttons&&e.buttons.contextButton.menuItems;b=this.options.lang;e&&e.menuItemDefinitions&&b&&b.viewData&&b.hideData&&d&&c&&(c=c[d.indexOf("viewData")])&&a.setElementHTML(c,this.isDataTableVisible?b.hideData:b.viewData)}function ea(){this.toggleDataTable(!0)}function P(a,b){const c=t.navigator,e=-1<c.userAgent.indexOf("WebKit")&&0>c.userAgent.indexOf("Chrome"),d=t.URL||t.webkitURL||t;try{if(c.msSaveOrOpenBlob&&t.MSBlobBuilder){const b=new t.MSBlobBuilder;b.append(a);return b.getBlob("image/svg+xml")}if(!e)return d.createObjectURL(new t.Blob(["\ufeff"+
a],{type:b}))}catch(A){}}function fa(){const a=this,b=a.dataTableDiv,c=(a,b)=>(c,e)=>{var d=(b?c:e).children[a].textContent;c=(b?e:c).children[a].textContent;return""===d||""===c||isNaN(d)||isNaN(c)?d.toString().localeCompare(c):d-c};if(b&&a.options.exporting&&a.options.exporting.allowTableSorting){const e=b.querySelector("thead tr");e&&e.childNodes.forEach(e=>{const d=e.closest("table");e.addEventListener("click",function(){const f=[...b.querySelectorAll("tr:not(thead tr)")],h=[...e.parentNode.children];
f.sort(c(h.indexOf(e),a.ascendingOrderInTable=!a.ascendingOrderInTable)).forEach(a=>{d.appendChild(a)});h.forEach(a=>{["highcharts-sort-ascending","highcharts-sort-descending"].forEach(b=>{a.classList.contains(b)&&a.classList.remove(b)})});e.classList.add(a.ascendingOrderInTable?"highcharts-sort-ascending":"highcharts-sort-descending")})})}}function ha(){this.options&&this.options.exporting&&this.options.exporting.showTable&&!this.options.chart.forExport&&this.viewData()}const {doc:da,win:t}=h,{getOptions:ia,
setOptions:T}=w,{downloadURL:O}=f,{series:X,seriesTypes:{arearange:I,gantt:J,map:K,mapbubble:L,treemap:M}}=D,{addEvent:U,defined:H,extend:S,find:Y,fireEvent:E,isNumber:W,pick:x}=q,v=[];"";return{compose:function(a){q.pushUnique(v,a)&&(U(a,"afterViewData",fa),U(a,"render",ha),a=a.prototype,a.downloadCSV=b,a.downloadXLS=d,a.getCSV=V,a.getDataRows=N,a.getTable=Z,a.getTableAST=aa,a.hideData=ba,a.toggleDataTable=ca,a.viewData=ea);if(q.pushUnique(v,T)){if(a=ia().exporting)S(a.menuItemDefinitions,{downloadCSV:{textKey:"downloadCSV",
onclick:function(){this.downloadCSV()}},downloadXLS:{textKey:"downloadXLS",onclick:function(){this.downloadXLS()}},viewData:{textKey:"viewData",onclick:function(){this.toggleDataTable()}}}),a.buttons&&a.buttons.contextButton.menuItems&&a.buttons.contextButton.menuItems.push("separator","downloadCSV","downloadXLS","viewData");T(c)}I&&q.pushUnique(v,I)&&(I.prototype.keyToAxis={low:"y",high:"y"});J&&q.pushUnique(v,J)&&(J.prototype.keyToAxis={start:"x",end:"x"});K&&q.pushUnique(v,K)&&(K.prototype.exportKey=
"name");L&&q.pushUnique(v,L)&&(L.prototype.exportKey="name");M&&q.pushUnique(v,M)&&(M.prototype.exportKey="name")}}});c(a,"masters/modules/export-data.src.js",[a["Core/Globals.js"],a["Extensions/ExportData/ExportData.js"]],function(a,b){b.compose(a.Chart)})});//# sourceMappingURL=export-data.js.map