/*
 Highmaps JS v11.1.0 (2023-08-20)

 Highmaps as a plugin for Highcharts or Highcharts Stock.

 (c) 2011-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/map",["highcharts"],function(y){a(y);a.Highcharts=y;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function y(a,p,q,z){a.hasOwnProperty(p)||(a[p]=z.apply(null,q),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:p,module:a[p]}})))}a=a?a._modules:
{};y(a,"Core/Axis/Color/ColorAxisComposition.js",[a["Core/Color/Color.js"],a["Core/Utilities.js"]],function(a,p){const {parse:q}=a,{addEvent:g,extend:l,merge:n,pick:A,splat:u}=p;var v;(function(t){function f(){const b=this.options;this.colorAxis=[];b.colorAxis&&(b.colorAxis=u(b.colorAxis),b.colorAxis.forEach(b=>{new w(this,b)}))}function a(b){const r=r=>{r=b.allItems.indexOf(r);-1!==r&&(this.destroyItem(b.allItems[r]),b.allItems.splice(r,1))};let d=[],h,m;(this.chart.colorAxis||[]).forEach(function(b){(h=
b.options)&&h.showInLegend&&(h.dataClasses&&h.visible?d=d.concat(b.getDataClassLegendSymbols()):h.visible&&d.push(b),b.series.forEach(function(b){if(!b.options.showInLegend||h.dataClasses)"point"===b.options.legendType?b.points.forEach(function(b){r(b)}):r(b)}))});for(m=d.length;m--;)b.allItems.unshift(d[m])}function e(b){b.visible&&b.item.legendColor&&b.item.legendItem.symbol.attr({fill:b.item.legendColor})}function c(){const b=this.chart.colorAxis;b&&b.forEach(function(b,d,h){b.update({},h)})}function k(){(this.chart.colorAxis&&
this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()}function b(){const b=this.axisTypes;b?-1===b.indexOf("colorAxis")&&b.push("colorAxis"):this.axisTypes=["colorAxis"]}function d(b){const r=this,d=b?"show":"hide";r.visible=r.options.visible=!!b;["graphic","dataLabel"].forEach(function(b){if(r[b])r[b][d]()});this.series.buildKDTree()}function E(){const b=this,r=this.options.nullColor,d=this.colorAxis,h=this.colorKey;(this.data.length?this.data:this.points).forEach(m=>{var c=m.getNestedProperty(h);
(c=m.options.color||(m.isNull||null===m.value?r:d&&"undefined"!==typeof c?d.toColor(c,m):m.color||b.color))&&m.color!==c&&(m.color=c,"point"===b.options.legendType&&m.legendItem&&m.legendItem.label&&b.chart.legend.colorizeItem(m,m.visible))})}function h(b){const r=b.prototype.createAxis;b.prototype.createAxis=function(b,d){if("colorAxis"!==b)return r.apply(this,arguments);const h=new w(this,n(d.axis,{index:this[b].length,isX:!1}));this.isDirtyLegend=!0;this.axes.forEach(function(b){b.series=[]});
this.series.forEach(function(b){b.bindAxes();b.isDirtyData=!0});A(d.redraw,!0)&&this.redraw(d.animation);return h}}function C(){this.elem.attr("fill",q(this.start).tweenTo(q(this.end),this.pos),void 0,!0)}function m(){this.elem.attr("stroke",q(this.start).tweenTo(q(this.end),this.pos),void 0,!0)}const x=[];let w;t.compose=function(t,r,B,D,H){w||(w=t);p.pushUnique(x,r)&&(t=r.prototype,t.collectionsWithUpdate.push("colorAxis"),t.collectionsWithInit.colorAxis=[t.addColorAxis],g(r,"afterGetAxes",f),h(r));
p.pushUnique(x,B)&&(r=B.prototype,r.fillSetter=C,r.strokeSetter=m);p.pushUnique(x,D)&&(g(D,"afterGetAllItems",a),g(D,"afterColorizeItem",e),g(D,"afterUpdate",c));p.pushUnique(x,H)&&(l(H.prototype,{optionalAxis:"colorAxis",translateColors:E}),l(H.prototype.pointClass.prototype,{setVisible:d}),g(H,"afterTranslate",k,{order:1}),g(H,"bindAxes",b))};t.pointSetVisible=d})(v||(v={}));return v});y(a,"Core/Axis/Color/ColorAxisDefaults.js",[],function(){return{lineWidth:0,minPadding:0,maxPadding:0,gridLineColor:"#ffffff",
gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:"#999999"},labels:{distance:8,overflow:"justify",rotation:0},minColor:"#e6e9ff",maxColor:"#0022ff",tickLength:5,showInLegend:!0}});y(a,"Core/Axis/Color/ColorAxis.js",[a["Core/Axis/Axis.js"],a["Core/Color/Color.js"],a["Core/Axis/Color/ColorAxisComposition.js"],a["Core/Axis/Color/ColorAxisDefaults.js"],a["Core/Legend/LegendSymbol.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],
function(a,p,q,z,l,n,A){const {parse:g}=p,{series:v}=n,{extend:t,isArray:f,isNumber:F,merge:e,pick:c}=A;class k extends a{static compose(b,d,c,h){q.compose(k,b,d,c,h)}constructor(b,d){super(b,d);this.beforePadding=!1;this.chart=void 0;this.coll="colorAxis";this.stops=this.options=this.dataClasses=void 0;this.visible=!0;this.init(b,d)}init(b,d){var c=b.options.legend||{};const h=d.layout?"vertical"!==d.layout:"vertical"!==c.layout,C=d.visible;c=e(k.defaultColorAxisOptions,d,{showEmpty:!1,title:null,
visible:c.enabled&&!1!==C});this.side=d.side||h?2:1;this.reversed=d.reversed||!h;this.opposite=!h;super.init(b,c,"colorAxis");this.userOptions=d;f(b.userOptions.colorAxis)&&(b.userOptions.colorAxis[this.index]=d);d.dataClasses&&this.initDataClasses(d);this.initStops();this.horiz=h;this.zoomEnabled=!1}initDataClasses(b){const d=this.chart,c=this.legendItem=this.legendItem||{},h=b.dataClasses.length,k=this.options;let m,x=0,w=d.options.chart.colorCount;this.dataClasses=m=[];c.labels=[];(b.dataClasses||
[]).forEach(function(b,r){b=e(b);m.push(b);if(d.styledMode||!b.color)"category"===k.dataClassColor?(d.styledMode||(r=d.options.colors,w=r.length,b.color=r[x]),b.colorIndex=x,x++,x===w&&(x=0)):b.color=g(k.minColor).tweenTo(g(k.maxColor),2>h?.5:r/(h-1))})}hasData(){return!!(this.tickPositions||[]).length}setTickPositions(){if(!this.dataClasses)return super.setTickPositions()}initStops(){this.stops=this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(b){b.color=
g(b[1])})}setOptions(b){super.setOptions(b);this.options.crosshair=this.options.marker}setAxisSize(){var b=this.legendItem&&this.legendItem.symbol;const d=this.chart;var c=d.options.legend||{};let h,e;b?(this.left=c=b.attr("x"),this.top=h=b.attr("y"),this.width=e=b.attr("width"),this.height=b=b.attr("height"),this.right=d.chartWidth-c-e,this.bottom=d.chartHeight-h-b,this.len=this.horiz?e:b,this.pos=this.horiz?c:h):this.len=(this.horiz?c.symbolWidth:c.symbolHeight)||k.defaultLegendLength}normalizedValue(b){this.logarithmic&&
(b=this.logarithmic.log2lin(b));return 1-(this.max-b)/(this.max-this.min||1)}toColor(b,d){const c=this.dataClasses;var h=this.stops;let k,m,e,w;if(c)for(w=c.length;w--;){if(e=c[w],k=e.from,h=e.to,("undefined"===typeof k||b>=k)&&("undefined"===typeof h||b<=h)){m=e.color;d&&(d.dataClass=w,d.colorIndex=e.colorIndex);break}}else{b=this.normalizedValue(b);for(w=h.length;w--&&!(b>h[w][0]););k=h[w]||h[w+1];h=h[w+1]||k;b=1-(h[0]-b)/(h[0]-k[0]||1);m=k.color.tweenTo(h.color,b)}return m}getOffset(){const b=
this.legendItem&&this.legendItem.group,d=this.chart.axisOffset[this.side];if(b){this.axisParent=b;super.getOffset();const c=this.chart.legend;c.allItems.forEach(function(b){b instanceof k&&b.drawLegendSymbol(c,b)});c.render();this.chart.getMargins(!0);this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width);this.chart.axisOffset[this.side]=d}}setLegendColor(){var b=this.reversed,d=b?1:0;b=b?0:1;d=this.horiz?[d,0,b,0]:[0,b,0,d];this.legendColor={linearGradient:{x1:d[0],y1:d[1],x2:d[2],
y2:d[3]},stops:this.stops}}drawLegendSymbol(b,d){var e;d=d.legendItem||{};const h=b.padding,f=b.options,m=this.options.labels,x=c(f.itemDistance,10),w=this.horiz,t=c(f.symbolWidth,w?k.defaultLegendLength:12),r=c(f.symbolHeight,w?12:k.defaultLegendLength),B=c(f.labelPadding,w?16:30);this.setLegendColor();d.symbol||(d.symbol=this.chart.renderer.symbol("roundedRect",0,b.baseline-11,t,r,{r:null!==(e=f.symbolRadius)&&void 0!==e?e:3}).attr({zIndex:1}).add(d.group));d.labelWidth=t+h+(w?x:c(m.x,m.distance)+
this.maxLabelLength);d.labelHeight=r+h+(w?B:0)}setState(b){this.series.forEach(function(d){d.setState(b)})}setVisible(){}getSeriesExtremes(){const b=this.series;let d;let k,h,e=b.length,m,x;this.dataMin=Infinity;for(this.dataMax=-Infinity;e--;){h=b[e];d=h.colorKey=c(h.options.colorKey,h.colorKey,h.pointValKey,h.zoneAxis,"y");var w=h.pointArrayMap;k=h[d+"Min"]&&h[d+"Max"];if(h[d+"Data"])var f=h[d+"Data"];else if(w){if(f=[],w=w.indexOf(d),m=h.yData,0<=w&&m)for(x=0;x<m.length;x++)f.push(c(m[x][w],m[x]))}else f=
h.yData;k?(h.minColorValue=h[d+"Min"],h.maxColorValue=h[d+"Max"]):(f=v.prototype.getExtremes.call(h,f),h.minColorValue=f.dataMin,h.maxColorValue=f.dataMax);"undefined"!==typeof h.minColorValue&&(this.dataMin=Math.min(this.dataMin,h.minColorValue),this.dataMax=Math.max(this.dataMax,h.maxColorValue));k||v.prototype.applyExtremes.call(h)}}drawCrosshair(b,d){const c=this.legendItem||{},h=d&&d.plotX,k=d&&d.plotY,m=this.pos,e=this.len;let f;d&&(f=this.toPixels(d.getNestedProperty(d.series.colorKey)),f<
m?f=m-2:f>m+e&&(f=m+e+2),d.plotX=f,d.plotY=this.len-f,super.drawCrosshair(b,d),d.plotX=h,d.plotY=k,this.cross&&!this.cross.addedToColorAxis&&c.group&&(this.cross.addClass("highcharts-coloraxis-marker").add(c.group),this.cross.addedToColorAxis=!0,this.chart.styledMode||"object"!==typeof this.crosshair||this.cross.attr({fill:this.crosshair.color})))}getPlotLinePath(b){const d=this.left,c=b.translatedValue,h=this.top;return F(c)?this.horiz?[["M",c-4,h-6],["L",c+4,h-6],["L",c,h],["Z"]]:[["M",d,c],["L",
d-6,c+6],["L",d-6,c-6],["Z"]]:super.getPlotLinePath(b)}update(b,d){const c=this.chart.legend;this.series.forEach(b=>{b.isDirtyData=!0});(b.dataClasses&&c.allItems||this.dataClasses)&&this.destroyItems();super.update(b,d);this.legendItem&&this.legendItem.label&&(this.setLegendColor(),c.colorizeItem(this,!0))}destroyItems(){const b=this.chart,d=this.legendItem||{};if(d.label)b.legend.destroyItem(this);else if(d.labels)for(const c of d.labels)b.legend.destroyItem(c);b.isDirtyLegend=!0}destroy(){this.chart.isDirtyLegend=
!0;this.destroyItems();super.destroy(...[].slice.call(arguments))}remove(b){this.destroyItems();super.remove(b)}getDataClassLegendSymbols(){const b=this,d=b.chart,k=b.legendItem&&b.legendItem.labels||[],h=d.options.legend,e=c(h.valueDecimals,-1),m=c(h.valueSuffix,""),f=d=>b.series.reduce((b,c)=>{b.push(...c.points.filter(b=>b.dataClass===d));return b},[]);let w;k.length||b.dataClasses.forEach((c,r)=>{const h=c.from,x=c.to,{numberFormatter:a}=d;let C=!0;w="";"undefined"===typeof h?w="< ":"undefined"===
typeof x&&(w="> ");"undefined"!==typeof h&&(w+=a(h,e)+m);"undefined"!==typeof h&&"undefined"!==typeof x&&(w+=" - ");"undefined"!==typeof x&&(w+=a(x,e)+m);k.push(t({chart:d,name:w,options:{},drawLegendSymbol:l.rectangle,visible:!0,isDataClass:!0,setState:b=>{for(const d of f(r))d.setState(b)},setVisible:function(){this.visible=C=b.visible=!C;for(const b of f(r))b.setVisible(C);d.legend.colorizeItem(this,C)}},c))});return k}}k.defaultColorAxisOptions=z;k.defaultLegendLength=200;k.keepProps=["legendItem"];
Array.prototype.push.apply(a.keepProps,k.keepProps);"";return k});y(a,"Maps/MapNavigationDefaults.js",[a["Core/Defaults.js"],a["Core/Utilities.js"]],function(a,p){({extend:p}=p);const g={buttonOptions:{alignTo:"plotBox",align:"left",verticalAlign:"top",x:0,width:18,height:18,padding:5,style:{color:"#666666",fontSize:"1em",fontWeight:"bold"},theme:{fill:"#ffffff",stroke:"#e6e6e6","stroke-width":1,"text-align":"center"}},buttons:{zoomIn:{onclick:function(){this.mapZoom(.5)},text:"+",y:0},zoomOut:{onclick:function(){this.mapZoom(2)},
text:"-",y:28}},mouseWheelSensitivity:1.1};p(a.defaultOptions.lang,{zoomIn:"Zoom in",zoomOut:"Zoom out"});return a.defaultOptions.mapNavigation=g});y(a,"Maps/MapNavigation.js",[a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,p,q){function g(e){e&&(e.preventDefault&&e.preventDefault(),e.stopPropagation&&e.stopPropagation(),e.cancelBubble=!0)}function l(e){this.navButtons=[];this.init(e)}const {doc:n}=p,{addEvent:A,extend:u,isNumber:v,merge:t,objectEach:f,pick:F}=q;
l.prototype.init=function(e){this.chart=e};l.prototype.update=function(e){function c(d){this.handler.call(b,d);g(d)}let k=this,b=this.chart,d=b.options.mapNavigation,a,h=k.navButtons;e&&(d=b.options.mapNavigation=t(b.options.mapNavigation,e));for(;h.length;)h.pop().destroy();F(d.enableButtons,d.enabled)&&!b.renderer.forExport&&(k.navButtonsGroup||(k.navButtonsGroup=b.renderer.g().attr({zIndex:4}).add()),f(d.buttons,function(e,m){var f;e=t(d.buttonOptions,e);!b.styledMode&&e.theme&&(a=e.theme,a.style=
t(e.theme.style,e.style));const {text:w,width:E=0,height:r=0,padding:B=0}=e,D=b.renderer.button("+"!==w&&"-"!==w&&w||"",0,0,c,a,void 0,void 0,void 0,"zoomIn"===m?"topbutton":"bottombutton").addClass("highcharts-map-navigation highcharts-"+{zoomIn:"zoom-in",zoomOut:"zoom-out"}[m]).attr({width:E,height:r,title:b.options.lang[m],padding:e.padding,zIndex:5}).add(k.navButtonsGroup);if("+"===w||"-"===w){m=E+1;const d=[["M",B+3,B+r/2],["L",B+m-3,B+r/2]];"+"===w&&d.push(["M",B+m/2,B+3],["L",B+m/2,B+r-3]);
b.renderer.path(d).addClass("highcharts-button-symbol").attr(b.styledMode?{}:{stroke:null===(f=e.style)||void 0===f?void 0:f.color,"stroke-width":3,"stroke-linecap":"round"}).add(D)}D.handler=e.onclick;A(D.element,"dblclick",g);h.push(D);u(e,{width:D.width,height:2*D.height});if(b.hasLoaded)D.align(e,!1,e.alignTo);else{const d=A(b,"load",()=>{D.element&&D.align(e,!1,e.alignTo);d()})}}),e=function(){var c=b.exportingGroup&&b.exportingGroup.getBBox();if(c){const b=k.navButtonsGroup.getBBox();if(!(b.x>=
c.x+c.width||b.x+b.width<=c.x||b.y>=c.y+c.height||b.y+b.height<=c.y)){const e=-b.y-b.height+c.y-5;c=c.y+c.height-b.y+5;k.navButtonsGroup.attr({translateY:"bottom"===(d.buttonOptions&&d.buttonOptions.verticalAlign)?e:c})}}},b.hasLoaded||A(b,"render",e));this.updateEvents(d)};l.prototype.updateEvents=function(e){const c=this.chart;F(e.enableDoubleClickZoom,e.enabled)||e.enableDoubleClickZoomTo?this.unbindDblClick=this.unbindDblClick||A(c.container,"dblclick",function(e){c.pointer.onContainerDblClick(e)}):
this.unbindDblClick&&(this.unbindDblClick=this.unbindDblClick());F(e.enableMouseWheelZoom,e.enabled)?this.unbindMouseWheel=this.unbindMouseWheel||A(c.container,void 0!==n.onwheel?"wheel":void 0!==n.onmousewheel?"mousewheel":"DOMMouseScroll",function(e){c.pointer.inClass(e.target,"highcharts-no-mousewheel")||(c.pointer.onContainerMouseWheel(e),g(e));return!1}):this.unbindMouseWheel&&(this.unbindMouseWheel=this.unbindMouseWheel())};u(a.prototype,{fitToBox:function(e,c){[["x","width"],["y","height"]].forEach(function(k){const b=
k[0];k=k[1];e[b]+e[k]>c[b]+c[k]&&(e[k]>c[k]?(e[k]=c[k],e[b]=c[b]):e[b]=c[b]+c[k]-e[k]);e[k]>c[k]&&(e[k]=c[k]);e[b]<c[b]&&(e[b]=c[b])});return e},mapZoom:function(e,c,k,b,d){this.mapView&&(v(e)&&(e=Math.log(e)/Math.log(.5)),this.mapView.zoomBy(e,v(c)&&v(k)?this.mapView.projection.inverse([c,k]):void 0,v(b)&&v(d)?[b,d]:void 0))}});A(a,"beforeRender",function(){this.mapNavigation=new l(this);this.mapNavigation.update()});p.MapNavigation=l});y(a,"Maps/MapPointer.js",[a["Core/Pointer.js"],a["Core/Utilities.js"]],
function(a,p){const {defined:g,extend:z,pick:l,wrap:n}=p,A=a.prototype.normalize;let u=0,v;z(a.prototype,{normalize:function(t,f){const a=this.chart;t=A.call(this,t,f);a&&a.mapView&&(f=a.mapView.pixelsToLonLat({x:t.chartX-a.plotLeft,y:t.chartY-a.plotTop}))&&z(t,f);return t},onContainerDblClick:function(a){const f=this.chart;a=this.normalize(a);f.options.mapNavigation.enableDoubleClickZoomTo?f.pointer.inClass(a.target,"highcharts-tracker")&&f.hoverPoint&&f.hoverPoint.zoomTo():f.isInsidePlot(a.chartX-
f.plotLeft,a.chartY-f.plotTop)&&f.mapZoom(.5,void 0,void 0,a.chartX,a.chartY)},onContainerMouseWheel:function(a){const f=this.chart;a=this.normalize(a);const t=g(a.wheelDelta)&&-a.wheelDelta/120||a.deltaY||a.detail;1<=Math.abs(t)&&(u+=Math.abs(t),v&&clearTimeout(v),v=setTimeout(()=>{u=0},50));10>u&&f.isInsidePlot(a.chartX-f.plotLeft,a.chartY-f.plotTop)&&f.mapView&&f.mapView.zoomBy((f.options.mapNavigation.mouseWheelSensitivity-1)*-t,void 0,[a.chartX,a.chartY],1>Math.abs(t)?!1:void 0)}});n(a.prototype,
"zoomOption",function(a){const f=this.chart.options.mapNavigation;l(f.enableTouchZoom,f.enabled)&&(this.chart.zooming.pinchType="xy");a.apply(this,[].slice.call(arguments,1))});n(a.prototype,"pinchTranslate",function(a,f,l,e,c,k,b){a.call(this,f,l,e,c,k,b);"map"===this.chart.options.chart.type&&this.hasZoom&&(a=e.scaleX>e.scaleY,this.pinchTranslateDirection(!a,f,l,e,c,k,b,a?e.scaleX:e.scaleY))})});y(a,"Series/ColorMapComposition.js",[a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,
p){const {column:{prototype:g}}=a.seriesTypes,{addEvent:z,defined:l}=p;var n;(function(a){function n(a){this.moveToTopOnHover&&this.graphic&&this.graphic.attr({zIndex:a&&"hover"===a.state?1:0})}const q=[];a.pointMembers={dataLabelOnNull:!0,moveToTopOnHover:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value&&(void 0===this.value||!isNaN(this.value))}};a.seriesMembers={colorKey:"value",axisTypes:["xAxis","yAxis","colorAxis"],parallelArrays:["x","y","value"],
pointArrayMap:["value"],trackerGroups:["group","markerGroup","dataLabelsGroup"],colorAttribs:function(a){const f={};!l(a.color)||a.state&&"normal"!==a.state||(f[this.colorProp||"fill"]=a.color);return f},pointAttribs:g.pointAttribs};a.compose=function(a){const f=a.prototype.pointClass;p.pushUnique(q,f)&&z(f,"afterSetState",n);return a}})(n||(n={}));return n});y(a,"Maps/MapSymbols.js",[a["Core/Renderer/SVG/SVGRenderer.js"]],function(a){const {prototype:{symbols:g}}=a;g.bottombutton=function(a,p,l,
n,A){if(A){const a=(null===A||void 0===A?void 0:A.r)||0;A.brBoxY=p-a;A.brBoxHeight=n+a}return g.roundedRect(a,p,l,n,A)};g.topbutton=function(a,p,l,n,A){A&&(A.brBoxHeight=n+((null===A||void 0===A?void 0:A.r)||0));return g.roundedRect(a,p,l,n,A)};return g});y(a,"Core/Chart/MapChart.js",[a["Core/Chart/Chart.js"],a["Core/Defaults.js"],a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,p,q,z){const {getOptions:l}=p,{merge:g,pick:A}=z;class u extends a{init(a,t){const f=l().credits;
a=g({chart:{panning:{enabled:!0,type:"xy"},type:"map"},credits:{mapText:A(f.mapText,' \u00a9 <a href="{geojson.copyrightUrl}">{geojson.copyrightShort}</a>'),mapTextFull:A(f.mapTextFull,"{geojson.copyright}")},mapView:{},tooltip:{followTouchMove:!1}},a);super.init(a,t)}}(function(a){a.maps={};a.mapChart=function(t,f,l){return new a(t,f,l)};a.splitPath=function(a){"string"===typeof a&&(a=a.replace(/([A-Za-z])/g," $1 ").replace(/^\s*/,"").replace(/\s*$/,""),a=a.split(/[ ,;]+/).map(a=>/[A-za-z]/.test(a)?
a:parseFloat(a)));return q.prototype.pathToSegments(a)}})(u||(u={}));return u});y(a,"Maps/MapUtilities.js",[],function(){return{boundsFromPath:function(a){let g=-Number.MAX_VALUE,q=Number.MAX_VALUE,z=-Number.MAX_VALUE,l=Number.MAX_VALUE,n;a.forEach(a=>{const u=a[a.length-2];a=a[a.length-1];"number"===typeof u&&"number"===typeof a&&(q=Math.min(q,u),g=Math.max(g,u),l=Math.min(l,a),z=Math.max(z,a),n=!0)});if(n)return{x1:q,y1:l,x2:g,y2:z}},pointInPolygon:function(a,p){let g,z,l,n=!1,A=a.x,u=a.y;a=0;for(g=
p.length-1;a<p.length;g=a++)z=p[a][1]>u,l=p[g][1]>u,z!==l&&A<(p[g][0]-p[a][0])*(u-p[a][1])/(p[g][1]-p[a][1])+p[a][0]&&(n=!n);return n}}});y(a,"Series/Map/MapPoint.js",[a["Series/ColorMapComposition.js"],a["Maps/MapUtilities.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,p,q,z){const {boundsFromPath:l}=p;({seriesTypes:{scatter:p}}=q);const {extend:n,isNumber:g,pick:u}=z;class v extends p.prototype.pointClass{constructor(){super(...arguments);this.series=this.path=this.options=
void 0}static getProjectedPath(a,f){a.projectedPath||(f&&a.geometry?(f.hasCoordinates=!0,a.projectedPath=f.path(a.geometry)):a.projectedPath=a.path);return a.projectedPath||[]}applyOptions(a,f){const l=this.series;a=super.applyOptions.call(this,a,f);f=l.joinBy;l.mapData&&l.mapMap&&(f=super.getNestedProperty.call(a,f[1]),(f="undefined"!==typeof f&&l.mapMap[f])?n(a,f):-1!==l.pointArrayMap.indexOf("value")&&(a.value=a.value||null));return a}getProjectedBounds(a){var f=v.getProjectedPath(this,a);f=l(f);
var n=this.properties;const e=this.series.chart.mapView;if(f){const c=n&&n["hc-middle-lon"],k=n&&n["hc-middle-lat"];e&&g(c)&&g(k)?(a=a.forward([c,k]),f.midX=a[0],f.midY=a[1]):(a=n&&n["hc-middle-x"],n=n&&n["hc-middle-y"],f.midX=f.x1+(f.x2-f.x1)*u(this.middleX,g(a)?a:.5),a=u(this.middleY,g(n)?n:.5),this.geometry||(a=1-a),f.midY=f.y2-(f.y2-f.y1)*a);return f}}onMouseOver(a){z.clearTimeout(this.colorInterval);if(!this.isNull&&this.visible||this.series.options.nullInteraction)super.onMouseOver.call(this,
a);else this.series.onMouseOut(a)}setVisible(a){const f=a?"show":"hide";this.visible=this.options.visible=!!a;if(this.dataLabel)this.dataLabel[f]();this.graphic&&this.graphic.attr(this.series.pointAttribs(this))}zoomTo(a){const f=this.series.chart,l=f.mapView;var e=this.bounds;if(l&&e){const k=g(this.insetIndex)&&l.insets[this.insetIndex];if(k){var c=k.projectedUnitsToPixels({x:e.x1,y:e.y1});e=k.projectedUnitsToPixels({x:e.x2,y:e.y2});c=l.pixelsToProjectedUnits({x:c.x,y:c.y});e=l.pixelsToProjectedUnits({x:e.x,
y:e.y});e={x1:c.x,y1:c.y,x2:e.x,y2:e.y}}l.fitToBounds(e,void 0,!1);this.series.isDirty=!0;f.redraw(a)}}}n(v.prototype,{dataLabelOnNull:a.pointMembers.dataLabelOnNull,moveToTopOnHover:a.pointMembers.moveToTopOnHover,isValid:a.pointMembers.isValid});return v});y(a,"Maps/MapViewOptionsDefault.js",[],function(){return{center:[0,0],fitToGeometry:void 0,maxZoom:void 0,padding:0,projection:{name:void 0,parallels:void 0,rotation:void 0},zoom:void 0}});y(a,"Maps/MapViewInsetsOptionsDefault.js",[],function(){return{borderColor:"#cccccc",
borderWidth:1,center:[0,0],padding:"10%",relativeTo:"mapBoundingBox",units:"percent"}});y(a,"Extensions/GeoJSON.js",[a["Core/Chart/Chart.js"],a["Core/Templating.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,p,q,z){function l(a,c){c||(c=Object.keys(a.objects)[0]);c=a.objects[c];if(c["hc-decoded-geojson"])return c["hc-decoded-geojson"];let e=a.arcs;if(a.transform){const {scale:b,translate:d}=a.transform;e=a.arcs.map(a=>{let c=0,e=0;return a.map(a=>{a=a.slice();a[0]=(c+=a[0])*b[0]+d[0];
a[1]=(e+=a[1])*b[1]+d[1];return a})})}const b=a=>"number"===typeof a[0]?a.reduce((b,a,d)=>{let c=0>a?e[~a]:e[a];0>a?(c=c.slice(0,0===d?c.length:c.length-1),c.reverse()):d&&(c=c.slice(1));return b.concat(c)},[]):a.map(b),d=c.geometries.map(a=>({type:"Feature",properties:a.properties,geometry:{type:a.type,coordinates:a.coordinates||b(a.arcs)}}));a={type:"FeatureCollection",copyright:a.copyright,copyrightShort:a.copyrightShort,copyrightUrl:a.copyrightUrl,features:d,"hc-recommended-mapview":c["hc-recommended-mapview"],
bbox:a.bbox,title:a.title};return c["hc-decoded-geojson"]=a}function n(a,c="map",k){const b=[];a="Topology"===a.type?l(a):a;a.features.forEach(function(a){var d=a.geometry||{},h=d.type;d=d.coordinates;a=a.properties;let e;"map"!==c&&"mapbubble"!==c||"Polygon"!==h&&"MultiPolygon"!==h?"mapline"!==c||"LineString"!==h&&"MultiLineString"!==h?"mappoint"===c&&"Point"===h&&d.length&&(e={geometry:{coordinates:d,type:h}}):d.length&&(e={geometry:{coordinates:d,type:h}}):d.length&&(e={geometry:{coordinates:d,
type:h}});if(e){h=a&&(a.name||a.NAME);d=a&&a.lon;const c=a&&a.lat;b.push(t(e,{lat:"number"===typeof c?c:void 0,lon:"number"===typeof d?d:void 0,name:"string"===typeof h?h:void 0,properties:a}))}});k&&a.copyrightShort&&(k.chart.mapCredits=g(k.chart.options.credits.mapText,{geojson:a}),k.chart.mapCreditsFull=g(k.chart.options.credits.mapTextFull,{geojson:a}));return b}const {format:g}=p,{win:u}=q,{error:v,extend:t,merge:f,wrap:F}=z;"";a.prototype.transformFromLatLon=function(a,c){var e=this.options.chart.proj4||
u.proj4;if(e){var {jsonmarginX:b=0,jsonmarginY:d=0,jsonres:f=1,scale:h=1,xoffset:l=0,xpan:m=0,yoffset:x=0,ypan:w=0}=c;a=e(c.crs,[a.lon,a.lat]);e=c.cosAngle||c.rotation&&Math.cos(c.rotation);var n=c.sinAngle||c.rotation&&Math.sin(c.rotation);c=c.rotation?[a[0]*e+a[1]*n,-a[0]*n+a[1]*e]:a;return{x:((c[0]-l)*h+m)*f+b,y:-(((x-c[1])*h+w)*f-d)}}v(21,!1,this)};a.prototype.transformToLatLon=function(a,c){const e=this.options.chart.proj4||u.proj4;if(!e)v(21,!1,this);else if(null!==a.y){var {jsonmarginX:b=0,
jsonmarginY:d=0,jsonres:f=1,scale:h=1,xoffset:l=0,xpan:m=0,yoffset:x=0,ypan:w=0}=c;a={x:((a.x-b)/f-m)/h+l,y:((a.y-d)/f+w)/h+x};var n=c.cosAngle||c.rotation&&Math.cos(c.rotation),r=c.sinAngle||c.rotation&&Math.sin(c.rotation);c=e(c.crs,"WGS84",c.rotation?{x:a.x*n+a.y*-r,y:a.x*r+a.y*n}:a);return{lat:c.y,lon:c.x}}};a.prototype.fromPointToLatLon=function(a){return this.mapView&&this.mapView.projectedUnitsToLonLat(a)};a.prototype.fromLatLonToPoint=function(a){return this.mapView&&this.mapView.lonLatToProjectedUnits(a)};
F(a.prototype,"addCredits",function(a,c){c=f(!0,this.options.credits,c);this.mapCredits&&(c.href=null);a.call(this,c);this.credits&&this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})});q.geojson=n;q.topo2geo=l;return{geojson:n,topo2geo:l}});y(a,"Core/Geometry/PolygonClip.js",[],function(){const a=(a,l,n)=>(l[0]-a[0])*(n[1]-a[1])>(l[1]-a[1])*(n[0]-a[0]),p=(a,l,n,g)=>{var u=[a[0]-l[0],a[1]-l[1]];const q=[n[0]-g[0],n[1]-g[1]];a=a[0]*l[1]-a[1]*l[0];n=n[0]*g[1]-n[1]*g[0];g=1/(u[0]*q[1]-
u[1]*q[0]);u=[(a*q[0]-n*u[0])*g,(a*q[1]-n*u[1])*g];u.isIntersection=!0;return u};var q;(function(g){g.clipLineString=(a,n)=>{const l=[];a=g.clipPolygon(a,n,!1);for(n=1;n<a.length;n++)a[n].isIntersection&&a[n-1].isIntersection&&(l.push(a.splice(0,n)),n=0),n===a.length-1&&l.push(a);return l};g.clipPolygon=(l,n,g=!0)=>{let q=n[n.length-1],v,t,f=l;for(let u=0;u<n.length;u++){const e=f;l=n[u];f=[];v=g?e[e.length-1]:e[0];for(let c=0;c<e.length;c++)t=e[c],a(q,l,t)?(a(q,l,v)||f.push(p(q,l,v,t)),f.push(t)):
a(q,l,v)&&f.push(p(q,l,v,t)),v=t;q=l}return f}})(q||(q={}));return q});y(a,"Maps/Projections/LambertConformalConic.js",[],function(){const a=Math.sign||(a=>0===a?0:0<a?1:-1),p=Math.PI/180,q=Math.PI/2;class z{constructor(l){var n,g=(l.parallels||[]).map(a=>a*p);const u=g[0]||0;g=null!==(n=g[1])&&void 0!==n?n:u;n=Math.cos(u);"object"===typeof l.projectedBounds&&(this.projectedBounds=l.projectedBounds);l=u===g?Math.sin(u):Math.log(n/Math.cos(g))/Math.log(Math.tan((q+g)/2)/Math.tan((q+u)/2));1e-10>Math.abs(l)&&
(l=1e-10*(a(l)||1));this.n=l;this.c=n*Math.pow(Math.tan((q+u)/2),l)/l}forward(a){var n=a[0]*p;const {c:l,n:g,projectedBounds:v}=this;a=a[1]*p;0<l?a<-q+.000001&&(a=-q+.000001):a>q-.000001&&(a=q-.000001);var t=l/Math.pow(Math.tan((q+a)/2),g);a=t*Math.sin(g*n)*63.78137;n=63.78137*(l-t*Math.cos(g*n));t=[a,n];v&&(a<v.x1||a>v.x2||n<v.y1||n>v.y2)&&(t.outside=!0);return t}inverse(l){const n=l[0]/63.78137;l=l[1]/63.78137;const {c:g,n:u}=this;l=g-l;const v=a(u)*Math.sqrt(n*n+l*l);let t=Math.atan2(n,Math.abs(l))*
a(l);0>l*u&&(t-=Math.PI*a(n)*a(l));return[t/u/p,(2*Math.atan(Math.pow(g/v,1/u))-q)/p]}}return z});y(a,"Maps/Projections/EqualEarth.js",[],function(){const a=Math.sqrt(3)/2;class p{constructor(){this.bounds={x1:-200.37508342789243,x2:200.37508342789243,y1:-97.52595454902263,y2:97.52595454902263}}forward(g){const q=Math.PI/180,l=Math.asin(a*Math.sin(g[1]*q)),n=l*l,p=n*n*n;return[g[0]*q*Math.cos(l)*74.03120656864502/(a*(1.340264+3*-.081106*n+p*(7*.000893+.034164*n))),74.03120656864502*l*(1.340264+-.081106*
n+p*(.000893+.003796*n))]}inverse(g){const q=g[0]/74.03120656864502;g=g[1]/74.03120656864502;const l=180/Math.PI;let n=g;let p;let u;for(u=0;12>u;++u){var v=n*n;p=v*v*v;var t=n*(1.340264+-.081106*v+p*(.000893+.003796*v))-g;v=1.340264+3*-.081106*v+p*(7*.000893+.034164*v);n-=t/=v;if(1e-9>Math.abs(t))break}v=n*n;return[l*a*q*(1.340264+3*-.081106*v+v*v*v*(7*.000893+.034164*v))/Math.cos(n),l*Math.asin(Math.sin(n)/a)]}}return p});y(a,"Maps/Projections/Miller.js",[],function(){const a=Math.PI/4,p=Math.PI/
180;class q{constructor(){this.bounds={x1:-200.37508342789243,x2:200.37508342789243,y1:-146.91480769173063,y2:146.91480769173063}}forward(g){return[g[0]*p*63.78137,79.7267125*Math.log(Math.tan(a+.4*g[1]*p))]}inverse(g){return[g[0]/63.78137/p,2.5*(Math.atan(Math.exp(g[1]/63.78137*.8))-a)/p]}}return q});y(a,"Maps/Projections/Orthographic.js",[],function(){const a=Math.PI/180;class p{constructor(){this.antimeridianCutting=!1;this.bounds={x1:-63.78460826781007,x2:63.78460826781007,y1:-63.78460826781007,
y2:63.78460826781007}}forward(g){const p=g[0];g=g[1]*a;g=[Math.cos(g)*Math.sin(p*a)*63.78460826781007,63.78460826781007*Math.sin(g)];if(-90>p||90<p)g.outside=!0;return g}inverse(g){const p=g[0]/63.78460826781007;g=g[1]/63.78460826781007;const l=Math.sqrt(p*p+g*g),n=Math.asin(l),q=Math.sin(n);return[Math.atan2(p*q,l*Math.cos(n))/a,Math.asin(l&&g*q/l)/a]}}return p});y(a,"Maps/Projections/WebMercator.js",[],function(){const a=Math.PI/180;class p{constructor(){this.bounds={x1:-200.37508342789243,x2:200.37508342789243,
y1:-200.3750834278071,y2:200.3750834278071};this.maxLatitude=85.0511287798}forward(g){var p=Math.sin(g[1]*a);p=[63.78137*g[0]*a,63.78137*Math.log((1+p)/(1-p))/2];85.0511287798<Math.abs(g[1])&&(p.outside=!0);return p}inverse(g){return[g[0]/(63.78137*a),(2*Math.atan(Math.exp(g[1]/63.78137))-Math.PI/2)/a]}}return p});y(a,"Maps/Projections/ProjectionRegistry.js",[a["Maps/Projections/LambertConformalConic.js"],a["Maps/Projections/EqualEarth.js"],a["Maps/Projections/Miller.js"],a["Maps/Projections/Orthographic.js"],
a["Maps/Projections/WebMercator.js"]],function(a,p,q,z,l){return{EqualEarth:p,LambertConformalConic:a,Miller:q,Orthographic:z,WebMercator:l}});y(a,"Maps/Projection.js",[a["Core/Geometry/PolygonClip.js"],a["Maps/Projections/ProjectionRegistry.js"],a["Core/Utilities.js"]],function(a,p,q){const {clipLineString:g,clipPolygon:l}=a,{clamp:n,erase:A}=q,u=2*Math.PI/360,v=a=>{-180>a&&(a+=360);180<a&&(a-=360);return a};class t{static add(a,g){t.registry[a]=g}static greatCircle(a,g,e){const {atan2:c,cos:k,sin:b,
sqrt:d}=Math,f=a[1]*u,h=a[0]*u,n=g[1]*u,m=g[0]*u;var x=n-f,w=m-h;x=b(x/2)*b(x/2)+k(f)*k(n)*b(w/2)*b(w/2);x=2*c(d(x),d(1-x));var l=Math.round(6371E3*x/5E5);w=[];e&&w.push(a);if(1<l)for(a=1/l,l=a;.999>l;l+=a){var r=b((1-l)*x)/b(x);const a=b(l*x)/b(x);var B=r*k(f)*k(h)+a*k(n)*k(m);const e=r*k(f)*b(h)+a*k(n)*b(m);r=r*b(f)+a*b(n);r=c(r,d(B*B+e*e));B=c(e,B);w.push([B/u,r/u])}e&&w.push(g);return w}static insertGreatCircles(a){let f=a.length-1;for(;f--;)if(10<Math.max(Math.abs(a[f][0]-a[f+1][0]),Math.abs(a[f][1]-
a[f+1][1]))){const e=t.greatCircle(a[f],a[f+1]);e.length&&a.splice(f+1,0,...e)}}static toString(a){const {name:f,rotation:e}=a||{};return[f,e&&e.join(",")].join(";")}constructor(a={}){this.hasGeoProjection=this.hasCoordinates=!1;this.maxLatitude=90;this.options=a;const {name:f,projectedBounds:e,rotation:c}=a;this.rotator=c?this.getRotator(c):void 0;const k=f?t.registry[f]:void 0;k&&(this.def=new k(a));const {def:b,rotator:d}=this;b&&(this.maxLatitude=b.maxLatitude||90,this.hasGeoProjection=!0);d&&
b?(this.forward=a=>b.forward(d.forward(a)),this.inverse=a=>d.inverse(b.inverse(a))):b?(this.forward=a=>b.forward(a),this.inverse=a=>b.inverse(a)):d&&(this.forward=d.forward,this.inverse=d.inverse);this.bounds="world"===e?b&&b.bounds:e}lineIntersectsBounds(a){const {x1:f,x2:e,y1:c,y2:k}=this.bounds||{},b=(a,b,d)=>{const [c,e]=a;a=b?0:1;if("number"===typeof d&&c[b]>=d!==e[b]>=d)return a=c[a]+(d-c[b])/(e[b]-c[b])*(e[a]-c[a]),b?[a,d]:[d,a]};let d,g=a[0];if(d=b(a,0,f))g=d,a[1]=d;else if(d=b(a,0,e))g=d,
a[1]=d;if(d=b(a,1,c))g=d;else if(d=b(a,1,k))g=d;return g}getRotator(a){const f=a[0]*u,e=(a[1]||0)*u;a=(a[2]||0)*u;const c=Math.cos(e),k=Math.sin(e),b=Math.cos(a),d=Math.sin(a);if(0!==f||0!==e||0!==a)return{forward:a=>{var e=a[0]*u+f,g=a[1]*u,m=Math.cos(g);a=Math.cos(e)*m;e=Math.sin(e)*m;g=Math.sin(g);m=g*c+a*k;return[Math.atan2(e*b-m*d,a*c-g*k)/u,Math.asin(m*b+e*d)/u]},inverse:a=>{var e=a[0]*u,g=a[1]*u,m=Math.cos(g);a=Math.cos(e)*m;e=Math.sin(e)*m;g=Math.sin(g);m=g*b-e*d;return[(Math.atan2(e*b+g*
d,a*c+m*k)-f)/u,Math.asin(m*c-a*k)/u]}}}forward(a){return a}inverse(a){return a}cutOnAntimeridian(a,g){const e=[],c=[a];a.forEach((b,d)=>{let c=a[d-1];if(!d){if(!g)return;c=a[a.length-1]}const k=c[0];var r=b[0];(-90>k||90<k)&&(-90>r||90<r)&&0<k!==0<r&&(r=n((180-(k+360)%360)/((r+360)%360-(k+360)%360),0,1),e.push({i:d,lat:c[1]+r*(b[1]-c[1]),direction:0>k?1:-1,previousLonLat:c,lonLat:b}))});if(e.length)if(g){if(1===e.length%2){var k=e.slice().sort((a,b)=>Math.abs(b.lat)-Math.abs(a.lat))[0];A(e,k)}for(var b=
e.length-2;0<=b;){var d=e[b].i,f=v(180+.000001*e[b].direction),h=v(180-.000001*e[b].direction);d=a.splice(d,e[b+1].i-d,...t.greatCircle([f,e[b].lat],[f,e[b+1].lat],!0));d.push(...t.greatCircle([h,e[b+1].lat],[h,e[b].lat],!0));c.push(d);b-=2}if(k)for(d=0;d<c.length;d++){const {direction:a,lat:e}=k;b=c[d];h=b.indexOf(k.lonLat);if(-1<h){d=(0>e?-1:1)*this.maxLatitude;var l=v(180+.000001*a);f=v(180-.000001*a);const c=t.greatCircle([l,e],[l,d],!0);for(l+=120*a;-180<l&&180>l;l+=120*a)c.push([l,d]);c.push(...t.greatCircle([f,
d],[f,k.lat],!0));b.splice(h,0,...c);break}}}else for(k=e.length;k--;)b=a.splice(e[k].i,a.length,[v(180+.000001*e[k].direction),e[k].lat]),b.unshift([v(180-.000001*e[k].direction),e[k].lat]),c.push(b);return c}path(a){const {bounds:f,def:e,rotator:c}=this,k=[],b="Polygon"===a.type||"MultiPolygon"===a.type,d=this.hasGeoProjection,n=!e||!1!==e.antimeridianCutting,h=n?c:void 0,p=n?e||this:this;let m;f&&(m=[[f.x1,f.y1],[f.x2,f.y1],[f.x2,f.y2],[f.x1,f.y2]]);const x=a=>{a=a.map(a=>{if(n){h&&(a=h.forward(a));
let b=a[0];.000001>Math.abs(b-180)&&(b=180>b?179.999999:180.000001);a=[b,a[1]]}return a});let c=[a];d&&(t.insertGreatCircles(a),n&&(c=this.cutOnAntimeridian(a,b)));c.forEach(a=>{if(!(2>a.length)){var c=!1,r=!1,e=a=>{c?k.push(["L",a[0],a[1]]):(k.push(["M",a[0],a[1]]),c=!0)},h=!1,w=!1,x=a.map(a=>{a=p.forward(a);a.outside?h=!0:w=!0;Infinity===a[1]?a[1]=1E10:-Infinity===a[1]&&(a[1]=-1E10);return a});if(n){b&&x.push(x[0]);if(h){if(!w)return;if(m)if(b)x=l(x,m);else if(f){g(x,m).forEach(a=>{c=!1;a.forEach(e)});
return}}x.forEach(e)}else for(let k=0;k<x.length;k++){const h=a[k],m=x[k];if(m.outside)r=!0;else{if(b&&!u){var u=h;a.push(h);x.push(m)}r&&q&&(b&&d?t.greatCircle(q,h).forEach(a=>e(p.forward(a))):c=!1);e(m);var q=h;r=!1}}}})};"LineString"===a.type?x(a.coordinates):"MultiLineString"===a.type?a.coordinates.forEach(a=>x(a)):"Polygon"===a.type?(a.coordinates.forEach(a=>x(a)),k.length&&k.push(["Z"])):"MultiPolygon"===a.type&&(a.coordinates.forEach(a=>{a.forEach(a=>x(a))}),k.length&&k.push(["Z"]));return k}}
t.registry=p;return t});y(a,"Maps/MapView.js",[a["Maps/MapViewOptionsDefault.js"],a["Maps/MapViewInsetsOptionsDefault.js"],a["Extensions/GeoJSON.js"],a["Core/Chart/MapChart.js"],a["Maps/MapUtilities.js"],a["Maps/Projection.js"],a["Core/Utilities.js"]],function(a,p,q,z,l,n,A){const {topo2geo:g}=q,{maps:v}=z,{boundsFromPath:t,pointInPolygon:f}=l,{addEvent:F,clamp:e,fireEvent:c,isArray:k,isNumber:b,isObject:d,isString:E,merge:h,pick:C,relativeLength:m}=A,x=(a,b)=>{const {width:c,height:d}=b;return Math.log(400.979322/
Math.max((a.x2-a.x1)/(c/256),(a.y2-a.y1)/(d/256)))/Math.log(2)};class w{static mergeInsets(a,b){const c=a=>{const b={};a.forEach((a,c)=>{b[a&&a.id||`i${c}`]=a});return b},d=h(c(a),c(b));return Object.keys(d).map(a=>d[a])}createInsets(){const a=this.options,b=a.insets;b&&b.forEach(b=>{b=new G(this,h(a.insetOptions,b));this.insets.push(b)})}constructor(d,e){this.allowTransformAnimation=!0;this.insets=[];this.padding=[0,0,0,0];this.eventsToUnbind=[];let r,k;if(!(this instanceof G)){var m=[d.options.chart.map,
...(d.options.series||[]).map(a=>a.mapData)].map(a=>this.getGeoMap(a));const a=[];m.forEach(b=>{if(b&&(r||(r=b["hc-recommended-mapview"]),b.bbox)){const [d,c,r,e]=b.bbox;a.push({x1:d,y1:c,x2:r,y2:e})}});const b=a.length&&w.compositeBounds(a);c(d,"beforeMapViewInit",{geoBounds:b},function(){if(b){const {x1:a,y1:d,x2:c,y2:r}=b;k=180<c-a&&90<r-d?{name:"EqualEarth"}:{name:"LambertConformalConic",parallels:[d,r],rotation:[-(a+c)/2]}}});this.geoMap=m[0]}this.userOptions=e||{};d.options.mapView&&d.options.mapView.recommendedMapView&&
(r=d.options.mapView.recommendedMapView);m=h(a,{projection:k},r,e);const f=r&&r.insets;e=e&&e.insets;f&&e&&(m.insets=w.mergeInsets(f,e));this.chart=d;this.center=m.center;this.options=m;this.projection=new n(m.projection);this.playingField=d.plotBox;this.zoom=m.zoom||0;this.minZoom=m.minZoom;this.createInsets();this.eventsToUnbind.push(F(d,"afterSetChartSize",()=>{this.playingField=this.getField();if(void 0===this.minZoom||this.minZoom===this.zoom)this.fitToBounds(void 0,void 0,!1),!this.chart.hasRendered&&
b(this.userOptions.zoom)&&(this.zoom=this.userOptions.zoom),this.userOptions.center&&h(!0,this.center,this.userOptions.center)}));this.setUpEvents()}fitToBounds(a,b,d=!0,c){const r=a||this.getProjectedBounds();if(r){var e=C(b,a?0:this.options.padding);b=this.getField(!1);e=k(e)?e:[e,e,e,e];this.padding=[m(e[0],b.height),m(e[1],b.width),m(e[2],b.height),m(e[3],b.width)];this.playingField=this.getField();b=x(r,this.playingField);a||(this.minZoom=b);a=this.projection.inverse([(r.x2+r.x1)/2,(r.y2+r.y1)/
2]);this.setView(a,b,d,c)}}getField(a=!0){a=a?this.padding:[0,0,0,0];return{x:a[3],y:a[0],width:this.chart.plotWidth-a[1]-a[3],height:this.chart.plotHeight-a[0]-a[2]}}getGeoMap(a){if(E(a))return v[a]&&"Topology"===v[a].type?g(v[a]):v[a];if(d(a,!0)){if("FeatureCollection"===a.type)return a;if("Topology"===a.type)return g(a)}}getMapBBox(){const a=this.getProjectedBounds(),b=this.getScale();if(a){const d=this.padding,c=this.projectedUnitsToPixels({x:a.x1,y:a.y2});return{width:(a.x2-a.x1)*b+d[1]+d[3],
height:(a.y2-a.y1)*b+d[0]+d[2],x:c.x-d[3],y:c.y-d[0]}}}getProjectedBounds(){const a=this.projection;var b=this.chart.series.reduce((a,b)=>{const d=b.getProjectedBounds&&b.getProjectedBounds();d&&!1!==b.options.affectsMapView&&a.push(d);return a},[]),d=this.options.fitToGeometry;return d?(this.fitToGeometryCache||("MultiPoint"===d.type?(d=d.coordinates.map(b=>a.forward(b)),b=d.map(a=>a[0]),d=d.map(a=>a[1]),this.fitToGeometryCache={x1:Math.min.apply(0,b),x2:Math.max.apply(0,b),y1:Math.min.apply(0,d),
y2:Math.max.apply(0,d)}):this.fitToGeometryCache=t(a.path(d))),this.fitToGeometryCache):this.projection.bounds||w.compositeBounds(b)}getScale(){return 256/400.979322*Math.pow(2,this.zoom)}getSVGTransform(){const {x:a,y:b,width:d,height:c}=this.playingField,e=this.projection.forward(this.center);var k=this.projection.hasCoordinates?-1:1;const h=this.getScale();k*=h;return{scaleX:h,scaleY:k,translateX:a+d/2-e[0]*h,translateY:b+c/2-e[1]*k}}lonLatToPixels(a){if(a=this.lonLatToProjectedUnits(a))return this.projectedUnitsToPixels(a)}lonLatToProjectedUnits(a){const b=
this.chart,d=b.mapTransforms;if(d){for(const e in d)if(Object.hasOwnProperty.call(d,e)&&d[e].hitZone){var c=b.transformFromLatLon(a,d[e]);if(c&&f(c,d[e].hitZone.coordinates[0]))return c}return b.transformFromLatLon(a,d["default"])}for(c of this.insets)if(c.options.geoBounds&&f({x:a.lon,y:a.lat},c.options.geoBounds.coordinates[0]))return a=c.projection.forward([a.lon,a.lat]),a=c.projectedUnitsToPixels({x:a[0],y:a[1]}),this.pixelsToProjectedUnits(a);a=this.projection.forward([a.lon,a.lat]);if(!a.outside)return{x:a[0],
y:a[1]}}projectedUnitsToLonLat(a){var b=this.chart;const d=b.mapTransforms;if(d){for(const c in d)if(Object.hasOwnProperty.call(d,c)&&d[c].hitZone&&f(a,d[c].hitZone.coordinates[0]))return b.transformToLatLon(a,d[c]);return b.transformToLatLon(a,d["default"])}b=this.projectedUnitsToPixels(a);for(var c of this.insets)if(c.hitZone&&f(b,c.hitZone.coordinates[0]))return a=c.pixelsToProjectedUnits(b),c=c.projection.inverse([a.x,a.y]),{lon:c[0],lat:c[1]};c=this.projection.inverse([a.x,a.y]);return{lon:c[0],
lat:c[1]}}redraw(a){this.chart.series.forEach(a=>{a.useMapGeometry&&(a.isDirty=!0)});this.chart.redraw(a)}setView(a,d,e=!0,k){a&&(this.center=a);"number"===typeof d&&("number"===typeof this.minZoom&&(d=Math.max(d,this.minZoom)),"number"===typeof this.options.maxZoom&&(d=Math.min(d,this.options.maxZoom)),b(d)&&(this.zoom=d));var h=this.getProjectedBounds();if(h){a=this.projection.forward(this.center);const {x:b,y:c,width:e,height:k}=this.playingField;d=this.getScale();var m=this.projectedUnitsToPixels({x:h.x1,
y:h.y1}),f=this.projectedUnitsToPixels({x:h.x2,y:h.y2});h=[(h.x1+h.x2)/2,(h.y1+h.y2)/2];if(!this.chart.series.some(a=>a.isDrilling)){const g=m.x,r=f.y;f=f.x;m=m.y;f-g<e?a[0]=h[0]:g<b&&f<b+e?a[0]+=Math.max(g-b,f-e-b)/d:f>b+e&&g>b&&(a[0]+=Math.min(f-e-b,g-b)/d);m-r<k?a[1]=h[1]:r<c&&m<c+k?a[1]-=Math.max(r-c,m-k-c)/d:m>c+k&&r>c&&(a[1]-=Math.min(m-k-c,r-c)/d);this.center=this.projection.inverse(a)}this.insets.forEach(a=>{a.options.field&&(a.hitZone=a.getHitZone(),a.playingField=a.getField())});this.render()}c(this,
"afterSetView");e&&this.redraw(k)}projectedUnitsToPixels(a){const b=this.getScale(),d=this.projection.forward(this.center),c=this.playingField;return{x:c.x+c.width/2-b*(d[0]-a.x),y:c.y+c.height/2+b*(d[1]-a.y)}}pixelsToLonLat(a){return this.projectedUnitsToLonLat(this.pixelsToProjectedUnits(a))}pixelsToProjectedUnits(a){const {x:b,y:d}=a;a=this.getScale();const c=this.projection.forward(this.center),e=this.playingField;return{x:c[0]+(b-(e.x+e.width/2))/a,y:c[1]-(d-(e.y+e.height/2))/a}}setUpEvents(){const {chart:a}=
this;let d,c,k;const h=h=>{var m=a.pointer.pinchDown,f=this.projection;let {mouseDownX:g,mouseDownY:r}=a;1===m.length&&(g=m[0].chartX,r=m[0].chartY);if("number"===typeof g&&"number"===typeof r){m=`${g},${r}`;const {chartX:l,chartY:w}=h.originalEvent;m!==c&&(c=m,d=this.projection.forward(this.center),k=(this.projection.options.rotation||[0,0]).slice());m=(m=f.def&&f.def.bounds)&&x(m,this.playingField)||-Infinity;if("Orthographic"===f.options.name&&(this.minZoom||Infinity)<1.3*m){if(m=440/(this.getScale()*
Math.min(a.plotWidth,a.plotHeight)),k){f=(g-l)*m-k[0];m=e(-k[1]-(r-w)*m,-80,80);const b=this.zoom;this.update({projection:{rotation:[-f,-m]}},!1);this.fitToBounds(void 0,void 0,!1);this.zoom=b;a.redraw(!1)}}else b(l)&&b(w)&&(f=this.getScale(),f=this.projection.inverse([d[0]+(g-l)/f,d[1]-(r-w)/f*(this.projection.hasCoordinates?1:-1)]),this.setView(f,void 0,!0,!1));h.preventDefault()}};F(a,"pan",h);F(a,"touchpan",h);F(a,"selection",b=>{if(b.resetSelection)this.zoomBy();else{const d=b.x-a.plotLeft,c=
b.y-a.plotTop,{y:e,x:k}=this.pixelsToProjectedUnits({x:d,y:c}),{y:h,x:m}=this.pixelsToProjectedUnits({x:d+b.width,y:c+b.height});this.fitToBounds({x1:k,y1:e,x2:m,y2:h},void 0,!0,b.originalEvent.touches?!1:void 0);/^touch/.test(b.originalEvent.type)||a.showResetZoom();b.preventDefault()}})}render(){this.group||(this.group=this.chart.renderer.g("map-view").attr({zIndex:4}).add())}update(a,d=!0,c){var e=a.projection;e=e&&n.toString(e)!==n.toString(this.options.projection);let k=!1;h(!0,this.userOptions,
a);h(!0,this.options,a);"insets"in a&&(this.insets.forEach(a=>a.destroy()),this.insets.length=0,k=!0);(e||"fitToGeometry"in a)&&delete this.fitToGeometryCache;if(e||k)this.chart.series.forEach(a=>{const b=a.transformGroups;a.clearBounds&&a.clearBounds();a.isDirty=!0;a.isDirtyData=!0;if(k&&b)for(;1<b.length;)(a=b.pop())&&a.destroy()}),e&&(this.projection=new n(this.options.projection)),k&&this.createInsets(),a.center||!Object.hasOwnProperty.call(a,"zoom")||b(a.zoom)||this.fitToBounds(void 0,void 0,
!1);a.center||b(a.zoom)?this.setView(this.options.center,a.zoom,!1):"fitToGeometry"in a&&this.fitToBounds(void 0,void 0,!1);d&&this.chart.redraw(c)}zoomBy(a,b,d,c){var e=this.chart;const k=this.projection.forward(this.center);let [h,m]=b?this.projection.forward(b):[];if("number"===typeof a){a=this.zoom+a;if(d){const [a,c]=d;d=this.getScale();b=c-e.plotTop-e.plotHeight/2;h=k[0]+(a-e.plotLeft-e.plotWidth/2)/d;m=k[1]+b/d}if("number"===typeof h&&"number"===typeof m){e=1-Math.pow(2,this.zoom)/Math.pow(2,
a);var f=k[1]-m;k[0]-=(k[0]-h)*e;k[1]+=f*e;f=this.projection.inverse(k)}this.setView(f,a,void 0,c)}else this.fitToBounds(void 0,void 0,void 0,c)}}w.compositeBounds=a=>{if(a.length)return a.slice(1).reduce((a,b)=>{a.x1=Math.min(a.x1,b.x1);a.y1=Math.min(a.y1,b.y1);a.x2=Math.max(a.x2,b.x2);a.y2=Math.max(a.y2,b.y2);return a},h(a[0]))};class G extends w{constructor(a,b){super(a.chart,b);this.id=b.id;this.mapView=a;this.options=h(p,b);this.allBounds=[];this.options.geoBounds&&(a=a.projection.path(this.options.geoBounds),
this.geoBoundsProjectedBox=t(a),this.geoBoundsProjectedPolygon=a.map(a=>[a[1]||0,a[2]||0]))}getField(a=!0){var d=this.hitZone;if(d){var c=a?this.padding:[0,0,0,0];d=d.coordinates[0];var e=d.map(a=>a[0]);const k=d.map(a=>a[1]);d=Math.min.apply(0,e)+c[3];e=Math.max.apply(0,e)-c[1];const h=Math.min.apply(0,k)+c[0];c=Math.max.apply(0,k)-c[2];if(b(d)&&b(h))return{x:d,y:h,width:e-d,height:c-h}}return super.getField.call(this,a)}getHitZone(){const {chart:a,mapView:b,options:d}=this;var {coordinates:c}=d.field||
{};if(c){c=c[0];if("percent"===d.units){const e="mapBoundingBox"===d.relativeTo&&b.getMapBBox()||h(a.plotBox,{x:0,y:0});c=c.map(a=>[m(`${a[0]}%`,e.width,e.x),m(`${a[1]}%`,e.height,e.y)])}return{type:"Polygon",coordinates:[c]}}}getProjectedBounds(){return w.compositeBounds(this.allBounds)}isInside(a){const {geoBoundsProjectedBox:b,geoBoundsProjectedPolygon:d}=this;return!!(b&&a.x>=b.x1&&a.x<=b.x2&&a.y>=b.y1&&a.y<=b.y2&&d&&f(a,d))}render(){const {chart:a,mapView:b,options:d}=this;var c=d.borderPath||
d.field;if(c&&b.group){let e=!0;this.border||(this.border=a.renderer.path().addClass("highcharts-mapview-inset-border").add(b.group),e=!1);a.styledMode||this.border.attr({stroke:d.borderColor,"stroke-width":d.borderWidth});const k=Math.round(this.border.strokeWidth())%2/2,h="mapBoundingBox"===d.relativeTo&&b.getMapBBox()||b.playingField;c=(c.coordinates||[]).reduce((b,c)=>c.reduce((b,c,e)=>{let [f,g]=c;"percent"===d.units&&(f=a.plotLeft+m(`${f}%`,h.width,h.x),g=a.plotTop+m(`${g}%`,h.height,h.y));
f=Math.floor(f)+k;g=Math.floor(g)+k;b.push(0===e?["M",f,g]:["L",f,g]);return b},b),[]);this.border[e?"animate":"attr"]({d:c})}}destroy(){this.border&&(this.border=this.border.destroy());this.eventsToUnbind.forEach(a=>a())}setUpEvents(){}}F(z,"afterInit",function(){this.mapView=new w(this,this.options.mapView)});return w});y(a,"Series/Map/MapSeries.js",[a["Core/Animation/AnimationUtilities.js"],a["Series/ColorMapComposition.js"],a["Series/CenteredUtilities.js"],a["Core/Globals.js"],a["Core/Chart/MapChart.js"],
a["Series/Map/MapPoint.js"],a["Maps/MapView.js"],a["Core/Series/Series.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,p,q,z,l,n,A,u,v,t,f){const {animObject:g,stop:e}=a;({noop:a}=z);const {splitPath:c}=l,{seriesTypes:{column:k,scatter:b}}=v,{extend:d,find:E,fireEvent:h,getNestedProperty:C,isArray:m,defined:x,isNumber:w,isObject:G,merge:r,objectEach:B,pick:D,splat:H}=f;class y extends b{constructor(){super(...arguments);this.points=
this.options=this.joinBy=this.group=this.data=this.chart=void 0;this.processedData=[]}animate(a){const {chart:b,group:d}=this,c=g(this.options.animation);a?d.attr({translateX:b.plotLeft+b.plotWidth/2,translateY:b.plotTop+b.plotHeight/2,scaleX:.001,scaleY:.001}):d.animate({translateX:b.plotLeft,translateY:b.plotTop,scaleX:1,scaleY:1},c)}clearBounds(){this.points.forEach(a=>{delete a.bounds;delete a.insetIndex;delete a.projectedPath});delete this.bounds}doFullTranslate(){return!(!this.isDirtyData&&
!this.chart.isResizing&&this.hasRendered)}drawMapDataLabels(){u.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)}drawPoints(){const a=this,{chart:b,group:d,transformGroups:c=[]}=this,{mapView:h,renderer:m}=b;h&&(this.transformGroups=c,c[0]||(c[0]=m.g().add(d)),h.insets.forEach((a,b)=>{c[b+1]||c.push(m.g().add(d))}),this.doFullTranslate()&&(this.points.forEach(a=>{const {graphic:d,shapeArgs:e}=a;a.group=c["number"===typeof a.insetIndex?a.insetIndex+
1:0];d&&d.parentGroup!==a.group&&d.add(a.group);e&&b.hasRendered&&!b.styledMode&&(e.fill=this.pointAttribs(a,a.state).fill)}),k.prototype.drawPoints.apply(this),this.points.forEach(d=>{const c=d.graphic;if(c){const e=c.animate;let k="";d.name&&(k+="highcharts-name-"+d.name.replace(/ /g,"-").toLowerCase());d.properties&&d.properties["hc-key"]&&(k+=" highcharts-key-"+d.properties["hc-key"].toString().toLowerCase());k&&c.addClass(k);b.styledMode&&c.css(this.pointAttribs(d,d.selected&&"select"||void 0));
c.animate=function(d,k,h){const m=w(d["stroke-width"])&&!w(c["stroke-width"]),f=w(c["stroke-width"])&&!w(d["stroke-width"]);if(m||f){const e=D(a.getStrokeWidth(a.options),1)/(b.mapView&&b.mapView.getScale()||1);m&&(c["stroke-width"]=e);f&&(d["stroke-width"]=e)}return e.call(c,d,k,f?function(){c.element.removeAttribute("stroke-width");delete c["stroke-width"];h&&h.apply(this,arguments)}:h)}}})),c.forEach((d,c)=>{const k=(0===c?h:h.insets[c-1]).getSVGTransform(),f=D(this.getStrokeWidth(this.options),
1),x=k.scaleX,l=0<k.scaleY?1:-1,w=b=>{(a.points||[]).forEach(a=>{const d=a.graphic;let c;d&&d["stroke-width"]&&(c=this.getStrokeWidth(a.options))&&d.attr({"stroke-width":c/b})})};if(m.globalAnimation&&b.hasRendered&&h.allowTransformAnimation){const a=Number(d.attr("translateX")),b=Number(d.attr("translateY")),e=Number(d.attr("scaleX")),h=(c,h)=>{c=e+(x-e)*h.pos;d.attr({translateX:a+(k.translateX-a)*h.pos,translateY:b+(k.translateY-b)*h.pos,scaleX:c,scaleY:c*l,"stroke-width":f/c});w(c)};c=r(g(m.globalAnimation));
const n=c.step;c.step=function(a){n&&n.apply(this,arguments);h.apply(this,arguments)};d.attr({animator:0}).animate({animator:1},c,function(){"boolean"!==typeof m.globalAnimation&&m.globalAnimation.complete&&m.globalAnimation.complete({applyDrilldown:!0})})}else e(d),d.attr(r(k,{"stroke-width":f/x})),w(x)}),this.isDrilling||this.drawMapDataLabels())}getProjectedBounds(){if(!this.bounds&&this.chart.mapView){const {insets:a,projection:b}=this.chart.mapView,d=[];(this.points||[]).forEach(function(e){if(e.path||
e.geometry){"string"===typeof e.path?e.path=c(e.path):m(e.path)&&"M"===e.path[0]&&(e.path=t.prototype.pathToSegments(e.path));if(!e.bounds){let d=e.getProjectedBounds(b);if(d){e.labelrank=D(e.labelrank,(d.x2-d.x1)*(d.y2-d.y1));const {midX:b,midY:c}=d;if(a&&w(b)&&w(c)){const k=E(a,a=>a.isInside({x:b,y:c}));k&&(delete e.projectedPath,(d=e.getProjectedBounds(k.projection))&&k.allBounds.push(d),e.insetIndex=a.indexOf(k))}e.bounds=d}}e.bounds&&void 0===e.insetIndex&&d.push(e.bounds)}});this.bounds=A.compositeBounds(d)}return this.bounds}getStrokeWidth(a){const b=
this.pointAttrToOptions;return a[b&&b["stroke-width"]||"borderWidth"]}hasData(){return!!this.processedXData.length}pointAttribs(a,b){var d;const {mapView:c,styledMode:e}=a.series.chart,h=e?this.colorAttribs(a):k.prototype.pointAttribs.call(this,a,b);let m=this.getStrokeWidth(a.options);if(b){b=r(this.options.states[b],a.options.states&&a.options.states[b]||{});const c=this.getStrokeWidth(b);x(c)&&(m=c);h.stroke=null!==(d=b.borderColor)&&void 0!==d?d:a.color}m&&c&&(m/=c.getScale());d=this.getStrokeWidth(this.options);
h.dashstyle&&c&&w(d)&&(m=d/c.getScale());a.visible||(h.fill=this.options.nullColor);x(m)?h["stroke-width"]=m:delete h["stroke-width"];h["stroke-linecap"]=h["stroke-linejoin"]=this.options.linecap;return h}updateData(){return this.processedData?!1:super.updateData.apply(this,arguments)}setData(a,b=!0,d,c){delete this.bounds;super.setData.call(this,a,!1,void 0,c);this.processData();this.generatePoints();b&&this.chart.redraw(d)}processData(){const a=this.options,b=a.data;var d=this.chart.options.chart;
const c=this.joinBy,e=a.keys||this.pointArrayMap,k=[],h={};var f=this.chart.mapView;f=f&&(G(a.mapData,!0)?f.getGeoMap(a.mapData):f.geoMap);var g=this.chart.mapTransforms;(this.chart.mapTransforms=g=d.mapTransforms||f&&f["hc-transform"]||g)&&B(g,function(a){a.rotation&&(a.cosAngle=Math.cos(a.rotation),a.sinAngle=Math.sin(a.rotation))});let x;m(a.mapData)?x=a.mapData:f&&"FeatureCollection"===f.type&&(this.mapTitle=f.title,x=z.geojson(f,this.type,this));const l=this.processedData=[];b&&b.forEach(function(d,
k){let h=0;if(w(d))l[k]={value:d};else if(m(d)){l[k]={};!a.keys&&d.length>e.length&&"string"===typeof d[0]&&(l[k]["hc-key"]=d[0],++h);for(let a=0;a<e.length;++a,++h)e[a]&&"undefined"!==typeof d[h]&&(0<e[a].indexOf(".")?n.prototype.setNestedProperty(l[k],d[h],e[a]):l[k][e[a]]=d[h])}else l[k]=b[k];c&&"_i"===c[0]&&(l[k]._i=k)});if(x){this.mapData=x;this.mapMap={};for(g=0;g<x.length;g++)d=x[g],f=d.properties,d._i=g,c[0]&&f&&f[c[0]]&&(d[c[0]]=f[c[0]]),h[d[c[0]]]=d;this.mapMap=h;if(c[1]){const a=c[1];l.forEach(function(b){b=
C(a,b);h[b]&&k.push(h[b])})}if(a.allAreas){if(c[1]){const a=c[1];l.forEach(function(b){k.push(C(a,b))})}const a="|"+k.map(function(a){return a&&a[c[0]]}).join("|")+"|";x.forEach(function(b){c[0]&&-1!==a.indexOf("|"+b[c[0]]+"|")||l.push(r(b,{value:null}))})}}this.processedXData=Array(l.length)}setOptions(a){a=u.prototype.setOptions.call(this,a);let b=a.joinBy;null===b&&(b="_i");b=this.joinBy=H(b);b[1]||(b[1]=b[0]);return a}translate(){const a=this.doFullTranslate(),b=this.chart.mapView,d=b&&b.projection;
!this.chart.hasRendered||!this.isDirtyData&&this.hasRendered||(this.processData(),this.generatePoints(),delete this.bounds,!b||b.userOptions.center||w(b.userOptions.zoom)||b.zoom!==b.minZoom?this.getProjectedBounds():b.fitToBounds(void 0,void 0,!1));if(b){const c=b.getSVGTransform();this.points.forEach(function(e){const k=w(e.insetIndex)&&b.insets[e.insetIndex].getSVGTransform()||c;k&&e.bounds&&w(e.bounds.midX)&&w(e.bounds.midY)&&(e.plotX=e.bounds.midX*k.scaleX+k.translateX,e.plotY=e.bounds.midY*
k.scaleY+k.translateY);a&&(e.shapeType="path",e.shapeArgs={d:n.getProjectedPath(e,d)});e.projectedPath&&!e.projectedPath.length?e.setVisible(!1):e.visible||e.setVisible(!0)})}h(this,"afterTranslate")}}y.defaultOptions=r(b.defaultOptions,{affectsMapView:!0,animation:!1,dataLabels:{crop:!1,formatter:function(){const {numberFormatter:a}=this.series.chart,{value:b}=this.point;return w(b)?a(b,-1):""},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},linecap:"round",marker:null,nullColor:"#f7f7f7",
stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:"{point.name}: {point.value}<br/>"},turboThreshold:0,allAreas:!0,borderColor:"#e6e6e6",borderWidth:1,joinBy:"hc-key",states:{hover:{halo:void 0,borderColor:"#666666",borderWidth:2},normal:{animation:!0},select:{color:"#cccccc"}},legendSymbol:"rectangle"});d(y.prototype,{type:"map",axisTypes:p.seriesMembers.axisTypes,colorAttribs:p.seriesMembers.colorAttribs,colorKey:p.seriesMembers.colorKey,directTouch:!0,drawDataLabels:a,drawGraph:a,forceDL:!0,
getCenter:q.getCenter,getExtremesFromAll:!0,getSymbol:a,isCartesian:!1,parallelArrays:p.seriesMembers.parallelArrays,pointArrayMap:p.seriesMembers.pointArrayMap,pointClass:n,preserveAspectRatio:!0,searchPoint:a,trackerGroups:p.seriesMembers.trackerGroups,useMapGeometry:!0});p.compose(y);v.registerSeriesType("map",y);"";return y});y(a,"Series/MapLine/MapLineSeries.js",[a["Series/Map/MapSeries.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,p,q){const {extend:g,merge:l}=q;
class n extends a{constructor(){super(...arguments);this.points=this.options=this.data=void 0}pointAttribs(g,l){g=a.prototype.pointAttribs.call(this,g,l);g.fill=this.options.fillColor;return g}}n.defaultOptions=l(a.defaultOptions,{lineWidth:1,fillColor:"none",legendSymbol:"lineMarker"});g(n.prototype,{type:"mapline",colorProp:"stroke",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"}});p.registerSeriesType("mapline",n);"";return n});y(a,"Series/MapPoint/MapPointPoint.js",[a["Core/Series/SeriesRegistry.js"],
a["Core/Utilities.js"]],function(a,p){({seriesTypes:{scatter:a}}=a);const {isNumber:g}=p;class z extends a.prototype.pointClass{constructor(){super(...arguments);this.series=this.options=void 0}isValid(){return!!(this.options.geometry||g(this.x)&&g(this.y)||g(this.options.lon)&&g(this.options.lat))}}return z});y(a,"Series/MapPoint/MapPointSeries.js",[a["Core/Globals.js"],a["Series/MapPoint/MapPointPoint.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],
function(a,p,q,z,l){({noop:a}=a);const {seriesTypes:{map:g,scatter:A}}=q,{extend:u,fireEvent:v,isNumber:t,merge:f}=l;class y extends A{constructor(){super(...arguments);this.points=this.options=this.data=this.chart=void 0;this.clearBounds=g.prototype.clearBounds}drawDataLabels(){super.drawDataLabels();this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)}projectPoint(a){const c=this.chart.mapView;if(c){const {geometry:e,lon:b,lat:d}=a;a=e&&"Point"===e.type&&e.coordinates;t(b)&&t(d)&&
(a=[b,d]);if(a)return c.lonLatToProjectedUnits({lon:a[0],lat:a[1]})}}translate(){const a=this.chart.mapView;this.processedXData||this.processData();this.generatePoints();this.getProjectedBounds&&this.isDirtyData&&(delete this.bounds,this.getProjectedBounds());if(a){const c=a.getSVGTransform(),{hasCoordinates:e}=a.projection;this.points.forEach(b=>{let {x:d,y:k}=b;var h=t(b.insetIndex)&&a.insets[b.insetIndex].getSVGTransform()||c;const f=this.projectPoint(b.options)||b.properties&&this.projectPoint(b.properties);
let m;f?(d=f.x,k=f.y):b.bounds&&(d=b.bounds.midX,k=b.bounds.midY,h&&t(d)&&t(k)&&(b.plotX=d*h.scaleX+h.translateX,b.plotY=k*h.scaleY+h.translateY,m=!0));t(d)&&t(k)?m||(h=a.projectedUnitsToPixels({x:d,y:k}),b.plotX=h.x,b.plotY=e?h.y:this.chart.plotHeight-h.y):b.y=b.plotX=b.plotY=void 0;b.isInside=this.isPointInside(b);b.zone=this.zones.length?b.getZone():void 0})}v(this,"afterTranslate")}}y.defaultOptions=f(A.defaultOptions,{dataLabels:{crop:!1,defer:!1,enabled:!0,formatter:function(){return this.point.name},
overflow:!1,style:{color:"#000000"}},legendSymbol:"lineMarker"});z.prototype.symbols.mapmarker=(a,c,k,b,d)=>{const e=d&&"legend"===d.context;e?(a+=k/2,d=c+b):d&&"number"===typeof d.anchorX&&"number"===typeof d.anchorY?(a=d.anchorX,d=d.anchorY):(a+=k/2,d=c+b/2,c-=b);b=e?b/3:b/2;return[["M",a,d],["C",a,d,a-b,c+1.5*b,a-b,c+b],["A",b,b,1,1,1,a+b,c+b],["C",a+b,c+1.5*b,a,d,a,d],["Z"]]};u(y.prototype,{type:"mappoint",axisTypes:["colorAxis"],forceDL:!0,isCartesian:!1,pointClass:p,searchPoint:a,useMapGeometry:!0});
q.registerSeriesType("mappoint",y);"";return y});y(a,"Series/Bubble/BubbleLegendDefaults.js",[],function(){return{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:"0.9em",color:"#000000"},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},
sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}});y(a,"Series/Bubble/BubbleLegendItem.js",[a["Core/Color/Color.js"],a["Core/Templating.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,p,q,z){const {parse:g}=a,{noop:n}=q,{arrayMax:A,arrayMin:u,isNumber:v,merge:t,pick:f,stableSort:y}=z;class e{constructor(a,e){this.options=this.symbols=this.visible=this.selected=this.ranges=this.movementX=this.maxLabel=this.legend=this.chart=void 0;this.setState=n;this.init(a,e)}init(a,e){this.options=
a;this.visible=!0;this.chart=e.chart;this.legend=e}addToLegend(a){a.splice(this.options.legendIndex,0,this)}drawLegendSymbol(a){const c=f(a.options.itemDistance,20),b=this.legendItem||{},d=this.options;var e=d.ranges,h=d.connectorDistance;if(e&&e.length&&v(e[0].value)){y(e,function(a,b){return b.value-a.value});this.ranges=e;this.setOptions();this.render();a=this.getMaxLabelSize();var g=this.ranges[0].radius;e=2*g;h=h-g+a.width;h=0<h?h:0;this.maxLabel=a;this.movementX="left"===d.labels.align?h:0;
b.labelWidth=e+h+c;b.labelHeight=e+a.height/2}else a.options.bubbleLegend.autoRanges=!0}setOptions(){const a=this.ranges,e=this.options,b=this.chart.series[e.seriesIndex],d=this.legend.baseline,l={zIndex:e.zIndex,"stroke-width":e.borderWidth},h={zIndex:e.zIndex,"stroke-width":e.connectorWidth},n={align:this.legend.options.rtl||"left"===e.labels.align?"right":"left",zIndex:e.zIndex},m=b.options.marker.fillOpacity,x=this.chart.styledMode;a.forEach(function(c,k){x||(l.stroke=f(c.borderColor,e.borderColor,
b.color),l.fill=f(c.color,e.color,1!==m?g(b.color).setOpacity(m).get("rgba"):b.color),h.stroke=f(c.connectorColor,e.connectorColor,b.color));a[k].radius=this.getRangeRadius(c.value);a[k]=t(a[k],{center:a[0].radius-a[k].radius+d});x||t(!0,a[k],{bubbleAttribs:t(l),connectorAttribs:t(h),labelAttribs:n})},this)}getRangeRadius(a){const c=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,c.ranges[c.ranges.length-1].value,c.ranges[0].value,c.minSize,c.maxSize,a)}render(){const a=
this.legendItem||{},e=this.chart.renderer,b=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});a.symbol=e.g("bubble-legend");a.label=e.g("bubble-legend-item").css(this.legend.itemStyle||{});a.symbol.translateX=0;a.symbol.translateY=0;a.symbol.add(a.label);a.label.add(a.group);for(const a of this.ranges)a.value>=b&&this.renderRange(a);this.hideOverlappingLabels()}renderRange(a){var c=this.options;const b=c.labels;var d=this.chart;const e=d.series[c.seriesIndex],
h=d.renderer,f=this.symbols;d=f.labels;const m=a.center,g=Math.abs(a.radius);var l=c.connectorDistance||0;const n=b.align,p=c.connectorWidth,u=this.ranges[0].radius||0,t=m-g-c.borderWidth/2+p/2,q=h.styledMode;l=this.legend.options.rtl||"left"===n?-l:l;"center"===n&&(l=0,c.connectorDistance=0,a.labelAttribs.align="center");f.bubbleItems.push(h.circle(u,m+((t%1?1:.5)-(p%2?0:.5)),g).attr(q?{}:a.bubbleAttribs).addClass((q?"highcharts-color-"+e.colorIndex+" ":"")+"highcharts-bubble-legend-symbol "+(c.className||
"")).add(this.legendItem.symbol));f.connectors.push(h.path(h.crispLine([["M",u,t],["L",u+l,t]],c.connectorWidth)).attr(q?{}:a.connectorAttribs).addClass((q?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(c.connectorClassName||"")).add(this.legendItem.symbol));a=h.text(this.formatLabel(a)).attr(q?{}:a.labelAttribs).css(q?{}:b.style).addClass("highcharts-bubble-legend-labels "+(c.labels.className||"")).add(this.legendItem.symbol);c={x:u+l+c.labels.x,y:t+
c.labels.y+.4*a.getBBox().height};a.attr(c);d.push(a);a.placed=!0;a.alignAttr=c}getMaxLabelSize(){let a,e;this.symbols.labels.forEach(function(b){e=b.getBBox(!0);a=a?e.width>a.width?e:a:e});return a||{}}formatLabel(a){var c=this.options;const b=c.labels.formatter;c=c.labels.format;const {numberFormatter:d}=this.chart;return c?p.format(c,a):b?b.call(a):d(a.value,1)}hideOverlappingLabels(){const a=this.chart,e=this.symbols;!this.options.labels.allowOverlap&&e&&(a.hideOverlappingLabels(e.labels),e.labels.forEach(function(a,
d){a.newOpacity?a.newOpacity!==a.oldOpacity&&e.connectors[d].show():e.connectors[d].hide()}))}getRanges(){const a=this.legend.bubbleLegend,e=a.options.ranges;let b,d,g=Number.MAX_VALUE,h=-Number.MAX_VALUE;a.chart.series.forEach(function(a){a.isBubble&&!a.ignoreSeries&&(d=a.zData.filter(v),d.length&&(g=f(a.options.zMin,Math.min(g,Math.max(u(d),!1===a.options.displayNegative?a.options.zThreshold:-Number.MAX_VALUE))),h=f(a.options.zMax,Math.max(h,A(d)))))});b=g===h?[{value:h}]:[{value:g},{value:(g+h)/
2},{value:h,autoRanges:!0}];e.length&&e[0].radius&&b.reverse();b.forEach(function(a,d){e&&e[d]&&(b[d]=t(e[d],a))});return b}predictBubbleSizes(){var a=this.chart,e=a.legend.options,b=e.floating;const d=(e="horizontal"===e.layout)?a.legend.lastLineHeight:0,f=a.plotSizeX,h=a.plotSizeY;var g=a.series[this.options.seriesIndex],m=g.getPxExtremes();a=Math.ceil(m.minPxSize);m=Math.ceil(m.maxPxSize);const l=Math.min(h,f);g=g.options.maxSize;if(b||!/%$/.test(g))b=m;else if(g=parseFloat(g),b=(l+d)*g/100/(g/
100+1),e&&h-b>=f||!e&&f-b>=h)b=m;return[a,Math.ceil(b)]}updateRanges(a,e){const b=this.legend.options.bubbleLegend;b.minSize=a;b.maxSize=e;b.ranges=this.getRanges()}correctSizes(){const a=this.legend,e=this.chart.series[this.options.seriesIndex].getPxExtremes();1<Math.abs(Math.ceil(e.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,e.maxPxSize),a.render())}}"";return e});y(a,"Series/Bubble/BubbleLegendComposition.js",[a["Series/Bubble/BubbleLegendDefaults.js"],a["Series/Bubble/BubbleLegendItem.js"],
a["Core/Defaults.js"],a["Core/Utilities.js"]],function(a,p,q,z){function g(a,d,c){const b=this.legend;var f=0<=n(this);let m,g;b&&b.options.enabled&&b.bubbleLegend&&b.options.bubbleLegend.autoRanges&&f?(m=b.bubbleLegend.options,f=b.bubbleLegend.predictBubbleSizes(),b.bubbleLegend.updateRanges(f[0],f[1]),m.placed||(b.group.placed=!1,b.allItems.forEach(a=>{g=a.legendItem||{};g.group&&(g.group.translateY=null)})),b.render(),this.getMargins(),this.axes.forEach(function(a){a.visible&&a.render();m.placed||
(a.setScale(),a.updateNames(),e(a.ticks,function(a){a.isNew=!0;a.isNewLabel=!0}))}),m.placed=!0,this.getMargins(),a.call(this,d,c),b.bubbleLegend.correctSizes(),t(b,A(b))):(a.call(this,d,c),b&&b.options.enabled&&b.bubbleLegend&&(b.render(),t(b,A(b))))}function n(a){a=a.series;let b=0;for(;b<a.length;){if(a[b]&&a[b].isBubble&&a[b].visible&&a[b].zData.length)return b;b++}return-1}function A(a){a=a.allItems;const b=[],c=a.length;let e,f,m=0;for(f=0;f<c;f++){var g=a[f].legendItem||{};e=(a[f+1]||{}).legendItem||
{};g.labelHeight&&(a[f].itemHeight=g.labelHeight);if(a[f]===a[c-1]||g.y!==e.y){b.push({height:0});g=b[b.length-1];for(m;m<=f;m++)a[m].itemHeight>g.height&&(g.height=a[m].itemHeight);g.step=f}}return b}function u(a){const b=this.bubbleLegend,c=this.options,e=c.bubbleLegend,f=n(this.chart);b&&b.ranges&&b.ranges.length&&(e.ranges.length&&(e.autoRanges=!!e.ranges[0].autoRanges),this.destroyItem(b));0<=f&&c.enabled&&e.enabled&&(e.seriesIndex=f,this.bubbleLegend=new p(e,this),this.bubbleLegend.addToLegend(a.allItems))}
function v(a){if(a.defaultPrevented)return!1;var b=this.chart;a=this.visible;const c=this.chart.legend;c&&c.bubbleLegend&&(this.visible=!a,this.ignoreSeries=a,b=0<=n(b),c.bubbleLegend.visible!==b&&(c.update({bubbleLegend:{enabled:b}}),c.bubbleLegend.visible=b),this.visible=a)}function t(a,d){const b=a.options.rtl;let c,e,f,g,k=0;a.allItems.forEach((a,h)=>{g=a.legendItem||{};if(g.group){c=g.group.translateX||0;e=g.y||0;if((f=a.movementX)||b&&a.ranges)f=b?c-a.options.maxSize/2:c+f,g.group.attr({translateX:f});
h>d[k].step&&k++;g.group.attr({translateY:Math.round(e+d[k].height/2)});g.y=e+d[k].height/2}})}const {setOptions:f}=q,{addEvent:y,objectEach:e,wrap:c}=z,k=[];return{compose:function(b,d,e){z.pushUnique(k,b)&&(f({legend:{bubbleLegend:a}}),c(b.prototype,"drawChartBox",g));z.pushUnique(k,d)&&y(d,"afterGetAllItems",u);z.pushUnique(k,e)&&y(e,"legendItemClick",v)}}});y(a,"Series/Bubble/BubblePoint.js",[a["Core/Series/Point.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,p,q){({seriesTypes:{scatter:{prototype:{pointClass:p}}}}=
p);({extend:q}=q);class g extends p{constructor(){super(...arguments);this.series=this.options=void 0}haloPath(g){return a.prototype.haloPath.call(this,0===g?0:(this.marker?this.marker.radius||0:0)+g)}}q(g.prototype,{ttBelow:!1});return g});y(a,"Series/Bubble/BubbleSeries.js",[a["Series/Bubble/BubbleLegendComposition.js"],a["Series/Bubble/BubblePoint.js"],a["Core/Color/Color.js"],a["Core/Globals.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,p,q,z,l,n){function g(){const a=
this.len,b=this.chart,c=this.isXAxis,e=c?"xData":"yData",f=this.min,g=this.max-f;let m=0,k=a,l=a/g,n;this.series.forEach(a=>{if(a.bubblePadding&&(a.visible||!b.options.chart.ignoreHiddenSeries)){n=this.allowZoomOutside=!0;const b=a[e];c&&((a.onPoint||a).getRadii(0,0,a),a.onPoint&&(a.radii=a.onPoint.radii));if(0<g){let c=b.length;for(;c--;)if(d(b[c])&&this.dataMin<=b[c]&&b[c]<=this.max){const d=a.radii&&a.radii[c]||0;m=Math.min((b[c]-f)*l-d,m);k=Math.max((b[c]-f)*l+d,k)}}}});n&&0<g&&!this.logarithmic&&
(k-=a,l*=(a+Math.max(0,m)-Math.min(k,a))/a,[["min","userMin",m],["max","userMax",k]].forEach(a=>{"undefined"===typeof h(this.options[a[0]],this[a[1]])&&(this[a[0]]+=a[2]/l)}))}const {parse:u}=q;({noop:q}=z);const {series:v,seriesTypes:{column:{prototype:t},scatter:f}}=l,{addEvent:y,arrayMax:e,arrayMin:c,clamp:k,extend:b,isNumber:d,merge:E,pick:h}=n,C=[];class m extends f{constructor(){super(...arguments);this.zData=this.yData=this.radii=this.points=this.options=this.minPxSize=this.maxPxSize=this.data=
void 0}static compose(b,d,c,e){a.compose(d,c,e);n.pushUnique(C,b)&&(b.prototype.beforePadding=g)}animate(a){!a&&this.points.length<this.options.animationLimit&&this.points.forEach(function(a){const {graphic:b}=a;b&&b.width&&(this.hasRendered||b.attr({x:a.plotX,y:a.plotY,width:1,height:1}),b.animate(this.markerAttribs(a),this.options.animation))},this)}getRadii(){const a=this.zData,b=this.yData,d=[];let c,e,f,g=this.chart.bubbleZExtremes;const {minPxSize:m,maxPxSize:k}=this.getPxExtremes();if(!g){let a=
Number.MAX_VALUE,b=-Number.MAX_VALUE,d;this.chart.series.forEach(c=>{c.bubblePadding&&(c.visible||!this.chart.options.chart.ignoreHiddenSeries)&&(c=(c.onPoint||c).getZExtremes())&&(a=Math.min(h(a,c.zMin),c.zMin),b=Math.max(h(b,c.zMax),c.zMax),d=!0)});d?(g={zMin:a,zMax:b},this.chart.bubbleZExtremes=g):g={zMin:0,zMax:0}}e=0;for(c=a.length;e<c;e++)f=a[e],d.push(this.getRadius(g.zMin,g.zMax,m,k,f,b&&b[e]));this.radii=d}getRadius(a,b,c,e,f,g){const h=this.options,m="width"!==h.sizeBy,k=h.zThreshold;let l=
b-a,n=.5;if(null===g||null===f)return null;if(d(f)){h.sizeByAbsoluteValue&&(f=Math.abs(f-k),l=Math.max(b-k,Math.abs(a-k)),a=0);if(f<a)return c/2-1;0<l&&(n=(f-a)/l)}m&&0<=n&&(n=Math.sqrt(n));return Math.ceil(c+n*(e-c))/2}hasData(){return!!this.processedXData.length}pointAttribs(a,b){const d=this.options.marker.fillOpacity;a=v.prototype.pointAttribs.call(this,a,b);1!==d&&(a.fill=u(a.fill).setOpacity(d).get("rgba"));return a}translate(){super.translate.call(this);this.getRadii();this.translateBubble()}translateBubble(){const {data:a,
options:c,radii:e}=this,{minPxSize:f}=this.getPxExtremes();let g=a.length;for(;g--;){const h=a[g],m=e?e[g]:0;"z"===this.zoneAxis&&(h.negative=(h.z||0)<(c.zThreshold||0));d(m)&&m>=f/2?(h.marker=b(h.marker,{radius:m,width:2*m,height:2*m}),h.dlBox={x:h.plotX-m,y:h.plotY-m,width:2*m,height:2*m}):(h.shapeArgs=h.plotY=h.dlBox=void 0,h.isInside=!1)}}getPxExtremes(){const a=Math.min(this.chart.plotWidth,this.chart.plotHeight);var b=b=>{let d;"string"===typeof b&&(d=/%$/.test(b),b=parseInt(b,10));return d?
a*b/100:b};const d=b(h(this.options.minSize,8));b=Math.max(b(h(this.options.maxSize,"20%")),d);return{minPxSize:d,maxPxSize:b}}getZExtremes(){var a=this.options;const b=(this.zData||[]).filter(d);if(b.length){const f=h(a.zMin,k(c(b),!1===a.displayNegative?a.zThreshold||0:-Number.MAX_VALUE,Number.MAX_VALUE));a=h(a.zMax,e(b));if(d(f)&&d(a))return{zMin:f,zMax:a}}}}m.defaultOptions=E(f.defaultOptions,{dataLabels:{formatter:function(){const {numberFormatter:a}=this.series.chart,{z:b}=this.point;return d(b)?
a(b,-1):""},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"});b(m.prototype,{alignDataLabel:t.alignDataLabel,applyZones:q,bubblePadding:!0,buildKDTree:q,directTouch:!0,isBubble:!0,pointArrayMap:["y","z"],pointClass:p,
parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",zoneAxis:"z"});y(m,"updatedData",a=>{delete a.target.chart.bubbleZExtremes});y(m,"remove",a=>{delete a.target.chart.bubbleZExtremes});l.registerSeriesType("bubble",m);"";"";return m});y(a,"Series/MapBubble/MapBubblePoint.js",[a["Series/Bubble/BubblePoint.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,p,q){({seriesTypes:{map:{prototype:{pointClass:{prototype:p}}}}}=p);({extend:q}=
q);class g extends a{isValid(){return"number"===typeof this.z}}q(g.prototype,{applyOptions:p.applyOptions,getProjectedBounds:p.getProjectedBounds});return g});y(a,"Series/MapBubble/MapBubbleSeries.js",[a["Series/Bubble/BubbleSeries.js"],a["Series/MapBubble/MapBubblePoint.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,p,q,y){const {seriesTypes:{map:{prototype:g},mappoint:{prototype:n}}}=q,{extend:z,merge:u}=y;class v extends a{constructor(){super(...arguments);this.points=
this.options=this.data=void 0;this.clearBounds=g.clearBounds}searchPoint(a,f){return this.searchKDTree({clientX:a.chartX-this.chart.plotLeft,plotY:a.chartY-this.chart.plotTop},f,a)}translate(){n.translate.call(this);this.getRadii();this.translateBubble()}updateParallelArrays(a,f,g){super.updateParallelArrays.call(this,a,f,g);a=this.processedXData;f=this.xData;a&&f&&(a.length=f.length)}}v.defaultOptions=u(a.defaultOptions,{lineWidth:0,animationLimit:500,joinBy:"hc-key",tooltip:{pointFormat:"{point.name}: {point.z}"}});
z(v.prototype,{type:"mapbubble",axisTypes:["colorAxis"],getProjectedBounds:g.getProjectedBounds,isCartesian:!1,pointArrayMap:["z"],pointClass:p,processData:g.processData,projectPoint:n.projectPoint,setData:g.setData,setOptions:g.setOptions,updateData:g.updateData,useMapGeometry:!0,xyFromShape:!0});q.registerSeriesType("mapbubble",v);"";return v});y(a,"Series/Heatmap/HeatmapPoint.js",[a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,p){({seriesTypes:{scatter:{prototype:{pointClass:a}}}}=
a);const {clamp:g,defined:y,extend:l,pick:n}=p;class A extends a{constructor(){super(...arguments);this.y=this.x=this.value=this.series=this.options=void 0}applyOptions(a,g){(this.isNull||null===this.value)&&delete this.color;super.applyOptions(a,g);this.formatPrefix=this.isNull||null===this.value?"null":"point";return this}getCellAttributes(){var a=this.series;const l=a.options,p=(l.colsize||1)/2,f=(l.rowsize||1)/2,q=a.xAxis,e=a.yAxis,c=this.options.marker||a.options.marker;a=a.pointPlacementToXValue();
const k=n(this.pointPadding,l.pointPadding,0),b={x1:g(Math.round(q.len-q.translate(this.x-p,!1,!0,!1,!0,-a)),-q.len,2*q.len),x2:g(Math.round(q.len-q.translate(this.x+p,!1,!0,!1,!0,-a)),-q.len,2*q.len),y1:g(Math.round(e.translate(this.y-f,!1,!0,!1,!0)),-e.len,2*e.len),y2:g(Math.round(e.translate(this.y+f,!1,!0,!1,!0)),-e.len,2*e.len)};[["width","x"],["height","y"]].forEach(function(a){var d=a[0];a=a[1];let f=a+"1",g=a+"2";const m=Math.abs(b[f]-b[g]),l=c&&c.lineWidth||0,n=Math.abs(b[f]+b[g])/2;d=c&&
c[d];y(d)&&d<m&&(d=d/2+l/2,b[f]=n-d,b[g]=n+d);if(k){if("x"===a&&q.reversed||"y"===a&&!e.reversed)f=g,g=a+"1";b[f]+=k;b[g]-=k}});return b}haloPath(a){if(!a)return[];const {x:g=0,y:l=0,width:f=0,height:n=0}=this.shapeArgs||{};return[["M",g-a,l-a],["L",g-a,l+n+a],["L",g+f+a,l+n+a],["L",g+f+a,l-a],["Z"]]}isValid(){return Infinity!==this.value&&-Infinity!==this.value}}l(A.prototype,{dataLabelOnNull:!0,moveToTopOnHover:!0,ttBelow:!1});return A});y(a,"Series/Heatmap/HeatmapSeries.js",[a["Core/Color/Color.js"],
a["Series/ColorMapComposition.js"],a["Core/Globals.js"],a["Series/Heatmap/HeatmapPoint.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,p,q,y,l,n,A){const {doc:g}=q,{series:v,seriesTypes:{column:t,scatter:f}}=l,{prototype:{symbols:z}}=n,{clamp:e,extend:c,fireEvent:k,isNumber:b,merge:d,pick:E,defined:h}=A;class C extends f{constructor(){super(...arguments);this.points=this.options=this.data=this.context=this.colorAxis=this.canvas=void 0;
this.valueMin=this.valueMax=NaN}drawPoints(){const a=this;var b=a.options,d=b.marker||{};if(b.interpolation){const {image:k,chart:m,xAxis:l,yAxis:n,points:p}=a;d=p.length-1;const {len:q,reversed:w}=l,{len:r,reversed:x}=n,{min:t,max:u}=l.getExtremes(),{min:v,max:y}=n.getExtremes(),[z,A]=[E(b.colsize,1),E(b.rowsize,1)];var c=m.inverted,f=z/2;b=l.userOptions.minPadding;var g=h(b)&&!(0<b);b=c||g;f=g&&f||0;const [B,G,C]=[t-f,u+2*f,t+z].map(b=>e(Math.round(l.len-l.translate(b,!1,!0,!1,!0,-a.pointPlacementToXValue())),
-l.len,2*l.len)),[F,I]=w?[G,B]:[B,G];f=q/C/2/2/2;c=c?{width:q,height:r,x:0,y:0}:{x:F-f,width:I-f,height:r,y:0};if(!k||a.isDirtyData){const e=m.colorAxis&&m.colorAxis[0];f=a.getContext();if((g=a.canvas)&&f&&e){const h=g.width=~~((u-t)/z)+1,l=g.height=~~((y-v)/A)+1,n=h*l,q=new Uint8ClampedArray(4*n),r=h-(b&&1||0),D=l-1;b=a=>{a=e.toColor(a.value||0,E(a)).split(")")[0].split("(")[1].split(",").map(a=>E(parseFloat(a),parseInt(a,10)));a[3]=255*E(a[3],1);return a};const B=w?a=>r-a:a=>a,G=x?a=>D-a:a=>a,C=
(a,b)=>Math.ceil(h*G(~~((D-0)/(y-v)*(y-b-v)))+B(~~((r-0)/(u-t)*(a-t))));a.buildKDTree();a.directTouch=!1;for(let a=0;a<n;a++){const c=p[~~((d-0)/(q.length-4)*a*4)],e=new Uint8ClampedArray(b(c));q.set(e,4*C(c.x,c.y))}f.putImageData(new ImageData(q,h,l),0,0);k?k.attr(Object.assign(Object.assign({},c),{href:g.toDataURL()})):a.image=m.renderer.image(g.toDataURL()).attr(c).add(a.group)}}else k.width===c.width&&k.height===c.height||k.attr(c)}else if(d.enabled||a._hasPointMarkers)v.prototype.drawPoints.call(a),
a.points.forEach(b=>{b.graphic&&(b.graphic[a.chart.styledMode?"css":"animate"](a.colorAttribs(b)),null===b.value&&b.graphic.addClass("highcharts-null-point"))})}getContext(){const {canvas:a,context:b}=this;if(a&&b)b.clearRect(0,0,a.width,a.height);else return this.canvas=g.createElement("canvas"),this.context=this.canvas.getContext("2d")||void 0;return b}getExtremes(){const {dataMin:a,dataMax:d}=v.prototype.getExtremes.call(this,this.valueData);b(a)&&(this.valueMin=a);b(d)&&(this.valueMax=d);return v.prototype.getExtremes.call(this)}getValidPoints(a,
b){return v.prototype.getValidPoints.call(this,a,b,!0)}hasData(){return!!this.processedXData.length}init(){super.init.apply(this,arguments);const a=this.options;a.pointRange=E(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=a.rowsize||1;z.ellipse=z.circle;a.marker&&b(a.borderRadius)&&(a.marker.r=a.borderRadius)}markerAttribs(a,b){const d=a.shapeArgs||{};if(a.hasImage)return{x:a.plotX,y:a.plotY};if(b&&"normal"!==b){var c=a.options.marker||{};a=this.options.marker||{};a=a.states&&a.states[b]||
{};c=c.states&&c.states[b]||{};b=(c.width||a.width||d.width||0)+(c.widthPlus||a.widthPlus||0);a=(c.height||a.height||d.height||0)+(c.heightPlus||a.heightPlus||0);return{x:(d.x||0)+((d.width||0)-b)/2,y:(d.y||0)+((d.height||0)-a)/2,width:b,height:a}}return d}pointAttribs(b,c){const e=v.prototype.pointAttribs.call(this,b,c),f=this.options||{};var g=this.chart.options.plotOptions||{},h=g.series||{};const k=g.heatmap||{};g=b&&b.options.borderColor||f.borderColor||k.borderColor||h.borderColor;h=b&&b.options.borderWidth||
f.borderWidth||k.borderWidth||h.borderWidth||e["stroke-width"];e.stroke=b&&b.marker&&b.marker.lineColor||f.marker&&f.marker.lineColor||g||this.color;e["stroke-width"]=h;c&&"normal"!==c&&(b=d(f.states&&f.states[c],f.marker&&f.marker.states&&f.marker.states[c],b&&b.options.states&&b.options.states[c]||{}),e.fill=b.color||a.parse(e.fill).brighten(b.brightness||0).get(),e.stroke=b.lineColor||e.stroke);return e}translate(){const {borderRadius:a,marker:c}=this.options,e=c&&c.symbol||"rect",f=z[e]?e:"rect",
g=-1!==["circle","square"].indexOf(f);this.generatePoints();this.points.forEach(function(c){const h=c.getCellAttributes();let k=Math.min(h.x1,h.x2);var l=Math.min(h.y1,h.y2);let m=Math.max(Math.abs(h.x2-h.x1),0),n=Math.max(Math.abs(h.y2-h.y1),0);c.hasImage=0===(c.marker&&c.marker.symbol||e||"").indexOf("url");g&&(l=Math.abs(m-n),k=Math.min(h.x1,h.x2)+(m<n?0:l/2),l=Math.min(h.y1,h.y2)+(m<n?l/2:0),m=n=Math.min(m,n));c.hasImage&&(c.marker={width:m,height:n});c.plotX=c.clientX=(h.x1+h.x2)/2;c.plotY=(h.y1+
h.y2)/2;c.shapeType="path";c.shapeArgs=d(!0,{x:k,y:l,width:m,height:n},{d:z[f](k,l,m,n,{r:b(a)?a:0})})});k(this,"afterTranslate")}}C.defaultOptions=d(f.defaultOptions,{animation:!1,borderRadius:0,borderWidth:0,interpolation:!1,nullColor:"#f7f7f7",dataLabels:{formatter:function(){const {numberFormatter:a}=this.series.chart,{value:c}=this.point;return b(c)?a(c,-1):""},inside:!0,verticalAlign:"middle",crop:!1,overflow:"allow",padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},
select:{}}},clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,brightness:.2}},legendSymbol:"rectangle"});c(C.prototype,{axisTypes:p.seriesMembers.axisTypes,colorKey:p.seriesMembers.colorKey,directTouch:!0,getExtremesFromAll:!0,parallelArrays:p.seriesMembers.parallelArrays,pointArrayMap:["y","value"],pointClass:y,specialGroup:"group",trackerGroups:p.seriesMembers.trackerGroups,alignDataLabel:t.prototype.alignDataLabel,colorAttribs:p.seriesMembers.colorAttribs,
getSymbol:v.prototype.getSymbol});p.compose(C);l.registerSeriesType("heatmap",C);"";"";return C});y(a,"masters/modules/map.src.js",[a["Core/Globals.js"],a["Core/Axis/Color/ColorAxis.js"],a["Series/MapBubble/MapBubbleSeries.js"],a["Core/Chart/MapChart.js"],a["Maps/MapView.js"],a["Maps/Projection.js"]],function(a,p,q,y,l,n){a.ColorAxis=p;a.MapChart=y;a.mapChart=a.Map=y.mapChart;a.MapView=l;a.maps=y.maps;a.Projection=n;p.compose(a.Chart,a.Fx,a.Legend,a.Series);q.compose(a.Axis,a.Chart,a.Legend,a.Series)})});//# sourceMappingURL=map.js.map