/*
 Highcharts JS v11.1.0 (2023-08-20)

 Sankey diagram module

 (c) 2010-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/sankey",["highcharts"],function(q){b(q);b.Highcharts=q;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function q(b,h,m,g){b.hasOwnProperty(h)||(b[h]=g.apply(null,m),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:h,module:b[h]}})))}b=b?b._modules:
{};q(b,"Series/NodesComposition.js",[b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,h){const {series:{prototype:m,prototype:{pointClass:{prototype:g}}}}=b,{defined:x,extend:y,find:d,merge:n,pick:k}=h;var a;(function(a){function c(){this.data=[].concat(this.points||[],this.nodes);return m.destroy.apply(this,arguments)}function b(){this.nodes&&(this.nodes.forEach(a=>{a.destroy()}),this.nodes.length=0);m.setData.apply(this,arguments)}function B(a){const c=arguments,e=this.isNode?
this.linksTo.concat(this.linksFrom):[this.fromNode,this.toNode];"select"!==a&&e.forEach(a=>{a&&a.series&&(g.setState.apply(a,c),a.isNode||(a.fromNode.graphic&&g.setState.apply(a.fromNode,c),a.toNode&&a.toNode.graphic&&g.setState.apply(a.toNode,c)))});g.setState.apply(this,c)}function l(a,c,e,d){const f=this.series.options.nodes,p=this.series.options.data,w=p&&p.length||0,z=p&&p[this.index];g.update.call(this,a,this.isNode?!1:c,e,d);this.isNode&&(a=(f||[]).reduce((f,a,p)=>this.id===a.id?p:f,-1),d=
n(f&&f[a]||{},p&&p[this.index]||{}),p&&(z?p[this.index]=z:p.length=w),f?0<=a?f[a]=d:f.push(d):this.series.options.nodes=[d],k(c,!0)&&this.series.chart.redraw(e))}const v=[];a.compose=function(a,d){h.pushUnique(v,a)&&(a=a.prototype,a.setNodeState=B,a.setState=B,a.update=l);h.pushUnique(v,d)&&(a=d.prototype,a.destroy=c,a.setData=b);return d};a.createNode=function(a){const c=this.pointClass;var e=(f,a)=>d(f,f=>f.id===a);let b=e(this.nodes,a);if(!b){e=this.options.nodes&&e(this.options.nodes,a);const f=
(new c).init(this,y({className:"highcharts-node",isNode:!0,id:a,y:1},e));f.linksTo=[];f.linksFrom=[];f.getSum=function(){let a=0,e=0;f.linksTo.forEach(f=>{a+=f.weight||0});f.linksFrom.forEach(f=>{e+=f.weight||0});return Math.max(a,e)};f.offset=function(a,e){let p=0;for(let c=0;c<f[e].length;c++){if(f[e][c]===a)return p;p+=f[e][c].weight}};f.hasShape=function(){let a=0;f.linksTo.forEach(f=>{f.outgoing&&a++});return!f.linksTo.length||a!==f.linksTo.length};f.index=this.nodes.push(f)-1;b=f}b.formatPrefix=
"node";b.name=b.name||b.options.id||"";b.mass=k(b.options.mass,b.options.marker&&b.options.marker.radius,this.options.marker&&this.options.marker.radius,4);return b};a.destroy=c;a.generatePoints=function(){const a=this.chart,c={};m.generatePoints.call(this);this.nodes||(this.nodes=[]);this.colorCounter=0;this.nodes.forEach(a=>{a.linksFrom.length=0;a.linksTo.length=0;a.level=a.options.level});this.points.forEach(e=>{x(e.from)&&(c[e.from]||(c[e.from]=this.createNode(e.from)),c[e.from].linksFrom.push(e),
e.fromNode=c[e.from],a.styledMode?e.colorIndex=k(e.options.colorIndex,c[e.from].colorIndex):e.color=e.options.color||c[e.from].color);x(e.to)&&(c[e.to]||(c[e.to]=this.createNode(e.to)),c[e.to].linksTo.push(e),e.toNode=c[e.to]);e.name=e.name||e.id},this);this.nodeLookup=c};a.setNodeState=B;a.updateNode=l})(a||(a={}));return a});q(b,"Series/Sankey/SankeyPoint.js",[b["Core/Series/Point.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,h,m){({seriesTypes:{column:h}}=h);const {defined:g}=
m;class x extends h.prototype.pointClass{constructor(){super(...arguments);this.toNode=this.series=this.options=this.nodeY=this.nodeX=this.mass=this.linksTo=this.linksFrom=this.linkBase=this.level=this.fromNode=this.className=void 0}applyOptions(h,d){b.prototype.applyOptions.call(this,h,d);g(this.options.level)&&(this.options.column=this.column=this.options.level);return this}getClassName(){return(this.isNode?"highcharts-node ":"highcharts-link ")+b.prototype.getClassName.call(this)}getFromNode(){let b=
-1,d;for(let n=0;n<this.linksTo.length;n++){const k=this.linksTo[n];k.fromNode.column>b&&k.fromNode!==this&&(d=k.fromNode,b=d.column)}return{fromNode:d,fromColumn:b}}setNodeColumn(){g(this.options.column)||(this.column=0===this.linksTo.length?0:this.getFromNode().fromColumn+1)}isValid(){return this.isNode||"number"===typeof this.weight}}return x});q(b,"Series/Sankey/SankeySeriesDefaults.js",[],function(){"";return{borderWidth:0,colorByPoint:!0,curveFactor:.33,dataLabels:{enabled:!0,backgroundColor:"none",
crop:!1,nodeFormat:void 0,nodeFormatter:function(){return this.point.name},format:void 0,formatter:function(){},inside:!0},inactiveOtherPoints:!0,linkOpacity:.5,opacity:1,minLinkWidth:0,nodeAlignment:"center",nodeWidth:20,nodePadding:10,showInLegend:!1,states:{hover:{linkOpacity:1,opacity:1},inactive:{linkOpacity:.1,opacity:.1,animation:{duration:50}}},tooltip:{followPointer:!0,headerFormat:'<span style="font-size: 0.8em">{series.name}</span><br/>',pointFormat:"{point.fromNode.name} \u2192 {point.toNode.name}: <b>{point.weight}</b><br/>",
nodeFormat:"{point.name}: <b>{point.sum}</b><br/>"}}});q(b,"Series/Sankey/SankeyColumnComposition.js",[b["Core/Utilities.js"]],function(b){const {defined:h,relativeLength:m}=b;var g;(function(b){b.compose=function(b,n){b.sankeyColumn=new g(b,n);return b};class g{constructor(b,n){this.points=b;this.series=n}getTranslationFactor(b){const d=this.points,k=d.slice(),a=b.options.minLinkWidth||0;let c=0,r,t=(b.chart.plotSizeY||0)-(b.options.borderWidth||0)-(d.length-1)*b.nodePadding;for(;d.length;){c=t/
d.sankeyColumn.sum();b=!1;for(r=d.length;r--;)d[r].getSum()*c<a&&(d.splice(r,1),t=Math.max(0,t-a),b=!0);if(!b)break}d.length=0;k.forEach(a=>{d.push(a)});return c}top(b){const d=this.series,k=d.nodePadding,a=this.points.reduce(function(a,r){0<a&&(a+=k);r=Math.max(r.getSum()*b,d.options.minLinkWidth||0);return a+r},0);return{top:0,center:.5,bottom:1}[d.options.nodeAlignment||"center"]*((d.chart.plotSizeY||0)-a)}left(b){const d=this.series,k=d.chart,a=d.options.equalNodes,c=k.inverted?k.plotHeight:k.plotWidth,
r=d.nodePadding,t=this.points.reduce(function(k,l){0<k&&(k+=r);l=a?c/l.series.nodes.length-r:Math.max(l.getSum()*b,d.options.minLinkWidth||0);return k+l},0);return((k.plotSizeX||0)-Math.round(t))/2}sum(){return this.points.reduce(function(b,g){return b+g.getSum()},0)}offset(b,g){const d=this.points,a=this.series,c=a.nodePadding;let r=0;if(a.is("organization")&&b.hangsFrom)return{absoluteTop:b.hangsFrom.nodeY};for(let k=0;k<d.length;k++){var t=d[k].getSum();const l=Math.max(t*g,a.options.minLinkWidth||
0),v=b.options[a.chart.inverted?"offsetHorizontal":"offsetVertical"],u=b.options.offset||0;t=t?l+c:0;if(d[k]===b)return{relativeTop:r+(h(v)?m(v,l):m(u,t))};r+=t}}}b.SankeyColumnAdditions=g})(g||(g={}));return g});q(b,"Series/TreeUtilities.js",[b["Core/Color/Color.js"],b["Core/Utilities.js"]],function(b,h){function m(a,b){var c=b.before;const d=b.idRoot,h=b.mapIdToNode[d],l=b.points[a.i],v=l&&l.options||{},u=[];let n=0;a.levelDynamic=a.level-(!1!==b.levelIsConstant?0:h.level);a.name=k(l&&l.name,"");
a.visible=d===a.id||!0===b.visible;"function"===typeof c&&(a=c(a,b));a.children.forEach((c,d)=>{const f=g({},b);g(f,{index:d,siblings:a.children.length,visible:a.visible});c=m(c,f);u.push(c);c.visible&&(n+=c.val)});c=k(v.value,n);a.visible=0<=c&&(0<n||a.visible);a.children=u;a.childrenTotal=n;a.isLeaf=a.visible&&!n;a.val=c;return a}const {extend:g,isArray:q,isNumber:y,isObject:d,merge:n,pick:k}=h;return{getColor:function(a,c){const d=c.index;var g=c.mapOptionsToLevel;const h=c.parentColor,l=c.parentColorIndex,
n=c.series;var u=c.colors;const m=c.siblings;var e=n.points,q=n.chart.options.chart;let f;var p;let w;if(a){e=e[a.i];a=g[a.level]||{};if(g=e&&a.colorByPoint){f=e.index%(u?u.length:q.colorCount);var z=u&&u[f]}if(!n.chart.styledMode){u=e&&e.options.color;q=a&&a.color;if(p=h)p=(p=a&&a.colorVariation)&&"brightness"===p.key&&d&&m?b.parse(h).brighten(d/m*p.to).get():h;p=k(u,q,z,p,n.color)}w=k(e&&e.options.colorIndex,a&&a.colorIndex,f,l,c.colorIndex)}return{color:p,colorIndex:w}},getLevelOptions:function(a){let b=
{},g,h,m;if(d(a)){m=y(a.from)?a.from:1;var l=a.levels;h={};g=d(a.defaults)?a.defaults:{};q(l)&&(h=l.reduce((a,b)=>{let c,e;d(b)&&y(b.level)&&(e=n({},b),c=k(e.levelIsConstant,g.levelIsConstant),delete e.levelIsConstant,delete e.level,b=b.level+(c?0:m-1),d(a[b])?n(!0,a[b],e):a[b]=e);return a},{}));l=y(a.to)?a.to:1;for(a=0;a<=l;a++)b[a]=n({},g,d(h[a])?h[a]:{})}return b},setTreeValues:m,updateRootId:function(a){if(d(a)){var b=d(a.options)?a.options:{};b=k(a.rootNode,b.rootId,"");d(a.userOptions)&&(a.userOptions.rootId=
b);a.rootNode=b}return b}}});q(b,"Series/Sankey/SankeySeries.js",[b["Core/Color/Color.js"],b["Core/Globals.js"],b["Series/NodesComposition.js"],b["Series/Sankey/SankeyPoint.js"],b["Series/Sankey/SankeySeriesDefaults.js"],b["Core/Series/SeriesRegistry.js"],b["Series/Sankey/SankeyColumnComposition.js"],b["Series/TreeUtilities.js"],b["Core/Utilities.js"]],function(b,h,m,g,q,y,d,n,k){const {series:a,seriesTypes:{column:c}}=y,{getLevelOptions:r}=n,{clamp:t,extend:B,isObject:l,merge:v,pick:u,relativeLength:x,
stableSort:e}=k;class A extends c{constructor(){super(...arguments);this.translationFactor=this.points=this.options=this.nodeWidth=this.nodes=this.nodePadding=this.nodeLookup=this.group=this.data=this.colDistance=void 0}static getDLOptions(a){const b=l(a.optionsPoint)?a.optionsPoint.dataLabels:{};a=l(a.level)?a.level.dataLabels:{};return v({style:{}},a,b)}createNodeColumns(){const a=[];this.nodes.forEach(function(b){b.setNodeColumn();a[b.column]||(a[b.column]=d.compose([],this));a[b.column].push(b)},
this);for(let b=0;b<a.length;b++)"undefined"===typeof a[b]&&(a[b]=d.compose([],this));return a}order(a,b){const f=this;"undefined"===typeof a.level&&(a.level=b,a.linksFrom.forEach(function(a){a.toNode&&f.order(a.toNode,b+1)}))}generatePoints(){m.generatePoints.apply(this,arguments);const a=this;this.orderNodes&&(this.nodes.filter(function(a){return 0===a.linksTo.length}).forEach(function(b){a.order(b,0)}),e(this.nodes,function(a,b){return a.level-b.level}))}getNodePadding(){let a=this.options.nodePadding||
0;if(this.nodeColumns){const b=this.nodeColumns.reduce((a,b)=>Math.max(a,b.length),0);b*a>this.chart.plotSizeY&&(a=this.chart.plotSizeY/b)}return a}hasData(){return!!this.processedXData.length}pointAttribs(a,c){if(!a)return{};const f=this,d=f.mapOptionsToLevel[(a.isNode?a.level:a.fromNode.level)||0]||{},e=a.options,p=d.states&&d.states[c||""]||{};c=["colorByPoint","borderColor","borderWidth","linkOpacity","opacity"].reduce(function(a,b){a[b]=u(p[b],e[b],d[b],f.options[b]);return a},{});const D=u(p.color,
e.color,c.colorByPoint?a.color:d.color);return a.isNode?{fill:D,stroke:c.borderColor,"stroke-width":c.borderWidth,opacity:c.opacity}:{fill:b.parse(D).setOpacity(c.linkOpacity).get()}}drawTracker(){c.prototype.drawTracker.call(this,this.points);c.prototype.drawTracker.call(this,this.nodes)}drawPoints(){c.prototype.drawPoints.call(this,this.points);c.prototype.drawPoints.call(this,this.nodes)}drawDataLabels(){c.prototype.drawDataLabels.call(this,this.points);c.prototype.drawDataLabels.call(this,this.nodes)}translate(){this.processedXData||
this.processData();this.generatePoints();this.nodeColumns=this.createNodeColumns();this.nodeWidth=x(this.options.nodeWidth,this.chart.plotSizeX);const a=this,b=this.chart,c=this.options,d=this.nodeWidth,e=this.nodeColumns;this.nodePadding=this.getNodePadding();this.translationFactor=e.reduce((b,f)=>Math.min(b,f.sankeyColumn.getTranslationFactor(a)),Infinity);this.colDistance=(b.plotSizeX-d-c.borderWidth)/Math.max(1,e.length-1);a.mapOptionsToLevel=r({from:1,levels:c.levels,to:e.length-1,defaults:{borderColor:c.borderColor,
borderRadius:c.borderRadius,borderWidth:c.borderWidth,color:a.color,colorByPoint:c.colorByPoint,levelIsConstant:!0,linkColor:c.linkColor,linkLineWidth:c.linkLineWidth,linkOpacity:c.linkOpacity,states:c.states}});e.forEach(function(b){b.forEach(function(f){a.translateNode(f,b)})},this);this.nodes.forEach(function(b){b.linksFrom.forEach(function(b){(b.weight||b.isNull)&&b.to&&(a.translateLink(b),b.allowShadow=!1)})})}translateLink(a){var b=(b,c)=>{c=b.offset(a,c)*e;return Math.min(b.nodeY+c,b.nodeY+
(b.shapeArgs&&b.shapeArgs.height||0)-g)};let c=a.fromNode;var f=a.toNode;let d=this.chart,e=this.translationFactor,g=Math.max(a.weight*e,this.options.minLinkWidth);var k=(d.inverted?-this.colDistance:this.colDistance)*this.options.curveFactor;let h=b(c,"linksFrom");b=b(f,"linksTo");let n=c.nodeX,l=this.nodeWidth;f=f.nodeX;var m=a.outgoing,q=f>n+l;d.inverted&&(h=d.plotSizeY-h,b=(d.plotSizeY||0)-b,l=-l,g=-g,q=n>f);a.shapeType="path";a.linkBase=[h,h+g,b,b+g];if(q&&"number"===typeof b)a.shapeArgs={d:[["M",
n+l,h],["C",n+l+k,h,f-k,b,f,b],["L",f+(m?l:0),b+g/2],["L",f,b+g],["C",f-k,b+g,n+l+k,h+g,n+l,h+g],["Z"]]};else if("number"===typeof b){k=f-20-g;m=f-20;q=n+l;const c=q+20,e=c+g,p=h,r=h+g,u=r+20,t=u+(d.plotHeight-h-g),w=t+20,z=w+g,v=b,C=v+g,x=C+20,y=w+.7*g,F=f-.7*g,E=q+.7*g;a.shapeArgs={d:[["M",q,p],["C",E,p,e,r-.7*g,e,u],["L",e,t],["C",e,y,E,z,q,z],["L",f,z],["C",F,z,k,y,k,t],["L",k,x],["C",k,C-.7*g,F,v,f,v],["L",f,C],["C",m,C,m,C,m,x],["L",m,t],["C",m,w,m,w,f,w],["L",q,w],["C",c,w,c,w,c,t],["L",c,
u],["C",c,r,c,r,q,r],["Z"]]}}a.dlBox={x:n+(f-n+l)/2,y:h+(b-h)/2,height:g,width:0};a.tooltipPos=d.inverted?[d.plotSizeY-a.dlBox.y-g/2,d.plotSizeX-a.dlBox.x]:[a.dlBox.x,a.dlBox.y+g/2];a.y=a.plotY=1;a.x=a.plotX=1;a.color||(a.color=c.color)}translateNode(a,b){var c=this.translationFactor;const d=this.chart,e=this.options,{borderRadius:f,borderWidth:g=0}=e;var h=a.getSum();const k=Math.max(Math.round(h*c),this.options.minLinkWidth),n=Math.round(this.nodeWidth);var l=Math.round(g)%2/2,m=b.sankeyColumn.offset(a,
c);b=Math.floor(u(m.absoluteTop,b.sankeyColumn.top(c)+m.relativeTop))+l;l=Math.floor(this.colDistance*a.column+g/2)+x(a.options.offsetHorizontal||0,n)+l;l=d.inverted?d.plotSizeX-l:l;if(a.sum=h){a.shapeType="roundedRect";a.nodeX=l;a.nodeY=b;h=l;c=b;m=a.options.width||e.width||n;let g=a.options.height||e.height||k;const p=t(x("object"===typeof f?f.radius:f||0,m),0,k/2);d.inverted&&(h=l-n,c=d.plotSizeY-b-k,m=a.options.height||e.height||n,g=a.options.width||e.width||k);a.dlOptions=A.getDLOptions({level:this.mapOptionsToLevel[a.level],
optionsPoint:a.options});a.plotX=1;a.plotY=1;a.tooltipPos=d.inverted?[d.plotSizeY-c-g/2,d.plotSizeX-h-m/2]:[h+m/2,c+g/2];a.shapeArgs={x:h,y:c,width:m,height:g,r:p,display:a.hasShape()?"":"none"}}else a.dlOptions={enabled:!1}}}A.defaultOptions=v(c.defaultOptions,q);m.compose(g,A);B(A.prototype,{animate:a.prototype.animate,createNode:m.createNode,forceDL:!0,invertible:!0,isCartesian:!1,orderNodes:!0,noSharedTooltip:!0,pointArrayMap:["from","to","weight"],pointClass:g,searchPoint:h.noop});y.registerSeriesType("sankey",
A);"";return A});q(b,"masters/modules/sankey.src.js",[],function(){})});//# sourceMappingURL=sankey.js.map