/*
 Highcharts JS v11.1.0 (2023-08-20)

 (c) 2016-2021 Highsoft AS
 Authors: Jon Arild Nygard

 License: www.highcharts.com/license
*/
'use strict';(function(d){"object"===typeof module&&module.exports?(d["default"]=d,module.exports=d):"function"===typeof define&&define.amd?define("highcharts/modules/wordcloud",["highcharts"],function(h){d(h);d.Highcharts=h;return d}):d("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(d){function h(d,e,m,l){d.hasOwnProperty(e)||(d[e]=l.apply(null,m),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:e,module:d[e]}})))}d=d?d._modules:
{};h(d,"Series/DrawPointUtilities.js",[d["Core/Utilities.js"]],function(){return{draw:function(d,e){const {animatableAttribs:m,onComplete:l,css:h,renderer:q}=e,u=d.series&&d.series.chart.hasRendered?void 0:d.series&&d.series.options.animation;let g=d.graphic;e.attribs=Object.assign(Object.assign({},e.attribs),{"class":d.getClassName()})||{};if(d.shouldDraw())g||(g="text"===e.shapeType?q.text():"image"===e.shapeType?q.image(e.imageUrl||"").attr(e.shapeArgs||{}):q[e.shapeType](e.shapeArgs||{}),d.graphic=
g,g.add(e.group)),h&&g.css(h),g.attr(e.attribs).animate(m,e.isNew?!1:u,l);else if(g){const e=()=>{d.graphic=g=g&&g.destroy();"function"===typeof l&&l()};Object.keys(m).length?g.animate(m,void 0,()=>e()):e()}}}});h(d,"Series/Wordcloud/WordcloudPoint.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,e){({seriesTypes:{column:{prototype:{pointClass:d}}}}=d);({extend:e}=e);class m extends d{constructor(){super(...arguments);this.series=this.rect=this.polygon=this.options=this.dimensions=
void 0}isValid(){return!0}}e(m.prototype,{weight:1});return m});h(d,"Series/Wordcloud/WordcloudUtils.js",[d["Core/Globals.js"],d["Core/Utilities.js"]],function(d,e){function m(a,b){return!(b.left>a.right||b.right<a.left||b.top>a.bottom||b.bottom<a.top)}function h(a,b){const c=b[0]-a[0];a=b[1]-a[1];return[[-a,c],[a,-c]]}function n(a){let b,c=a.axes||[];c.length||(c=[],b=b=a.concat([a[0]]),b.reduce(function(a,b){const f=h(a,b)[0];B(c,a=>a[0]===f[0]&&a[1]===f[1])||c.push(f);return b}),a.axes=c);return c}
function q(a,b){a=a.map(a=>a[0]*b[0]+a[1]*b[1]);return{min:Math.min.apply(this,a),max:Math.max.apply(this,a)}}function t(a,b){var c=n(a);const f=n(b);c=c.concat(f);return!B(c,c=>{var f=q(a,c);c=q(b,c);return f=!!(c.min>f.max||c.max<f.min)})}function g(a,b){function c(b){let c=m(d,b.rect);c&&(a.rotation%90||b.rotation%90)&&(c=t(e,b.polygon));return c}let f=!1,d=a.rect,e=a.polygon,g=a.lastCollidedWith;g&&((f=c(g))||delete a.lastCollidedWith);f||(f=!!B(b,function(b){const f=c(b);f&&(a.lastCollidedWith=
b);return f}));return f}function A(a){let b=4*a,c=Math.ceil((Math.sqrt(b)-1)/2),f=2*c+1,d=Math.pow(f,2),e=!1;--f;1E4>=a&&("boolean"===typeof e&&b>=d-f&&(e={x:c-(d-b),y:-c}),d-=f,"boolean"===typeof e&&b>=d-f&&(e={x:-c,y:-c+(d-b)}),d-=f,"boolean"===typeof e&&(e=b>=d-f?{x:-c+(d-b),y:c}:{x:c,y:c-(d-b-f)}),e.x*=5,e.y*=5);return e}function v(a,b){var c=b.width/2,f=-(b.height/2),d=b.height/2;return!(-(b.width/2)<a.left&&c>a.right&&f<a.top&&d>a.bottom)}function u(a,b,c){return c.map(function(c){return[c[0]+
a,c[1]+b]})}function x(a,b){b=k(b)?b:14;b=Math.pow(10,b);return Math.round(a*b)/b}function C(a,b){const c=a[0];a=a[1];var f=D*-b;b=Math.cos(f);f=Math.sin(f);return[x(c*b-a*f),x(c*f+a*b)]}function y(a,b,c){a=C([a[0]-b[0],a[1]-b[1]],c);return[a[0]+b[0],a[1]+b[1]]}const {deg2rad:D}=d,{extend:F,find:B,isNumber:k,isObject:E,merge:w}=e;return{archimedeanSpiral:function(a,b){var c=b.field;b=!1;c=c.width*c.width+c.height*c.height;let f=.8*a;1E4>=a&&(b={x:f*Math.cos(f),y:f*Math.sin(f)},Math.min(Math.abs(b.x),
Math.abs(b.y))<c||(b=!1));return b},extendPlayingField:function(a,b){let c,f;if(E(a)&&E(b)){var d=b.bottom-b.top;c=b.right-b.left;b=a.ratioX;f=a.ratioY;d=c*b>d*f?c:d;a=w(a,{width:a.width+d*b*2,height:a.height+d*f*2})}return a},getBoundingBoxFromPolygon:function(a){return a.reduce(function(a,c){const b=c[0];c=c[1];a.left=Math.min(b,a.left);a.right=Math.max(b,a.right);a.bottom=Math.max(c,a.bottom);a.top=Math.min(c,a.top);return a},{left:Number.MAX_VALUE,right:-Number.MAX_VALUE,bottom:-Number.MAX_VALUE,
top:Number.MAX_VALUE})},getPlayingField:function(a,b,c){c=c.reduce(function(a,b){b=b.dimensions;const c=Math.max(b.width,b.height);a.maxHeight=Math.max(a.maxHeight,b.height);a.maxWidth=Math.max(a.maxWidth,b.width);a.area+=c*c;return a},{maxHeight:0,maxWidth:0,area:0});c=Math.max(c.maxHeight,c.maxWidth,.85*Math.sqrt(c.area));const d=a>b?a/b:1;a=b>a?b/a:1;return{width:c*d,height:c*a,ratioX:d,ratioY:a}},getPolygon:function(a,b,c,d,e){const f=[a,b],g=a-c/2;a+=c/2;c=b-d/2;b+=d/2;return[[g,c],[a,c],[a,
b],[g,b]].map(function(a){return y(a,f,-e)})},getRandomPosition:function(a){return Math.round(a*(Math.random()+.5)/2)},getRotation:function(a,b,c,d){let f=!1;k(a)&&k(b)&&k(c)&&k(d)&&0<a&&-1<b&&d>c&&(f=c+b%a*((d-c)/(a-1||1)));return f},getScale:function(a,b,c){const d=2*Math.max(Math.abs(c.top),Math.abs(c.bottom));c=2*Math.max(Math.abs(c.left),Math.abs(c.right));return Math.min(0<c?1/c*a:1,0<d?1/d*b:1)},getSpiral:function(a,b){let c,d=[];for(c=1;1E4>c;c++)d.push(a(c,b));return function(a){return 1E4>=
a?d[a-1]:!1}},intersectionTesting:function(a,b){let c=b.placed,d=b.field,e=b.rectangle,h=b.polygon,m=b.spiral,k=1,p={x:0,y:0},l=a.rect=F({},e);a.polygon=h;for(a.rotation=b.rotation;!1!==p&&(g(a,c)||v(l,d));)p=m(k),E(p)&&(l.left=e.left+p.x,l.right=e.right+p.x,l.top=e.top+p.y,l.bottom=e.bottom+p.y,a.polygon=u(p.x,p.y,h)),k++;return p},isPolygonsColliding:t,isRectanglesIntersecting:m,rectangularSpiral:function(a,b){a=A(a,b);b=b.field;a&&(a.x*=b.ratioX,a.y*=b.ratioY);return a},rotate2DToOrigin:C,rotate2DToPoint:y,
squareSpiral:A,updateFieldBoundaries:function(a,b){if(!k(a.left)||a.left>b.left)a.left=b.left;if(!k(a.right)||a.right<b.right)a.right=b.right;if(!k(a.top)||a.top>b.top)a.top=b.top;if(!k(a.bottom)||a.bottom<b.bottom)a.bottom=b.bottom;return a}}});h(d,"Series/Wordcloud/WordcloudSeries.js",[d["Series/DrawPointUtilities.js"],d["Core/Globals.js"],d["Core/Series/Series.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"],d["Series/Wordcloud/WordcloudPoint.js"],d["Series/Wordcloud/WordcloudUtils.js"]],
function(d,e,h,l,n,q,t){const {noop:g}=e,{seriesTypes:{column:m}}=l,{extend:v,isArray:u,isNumber:x,isObject:C,merge:y}=n,{archimedeanSpiral:D,extendPlayingField:F,getBoundingBoxFromPolygon:B,getPlayingField:k,getPolygon:E,getRandomPosition:w,getRotation:a,getScale:b,getSpiral:c,intersectionTesting:f,isPolygonsColliding:J,rectangularSpiral:K,rotate2DToOrigin:L,rotate2DToPoint:M,squareSpiral:p,updateFieldBoundaries:N}=t;class z extends m{constructor(){super(...arguments);this.points=this.options=this.data=
void 0}bindAxes(){const a={endOnTick:!1,gridLineWidth:0,lineWidth:0,maxPadding:0,startOnTick:!1,title:void 0,tickPositions:[]};h.prototype.bindAxes.call(this);v(this.yAxis.options,a);v(this.xAxis.options,a)}pointAttribs(a,b){a=e.seriesTypes.column.prototype.pointAttribs.call(this,a,b);delete a.stroke;delete a["stroke-width"];return a}deriveFontSize(a,b,c){a=x(a)?a:0;b=x(b)?b:1;c=x(c)?c:1;return Math.floor(Math.max(c,a*b))}drawPoints(){let a=this,e=a.hasRendered;var g=a.xAxis;let h=a.yAxis,m=a.group,
l=a.options,p=l.animation,q=l.allowExtendPlayingField,u=a.chart.renderer,n=u.text().add(m),t=[],y=a.placementStrategy[l.placementStrategy],w,z=l.rotation,D=a.points.map(function(a){return a.weight}),A=Math.max.apply(null,D),G=a.points.concat().sort(function(a,b){return b.weight-a.weight}),r;a.group.attr({scaleX:1,scaleY:1});G.forEach(function(b){var c=a.deriveFontSize(1/A*b.weight,l.maxFontSize,l.minFontSize);c=v({fontSize:c+"px"},l.style);n.css(c).attr({x:0,y:0,text:b.name});c=n.getBBox(!0);b.dimensions=
{height:c.height,width:c.width}});r=k(g.len,h.len,G);w=c(a.spirals[l.spiral],{field:r});G.forEach(function(b){var c=a.deriveFontSize(1/A*b.weight,l.maxFontSize,l.minFontSize);c=v({fontSize:c+"px"},l.style);let g=y(b,{data:G,field:r,placed:t,rotation:z}),h=v(a.pointAttribs(b,b.selected&&"select"),{align:"center","alignment-baseline":"middle","dominant-baseline":"middle",x:g.x,y:g.y,text:b.name,rotation:x(g.rotation)?g.rotation:void 0}),H=E(g.x,g.y,b.dimensions.width,b.dimensions.height,g.rotation),
k=B(H),n=f(b,{rectangle:k,polygon:H,field:r,placed:t,spiral:w,rotation:g.rotation}),I;!n&&q&&(r=F(r,k),n=f(b,{rectangle:k,polygon:H,field:r,placed:t,spiral:w,rotation:g.rotation}));C(n)?(h.x=(h.x||0)+n.x,h.y=(h.y||0)+n.y,k.left+=n.x,k.right+=n.x,k.top+=n.y,k.bottom+=n.y,r=N(r,k),t.push(b),b.isNull=!1,b.isInside=!0):b.isNull=!0;p&&(I={x:h.x,y:h.y},e?(delete h.x,delete h.y):(h.x=0,h.y=0));d.draw(b,{animatableAttribs:I,attribs:h,css:c,group:m,renderer:u,shapeArgs:void 0,shapeType:"text"})});n=n.destroy();
g=b(g.len,h.len,r);a.group.attr({scaleX:g,scaleY:g})}hasData(){return C(this)&&!0===this.visible&&u(this.points)&&0<this.points.length}getPlotBox(){const a=this.chart;var b=a.inverted;const c=this[b?"yAxis":"xAxis"];b=this[b?"xAxis":"yAxis"];return{translateX:(c?c.left:a.plotLeft)+(c?c.len:a.plotWidth)/2,translateY:(b?b.top:a.plotTop)+(b?b.len:a.plotHeight)/2,scaleX:1,scaleY:1}}}z.defaultOptions=y(m.defaultOptions,{allowExtendPlayingField:!0,animation:{duration:500},borderWidth:0,clip:!1,colorByPoint:!0,
cropThreshold:Infinity,minFontSize:1,maxFontSize:25,placementStrategy:"center",rotation:{from:0,orientations:2,to:90},showInLegend:!1,spiral:"rectangular",style:{fontFamily:"sans-serif",fontWeight:"900",whiteSpace:"nowrap"},tooltip:{followPointer:!0,pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.weight}</b><br/>'}});v(z.prototype,{animate:g,animateDrilldown:g,animateDrillupFrom:g,pointClass:q,setClip:g,placementStrategy:{random:function(b,c){const d=c.field;
c=c.rotation;return{x:w(d.width)-d.width/2,y:w(d.height)-d.height/2,rotation:a(c.orientations,b.index,c.from,c.to)}},center:function(b,c){c=c.rotation;return{x:0,y:0,rotation:a(c.orientations,b.index,c.from,c.to)}}},pointArrayMap:["weight"],spirals:{archimedean:D,rectangular:K,square:p},utils:{extendPlayingField:F,getRotation:a,isPolygonsColliding:J,rotate2DToOrigin:L,rotate2DToPoint:M}});l.registerSeriesType("wordcloud",z);"";return z});h(d,"masters/modules/wordcloud.src.js",[],function(){})});//# sourceMappingURL=wordcloud.js.map