/*
 Highcharts JS v11.1.0 (2023-08-20)

 X-range series

 (c) 2010-2021 Torstein Honsi, Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
'use strict';(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/xrange",["highcharts"],function(d){a(d);a.Highcharts=d;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function d(a,b,A,m){a.hasOwnProperty(b)||(a[b]=m.apply(null,A),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:b,module:a[b]}})))}a=a?a._modules:
{};d(a,"Series/XRange/XRangeSeriesDefaults.js",[a["Core/Utilities.js"]],function(a){const {correctFloat:b,isNumber:k,isObject:m}=a;"";return{colorByPoint:!0,dataLabels:{formatter:function(){let a=this.point.partialFill;m(a)&&(a=a.amount);if(k(a)&&0<a)return b(100*a)+"%"},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:'<span style="font-size: 0.8em">{point.x} - {point.x2}</span><br/>',pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.yCategory}</b><br/>'},
borderRadius:3,pointRange:0}});d(a,"Series/XRange/XRangePoint.js",[a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,b){const {series:{prototype:{pointClass:{prototype:k}}},seriesTypes:{column:{prototype:{pointClass:m}}}}=a;({extend:a}=b);class d extends m{constructor(){super(...arguments);this.series=this.options=void 0}static getColorByCategory(a,k){const b=a.options.colors||a.chart.options.colors;a=k.y%(b?b.length:a.chart.options.chart.colorCount);return{colorIndex:a,color:b&&
b[a]}}resolveColor(){const a=this.series;if(a.options.colorByPoint&&!this.options.color){const b=d.getColorByCategory(a,this);a.chart.styledMode||(this.color=b.color);this.options.colorIndex||(this.colorIndex=b.colorIndex)}else this.color||(this.color=a.color)}init(){k.init.apply(this,arguments);this.y||(this.y=0);return this}setState(){k.setState.apply(this,arguments);this.series.drawPoint(this,this.series.getAnimationVerb())}getLabelConfig(){const a=k.getLabelConfig.call(this),b=this.series.yAxis.categories;
a.x2=this.x2;a.yCategory=this.yCategory=b&&b[this.y];return a}isValid(){return"number"===typeof this.x&&"number"===typeof this.x2}}a(d.prototype,{ttBelow:!1,tooltipDateKeys:["x","x2"]});"";return d});d(a,"Series/XRange/XRangeSeries.js",[a["Core/Globals.js"],a["Core/Color/Color.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"],a["Series/XRange/XRangeSeriesDefaults.js"],a["Series/XRange/XRangePoint.js"]],function(a,b,d,m,H,I){function k(){let c,a;if(this.isXAxis){c=v(this.dataMax,-Number.MAX_VALUE);
for(const D of this.series)if(D.x2Data)for(const r of D.x2Data)r&&r>c&&(c=r,a=!0);a&&(this.dataMax=c)}}({noop:a}=a);const {parse:C}=b,{series:{prototype:E},seriesTypes:{column:F}}=d,{addEvent:A,clamp:w,defined:J,extend:K,find:G,isNumber:y,isObject:B,merge:t,pick:v,relativeLength:L}=m,M=[];class z extends F{constructor(){super(...arguments);this.points=this.options=this.data=void 0}static compose(c){m.pushUnique(M,c)&&A(c,"afterGetSeriesExtremes",k)}init(){super.init.apply(this,arguments);this.options.stacking=
void 0}getColumnMetrics(){const c=()=>{for(const c of this.chart.series){const a=c.xAxis;c.xAxis=c.yAxis;c.yAxis=a}};c();const a=super.getColumnMetrics();c();return a}cropData(c,a,r,b){a=E.cropData.call(this,this.x2Data,a,r,b);a.xData=c.slice(a.start,a.end);return a}findPointIndex(c){const {cropStart:a,points:r}=this,{id:b}=c;if(b)var g=(g=G(r,a=>a.id===b))?g.index:void 0;"undefined"===typeof g&&(g=(g=G(r,a=>a.x===c.x&&a.x2===c.x2&&!a.touched))?g.index:void 0);this.cropped&&y(g)&&y(a)&&g>=a&&(g-=
a);return g}alignDataLabel(a){const c=a.plotX;a.plotX=v(a.dlBox&&a.dlBox.centerX,a.plotX);super.alignDataLabel.apply(this,arguments);a.plotX=c}translatePoint(a){const c=this.xAxis;var b=this.yAxis,u=this.columnMetrics,g=this.options,d=g.minPointLength||0,h=(a.shapeArgs&&a.shapeArgs.width||0)/2,l=this.pointXOffset=u.offset,n=v(a.x2,a.x+(a.len||0)),f=g.borderRadius,p=a.plotX,e=c.translate(n,0,0,0,1);n=Math.abs(e-p);const k=this.chart.inverted;var q=v(g.borderWidth,1)%2/2;let m=u.offset,x=Math.round(u.width);
d&&(d-=n,0>d&&(d=0),p-=d/2,e+=d/2);p=Math.max(p,-10);e=w(e,-10,c.len+10);J(a.options.pointWidth)&&(m-=(Math.ceil(a.options.pointWidth)-x)/2,x=Math.ceil(a.options.pointWidth));g.pointPlacement&&y(a.plotY)&&b.categories&&(a.plotY=b.translate(a.y,0,1,0,1,g.pointPlacement));g=Math.floor(Math.min(p,e))+q;e=Math.floor(Math.max(p,e))+q-g;f=Math.min(L("object"===typeof f?f.radius:f||0,x),Math.min(e,x)/2);f={x:g,y:Math.floor(a.plotY+m)+q,width:e,height:x,r:f};a.shapeArgs=f;k?a.tooltipPos[1]+=l+h:a.tooltipPos[0]-=
h+l-f.width/2;h=f.x;l=h+f.width;0>h||l>c.len?(h=w(h,0,c.len),l=w(l,0,c.len),q=l-h,a.dlBox=t(f,{x:h,width:l-h,centerX:q?q/2:null})):a.dlBox=null;h=a.tooltipPos;l=k?1:0;q=k?0:1;u=this.columnMetrics?this.columnMetrics.offset:-u.width/2;h[l]=k?h[l]+f.width/2:w(h[l]+(c.reversed?-1:0)*f.width,0,c.len-1);h[q]=w(h[q]+(k?-1:1)*u,0,b.len-1);if(b=a.partialFill)B(b)&&(b=b.amount),y(b)||(b=0),a.partShapeArgs=t(f),p=Math.max(Math.round(n*b+a.plotX-p),0),a.clipRectArgs={x:c.reversed?f.x+n-p:f.x,y:f.y,width:p,height:f.height}}translate(){super.translate.apply(this,
arguments);for(const a of this.points)this.translatePoint(a)}drawPoint(a,b){const c=this.options,d=this.chart.renderer,g=a.shapeType,k=a.shapeArgs,h=a.partShapeArgs,l=a.clipRectArgs;var n=a.state,f=c.states[n||"normal"]||{};const p="undefined"===typeof n?"attr":b;n=this.pointAttribs(a,n);f=v(this.chart.options.chart.animation,f.animation);let e=a.graphic,m=a.partialFill;if(a.isNull||!1===a.visible)e&&(a.graphic=e.destroy());else{if(e)e.rect[b](k);else a.graphic=e=d.g("point").addClass(a.getClassName()).add(a.group||
this.group),e.rect=d[g](t(k)).addClass(a.getClassName()).addClass("highcharts-partfill-original").add(e);h&&(e.partRect?(e.partRect[b](t(h)),e.partialClipRect[b](t(l))):(e.partialClipRect=d.clipRect(l.x,l.y,l.width,l.height),e.partRect=d[g](h).addClass("highcharts-partfill-overlay").add(e).clip(e.partialClipRect)));this.chart.styledMode||(e.rect[b](n,f).shadow(c.shadow),h&&(B(m)||(m={}),B(c.partialFill)&&(m=t(c.partialFill,m)),a=m.fill||C(n.fill).brighten(-.3).get()||C(a.color||this.color).brighten(-.3).get(),
n.fill=a,e.partRect[p](n,f).shadow(c.shadow)))}}drawPoints(){const a=this.getAnimationVerb();for(const b of this.points)this.drawPoint(b,a)}getAnimationVerb(){return this.chart.pointCount<(this.options.animationLimit||250)?"animate":"attr"}isPointInside(a){const b=a.shapeArgs,c=a.plotX,d=a.plotY;return b?"undefined"!==typeof c&&"undefined"!==typeof d&&0<=d&&d<=this.yAxis.len&&0<=(b.x||0)+(b.width||0)&&c<=this.xAxis.len:super.isPointInside.apply(this,arguments)}}z.defaultOptions=t(F.defaultOptions,
H);K(z.prototype,{pointClass:I,cropShoulder:1,getExtremesFromAll:!0,parallelArrays:["x","x2","y"],requireSorting:!1,type:"xrange",animate:E.animate,autoIncrement:a,buildKDTree:a});d.registerSeriesType("xrange",z);return z});d(a,"masters/modules/xrange.src.js",[a["Core/Globals.js"],a["Series/XRange/XRangeSeries.js"]],function(a,b){b.compose(a.Axis)})});//# sourceMappingURL=xrange.js.map