/*
 Highcharts JS v11.1.0 (2023-08-20)

 3D features for Highcharts JS

 License: www.highcharts.com/license
*/
'use strict';(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/highcharts-3d",["highcharts"],function(F){a(F);a.Highcharts=F;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function F(a,y,r,J){a.hasOwnProperty(y)||(a[y]=J.apply(null,r),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:y,module:a[y]}})))}a=a?a._modules:
{};F(a,"Core/Math3D.js",[a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,y){function r(a,f,c,d){var l=f.options.chart.options3d;const g=E(d,c?f.inverted:!1),q={x:f.plotWidth/2,y:f.plotHeight/2,z:l.depth/2,vd:E(l.depth,1)*E(l.viewDistance,0)},x=f.scale3d||1;d=K*l.beta*(g?-1:1);l=K*l.alpha*(g?-1:1);var H=Math.cos(l),k=Math.cos(-d),m=Math.sin(l),I=Math.sin(-d);c||(q.x+=f.plotLeft,q.y+=f.plotTop);return a.map(function(d){var c=(g?d.y:d.x)-q.x;var a=(g?d.x:d.y)-q.y;d=(d.z||0)-q.z;c={x:k*c-I*d,
y:-m*I*c+H*a-k*m*d,z:H*I*c+m*a+H*k*d};a=u(c,q,q.vd);a.x=a.x*x+q.x;a.y=a.y*x+q.y;a.z=c.z*x+q.z;return{x:g?a.y:a.x,y:g?a.x:a.y,z:a.z}})}function u(a,f,c){f=0<c&&c<Number.POSITIVE_INFINITY?c/(a.z+f.z+c):1;return{x:a.x*f,y:a.y*f}}function g(a){let f=0,c,d;for(c=0;c<a.length;c++)d=(c+1)%a.length,f+=a[c].x*a[d].y-a[d].x*a[c].y;return f/2}const {deg2rad:K}=a,{pick:E}=y;return{perspective:r,perspective3D:u,pointCameraDistance:function(a,f){var c=f.options.chart.options3d,d=f.plotWidth/2;f=f.plotHeight/2;
c=E(c.depth,1)*E(c.viewDistance,0)+c.depth;return Math.sqrt(Math.pow(d-E(a.plotX,a.x),2)+Math.pow(f-E(a.plotY,a.y),2)+Math.pow(c-E(a.plotZ,a.z),2))},shapeArea:g,shapeArea3D:function(a,f,c){return g(r(a,f,c))}}});F(a,"Core/Renderer/SVG/SVGElement3D.js",[a["Core/Color/Color.js"],a["Core/Renderer/SVG/SVGElement.js"],a["Core/Utilities.js"]],function(a,y,r){const {parse:u}=a,{defined:g,merge:K,objectEach:E,pick:L}=r,f={base:{initArgs:function(a){const d=this,c=d.renderer,f=c[d.pathType+"Path"](a),g=f.zIndexes;
d.parts.forEach(function(a){const l={"class":"highcharts-3d-"+a,zIndex:g[a]||0};c.styledMode&&("top"===a?l.filter="url(#highcharts-brighter)":"side"===a&&(l.filter="url(#highcharts-darker)"));d[a]=c.path(f[a]).attr(l).add(d)});d.attr({"stroke-linejoin":"round",zIndex:g.group});d.originalDestroy=d.destroy;d.destroy=d.destroyParts;d.forcedSides=f.forcedSides},singleSetterForParts:function(a,d,f,g,q,x){const c={};g=[null,null,g||"attr",q,x];const l=f&&f.zIndexes;f?(l&&l.group&&this.attr({zIndex:l.group}),
E(f,function(d,g){c[g]={};c[g][a]=d;l&&(c[g].zIndex=f.zIndexes[g]||0)}),g[1]=c):(c[a]=d,g[0]=c);return this.processParts.apply(this,g)},processParts:function(a,d,f,g,q){const c=this;c.parts.forEach(function(l){d&&(a=L(d[l],!1));if(!1!==a)c[l][f](a,g,q)});return c},destroyParts:function(){this.processParts(null,null,"destroy");return this.originalDestroy()}}};f.cuboid=K(f.base,{parts:["front","top","side"],pathType:"cuboid",attr:function(a,d,f,u){if("string"===typeof a&&"undefined"!==typeof d){const c=
a;a={};a[c]=d}return a.shapeArgs||g(a.x)?this.singleSetterForParts("d",null,this.renderer[this.pathType+"Path"](a.shapeArgs||a)):y.prototype.attr.call(this,a,void 0,f,u)},animate:function(a,d,l){if(g(a.x)&&g(a.y)){a=this.renderer[this.pathType+"Path"](a);const c=a.forcedSides;this.singleSetterForParts("d",null,a,"animate",d,l);this.attr({zIndex:a.zIndexes.group});c!==this.forcedSides&&(this.forcedSides=c,this.renderer.styledMode||f.cuboid.fillSetter.call(this,this.fill))}else y.prototype.animate.call(this,
a,d,l);return this},fillSetter:function(a){this.forcedSides=this.forcedSides||[];this.singleSetterForParts("fill",null,{front:a,top:u(a).brighten(0<=this.forcedSides.indexOf("top")?0:.1).get(),side:u(a).brighten(0<=this.forcedSides.indexOf("side")?0:-.1).get()});this.color=this.fill=a;return this}});return f});F(a,"Core/Renderer/SVG/SVGRenderer3D.js",[a["Core/Animation/AnimationUtilities.js"],a["Core/Color/Color.js"],a["Core/Globals.js"],a["Core/Math3D.js"],a["Core/Renderer/SVG/SVGElement.js"],a["Core/Renderer/SVG/SVGElement3D.js"],
a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,y,r,J,g,K,E,L){const {animObject:f}=a,{parse:c}=y,{charts:d,deg2rad:l}=r,{perspective:u,shapeArea:q}=J,{defined:x,extend:H,merge:k,pick:m}=L,I=Math.cos,M=Math.sin,z=Math.PI,N=4*(Math.sqrt(2)-1)/3/(z/2);class G extends E{static compose(e){e=e.prototype;const a=G.prototype;e.elements3d=K;e.arc3d=a.arc3d;e.arc3dPath=a.arc3dPath;e.cuboid=a.cuboid;e.cuboidPath=a.cuboidPath;e.element3d=a.element3d;e.face3d=a.face3d;e.polyhedron=a.polyhedron;
e.toLinePath=a.toLinePath;e.toLineSegments=a.toLineSegments}static curveTo(a,d,b,n,h,v,w,A){let C=[],e=v-h;return v>h&&v-h>Math.PI/2+.0001?(C=C.concat(this.curveTo(a,d,b,n,h,h+Math.PI/2,w,A)),C=C.concat(this.curveTo(a,d,b,n,h+Math.PI/2,v,w,A))):v<h&&h-v>Math.PI/2+.0001?(C=C.concat(this.curveTo(a,d,b,n,h,h-Math.PI/2,w,A)),C=C.concat(this.curveTo(a,d,b,n,h-Math.PI/2,v,w,A))):[["C",a+b*Math.cos(h)-b*N*e*Math.sin(h)+w,d+n*Math.sin(h)+n*N*e*Math.cos(h)+A,a+b*Math.cos(v)+b*N*e*Math.sin(v)+w,d+n*Math.sin(v)-
n*N*e*Math.cos(v)+A,a+b*Math.cos(v)+w,d+n*Math.sin(v)+A]]}toLinePath(a,d){const b=[];a.forEach(function(a){b.push(["L",a.x,a.y])});a.length&&(b[0][0]="M",d&&b.push(["Z"]));return b}toLineSegments(a){let e=[],b=!0;a.forEach(function(a){e.push(b?["M",a.x,a.y]:["L",a.x,a.y]);b=!b});return e}face3d(a){const e=this,b=this.createElement("path");b.vertexes=[];b.insidePlotArea=!1;b.enabled=!0;b.attr=function(b){if("object"===typeof b&&(x(b.enabled)||x(b.vertexes)||x(b.insidePlotArea))){this.enabled=m(b.enabled,
this.enabled);this.vertexes=m(b.vertexes,this.vertexes);this.insidePlotArea=m(b.insidePlotArea,this.insidePlotArea);delete b.enabled;delete b.vertexes;delete b.insidePlotArea;var h=u(this.vertexes,d[e.chartIndex],this.insidePlotArea);const a=e.toLinePath(h,!0);h=q(h);b.d=a;b.visibility=this.enabled&&0<h?"inherit":"hidden"}return g.prototype.attr.apply(this,arguments)};b.animate=function(b){if("object"===typeof b&&(x(b.enabled)||x(b.vertexes)||x(b.insidePlotArea))){this.enabled=m(b.enabled,this.enabled);
this.vertexes=m(b.vertexes,this.vertexes);this.insidePlotArea=m(b.insidePlotArea,this.insidePlotArea);delete b.enabled;delete b.vertexes;delete b.insidePlotArea;var h=u(this.vertexes,d[e.chartIndex],this.insidePlotArea);const a=e.toLinePath(h,!0);h=q(h);h=this.enabled&&0<h?"visible":"hidden";b.d=a;this.attr("visibility",h)}return g.prototype.animate.apply(this,arguments)};return b.attr(a)}polyhedron(a){const e=this,b=this.g(),d=b.destroy;this.styledMode||b.attr({"stroke-linejoin":"round"});b.faces=
[];b.destroy=function(){for(let h=0;h<b.faces.length;h++)b.faces[h].destroy();return d.call(this)};b.attr=function(h,a,w,A){if("object"===typeof h&&x(h.faces)){for(;b.faces.length>h.faces.length;)b.faces.pop().destroy();for(;b.faces.length<h.faces.length;)b.faces.push(e.face3d().add(b));for(let a=0;a<h.faces.length;a++)e.styledMode&&delete h.faces[a].fill,b.faces[a].attr(h.faces[a],null,w,A);delete h.faces}return g.prototype.attr.apply(this,arguments)};b.animate=function(h,a,w){if(h&&h.faces){for(;b.faces.length>
h.faces.length;)b.faces.pop().destroy();for(;b.faces.length<h.faces.length;)b.faces.push(e.face3d().add(b));for(let e=0;e<h.faces.length;e++)b.faces[e].animate(h.faces[e],a,w);delete h.faces}return g.prototype.animate.apply(this,arguments)};return b.attr(a)}element3d(a,d){const b=this.g();H(b,this.elements3d[a]);b.initArgs(d);return b}cuboid(a){return this.element3d("cuboid",a)}cuboidPath(a){function e(h){return 0===w&&1<h&&6>h?{x:B[h].x,y:B[h].y+10,z:B[h].z}:B[0].x===B[7].x&&4<=h?{x:B[h].x+10,y:B[h].y,
z:B[h].z}:0===C&&2>h||5<h?{x:B[h].x,y:B[h].y,z:B[h].z+10}:B[h]}function b(h){return B[h]}let n=a.x||0,h=a.y||0,v=a.z||0,w=a.height||0;var A=a.width||0;let C=a.depth||0,D=d[this.chartIndex];let P,c,f=D.options.chart.options3d.alpha,p=0,B=[{x:n,y:h,z:v},{x:n+A,y:h,z:v},{x:n+A,y:h+w,z:v},{x:n,y:h+w,z:v},{x:n,y:h+w,z:v+C},{x:n+A,y:h+w,z:v+C},{x:n+A,y:h,z:v+C},{x:n,y:h,z:v+C}],g=[];B=u(B,D,a.insidePlotArea);var l=function(h,w,a){let C=[[],-1],d=h.map(b),v=w.map(b);h=h.map(e);w=w.map(e);0>q(d)?C=[d,0]:
0>q(v)?C=[v,1]:a&&(g.push(a),C=0>q(h)?[d,0]:0>q(w)?[v,1]:[d,0]);return C};var k=l([3,2,1,0],[7,6,5,4],"front");a=k[0];P=k[1];k=l([1,6,7,0],[4,5,2,3],"top");A=k[0];c=k[1];k=l([1,2,5,6],[0,7,4,3],"side");l=k[0];k=k[1];1===k?p+=1E6*(D.plotWidth-n):k||(p+=1E6*n);p+=10*(!c||0<=f&&180>=f||360>f&&357.5<f?D.plotHeight-h:10+h);1===P?p+=100*v:P||(p+=100*(1E3-v));return{front:this.toLinePath(a,!0),top:this.toLinePath(A,!0),side:this.toLinePath(l,!0),zIndexes:{group:Math.round(p)},forcedSides:g,isFront:P,isTop:c}}arc3d(a){function d(a){let w=
!1,b={},C;a=k(a);for(C in a)-1!==h.indexOf(C)&&(b[C]=a[C],delete a[C],w=!0);return w?[b,a]:!1}const b=this.g(),e=b.renderer,h="x y r innerR start end depth".split(" ");a=k(a);a.alpha=(a.alpha||0)*l;a.beta=(a.beta||0)*l;b.top=e.path();b.side1=e.path();b.side2=e.path();b.inn=e.path();b.out=e.path();b.onAdd=function(){const h=b.parentGroup,a=b.attr("class");b.top.add(b);["out","inn","side1","side2"].forEach(function(w){b[w].attr({"class":a+" highcharts-3d-side"}).add(h)})};["addClass","removeClass"].forEach(function(h){b[h]=
function(){const a=arguments;["top","out","inn","side1","side2"].forEach(function(w){b[w][h].apply(b[w],a)})}});b.setPaths=function(h){const a=b.renderer.arc3dPath(h),d=100*a.zTop;b.attribs=h;b.top.attr({d:a.top,zIndex:a.zTop});b.inn.attr({d:a.inn,zIndex:a.zInn});b.out.attr({d:a.out,zIndex:a.zOut});b.side1.attr({d:a.side1,zIndex:a.zSide1});b.side2.attr({d:a.side2,zIndex:a.zSide2});b.zIndex=d;b.attr({zIndex:d});h.center&&(b.top.setRadialReference(h.center),delete h.center)};b.setPaths(a);b.fillSetter=
function(h){const a=c(h).brighten(-.1).get();this.fill=h;this.side1.attr({fill:a});this.side2.attr({fill:a});this.inn.attr({fill:a});this.out.attr({fill:a});this.top.attr({fill:h});return this};["opacity","translateX","translateY","visibility"].forEach(function(a){b[a+"Setter"]=function(a,h){b[h]=a;["out","inn","side1","side2","top"].forEach(function(w){b[w].attr(h,a)})}});b.attr=function(a){let h,e;"object"===typeof a&&(e=d(a))&&(h=e[0],arguments[0]=e[1],H(b.attribs,h),b.setPaths(b.attribs));return g.prototype.attr.apply(b,
arguments)};b.animate=function(a,h,e){let w=this.attribs,A,v,n="data-"+Math.random().toString(26).substring(2,9);delete a.center;delete a.z;delete a.alpha;delete a.beta;v=f(m(h,this.renderer.globalAnimation));v.duration&&(h=d(a),b[n]=0,a[n]=1,b[n+"Setter"]=r.noop,h&&(A=h[0],v.step=function(a,h){function b(a){return w[a]+(m(A[a],w[a])-w[a])*h.pos}h.prop===n&&h.elem.setPaths(k(w,{x:b("x"),y:b("y"),r:b("r"),innerR:b("innerR"),start:b("start"),end:b("end"),depth:b("depth")}))}),h=v);return g.prototype.animate.call(this,
a,h,e)};b.destroy=function(){this.top.destroy();this.out.destroy();this.inn.destroy();this.side1.destroy();this.side2.destroy();return g.prototype.destroy.call(this)};b.hide=function(){this.top.hide();this.out.hide();this.inn.hide();this.side1.hide();this.side2.hide()};b.show=function(a){this.top.show(a);this.out.show(a);this.inn.show(a);this.side1.show(a);this.side2.show(a)};return b}arc3dPath(a){function d(a){a%=2*Math.PI;a>Math.PI&&(a=2*Math.PI-a);return a}var b=a.x||0,e=a.y||0,h=a.start||0,v=
(a.end||0)-.00001,w=a.r||0,A=a.innerR||0,C=a.depth||0,D=a.alpha||0,c=a.beta||0,f=Math.cos(h);const g=Math.sin(h);a=Math.cos(v);var p=Math.sin(v);const B=w*Math.cos(c);w*=Math.cos(D);const l=A*Math.cos(c),k=A*Math.cos(D);A=C*Math.sin(c);const m=C*Math.sin(D);C=[["M",b+B*f,e+w*g]];C=C.concat(G.curveTo(b,e,B,w,h,v,0,0));C.push(["L",b+l*a,e+k*p]);C=C.concat(G.curveTo(b,e,l,k,v,h,0,0));C.push(["Z"]);var u=0<c?Math.PI/2:0;c=0<D?0:Math.PI/2;u=h>-u?h:v>-u?-u:h;const x=v<z-c?v:h<z-c?z-c:v,q=2*z-c;D=[["M",
b+B*I(u),e+w*M(u)]];D=D.concat(G.curveTo(b,e,B,w,u,x,0,0));v>q&&h<q?(D.push(["L",b+B*I(x)+A,e+w*M(x)+m]),D=D.concat(G.curveTo(b,e,B,w,x,q,A,m)),D.push(["L",b+B*I(q),e+w*M(q)]),D=D.concat(G.curveTo(b,e,B,w,q,v,0,0)),D.push(["L",b+B*I(v)+A,e+w*M(v)+m]),D=D.concat(G.curveTo(b,e,B,w,v,q,A,m)),D.push(["L",b+B*I(q),e+w*M(q)]),D=D.concat(G.curveTo(b,e,B,w,q,x,0,0))):v>z-c&&h<z-c&&(D.push(["L",b+B*Math.cos(x)+A,e+w*Math.sin(x)+m]),D=D.concat(G.curveTo(b,e,B,w,x,v,A,m)),D.push(["L",b+B*Math.cos(v),e+w*Math.sin(v)]),
D=D.concat(G.curveTo(b,e,B,w,v,x,0,0)));D.push(["L",b+B*Math.cos(x)+A,e+w*Math.sin(x)+m]);D=D.concat(G.curveTo(b,e,B,w,x,u,A,m));D.push(["Z"]);c=[["M",b+l*f,e+k*g]];c=c.concat(G.curveTo(b,e,l,k,h,v,0,0));c.push(["L",b+l*Math.cos(v)+A,e+k*Math.sin(v)+m]);c=c.concat(G.curveTo(b,e,l,k,v,h,A,m));c.push(["Z"]);f=[["M",b+B*f,e+w*g],["L",b+B*f+A,e+w*g+m],["L",b+l*f+A,e+k*g+m],["L",b+l*f,e+k*g],["Z"]];b=[["M",b+B*a,e+w*p],["L",b+B*a+A,e+w*p+m],["L",b+l*a+A,e+k*p+m],["L",b+l*a,e+k*p],["Z"]];p=Math.atan2(m,
-A);e=Math.abs(v+p);a=Math.abs(h+p);h=Math.abs((h+v)/2+p);e=d(e);a=d(a);h=d(h);h*=1E5;v=1E5*a;e*=1E5;return{top:C,zTop:1E5*Math.PI+1,out:D,zOut:Math.max(h,v,e),inn:c,zInn:Math.max(h,v,e),side1:f,zSide1:.99*e,side2:b,zSide2:.99*v}}}return G});F(a,"Core/Chart/Chart3D.js",[a["Core/Color/Color.js"],a["Core/Defaults.js"],a["Core/Math3D.js"],a["Core/Utilities.js"]],function(a,y,r,J){const {parse:g}=a,{defaultOptions:u}=y,{perspective:E,shapeArea3D:L}=r,{addEvent:f,isArray:c,merge:d,pick:l,wrap:O}=J;var q;
(function(a){function q(a){this.is3d()&&"scatter"===a.options.type&&(a.options.type="scatter3d")}function k(){if(this.chart3d&&this.is3d()){const h=this.renderer;var a=this.options.chart.options3d;const b=this.chart3d.get3dFrame(),e=this.plotLeft,d=this.plotLeft+this.plotWidth,c=this.plotTop,f=this.plotTop+this.plotHeight;a=a.depth;const l=e-(b.left.visible?b.left.size:0),n=d+(b.right.visible?b.right.size:0),p=c-(b.top.visible?b.top.size:0),k=f+(b.bottom.visible?b.bottom.size:0),m=0-(b.front.visible?
b.front.size:0),t=a+(b.back.visible?b.back.size:0),z=this.hasRendered?"animate":"attr";this.chart3d.frame3d=b;this.frameShapes||(this.frameShapes={bottom:h.polyhedron().add(),top:h.polyhedron().add(),left:h.polyhedron().add(),right:h.polyhedron().add(),back:h.polyhedron().add(),front:h.polyhedron().add()});this.frameShapes.bottom[z]({"class":"highcharts-3d-frame highcharts-3d-frame-bottom",zIndex:b.bottom.frontFacing?-1E3:1E3,faces:[{fill:g(b.bottom.color).brighten(.1).get(),vertexes:[{x:l,y:k,z:m},
{x:n,y:k,z:m},{x:n,y:k,z:t},{x:l,y:k,z:t}],enabled:b.bottom.visible},{fill:g(b.bottom.color).brighten(.1).get(),vertexes:[{x:e,y:f,z:a},{x:d,y:f,z:a},{x:d,y:f,z:0},{x:e,y:f,z:0}],enabled:b.bottom.visible},{fill:g(b.bottom.color).brighten(-.1).get(),vertexes:[{x:l,y:k,z:m},{x:l,y:k,z:t},{x:e,y:f,z:a},{x:e,y:f,z:0}],enabled:b.bottom.visible&&!b.left.visible},{fill:g(b.bottom.color).brighten(-.1).get(),vertexes:[{x:n,y:k,z:t},{x:n,y:k,z:m},{x:d,y:f,z:0},{x:d,y:f,z:a}],enabled:b.bottom.visible&&!b.right.visible},
{fill:g(b.bottom.color).get(),vertexes:[{x:n,y:k,z:m},{x:l,y:k,z:m},{x:e,y:f,z:0},{x:d,y:f,z:0}],enabled:b.bottom.visible&&!b.front.visible},{fill:g(b.bottom.color).get(),vertexes:[{x:l,y:k,z:t},{x:n,y:k,z:t},{x:d,y:f,z:a},{x:e,y:f,z:a}],enabled:b.bottom.visible&&!b.back.visible}]});this.frameShapes.top[z]({"class":"highcharts-3d-frame highcharts-3d-frame-top",zIndex:b.top.frontFacing?-1E3:1E3,faces:[{fill:g(b.top.color).brighten(.1).get(),vertexes:[{x:l,y:p,z:t},{x:n,y:p,z:t},{x:n,y:p,z:m},{x:l,
y:p,z:m}],enabled:b.top.visible},{fill:g(b.top.color).brighten(.1).get(),vertexes:[{x:e,y:c,z:0},{x:d,y:c,z:0},{x:d,y:c,z:a},{x:e,y:c,z:a}],enabled:b.top.visible},{fill:g(b.top.color).brighten(-.1).get(),vertexes:[{x:l,y:p,z:t},{x:l,y:p,z:m},{x:e,y:c,z:0},{x:e,y:c,z:a}],enabled:b.top.visible&&!b.left.visible},{fill:g(b.top.color).brighten(-.1).get(),vertexes:[{x:n,y:p,z:m},{x:n,y:p,z:t},{x:d,y:c,z:a},{x:d,y:c,z:0}],enabled:b.top.visible&&!b.right.visible},{fill:g(b.top.color).get(),vertexes:[{x:l,
y:p,z:m},{x:n,y:p,z:m},{x:d,y:c,z:0},{x:e,y:c,z:0}],enabled:b.top.visible&&!b.front.visible},{fill:g(b.top.color).get(),vertexes:[{x:n,y:p,z:t},{x:l,y:p,z:t},{x:e,y:c,z:a},{x:d,y:c,z:a}],enabled:b.top.visible&&!b.back.visible}]});this.frameShapes.left[z]({"class":"highcharts-3d-frame highcharts-3d-frame-left",zIndex:b.left.frontFacing?-1E3:1E3,faces:[{fill:g(b.left.color).brighten(.1).get(),vertexes:[{x:l,y:k,z:m},{x:e,y:f,z:0},{x:e,y:f,z:a},{x:l,y:k,z:t}],enabled:b.left.visible&&!b.bottom.visible},
{fill:g(b.left.color).brighten(.1).get(),vertexes:[{x:l,y:p,z:t},{x:e,y:c,z:a},{x:e,y:c,z:0},{x:l,y:p,z:m}],enabled:b.left.visible&&!b.top.visible},{fill:g(b.left.color).brighten(-.1).get(),vertexes:[{x:l,y:k,z:t},{x:l,y:p,z:t},{x:l,y:p,z:m},{x:l,y:k,z:m}],enabled:b.left.visible},{fill:g(b.left.color).brighten(-.1).get(),vertexes:[{x:e,y:c,z:a},{x:e,y:f,z:a},{x:e,y:f,z:0},{x:e,y:c,z:0}],enabled:b.left.visible},{fill:g(b.left.color).get(),vertexes:[{x:l,y:k,z:m},{x:l,y:p,z:m},{x:e,y:c,z:0},{x:e,y:f,
z:0}],enabled:b.left.visible&&!b.front.visible},{fill:g(b.left.color).get(),vertexes:[{x:l,y:p,z:t},{x:l,y:k,z:t},{x:e,y:f,z:a},{x:e,y:c,z:a}],enabled:b.left.visible&&!b.back.visible}]});this.frameShapes.right[z]({"class":"highcharts-3d-frame highcharts-3d-frame-right",zIndex:b.right.frontFacing?-1E3:1E3,faces:[{fill:g(b.right.color).brighten(.1).get(),vertexes:[{x:n,y:k,z:t},{x:d,y:f,z:a},{x:d,y:f,z:0},{x:n,y:k,z:m}],enabled:b.right.visible&&!b.bottom.visible},{fill:g(b.right.color).brighten(.1).get(),
vertexes:[{x:n,y:p,z:m},{x:d,y:c,z:0},{x:d,y:c,z:a},{x:n,y:p,z:t}],enabled:b.right.visible&&!b.top.visible},{fill:g(b.right.color).brighten(-.1).get(),vertexes:[{x:d,y:c,z:0},{x:d,y:f,z:0},{x:d,y:f,z:a},{x:d,y:c,z:a}],enabled:b.right.visible},{fill:g(b.right.color).brighten(-.1).get(),vertexes:[{x:n,y:k,z:m},{x:n,y:p,z:m},{x:n,y:p,z:t},{x:n,y:k,z:t}],enabled:b.right.visible},{fill:g(b.right.color).get(),vertexes:[{x:n,y:p,z:m},{x:n,y:k,z:m},{x:d,y:f,z:0},{x:d,y:c,z:0}],enabled:b.right.visible&&!b.front.visible},
{fill:g(b.right.color).get(),vertexes:[{x:n,y:k,z:t},{x:n,y:p,z:t},{x:d,y:c,z:a},{x:d,y:f,z:a}],enabled:b.right.visible&&!b.back.visible}]});this.frameShapes.back[z]({"class":"highcharts-3d-frame highcharts-3d-frame-back",zIndex:b.back.frontFacing?-1E3:1E3,faces:[{fill:g(b.back.color).brighten(.1).get(),vertexes:[{x:n,y:k,z:t},{x:l,y:k,z:t},{x:e,y:f,z:a},{x:d,y:f,z:a}],enabled:b.back.visible&&!b.bottom.visible},{fill:g(b.back.color).brighten(.1).get(),vertexes:[{x:l,y:p,z:t},{x:n,y:p,z:t},{x:d,y:c,
z:a},{x:e,y:c,z:a}],enabled:b.back.visible&&!b.top.visible},{fill:g(b.back.color).brighten(-.1).get(),vertexes:[{x:l,y:k,z:t},{x:l,y:p,z:t},{x:e,y:c,z:a},{x:e,y:f,z:a}],enabled:b.back.visible&&!b.left.visible},{fill:g(b.back.color).brighten(-.1).get(),vertexes:[{x:n,y:p,z:t},{x:n,y:k,z:t},{x:d,y:f,z:a},{x:d,y:c,z:a}],enabled:b.back.visible&&!b.right.visible},{fill:g(b.back.color).get(),vertexes:[{x:e,y:c,z:a},{x:d,y:c,z:a},{x:d,y:f,z:a},{x:e,y:f,z:a}],enabled:b.back.visible},{fill:g(b.back.color).get(),
vertexes:[{x:l,y:k,z:t},{x:n,y:k,z:t},{x:n,y:p,z:t},{x:l,y:p,z:t}],enabled:b.back.visible}]});this.frameShapes.front[z]({"class":"highcharts-3d-frame highcharts-3d-frame-front",zIndex:b.front.frontFacing?-1E3:1E3,faces:[{fill:g(b.front.color).brighten(.1).get(),vertexes:[{x:l,y:k,z:m},{x:n,y:k,z:m},{x:d,y:f,z:0},{x:e,y:f,z:0}],enabled:b.front.visible&&!b.bottom.visible},{fill:g(b.front.color).brighten(.1).get(),vertexes:[{x:n,y:p,z:m},{x:l,y:p,z:m},{x:e,y:c,z:0},{x:d,y:c,z:0}],enabled:b.front.visible&&
!b.top.visible},{fill:g(b.front.color).brighten(-.1).get(),vertexes:[{x:l,y:p,z:m},{x:l,y:k,z:m},{x:e,y:f,z:0},{x:e,y:c,z:0}],enabled:b.front.visible&&!b.left.visible},{fill:g(b.front.color).brighten(-.1).get(),vertexes:[{x:n,y:k,z:m},{x:n,y:p,z:m},{x:d,y:c,z:0},{x:d,y:f,z:0}],enabled:b.front.visible&&!b.right.visible},{fill:g(b.front.color).get(),vertexes:[{x:d,y:c,z:0},{x:e,y:c,z:0},{x:e,y:f,z:0},{x:d,y:f,z:0}],enabled:b.front.visible},{fill:g(b.front.color).get(),vertexes:[{x:n,y:k,z:m},{x:l,y:k,
z:m},{x:l,y:p,z:m},{x:n,y:p,z:m}],enabled:b.front.visible}]})}}function m(){this.styledMode&&[{name:"darker",slope:.6},{name:"brighter",slope:1.4}].forEach(function(a){this.renderer.definition({tagName:"filter",attributes:{id:"highcharts-"+a.name},children:[{tagName:"feComponentTransfer",children:[{tagName:"feFuncR",attributes:{type:"linear",slope:a.slope}},{tagName:"feFuncG",attributes:{type:"linear",slope:a.slope}},{tagName:"feFuncB",attributes:{type:"linear",slope:a.slope}}]}]})},this)}function x(){const a=
this.options;this.is3d()&&(a.series||[]).forEach(function(b){"scatter"===(b.type||a.chart.type||a.chart.defaultSeriesType)&&(b.type="scatter3d")})}function M(){const a=this.options.chart.options3d;if(this.chart3d&&this.is3d()){a&&(a.alpha=a.alpha%360+(0<=a.alpha?0:360),a.beta=a.beta%360+(0<=a.beta?0:360));const b=this.inverted,e=this.clipBox,h=this.margin,d=b?"x":"y",c=b?"height":"width",f=b?"width":"height";e[b?"y":"x"]=-(h[3]||0);e[d]=-(h[0]||0);e[c]=this.chartWidth+(h[3]||0)+(h[1]||0);e[f]=this.chartHeight+
(h[0]||0)+(h[2]||0);this.scale3d=1;!0===a.fitToPlot&&(this.scale3d=this.chart3d.getScale(a.depth));this.chart3d.frame3d=this.chart3d.get3dFrame()}}function z(){this.is3d()&&(this.isDirtyBox=!0)}function r(){this.chart3d&&this.is3d()&&(this.chart3d.frame3d=this.chart3d.get3dFrame())}function G(){this.chart3d||(this.chart3d=new n(this))}function e(a){return this.is3d()||a.apply(this,[].slice.call(arguments,1))}function t(a){let b=this.series.length;if(this.is3d())for(;b--;)a=this.series[b],a.translate(),
a.render();else a.call(this)}function b(a){a.apply(this,[].slice.call(arguments,1));this.is3d()&&(this.container.className+=" highcharts-3d-chart")}class n{constructor(a){this.frame3d=void 0;this.chart=a}get3dFrame(){function a(a,b,e){const d=["size","color","visible"],h={};for(let b=0;b<d.length;b++){const e=d[b];for(let b=0;b<a.length;b++)if("object"===typeof a[b]){const d=a[b][e];if("undefined"!==typeof d&&null!==d){h[e]=d;break}}}a=e;!0===h.visible||!1===h.visible?a=h.visible:"auto"===h.visible&&
(a=0<b);return{size:l(h.size,1),color:l(h.color,"none"),frontFacing:0<b,visible:a}}function b(a){a=L(a,e);return.5<a?1:-.5>a?-1:0}const e=this.chart;var d=e.options.chart.options3d,c=d.frame,f=e.plotLeft;const n=e.plotLeft+e.plotWidth,k=e.plotTop;var m=e.plotTop+e.plotHeight;const t=d.depth;var g=b([{x:f,y:m,z:t},{x:n,y:m,z:t},{x:n,y:m,z:0},{x:f,y:m,z:0}]),z=b([{x:f,y:k,z:0},{x:n,y:k,z:0},{x:n,y:k,z:t},{x:f,y:k,z:t}]),u=b([{x:f,y:k,z:0},{x:f,y:k,z:t},{x:f,y:m,z:t},{x:f,y:m,z:0}]),q=b([{x:n,y:k,z:t},
{x:n,y:k,z:0},{x:n,y:m,z:0},{x:n,y:m,z:t}]);const x=b([{x:f,y:m,z:0},{x:n,y:m,z:0},{x:n,y:k,z:0},{x:f,y:k,z:0}]),M=b([{x:f,y:k,z:t},{x:n,y:k,z:t},{x:n,y:m,z:t},{x:f,y:m,z:t}]);let I=!1,G=!1,r=!1,y=!1;[].concat(e.xAxis,e.yAxis,e.zAxis).forEach(function(a){a&&(a.horiz?a.opposite?G=!0:I=!0:a.opposite?y=!0:r=!0)});c={axes:{},bottom:a([c.bottom,c.top,c],g,I),top:a([c.top,c.bottom,c],z,G),left:a([c.left,c.right,c.side,c],u,r),right:a([c.right,c.left,c.side,c],q,y),back:a([c.back,c.front,c],M,!0),front:a([c.front,
c.back,c],x,!1)};"auto"===d.axisLabelPosition?(q=function(a,b){return a.visible!==b.visible||a.visible&&b.visible&&a.frontFacing!==b.frontFacing},d=[],q(c.left,c.front)&&d.push({y:(k+m)/2,x:f,z:0,xDir:{x:1,y:0,z:0}}),q(c.left,c.back)&&d.push({y:(k+m)/2,x:f,z:t,xDir:{x:0,y:0,z:-1}}),q(c.right,c.front)&&d.push({y:(k+m)/2,x:n,z:0,xDir:{x:0,y:0,z:1}}),q(c.right,c.back)&&d.push({y:(k+m)/2,x:n,z:t,xDir:{x:-1,y:0,z:0}}),g=[],q(c.bottom,c.front)&&g.push({x:(f+n)/2,y:m,z:0,xDir:{x:1,y:0,z:0}}),q(c.bottom,
c.back)&&g.push({x:(f+n)/2,y:m,z:t,xDir:{x:-1,y:0,z:0}}),z=[],q(c.top,c.front)&&z.push({x:(f+n)/2,y:k,z:0,xDir:{x:1,y:0,z:0}}),q(c.top,c.back)&&z.push({x:(f+n)/2,y:k,z:t,xDir:{x:-1,y:0,z:0}}),u=[],q(c.bottom,c.left)&&u.push({z:(0+t)/2,y:m,x:f,xDir:{x:0,y:0,z:-1}}),q(c.bottom,c.right)&&u.push({z:(0+t)/2,y:m,x:n,xDir:{x:0,y:0,z:1}}),m=[],q(c.top,c.left)&&m.push({z:(0+t)/2,y:k,x:f,xDir:{x:0,y:0,z:-1}}),q(c.top,c.right)&&m.push({z:(0+t)/2,y:k,x:n,xDir:{x:0,y:0,z:1}}),f=function(a,b,d){if(0===a.length)return null;
if(1===a.length)return a[0];const h=E(a,e,!1);let c=0;for(let a=1;a<h.length;a++)d*h[a][b]>d*h[c][b]?c=a:d*h[a][b]===d*h[c][b]&&h[a].z<h[c].z&&(c=a);return a[c]},c.axes={y:{left:f(d,"x",-1),right:f(d,"x",1)},x:{top:f(z,"y",-1),bottom:f(g,"y",1)},z:{top:f(m,"y",-1),bottom:f(u,"y",1)}}):c.axes={y:{left:{x:f,z:0,xDir:{x:1,y:0,z:0}},right:{x:n,z:0,xDir:{x:0,y:0,z:1}}},x:{top:{y:k,z:0,xDir:{x:1,y:0,z:0}},bottom:{y:m,z:0,xDir:{x:1,y:0,z:0}}},z:{top:{x:r?n:f,y:k,xDir:r?{x:0,y:0,z:1}:{x:0,y:0,z:-1}},bottom:{x:r?
n:f,y:m,xDir:r?{x:0,y:0,z:1}:{x:0,y:0,z:-1}}}};return c}getScale(a){const b=this.chart,e=b.plotLeft,d=b.plotWidth+e,h=b.plotTop,c=b.plotHeight+h,f=e+b.plotWidth/2,n=h+b.plotHeight/2;var k=Number.MAX_VALUE,m=-Number.MAX_VALUE,l=Number.MAX_VALUE,t=-Number.MAX_VALUE;let g,z=1;g=[{x:e,y:h,z:0},{x:e,y:h,z:a}];[0,1].forEach(function(a){g.push({x:d,y:g[a].y,z:g[a].z})});[0,1,2,3].forEach(function(a){g.push({x:g[a].x,y:c,z:g[a].z})});g=E(g,b,!1);g.forEach(function(a){k=Math.min(k,a.x);m=Math.max(m,a.x);l=
Math.min(l,a.y);t=Math.max(t,a.y)});e>k&&(z=Math.min(z,1-Math.abs((e+f)/(k+f))%1));d<m&&(z=Math.min(z,(d-f)/(m-f)));h>l&&(z=0>l?Math.min(z,(h+n)/(-l+h+n)):Math.min(z,1-(h+n)/(l+n)%1));c<t&&(z=Math.min(z,Math.abs((c-n)/(t-n))));return z}}a.Composition=n;a.defaultOptions={chart:{options3d:{enabled:!1,alpha:0,beta:0,depth:100,fitToPlot:!0,viewDistance:25,axisLabelPosition:null,frame:{visible:"default",size:1,bottom:{},top:{},left:{},right:{},back:{},front:{}}}}};a.compose=function(h,n){const l=h.prototype;
n=n.prototype;l.is3d=function(){return!(!this.options.chart.options3d||!this.options.chart.options3d.enabled)};l.propsRequireDirtyBox.push("chart.options3d");l.propsRequireUpdateSeries.push("chart.options3d");n.matrixSetter=function(){let a;if(1>this.pos&&(c(this.start)||c(this.end))){const b=this.start||[1,0,0,1,0,0],e=this.end||[1,0,0,1,0,0];a=[];for(let d=0;6>d;d++)a.push(this.pos*e[d]+(1-this.pos)*b[d])}else a=this.end;this.elem.attr(this.prop,a,null,!0)};d(!0,u,a.defaultOptions);f(h,"init",G);
f(h,"addSeries",q);f(h,"afterDrawChartBox",k);f(h,"afterGetContainer",m);f(h,"afterInit",x);f(h,"afterSetChartSize",M);f(h,"beforeRedraw",z);f(h,"beforeRender",r);O(l,"isInsidePlot",e);O(l,"renderSeries",t);O(l,"setClassName",b)}})(q||(q={}));"";return q});F(a,"Core/Axis/ZAxis.js",[a["Core/Axis/Axis.js"],a["Core/Utilities.js"]],function(a,y){function u(a){return new c(this,a)}function J(){const a=this.options.zAxis=L(this.options.zAxis||{});this.is3d()&&(this.zAxis=[],a.forEach(a=>{this.addZAxis(a).setScale()}))}
const {addEvent:g,merge:K,pick:E,splat:L}=y,f=[];class c extends a{constructor(){super(...arguments);this.isZAxis=!0}static compose(a){y.pushUnique(f,a)&&(g(a,"afterGetAxes",J),a=a.prototype,a.addZAxis=u,a.collectionsWithInit.zAxis=[a.addZAxis],a.collectionsWithUpdate.push("zAxis"))}init(a,c){this.isZAxis=!0;super.init(a,c,"zAxis")}getSeriesExtremes(){const a=this.chart;this.hasVisibleSeries=!1;this.dataMin=this.dataMax=this.ignoreMinPadding=this.ignoreMaxPadding=void 0;this.stacking&&this.stacking.buildStacks();
this.series.forEach(d=>{if(d.visible||!a.options.chart.ignoreHiddenSeries)this.hasVisibleSeries=!0,d=d.zData,d.length&&(this.dataMin=Math.min(E(this.dataMin,d[0]),Math.min.apply(null,d)),this.dataMax=Math.max(E(this.dataMax,d[0]),Math.max.apply(null,d)))})}setAxisSize(){const a=this.chart;super.setAxisSize();this.width=this.len=a.options.chart.options3d&&a.options.chart.options3d.depth||0;this.right=a.chartWidth-this.width-this.left}setOptions(a){a=K({offset:0,lineWidth:0},a);super.setOptions(a)}}
return c});F(a,"Core/Axis/Axis3DDefaults.js",[],function(){return{labels:{position3d:"offset",skew3d:!1},title:{position3d:null,skew3d:null}}});F(a,"Core/Axis/Tick3DComposition.js",[a["Core/Utilities.js"]],function(a){function u(a){const f=this.axis.axis3D;f&&g(a.pos,f.fix3dPosition(a.pos))}function r(a){var f=this.axis.axis3D;const c=a.apply(this,[].slice.call(arguments,1));if(f){const a=c[0],l=c[1];if("M"===a[0]&&"L"===l[0])return f=[f.fix3dPosition({x:a[1],y:a[2],z:0}),f.fix3dPosition({x:l[1],
y:l[2],z:0})],this.axis.chart.renderer.toLineSegments(f)}return c}const {addEvent:J,extend:g,wrap:K}=a,E=[];return{compose:function(g){a.pushUnique(E,g)&&(J(g,"afterGetLabelPosition",u),K(g.prototype,"getMarkPath",r))}}});F(a,"Core/Axis/Axis3DComposition.js",[a["Core/Axis/Axis3DDefaults.js"],a["Core/Globals.js"],a["Core/Math3D.js"],a["Core/Axis/Tick3DComposition.js"],a["Core/Utilities.js"]],function(a,y,r,J,g){function u(){const a=this.chart,d=this.options;a.is3d&&a.is3d()&&"colorAxis"!==this.coll&&
(d.tickWidth=M(d.tickWidth,0),d.gridLineWidth=M(d.gridLineWidth,1))}function E(a){this.chart.is3d()&&"colorAxis"!==this.coll&&a.point&&(a.point.crosshairPos=this.isXAxis?a.point.axisXpos:this.len-a.point.axisYpos)}function L(){this.axis3D||(this.axis3D=new G(this))}function f(a){return this.chart.is3d()&&"colorAxis"!==this.coll?[]:a.apply(this,[].slice.call(arguments,1))}function c(a){if(!this.chart.is3d()||"colorAxis"===this.coll)return a.apply(this,[].slice.call(arguments,1));var e=arguments,b=
e[2];const d=[];e=this.getPlotLinePath({value:e[1]});b=this.getPlotLinePath({value:b});if(e&&b)for(let a=0;a<e.length;a+=2){const h=e[a],c=e[a+1],f=b[a],n=b[a+1];"M"===h[0]&&"L"===c[0]&&"M"===f[0]&&"L"===n[0]&&d.push(h,c,n,["L",f[1],f[2]],["Z"])}return d}function d(a){var e=this.axis3D;const b=this.chart;var d=a.apply(this,[].slice.call(arguments,1));if("colorAxis"===this.coll||!b.chart3d||!b.is3d()||null===d)return d;var h=b.options.chart.options3d;const c=this.isZAxis?b.plotWidth:h.depth;h=b.chart3d.frame3d;
const f=d[0],k=d[1];d=[];"M"===f[0]&&"L"===k[0]&&(e=[e.swapZ({x:f[1],y:f[2],z:0}),e.swapZ({x:f[1],y:f[2],z:c}),e.swapZ({x:k[1],y:k[2],z:0}),e.swapZ({x:k[1],y:k[2],z:c})],this.horiz?(this.isZAxis?(h.left.visible&&d.push(e[0],e[2]),h.right.visible&&d.push(e[1],e[3])):(h.front.visible&&d.push(e[0],e[2]),h.back.visible&&d.push(e[1],e[3])),h.top.visible&&d.push(e[0],e[1]),h.bottom.visible&&d.push(e[2],e[3])):(h.front.visible&&d.push(e[0],e[2]),h.back.visible&&d.push(e[1],e[3]),h.left.visible&&d.push(e[0],
e[1]),h.right.visible&&d.push(e[2],e[3])),d=x(d,this.chart,!1));return b.renderer.toLineSegments(d)}function l(a,d){var b=this.chart,e=this.ticks,h=this.gridGroup;if(this.categories&&b.frameShapes&&b.is3d()&&h&&d&&d.label){h=h.element.childNodes[0].getBBox();const a=b.frameShapes.left.getBBox();var c=b.options.chart.options3d;b={x:b.plotWidth/2,y:b.plotHeight/2,z:c.depth/2,vd:M(c.depth,1)*M(c.viewDistance,0)};c=d.pos;const f=e[c-1];e=e[c+1];let k,m;0!==c&&f&&f.label&&f.label.xy&&(k=H({x:f.label.xy.x,
y:f.label.xy.y,z:null},b,b.vd));e&&e.label&&e.label.xy&&(m=H({x:e.label.xy.x,y:e.label.xy.y,z:null},b,b.vd));e={x:d.label.xy.x,y:d.label.xy.y,z:null};e=H(e,b,b.vd);return Math.abs(k?e.x-k.x:m?m.x-e.x:h.x-a.x)}return a.apply(this,[].slice.call(arguments,1))}function O(a){const e=a.apply(this,[].slice.call(arguments,1));return this.axis3D?this.axis3D.fix3dPosition(e,!0):e}const {deg2rad:q}=y,{perspective:x,perspective3D:H,shapeArea:k}=r,{addEvent:m,merge:I,pick:M,wrap:z}=g,N=[];class G{static compose(e,
k){J.compose(k);g.pushUnique(N,e)&&(I(!0,e.defaultOptions,a),e.keepProps.push("axis3D"),m(e,"init",L),m(e,"afterSetOptions",u),m(e,"drawCrosshair",E),e=e.prototype,z(e,"getLinePath",f),z(e,"getPlotBandPath",c),z(e,"getPlotLinePath",d),z(e,"getSlotWidth",l),z(e,"getTitlePosition",O))}constructor(a){this.axis=a}fix3dPosition(a,d){const b=this.axis;var e=b.chart;if("colorAxis"===b.coll||!e.chart3d||!e.is3d())return a;var c=q*e.options.chart.options3d.alpha,f=q*e.options.chart.options3d.beta,m=M(d&&b.options.title.position3d,
b.options.labels.position3d);d=M(d&&b.options.title.skew3d,b.options.labels.skew3d);const l=e.chart3d.frame3d;var g=e.plotLeft;const z=e.plotWidth+g,t=e.plotTop,u=e.plotHeight+t;let I=e=0;var p={x:0,y:1,z:0};let G=!1;a=b.axis3D.swapZ({x:a.x,y:a.y,z:0});if(b.isZAxis)if(b.opposite){if(null===l.axes.z.top)return{};I=a.y-t;a.x=l.axes.z.top.x;a.y=l.axes.z.top.y;g=l.axes.z.top.xDir;G=!l.top.frontFacing}else{if(null===l.axes.z.bottom)return{};I=a.y-u;a.x=l.axes.z.bottom.x;a.y=l.axes.z.bottom.y;g=l.axes.z.bottom.xDir;
G=!l.bottom.frontFacing}else if(b.horiz)if(b.opposite){if(null===l.axes.x.top)return{};I=a.y-t;a.y=l.axes.x.top.y;a.z=l.axes.x.top.z;g=l.axes.x.top.xDir;G=!l.top.frontFacing}else{if(null===l.axes.x.bottom)return{};I=a.y-u;a.y=l.axes.x.bottom.y;a.z=l.axes.x.bottom.z;g=l.axes.x.bottom.xDir;G=!l.bottom.frontFacing}else if(b.opposite){if(null===l.axes.y.right)return{};e=a.x-z;a.x=l.axes.y.right.x;a.z=l.axes.y.right.z;g=l.axes.y.right.xDir;g={x:g.z,y:g.y,z:-g.x}}else{if(null===l.axes.y.left)return{};e=
a.x-g;a.x=l.axes.y.left.x;a.z=l.axes.y.left.z;g=l.axes.y.left.xDir}"chart"!==m&&("flap"===m?b.horiz?(f=Math.sin(c),c=Math.cos(c),b.opposite&&(f=-f),G&&(f=-f),p={x:g.z*f,y:c,z:-g.x*f}):g={x:Math.cos(f),y:0,z:Math.sin(f)}:"ortho"===m?b.horiz?(p=Math.cos(c),m=Math.sin(f)*p,c=-Math.sin(c),f=-p*Math.cos(f),p={x:g.y*f-g.z*c,y:g.z*m-g.x*f,z:g.x*c-g.y*m},c=1/Math.sqrt(p.x*p.x+p.y*p.y+p.z*p.z),G&&(c=-c),p={x:c*p.x,y:c*p.y,z:c*p.z}):g={x:Math.cos(f),y:0,z:Math.sin(f)}:b.horiz?p={x:Math.sin(f)*Math.sin(c),y:Math.cos(c),
z:-Math.cos(f)*Math.sin(c)}:g={x:Math.cos(f),y:0,z:Math.sin(f)});a.x+=e*g.x+I*p.x;a.y+=e*g.y+I*p.y;a.z+=e*g.z+I*p.z;e=x([a],b.chart)[0];d&&(0>k(x([a,{x:a.x+g.x,y:a.y+g.y,z:a.z+g.z},{x:a.x+p.x,y:a.y+p.y,z:a.z+p.z}],b.chart))&&(g={x:-g.x,y:-g.y,z:-g.z}),a=x([{x:a.x,y:a.y,z:a.z},{x:a.x+g.x,y:a.y+g.y,z:a.z+g.z},{x:a.x+p.x,y:a.y+p.y,z:a.z+p.z}],b.chart),e.matrix=[a[1].x-a[0].x,a[1].y-a[0].y,a[2].x-a[0].x,a[2].y-a[0].y,e.x,e.y],e.matrix[4]-=e.x*e.matrix[0]+e.y*e.matrix[2],e.matrix[5]-=e.x*e.matrix[1]+e.y*
e.matrix[3]);return e}swapZ(a,d){const b=this.axis;return b.isZAxis?(d=d?0:b.chart.plotLeft,{x:d+a.z,y:a.y,z:a.x-d}):a}}return G});F(a,"Core/Series/Series3D.js",[a["Core/Math3D.js"],a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,y,r){const {perspective:u}=a,{addEvent:g,extend:K,merge:E,pick:L,isNumber:f}=r;class c extends y{translate(){super.translate.apply(this,arguments);this.chart.is3d()&&this.translate3dPoints()}translate3dPoints(){var a=this.options,c=this.chart,g=L(this.zAxis,
c.options.zAxis[0]);let q=[],x,r,k=[];this.zPadding=(a.stacking?f(a.stack)?a.stack:0:this.index||0)*(a.depth||0+(a.groupZPadding||1));for(r=0;r<this.data.length;r++)a=this.data[r],g&&g.translate?(x=g.logarithmic&&g.val2lin?g.val2lin(a.z):a.z,a.plotZ=g.translate(x),a.isInside=a.isInside?x>=g.min&&x<=g.max:!1):a.plotZ=this.zPadding,a.axisXpos=a.plotX,a.axisYpos=a.plotY,a.axisZpos=a.plotZ,q.push({x:a.plotX,y:a.plotY,z:a.plotZ}),k.push(a.plotX||0);this.rawPointsX=k;c=u(q,c,!0);for(r=0;r<this.data.length;r++)a=
this.data[r],g=c[r],a.plotX=g.x,a.plotY=g.y,a.plotZ=g.z}}c.defaultOptions=E(y.defaultOptions);g(y,"afterTranslate",function(){this.chart.is3d()&&this.translate3dPoints()});K(y.prototype,{translate3dPoints:c.prototype.translate3dPoints});return c});F(a,"Series/Area3D/Area3DSeries.js",[a["Core/Math3D.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,y,r){function u(a){const c=a.apply(this,[].slice.call(arguments,1));if(!this.chart.is3d())return c;var d=K.getGraphPath,f=this.options;
const u=Math.round(this.yAxis.getThreshold(f.threshold));let q=[];if(this.rawPointsX)for(let a=0;a<this.points.length;a++)q.push({x:this.rawPointsX[a],y:f.stacking?this.points[a].yBottom:u,z:this.zPadding});f=this.chart.options.chart.options3d;q=g(q,this.chart,!0).map(a=>({plotX:a.x,plotY:a.y,plotZ:a.z}));this.group&&f&&f.depth&&f.beta&&(this.markerGroup&&(this.markerGroup.add(this.group),this.markerGroup.attr({translateX:0,translateY:0})),this.group.attr({zIndex:Math.max(1,270<f.beta||90>f.beta?
f.depth-Math.round(this.zPadding||0):Math.round(this.zPadding||0))}));q.reversed=!0;d=d.call(this,q,!0,!0);d[0]&&"M"===d[0][0]&&(d[0]=["L",d[0][1],d[0][2]]);this.areaPath&&(d=this.areaPath.splice(0,this.areaPath.length/2).concat(d),d.xMap=this.areaPath.xMap,this.areaPath=d);return c}const {perspective:g}=a,{seriesTypes:{line:{prototype:K}}}=y,{wrap:E}=r,L=[];return{compose:function(a){r.pushUnique(L,a)&&E(a.prototype,"getGraphPath",u)}}});F(a,"Series/Column3D/Column3DComposition.js",[a["Series/Column/ColumnSeries.js"],
a["Core/Series/Series.js"],a["Core/Math3D.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Axis/Stacking/StackItem.js"],a["Core/Utilities.js"]],function(a,y,r,J,g,K){function u(a,c){const d=a.series,f={totalStacks:0};let g,k=1;d.forEach(function(a){g=x(a.options.stack,c?0:d.length-1-a.index);f[g]?f[g].series.push(a):(f[g]={series:[a],position:k},k++)});f.totalStacks=k+1;return f}function L(a){const c=a.apply(this,[].slice.call(arguments,1));this.chart.is3d&&this.chart.is3d()&&(c.stroke=this.options.edgeColor||
c.fill,c["stroke-width"]=x(this.options.edgeWidth,1));return c}function f(a,c,d){const f=this.chart.is3d&&this.chart.is3d();f&&(this.options.inactiveOtherPoints=!0);a.call(this,c,d);f&&(this.options.inactiveOtherPoints=!1)}function c(a,...c){return this.series.chart.is3d()?this.graphic&&"g"!==this.graphic.element.nodeName:a.apply(this,c)}const {prototype:d}=a,{perspective:l}=r,{addEvent:F,extend:q,pick:x,wrap:H}=K;H(d,"translate",function(a){a.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&
this.translate3dShapes()});H(y.prototype,"justifyDataLabel",function(a){return arguments[2].outside3dPlot?!1:a.apply(this,[].slice.call(arguments,1))});d.translate3dPoints=function(){};d.translate3dShapes=function(){let a=this,c=a.chart,d=a.options,f=d.depth,g=(d.stacking?d.stack||0:a.index)*(f+(d.groupZPadding||1)),u=a.borderWidth%2?.5:0,r;c.inverted&&!a.yAxis.reversed&&(u*=-1);!1!==d.grouping&&(g=0);g+=d.groupZPadding||1;a.data.forEach(function(e){e.outside3dPlot=null;if(null!==e.y){const b=q({x:0,
y:0,width:0,height:0},e.shapeArgs||{});var d=e.tooltipPos;let k;[["x","width"],["y","height"]].forEach(c=>{k=b[c[0]]-u;0>k&&(b[c[1]]+=b[c[0]]+u,b[c[0]]=-u,k=0);k+b[c[1]]>a[c[0]+"Axis"].len&&0!==b[c[1]]&&(b[c[1]]=a[c[0]+"Axis"].len-b[c[0]]);if(0!==b[c[1]]&&(b[c[0]]>=a[c[0]+"Axis"].len||b[c[0]]+b[c[1]]<=u)){for(const a in b)b[a]="y"===a?-9999:0;e.outside3dPlot=!0}});"roundedRect"===e.shapeType&&(e.shapeType="cuboid");e.shapeArgs=q(b,{z:g,depth:f,insidePlotArea:!0});r={x:b.x+b.width/2,y:b.y,z:g+f/2};
c.inverted&&(r.x=b.height,r.y=e.clientX||0);e.plot3d=l([r],c,!0,!1)[0];d&&(d=l([{x:d[0],y:d[1],z:g+f/2}],c,!0,!1)[0],e.tooltipPos=[d.x,d.y])}});a.z=g};H(d,"animate",function(a){if(this.chart.is3d()){const a=this.yAxis,c=this,d=this.yAxis.reversed;arguments[1]?c.data.forEach(function(c){null!==c.y&&(c.height=c.shapeArgs.height,c.shapey=c.shapeArgs.y,c.shapeArgs.height=1,d||(c.shapeArgs.y=c.stackY?c.plotY+a.translate(c.stackY):c.plotY+(c.negative?-c.height:c.height)))}):(c.data.forEach(function(a){if(null!==
a.y&&(a.shapeArgs.height=a.height,a.shapeArgs.y=a.shapey,a.graphic))a.graphic[a.outside3dPlot?"attr":"animate"](a.shapeArgs,c.options.animation)}),this.drawDataLabels())}else a.apply(this,[].slice.call(arguments,1))});H(d,"plotGroup",function(a,c,d,f,g,l){"dataLabelsGroup"!==c&&"markerGroup"!==c&&this.chart.is3d()&&(this[c]&&delete this[c],l&&(this.chart.columnGroup||(this.chart.columnGroup=this.chart.renderer.g("columnGroup").add(l)),this[c]=this.chart.columnGroup,this.chart.columnGroup.attr(this.getPlotBox()),
this[c].survive=!0,"group"===c&&(arguments[3]="visible")));return a.apply(this,Array.prototype.slice.call(arguments,1))});H(d,"setVisible",function(a,c){const d=this;d.chart.is3d()&&d.data.forEach(function(a){a.visible=a.options.visible=c="undefined"===typeof c?!x(d.visible,a.visible):c;d.options.data[d.data.indexOf(a)]=a.options;a.graphic&&a.graphic.attr({visibility:c?"visible":"hidden"})});a.apply(this,Array.prototype.slice.call(arguments,1))});F(a,"afterInit",function(){if(this.chart.is3d()){let f=
this.options;var a=f.grouping,c=f.stacking;let g=this.yAxis.options.reversedStacks;var d=0;if("undefined"===typeof a||a){a=u(this.chart,c);d=f.stack||0;for(c=0;c<a[d].series.length&&a[d].series[c]!==this;c++);d=10*(a.totalStacks-a[d].position)+(g?c:-c);this.xAxis.reversed||(d=10*a.totalStacks-d)}f.depth=f.depth||25;this.z=this.z||0;f.zIndex=d}});H(d,"pointAttribs",L);H(d,"setState",f);H(d.pointClass.prototype,"hasNewShapeType",c);J.seriesTypes.columnRange&&(r=J.seriesTypes.columnrange.prototype,H(r,
"pointAttribs",L),H(r,"setState",f),H(r.pointClass.prototype,"hasNewShapeType",c),r.plotGroup=d.plotGroup,r.setVisible=d.setVisible);H(y.prototype,"alignDataLabel",function(a,c,d,f,g){const k=this.chart;f.outside3dPlot=c.outside3dPlot;if(k.is3d()&&this.is("column")){var m=this.options;const a=x(f.inside,!!this.options.stacking),d=k.options.chart.options3d,b=c.pointWidth/2||0;m={x:g.x+b,y:g.y,z:this.z+m.depth/2};k.inverted&&(a&&(g.width=0,m.x+=c.shapeArgs.height/2),90<=d.alpha&&270>=d.alpha&&(m.y+=
c.shapeArgs.width));m=l([m],k,!0,!1)[0];g.x=m.x-b;g.y=c.outside3dPlot?-9E9:m.y}a.apply(this,[].slice.call(arguments,1))});H(g.prototype,"getStackBox",function(a,c){const d=a.apply(this,[].slice.call(arguments,1)),f=this.axis.chart,{width:g}=c;if(f.is3d()&&this.base){var k=+this.base.split(",")[0],m=f.series[k];k=f.options.chart.options3d;m&&m instanceof J.seriesTypes.column&&(m={x:d.x+(f.inverted?d.height:g/2),y:d.y,z:m.options.depth/2},f.inverted&&(d.width=0,90<=k.alpha&&270>=k.alpha&&(m.y+=g)),
m=l([m],f,!0,!1)[0],d.x=m.x-g/2,d.y=m.y)}return d});"";return a});F(a,"Series/Pie3D/Pie3DPoint.js",[a["Core/Series/SeriesRegistry.js"]],function(a){({seriesTypes:{pie:{prototype:{pointClass:a}}}}=a);const u=a.prototype.haloPath;class r extends a{constructor(){super(...arguments);this.series=void 0}haloPath(){var a;return(null===(a=this.series)||void 0===a?0:a.chart.is3d())?[]:u.apply(this,arguments)}}return r});F(a,"Series/Pie3D/Pie3DSeries.js",[a["Core/Globals.js"],a["Series/Pie3D/Pie3DPoint.js"],
a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,y,r,J){const {deg2rad:g}=a;({seriesTypes:{pie:a}}=r);const {extend:u,pick:E}=J;class F extends a{addPoint(){super.addPoint.apply(this,arguments);this.chart.is3d()&&this.update(this.userOptions,!0)}animate(a){if(this.chart.is3d()){let d=this.options.animation;var c=this.center;let f=this.group,g=this.markerGroup;!0===d&&(d={});a?(f.oldtranslateX=E(f.oldtranslateX,f.translateX),f.oldtranslateY=E(f.oldtranslateY,f.translateY),c={translateX:c[0],
translateY:c[1],scaleX:.001,scaleY:.001},f.attr(c),g&&(g.attrSetters=f.attrSetters,g.attr(c))):(c={translateX:f.oldtranslateX,translateY:f.oldtranslateY,scaleX:1,scaleY:1},f.animate(c,d),g&&g.animate(c,d))}else super.animate.apply(this,arguments)}drawDataLabels(){if(this.chart.is3d()){const a=this.chart.options.chart.options3d;this.data.forEach(function(c){const d=c.shapeArgs,f=d.r,u=(d.start+d.end)/2;c=c.labelPosition;const q=c.connectorPosition,r=-f*(1-Math.cos((d.alpha||a.alpha)*g))*Math.sin(u),
y=f*(Math.cos((d.beta||a.beta)*g)-1)*Math.cos(u);[c.natural,q.breakAt,q.touchingSliceAt].forEach(function(a){a.x+=y;a.y+=r})})}super.drawDataLabels.apply(this,arguments)}pointAttribs(a){const c=super.pointAttribs.apply(this,arguments),d=this.options;this.chart.is3d()&&!this.chart.styledMode&&(c.stroke=d.edgeColor||a.color||this.color,c["stroke-width"]=E(d.edgeWidth,1));return c}translate(){super.translate.apply(this,arguments);if(this.chart.is3d()){var a=this,c=a.options,d=c.depth||0,l=a.chart.options.chart.options3d,
u=l.alpha,q=l.beta,r=c.stacking?(c.stack||0)*d:a._i*d;r+=d/2;!1!==c.grouping&&(r=0);a.data.forEach(function(f){var k=f.shapeArgs;f.shapeType="arc3d";k.z=r;k.depth=.75*d;k.alpha=u;k.beta=q;k.center=a.center;k=(k.end+k.start)/2;f.slicedTranslation={translateX:Math.round(Math.cos(k)*c.slicedOffset*Math.cos(u*g)),translateY:Math.round(Math.sin(k)*c.slicedOffset*Math.cos(u*g))}})}}drawTracker(){super.drawTracker.apply(this,arguments);this.chart.is3d()&&this.points.forEach(function(a){a.graphic&&["out",
"inn","side1","side2"].forEach(c=>{a.graphic&&(a.graphic[c].element.point=a)})})}}u(F.prototype,{pointClass:y});"";return F});F(a,"Series/Pie3D/Pie3DComposition.js",[a["Series/Pie3D/Pie3DPoint.js"],a["Series/Pie3D/Pie3DSeries.js"],a["Core/Series/SeriesRegistry.js"]],function(a,y,r){r.seriesTypes.pie.prototype.pointClass.prototype.haloPath=a.prototype.haloPath;r.seriesTypes.pie=y});F(a,"Series/Scatter3D/Scatter3DPoint.js",[a["Series/Scatter/ScatterSeries.js"],a["Core/Utilities.js"]],function(a,y){const {defined:u}=
y;class F extends a.prototype.pointClass{constructor(){super(...arguments);this.series=this.options=void 0}applyOptions(){super.applyOptions.apply(this,arguments);u(this.z)||(this.z=0);return this}}return F});F(a,"Series/Scatter3D/Scatter3DSeries.js",[a["Core/Math3D.js"],a["Series/Scatter3D/Scatter3DPoint.js"],a["Series/Scatter/ScatterSeries.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,y,r,F,g){const {pointCameraDistance:u}=a,{extend:E,merge:J}=g;class f extends r{constructor(){super(...arguments);
this.points=this.options=this.data=void 0}pointAttribs(a){const c=super.pointAttribs.apply(this,arguments);this.chart.is3d()&&a&&(c.zIndex=u(a,this.chart));return c}}f.defaultOptions=J(r.defaultOptions,{tooltip:{pointFormat:"x: <b>{point.x}</b><br/>y: <b>{point.y}</b><br/>z: <b>{point.z}</b><br/>"}});E(f.prototype,{axisTypes:["xAxis","yAxis","zAxis"],directTouch:!0,parallelArrays:["x","y","z"],pointArrayMap:["x","y","z"],pointClass:y});F.registerSeriesType("scatter3d",f);"";return f});F(a,"masters/highcharts-3d.src.js",
[a["Core/Globals.js"],a["Core/Renderer/SVG/SVGRenderer3D.js"],a["Core/Chart/Chart3D.js"],a["Core/Axis/ZAxis.js"],a["Core/Axis/Axis3DComposition.js"],a["Series/Area3D/Area3DSeries.js"]],function(a,y,r,F,g,K){y.compose(a.SVGRenderer);r.compose(a.Chart,a.Fx);F.compose(a.Chart);g.compose(a.Axis,a.Tick);K.compose(a.seriesTypes.area)})});//# sourceMappingURL=highcharts-3d.js.map