/*
 Highcharts JS v11.1.0 (2023-08-20)

 (c) 2009-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/highcharts-more",["highcharts"],function(r){b(r);b.Highcharts=r;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function r(a,d,e,b){a.hasOwnProperty(d)||(a[d]=b.apply(null,e),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:d,module:a[d]}})))}b=b?b._modules:
{};r(b,"Extensions/Pane.js",[b["Core/Chart/Chart.js"],b["Series/CenteredUtilities.js"],b["Core/Globals.js"],b["Core/Pointer.js"],b["Core/Utilities.js"]],function(a,d,e,b,f){function k(c,l,g,A,d){let I=!0;const a=g[0],z=g[1],H=Math.sqrt(Math.pow(c-a,2)+Math.pow(l-z,2));E(A)&&E(d)&&(c=Math.atan2(t(l-z,8),t(c-a,8)),d!==A&&(I=A>d?c>=A&&c<=Math.PI||c<=d&&c>=-Math.PI:c>=A&&c<=t(d,8)));return H<=Math.ceil(g[2]/2)&&I}const {addEvent:h,correctFloat:t,defined:E,extend:x,merge:v,pick:n,splat:B}=f;a.prototype.collectionsWithUpdate.push("pane");
class g{constructor(c,l){this.options=this.chart=this.center=this.background=void 0;this.coll="pane";this.defaultOptions={center:["50%","50%"],size:"85%",innerSize:"0%",startAngle:0};this.defaultBackgroundOptions={shape:"circle",borderWidth:1,borderColor:"#cccccc",backgroundColor:{linearGradient:{x1:0,y1:0,x2:0,y2:1},stops:[[0,"#ffffff"],[1,"#e6e6e6"]]},from:-Number.MAX_VALUE,innerRadius:0,to:Number.MAX_VALUE,outerRadius:"105%"};this.init(c,l)}init(c,l){this.chart=l;this.background=[];l.pane.push(this);
this.setOptions(c)}setOptions(c){this.options=v(this.defaultOptions,this.chart.angular?{background:{}}:void 0,c)}render(){var c=this.options;let l=this.options.background;var g=this.chart.renderer;this.group||(this.group=g.g("pane-group").attr({zIndex:c.zIndex||0}).add());this.updateCenter();if(l)for(l=B(l),c=Math.max(l.length,this.background.length||0),g=0;g<c;g++)l[g]&&this.axis?this.renderBackground(v(this.defaultBackgroundOptions,l[g]),g):this.background[g]&&(this.background[g]=this.background[g].destroy(),
this.background.splice(g,1))}renderBackground(c,l){let g="animate",A={"class":"highcharts-pane "+(c.className||"")};this.chart.styledMode||x(A,{fill:c.backgroundColor,stroke:c.borderColor,"stroke-width":c.borderWidth});this.background[l]||(this.background[l]=this.chart.renderer.path().add(this.group),g="attr");this.background[l][g]({d:this.axis.getPlotBandPath(c.from,c.to,c)}).attr(A)}updateCenter(c){this.center=(c||this.axis||{}).center=d.getCenter.call(this)}update(c,l){v(!0,this.options,c);this.setOptions(this.options);
this.render();this.chart.axes.forEach(function(c){c.pane===this&&(c.pane=null,c.update({},l))},this)}}a.prototype.getHoverPane=function(c){const l=this;let g;c&&l.pane.forEach(A=>{k(c.chartX-l.plotLeft,c.chartY-l.plotTop,A.center)&&(g=A)});return g};h(a,"afterIsInsidePlot",function(c){this.polar&&(c.options.inverted&&([c.x,c.y]=[c.y,c.x]),c.isInsidePlot=this.pane.some(l=>k(c.x,c.y,l.center,l.axis&&l.axis.normalizedStartAngleRad,l.axis&&l.axis.normalizedEndAngleRad)))});h(b,"beforeGetHoverData",function(c){const l=
this.chart;l.polar?(l.hoverPane=l.getHoverPane(c),c.filter=function(g){return g.visible&&!(!c.shared&&g.directTouch)&&n(g.options.enableMouseTracking,!0)&&(!l.hoverPane||g.xAxis.pane===l.hoverPane)}):l.hoverPane=void 0});h(b,"afterGetHoverData",function(c){const l=this.chart;c.hoverPoint&&c.hoverPoint.plotX&&c.hoverPoint.plotY&&l.hoverPane&&!k(c.hoverPoint.plotX,c.hoverPoint.plotY,l.hoverPane.center)&&(c.hoverPoint=void 0)});e.Pane=g;return e.Pane});r(b,"Series/AreaRange/AreaRangePoint.js",[b["Core/Series/SeriesRegistry.js"],
b["Core/Utilities.js"]],function(a,d){const {area:{prototype:{pointClass:e,pointClass:{prototype:b}}}}=a.seriesTypes,{defined:f,isNumber:k}=d;class q extends e{constructor(){super(...arguments);this.series=this.plotX=this.options=this.low=this.high=void 0}setState(){const d=this.state,a=this.series,e=a.chart.polar;f(this.plotHigh)||(this.plotHigh=a.yAxis.toPixels(this.high,!0));f(this.plotLow)||(this.plotLow=this.plotY=a.yAxis.toPixels(this.low,!0));a.stateMarkerGraphic&&(a.lowerStateMarkerGraphic=
a.stateMarkerGraphic,a.stateMarkerGraphic=a.upperStateMarkerGraphic);this.graphic=this.graphics&&this.graphics[1];this.plotY=this.plotHigh;e&&k(this.plotHighX)&&(this.plotX=this.plotHighX);b.setState.apply(this,arguments);this.state=d;this.plotY=this.plotLow;this.graphic=this.graphics&&this.graphics[0];e&&k(this.plotLowX)&&(this.plotX=this.plotLowX);a.stateMarkerGraphic&&(a.upperStateMarkerGraphic=a.stateMarkerGraphic,a.stateMarkerGraphic=a.lowerStateMarkerGraphic,a.lowerStateMarkerGraphic=void 0);
b.setState.apply(this,arguments)}haloPath(){const a=this.series.chart.polar;let d=[];this.plotY=this.plotLow;a&&k(this.plotLowX)&&(this.plotX=this.plotLowX);this.isInside&&(d=b.haloPath.apply(this,arguments));this.plotY=this.plotHigh;a&&k(this.plotHighX)&&(this.plotX=this.plotHighX);this.isTopInside&&(d=d.concat(b.haloPath.apply(this,arguments)));return d}isValid(){return k(this.low)&&k(this.high)}}return q});r(b,"Series/AreaRange/AreaRangeSeries.js",[b["Series/AreaRange/AreaRangePoint.js"],b["Core/Globals.js"],
b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(a,d,b,h){({noop:d}=d);const {area:e,area:{prototype:k},column:{prototype:q}}=b.seriesTypes,{addEvent:t,defined:E,extend:x,isArray:v,isNumber:n,pick:B,merge:g}=h;class c extends e{constructor(){super(...arguments);this.xAxis=this.lowerStateMarkerGraphic=this.points=this.options=this.data=void 0}toYData(c){return[c.low,c.high]}highToXY(c){const l=this.chart,g=this.xAxis.postTranslate(c.rectPlotX||0,this.yAxis.len-(c.plotHigh||0));c.plotHighX=
g.x-l.plotLeft;c.plotHigh=g.y-l.plotTop;c.plotLowX=c.plotX}getGraphPath(c){var g=[],l=[];const a=k.getGraphPath;var d=this.options;const b=this.chart.polar,z=b&&!1!==d.connectEnds,e=d.connectNulls;let f,h,p,m=d.step;c=c||this.points;for(f=c.length;f--;){h=c[f];const d=b?{plotX:h.rectPlotX,plotY:h.yBottom,doCurve:!1}:{plotX:h.plotX,plotY:h.plotY,doCurve:!1};h.isNull||z||e||c[f+1]&&!c[f+1].isNull||l.push(d);p={polarPlotY:h.polarPlotY,rectPlotX:h.rectPlotX,yBottom:h.yBottom,plotX:B(h.plotHighX,h.plotX),
plotY:h.plotHigh,isNull:h.isNull};l.push(p);g.push(p);h.isNull||z||e||c[f-1]&&!c[f-1].isNull||l.push(d)}c=a.call(this,c);m&&(!0===m&&(m="left"),d.step={left:"right",center:"center",right:"left"}[m]);g=a.call(this,g);l=a.call(this,l);d.step=m;d=[].concat(c,g);!this.chart.polar&&l[0]&&"M"===l[0][0]&&(l[0]=["L",l[0][1],l[0][2]]);this.graphPath=d;this.areaPath=c.concat(l);d.isArea=!0;d.xMap=c.xMap;this.areaPath.xMap=c.xMap;return d}drawDataLabels(){const c=this.points,g=c.length,d=[],a=this.options.dataLabels,
b=this.chart.inverted;let e,z,f,h,n;if(a){v(a)?(h=a[0]||{enabled:!1},n=a[1]||{enabled:!1}):(h=x({},a),h.x=a.xHigh,h.y=a.yHigh,n=x({},a),n.x=a.xLow,n.y=a.yLow);if(h.enabled||this._hasPointLabels){for(e=g;e--;)if(z=c[e]){const {plotHigh:c=0,plotLow:g=0}=z;f=h.inside?c<g:c>g;z.y=z.high;z._plotY=z.plotY;z.plotY=c;d[e]=z.dataLabel;z.dataLabel=z.dataLabelUpper;z.below=f;b?h.align||(h.align=f?"right":"left"):h.verticalAlign||(h.verticalAlign=f?"top":"bottom")}this.options.dataLabels=h;k.drawDataLabels&&
k.drawDataLabels.apply(this,arguments);for(e=g;e--;)if(z=c[e])z.dataLabelUpper=z.dataLabel,z.dataLabel=d[e],delete z.dataLabels,z.y=z.low,z.plotY=z._plotY}if(n.enabled||this._hasPointLabels){for(e=g;e--;)if(z=c[e]){const {plotHigh:c=0,plotLow:g=0}=z;f=n.inside?c<g:c>g;z.below=!f;b?n.align||(n.align=f?"left":"right"):n.verticalAlign||(n.verticalAlign=f?"bottom":"top")}this.options.dataLabels=n;k.drawDataLabels&&k.drawDataLabels.apply(this,arguments)}if(h.enabled)for(e=g;e--;)if(z=c[e])z.dataLabels=
[z.dataLabelUpper,z.dataLabel].filter(function(c){return!!c});this.options.dataLabels=a}}alignDataLabel(){q.alignDataLabel.apply(this,arguments)}drawPoints(){const c=this.points.length;let g,a;k.drawPoints.apply(this,arguments);for(g=0;g<c;){a=this.points[g];a.graphics=a.graphics||[];a.origProps={plotY:a.plotY,plotX:a.plotX,isInside:a.isInside,negative:a.negative,zone:a.zone,y:a.y};if(a.graphic||a.graphics[0])a.graphics[0]=a.graphic;a.graphic=a.graphics[1];a.plotY=a.plotHigh;E(a.plotHighX)&&(a.plotX=
a.plotHighX);a.y=B(a.high,a.origProps.y);a.negative=a.y<(this.options.threshold||0);this.zones.length&&(a.zone=a.getZone());this.chart.polar||(a.isInside=a.isTopInside="undefined"!==typeof a.plotY&&0<=a.plotY&&a.plotY<=this.yAxis.len&&0<=a.plotX&&a.plotX<=this.xAxis.len);g++}k.drawPoints.apply(this,arguments);for(g=0;g<c;){a=this.points[g];a.graphics=a.graphics||[];if(a.graphic||a.graphics[1])a.graphics[1]=a.graphic;a.graphic=a.graphics[0];a.origProps&&(x(a,a.origProps),delete a.origProps);g++}}}
c.defaultOptions=g(e.defaultOptions,{lineWidth:1,threshold:null,tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},trackByArea:!0,dataLabels:{align:void 0,verticalAlign:void 0,xLow:0,xHigh:0,yLow:0,yHigh:0}});t(c,"afterTranslate",function(){"low,high"===this.pointArrayMap.join(",")&&this.points.forEach(c=>{const g=c.high,a=c.plotY;c.isNull?c.plotY=void 0:(c.plotLow=a,c.plotHigh=n(g)?this.yAxis.translate(this.dataModify?
this.dataModify.modifyValue(g):g,!1,!0,void 0,!0):void 0,this.dataModify&&(c.yBottom=c.plotHigh))})},{order:0});t(c,"afterTranslate",function(){this.points.forEach(c=>{if(this.chart.polar)this.highToXY(c),c.plotLow=c.plotY,c.tooltipPos=[((c.plotHighX||0)+(c.plotLowX||0))/2,((c.plotHigh||0)+(c.plotLow||0))/2];else{const g=c.pos(!1,c.plotLow),a=c.pos(!1,c.plotHigh);g&&a&&(g[0]=(g[0]+a[0])/2,g[1]=(g[1]+a[1])/2);c.tooltipPos=g}})},{order:3});x(c.prototype,{deferTranslatePolar:!0,pointArrayMap:["low",
"high"],pointClass:a,pointValKey:"low",setStackedPoints:d});b.registerSeriesType("arearange",c);"";return c});r(b,"Series/AreaSplineRange/AreaSplineRangeSeries.js",[b["Series/AreaRange/AreaRangeSeries.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(a,d,e){const {spline:{prototype:b}}=d.seriesTypes,{merge:f,extend:k}=e;class q extends a{constructor(){super(...arguments);this.points=this.data=this.options=void 0}}q.defaultOptions=f(a.defaultOptions);k(q.prototype,{getPointSpline:b.getPointSpline});
d.registerSeriesType("areasplinerange",q);"";return q});r(b,"Series/BoxPlot/BoxPlotSeries.js",[b["Series/Column/ColumnSeries.js"],b["Core/Globals.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(a,d,e,b){({noop:d}=d);const {extend:f,merge:h,pick:q}=b;class t extends a{constructor(){super(...arguments);this.points=this.options=this.data=void 0}pointAttribs(){return{}}translate(){const a=this.yAxis,d=this.pointArrayMap;super.translate.apply(this);this.points.forEach(function(e){d.forEach(function(d){null!==
e[d]&&(e[d+"Plot"]=a.translate(e[d],0,1,0,1))});e.plotHigh=e.highPlot})}drawPoints(){let a=this,d=a.options,e=a.chart,b=e.renderer,f,g,c,l,I,h,H=0,k,w,z,P,M=!1!==a.doQuartiles,N,p=a.options.whiskerLength;a.points.forEach(function(m){var D=m.graphic;let J=D?"animate":"attr",u=m.shapeArgs,F={},A={},n={},Q={},v=m.color||a.color;"undefined"!==typeof m.plotY&&(k=Math.round(u.width),w=Math.floor(u.x),z=w+k,P=Math.round(k/2),f=Math.floor(M?m.q1Plot:m.lowPlot),g=Math.floor(M?m.q3Plot:m.lowPlot),c=Math.floor(m.highPlot),
l=Math.floor(m.lowPlot),D||(m.graphic=D=b.g("point").add(a.group),m.stem=b.path().addClass("highcharts-boxplot-stem").add(D),p&&(m.whiskers=b.path().addClass("highcharts-boxplot-whisker").add(D)),M&&(m.box=b.path(void 0).addClass("highcharts-boxplot-box").add(D)),m.medianShape=b.path(void 0).addClass("highcharts-boxplot-median").add(D)),e.styledMode||(A.stroke=m.stemColor||d.stemColor||v,A["stroke-width"]=q(m.stemWidth,d.stemWidth,d.lineWidth),A.dashstyle=m.stemDashStyle||d.stemDashStyle||d.dashStyle,
m.stem.attr(A),p&&(n.stroke=m.whiskerColor||d.whiskerColor||v,n["stroke-width"]=q(m.whiskerWidth,d.whiskerWidth,d.lineWidth),n.dashstyle=m.whiskerDashStyle||d.whiskerDashStyle||d.dashStyle,m.whiskers.attr(n)),M&&(F.fill=m.fillColor||d.fillColor||v,F.stroke=d.lineColor||v,F["stroke-width"]=d.lineWidth||0,F.dashstyle=m.boxDashStyle||d.boxDashStyle||d.dashStyle,m.box.attr(F)),Q.stroke=m.medianColor||d.medianColor||v,Q["stroke-width"]=q(m.medianWidth,d.medianWidth,d.lineWidth),Q.dashstyle=m.medianDashStyle||
d.medianDashStyle||d.dashStyle,m.medianShape.attr(Q)),h=m.stem.strokeWidth()%2/2,H=w+P+h,D=[["M",H,g],["L",H,c],["M",H,f],["L",H,l]],m.stem[J]({d:D}),M&&(h=m.box.strokeWidth()%2/2,f=Math.floor(f)+h,g=Math.floor(g)+h,w+=h,z+=h,D=[["M",w,g],["L",w,f],["L",z,f],["L",z,g],["L",w,g],["Z"]],m.box[J]({d:D})),p&&(h=m.whiskers.strokeWidth()%2/2,c+=h,l+=h,N=/%$/.test(p)?P*parseFloat(p)/100:p/2,D=[["M",H-N,c],["L",H+N,c],["M",H-N,l],["L",H+N,l]],m.whiskers[J]({d:D})),I=Math.round(m.medianPlot),h=m.medianShape.strokeWidth()%
2/2,I+=h,D=[["M",w,I],["L",z,I]],m.medianShape[J]({d:D}))})}toYData(a){return[a.low,a.q1,a.median,a.q3,a.high]}}t.defaultOptions=h(a.defaultOptions,{threshold:null,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b>{series.name}</b><br/>Maximum: {point.high}<br/>Upper quartile: {point.q3}<br/>Median: {point.median}<br/>Lower quartile: {point.q1}<br/>Minimum: {point.low}<br/>'},whiskerLength:"50%",fillColor:"#ffffff",lineWidth:1,medianWidth:2,whiskerWidth:2});f(t.prototype,{pointArrayMap:["low",
"q1","median","q3","high"],pointValKey:"high",drawDataLabels:d,setStackedPoints:d});e.registerSeriesType("boxplot",t);"";return t});r(b,"Series/Bubble/BubbleLegendDefaults.js",[],function(){return{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:"0.9em",color:"#000000"},x:0,y:0},maxSize:60,minSize:10,
legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}});r(b,"Series/Bubble/BubbleLegendItem.js",[b["Core/Color/Color.js"],b["Core/Templating.js"],b["Core/Globals.js"],b["Core/Utilities.js"]],function(a,d,e,b){const {parse:f}=a,{noop:h}=e,{arrayMax:q,arrayMin:t,isNumber:E,merge:x,pick:v,stableSort:n}=b;class B{constructor(a,c){this.options=this.symbols=this.visible=this.selected=this.ranges=this.movementX=
this.maxLabel=this.legend=this.chart=void 0;this.setState=h;this.init(a,c)}init(a,c){this.options=a;this.visible=!0;this.chart=c.chart;this.legend=c}addToLegend(a){a.splice(this.options.legendIndex,0,this)}drawLegendSymbol(a){const c=v(a.options.itemDistance,20),g=this.legendItem||{},d=this.options;var e=d.ranges,b=d.connectorDistance;if(e&&e.length&&E(e[0].value)){n(e,function(c,a){return a.value-c.value});this.ranges=e;this.setOptions();this.render();a=this.getMaxLabelSize();var f=this.ranges[0].radius;
e=2*f;b=b-f+a.width;b=0<b?b:0;this.maxLabel=a;this.movementX="left"===d.labels.align?b:0;g.labelWidth=e+b+c;g.labelHeight=e+a.height/2}else a.options.bubbleLegend.autoRanges=!0}setOptions(){const a=this.ranges,c=this.options,d=this.chart.series[c.seriesIndex],e=this.legend.baseline,b={zIndex:c.zIndex,"stroke-width":c.borderWidth},h={zIndex:c.zIndex,"stroke-width":c.connectorWidth},k={align:this.legend.options.rtl||"left"===c.labels.align?"right":"left",zIndex:c.zIndex},w=d.options.marker.fillOpacity,
z=this.chart.styledMode;a.forEach(function(g,l){z||(b.stroke=v(g.borderColor,c.borderColor,d.color),b.fill=v(g.color,c.color,1!==w?f(d.color).setOpacity(w).get("rgba"):d.color),h.stroke=v(g.connectorColor,c.connectorColor,d.color));a[l].radius=this.getRangeRadius(g.value);a[l]=x(a[l],{center:a[0].radius-a[l].radius+e});z||x(!0,a[l],{bubbleAttribs:x(b),connectorAttribs:x(h),labelAttribs:k})},this)}getRangeRadius(a){const c=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,
c.ranges[c.ranges.length-1].value,c.ranges[0].value,c.minSize,c.maxSize,a)}render(){const a=this.legendItem||{},c=this.chart.renderer,d=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});a.symbol=c.g("bubble-legend");a.label=c.g("bubble-legend-item").css(this.legend.itemStyle||{});a.symbol.translateX=0;a.symbol.translateY=0;a.symbol.add(a.label);a.label.add(a.group);for(const c of this.ranges)c.value>=d&&this.renderRange(c);this.hideOverlappingLabels()}renderRange(a){var c=
this.options;const d=c.labels;var g=this.chart;const e=g.series[c.seriesIndex],b=g.renderer,f=this.symbols;g=f.labels;const h=a.center,z=Math.abs(a.radius);var k=c.connectorDistance||0;const n=d.align,v=c.connectorWidth,p=this.ranges[0].radius||0,m=h-z-c.borderWidth/2+v/2,D=b.styledMode;k=this.legend.options.rtl||"left"===n?-k:k;"center"===n&&(k=0,c.connectorDistance=0,a.labelAttribs.align="center");f.bubbleItems.push(b.circle(p,h+((m%1?1:.5)-(v%2?0:.5)),z).attr(D?{}:a.bubbleAttribs).addClass((D?
"highcharts-color-"+e.colorIndex+" ":"")+"highcharts-bubble-legend-symbol "+(c.className||"")).add(this.legendItem.symbol));f.connectors.push(b.path(b.crispLine([["M",p,m],["L",p+k,m]],c.connectorWidth)).attr(D?{}:a.connectorAttribs).addClass((D?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(c.connectorClassName||"")).add(this.legendItem.symbol));a=b.text(this.formatLabel(a)).attr(D?{}:a.labelAttribs).css(D?{}:d.style).addClass("highcharts-bubble-legend-labels "+
(c.labels.className||"")).add(this.legendItem.symbol);c={x:p+k+c.labels.x,y:m+c.labels.y+.4*a.getBBox().height};a.attr(c);g.push(a);a.placed=!0;a.alignAttr=c}getMaxLabelSize(){let a,c;this.symbols.labels.forEach(function(d){c=d.getBBox(!0);a=a?c.width>a.width?c:a:c});return a||{}}formatLabel(a){var c=this.options;const g=c.labels.formatter;c=c.labels.format;const {numberFormatter:b}=this.chart;return c?d.format(c,a):g?g.call(a):b(a.value,1)}hideOverlappingLabels(){const a=this.chart,c=this.symbols;
!this.options.labels.allowOverlap&&c&&(a.hideOverlappingLabels(c.labels),c.labels.forEach(function(a,d){a.newOpacity?a.newOpacity!==a.oldOpacity&&c.connectors[d].show():c.connectors[d].hide()}))}getRanges(){const a=this.legend.bubbleLegend,c=a.options.ranges;let d,b,e=Number.MAX_VALUE,f=-Number.MAX_VALUE;a.chart.series.forEach(function(c){c.isBubble&&!c.ignoreSeries&&(b=c.zData.filter(E),b.length&&(e=v(c.options.zMin,Math.min(e,Math.max(t(b),!1===c.options.displayNegative?c.options.zThreshold:-Number.MAX_VALUE))),
f=v(c.options.zMax,Math.max(f,q(b)))))});d=e===f?[{value:f}]:[{value:e},{value:(e+f)/2},{value:f,autoRanges:!0}];c.length&&c[0].radius&&d.reverse();d.forEach(function(a,g){c&&c[g]&&(d[g]=x(c[g],a))});return d}predictBubbleSizes(){var a=this.chart,c=a.legend.options,d=c.floating;const b=(c="horizontal"===c.layout)?a.legend.lastLineHeight:0,e=a.plotSizeX,f=a.plotSizeY;var h=a.series[this.options.seriesIndex],k=h.getPxExtremes();a=Math.ceil(k.minPxSize);k=Math.ceil(k.maxPxSize);const z=Math.min(f,e);
h=h.options.maxSize;if(d||!/%$/.test(h))d=k;else if(h=parseFloat(h),d=(z+b)*h/100/(h/100+1),c&&f-d>=e||!c&&e-d>=f)d=k;return[a,Math.ceil(d)]}updateRanges(a,c){const d=this.legend.options.bubbleLegend;d.minSize=a;d.maxSize=c;d.ranges=this.getRanges()}correctSizes(){const a=this.legend,c=this.chart.series[this.options.seriesIndex].getPxExtremes();1<Math.abs(Math.ceil(c.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,c.maxPxSize),a.render())}}"";return B});r(b,"Series/Bubble/BubbleLegendComposition.js",
[b["Series/Bubble/BubbleLegendDefaults.js"],b["Series/Bubble/BubbleLegendItem.js"],b["Core/Defaults.js"],b["Core/Utilities.js"]],function(a,d,e,b){function f(c,a,d){const g=this.legend;var b=0<=h(this);let e,f;g&&g.options.enabled&&g.bubbleLegend&&g.options.bubbleLegend.autoRanges&&b?(e=g.bubbleLegend.options,b=g.bubbleLegend.predictBubbleSizes(),g.bubbleLegend.updateRanges(b[0],b[1]),e.placed||(g.group.placed=!1,g.allItems.forEach(c=>{f=c.legendItem||{};f.group&&(f.group.translateY=null)})),g.render(),
this.getMargins(),this.axes.forEach(function(c){c.visible&&c.render();e.placed||(c.setScale(),c.updateNames(),B(c.ticks,function(c){c.isNew=!0;c.isNewLabel=!0}))}),e.placed=!0,this.getMargins(),c.call(this,a,d),g.bubbleLegend.correctSizes(),x(g,q(g))):(c.call(this,a,d),g&&g.options.enabled&&g.bubbleLegend&&(g.render(),x(g,q(g))))}function h(c){c=c.series;let a=0;for(;a<c.length;){if(c[a]&&c[a].isBubble&&c[a].visible&&c[a].zData.length)return a;a++}return-1}function q(c){c=c.allItems;const a=[],d=
c.length;let g,b,e=0;for(b=0;b<d;b++){var f=c[b].legendItem||{};g=(c[b+1]||{}).legendItem||{};f.labelHeight&&(c[b].itemHeight=f.labelHeight);if(c[b]===c[d-1]||f.y!==g.y){a.push({height:0});f=a[a.length-1];for(e;e<=b;e++)c[e].itemHeight>f.height&&(f.height=c[e].itemHeight);f.step=b}}return a}function t(c){const a=this.bubbleLegend,g=this.options,b=g.bubbleLegend,e=h(this.chart);a&&a.ranges&&a.ranges.length&&(b.ranges.length&&(b.autoRanges=!!b.ranges[0].autoRanges),this.destroyItem(a));0<=e&&g.enabled&&
b.enabled&&(b.seriesIndex=e,this.bubbleLegend=new d(b,this),this.bubbleLegend.addToLegend(c.allItems))}function E(c){if(c.defaultPrevented)return!1;var a=this.chart;c=this.visible;const d=this.chart.legend;d&&d.bubbleLegend&&(this.visible=!c,this.ignoreSeries=c,a=0<=h(a),d.bubbleLegend.visible!==a&&(d.update({bubbleLegend:{enabled:a}}),d.bubbleLegend.visible=a),this.visible=c)}function x(c,a){const d=c.options.rtl;let g,b,e,f,h=0;c.allItems.forEach((c,l)=>{f=c.legendItem||{};if(f.group){g=f.group.translateX||
0;b=f.y||0;if((e=c.movementX)||d&&c.ranges)e=d?g-c.options.maxSize/2:g+e,f.group.attr({translateX:e});l>a[h].step&&h++;f.group.attr({translateY:Math.round(b+a[h].height/2)});f.y=b+a[h].height/2}})}const {setOptions:v}=e,{addEvent:n,objectEach:B,wrap:g}=b,c=[];return{compose:function(d,e,h){b.pushUnique(c,d)&&(v({legend:{bubbleLegend:a}}),g(d.prototype,"drawChartBox",f));b.pushUnique(c,e)&&n(e,"afterGetAllItems",t);b.pushUnique(c,h)&&n(h,"legendItemClick",E)}}});r(b,"Series/Bubble/BubblePoint.js",
[b["Core/Series/Point.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(a,d,b){({seriesTypes:{scatter:{prototype:{pointClass:d}}}}=d);({extend:b}=b);class e extends d{constructor(){super(...arguments);this.series=this.options=void 0}haloPath(d){return a.prototype.haloPath.call(this,0===d?0:(this.marker?this.marker.radius||0:0)+d)}}b(e.prototype,{ttBelow:!1});return e});r(b,"Series/Bubble/BubbleSeries.js",[b["Series/Bubble/BubbleLegendComposition.js"],b["Series/Bubble/BubblePoint.js"],
b["Core/Color/Color.js"],b["Core/Globals.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(a,d,b,h,f,k){function e(){const c=this.len,a=this.chart,d=this.isXAxis,g=d?"xData":"yData",b=this.min,e=this.max-b;let f=0,h=c,l=c/e,F;this.series.forEach(c=>{if(c.bubblePadding&&(c.visible||!a.options.chart.ignoreHiddenSeries)){F=this.allowZoomOutside=!0;const a=c[g];d&&((c.onPoint||c).getRadii(0,0,c),c.onPoint&&(c.radii=c.onPoint.radii));if(0<e){let d=a.length;for(;d--;)if(I(a[d])&&
this.dataMin<=a[d]&&a[d]<=this.max){const g=c.radii&&c.radii[d]||0;f=Math.min((a[d]-b)*l-g,f);h=Math.max((a[d]-b)*l+g,h)}}}});F&&0<e&&!this.logarithmic&&(h-=c,l*=(c+Math.max(0,f)-Math.min(h,c))/c,[["min","userMin",f],["max","userMax",h]].forEach(c=>{"undefined"===typeof H(this.options[c[0]],this[c[1]])&&(this[c[0]]+=c[2]/l)}))}const {parse:t}=b;({noop:b}=h);const {series:E,seriesTypes:{column:{prototype:x},scatter:v}}=f,{addEvent:n,arrayMax:B,arrayMin:g,clamp:c,extend:l,isNumber:I,merge:A,pick:H}=
k,Q=[];class w extends v{constructor(){super(...arguments);this.zData=this.yData=this.radii=this.points=this.options=this.minPxSize=this.maxPxSize=this.data=void 0}static compose(c,d,g,b){a.compose(d,g,b);k.pushUnique(Q,c)&&(c.prototype.beforePadding=e)}animate(c){!c&&this.points.length<this.options.animationLimit&&this.points.forEach(function(c){const {graphic:a}=c;a&&a.width&&(this.hasRendered||a.attr({x:c.plotX,y:c.plotY,width:1,height:1}),a.animate(this.markerAttribs(c),this.options.animation))},
this)}getRadii(){const c=this.zData,a=this.yData,d=[];let g,b,e,f=this.chart.bubbleZExtremes;const {minPxSize:h,maxPxSize:l}=this.getPxExtremes();if(!f){let c=Number.MAX_VALUE,a=-Number.MAX_VALUE,d;this.chart.series.forEach(g=>{g.bubblePadding&&(g.visible||!this.chart.options.chart.ignoreHiddenSeries)&&(g=(g.onPoint||g).getZExtremes())&&(c=Math.min(H(c,g.zMin),g.zMin),a=Math.max(H(a,g.zMax),g.zMax),d=!0)});d?(f={zMin:c,zMax:a},this.chart.bubbleZExtremes=f):f={zMin:0,zMax:0}}b=0;for(g=c.length;b<g;b++)e=
c[b],d.push(this.getRadius(f.zMin,f.zMax,h,l,e,a&&a[b]));this.radii=d}getRadius(c,a,d,g,b,e){const f=this.options,p="width"!==f.sizeBy,h=f.zThreshold;let m=a-c,l=.5;if(null===e||null===b)return null;if(I(b)){f.sizeByAbsoluteValue&&(b=Math.abs(b-h),m=Math.max(a-h,Math.abs(c-h)),c=0);if(b<c)return d/2-1;0<m&&(l=(b-c)/m)}p&&0<=l&&(l=Math.sqrt(l));return Math.ceil(d+l*(g-d))/2}hasData(){return!!this.processedXData.length}pointAttribs(c,a){const d=this.options.marker.fillOpacity;c=E.prototype.pointAttribs.call(this,
c,a);1!==d&&(c.fill=t(c.fill).setOpacity(d).get("rgba"));return c}translate(){super.translate.call(this);this.getRadii();this.translateBubble()}translateBubble(){const {data:c,options:a,radii:d}=this,{minPxSize:g}=this.getPxExtremes();let b=c.length;for(;b--;){const e=c[b],f=d?d[b]:0;"z"===this.zoneAxis&&(e.negative=(e.z||0)<(a.zThreshold||0));I(f)&&f>=g/2?(e.marker=l(e.marker,{radius:f,width:2*f,height:2*f}),e.dlBox={x:e.plotX-f,y:e.plotY-f,width:2*f,height:2*f}):(e.shapeArgs=e.plotY=e.dlBox=void 0,
e.isInside=!1)}}getPxExtremes(){const c=Math.min(this.chart.plotWidth,this.chart.plotHeight);var a=a=>{let d;"string"===typeof a&&(d=/%$/.test(a),a=parseInt(a,10));return d?c*a/100:a};const d=a(H(this.options.minSize,8));a=Math.max(a(H(this.options.maxSize,"20%")),d);return{minPxSize:d,maxPxSize:a}}getZExtremes(){var a=this.options;const d=(this.zData||[]).filter(I);if(d.length){const b=H(a.zMin,c(g(d),!1===a.displayNegative?a.zThreshold||0:-Number.MAX_VALUE,Number.MAX_VALUE));a=H(a.zMax,B(d));if(I(b)&&
I(a))return{zMin:b,zMax:a}}}}w.defaultOptions=A(v.defaultOptions,{dataLabels:{formatter:function(){const {numberFormatter:c}=this.series.chart,{z:a}=this.point;return I(a)?c(a,-1):""},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,
zoneAxis:"z"});l(w.prototype,{alignDataLabel:x.alignDataLabel,applyZones:b,bubblePadding:!0,buildKDTree:b,directTouch:!0,isBubble:!0,pointArrayMap:["y","z"],pointClass:d,parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",zoneAxis:"z"});n(w,"updatedData",c=>{delete c.target.chart.bubbleZExtremes});n(w,"remove",c=>{delete c.target.chart.bubbleZExtremes});f.registerSeriesType("bubble",w);"";"";return w});r(b,"Series/ColumnRange/ColumnRangePoint.js",[b["Core/Series/SeriesRegistry.js"],
b["Core/Utilities.js"]],function(a,d){const {seriesTypes:{column:{prototype:{pointClass:{prototype:b}}},arearange:{prototype:{pointClass:h}}}}=a,{extend:f,isNumber:k}=d;class q extends h{constructor(){super(...arguments);this.series=this.options=void 0}isValid(){return k(this.low)}}f(q.prototype,{setState:b.setState});return q});r(b,"Series/ColumnRange/ColumnRangeSeries.js",[b["Series/ColumnRange/ColumnRangePoint.js"],b["Core/Globals.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],
function(a,d,b,h){({noop:d}=d);const {seriesTypes:{arearange:e,column:k,column:{prototype:q}}}=b,{addEvent:t,clamp:E,extend:x,isNumber:v,merge:n,pick:B}=h;class g extends e{setOptions(){n(!0,arguments[0],{stacking:void 0});return e.prototype.setOptions.apply(this,arguments)}translate(){return q.translate.apply(this)}pointAttribs(){return q.pointAttribs.apply(this,arguments)}translate3dPoints(){return q.translate3dPoints.apply(this,arguments)}translate3dShapes(){return q.translate3dShapes.apply(this,
arguments)}afterColumnTranslate(){const c=this.yAxis,a=this.xAxis,d=a.startAngleRad,g=this.chart,b=this.xAxis.isRadial,e=Math.max(g.chartWidth,g.chartHeight)+999;let f,h,k,q;this.points.forEach(l=>{const p=l.shapeArgs||{},m=this.options.minPointLength,D=l.plotY,J=c.translate(l.high,0,1,0,1);if(v(J)&&v(D))if(l.plotHigh=E(J,-e,e),l.plotLow=E(D,-e,e),q=l.plotHigh,f=B(l.rectPlotY,l.plotY)-l.plotHigh,Math.abs(f)<m?(h=m-f,f+=h,q-=h/2):0>f&&(f*=-1,q-=f),b&&this.polar)k=l.barX+d,l.shapeType="arc",l.shapeArgs=
this.polar.arc(q+f,q,k,k+l.pointWidth);else{p.height=f;p.y=q;const {x:d=0,width:b=0}=p;l.shapeArgs=n(l.shapeArgs,this.crispCol(d,q,b,f));l.tooltipPos=g.inverted?[c.len+c.pos-g.plotLeft-q-f/2,a.len+a.pos-g.plotTop-d-b/2,f]:[a.left-g.plotLeft+d+b/2,c.pos-g.plotTop+q+f/2,f]}})}}g.defaultOptions=n(k.defaultOptions,e.defaultOptions,{borderRadius:{where:"all"},pointRange:null,marker:null,states:{hover:{halo:!1}}});t(g,"afterColumnTranslate",function(){g.prototype.afterColumnTranslate.apply(this)},{order:5});
x(g.prototype,{directTouch:!0,pointClass:a,trackerGroups:["group","dataLabelsGroup"],adjustForMissingColumns:q.adjustForMissingColumns,animate:q.animate,crispCol:q.crispCol,drawGraph:d,drawPoints:q.drawPoints,getSymbol:d,drawTracker:q.drawTracker,getColumnMetrics:q.getColumnMetrics});b.registerSeriesType("columnrange",g);"";return g});r(b,"Series/ColumnPyramid/ColumnPyramidSeries.js",[b["Series/Column/ColumnSeries.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(a,d,b){const {prototype:e}=
a,{clamp:f,merge:k,pick:q}=b;class t extends a{constructor(){super(...arguments);this.points=this.options=this.data=void 0}translate(){let a=this,d=a.chart,b=a.options;var h=a.dense=2>a.closestPointRange*a.xAxis.transA;h=a.borderWidth=q(b.borderWidth,h?0:1);let k=a.yAxis,g=b.threshold,c=a.translatedThreshold=k.getThreshold(g),l=q(b.minPointLength,5),I=a.getColumnMetrics(),A=I.width,H=a.barW=Math.max(A,1+2*h),t=a.pointXOffset=I.offset;d.inverted&&(c-=.5);b.pointPadding&&(H=Math.ceil(H));e.translate.apply(a);
a.points.forEach(function(e){var h=q(e.yBottom,c),n=999+Math.abs(h),v=f(e.plotY,-n,k.len+n);n=e.plotX+t;let w=H/2,p=Math.min(v,h);h=Math.max(v,h)-p;var m;let D,J;b.centerInCategory&&(n=a.adjustForMissingColumns(n,A,e,I));e.barX=n;e.pointWidth=A;e.tooltipPos=d.inverted?[k.len+k.pos-d.plotLeft-v,a.xAxis.len-n-w,h]:[n+w,v+k.pos-d.plotTop,h];v=g+(e.total||e.y);"percent"===b.stacking&&(v=g+(0>e.y)?-100:100);v=k.toPixels(v,!0);var u=(m=d.plotHeight-v-(d.plotHeight-c))?w*(p-v)/m:0;var F=m?w*(p+h-v)/m:0;
m=n-u+w;u=n+u+w;var R=n+F+w;F=n-F+w;D=p-l;J=p+h;0>e.y&&(D=p,J=p+h+l);d.inverted&&(R=k.width-p,m=v-(k.width-c),u=w*(v-R)/m,F=w*(v-(R-h))/m,m=n+w+u,u=m-2*u,R=n-F+w,F=n+F+w,D=p,J=p+h-l,0>e.y&&(J=p+h+l));e.shapeType="path";e.shapeArgs={x:m,y:D,width:u-m,height:h,d:[["M",m,D],["L",u,D],["L",R,J],["L",F,J],["Z"]]}})}}t.defaultOptions=k(a.defaultOptions,{});d.registerSeriesType("columnpyramid",t);"";return t});r(b,"Series/ErrorBar/ErrorBarSeriesDefaults.js",[],function(){"";return{color:"#000000",grouping:!1,
linkedTo:":previous",tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},whiskerWidth:null}});r(b,"Series/ErrorBar/ErrorBarSeries.js",[b["Series/BoxPlot/BoxPlotSeries.js"],b["Series/Column/ColumnSeries.js"],b["Series/ErrorBar/ErrorBarSeriesDefaults.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(a,d,b,h,f){const {arearange:e}=h.seriesTypes,{addEvent:q,merge:t,extend:E}=f;class x extends a{constructor(){super(...arguments);
this.points=this.options=this.data=void 0}getColumnMetrics(){return this.linkedParent&&this.linkedParent.columnMetrics||d.prototype.getColumnMetrics.call(this)}drawDataLabels(){const a=this.pointValKey;e&&(e.prototype.drawDataLabels.call(this),this.data.forEach(function(d){d.y=d[a]}))}toYData(a){return[a.low,a.high]}}x.defaultOptions=t(a.defaultOptions,b);q(x,"afterTranslate",function(){this.points.forEach(a=>{a.plotLow=a.plotY})},{order:0});E(x.prototype,{pointArrayMap:["low","high"],pointValKey:"high",
doQuartiles:!1});h.registerSeriesType("errorbar",x);return x});r(b,"Series/Gauge/GaugePoint.js",[b["Core/Series/SeriesRegistry.js"]],function(a){({series:{prototype:{pointClass:a}}}=a);class d extends a{constructor(){super(...arguments);this.shapeArgs=this.series=this.options=void 0}setState(a){this.state=a}}return d});r(b,"Series/Gauge/GaugeSeries.js",[b["Series/Gauge/GaugePoint.js"],b["Core/Globals.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(a,d,b,h){({noop:d}=d);const {series:e,
seriesTypes:{column:k}}=b,{clamp:q,isNumber:t,extend:E,merge:x,pick:v,pInt:n,defined:B}=h;class g extends e{constructor(){super(...arguments);this.yAxis=this.options=this.points=this.data=void 0}translate(){const c=this.yAxis,a=this.options,d=c.center;this.generatePoints();this.points.forEach(b=>{const g=x(a.dial,b.dial),e=n(g.radius)*d[2]/200,f=n(g.baseLength)*e/100,h=n(g.rearLength)*e/100,l=g.baseWidth,k=g.topWidth;let v=a.overshoot,p=c.startAngleRad+c.translate(b.y,void 0,void 0,void 0,!0);if(t(v)||
!1===a.wrap)v=t(v)?v/180*Math.PI:0,p=q(p,c.startAngleRad-v,c.endAngleRad+v);p=180*p/Math.PI;b.shapeType="path";b.shapeArgs={d:g.path||[["M",-h,-l/2],["L",f,-l/2],["L",e,-k/2],["L",e,k/2],["L",f,l/2],["L",-h,l/2],["Z"]],translateX:d[0],translateY:d[1],rotation:p};b.plotX=d[0];b.plotY=d[1];B(b.y)&&c.max-c.min&&(b.percentage=(b.y-c.min)/(c.max-c.min)*100)})}drawPoints(){const c=this,a=c.chart,d=c.yAxis.center,b=c.pivot,g=c.options,e=g.pivot,f=a.renderer;c.points.forEach(d=>{const b=d.graphic,e=d.shapeArgs,
h=e.d,p=x(g.dial,d.dial);b?(b.animate(e),e.d=h):d.graphic=f[d.shapeType](e).addClass("highcharts-dial").add(c.group);if(!a.styledMode)d.graphic[b?"animate":"attr"]({stroke:p.borderColor,"stroke-width":p.borderWidth,fill:p.backgroundColor})});b?b.animate({translateX:d[0],translateY:d[1]}):e&&(c.pivot=f.circle(0,0,e.radius).attr({zIndex:2}).addClass("highcharts-pivot").translate(d[0],d[1]).add(c.group),a.styledMode||c.pivot.attr({fill:e.backgroundColor,stroke:e.borderColor,"stroke-width":e.borderWidth}))}animate(a){const c=
this;a||c.points.forEach(a=>{const d=a.graphic;d&&(d.attr({rotation:180*c.yAxis.startAngleRad/Math.PI}),d.animate({rotation:a.shapeArgs.rotation},c.options.animation))})}render(){this.group=this.plotGroup("group","series",this.visible?"inherit":"hidden",this.options.zIndex,this.chart.seriesGroup);e.prototype.render.call(this);this.group.clip(this.chart.clipRect)}setData(a,d){e.prototype.setData.call(this,a,!1);this.processData();this.generatePoints();v(d,!0)&&this.chart.redraw()}hasData(){return!!this.points.length}}
g.defaultOptions=x(e.defaultOptions,{dataLabels:{borderColor:"#cccccc",borderRadius:3,borderWidth:1,crop:!1,defer:!1,enabled:!0,verticalAlign:"top",y:15,zIndex:2},dial:{backgroundColor:"#000000",baseLength:"70%",baseWidth:3,borderColor:"#cccccc",borderWidth:0,radius:"80%",rearLength:"10%",topWidth:1},pivot:{radius:5,borderWidth:0,borderColor:"#cccccc",backgroundColor:"#000000"},tooltip:{headerFormat:""},showInLegend:!1});E(g.prototype,{angular:!0,directTouch:!0,drawGraph:d,drawTracker:k.prototype.drawTracker,
fixedBox:!0,forceDL:!0,noSharedTooltip:!0,pointClass:a,trackerGroups:["group","dataLabelsGroup"]});b.registerSeriesType("gauge",g);"";return g});r(b,"Series/DragNodesComposition.js",[b["Core/Utilities.js"]],function(a){function d(){const a=this;let d,e,h;a.container&&(d=b(a.container,"mousedown",d=>{const f=a.hoverPoint;f&&f.series&&f.series.hasDraggableNodes&&f.series.options.draggable&&(f.series.onMouseDown(f,d),e=b(a.container,"mousemove",a=>f&&f.series&&f.series.onMouseMove(f,a)),h=b(a.container.ownerDocument,
"mouseup",a=>{e();h();return f&&f.series&&f.series.onMouseUp(f,a)}))}));b(a,"destroy",function(){d()})}const {addEvent:b}=a,h=[];return{compose:function(e){a.pushUnique(h,e)&&b(e,"load",d)},onMouseDown:function(a,d){d=this.chart.pointer.normalize(d);a.fixedPosition={chartX:d.chartX,chartY:d.chartY,plotX:a.plotX,plotY:a.plotY};a.inDragMode=!0},onMouseMove:function(a,d){if(a.fixedPosition&&a.inDragMode){const f=this.chart;d=f.pointer.normalize(d);var b=a.fixedPosition.chartX-d.chartX,e=a.fixedPosition.chartY-
d.chartY;d=f.graphLayoutsLookup;if(5<Math.abs(b)||5<Math.abs(e))b=a.fixedPosition.plotX-b,e=a.fixedPosition.plotY-e,f.isInsidePlot(b,e)&&(a.plotX=b,a.plotY=e,a.hasDragged=!0,this.redrawHalo(a),d.forEach(a=>{a.restartSimulation()}))}},onMouseUp:function(a){a.fixedPosition&&(a.hasDragged&&(this.layout.enableSimulation?this.layout.start():this.chart.redraw()),a.inDragMode=a.hasDragged=!1,this.options.fixedDraggable||delete a.fixedPosition)},redrawHalo:function(a){a&&this.halo&&this.halo.attr({d:a.haloPath(this.options.states.hover.halo.size)})}}});
r(b,"Series/GraphLayoutComposition.js",[b["Core/Animation/AnimationUtilities.js"],b["Core/Utilities.js"]],function(a,d){function b(){this.graphLayoutsLookup&&(this.graphLayoutsLookup.forEach(a=>{a.updateSimulation()}),this.redraw())}function h(){this.graphLayoutsLookup&&(this.graphLayoutsLookup.forEach(a=>{a.updateSimulation(!1)}),this.redraw())}function f(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(a=>{a.stop()})}function k(){let a,d=!1;const b=b=>{b.maxIterations--&&isFinite(b.temperature)&&
!b.isStable()&&!b.enableSimulation&&(b.beforeStep&&b.beforeStep(),b.step(),a=!1,d=!0)};if(this.graphLayoutsLookup){q(!1,this);for(this.graphLayoutsLookup.forEach(a=>a.start());!a;)a=!0,this.graphLayoutsLookup.forEach(b);d&&this.series.forEach(a=>{a&&a.layout&&a.render()})}}const {setAnimation:q}=a,{addEvent:t}=d,E=[];return{compose:function(a){d.pushUnique(E,a)&&(t(a,"afterPrint",b),t(a,"beforePrint",h),t(a,"predraw",f),t(a,"render",k))},integrations:{},layouts:{}}});r(b,"Series/PackedBubble/PackedBubblePoint.js",
[b["Core/Chart/Chart.js"],b["Core/Series/Point.js"],b["Core/Series/SeriesRegistry.js"]],function(a,d,b){({seriesTypes:{bubble:{prototype:{pointClass:b}}}}=b);class e extends b{constructor(){super(...arguments);this.radius=this.mass=this.degree=NaN;this.series=this.options=void 0;this.value=null}destroy(){this.series.layout&&this.series.layout.removeElementFromCollection(this,this.series.layout.nodes);return d.prototype.destroy.apply(this,arguments)}firePointEvent(){const a=this.series.options;if(this.isParentNode&&
a.parentNode){const b=a.allowPointSelect;a.allowPointSelect=a.parentNode.allowPointSelect;d.prototype.firePointEvent.apply(this,arguments);a.allowPointSelect=b}else d.prototype.firePointEvent.apply(this,arguments)}select(){const b=this.series.chart;this.isParentNode?(b.getSelectedPoints=b.getSelectedParentNodes,d.prototype.select.apply(this,arguments),b.getSelectedPoints=a.prototype.getSelectedPoints):d.prototype.select.apply(this,arguments)}}return e});r(b,"Series/PackedBubble/PackedBubbleSeriesDefaults.js",
[b["Core/Utilities.js"]],function(a){const {isNumber:d}=a;"";return{minSize:"10%",maxSize:"50%",sizeBy:"area",zoneAxis:"y",crisp:!1,tooltip:{pointFormat:"Value: {point.value}"},draggable:!0,useSimulation:!0,parentNode:{allowPointSelect:!1},dataLabels:{formatter:function(){const {numberFormatter:a}=this.series.chart,{value:b}=this.point;return d(b)?a(b,-1):""},parentNodeFormatter:function(){return this.name},parentNodeTextPath:{enabled:!0},padding:0,style:{transition:"opacity 2000ms"}},layoutAlgorithm:{initialPositions:"circle",
initialPositionRadius:20,bubblePadding:5,parentNodeLimit:!1,seriesInteraction:!0,dragBetweenSeries:!1,parentNodeOptions:{maxIterations:400,gravitationalConstant:.03,maxSpeed:50,initialPositionRadius:100,seriesInteraction:!0,marker:{fillColor:null,fillOpacity:1,lineWidth:null,lineColor:null,symbol:"circle"}},enableSimulation:!0,type:"packedbubble",integration:"packedbubble",maxIterations:1E3,splitSeries:!1,maxSpeed:5,gravitationalConstant:.01,friction:-.981}}});r(b,"Series/Networkgraph/VerletIntegration.js",
[],function(){return{attractive:function(a,d,b){const e=a.getMass(),f=-b.x*d*this.diffTemperature;d=-b.y*d*this.diffTemperature;a.fromNode.fixedPosition||(a.fromNode.plotX-=f*e.fromNode/a.fromNode.degree,a.fromNode.plotY-=d*e.fromNode/a.fromNode.degree);a.toNode.fixedPosition||(a.toNode.plotX+=f*e.toNode/a.toNode.degree,a.toNode.plotY+=d*e.toNode/a.toNode.degree)},attractiveForceFunction:function(a,d){return(d-a)/a},barycenter:function(){let a=this.options.gravitationalConstant,d=this.barycenter.xFactor,
b=this.barycenter.yFactor;d=(d-(this.box.left+this.box.width)/2)*a;b=(b-(this.box.top+this.box.height)/2)*a;this.nodes.forEach(function(a){a.fixedPosition||(a.plotX-=d/a.mass/a.degree,a.plotY-=b/a.mass/a.degree)})},getK:function(a){return Math.pow(a.box.width*a.box.height/a.nodes.length,.5)},integrate:function(a,d){var b=-a.options.friction;let h=a.options.maxSpeed,f=(d.plotX+d.dispX-d.prevX)*b;b*=d.plotY+d.dispY-d.prevY;var k=Math.abs;let q=k(f)/(f||1);k=k(b)/(b||1);f=q*Math.min(h,Math.abs(f));b=
k*Math.min(h,Math.abs(b));d.prevX=d.plotX+d.dispX;d.prevY=d.plotY+d.dispY;d.plotX+=f;d.plotY+=b;d.temperature=a.vectorLength({x:f,y:b})},repulsive:function(a,d,b){d=d*this.diffTemperature/a.mass/a.degree;a.fixedPosition||(a.plotX+=b.x*d,a.plotY+=b.y*d)},repulsiveForceFunction:function(a,d){return(d-a)/a*(d>a?1:0)}}});r(b,"Series/PackedBubble/PackedBubbleIntegration.js",[b["Core/Globals.js"],b["Series/Networkgraph/VerletIntegration.js"]],function(a,d){({noop:a}=a);return{barycenter:function(){const a=
this.options.gravitationalConstant,d=this.box,b=this.nodes;let k,q;for(const e of b)this.options.splitSeries&&!e.isParentNode?(k=e.series.parentNode.plotX,q=e.series.parentNode.plotY):(k=d.width/2,q=d.height/2),e.fixedPosition||(e.plotX-=(e.plotX-k)*a/(e.mass*Math.sqrt(b.length)),e.plotY-=(e.plotY-q)*a/(e.mass*Math.sqrt(b.length)))},getK:a,integrate:d.integrate,repulsive:function(a,d,b,k){const e=d*this.diffTemperature/a.mass/a.degree;d=b.x*e;b=b.y*e;a.fixedPosition||(a.plotX+=d,a.plotY+=b);k.fixedPosition||
(k.plotX-=d,k.plotY-=b)},repulsiveForceFunction:function(a,d,b,k){return Math.min(a,(b.marker.radius+k.marker.radius)/2)}}});r(b,"Series/Networkgraph/EulerIntegration.js",[],function(){return{attractive:function(a,d,b,h){const e=a.getMass(),k=b.x/h*d;d*=b.y/h;a.fromNode.fixedPosition||(a.fromNode.dispX-=k*e.fromNode/a.fromNode.degree,a.fromNode.dispY-=d*e.fromNode/a.fromNode.degree);a.toNode.fixedPosition||(a.toNode.dispX+=k*e.toNode/a.toNode.degree,a.toNode.dispY+=d*e.toNode/a.toNode.degree)},attractiveForceFunction:function(a,
d){return a*a/d},barycenter:function(){const a=this.options.gravitationalConstant,d=this.barycenter.xFactor,b=this.barycenter.yFactor;this.nodes.forEach(function(e){if(!e.fixedPosition){var f=e.getDegree();f*=1+f/2;e.dispX+=(d-e.plotX)*a*f/e.degree;e.dispY+=(b-e.plotY)*a*f/e.degree}})},getK:function(a){return Math.pow(a.box.width*a.box.height/a.nodes.length,.3)},integrate:function(a,d){let b;d.dispX+=d.dispX*a.options.friction;d.dispY+=d.dispY*a.options.friction;b=d.temperature=a.vectorLength({x:d.dispX,
y:d.dispY});0!==b&&(d.plotX+=d.dispX/b*Math.min(Math.abs(d.dispX),a.temperature),d.plotY+=d.dispY/b*Math.min(Math.abs(d.dispY),a.temperature))},repulsive:function(a,d,b,h){a.dispX+=b.x/h*d/a.degree;a.dispY+=b.y/h*d/a.degree},repulsiveForceFunction:function(a,d){return d*d/a}}});r(b,"Series/Networkgraph/QuadTreeNode.js",[],function(){class a{constructor(a){this.isInternal=this.isEmpty=this.body=!1;this.nodes=[];this.box=a;this.boxSize=Math.min(a.width,a.height)}divideBox(){const d=this.box.width/2,
b=this.box.height/2;this.nodes[0]=new a({left:this.box.left,top:this.box.top,width:d,height:b});this.nodes[1]=new a({left:this.box.left+d,top:this.box.top,width:d,height:b});this.nodes[2]=new a({left:this.box.left+d,top:this.box.top+b,width:d,height:b});this.nodes[3]=new a({left:this.box.left,top:this.box.top+b,width:d,height:b})}getBoxPosition(a){const b=a.plotY<this.box.top+this.box.height/2;return a.plotX<this.box.left+this.box.width/2?b?0:3:b?1:2}insert(b,e){this.isInternal?this.nodes[this.getBoxPosition(b)].insert(b,
e-1):(this.isEmpty=!1,this.body?e?(this.isInternal=!0,this.divideBox(),!0!==this.body&&(this.nodes[this.getBoxPosition(this.body)].insert(this.body,e-1),this.body=!0),this.nodes[this.getBoxPosition(b)].insert(b,e-1)):(e=new a({top:b.plotX||NaN,left:b.plotY||NaN,width:.1,height:.1}),e.body=b,e.isInternal=!1,this.nodes.push(e)):(this.isInternal=!1,this.body=b))}updateMassAndCenter(){let a=0,b=0,h=0;if(this.isInternal){for(const d of this.nodes)d.isEmpty||(a+=d.mass,b+=d.plotX*d.mass,h+=d.plotY*d.mass);
b/=a;h/=a}else this.body&&(a=this.body.mass,b=this.body.plotX,h=this.body.plotY);this.mass=a;this.plotX=b;this.plotY=h}}return a});r(b,"Series/Networkgraph/QuadTree.js",[b["Series/Networkgraph/QuadTreeNode.js"]],function(a){class b{constructor(b,d,f,k){this.box={left:b,top:d,width:f,height:k};this.maxDepth=25;this.root=new a(this.box);this.root.isInternal=!0;this.root.isRoot=!0;this.root.divideBox()}calculateMassAndCenter(){this.visitNodeRecursive(null,null,function(a){a.updateMassAndCenter()})}insertNodes(a){for(const b of a)this.root.insert(b,
this.maxDepth)}visitNodeRecursive(a,b,d){let e;a||(a=this.root);a===this.root&&b&&(e=b(a));if(!1!==e){for(const f of a.nodes){if(f.isInternal){b&&(e=b(f));if(!1===e)continue;this.visitNodeRecursive(f,b,d)}else f.body&&b&&b(f.body);d&&d(f)}a===this.root&&d&&d(a)}}}return b});r(b,"Series/Networkgraph/ReingoldFruchtermanLayout.js",[b["Series/Networkgraph/EulerIntegration.js"],b["Core/Globals.js"],b["Series/GraphLayoutComposition.js"],b["Series/Networkgraph/QuadTree.js"],b["Core/Utilities.js"],b["Series/Networkgraph/VerletIntegration.js"]],
function(a,b,e,h,f,k){const {win:d}=b,{clamp:t,defined:E,isFunction:x,fireEvent:v,pick:n}=f;class B{constructor(){this.attractiveForce=void 0;this.box={};this.currentStep=0;this.initialRendering=!0;this.integration=void 0;this.links=[];this.nodes=[];this.repulsiveForce=this.quadTree=this.options=void 0;this.series=[];this.simulation=!1}static compose(b){e.compose(b);e.integrations.euler=a;e.integrations.verlet=k;e.layouts["reingold-fruchterman"]=B}init(a){this.options=a;this.nodes=[];this.links=[];
this.series=[];this.box={x:0,y:0,width:0,height:0};this.setInitialRendering(!0);this.integration=e.integrations[a.integration];this.enableSimulation=a.enableSimulation;this.attractiveForce=n(a.attractiveForce,this.integration.attractiveForceFunction);this.repulsiveForce=n(a.repulsiveForce,this.integration.repulsiveForceFunction);this.approximation=a.approximation}updateSimulation(a){this.enableSimulation=n(a,this.options.enableSimulation)}start(){const a=this.series,c=this.options;this.currentStep=
0;this.forces=a[0]&&a[0].forces||[];this.chart=a[0]&&a[0].chart;this.initialRendering&&(this.initPositions(),a.forEach(function(a){a.finishedAnimating=!0;a.render()}));this.setK();this.resetSimulation(c);this.enableSimulation&&this.step()}step(){const a=this.series;this.currentStep++;"barnes-hut"===this.approximation&&(this.createQuadTree(),this.quadTree.calculateMassAndCenter());for(const a of this.forces||[])this[a+"Forces"](this.temperature);this.applyLimits();this.temperature=this.coolDown(this.startTemperature,
this.diffTemperature,this.currentStep);this.prevSystemTemperature=this.systemTemperature;this.systemTemperature=this.getSystemTemperature();if(this.enableSimulation){for(const c of a)c.chart&&c.render();this.maxIterations--&&isFinite(this.temperature)&&!this.isStable()?(this.simulation&&d.cancelAnimationFrame(this.simulation),this.simulation=d.requestAnimationFrame(()=>this.step())):(this.simulation=!1,this.series.forEach(a=>{v(a,"afterSimulation")}))}}stop(){this.simulation&&d.cancelAnimationFrame(this.simulation)}setArea(a,
c,b,d){this.box={left:a,top:c,width:b,height:d}}setK(){this.k=this.options.linkLength||this.integration.getK(this)}addElementsToCollection(a,c){for(const b of a)-1===c.indexOf(b)&&c.push(b)}removeElementFromCollection(a,c){a=c.indexOf(a);-1!==a&&c.splice(a,1)}clear(){this.nodes.length=0;this.links.length=0;this.series.length=0;this.resetSimulation()}resetSimulation(){this.forcedStop=!1;this.systemTemperature=0;this.setMaxIterations();this.setTemperature();this.setDiffTemperature()}restartSimulation(){this.simulation?
this.resetSimulation():(this.setInitialRendering(!1),this.enableSimulation?this.start():this.setMaxIterations(1),this.chart&&this.chart.redraw(),this.setInitialRendering(!0))}setMaxIterations(a){this.maxIterations=n(a,this.options.maxIterations)}setTemperature(){this.temperature=this.startTemperature=Math.sqrt(this.nodes.length)}setDiffTemperature(){this.diffTemperature=this.startTemperature/(this.options.maxIterations+1)}setInitialRendering(a){this.initialRendering=a}createQuadTree(){this.quadTree=
new h(this.box.left,this.box.top,this.box.width,this.box.height);this.quadTree.insertNodes(this.nodes)}initPositions(){const a=this.options.initialPositions;if(x(a)){a.call(this);for(const a of this.nodes)E(a.prevX)||(a.prevX=a.plotX),E(a.prevY)||(a.prevY=a.plotY),a.dispX=0,a.dispY=0}else"circle"===a?this.setCircularPositions():this.setRandomPositions()}setCircularPositions(){const a=this.box;var c=this.nodes;const b=2*Math.PI/(c.length+1),d=c.filter(function(a){return 0===a.linksTo.length}),e={},
f=this.options.initialPositionRadius,h=a=>{for(const c of a.linksFrom||[])e[c.toNode.id]||(e[c.toNode.id]=!0,k.push(c.toNode),h(c.toNode))};let k=[];for(const a of d)k.push(a),h(a);if(k.length)for(const a of c)-1===k.indexOf(a)&&k.push(a);else k=c;for(let d=0,g=k.length;d<g;++d)c=k[d],c.plotX=c.prevX=n(c.plotX,a.width/2+f*Math.cos(d*b)),c.plotY=c.prevY=n(c.plotY,a.height/2+f*Math.sin(d*b)),c.dispX=0,c.dispY=0}setRandomPositions(){const a=this.box,c=this.nodes,b=c.length+1,d=a=>{a=a*a/Math.PI;return a-=
Math.floor(a)};let e;for(let g=0,f=c.length;g<f;++g)e=c[g],e.plotX=e.prevX=n(e.plotX,a.width*d(g)),e.plotY=e.prevY=n(e.plotY,a.height*d(b+g)),e.dispX=0,e.dispY=0}force(a,...c){this.integration[a].apply(this,c)}barycenterForces(){this.getBarycenter();this.force("barycenter")}getBarycenter(){let a=0,c=0,b=0;for(const d of this.nodes)c+=d.plotX*d.mass,b+=d.plotY*d.mass,a+=d.mass;return this.barycenter={x:c,y:b,xFactor:c/a,yFactor:b/a}}barnesHutApproximation(a,c){const b=this.getDistXY(a,c),d=this.vectorLength(b);
let e,g;a!==c&&0!==d&&(c.isInternal?c.boxSize/d<this.options.theta&&0!==d?(g=this.repulsiveForce(d,this.k),this.force("repulsive",a,g*c.mass,b,d),e=!1):e=!0:(g=this.repulsiveForce(d,this.k),this.force("repulsive",a,g*c.mass,b,d)));return e}repulsiveForces(){if("barnes-hut"===this.approximation)for(const a of this.nodes)this.quadTree.visitNodeRecursive(null,c=>this.barnesHutApproximation(a,c));else{let a,c,b;for(const d of this.nodes)for(const e of this.nodes)d===e||d.fixedPosition||(b=this.getDistXY(d,
e),c=this.vectorLength(b),0!==c&&(a=this.repulsiveForce(c,this.k),this.force("repulsive",d,a*e.mass,b,c)))}}attractiveForces(){let a,c,b;for(const d of this.links)d.fromNode&&d.toNode&&(a=this.getDistXY(d.fromNode,d.toNode),c=this.vectorLength(a),0!==c&&(b=this.attractiveForce(c,this.k),this.force("attractive",d,b,a,c)))}applyLimits(){const a=this.nodes;for(const c of a){if(c.fixedPosition)break;this.integration.integrate(this,c);this.applyLimitBox(c,this.box);c.dispX=0;c.dispY=0}}applyLimitBox(a,
c){const b=a.radius;a.plotX=t(a.plotX,c.left+b,c.width-b);a.plotY=t(a.plotY,c.top+b,c.height-b)}coolDown(a,c,b){return a-c*b}isStable(){return.00001>Math.abs(this.systemTemperature-this.prevSystemTemperature)||0>=this.temperature}getSystemTemperature(){let a=0;for(const c of this.nodes)a+=c.temperature;return a}vectorLength(a){return Math.sqrt(a.x*a.x+a.y*a.y)}getDistR(a,c){a=this.getDistXY(a,c);return this.vectorLength(a)}getDistXY(a,c){const b=a.plotX-c.plotX;a=a.plotY-c.plotY;return{x:b,y:a,absX:Math.abs(b),
absY:Math.abs(a)}}}return B});r(b,"Series/PackedBubble/PackedBubbleLayout.js",[b["Series/GraphLayoutComposition.js"],b["Series/PackedBubble/PackedBubbleIntegration.js"],b["Series/Networkgraph/ReingoldFruchtermanLayout.js"],b["Core/Utilities.js"]],function(a,b,e,h){function d(){const a=[];this.series.forEach(b=>{b.parentNode&&b.parentNode.selected&&a.push(b.parentNode)});return a}function k(){this.allDataPoints&&delete this.allDataPoints}const {addEvent:q,pick:t}=h,E=[];class x extends e{constructor(){super(...arguments);
this.index=NaN;this.nodes=[];this.options=void 0;this.series=[]}static compose(f){e.compose(f);a.integrations.packedbubble=b;a.layouts.packedbubble=x;h.pushUnique(E,f)&&(q(f,"beforeRedraw",k),f.prototype.getSelectedParentNodes=d)}beforeStep(){this.options.marker&&this.series.forEach(a=>{a&&a.calculateParentRadius()})}isStable(){const a=Math.abs(this.prevSystemTemperature-this.systemTemperature);return 1>Math.abs(10*this.systemTemperature/Math.sqrt(this.nodes.length))&&.00001>a||0>=this.temperature}setCircularPositions(){const a=
this.box;var b=this.nodes;const d=2*Math.PI/(b.length+1),e=this.options.initialPositionRadius;let c,f=0;for(const g of b)this.options.splitSeries&&!g.isParentNode?(b=g.series.parentNode.plotX,c=g.series.parentNode.plotY):(b=a.width/2,c=a.height/2),g.plotX=g.prevX=t(g.plotX,b+e*Math.cos(g.index||f*d)),g.plotY=g.prevY=t(g.plotY,c+e*Math.sin(g.index||f*d)),g.dispX=0,g.dispY=0,f++}repulsiveForces(){const a=this,b=a.options.bubblePadding;let d,e,c;a.nodes.forEach(g=>{g.degree=g.mass;g.neighbours=0;a.nodes.forEach(f=>
{d=0;g===f||g.fixedPosition||!a.options.seriesInteraction&&g.series!==f.series||(c=a.getDistXY(g,f),e=a.vectorLength(c)-(g.marker.radius+f.marker.radius+b),0>e&&(g.degree+=.01,g.neighbours++,d=a.repulsiveForce(-e/Math.sqrt(g.neighbours),a.k,g,f)),a.force("repulsive",g,d*f.mass,c,f,e))})})}applyLimitBox(a,b){let d,e;this.options.splitSeries&&!a.isParentNode&&this.options.parentNodeLimit&&(d=this.getDistXY(a,a.series.parentNode),e=a.series.parentNodeRadius-a.marker.radius-this.vectorLength(d),0>e&&
e>-2*a.marker.radius&&(a.plotX-=.01*d.x,a.plotY-=.01*d.y));super.applyLimitBox(a,b)}}return a.layouts.packedbubble=x});r(b,"Series/SimulationSeriesUtilities.js",[b["Core/Utilities.js"],b["Core/Animation/AnimationUtilities.js"]],function(a,b){const {syncTimeout:d}=a,{animObject:h}=b;return{initDataLabels:function(){const a=this.options.dataLabels;if(!this.dataLabelsGroup){const b=this.initDataLabelsGroup();!this.chart.styledMode&&(null===a||void 0===a?0:a.style)&&b.css(a.style);b.attr({opacity:0});
this.visible&&b.show();return b}this.dataLabelsGroup.attr({opacity:1});return this.dataLabelsGroup},initDataLabelsDefer:function(){var a;const b=this.options.dataLabels;(null===b||void 0===b?0:b.defer)&&(null===(a=this.options.layoutAlgorithm)||void 0===a?0:a.enableSimulation)?d(()=>{this.deferDataLabels=!1},b?h(b.animation).defer:0):this.deferDataLabels=!1}}});r(b,"Series/PackedBubble/PackedBubbleSeries.js",[b["Core/Color/Color.js"],b["Series/DragNodesComposition.js"],b["Series/GraphLayoutComposition.js"],
b["Core/Globals.js"],b["Series/PackedBubble/PackedBubblePoint.js"],b["Series/PackedBubble/PackedBubbleSeriesDefaults.js"],b["Series/PackedBubble/PackedBubbleLayout.js"],b["Core/Series/SeriesRegistry.js"],b["Series/SimulationSeriesUtilities.js"],b["Core/Utilities.js"],b["Core/Animation/AnimationUtilities.js"]],function(a,b,e,h,f,k,q,t,E,x){const {parse:d}=a;({noop:a}=h);const {series:{prototype:n},seriesTypes:{bubble:B}}=t,{initDataLabels:g,initDataLabelsDefer:c}=E,{addEvent:l,clamp:r,defined:A,extend:H,
fireEvent:Q,isArray:w,isNumber:z,merge:P,pick:M}=x;class N extends B{constructor(){super(...arguments);this.options=this.layout=this.data=this.chart=void 0;this.parentNodeMass=0;this.xData=this.points=void 0;this.deferDataLabels=!0}static compose(a,c,d,e){B.compose(a,c,d,e);b.compose(c);q.compose(c)}accumulateAllPoints(){const a=this.chart,b=[];let c;for(const d of a.series)if(d.is("packedbubble")&&d.visible||!a.options.chart.ignoreHiddenSeries){c=d.yData||[];for(let a=0;a<c.length;a++)b.push([null,
null,c[a],d.index,a,{id:a,marker:{radius:0}}])}return b}addLayout(){const a=this.options.layoutAlgorithm=this.options.layoutAlgorithm||{},b=a.type||"packedbubble",c=this.chart.options.chart;let d=this.chart.graphLayoutsStorage,g=this.chart.graphLayoutsLookup,f;d||(this.chart.graphLayoutsStorage=d={},this.chart.graphLayoutsLookup=g=[]);f=d[b];f||(a.enableSimulation=A(c.forExport)?!c.forExport:a.enableSimulation,d[b]=f=new e.layouts[b],f.init(a),g.splice(f.index,0,f));this.layout=f;this.points.forEach(a=>
{a.mass=2;a.degree=1;a.collisionNmb=1});f.setArea(0,0,this.chart.plotWidth,this.chart.plotHeight);f.addElementsToCollection([this],f.series);f.addElementsToCollection(this.points,f.nodes)}addSeriesLayout(){var a=this.options.layoutAlgorithm=this.options.layoutAlgorithm||{};const b=a.type||"packedbubble",c=this.chart.graphLayoutsStorage,d=this.chart.graphLayoutsLookup;a=P(a,a.parentNodeOptions,{enableSimulation:this.layout.options.enableSimulation});let g=c[b+"-series"];g||(c[b+"-series"]=g=new e.layouts[b],
g.init(a),d.splice(g.index,0,g));this.parentNodeLayout=g;this.createParentNodes()}calculateParentRadius(){const a=this.seriesBox();this.parentNodeRadius=r(Math.sqrt(2*this.parentNodeMass/Math.PI)+20,20,a?Math.max(Math.sqrt(Math.pow(a.width,2)+Math.pow(a.height,2))/2+20,20):Math.sqrt(2*this.parentNodeMass/Math.PI)+20);this.parentNode&&(this.parentNode.marker.radius=this.parentNode.radius=this.parentNodeRadius)}calculateZExtremes(){let a=this.options.zMin,b=this.options.zMax,c=Infinity,d=-Infinity;
if(a&&b)return[a,b];this.chart.series.forEach(a=>{a.yData.forEach(a=>{A(a)&&(a>d&&(d=a),a<c&&(c=a))})});a=M(a,c);b=M(b,d);return[a,b]}checkOverlap(a,b){const c=a[0]-b[0],d=a[1]-b[1];return-.001>Math.sqrt(c*c+d*d)-Math.abs(a[2]+b[2])}createParentNodes(){const a=this.pointClass,b=this.chart,c=this.parentNodeLayout,e=this.layout.options;let g,f=this.parentNode,h={radius:this.parentNodeRadius,lineColor:this.color,fillColor:d(this.color).brighten(.4).get()};e.parentNodeOptions&&(h=P(e.parentNodeOptions.marker||
{},h));this.parentNodeMass=0;this.points.forEach(a=>{this.parentNodeMass+=Math.PI*Math.pow(a.marker.radius,2)});this.calculateParentRadius();c.nodes.forEach(a=>{a.seriesIndex===this.index&&(g=!0)});c.setArea(0,0,b.plotWidth,b.plotHeight);g||(f||(f=(new a).init(this,{mass:this.parentNodeRadius/2,marker:h,dataLabels:{inside:!1},states:{normal:{marker:h},hover:{marker:h}},dataLabelOnNull:!0,degree:this.parentNodeRadius,isParentNode:!0,seriesIndex:this.index})),this.parentNode&&(f.plotX=this.parentNode.plotX,
f.plotY=this.parentNode.plotY),this.parentNode=f,c.addElementsToCollection([this],c.series),c.addElementsToCollection([f],c.nodes))}deferLayout(){const a=this.options.layoutAlgorithm;this.visible&&(this.addLayout(),a.splitSeries&&this.addSeriesLayout())}destroy(){this.chart.graphLayoutsLookup&&this.chart.graphLayoutsLookup.forEach(a=>{a.removeElementFromCollection(this,a.series)},this);this.parentNode&&this.parentNodeLayout&&(this.parentNodeLayout.removeElementFromCollection(this.parentNode,this.parentNodeLayout.nodes),
this.parentNode.dataLabel&&(this.parentNode.dataLabel=this.parentNode.dataLabel.destroy()));n.destroy.apply(this,arguments)}drawDataLabels(){this.deferDataLabels||(n.drawDataLabels.call(this,this.points),this.parentNode&&(this.parentNode.formatPrefix="parentNode",n.drawDataLabels.call(this,[this.parentNode])))}drawGraph(){var a;if(this.layout&&this.layout.options.splitSeries){var b=this.chart,c=this.layout.options.parentNodeOptions.marker;c={fill:c.fillColor||d(this.color).brighten(.4).get(),opacity:c.fillOpacity,
stroke:c.lineColor||this.color,"stroke-width":M(c.lineWidth,this.options.lineWidth)};this.parentNodesGroup=this.plotGroup("parentNodesGroup","parentNode",this.visible?"inherit":"hidden",.1,b.seriesGroup);null===(a=this.group)||void 0===a?void 0:a.attr({zIndex:2});this.calculateParentRadius();this.parentNode&&A(this.parentNode.plotX)&&A(this.parentNode.plotY)&&A(this.parentNodeRadius)&&(a=P({x:this.parentNode.plotX-this.parentNodeRadius,y:this.parentNode.plotY-this.parentNodeRadius,width:2*this.parentNodeRadius,
height:2*this.parentNodeRadius},c),this.parentNode.graphic||(this.graph=this.parentNode.graphic=b.renderer.symbol(c.symbol).add(this.parentNodesGroup)),this.parentNode.graphic.attr(a))}}drawTracker(){const a=this.parentNode;let b;super.drawTracker();a&&(b=w(a.dataLabels)?a.dataLabels:a.dataLabel?[a.dataLabel]:[],a.graphic&&(a.graphic.element.point=a),b.forEach(b=>{b.div?b.div.point=a:b.element.point=a}))}getPointRadius(){const a=this.chart,b=this.options,c=b.useSimulation,d=Math.min(a.plotWidth,a.plotHeight),
e={},g=[],f=a.allDataPoints||[],h=f.length;let k,l,n,w;["minSize","maxSize"].forEach(a=>{const c=parseInt(b[a],10),g=/%$/.test(b[a]);e[a]=g?d*c/100:c*Math.sqrt(h)});a.minRadius=k=e.minSize/Math.sqrt(h);a.maxRadius=l=e.maxSize/Math.sqrt(h);const y=c?this.calculateZExtremes():[k,l];f.forEach((a,b)=>{n=c?r(a[2],y[0],y[1]):a[2];w=this.getRadius(y[0],y[1],k,l,n);0===w&&(w=null);f[b][2]=w;g.push(w)});this.radii=g}init(){n.init.apply(this,arguments);c.call(this);this.eventsToUnbind.push(l(this,"updatedData",
function(){this.chart.series.forEach(a=>{a.type===this.type&&(a.isDirty=!0)},this)}));return this}onMouseUp(a){const c=a;if(c.fixedPosition&&!c.removed){const a=this.layout,d=this.parentNodeLayout;let e,g;d&&a.options.dragBetweenSeries&&d.nodes.forEach(b=>{c&&c.marker&&b!==c.series.parentNode&&(e=a.getDistXY(c,b),g=a.vectorLength(e)-b.marker.radius-c.marker.radius,0>g&&(b.series.addPoint(P(c.options,{plotX:c.plotX,plotY:c.plotY}),!1),a.removeElementFromCollection(c,a.nodes),c.remove()))});b.onMouseUp.apply(this,
arguments)}}placeBubbles(a){const b=this.checkOverlap,c=this.positionBubble,d=[];let e=1,g=0,f=0;var h=[];let p;a=a.sort((a,b)=>b[2]-a[2]);if(a.length){d.push([[0,0,a[0][2],a[0][3],a[0][4]]]);if(1<a.length)for(d.push([[0,0-a[1][2]-a[0][2],a[1][2],a[1][3],a[1][4]]]),p=2;p<a.length;p++)a[p][2]=a[p][2]||1,h=c(d[e][g],d[e-1][f],a[p]),b(h,d[e][0])?(d.push([]),f=0,d[e+1].push(c(d[e][g],d[e][0],a[p])),e++,g=0):1<e&&d[e-1][f+1]&&b(h,d[e-1][f+1])?(f++,d[e].push(c(d[e][g],d[e-1][f],a[p])),g++):(g++,d[e].push(h));
this.chart.stages=d;this.chart.rawPositions=[].concat.apply([],d);this.resizeRadius();h=this.chart.rawPositions}return h}pointAttribs(a,b){var c=this.options;let d=c.marker;a&&a.isParentNode&&c.layoutAlgorithm&&c.layoutAlgorithm.parentNodeOptions&&(d=c.layoutAlgorithm.parentNodeOptions.marker);c=d.fillOpacity;a=n.pointAttribs.call(this,a,b);1!==c&&(a["fill-opacity"]=c);return a}positionBubble(a,b,c){var d=Math.sqrt,e=Math.asin,g=Math.acos;const f=Math.pow,h=Math.abs;d=d(f(a[0]-b[0],2)+f(a[1]-b[1],
2));g=g((f(d,2)+f(c[2]+b[2],2)-f(c[2]+a[2],2))/(2*(c[2]+b[2])*d));e=e(h(a[0]-b[0])/d);a=(0>a[1]-b[1]?0:Math.PI)+g+e*(0>(a[0]-b[0])*(a[1]-b[1])?1:-1);return[b[0]+(b[2]+c[2])*Math.sin(a),b[1]-(b[2]+c[2])*Math.cos(a),c[2],c[3],c[4]]}render(){const a=[];n.render.apply(this,arguments);this.options.dataLabels.allowOverlap||(this.data.forEach(b=>{w(b.dataLabels)&&b.dataLabels.forEach(b=>{a.push(b)})}),this.options.useSimulation&&this.chart.hideOverlappingLabels(a))}resizeRadius(){const a=this.chart,b=a.rawPositions;
var c=Math.min,d=Math.max;const e=a.plotLeft,g=a.plotTop,f=a.plotHeight,h=a.plotWidth;let k,l,n,w,y;k=n=Number.POSITIVE_INFINITY;l=w=Number.NEGATIVE_INFINITY;for(const a of b)y=a[2],k=c(k,a[0]-y),l=d(l,a[0]+y),n=c(n,a[1]-y),w=d(w,a[1]+y);d=[l-k,w-n];c=c.apply([],[(h-e)/d[0],(f-g)/d[1]]);if(1e-10<Math.abs(c-1)){for(const a of b)a[2]*=c;this.placeBubbles(b)}else a.diffY=f/2+g-n-(w-n)/2,a.diffX=h/2+e-k-(l-k)/2}seriesBox(){const a=this.chart,b=Math.max,c=Math.min,d=[a.plotLeft,a.plotLeft+a.plotWidth,
a.plotTop,a.plotTop+a.plotHeight];let e;this.data.forEach(a=>{A(a.plotX)&&A(a.plotY)&&a.marker.radius&&(e=a.marker.radius,d[0]=c(d[0],a.plotX-e),d[1]=b(d[1],a.plotX+e),d[2]=c(d[2],a.plotY-e),d[3]=b(d[3],a.plotY+e))});return z(d.width/d.height)?d:null}setVisible(){const a=this;n.setVisible.apply(a,arguments);a.parentNodeLayout&&a.graph?a.visible?(a.graph.show(),a.parentNode.dataLabel&&a.parentNode.dataLabel.show()):(a.graph.hide(),a.parentNodeLayout.removeElementFromCollection(a.parentNode,a.parentNodeLayout.nodes),
a.parentNode.dataLabel&&a.parentNode.dataLabel.hide()):a.layout&&(a.visible?a.layout.addElementsToCollection(a.points,a.layout.nodes):a.points.forEach(b=>{a.layout.removeElementFromCollection(b,a.layout.nodes)}))}translate(){const a=this.chart,b=this.data,c=this.index,d=this.options.useSimulation;let e;this.processedXData=this.xData;this.generatePoints();A(a.allDataPoints)||(a.allDataPoints=this.accumulateAllPoints(),this.getPointRadius());if(d)var g=a.allDataPoints;else g=this.placeBubbles(a.allDataPoints),
this.options.draggable=!1;for(const f of g)f[3]===c&&(g=b[f[4]],e=M(f[2],void 0),d||(g.plotX=f[0]-a.plotLeft+a.diffX,g.plotY=f[1]-a.plotTop+a.diffY),z(e)&&(g.marker=H(g.marker,{radius:e,width:2*e,height:2*e}),g.radius=e));d&&this.deferLayout();Q(this,"afterTranslate")}}N.defaultOptions=P(B.defaultOptions,k);H(N.prototype,{pointClass:f,axisTypes:[],directTouch:!0,forces:["barycenter","repulsive"],hasDraggableNodes:!0,isCartesian:!1,noSharedTooltip:!0,pointArrayMap:["value"],pointValKey:"value",requireSorting:!1,
trackerGroups:["group","dataLabelsGroup","parentNodesGroup"],initDataLabels:g,alignDataLabel:n.alignDataLabel,indexateNodes:a,onMouseDown:b.onMouseDown,onMouseMove:b.onMouseMove,redrawHalo:b.redrawHalo,searchPoint:a});t.registerSeriesType("packedbubble",N);"";return N});r(b,"Series/Polygon/PolygonSeries.js",[b["Core/Globals.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(a,b,e){({noop:a}=a);const {series:d,seriesTypes:{area:f,line:k,scatter:q}}=b,{extend:t,merge:r}=e;class x extends q{constructor(){super(...arguments);
this.points=this.options=this.data=void 0}getGraphPath(){let a=k.prototype.getGraphPath.call(this),b=a.length+1;for(;b--;)(b===a.length||"M"===a[b][0])&&0<b&&a.splice(b,0,["Z"]);return this.areaPath=a}drawGraph(){this.options.fillColor=this.color;f.prototype.drawGraph.call(this)}}x.defaultOptions=r(q.defaultOptions,{marker:{enabled:!1,states:{hover:{enabled:!1}}},stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:""},trackByArea:!0,legendSymbol:"rectangle"});t(x.prototype,{type:"polygon",drawTracker:d.prototype.drawTracker,
setStackedPoints:a});b.registerSeriesType("polygon",x);"";return x});r(b,"Core/Axis/WaterfallAxis.js",[b["Core/Axis/Stacking/StackItem.js"],b["Core/Utilities.js"]],function(a,b){const {addEvent:d,objectEach:h}=b;var f;(function(b){function e(){const a=this.waterfall.stacks;a&&(a.changed=!1,delete a.alreadyChanged)}function f(){const a=this.options.stackLabels;a&&a.enabled&&this.waterfall.stacks&&this.waterfall.renderStackTotals()}function k(){let a=this.axes,b=this.series,d=b.length;for(;d--;)b[d].options.stacking&&
(a.forEach(function(a){a.isXAxis||(a.waterfall.stacks.changed=!0)}),d=0)}function x(){this.waterfall||(this.waterfall=new v(this))}class v{constructor(a){this.axis=a;this.stacks={changed:!1}}renderStackTotals(){const b=this.axis,d=b.waterfall.stacks,e=b.stacking&&b.stacking.stackTotalGroup,c=new a(b,b.options.stackLabels||{},!1,0,void 0);this.dummyStackItem=c;e&&h(d,function(b){h(b,function(b,d){c.total=b.stackTotal;c.x=+d;b.label&&(c.label=b.label);a.prototype.render.call(c,e);b.label=c.label;delete c.label})});
c.total=null}}b.Composition=v;b.compose=function(a,b){d(a,"init",x);d(a,"afterBuildStacks",e);d(a,"afterRender",f);d(b,"beforeRedraw",k)}})(f||(f={}));return f});r(b,"Series/Waterfall/WaterfallPoint.js",[b["Series/Column/ColumnSeries.js"],b["Core/Series/Point.js"],b["Core/Utilities.js"]],function(a,b,e){const {isNumber:d}=e;class f extends a.prototype.pointClass{constructor(){super(...arguments);this.series=this.options=void 0}getClassName(){let a=b.prototype.getClassName.call(this);this.isSum?a+=
" highcharts-sum":this.isIntermediateSum&&(a+=" highcharts-intermediate-sum");return a}isValid(){return d(this.y)||this.isSum||!!this.isIntermediateSum}}return f});r(b,"Series/Waterfall/WaterfallSeries.js",[b["Core/Axis/Axis.js"],b["Core/Chart/Chart.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"],b["Core/Axis/WaterfallAxis.js"],b["Series/Waterfall/WaterfallPoint.js"]],function(a,b,e,h,f,k){const {seriesTypes:{column:d,line:t}}=e,{addEvent:r,arrayMax:x,arrayMin:v,correctFloat:n,extend:B,
isNumber:g,merge:c,objectEach:l,pick:I}=h;class A extends d{constructor(){super(...arguments);this.yData=this.yAxis=this.xData=this.stackKey=this.stackedYPos=this.stackedYNeg=this.points=this.options=this.data=this.chart=void 0}generatePoints(){d.prototype.generatePoints.apply(this);for(let a=0,b=this.points.length;a<b;a++){const b=this.points[a],c=this.processedYData[a];g(c)&&(b.isIntermediateSum||b.isSum)&&(b.y=n(c))}}processData(a){let b=this.options,c=this.yData,d=b.data,e,g=c.length,f=b.threshold||
0,h,k,l,q,u,F;for(F=k=h=l=q=0;F<g;F++)u=c[F],e=d&&d[F]?d[F]:{},"sum"===u||e.isSum?c[F]=n(k):"intermediateSum"===u||e.isIntermediateSum?(c[F]=n(h),h=0):(k+=u,h+=u),l=Math.min(k,l),q=Math.max(k,q);super.processData.call(this,a);b.stacking||(this.dataMin=l+f,this.dataMax=q)}toYData(a){return a.isSum?"sum":a.isIntermediateSum?"intermediateSum":a.y}updateParallelArrays(a,b){super.updateParallelArrays.call(this,a,b);if("sum"===this.yData[0]||"intermediateSum"===this.yData[0])this.yData[0]=null}pointAttribs(a,
b){const c=this.options.upColor;c&&!a.options.color&&g(a.y)&&(a.color=0<a.y?c:void 0);a=d.prototype.pointAttribs.call(this,a,b);delete a.dashstyle;return a}getGraphPath(){return[["M",0,0]]}getCrispPath(){let a=this.data.filter(a=>g(a.y)),b=this.yAxis,c=a.length,d=Math.round(this.graph.strokeWidth())%2/2,e=Math.round(this.borderWidth)%2/2,f=this.xAxis.reversed,h=this.yAxis.reversed,k=this.options.stacking,l=[];for(let m=1;m<c;m++){if(!this.options.connectNulls&&!g(this.data[a[m].index-1].y))continue;
var n=a[m].box,q=a[m-1];const c=q.y||0,w=a[m-1].box;if(!n||!w)continue;var u=b.waterfall.stacks[this.stackKey];const p=0<c?-w.height:0;u&&w&&n&&(u=u[m-1],q=k?Math.round(b.translate(u.connectorThreshold,!1,!0,!1,!0)+(h?p:0))-d:w.y+q.minPointLengthOffset+e-d,l.push(["M",(w.x||0)+(f?0:w.width||0),q],["L",(n.x||0)+(f?n.width||0:0),q]));w&&l.length&&(!k&&0>c&&!h||0<c&&h)&&((n=l[l.length-2])&&"number"===typeof n[2]&&(n[2]+=w.height||0),(n=l[l.length-1])&&"number"===typeof n[2]&&(n[2]+=w.height||0))}return l}drawGraph(){t.prototype.drawGraph.call(this);
this.graph&&this.graph.attr({d:this.getCrispPath()})}setStackedPoints(){function a(a,b,c,d){if(k){if(t)for(c;c<t;c++)k.stackState[c]+=d;else k.stackState[0]=a,t=k.stackState.length;k.stackState.push(k.stackState[t-1]+b)}}let b=this.options,c=this.yAxis.waterfall.stacks,d=b.threshold||0,e=d,g=e,f=this.stackKey,h=this.xData,l=h.length,k,n,q,v,t;let x,r,K;var A;let B;this.yAxis.stacking.usePercentage=!1;n=q=v=e;if(this.visible||!this.chart.options.chart.ignoreHiddenSeries){B=c.changed;(A=c.alreadyChanged)&&
0>A.indexOf(f)&&(B=!0);c[f]||(c[f]={});if(A=c[f])for(let c=0;c<l;c++){var y=h[c];if(!A[y]||B)A[y]={negTotal:0,posTotal:0,stackTotal:0,threshold:0,stateIndex:0,stackState:[],label:B&&A[y]?A[y].label:void 0};k=A[y];K=this.yData[c];0<=K?k.posTotal+=K:k.negTotal+=K;r=b.data[c];y=k.absolutePos=k.posTotal;x=k.absoluteNeg=k.negTotal;k.stackTotal=y+x;t=k.stackState.length;r&&r.isIntermediateSum?(a(v,q,0,v),v=q,q=d,e^=g,g^=e,e^=g):r&&r.isSum?(a(d,n,t,0),e=d):(a(e,K,0,n),r&&(n+=K,q+=K));k.stateIndex++;k.threshold=
e;e+=k.stackTotal}c.changed=!1;c.alreadyChanged||(c.alreadyChanged=[]);c.alreadyChanged.push(f)}}getExtremes(){let a=this.options.stacking;let b,c;if(a){var d=this.yAxis;d=d.waterfall.stacks;b=this.stackedYNeg=[];c=this.stackedYPos=[];"overlap"===a?l(d[this.stackKey],function(a){b.push(v(a.stackState));c.push(x(a.stackState))}):l(d[this.stackKey],function(a){b.push(a.negTotal+a.threshold);c.push(a.posTotal+a.threshold)});return{dataMin:v(b),dataMax:x(c)}}return{dataMin:this.dataMin,dataMax:this.dataMax}}}
A.defaultOptions=c(d.defaultOptions,{dataLabels:{inside:!0},lineWidth:1,lineColor:"#333333",dashStyle:"Dot",borderColor:"#333333",states:{hover:{lineWidthPlus:0}}});r(A,"afterColumnTranslate",function(){const {options:a,points:b,yAxis:d}=this,e=I(a.minPointLength,5),f=e/2,h=a.threshold||0,k=a.stacking,l=d.waterfall.stacks[this.stackKey];let n=h,q=h;for(let a=0;a<b.length;a++){const m=b[a];var v=this.processedYData[a];const p=B({x:0,y:0,width:0,height:0},m.shapeArgs||{});m.box=p;var u=[0,v],t=m.y||
0;if(k){if(l){u=l[a];if("overlap"===k){var r=u.stackState[u.stateIndex--];r=0<=t?r:r-t;Object.hasOwnProperty.call(u,"absolutePos")&&delete u.absolutePos;Object.hasOwnProperty.call(u,"absoluteNeg")&&delete u.absoluteNeg}else 0<=t?(r=u.threshold+u.posTotal,u.posTotal-=t):(r=u.threshold+u.negTotal,u.negTotal-=t,r-=t),!u.posTotal&&g(u.absolutePos)&&Object.hasOwnProperty.call(u,"absolutePos")&&(u.posTotal=u.absolutePos,delete u.absolutePos),!u.negTotal&&g(u.absoluteNeg)&&Object.hasOwnProperty.call(u,"absoluteNeg")&&
(u.negTotal=u.absoluteNeg,delete u.absoluteNeg);m.isSum||(u.connectorThreshold=u.threshold+u.stackTotal);d.reversed?v=0<=t?r-t:r+t:(v=r,r-=t);m.below=v<=h;p.y=d.translate(v,!1,!0,!1,!0);p.height=Math.abs(p.y-d.translate(r,!1,!0,!1,!0));if(r=d.waterfall.dummyStackItem)r.x=a,r.label=l[a].label,r.setOffset(this.pointXOffset||0,this.barW||0,this.stackedYNeg[a],this.stackedYPos[a],void 0,this.xAxis)}}else r=Math.max(q,q+t)+u[0],p.y=d.translate(r,!1,!0,!1,!0),m.isSum?(p.y=d.translate(u[1],!1,!0,!1,!0),
p.height=Math.min(d.translate(u[0],!1,!0,!1,!0),d.len)-p.y,m.below=u[1]<=h):m.isIntermediateSum?(0<=t?(v=u[1]+n,r=n):(v=n,r=u[1]+n),d.reversed&&(v^=r,r^=v,v^=r),p.y=d.translate(v,!1,!0,!1,!0),p.height=Math.abs(p.y-Math.min(d.translate(r,!1,!0,!1,!0),d.len)),n+=u[1],m.below=v<=h):(p.height=0<v?d.translate(q,!1,!0,!1,!0)-p.y:d.translate(q,!1,!0,!1,!0)-d.translate(q-v,!1,!0,!1,!0),q+=v,m.below=q<h),0>p.height&&(p.y+=p.height,p.height*=-1);m.plotY=p.y=Math.round(p.y||0)-this.borderWidth%2/2;p.height=
Math.max(Math.round(p.height||0),.001);m.yBottom=p.y+p.height;p.height<=e&&!m.isNull?(p.height=e,p.y-=f,m.plotY=p.y,m.minPointLengthOffset=0>t?-f:f):(m.isNull&&(p.width=0),m.minPointLengthOffset=0);t=m.plotY+(m.negative?p.height:0);m.below&&(m.plotY+=p.height);m.tooltipPos&&(this.chart.inverted?m.tooltipPos[0]=d.len-t:m.tooltipPos[1]=t);m.isInside=this.isPointInside(m);c(!0,m.shapeArgs,p)}},{order:2});B(A.prototype,{getZonesGraphs:t.prototype.getZonesGraphs,pointValKey:"y",showLine:!0,pointClass:k});
e.registerSeriesType("waterfall",A);f.compose(a,b);"";return A});r(b,"Core/Axis/RadialAxis.js",[b["Core/Axis/AxisDefaults.js"],b["Core/Defaults.js"],b["Core/Globals.js"],b["Core/Utilities.js"]],function(a,b,e,h){const {defaultOptions:d}=b,{noop:k}=e,{addEvent:q,correctFloat:r,defined:E,extend:x,fireEvent:v,merge:n,pick:B,relativeLength:g,wrap:c}=h;var l;(function(b){function e(){this.autoConnect=this.isCircular&&"undefined"===typeof B(this.userMax,this.options.max)&&r(this.endAngleRad-this.startAngleRad)===
r(2*Math.PI);!this.isCircular&&this.chart.inverted&&this.max++;this.autoConnect&&(this.max+=this.categories&&1||this.pointRange||this.closestPointRange||0)}function f(){return()=>{if(this.isRadial&&this.tickPositions&&this.options.labels&&!0!==this.options.labels.allowOverlap)return this.tickPositions.map(a=>this.ticks[a]&&this.ticks[a].label).filter(a=>!!a)}}function l(){return k}function t(a,b,c){const d=this.pane.center;let e=a.value;let g;if(this.isCircular){if(E(e))a.point&&(f=a.point.shapeArgs||
{},f.start&&(e=this.chart.inverted?this.translate(a.point.rectPlotY,!0):a.point.x));else{var f=a.chartX||0;g=a.chartY||0;e=this.translate(Math.atan2(g-c,f-b)-this.startAngleRad,!0)}a=this.getPosition(e);f=a.x;g=a.y}else E(e)||(f=a.chartX,g=a.chartY),E(f)&&E(g)&&(c=d[1]+this.chart.plotTop,e=this.translate(Math.min(Math.sqrt(Math.pow(f-b,2)+Math.pow(g-c,2)),d[2]/2)-d[3]/2,!0));return[e,f||0,g||0]}function z(a,b,c){a=this.pane.center;const d=this.chart,e=this.left||0,g=this.top||0;let f=B(b,a[2]/2-this.offset);
"undefined"===typeof c&&(c=this.horiz?0:this.center&&-this.center[3]/2);c&&(f+=c);this.isCircular||"undefined"!==typeof b?(b=this.chart.renderer.symbols.arc(e+a[0],g+a[1],f,f,{start:this.startAngleRad,end:this.endAngleRad,open:!0,innerR:0}),b.xBounds=[e+a[0]],b.yBounds=[g+a[1]-f]):(b=this.postTranslate(this.angleRad,f),b=[["M",this.center[0]+d.plotLeft,this.center[1]+d.plotTop],["L",b.x,b.y]]);return b}function I(){this.constructor.prototype.getOffset.call(this);this.chart.axisOffset[this.side]=0}
function M(a,b,c){const d=this.chart;var e=a=>{if("string"===typeof a){let b=parseInt(a,10);G.test(a)&&(b=b*h/100);return b}return a};const g=this.center;var f=this.startAngleRad;const h=g[2]/2;var k=Math.min(this.offset,0),l=this.left||0;const y=this.top||0,G=/%$/;var O=this.isCircular;let n,m=B(e(c.outerRadius),h),C=e(c.innerRadius);e=B(e(c.thickness),10);"polygon"===this.options.gridLineInterpolation?k=this.getPlotLinePath({value:a}).concat(this.getPlotLinePath({value:b,reverse:!0})):(a=Math.max(a,
this.min),b=Math.min(b,this.max),a=this.translate(a),b=this.translate(b),O||(m=a||0,C=b||0),"circle"!==c.shape&&O?(c=f+(a||0),f+=b||0):(c=-Math.PI/2,f=1.5*Math.PI,n=!0),m-=k,k=d.renderer.symbols.arc(l+g[0],y+g[1],m,m,{start:Math.min(c,f),end:Math.max(c,f),innerR:B(C,m-(e-k)),open:n}),O&&(O=(f+c)/2,l=l+g[0]+g[2]/2*Math.cos(O),k.xBounds=O>-Math.PI/2&&O<Math.PI/2?[l,d.plotWidth]:[0,l],k.yBounds=[y+g[1]+g[2]/2*Math.sin(O)],k.yBounds[0]+=O>-Math.PI&&0>O||O>Math.PI?-10:10));return k}function N(a){var b=
this.pane.center,c=this.chart;const d=c.inverted;var e=a.reverse,f=this.pane.options.background?this.pane.options.background[0]||this.pane.options.background:{};const h=f.innerRadius||"0%",k=f.outerRadius||"100%";var l=b[0]+c.plotLeft,y=b[1]+c.plotTop;const G=this.height,O=a.isCrosshair;f=b[3]/2;var m=a.value;let n;var C=this.getPosition(m);let L=C.x;C=C.y;O&&(C=this.getCrosshairPosition(a,l,y),m=C[0],L=C[1],C=C[2]);if(this.isCircular)m=Math.sqrt(Math.pow(L-l,2)+Math.pow(C-y,2)),e="string"===typeof h?
g(h,1):h/m,c="string"===typeof k?g(k,1):k/m,b&&f&&(f/=m,e<f&&(e=f),c<f&&(c=f)),b=[["M",l+e*(L-l),y-e*(y-C)],["L",L-(1-c)*(L-l),C+(1-c)*(y-C)]];else if((m=this.translate(m))&&(0>m||m>G)&&(m=0),"circle"===this.options.gridLineInterpolation)b=this.getLinePath(0,m,f);else if(b=[],c[d?"yAxis":"xAxis"].forEach(a=>{a.pane===this.pane&&(n=a)}),n)for(l=n.tickPositions,n.autoConnect&&(l=l.concat([l[0]])),e&&(l=l.slice().reverse()),m&&(m+=f),y=0;y<l.length;y++)f=n.getPosition(l[y],m),b.push(y?["L",f.x,f.y]:
["M",f.x,f.y]);return b}function p(a,b){a=this.translate(a);return this.postTranslate(this.isCircular?a:this.angleRad,B(this.isCircular?b:0>a?0:a,this.center[2]/2)-this.offset)}function m(){const a=this.center,b=this.chart,c=this.options.title;return{x:b.plotLeft+a[0]+(c.x||0),y:b.plotTop+a[1]-{high:.5,middle:.25,low:0}[c.align]*a[2]+(c.y||0)}}function D(a){a.beforeSetTickPositions=e;a.createLabelCollector=f;a.getCrosshairPosition=t;a.getLinePath=z;a.getOffset=I;a.getPlotBandPath=M;a.getPlotLinePath=
N;a.getPosition=p;a.getTitlePosition=m;a.postTranslate=S;a.setAxisSize=y;a.setAxisTranslation=G;a.setOptions=C}function J(){var a=this.chart,b=this.options,c=this.pane,d=c&&c.options;a.angular&&this.isXAxis||!c||!a.angular&&!a.polar||(a=2*Math.PI,c=(B(d.startAngle,0)-90)*Math.PI/180,d=(B(d.endAngle,B(d.startAngle,0)+360)-90)*Math.PI/180,this.angleRad=(b.angle||0)*Math.PI/180,this.startAngleRad=c,this.endAngleRad=d,this.offset=b.offset||0,b=(c%a+a)%a,d=(d%a+a)%a,b>Math.PI&&(b-=a),d>Math.PI&&(d-=a),
this.normalizedStartAngleRad=b,this.normalizedEndAngleRad=d)}function u(a){this.isRadial&&(a.align=void 0,a.preventDefault())}function F(){if(this.chart&&this.chart.labelCollectors){const a=this.labelCollector?this.chart.labelCollectors.indexOf(this.labelCollector):-1;0<=a&&this.chart.labelCollectors.splice(a,1)}}function R(b){const c=this.chart,d=c.inverted,e=c.angular,f=c.polar,g=this.isXAxis,h=this.coll,y=e&&g;b=b.userOptions.pane||0;b=this.pane=c.pane&&c.pane[b];let G;if("colorAxis"===h)this.isRadial=
!1;else{if(e){if(y?(this.isHidden=!0,this.createLabelCollector=l,this.getOffset=k,this.render=this.redraw=T,this.setTitle=this.setCategories=this.setScale=k):D(this),G=!g)this.defaultPolarOptions=X}else f&&(D(this),this.defaultPolarOptions=(G=this.horiz)?Y:n("xAxis"===h?a.defaultXAxisOptions:a.defaultYAxisOptions,Z),d&&"yAxis"===h&&(this.defaultPolarOptions.stackLabels=a.defaultYAxisOptions.stackLabels,this.defaultPolarOptions.reversedStacks=!0));e||f?(this.isRadial=!0,this.labelCollector||(this.labelCollector=
this.createLabelCollector()),this.labelCollector&&c.labelCollectors.push(this.labelCollector)):this.isRadial=!1;b&&G&&(b.axis=this);this.isCircular=G}}function U(){this.isRadial&&this.beforeSetTickPositions()}function V(a){const b=this.label;if(b){var c=this.axis,d=b.getBBox(),e=c.options.labels,f=(c.translate(this.pos)+c.startAngleRad+Math.PI/2)/Math.PI*180%360,h=Math.round(f),k=E(e.y)?0:.3*-d.height,l=e.y,y=20,G=e.align,m="end",C=0>h?h+360:h,n=C,L=0,p=0;if(c.isRadial){var q=c.getPosition(this.pos,
c.center[2]/2+g(B(e.distance,-25),c.center[2]/2,-c.center[2]/2));"auto"===e.rotation?b.attr({rotation:f}):E(l)||(l=c.chart.renderer.fontMetrics(b).b-d.height/2);E(G)||(c.isCircular?(d.width>c.len*c.tickInterval/(c.max-c.min)&&(y=0),G=f>y&&f<180-y?"left":f>180+y&&f<360-y?"right":"center"):G="center",b.attr({align:G}));if("auto"===G&&2===c.tickPositions.length&&c.isCircular){90<C&&180>C?C=180-C:270<C&&360>=C&&(C=540-C);180<n&&360>=n&&(n=360-n);if(c.pane.options.startAngle===h||c.pane.options.startAngle===
h+360||c.pane.options.startAngle===h-360)m="start";G=-90<=h&&90>=h||-360<=h&&-270>=h||270<=h&&360>=h?"start"===m?"right":"left":"start"===m?"left":"right";70<n&&110>n&&(G="center");15>C||180<=C&&195>C?L=.3*d.height:15<=C&&35>=C?L="start"===m?0:.75*d.height:195<=C&&215>=C?L="start"===m?.75*d.height:0:35<C&&90>=C?L="start"===m?.25*-d.height:d.height:215<C&&270>=C&&(L="start"===m?d.height:.25*-d.height);15>n?p="start"===m?.15*-d.height:.15*d.height:165<n&&180>=n&&(p="start"===m?.15*d.height:.15*-d.height);
b.attr({align:G});b.translate(p,L+k)}a.pos.x=q.x+(e.x||0);a.pos.y=q.y+(l||0)}}}function K(a){this.axis.getPosition&&x(a.pos,this.axis.getPosition(this.pos))}function S(a,b){const c=this.chart,d=this.center;a=this.startAngleRad+a;return{x:c.plotLeft+d[0]+Math.cos(a)*b,y:c.plotTop+d[1]+Math.sin(a)*b}}function T(){this.isDirty=!1}function y(){let a,b;this.constructor.prototype.setAxisSize.call(this);this.isRadial&&(this.pane.updateCenter(this),a=this.center=this.pane.center.slice(),this.isCircular?this.sector=
this.endAngleRad-this.startAngleRad:(b=this.postTranslate(this.angleRad,a[3]/2),a[0]=b.x-this.chart.plotLeft,a[1]=b.y-this.chart.plotTop),this.len=this.width=this.height=(a[2]-a[3])*B(this.sector,1)/2)}function G(){this.constructor.prototype.setAxisTranslation.call(this);this.center&&(this.transA=this.isCircular?(this.endAngleRad-this.startAngleRad)/(this.max-this.min||1):(this.center[2]-this.center[3])/2/(this.max-this.min||1),this.minPixelPadding=this.isXAxis?this.transA*this.minPointOffset:0)}
function C(a){a=this.options=n(this.constructor.defaultOptions,this.defaultPolarOptions,d[this.coll],a);a.plotBands||(a.plotBands=[]);v(this,"afterSetOptions")}function W(a,b,c,d,e,f,g){const h=this.axis;h.isRadial?(a=h.getPosition(this.pos,h.center[2]/2+d),b=["M",b,c,"L",a.x,a.y]):b=a.call(this,b,c,d,e,f,g);return b}const L=[],Y={gridLineWidth:1,labels:{align:void 0,x:0,y:void 0,style:{textOverflow:"none"}},maxPadding:0,minPadding:0,showLastLabel:!1,tickLength:0},X={labels:{align:"center",distance:-25,
x:0,y:void 0},minorGridLineWidth:0,minorTickInterval:"auto",minorTickLength:10,minorTickPosition:"inside",minorTickWidth:1,tickLength:10,tickPosition:"inside",tickWidth:2,title:{rotation:0},zIndex:2},Z={gridLineInterpolation:"circle",gridLineWidth:1,labels:{align:"right",x:-3,y:-2},showLastLabel:!1,title:{x:4,text:null,rotation:90}};b.compose=function(a,b){h.pushUnique(L,a)&&(q(a,"afterInit",J),q(a,"autoLabelAlign",u),q(a,"destroy",F),q(a,"init",R),q(a,"initialAxisTranslation",U));h.pushUnique(L,
b)&&(q(b,"afterGetLabelPosition",V),q(b,"afterGetPosition",K),c(b.prototype,"getMarkPath",W));return a}})(l||(l={}));return l});r(b,"Series/PolarComposition.js",[b["Core/Animation/AnimationUtilities.js"],b["Core/Globals.js"],b["Core/Series/Series.js"],b["Extensions/Pane.js"],b["Core/Axis/RadialAxis.js"],b["Core/Utilities.js"]],function(a,b,e,h,f,k){function d(a,b,c,e){var f=e?1:0;var g=0<=b&&b<=a.length-1?b:0>b?a.length-1+b:0;b=0>g-1?a.length-(1+f):g-1;var h=a[b];f=a[g+1>a.length-1?f:g+1];var k=h.plotY;
var l=f.plotX;var y=f.plotY;f=a[g].plotX;g=a[g].plotY;h=(1.5*f+h.plotX)/2.5;k=(1.5*g+k)/2.5;l=(1.5*f+l)/2.5;var G=(1.5*g+y)/2.5;y=Math.sqrt(Math.pow(h-f,2)+Math.pow(k-g,2));const m=Math.sqrt(Math.pow(l-f,2)+Math.pow(G-g,2));h=Math.atan2(k-g,h-f);G=Math.PI/2+(h+Math.atan2(G-g,l-f))/2;Math.abs(h-G)>Math.PI/2&&(G-=Math.PI);h=f+Math.cos(G)*y;k=g+Math.sin(G)*y;l=f+Math.cos(Math.PI+G)*m;G=g+Math.sin(Math.PI+G)*m;f={rightContX:l,rightContY:G,leftContX:h,leftContY:k,plotX:f,plotY:g};c&&(f.prevPointCont=d(a,
b,!1,e));return f}function r(){(this.pane||[]).forEach(a=>{a.render()})}function E(a){const b=a.args[0].xAxis,c=a.args[0].yAxis;a=a.args[0].chart;b&&c&&("polygon"===c.gridLineInterpolation?(b.startOnTick=!0,b.endOnTick=!0):"polygon"===b.gridLineInterpolation&&a.inverted&&(c.startOnTick=!0,c.endOnTick=!0))}function x(){this.pane||(this.pane=[]);this.options.pane=U(this.options.pane);this.options.pane.forEach(a=>{new h(a,this)},this)}function v(a){var b=a.args.marker,c=this.chart.xAxis[0],d=this.chart.yAxis[0],
e=this.chart.inverted;const f=e?d:c;c=e?c:d;if(this.chart.polar){a.preventDefault();d=(b.attr?b.attr("start"):b.start)-f.startAngleRad;e=b.attr?b.attr("r"):b.r;let g=(b.attr?b.attr("end"):b.end)-f.startAngleRad;b=b.attr?b.attr("innerR"):b.innerR;a.result.x=d+f.pos;a.result.width=g-d;a.result.y=c.len+c.pos-b;a.result.height=b-e}}function n(a){var b=this.chart;if(b.polar&&b.hoverPane&&b.hoverPane.axis){a.preventDefault();var c=b.hoverPane.center,d=this.mouseDownX||0;const G=this.mouseDownY||0;var e=
a.args.chartY;const C=a.args.chartX;var f=2*Math.PI,g=b.hoverPane.axis.startAngleRad,h=b.hoverPane.axis.endAngleRad,k=b.inverted?b.xAxis[0]:b.yAxis[0];const q={};var m="arc";q.x=c[0]+b.plotLeft;q.y=c[1]+b.plotTop;if(this.zoomHor){var y=0<g?h-g:Math.abs(g)+Math.abs(h),n=Math.atan2(G-b.plotTop-c[1],d-b.plotLeft-c[0])-g,p=Math.atan2(e-b.plotTop-c[1],C-b.plotLeft-c[0])-g;q.r=c[2]/2;q.innerR=c[3]/2;0>=n&&(n+=f);0>=p&&(p+=f);p<n&&(p=[n,n=p][0]);y<f&&g+p>h+(f-y)/2&&(p=n,n=0>=g?g:0);f=q.start=Math.max(n+
g,g);y=q.end=Math.min(p+g,h);if("polygon"===k.options.gridLineInterpolation){m=b.hoverPane.axis;p=f-m.startAngleRad+m.pos;n=y-f;f=k.getPlotLinePath({value:k.max});y=m.toValue(p);p=m.toValue(p+n);if(y<m.getExtremes().min){const {min:a,max:b}=m.getExtremes();y=b-(a-y)}if(p<m.getExtremes().min){const {min:a,max:b}=m.getExtremes();p=b-(a-p)}p<y&&(p=[y,y=p][0]);f=l(f,y,p,m);f.push(["L",c[0]+b.plotLeft,b.plotTop+c[1]]);q.d=f;m="path"}}this.zoomVert&&(p=b.inverted?b.xAxis[0]:b.yAxis[0],d=Math.sqrt(Math.pow(d-
b.plotLeft-c[0],2)+Math.pow(G-b.plotTop-c[1],2)),e=Math.sqrt(Math.pow(C-b.plotLeft-c[0],2)+Math.pow(e-b.plotTop-c[1],2)),e<d&&(d=[e,e=d][0]),e>c[2]/2&&(e=c[2]/2),d<c[3]/2&&(d=c[3]/2),this.zoomHor||(q.start=g,q.end=h),q.r=e,q.innerR=d,"polygon"===p.options.gridLineInterpolation&&(c=p.toValue(p.len+p.pos-d),g=p.toValue(p.len+p.pos-e),c=p.getPlotLinePath({value:g}).concat(p.getPlotLinePath({value:c,reverse:!0})),q.d=c,m="path"));this.zoomHor&&this.zoomVert&&"polygon"===k.options.gridLineInterpolation&&
(c=b.hoverPane.axis,k=q.start||0,g=k-c.startAngleRad+c.pos,h=(q.end||0)-k,k=c.toValue(g),c=c.toValue(g+h),q.d instanceof Array&&(g=q.d.slice(0,q.d.length/2),h=q.d.slice(q.d.length/2,q.d.length),h=[...h].reverse(),b=b.hoverPane.axis,g=l(g,k,c,b),(h=l(h,k,c,b))&&(h[0][0]="L"),h=[...h].reverse(),q.d=g.concat(h),m="path"));a.attrs=q;a.shapeType=m}}function B(){const a=this.chart;a.polar&&(this.polar=new T(this),a.inverted&&(this.isRadialSeries=!0,this.is("column")&&(this.isRadialBar=!0)))}function g(){if(this.chart.polar&&
this.xAxis){const {xAxis:a,yAxis:d}=this,e=this.chart;(this.kdByAngle=e.tooltip&&e.tooltip.shared)?this.searchPoint=c:this.options.findNearestPointBy="xy";const f=this.points;let g=f.length;for(;g--;)this.is("column")||this.is("columnrange")||this.polar.toXY(f[g]),e.hasParallelCoordinates||this.yAxis.reversed||(F(f[g].y,Number.MIN_VALUE)<d.min||f[g].x<a.min||f[g].x>a.max?(f[g].isNull=!0,f[g].plotY=NaN):f[g].isNull=f[g].isValid&&!f[g].isValid());this.hasClipCircleSetter||(this.hasClipCircleSetter=
!!this.eventsToUnbind.push(p(this,"afterRender",function(){if(e.polar){var a=this.yAxis.pane.center;if(this.clipCircle)this.clipCircle.animate({x:a[0],y:a[1],r:a[2]/2,innerR:a[3]/2});else{{var c=e.renderer;var d=a[0],f=a[1],g=a[2]/2,h=a[3]/2;a=V();const b=c.createElement("clipPath").attr({id:a}).add(c.defs);c=h?c.arc(d,f,g,h,0,2*Math.PI).add(b):c.circle(d,f,g).add(b);c.id=a;c.clipPath=b}this.clipCircle=c}this.group.clip(this.clipCircle);this.setClip=b.noop}})))}}function c(a){const b=this.chart;var c=
this.xAxis;c=c.pane&&c.pane.center;return this.searchKDTree({clientX:180+-180/Math.PI*Math.atan2(a.chartX-(c&&c[0]||0)-b.plotLeft,a.chartY-(c&&c[1]||0)-b.plotTop)})}function l(a,b,c,d){const e=d.tickInterval;d=d.tickPositions;let f=D(d,a=>a>=c),g=D([...d].reverse(),a=>a<=b);m(f)||(f=d[d.length-1]);m(g)||(g=d[0],f+=e,a[0][0]="L",a.unshift(a[a.length-3]));a=a.slice(d.indexOf(g),d.indexOf(f)+1);a[0][0]="M";return a}function I(a,b){return D(this.pane||[],function(a){return a.options.id===b})||a.call(this,
b)}function A(a,b,c,d,f,g){const h=this.chart;var k=F(d.inside,!!this.options.stacking);h.polar?(a=b.rectPlotX/Math.PI*180,h.inverted?(this.forceDL=h.isInsidePlot(b.plotX,b.plotY),k&&b.shapeArgs?(k=b.shapeArgs,k=this.yAxis.postTranslate(((k.start||0)+(k.end||0))/2-this.xAxis.startAngleRad,b.barX+b.pointWidth/2),f=u(f,{x:k.x-h.plotLeft,y:k.y-h.plotTop})):b.tooltipPos&&(f=u(f,{x:b.tooltipPos[0],y:b.tooltipPos[1]})),d.align=F(d.align,"center"),d.verticalAlign=F(d.verticalAlign,"middle")):(null===d.align&&
(d.align=20<a&&160>a?"left":200<a&&340>a?"right":"center"),null===d.verticalAlign&&(d.verticalAlign=45>a||315<a?"bottom":135<a&&225>a?"top":"middle")),e.prototype.alignDataLabel.call(this,b,c,d,f,g),this.isRadialBar&&b.shapeArgs&&b.shapeArgs.start===b.shapeArgs.end?c.hide():c.show()):a.call(this,b,c,d,f,g)}function H(){const a=this.options,b=a.stacking,c=this.chart;var d=this.xAxis;const e=this.yAxis,f=e.reversed,g=e.center,h=d.startAngleRad,l=d.endAngleRad-h;let n=0,p,q,v,r=0;var t=0;if(d.isRadial){d=
this.points;p=d.length;q=e.translate(e.min);v=e.translate(e.max);var u=a.threshold||0;c.inverted&&J(u)&&(n=e.translate(u),m(n)&&(0>n?n=0:n>l&&(n=l),this.translatedThreshold=n+h));for(;p--;){u=d[p];var w=u.barX;var z=u.x;var x=u.y;u.shapeType="arc";if(c.inverted){u.plotY=e.translate(x);b&&e.stacking?(x=e.stacking.stacks[(0>x?"-":"")+this.stackKey],this.visible&&x&&x[z]&&!u.isNull&&(t=x[z].points[this.getStackIndicator(void 0,z,this.index).key],r=e.translate(t[0]),t=e.translate(t[1]),m(r)&&(r=k.clamp(r,
0,l)))):(r=n,t=u.plotY);r>t&&(t=[r,r=t][0]);if(!f)if(r<q)r=q;else if(t>v)t=v;else{if(t<q||r>v)r=t=0}else if(t>q)t=q;else if(r<v)r=v;else if(r>q||t<v)r=t=l;e.min>e.max&&(r=t=f?l:0);r+=h;t+=h;g&&(u.barX=w+=g[3]/2);z=Math.max(w,0);x=Math.max(w+u.pointWidth,0);var A=a.borderRadius;A=R(("object"===typeof A?A.radius:A)||0,x-z);u.shapeArgs={x:g[0],y:g[1],r:x,innerR:z,start:r,end:t,borderRadius:A};u.opacity=r===t?0:void 0;u.plotY=(m(this.translatedThreshold)&&(r<this.translatedThreshold?r:t))-h}else r=w+
h,u.shapeArgs=this.polar.arc(u.yBottom,u.plotY,r,r+u.pointWidth),u.shapeArgs.borderRadius=0;this.polar.toXY(u);c.inverted?(w=e.postTranslate(u.rectPlotY,w+u.pointWidth/2),u.tooltipPos=[w.x-c.plotLeft,w.y-c.plotTop]):u.tooltipPos=[u.plotX,u.plotY];g&&(u.ttBelow=u.plotY>g[1])}}}function Q(a,b){const c=this;let d;if(this.chart.polar){b=b||this.points;for(let a=0;a<b.length;a++)if(!b[a].isNull){var e=a;break}!1!==this.options.connectEnds&&"undefined"!==typeof e&&(this.connectEnds=!0,b.splice(b.length,
0,b[e]),d=!0);b.forEach(a=>{"undefined"===typeof a.polarPlotY&&c.polar.toXY(a)})}e=a.apply(this,[].slice.call(arguments,1));d&&b.pop();return e}function w(a,b){const c=this.chart;let d={xAxis:[],yAxis:[]};c.polar?c.axes.forEach(a=>{if("colorAxis"!==a.coll){var e=a.isXAxis,f=a.center,g=b.chartX-f[0]-c.plotLeft;f=b.chartY-f[1]-c.plotTop;d[e?"xAxis":"yAxis"].push({axis:a,value:a.translate(e?Math.PI-Math.atan2(g,f):Math.sqrt(Math.pow(g,2)+Math.pow(f,2)),!0)})}}):d=a.call(this,b);return d}function z(a,
b){this.chart.polar||a.call(this,b)}function P(a,c){const d=this,e=this.chart,f=this.group,g=this.markerGroup,h=this.xAxis&&this.xAxis.center,k=e.plotLeft,l=e.plotTop;let m=this.options.animation,n,p,q,r,y;e.polar?d.isRadialBar?c||(d.startAngleRad=F(d.translatedThreshold,d.xAxis.startAngleRad),b.seriesTypes.pie.prototype.animate.call(d,c)):(m=N(m),d.is("column")?c||(n=h[3]/2,d.points.forEach(a=>{p=a.graphic;r=(q=a.shapeArgs)&&q.r;y=q&&q.innerR;p&&q&&(p.attr({r:n,innerR:n}),p.animate({r,innerR:y},
d.options.animation))})):c?(a={translateX:h[0]+k,translateY:h[1]+l,scaleX:.001,scaleY:.001},f.attr(a),g&&g.attr(a)):(a={translateX:k,translateY:l,scaleX:1,scaleY:1},f.animate(a,m),g&&g.animate(a,m))):a.call(this,c)}function M(a,b,c,e){this.chart.polar?e?(a=d(b,e,!0,this.connectEnds),b=a.prevPointCont&&a.prevPointCont.rightContX,c=a.prevPointCont&&a.prevPointCont.rightContY,a=["C",J(b)?b:a.plotX,J(c)?c:a.plotY,J(a.leftContX)?a.leftContX:a.plotX,J(a.leftContY)?a.leftContY:a.plotY,a.plotX,a.plotY]):
a=["M",c.plotX,c.plotY]:a=a.call(this,b,c,e);return a}const {animObject:N}=a,{addEvent:p,defined:m,find:D,isNumber:J,merge:u,pick:F,relativeLength:R,splat:U,uniqueKey:V,wrap:K}=k,S=[];class T{static compose(a,b,c,d,e,h,l,m,q){f.compose(a,e);k.pushUnique(S,b)&&(p(b,"afterDrawChartBox",r),p(b,"getAxes",x),p(b,"init",E),K(b.prototype,"get",I));k.pushUnique(S,c)&&(a=c.prototype,K(a,"getCoordinates",w),K(a,"pinch",z),p(c,"getSelectionMarkerAttrs",n),p(c,"getSelectionBox",v));k.pushUnique(S,d)&&(p(d,"afterInit",
B),p(d,"afterTranslate",g,{order:2}),p(d,"afterColumnTranslate",H,{order:4}),K(d.prototype,"animate",P));l&&k.pushUnique(S,l)&&(c=l.prototype,K(c,"alignDataLabel",A),K(c,"animate",P));m&&k.pushUnique(S,m)&&K(m.prototype,"getGraphPath",Q);q&&k.pushUnique(S,q)&&(m=q.prototype,K(m,"getPointSpline",M),h&&k.pushUnique(S,h)&&(h.prototype.getPointSpline=m.getPointSpline))}constructor(a){this.series=a}arc(a,b,c,d){const e=this.series,f=e.xAxis.center,g=e.yAxis.len,h=f[3]/2;b=g-b+h;a=g-F(a,g)+h;e.yAxis.reversed&&
(0>b&&(b=h),0>a&&(a=h));return{x:f[0],y:f[1],r:b,innerR:a,start:c,end:d}}toXY(a){var b=this.series;const c=b.chart,d=b.xAxis;var e=b.yAxis;const f=a.plotX,g=c.inverted,h=a.y;let k=a.plotY,l=g?f:e.len-k;g&&b&&!b.isRadialBar&&(a.plotY=k=J(h)?e.translate(h):0);a.rectPlotX=f;a.rectPlotY=k;e.center&&(l+=e.center[3]/2);J(k)&&(e=g?e.postTranslate(k,l):d.postTranslate(f,l),a.plotX=a.polarPlotX=e.x-c.plotLeft,a.plotY=a.polarPlotY=e.y-c.plotTop);b.kdByAngle?(b=(f/Math.PI*180+d.pane.options.startAngle)%360,
0>b&&(b+=360),a.clientX=b):a.clientX=a.plotX}}return T});r(b,"masters/highcharts-more.src.js",[b["Core/Globals.js"],b["Core/Series/SeriesRegistry.js"],b["Series/Bubble/BubbleSeries.js"],b["Series/PackedBubble/PackedBubbleSeries.js"],b["Series/PolarComposition.js"]],function(a,b,e,h,f){e.compose(a.Axis,a.Chart,a.Legend,a.Series);h.compose(a.Axis,a.Chart,a.Legend,a.Series);f.compose(a.Axis,a.Chart,a.Pointer,a.Series,a.Tick,b.seriesTypes.areasplinerange,b.seriesTypes.column,b.seriesTypes.line,b.seriesTypes.spline)})});//# sourceMappingURL=highcharts-more.js.map