/*
 Highcharts JS v11.1.0 (2023-08-20)

 3D features for Highcharts JS

 License: www.highcharts.com/license
*/
'use strict';(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/highcharts-3d",["highcharts"],function(D){a(D);a.Highcharts=D;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function D(a,z,t,C){a.hasOwnProperty(z)||(a[z]=C.apply(null,t),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:z,module:a[z]}})))}a=a?a._modules:
{};D(a,"Core/Math3D.js",[a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,z){function t(n,g,f,b){var c=g.options.chart.options3d,a=B(b,f?g.inverted:!1),k={x:g.plotWidth/2,y:g.plotHeight/2,z:c.depth/2,vd:B(c.depth,1)*B(c.viewDistance,0)},p=g.scale3d||1;b=m*c.beta*(a?-1:1);c=m*c.alpha*(a?-1:1);var l=Math.cos(c),y=Math.cos(-b),w=Math.sin(c),x=Math.sin(-b);f||(k.x+=g.plotLeft,k.y+=g.plotTop);return n.map(function(c){var g=(a?c.y:c.x)-k.x;var b=(a?c.x:c.y)-k.y;c=(c.z||0)-k.z;g={x:y*g-x*c,y:-w*x*
g+l*b-y*w*c,z:l*x*g+w*b+l*y*c};b=A(g,k,k.vd);b.x=b.x*p+k.x;b.y=b.y*p+k.y;b.z=g.z*p+k.z;return{x:a?b.y:b.x,y:a?b.x:b.y,z:b.z}})}function A(a,g,f){g=0<f&&f<Number.POSITIVE_INFINITY?f/(a.z+g.z+f):1;return{x:a.x*g,y:a.y*g}}function n(a){var g=0,f;for(f=0;f<a.length;f++){var b=(f+1)%a.length;g+=a[f].x*a[b].y-a[b].x*a[f].y}return g/2}var m=a.deg2rad,B=z.pick;return{perspective:t,perspective3D:A,pointCameraDistance:function(a,g){var f=g.options.chart.options3d,b=g.plotWidth/2;g=g.plotHeight/2;f=B(f.depth,
1)*B(f.viewDistance,0)+f.depth;return Math.sqrt(Math.pow(b-B(a.plotX,a.x),2)+Math.pow(g-B(a.plotY,a.y),2)+Math.pow(f-B(a.plotZ,a.z),2))},shapeArea:n,shapeArea3D:function(a,g,f){return n(t(a,g,f))}}});D(a,"Core/Renderer/SVG/SVGElement3D.js",[a["Core/Color/Color.js"],a["Core/Renderer/SVG/SVGElement.js"],a["Core/Utilities.js"]],function(a,z,t){var A=a.parse,n=t.defined;a=t.merge;var m=t.objectEach,B=t.pick,y={base:{initArgs:function(g){var a=this,b=a.renderer,c=b[a.pathType+"Path"](g),n=c.zIndexes;a.parts.forEach(function(g){var k=
{"class":"highcharts-3d-"+g,zIndex:n[g]||0};b.styledMode&&("top"===g?k.filter="url(#highcharts-brighter)":"side"===g&&(k.filter="url(#highcharts-darker)"));a[g]=b.path(c[g]).attr(k).add(a)});a.attr({"stroke-linejoin":"round",zIndex:n.group});a.originalDestroy=a.destroy;a.destroy=a.destroyParts;a.forcedSides=c.forcedSides},singleSetterForParts:function(g,a,b,c,n,k){var f={};c=[null,null,c||"attr",n,k];var l=b&&b.zIndexes;b?(l&&l.group&&this.attr({zIndex:l.group}),m(b,function(c,a){f[a]={};f[a][g]=
c;l&&(f[a].zIndex=b.zIndexes[a]||0)}),c[1]=f):(f[g]=a,c[0]=f);return this.processParts.apply(this,c)},processParts:function(a,f,b,c,n){var g=this;g.parts.forEach(function(k){f&&(a=B(f[k],!1));if(!1!==a)g[k][b](a,c,n)});return g},destroyParts:function(){this.processParts(null,null,"destroy");return this.originalDestroy()}}};y.cuboid=a(y.base,{parts:["front","top","side"],pathType:"cuboid",attr:function(a,f,b,c){if("string"===typeof a&&"undefined"!==typeof f){var g=a;a={};a[g]=f}return a.shapeArgs||
n(a.x)?this.singleSetterForParts("d",null,this.renderer[this.pathType+"Path"](a.shapeArgs||a)):z.prototype.attr.call(this,a,void 0,b,c)},animate:function(a,f,b){if(n(a.x)&&n(a.y)){a=this.renderer[this.pathType+"Path"](a);var c=a.forcedSides;this.singleSetterForParts("d",null,a,"animate",f,b);this.attr({zIndex:a.zIndexes.group});c!==this.forcedSides&&(this.forcedSides=c,this.renderer.styledMode||y.cuboid.fillSetter.call(this,this.fill))}else z.prototype.animate.call(this,a,f,b);return this},fillSetter:function(a){this.forcedSides=
this.forcedSides||[];this.singleSetterForParts("fill",null,{front:a,top:A(a).brighten(0<=this.forcedSides.indexOf("top")?0:.1).get(),side:A(a).brighten(0<=this.forcedSides.indexOf("side")?0:-.1).get()});this.color=this.fill=a;return this}});return y});D(a,"Core/Renderer/SVG/SVGRenderer3D.js",[a["Core/Animation/AnimationUtilities.js"],a["Core/Color/Color.js"],a["Core/Globals.js"],a["Core/Math3D.js"],a["Core/Renderer/SVG/SVGElement.js"],a["Core/Renderer/SVG/SVGElement3D.js"],a["Core/Renderer/SVG/SVGRenderer.js"],
a["Core/Utilities.js"]],function(a,z,t,C,n,m,B,y){var g=this&&this.__extends||function(){function a(h,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,e){a.__proto__=e}||function(a,e){for(var v in e)Object.prototype.hasOwnProperty.call(e,v)&&(a[v]=e[v])};return a(h,c)}return function(h,c){function b(){this.constructor=h}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");a(h,c);h.prototype=null===c?Object.create(c):
(b.prototype=c.prototype,new b)}}(),f=a.animObject,b=z.parse,c=t.charts,E=t.deg2rad,k=C.perspective,p=C.shapeArea,l=y.defined,F=y.extend,w=y.merge,x=y.pick,A=Math.cos,H=Math.sin,J=Math.PI,L=4*(Math.sqrt(2)-1)/3/(J/2);return function(a){function h(){return null!==a&&a.apply(this,arguments)||this}g(h,a);h.compose=function(a){a=a.prototype;var c=h.prototype;a.elements3d=m;a.arc3d=c.arc3d;a.arc3dPath=c.arc3dPath;a.cuboid=c.cuboid;a.cuboidPath=c.cuboidPath;a.element3d=c.element3d;a.face3d=c.face3d;a.polyhedron=
c.polyhedron;a.toLinePath=c.toLinePath;a.toLineSegments=c.toLineSegments};h.curveTo=function(a,c,e,v,d,u,G,q){var h=[],b=u-d;return u>d&&u-d>Math.PI/2+.0001?(h=h.concat(this.curveTo(a,c,e,v,d,d+Math.PI/2,G,q)),h=h.concat(this.curveTo(a,c,e,v,d+Math.PI/2,u,G,q))):u<d&&d-u>Math.PI/2+.0001?(h=h.concat(this.curveTo(a,c,e,v,d,d-Math.PI/2,G,q)),h=h.concat(this.curveTo(a,c,e,v,d-Math.PI/2,u,G,q))):[["C",a+e*Math.cos(d)-e*L*b*Math.sin(d)+G,c+v*Math.sin(d)+v*L*b*Math.cos(d)+q,a+e*Math.cos(u)+e*L*b*Math.sin(u)+
G,c+v*Math.sin(u)-v*L*b*Math.cos(u)+q,a+e*Math.cos(u)+G,c+v*Math.sin(u)+q]]};h.prototype.toLinePath=function(a,c){var e=[];a.forEach(function(a){e.push(["L",a.x,a.y])});a.length&&(e[0][0]="M",c&&e.push(["Z"]));return e};h.prototype.toLineSegments=function(a){var c=[],e=!0;a.forEach(function(a){c.push(e?["M",a.x,a.y]:["L",a.x,a.y]);e=!e});return c};h.prototype.face3d=function(a){var h=this,e=this.createElement("path");e.vertexes=[];e.insidePlotArea=!1;e.enabled=!0;e.attr=function(e){if("object"===
typeof e&&(l(e.enabled)||l(e.vertexes)||l(e.insidePlotArea))){this.enabled=x(e.enabled,this.enabled);this.vertexes=x(e.vertexes,this.vertexes);this.insidePlotArea=x(e.insidePlotArea,this.insidePlotArea);delete e.enabled;delete e.vertexes;delete e.insidePlotArea;var d=k(this.vertexes,c[h.chartIndex],this.insidePlotArea),a=h.toLinePath(d,!0);d=p(d);e.d=a;e.visibility=this.enabled&&0<d?"inherit":"hidden"}return n.prototype.attr.apply(this,arguments)};e.animate=function(e){if("object"===typeof e&&(l(e.enabled)||
l(e.vertexes)||l(e.insidePlotArea))){this.enabled=x(e.enabled,this.enabled);this.vertexes=x(e.vertexes,this.vertexes);this.insidePlotArea=x(e.insidePlotArea,this.insidePlotArea);delete e.enabled;delete e.vertexes;delete e.insidePlotArea;var d=k(this.vertexes,c[h.chartIndex],this.insidePlotArea),a=h.toLinePath(d,!0);d=p(d);d=this.enabled&&0<d?"visible":"hidden";e.d=a;this.attr("visibility",d)}return n.prototype.animate.apply(this,arguments)};return e.attr(a)};h.prototype.polyhedron=function(a){var c=
this,e=this.g(),h=e.destroy;this.styledMode||e.attr({"stroke-linejoin":"round"});e.faces=[];e.destroy=function(){for(var d=0;d<e.faces.length;d++)e.faces[d].destroy();return h.call(this)};e.attr=function(d,a,h,q){if("object"===typeof d&&l(d.faces)){for(;e.faces.length>d.faces.length;)e.faces.pop().destroy();for(;e.faces.length<d.faces.length;)e.faces.push(c.face3d().add(e));for(var u=0;u<d.faces.length;u++)c.styledMode&&delete d.faces[u].fill,e.faces[u].attr(d.faces[u],null,h,q);delete d.faces}return n.prototype.attr.apply(this,
arguments)};e.animate=function(d,a,h){if(d&&d.faces){for(;e.faces.length>d.faces.length;)e.faces.pop().destroy();for(;e.faces.length<d.faces.length;)e.faces.push(c.face3d().add(e));for(var q=0;q<d.faces.length;q++)e.faces[q].animate(d.faces[q],a,h);delete d.faces}return n.prototype.animate.apply(this,arguments)};return e.attr(a)};h.prototype.element3d=function(a,c){var e=this.g();F(e,this.elements3d[a]);e.initArgs(c);return e};h.prototype.cuboid=function(a){return this.element3d("cuboid",a)};h.prototype.cuboidPath=
function(a){function h(e){return 0===G&&1<e&&6>e?{x:r[e].x,y:r[e].y+10,z:r[e].z}:r[0].x===r[7].x&&4<=e?{x:r[e].x+10,y:r[e].y,z:r[e].z}:0===b&&2>e||5<e?{x:r[e].x,y:r[e].y,z:r[e].z+10}:r[e]}function e(e){return r[e]}var v=a.x||0,d=a.y||0,u=a.z||0,G=a.height||0,q=a.width||0,b=a.depth||0,g=c[this.chartIndex],f=g.options.chart.options3d.alpha,l=0,r=[{x:v,y:d,z:u},{x:v+q,y:d,z:u},{x:v+q,y:d+G,z:u},{x:v,y:d+G,z:u},{x:v,y:d+G,z:u+b},{x:v+q,y:d+G,z:u+b},{x:v+q,y:d,z:u+b},{x:v,y:d,z:u+b}],n=[];r=k(r,g,a.insidePlotArea);
var I=function(d,a,q){var c=[[],-1],u=d.map(e),G=a.map(e);d=d.map(h);a=a.map(h);0>p(u)?c=[u,0]:0>p(G)?c=[G,1]:q&&(n.push(q),c=0>p(d)?[u,0]:0>p(a)?[G,1]:[u,0]);return c};var m=I([3,2,1,0],[7,6,5,4],"front");a=m[0];var x=m[1];m=I([1,6,7,0],[4,5,2,3],"top");q=m[0];var w=m[1];m=I([1,2,5,6],[0,7,4,3],"side");I=m[0];m=m[1];1===m?l+=1E6*(g.plotWidth-v):m||(l+=1E6*v);l+=10*(!w||0<=f&&180>=f||360>f&&357.5<f?g.plotHeight-d:10+d);1===x?l+=100*u:x||(l+=100*(1E3-u));return{front:this.toLinePath(a,!0),top:this.toLinePath(q,
!0),side:this.toLinePath(I,!0),zIndexes:{group:Math.round(l)},forcedSides:n,isFront:x,isTop:w}};h.prototype.arc3d=function(a){function c(e){var a=!1,c={},h;e=w(e);for(h in e)-1!==d.indexOf(h)&&(c[h]=e[h],delete e[h],a=!0);return a?[c,e]:!1}var e=this.g(),h=e.renderer,d="x y r innerR start end depth".split(" ");a=w(a);a.alpha=(a.alpha||0)*E;a.beta=(a.beta||0)*E;e.top=h.path();e.side1=h.path();e.side2=h.path();e.inn=h.path();e.out=h.path();e.onAdd=function(){var d=e.parentGroup,a=e.attr("class");e.top.add(e);
["out","inn","side1","side2"].forEach(function(c){e[c].attr({"class":a+" highcharts-3d-side"}).add(d)})};["addClass","removeClass"].forEach(function(d){e[d]=function(){var a=arguments;["top","out","inn","side1","side2"].forEach(function(c){e[c][d].apply(e[c],a)})}});e.setPaths=function(d){var a=e.renderer.arc3dPath(d),c=100*a.zTop;e.attribs=d;e.top.attr({d:a.top,zIndex:a.zTop});e.inn.attr({d:a.inn,zIndex:a.zInn});e.out.attr({d:a.out,zIndex:a.zOut});e.side1.attr({d:a.side1,zIndex:a.zSide1});e.side2.attr({d:a.side2,
zIndex:a.zSide2});e.zIndex=c;e.attr({zIndex:c});d.center&&(e.top.setRadialReference(d.center),delete d.center)};e.setPaths(a);e.fillSetter=function(e){var d=b(e).brighten(-.1).get();this.fill=e;this.side1.attr({fill:d});this.side2.attr({fill:d});this.inn.attr({fill:d});this.out.attr({fill:d});this.top.attr({fill:e});return this};["opacity","translateX","translateY","visibility"].forEach(function(d){e[d+"Setter"]=function(d,a){e[a]=d;["out","inn","side1","side2","top"].forEach(function(c){e[c].attr(a,
d)})}});e.attr=function(d){var a;if("object"===typeof d&&(a=c(d))){var h=a[0];arguments[0]=a[1];F(e.attribs,h);e.setPaths(e.attribs)}return n.prototype.attr.apply(e,arguments)};e.animate=function(d,a,h){var q=this.attribs,u="data-"+Math.random().toString(26).substring(2,9);delete d.center;delete d.z;delete d.alpha;delete d.beta;var v=f(x(a,this.renderer.globalAnimation));if(v.duration){a=c(d);e[u]=0;d[u]=1;e[u+"Setter"]=t.noop;if(a){var b=a[0];v.step=function(d,e){function a(d){return q[d]+(x(b[d],
q[d])-q[d])*e.pos}e.prop===u&&e.elem.setPaths(w(q,{x:a("x"),y:a("y"),r:a("r"),innerR:a("innerR"),start:a("start"),end:a("end"),depth:a("depth")}))}}a=v}return n.prototype.animate.call(this,d,a,h)};e.destroy=function(){this.top.destroy();this.out.destroy();this.inn.destroy();this.side1.destroy();this.side2.destroy();return n.prototype.destroy.call(this)};e.hide=function(){this.top.hide();this.out.hide();this.inn.hide();this.side1.hide();this.side2.hide()};e.show=function(d){this.top.show(d);this.out.show(d);
this.inn.show(d);this.side1.show(d);this.side2.show(d)};return e};h.prototype.arc3dPath=function(a){function c(a){a%=2*Math.PI;a>Math.PI&&(a=2*Math.PI-a);return a}var e=a.x||0,v=a.y||0,d=a.start||0,u=(a.end||0)-.00001,b=a.r||0,q=a.innerR||0,g=a.depth||0,k=a.alpha||0,f=a.beta||0,l=Math.cos(d),r=Math.sin(d);a=Math.cos(u);var n=Math.sin(u),p=b*Math.cos(f);b*=Math.cos(k);var m=q*Math.cos(f),x=q*Math.cos(k);q=g*Math.sin(f);var w=g*Math.sin(k);g=[["M",e+p*l,v+b*r]];g=g.concat(h.curveTo(e,v,p,b,d,u,0,0));
g.push(["L",e+m*a,v+x*n]);g=g.concat(h.curveTo(e,v,m,x,u,d,0,0));g.push(["Z"]);var E=0<f?Math.PI/2:0;f=0<k?0:Math.PI/2;E=d>-E?d:u>-E?-E:d;var y=u<J-f?u:d<J-f?J-f:u,F=2*J-f;k=[["M",e+p*A(E),v+b*H(E)]];k=k.concat(h.curveTo(e,v,p,b,E,y,0,0));u>F&&d<F?(k.push(["L",e+p*A(y)+q,v+b*H(y)+w]),k=k.concat(h.curveTo(e,v,p,b,y,F,q,w)),k.push(["L",e+p*A(F),v+b*H(F)]),k=k.concat(h.curveTo(e,v,p,b,F,u,0,0)),k.push(["L",e+p*A(u)+q,v+b*H(u)+w]),k=k.concat(h.curveTo(e,v,p,b,u,F,q,w)),k.push(["L",e+p*A(F),v+b*H(F)]),
k=k.concat(h.curveTo(e,v,p,b,F,y,0,0))):u>J-f&&d<J-f&&(k.push(["L",e+p*Math.cos(y)+q,v+b*Math.sin(y)+w]),k=k.concat(h.curveTo(e,v,p,b,y,u,q,w)),k.push(["L",e+p*Math.cos(u),v+b*Math.sin(u)]),k=k.concat(h.curveTo(e,v,p,b,u,y,0,0)));k.push(["L",e+p*Math.cos(y)+q,v+b*Math.sin(y)+w]);k=k.concat(h.curveTo(e,v,p,b,y,E,q,w));k.push(["Z"]);f=[["M",e+m*l,v+x*r]];f=f.concat(h.curveTo(e,v,m,x,d,u,0,0));f.push(["L",e+m*Math.cos(u)+q,v+x*Math.sin(u)+w]);f=f.concat(h.curveTo(e,v,m,x,u,d,q,w));f.push(["Z"]);l=[["M",
e+p*l,v+b*r],["L",e+p*l+q,v+b*r+w],["L",e+m*l+q,v+x*r+w],["L",e+m*l,v+x*r],["Z"]];e=[["M",e+p*a,v+b*n],["L",e+p*a+q,v+b*n+w],["L",e+m*a+q,v+x*n+w],["L",e+m*a,v+x*n],["Z"]];n=Math.atan2(w,-q);v=Math.abs(u+n);a=Math.abs(d+n);d=Math.abs((d+u)/2+n);v=c(v);a=c(a);d=c(d);d*=1E5;u=1E5*a;v*=1E5;return{top:g,zTop:1E5*Math.PI+1,out:k,zOut:Math.max(d,u,v),inn:f,zInn:Math.max(d,u,v),side1:l,zSide1:.99*v,side2:e,zSide2:.99*u}};return h}(B)});D(a,"Core/Chart/Chart3D.js",[a["Core/Color/Color.js"],a["Core/Defaults.js"],
a["Core/Math3D.js"],a["Core/Utilities.js"]],function(a,z,t,C){var n=a.parse,m=z.defaultOptions,A=t.perspective,y=t.shapeArea3D,g=C.addEvent,f=C.isArray,b=C.merge,c=C.pick,E=C.wrap,k;(function(a){function k(a){this.is3d()&&"scatter"===a.options.type&&(a.options.type="scatter3d")}function p(){if(this.chart3d&&this.is3d()){var a=this.renderer,c=this.options.chart.options3d,d=this.chart3d.get3dFrame(),h=this.plotLeft,b=this.plotLeft+this.plotWidth,q=this.plotTop,k=this.plotTop+this.plotHeight;c=c.depth;
var f=h-(d.left.visible?d.left.size:0),g=b+(d.right.visible?d.right.size:0),l=q-(d.top.visible?d.top.size:0),r=k+(d.bottom.visible?d.bottom.size:0),p=0-(d.front.visible?d.front.size:0),m=c+(d.back.visible?d.back.size:0),w=this.hasRendered?"animate":"attr";this.chart3d.frame3d=d;this.frameShapes||(this.frameShapes={bottom:a.polyhedron().add(),top:a.polyhedron().add(),left:a.polyhedron().add(),right:a.polyhedron().add(),back:a.polyhedron().add(),front:a.polyhedron().add()});this.frameShapes.bottom[w]({"class":"highcharts-3d-frame highcharts-3d-frame-bottom",
zIndex:d.bottom.frontFacing?-1E3:1E3,faces:[{fill:n(d.bottom.color).brighten(.1).get(),vertexes:[{x:f,y:r,z:p},{x:g,y:r,z:p},{x:g,y:r,z:m},{x:f,y:r,z:m}],enabled:d.bottom.visible},{fill:n(d.bottom.color).brighten(.1).get(),vertexes:[{x:h,y:k,z:c},{x:b,y:k,z:c},{x:b,y:k,z:0},{x:h,y:k,z:0}],enabled:d.bottom.visible},{fill:n(d.bottom.color).brighten(-.1).get(),vertexes:[{x:f,y:r,z:p},{x:f,y:r,z:m},{x:h,y:k,z:c},{x:h,y:k,z:0}],enabled:d.bottom.visible&&!d.left.visible},{fill:n(d.bottom.color).brighten(-.1).get(),
vertexes:[{x:g,y:r,z:m},{x:g,y:r,z:p},{x:b,y:k,z:0},{x:b,y:k,z:c}],enabled:d.bottom.visible&&!d.right.visible},{fill:n(d.bottom.color).get(),vertexes:[{x:g,y:r,z:p},{x:f,y:r,z:p},{x:h,y:k,z:0},{x:b,y:k,z:0}],enabled:d.bottom.visible&&!d.front.visible},{fill:n(d.bottom.color).get(),vertexes:[{x:f,y:r,z:m},{x:g,y:r,z:m},{x:b,y:k,z:c},{x:h,y:k,z:c}],enabled:d.bottom.visible&&!d.back.visible}]});this.frameShapes.top[w]({"class":"highcharts-3d-frame highcharts-3d-frame-top",zIndex:d.top.frontFacing?-1E3:
1E3,faces:[{fill:n(d.top.color).brighten(.1).get(),vertexes:[{x:f,y:l,z:m},{x:g,y:l,z:m},{x:g,y:l,z:p},{x:f,y:l,z:p}],enabled:d.top.visible},{fill:n(d.top.color).brighten(.1).get(),vertexes:[{x:h,y:q,z:0},{x:b,y:q,z:0},{x:b,y:q,z:c},{x:h,y:q,z:c}],enabled:d.top.visible},{fill:n(d.top.color).brighten(-.1).get(),vertexes:[{x:f,y:l,z:m},{x:f,y:l,z:p},{x:h,y:q,z:0},{x:h,y:q,z:c}],enabled:d.top.visible&&!d.left.visible},{fill:n(d.top.color).brighten(-.1).get(),vertexes:[{x:g,y:l,z:p},{x:g,y:l,z:m},{x:b,
y:q,z:c},{x:b,y:q,z:0}],enabled:d.top.visible&&!d.right.visible},{fill:n(d.top.color).get(),vertexes:[{x:f,y:l,z:p},{x:g,y:l,z:p},{x:b,y:q,z:0},{x:h,y:q,z:0}],enabled:d.top.visible&&!d.front.visible},{fill:n(d.top.color).get(),vertexes:[{x:g,y:l,z:m},{x:f,y:l,z:m},{x:h,y:q,z:c},{x:b,y:q,z:c}],enabled:d.top.visible&&!d.back.visible}]});this.frameShapes.left[w]({"class":"highcharts-3d-frame highcharts-3d-frame-left",zIndex:d.left.frontFacing?-1E3:1E3,faces:[{fill:n(d.left.color).brighten(.1).get(),
vertexes:[{x:f,y:r,z:p},{x:h,y:k,z:0},{x:h,y:k,z:c},{x:f,y:r,z:m}],enabled:d.left.visible&&!d.bottom.visible},{fill:n(d.left.color).brighten(.1).get(),vertexes:[{x:f,y:l,z:m},{x:h,y:q,z:c},{x:h,y:q,z:0},{x:f,y:l,z:p}],enabled:d.left.visible&&!d.top.visible},{fill:n(d.left.color).brighten(-.1).get(),vertexes:[{x:f,y:r,z:m},{x:f,y:l,z:m},{x:f,y:l,z:p},{x:f,y:r,z:p}],enabled:d.left.visible},{fill:n(d.left.color).brighten(-.1).get(),vertexes:[{x:h,y:q,z:c},{x:h,y:k,z:c},{x:h,y:k,z:0},{x:h,y:q,z:0}],enabled:d.left.visible},
{fill:n(d.left.color).get(),vertexes:[{x:f,y:r,z:p},{x:f,y:l,z:p},{x:h,y:q,z:0},{x:h,y:k,z:0}],enabled:d.left.visible&&!d.front.visible},{fill:n(d.left.color).get(),vertexes:[{x:f,y:l,z:m},{x:f,y:r,z:m},{x:h,y:k,z:c},{x:h,y:q,z:c}],enabled:d.left.visible&&!d.back.visible}]});this.frameShapes.right[w]({"class":"highcharts-3d-frame highcharts-3d-frame-right",zIndex:d.right.frontFacing?-1E3:1E3,faces:[{fill:n(d.right.color).brighten(.1).get(),vertexes:[{x:g,y:r,z:m},{x:b,y:k,z:c},{x:b,y:k,z:0},{x:g,
y:r,z:p}],enabled:d.right.visible&&!d.bottom.visible},{fill:n(d.right.color).brighten(.1).get(),vertexes:[{x:g,y:l,z:p},{x:b,y:q,z:0},{x:b,y:q,z:c},{x:g,y:l,z:m}],enabled:d.right.visible&&!d.top.visible},{fill:n(d.right.color).brighten(-.1).get(),vertexes:[{x:b,y:q,z:0},{x:b,y:k,z:0},{x:b,y:k,z:c},{x:b,y:q,z:c}],enabled:d.right.visible},{fill:n(d.right.color).brighten(-.1).get(),vertexes:[{x:g,y:r,z:p},{x:g,y:l,z:p},{x:g,y:l,z:m},{x:g,y:r,z:m}],enabled:d.right.visible},{fill:n(d.right.color).get(),
vertexes:[{x:g,y:l,z:p},{x:g,y:r,z:p},{x:b,y:k,z:0},{x:b,y:q,z:0}],enabled:d.right.visible&&!d.front.visible},{fill:n(d.right.color).get(),vertexes:[{x:g,y:r,z:m},{x:g,y:l,z:m},{x:b,y:q,z:c},{x:b,y:k,z:c}],enabled:d.right.visible&&!d.back.visible}]});this.frameShapes.back[w]({"class":"highcharts-3d-frame highcharts-3d-frame-back",zIndex:d.back.frontFacing?-1E3:1E3,faces:[{fill:n(d.back.color).brighten(.1).get(),vertexes:[{x:g,y:r,z:m},{x:f,y:r,z:m},{x:h,y:k,z:c},{x:b,y:k,z:c}],enabled:d.back.visible&&
!d.bottom.visible},{fill:n(d.back.color).brighten(.1).get(),vertexes:[{x:f,y:l,z:m},{x:g,y:l,z:m},{x:b,y:q,z:c},{x:h,y:q,z:c}],enabled:d.back.visible&&!d.top.visible},{fill:n(d.back.color).brighten(-.1).get(),vertexes:[{x:f,y:r,z:m},{x:f,y:l,z:m},{x:h,y:q,z:c},{x:h,y:k,z:c}],enabled:d.back.visible&&!d.left.visible},{fill:n(d.back.color).brighten(-.1).get(),vertexes:[{x:g,y:l,z:m},{x:g,y:r,z:m},{x:b,y:k,z:c},{x:b,y:q,z:c}],enabled:d.back.visible&&!d.right.visible},{fill:n(d.back.color).get(),vertexes:[{x:h,
y:q,z:c},{x:b,y:q,z:c},{x:b,y:k,z:c},{x:h,y:k,z:c}],enabled:d.back.visible},{fill:n(d.back.color).get(),vertexes:[{x:f,y:r,z:m},{x:g,y:r,z:m},{x:g,y:l,z:m},{x:f,y:l,z:m}],enabled:d.back.visible}]});this.frameShapes.front[w]({"class":"highcharts-3d-frame highcharts-3d-frame-front",zIndex:d.front.frontFacing?-1E3:1E3,faces:[{fill:n(d.front.color).brighten(.1).get(),vertexes:[{x:f,y:r,z:p},{x:g,y:r,z:p},{x:b,y:k,z:0},{x:h,y:k,z:0}],enabled:d.front.visible&&!d.bottom.visible},{fill:n(d.front.color).brighten(.1).get(),
vertexes:[{x:g,y:l,z:p},{x:f,y:l,z:p},{x:h,y:q,z:0},{x:b,y:q,z:0}],enabled:d.front.visible&&!d.top.visible},{fill:n(d.front.color).brighten(-.1).get(),vertexes:[{x:f,y:l,z:p},{x:f,y:r,z:p},{x:h,y:k,z:0},{x:h,y:q,z:0}],enabled:d.front.visible&&!d.left.visible},{fill:n(d.front.color).brighten(-.1).get(),vertexes:[{x:g,y:r,z:p},{x:g,y:l,z:p},{x:b,y:q,z:0},{x:b,y:k,z:0}],enabled:d.front.visible&&!d.right.visible},{fill:n(d.front.color).get(),vertexes:[{x:b,y:q,z:0},{x:h,y:q,z:0},{x:h,y:k,z:0},{x:b,y:k,
z:0}],enabled:d.front.visible},{fill:n(d.front.color).get(),vertexes:[{x:g,y:r,z:p},{x:f,y:r,z:p},{x:f,y:l,z:p},{x:g,y:l,z:p}],enabled:d.front.visible}]})}}function w(){this.styledMode&&[{name:"darker",slope:.6},{name:"brighter",slope:1.4}].forEach(function(a){this.renderer.definition({tagName:"filter",attributes:{id:"highcharts-"+a.name},children:[{tagName:"feComponentTransfer",children:[{tagName:"feFuncR",attributes:{type:"linear",slope:a.slope}},{tagName:"feFuncG",attributes:{type:"linear",slope:a.slope}},
{tagName:"feFuncB",attributes:{type:"linear",slope:a.slope}}]}]})},this)}function x(){var a=this.options;this.is3d()&&(a.series||[]).forEach(function(e){"scatter"===(e.type||a.chart.type||a.chart.defaultSeriesType)&&(e.type="scatter3d")})}function t(){var a=this.options.chart.options3d;if(this.chart3d&&this.is3d()){a&&(a.alpha=a.alpha%360+(0<=a.alpha?0:360),a.beta=a.beta%360+(0<=a.beta?0:360));var c=this.inverted,d=this.clipBox,h=this.margin;d[c?"y":"x"]=-(h[3]||0);d[c?"x":"y"]=-(h[0]||0);d[c?"height":
"width"]=this.chartWidth+(h[3]||0)+(h[1]||0);d[c?"width":"height"]=this.chartHeight+(h[0]||0)+(h[2]||0);this.scale3d=1;!0===a.fitToPlot&&(this.scale3d=this.chart3d.getScale(a.depth));this.chart3d.frame3d=this.chart3d.get3dFrame()}}function B(){this.is3d()&&(this.isDirtyBox=!0)}function z(){this.chart3d&&this.is3d()&&(this.chart3d.frame3d=this.chart3d.get3dFrame())}function C(){this.chart3d||(this.chart3d=new K(this))}function M(a){return this.is3d()||a.apply(this,[].slice.call(arguments,1))}function h(a){var e=
this.series.length;if(this.is3d())for(;e--;)a=this.series[e],a.translate(),a.render();else a.call(this)}function I(a){a.apply(this,[].slice.call(arguments,1));this.is3d()&&(this.container.className+=" highcharts-3d-chart")}var K=function(){function a(a){this.frame3d=void 0;this.chart=a}a.prototype.get3dFrame=function(){function a(a,d,e){for(var b=["size","color","visible"],h={},k=0;k<b.length;k++)for(var f=b[k],g=0;g<a.length;g++)if("object"===typeof a[g]){var l=a[g][f];if("undefined"!==typeof l&&
null!==l){h[f]=l;break}}a=e;!0===h.visible||!1===h.visible?a=h.visible:"auto"===h.visible&&(a=0<d);return{size:c(h.size,1),color:c(h.color,"none"),frontFacing:0<d,visible:a}}function d(a){a=y(a,e);return.5<a?1:-.5>a?-1:0}var e=this.chart,h=e.options.chart.options3d,b=h.frame,k=e.plotLeft,f=e.plotLeft+e.plotWidth,g=e.plotTop,l=e.plotTop+e.plotHeight,p=h.depth,m=d([{x:k,y:l,z:p},{x:f,y:l,z:p},{x:f,y:l,z:0},{x:k,y:l,z:0}]),n=d([{x:k,y:g,z:0},{x:f,y:g,z:0},{x:f,y:g,z:p},{x:k,y:g,z:p}]),w=d([{x:k,y:g,
z:0},{x:k,y:g,z:p},{x:k,y:l,z:p},{x:k,y:l,z:0}]),x=d([{x:f,y:g,z:p},{x:f,y:g,z:0},{x:f,y:l,z:0},{x:f,y:l,z:p}]),E=d([{x:k,y:l,z:0},{x:f,y:l,z:0},{x:f,y:g,z:0},{x:k,y:g,z:0}]),F=d([{x:k,y:g,z:p},{x:f,y:g,z:p},{x:f,y:l,z:p},{x:k,y:l,z:p}]),t=!1,I=!1,K=!1,B=!1;[].concat(e.xAxis,e.yAxis,e.zAxis).forEach(function(a){a&&(a.horiz?a.opposite?I=!0:t=!0:a.opposite?B=!0:K=!0)});b={axes:{},bottom:a([b.bottom,b.top,b],m,t),top:a([b.top,b.bottom,b],n,I),left:a([b.left,b.right,b.side,b],w,K),right:a([b.right,b.left,
b.side,b],x,B),back:a([b.back,b.front,b],F,!0),front:a([b.front,b.back,b],E,!1)};"auto"===h.axisLabelPosition?(x=function(a,d){return a.visible!==d.visible||a.visible&&d.visible&&a.frontFacing!==d.frontFacing},h=[],x(b.left,b.front)&&h.push({y:(g+l)/2,x:k,z:0,xDir:{x:1,y:0,z:0}}),x(b.left,b.back)&&h.push({y:(g+l)/2,x:k,z:p,xDir:{x:0,y:0,z:-1}}),x(b.right,b.front)&&h.push({y:(g+l)/2,x:f,z:0,xDir:{x:0,y:0,z:1}}),x(b.right,b.back)&&h.push({y:(g+l)/2,x:f,z:p,xDir:{x:-1,y:0,z:0}}),m=[],x(b.bottom,b.front)&&
m.push({x:(k+f)/2,y:l,z:0,xDir:{x:1,y:0,z:0}}),x(b.bottom,b.back)&&m.push({x:(k+f)/2,y:l,z:p,xDir:{x:-1,y:0,z:0}}),n=[],x(b.top,b.front)&&n.push({x:(k+f)/2,y:g,z:0,xDir:{x:1,y:0,z:0}}),x(b.top,b.back)&&n.push({x:(k+f)/2,y:g,z:p,xDir:{x:-1,y:0,z:0}}),w=[],x(b.bottom,b.left)&&w.push({z:(0+p)/2,y:l,x:k,xDir:{x:0,y:0,z:-1}}),x(b.bottom,b.right)&&w.push({z:(0+p)/2,y:l,x:f,xDir:{x:0,y:0,z:1}}),l=[],x(b.top,b.left)&&l.push({z:(0+p)/2,y:g,x:k,xDir:{x:0,y:0,z:-1}}),x(b.top,b.right)&&l.push({z:(0+p)/2,y:g,
x:f,xDir:{x:0,y:0,z:1}}),k=function(a,d,b){if(0===a.length)return null;if(1===a.length)return a[0];for(var h=A(a,e,!1),c=0,k=1;k<h.length;k++)b*h[k][d]>b*h[c][d]?c=k:b*h[k][d]===b*h[c][d]&&h[k].z<h[c].z&&(c=k);return a[c]},b.axes={y:{left:k(h,"x",-1),right:k(h,"x",1)},x:{top:k(n,"y",-1),bottom:k(m,"y",1)},z:{top:k(l,"y",-1),bottom:k(w,"y",1)}}):b.axes={y:{left:{x:k,z:0,xDir:{x:1,y:0,z:0}},right:{x:f,z:0,xDir:{x:0,y:0,z:1}}},x:{top:{y:g,z:0,xDir:{x:1,y:0,z:0}},bottom:{y:l,z:0,xDir:{x:1,y:0,z:0}}},
z:{top:{x:K?f:k,y:g,xDir:K?{x:0,y:0,z:1}:{x:0,y:0,z:-1}},bottom:{x:K?f:k,y:l,xDir:K?{x:0,y:0,z:1}:{x:0,y:0,z:-1}}}};return b};a.prototype.getScale=function(a){var d=this.chart,e=d.plotLeft,b=d.plotWidth+e,h=d.plotTop,c=d.plotHeight+h,k=e+d.plotWidth/2,f=h+d.plotHeight/2,g=Number.MAX_VALUE,l=-Number.MAX_VALUE,p=Number.MAX_VALUE,m=-Number.MAX_VALUE,n=1;var x=[{x:e,y:h,z:0},{x:e,y:h,z:a}];[0,1].forEach(function(a){x.push({x:b,y:x[a].y,z:x[a].z})});[0,1,2,3].forEach(function(a){x.push({x:x[a].x,y:c,z:x[a].z})});
x=A(x,d,!1);x.forEach(function(a){g=Math.min(g,a.x);l=Math.max(l,a.x);p=Math.min(p,a.y);m=Math.max(m,a.y)});e>g&&(n=Math.min(n,1-Math.abs((e+k)/(g+k))%1));b<l&&(n=Math.min(n,(b-k)/(l-k)));h>p&&(n=0>p?Math.min(n,(h+f)/(-p+h+f)):Math.min(n,1-(h+f)/(p+f)%1));c<m&&(n=Math.min(n,Math.abs((c-f)/(m-f))));return n};return a}();a.Composition=K;a.defaultOptions={chart:{options3d:{enabled:!1,alpha:0,beta:0,depth:100,fitToPlot:!0,viewDistance:25,axisLabelPosition:null,frame:{visible:"default",size:1,bottom:{},
top:{},left:{},right:{},back:{},front:{}}}}};a.compose=function(e,c){var d=e.prototype;c=c.prototype;d.is3d=function(){return!(!this.options.chart.options3d||!this.options.chart.options3d.enabled)};d.propsRequireDirtyBox.push("chart.options3d");d.propsRequireUpdateSeries.push("chart.options3d");c.matrixSetter=function(){if(1>this.pos&&(f(this.start)||f(this.end))){var a=this.start||[1,0,0,1,0,0],d=this.end||[1,0,0,1,0,0];var e=[];for(var h=0;6>h;h++)e.push(this.pos*d[h]+(1-this.pos)*a[h])}else e=
this.end;this.elem.attr(this.prop,e,null,!0)};b(!0,m,a.defaultOptions);g(e,"init",C);g(e,"addSeries",k);g(e,"afterDrawChartBox",p);g(e,"afterGetContainer",w);g(e,"afterInit",x);g(e,"afterSetChartSize",t);g(e,"beforeRedraw",B);g(e,"beforeRender",z);E(d,"isInsidePlot",M);E(d,"renderSeries",h);E(d,"setClassName",I)}})(k||(k={}));"";return k});D(a,"Core/Axis/ZAxis.js",[a["Core/Axis/Axis.js"],a["Core/Utilities.js"]],function(a,z){function t(a){return new b(this,a)}function A(){var a=this,b=this.options.zAxis=
g(this.options.zAxis||{});this.is3d()&&(this.zAxis=[],b.forEach(function(b){a.addZAxis(b).setScale()}))}var n=this&&this.__extends||function(){function a(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};return a(b,c)}return function(b,c){function k(){this.constructor=b}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");
a(b,c);b.prototype=null===c?Object.create(c):(k.prototype=c.prototype,new k)}}(),m=z.addEvent,B=z.merge,y=z.pick,g=z.splat,f=[],b=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.isZAxis=!0;return b}n(b,a);b.compose=function(a){z.pushUnique(f,a)&&(m(a,"afterGetAxes",A),a=a.prototype,a.addZAxis=t,a.collectionsWithInit.zAxis=[a.addZAxis],a.collectionsWithUpdate.push("zAxis"))};b.prototype.init=function(b,c){this.isZAxis=!0;a.prototype.init.call(this,b,c,"zAxis")};b.prototype.getSeriesExtremes=
function(){var a=this,b=this.chart;this.hasVisibleSeries=!1;this.dataMin=this.dataMax=this.ignoreMinPadding=this.ignoreMaxPadding=void 0;this.stacking&&this.stacking.buildStacks();this.series.forEach(function(c){if(c.visible||!b.options.chart.ignoreHiddenSeries)a.hasVisibleSeries=!0,c=c.zData,c.length&&(a.dataMin=Math.min(y(a.dataMin,c[0]),Math.min.apply(null,c)),a.dataMax=Math.max(y(a.dataMax,c[0]),Math.max.apply(null,c)))})};b.prototype.setAxisSize=function(){var b=this.chart;a.prototype.setAxisSize.call(this);
this.width=this.len=b.options.chart.options3d&&b.options.chart.options3d.depth||0;this.right=b.chartWidth-this.width-this.left};b.prototype.setOptions=function(b){b=B({offset:0,lineWidth:0},b);a.prototype.setOptions.call(this,b)};return b}(a);return b});D(a,"Core/Axis/Axis3DDefaults.js",[],function(){return{labels:{position3d:"offset",skew3d:!1},title:{position3d:null,skew3d:null}}});D(a,"Core/Axis/Tick3DComposition.js",[a["Core/Utilities.js"]],function(a){function A(a){var g=this.axis.axis3D;g&&
n(a.pos,g.fix3dPosition(a.pos))}function t(a){var g=this.axis.axis3D,f=a.apply(this,[].slice.call(arguments,1));if(g){var b=f[0],c=f[1];if("M"===b[0]&&"L"===c[0])return g=[g.fix3dPosition({x:b[1],y:b[2],z:0}),g.fix3dPosition({x:c[1],y:c[2],z:0})],this.axis.chart.renderer.toLineSegments(g)}return f}var C=a.addEvent,n=a.extend,m=a.wrap,B=[];return{compose:function(n){a.pushUnique(B,n)&&(C(n,"afterGetLabelPosition",A),m(n.prototype,"getMarkPath",t))}}});D(a,"Core/Axis/Axis3DComposition.js",[a["Core/Axis/Axis3DDefaults.js"],
a["Core/Globals.js"],a["Core/Math3D.js"],a["Core/Axis/Tick3DComposition.js"],a["Core/Utilities.js"]],function(a,z,t,C,n){function m(){var a=this.chart,b=this.options;a.is3d&&a.is3d()&&"colorAxis"!==this.coll&&(b.tickWidth=A(b.tickWidth,0),b.gridLineWidth=A(b.gridLineWidth,1))}function B(a){this.chart.is3d()&&"colorAxis"!==this.coll&&a.point&&(a.point.crosshairPos=this.isXAxis?a.point.axisXpos:this.len-a.point.axisYpos)}function y(){this.axis3D||(this.axis3D=new L(this))}function g(a){return this.chart.is3d()&&
"colorAxis"!==this.coll?[]:a.apply(this,[].slice.call(arguments,1))}function f(a){if(!this.chart.is3d()||"colorAxis"===this.coll)return a.apply(this,[].slice.call(arguments,1));var b=arguments,c=b[2],f=[];b=this.getPlotLinePath({value:b[1]});c=this.getPlotLinePath({value:c});if(b&&c)for(var e=0;e<b.length;e+=2){var g=b[e],d=b[e+1],k=c[e],l=c[e+1];"M"===g[0]&&"L"===d[0]&&"M"===k[0]&&"L"===l[0]&&f.push(g,d,l,["L",k[1],k[2]],["Z"])}return f}function b(a){var b=this.axis3D,c=this.chart,f=a.apply(this,
[].slice.call(arguments,1));if("colorAxis"===this.coll||!c.chart3d||!c.is3d()||null===f)return f;var e=c.options.chart.options3d,g=this.isZAxis?c.plotWidth:e.depth;e=c.chart3d.frame3d;var d=f[0],k=f[1];f=[];"M"===d[0]&&"L"===k[0]&&(b=[b.swapZ({x:d[1],y:d[2],z:0}),b.swapZ({x:d[1],y:d[2],z:g}),b.swapZ({x:k[1],y:k[2],z:0}),b.swapZ({x:k[1],y:k[2],z:g})],this.horiz?(this.isZAxis?(e.left.visible&&f.push(b[0],b[2]),e.right.visible&&f.push(b[1],b[3])):(e.front.visible&&f.push(b[0],b[2]),e.back.visible&&f.push(b[1],
b[3])),e.top.visible&&f.push(b[0],b[1]),e.bottom.visible&&f.push(b[2],b[3])):(e.front.visible&&f.push(b[0],b[2]),e.back.visible&&f.push(b[1],b[3]),e.left.visible&&f.push(b[0],b[1]),e.right.visible&&f.push(b[2],b[3])),f=p(f,this.chart,!1));return c.renderer.toLineSegments(f)}function c(a,b){var c=this.chart,h=this.ticks,e=this.gridGroup;if(this.categories&&c.frameShapes&&c.is3d()&&e&&b&&b.label){e=e.element.childNodes[0].getBBox();var f=c.frameShapes.left.getBBox(),d=c.options.chart.options3d;c={x:c.plotWidth/
2,y:c.plotHeight/2,z:d.depth/2,vd:A(d.depth,1)*A(d.viewDistance,0)};d=b.pos;var k=h[d-1],g=h[d+1],p=h=void 0;0!==d&&k&&k.label&&k.label.xy&&(h=l({x:k.label.xy.x,y:k.label.xy.y,z:null},c,c.vd));g&&g.label&&g.label.xy&&(p=l({x:g.label.xy.x,y:g.label.xy.y,z:null},c,c.vd));d={x:b.label.xy.x,y:b.label.xy.y,z:null};d=l(d,c,c.vd);return Math.abs(h?d.x-h.x:p?p.x-d.x:e.x-f.x)}return a.apply(this,[].slice.call(arguments,1))}function E(a){var b=a.apply(this,[].slice.call(arguments,1));return this.axis3D?this.axis3D.fix3dPosition(b,
!0):b}var k=z.deg2rad,p=t.perspective,l=t.perspective3D,F=t.shapeArea,w=n.addEvent,x=n.merge,A=n.pick,H=n.wrap,J=[],L=function(){function l(a){this.axis=a}l.compose=function(h,k){C.compose(k);n.pushUnique(J,h)&&(x(!0,h.defaultOptions,a),h.keepProps.push("axis3D"),w(h,"init",y),w(h,"afterSetOptions",m),w(h,"drawCrosshair",B),h=h.prototype,H(h,"getLinePath",g),H(h,"getPlotBandPath",f),H(h,"getPlotLinePath",b),H(h,"getSlotWidth",c),H(h,"getTitlePosition",E))};l.prototype.fix3dPosition=function(a,b){var c=
this.axis,e=c.chart;if("colorAxis"===c.coll||!e.chart3d||!e.is3d())return a;var f=k*e.options.chart.options3d.alpha,d=k*e.options.chart.options3d.beta,g=A(b&&c.options.title.position3d,c.options.labels.position3d);b=A(b&&c.options.title.skew3d,c.options.labels.skew3d);var h=e.chart3d.frame3d,l=e.plotLeft,m=e.plotWidth+l,n=e.plotTop,x=e.plotHeight+n,w=e=0,r={x:0,y:1,z:0},y=!1;a=c.axis3D.swapZ({x:a.x,y:a.y,z:0});if(c.isZAxis)if(c.opposite){if(null===h.axes.z.top)return{};w=a.y-n;a.x=h.axes.z.top.x;
a.y=h.axes.z.top.y;l=h.axes.z.top.xDir;y=!h.top.frontFacing}else{if(null===h.axes.z.bottom)return{};w=a.y-x;a.x=h.axes.z.bottom.x;a.y=h.axes.z.bottom.y;l=h.axes.z.bottom.xDir;y=!h.bottom.frontFacing}else if(c.horiz)if(c.opposite){if(null===h.axes.x.top)return{};w=a.y-n;a.y=h.axes.x.top.y;a.z=h.axes.x.top.z;l=h.axes.x.top.xDir;y=!h.top.frontFacing}else{if(null===h.axes.x.bottom)return{};w=a.y-x;a.y=h.axes.x.bottom.y;a.z=h.axes.x.bottom.z;l=h.axes.x.bottom.xDir;y=!h.bottom.frontFacing}else if(c.opposite){if(null===
h.axes.y.right)return{};e=a.x-m;a.x=h.axes.y.right.x;a.z=h.axes.y.right.z;l=h.axes.y.right.xDir;l={x:l.z,y:l.y,z:-l.x}}else{if(null===h.axes.y.left)return{};e=a.x-l;a.x=h.axes.y.left.x;a.z=h.axes.y.left.z;l=h.axes.y.left.xDir}"chart"!==g&&("flap"===g?c.horiz?(d=Math.sin(f),f=Math.cos(f),c.opposite&&(d=-d),y&&(d=-d),r={x:l.z*d,y:f,z:-l.x*d}):l={x:Math.cos(d),y:0,z:Math.sin(d)}:"ortho"===g?c.horiz?(r=Math.cos(f),g=Math.sin(d)*r,f=-Math.sin(f),d=-r*Math.cos(d),r={x:l.y*d-l.z*f,y:l.z*g-l.x*d,z:l.x*f-
l.y*g},f=1/Math.sqrt(r.x*r.x+r.y*r.y+r.z*r.z),y&&(f=-f),r={x:f*r.x,y:f*r.y,z:f*r.z}):l={x:Math.cos(d),y:0,z:Math.sin(d)}:c.horiz?r={x:Math.sin(d)*Math.sin(f),y:Math.cos(f),z:-Math.cos(d)*Math.sin(f)}:l={x:Math.cos(d),y:0,z:Math.sin(d)});a.x+=e*l.x+w*r.x;a.y+=e*l.y+w*r.y;a.z+=e*l.z+w*r.z;e=p([a],c.chart)[0];b&&(0>F(p([a,{x:a.x+l.x,y:a.y+l.y,z:a.z+l.z},{x:a.x+r.x,y:a.y+r.y,z:a.z+r.z}],c.chart))&&(l={x:-l.x,y:-l.y,z:-l.z}),a=p([{x:a.x,y:a.y,z:a.z},{x:a.x+l.x,y:a.y+l.y,z:a.z+l.z},{x:a.x+r.x,y:a.y+r.y,
z:a.z+r.z}],c.chart),e.matrix=[a[1].x-a[0].x,a[1].y-a[0].y,a[2].x-a[0].x,a[2].y-a[0].y,e.x,e.y],e.matrix[4]-=e.x*e.matrix[0]+e.y*e.matrix[2],e.matrix[5]-=e.x*e.matrix[1]+e.y*e.matrix[3]);return e};l.prototype.swapZ=function(a,b){var c=this.axis;return c.isZAxis?(b=b?0:c.chart.plotLeft,{x:b+a.z,y:a.y,z:a.x-b}):a};return l}();return L});D(a,"Core/Series/Series3D.js",[a["Core/Math3D.js"],a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,z,t){var A=this&&this.__extends||function(){function a(b,
c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};return a(b,c)}return function(b,c){function f(){this.constructor=b}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");a(b,c);b.prototype=null===c?Object.create(c):(f.prototype=c.prototype,new f)}}(),n=a.perspective;a=t.addEvent;var m=t.extend,B=t.merge,y=t.pick,
g=t.isNumber;t=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}A(b,a);b.prototype.translate=function(){a.prototype.translate.apply(this,arguments);this.chart.is3d()&&this.translate3dPoints()};b.prototype.translate3dPoints=function(){var a=this.options,b=this.chart,f=y(this.zAxis,b.options.zAxis[0]),p=[],l,m=[];this.zPadding=(a.stacking?g(a.stack)?a.stack:0:this.index||0)*(a.depth||0+(a.groupZPadding||1));for(l=0;l<this.data.length;l++){a=this.data[l];if(f&&f.translate){var w=
f.logarithmic&&f.val2lin?f.val2lin(a.z):a.z;a.plotZ=f.translate(w);a.isInside=a.isInside?w>=f.min&&w<=f.max:!1}else a.plotZ=this.zPadding;a.axisXpos=a.plotX;a.axisYpos=a.plotY;a.axisZpos=a.plotZ;p.push({x:a.plotX,y:a.plotY,z:a.plotZ});m.push(a.plotX||0)}this.rawPointsX=m;b=n(p,b,!0);for(l=0;l<this.data.length;l++)a=this.data[l],f=b[l],a.plotX=f.x,a.plotY=f.y,a.plotZ=f.z};b.defaultOptions=B(z.defaultOptions);return b}(z);a(z,"afterTranslate",function(){this.chart.is3d()&&this.translate3dPoints()});
m(z.prototype,{translate3dPoints:t.prototype.translate3dPoints});return t});D(a,"Series/Area3D/Area3DSeries.js",[a["Core/Math3D.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,z,t){function A(a){var f=a.apply(this,[].slice.call(arguments,1));if(!this.chart.is3d())return f;var b=m.getGraphPath,c=this.options,g=Math.round(this.yAxis.getThreshold(c.threshold)),k=[];if(this.rawPointsX)for(var p=0;p<this.points.length;p++)k.push({x:this.rawPointsX[p],y:c.stacking?this.points[p].yBottom:
g,z:this.zPadding});c=this.chart.options.chart.options3d;k=n(k,this.chart,!0).map(function(a){return{plotX:a.x,plotY:a.y,plotZ:a.z}});this.group&&c&&c.depth&&c.beta&&(this.markerGroup&&(this.markerGroup.add(this.group),this.markerGroup.attr({translateX:0,translateY:0})),this.group.attr({zIndex:Math.max(1,270<c.beta||90>c.beta?c.depth-Math.round(this.zPadding||0):Math.round(this.zPadding||0))}));k.reversed=!0;b=b.call(this,k,!0,!0);b[0]&&"M"===b[0][0]&&(b[0]=["L",b[0][1],b[0][2]]);this.areaPath&&(b=
this.areaPath.splice(0,this.areaPath.length/2).concat(b),b.xMap=this.areaPath.xMap,this.areaPath=b);return f}var n=a.perspective,m=z.seriesTypes.line.prototype,B=t.wrap,y=[];return{compose:function(a){t.pushUnique(y,a)&&B(a.prototype,"getGraphPath",A)}}});D(a,"Series/Column3D/Column3DComposition.js",[a["Series/Column/ColumnSeries.js"],a["Core/Series/Series.js"],a["Core/Math3D.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Axis/Stacking/StackItem.js"],a["Core/Utilities.js"]],function(a,z,t,C,n,m){function B(a,
b){var c=a.series,f={totalStacks:0},g,l=1;c.forEach(function(a){g=k(a.options.stack,b?0:c.length-1-a.index);f[g]?f[g].series.push(a):(f[g]={series:[a],position:l},l++)});f.totalStacks=l+1;return f}function y(a){var b=a.apply(this,[].slice.call(arguments,1));this.chart.is3d&&this.chart.is3d()&&(b.stroke=this.options.edgeColor||b.fill,b["stroke-width"]=k(this.options.edgeWidth,1));return b}function g(a,b,c){var f=this.chart.is3d&&this.chart.is3d();f&&(this.options.inactiveOtherPoints=!0);a.call(this,
b,c);f&&(this.options.inactiveOtherPoints=!1)}function f(a){for(var b=[],c=1;c<arguments.length;c++)b[c-1]=arguments[c];return this.series.chart.is3d()?this.graphic&&"g"!==this.graphic.element.nodeName:a.apply(this,b)}var b=a.prototype,c=t.perspective;t=m.addEvent;var A=m.extend,k=m.pick;m=m.wrap;m(b,"translate",function(a){a.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&this.translate3dShapes()});m(z.prototype,"justifyDataLabel",function(a){return arguments[2].outside3dPlot?!1:a.apply(this,
[].slice.call(arguments,1))});b.translate3dPoints=function(){};b.translate3dShapes=function(){var a=this,b=a.chart,f=a.options,g=f.depth,k=(f.stacking?f.stack||0:a.index)*(g+(f.groupZPadding||1)),m=a.borderWidth%2?.5:0,n;b.inverted&&!a.yAxis.reversed&&(m*=-1);!1!==f.grouping&&(k=0);k+=f.groupZPadding||1;a.data.forEach(function(f){f.outside3dPlot=null;if(null!==f.y){var l=A({x:0,y:0,width:0,height:0},f.shapeArgs||{}),p=f.tooltipPos,h;[["x","width"],["y","height"]].forEach(function(b){h=l[b[0]]-m;0>
h&&(l[b[1]]+=l[b[0]]+m,l[b[0]]=-m,h=0);h+l[b[1]]>a[b[0]+"Axis"].len&&0!==l[b[1]]&&(l[b[1]]=a[b[0]+"Axis"].len-l[b[0]]);if(0!==l[b[1]]&&(l[b[0]]>=a[b[0]+"Axis"].len||l[b[0]]+l[b[1]]<=m)){for(var c in l)l[c]="y"===c?-9999:0;f.outside3dPlot=!0}});"roundedRect"===f.shapeType&&(f.shapeType="cuboid");f.shapeArgs=A(l,{z:k,depth:g,insidePlotArea:!0});n={x:l.x+l.width/2,y:l.y,z:k+g/2};b.inverted&&(n.x=l.height,n.y=f.clientX||0);f.plot3d=c([n],b,!0,!1)[0];p&&(p=c([{x:p[0],y:p[1],z:k+g/2}],b,!0,!1)[0],f.tooltipPos=
[p.x,p.y])}});a.z=k};m(b,"animate",function(a){if(this.chart.is3d()){var b=this.yAxis,c=this,f=this.yAxis.reversed;arguments[1]?c.data.forEach(function(a){null!==a.y&&(a.height=a.shapeArgs.height,a.shapey=a.shapeArgs.y,a.shapeArgs.height=1,f||(a.shapeArgs.y=a.stackY?a.plotY+b.translate(a.stackY):a.plotY+(a.negative?-a.height:a.height)))}):(c.data.forEach(function(a){if(null!==a.y&&(a.shapeArgs.height=a.height,a.shapeArgs.y=a.shapey,a.graphic))a.graphic[a.outside3dPlot?"attr":"animate"](a.shapeArgs,
c.options.animation)}),this.drawDataLabels())}else a.apply(this,[].slice.call(arguments,1))});m(b,"plotGroup",function(a,b,c,f,g,k){"dataLabelsGroup"!==b&&"markerGroup"!==b&&this.chart.is3d()&&(this[b]&&delete this[b],k&&(this.chart.columnGroup||(this.chart.columnGroup=this.chart.renderer.g("columnGroup").add(k)),this[b]=this.chart.columnGroup,this.chart.columnGroup.attr(this.getPlotBox()),this[b].survive=!0,"group"===b&&(arguments[3]="visible")));return a.apply(this,Array.prototype.slice.call(arguments,
1))});m(b,"setVisible",function(a,b){var c=this;c.chart.is3d()&&c.data.forEach(function(a){a.visible=a.options.visible=b="undefined"===typeof b?!k(c.visible,a.visible):b;c.options.data[c.data.indexOf(a)]=a.options;a.graphic&&a.graphic.attr({visibility:b?"visible":"hidden"})});a.apply(this,Array.prototype.slice.call(arguments,1))});t(a,"afterInit",function(){if(this.chart.is3d()){var a=this.options,b=a.grouping,c=a.stacking,f=this.yAxis.options.reversedStacks,g=0;if("undefined"===typeof b||b){b=B(this.chart,
c);g=a.stack||0;for(c=0;c<b[g].series.length&&b[g].series[c]!==this;c++);g=10*(b.totalStacks-b[g].position)+(f?c:-c);this.xAxis.reversed||(g=10*b.totalStacks-g)}a.depth=a.depth||25;this.z=this.z||0;a.zIndex=g}});m(b,"pointAttribs",y);m(b,"setState",g);m(b.pointClass.prototype,"hasNewShapeType",f);C.seriesTypes.columnRange&&(t=C.seriesTypes.columnrange.prototype,m(t,"pointAttribs",y),m(t,"setState",g),m(t.pointClass.prototype,"hasNewShapeType",f),t.plotGroup=b.plotGroup,t.setVisible=b.setVisible);
m(z.prototype,"alignDataLabel",function(a,b,f,g,m){var l=this.chart;g.outside3dPlot=b.outside3dPlot;if(l.is3d()&&this.is("column")){var n=this.options,p=k(g.inside,!!this.options.stacking),w=l.options.chart.options3d,y=b.pointWidth/2||0;n={x:m.x+y,y:m.y,z:this.z+n.depth/2};l.inverted&&(p&&(m.width=0,n.x+=b.shapeArgs.height/2),90<=w.alpha&&270>=w.alpha&&(n.y+=b.shapeArgs.width));n=c([n],l,!0,!1)[0];m.x=n.x-y;m.y=b.outside3dPlot?-9E9:n.y}a.apply(this,[].slice.call(arguments,1))});m(n.prototype,"getStackBox",
function(a,b){var f=a.apply(this,[].slice.call(arguments,1)),g=this.axis.chart,k=b.width;if(g.is3d()&&this.base){var l=+this.base.split(",")[0],m=g.series[l];l=g.options.chart.options3d;m&&m instanceof C.seriesTypes.column&&(m={x:f.x+(g.inverted?f.height:k/2),y:f.y,z:m.options.depth/2},g.inverted&&(f.width=0,90<=l.alpha&&270>=l.alpha&&(m.y+=k)),m=c([m],g,!0,!1)[0],f.x=m.x-k/2,f.y=m.y)}return f});"";return a});D(a,"Series/Pie3D/Pie3DPoint.js",[a["Core/Series/SeriesRegistry.js"]],function(a){var A=
this&&this.__extends||function(){function a(n,m){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,m){a.__proto__=m}||function(a,m){for(var g in m)Object.prototype.hasOwnProperty.call(m,g)&&(a[g]=m[g])};return a(n,m)}return function(n,m){function t(){this.constructor=n}if("function"!==typeof m&&null!==m)throw new TypeError("Class extends value "+String(m)+" is not a constructor or null");a(n,m);n.prototype=null===m?Object.create(m):(t.prototype=m.prototype,new t)}}();a=a.seriesTypes.pie.prototype.pointClass;
var t=a.prototype.haloPath;return function(a){function n(){var m=null!==a&&a.apply(this,arguments)||this;m.series=void 0;return m}A(n,a);n.prototype.haloPath=function(){var a;return(null===(a=this.series)||void 0===a?0:a.chart.is3d())?[]:t.apply(this,arguments)};return n}(a)});D(a,"Series/Pie3D/Pie3DSeries.js",[a["Core/Globals.js"],a["Series/Pie3D/Pie3DPoint.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,z,t,C){var n=this&&this.__extends||function(){function a(g,f){a=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)Object.prototype.hasOwnProperty.call(c,b)&&(a[b]=c[b])};return a(g,f)}return function(g,f){function b(){this.constructor=g}if("function"!==typeof f&&null!==f)throw new TypeError("Class extends value "+String(f)+" is not a constructor or null");a(g,f);g.prototype=null===f?Object.create(f):(b.prototype=f.prototype,new b)}}(),m=a.deg2rad;a=C.extend;var A=C.pick;t=function(a){function g(){return null!==a&&a.apply(this,
arguments)||this}n(g,a);g.prototype.addPoint=function(){a.prototype.addPoint.apply(this,arguments);this.chart.is3d()&&this.update(this.userOptions,!0)};g.prototype.animate=function(f){if(this.chart.is3d()){var b=this.options.animation;var c=this.center;var g=this.group,k=this.markerGroup;!0===b&&(b={});f?(g.oldtranslateX=A(g.oldtranslateX,g.translateX),g.oldtranslateY=A(g.oldtranslateY,g.translateY),c={translateX:c[0],translateY:c[1],scaleX:.001,scaleY:.001},g.attr(c),k&&(k.attrSetters=g.attrSetters,
k.attr(c))):(c={translateX:g.oldtranslateX,translateY:g.oldtranslateY,scaleX:1,scaleY:1},g.animate(c,b),k&&k.animate(c,b))}else a.prototype.animate.apply(this,arguments)};g.prototype.drawDataLabels=function(){if(this.chart.is3d()){var f=this.chart.options.chart.options3d;this.data.forEach(function(a){var b=a.shapeArgs,g=b.r,k=(b.start+b.end)/2;a=a.labelPosition;var n=a.connectorPosition,l=-g*(1-Math.cos((b.alpha||f.alpha)*m))*Math.sin(k),t=g*(Math.cos((b.beta||f.beta)*m)-1)*Math.cos(k);[a.natural,
n.breakAt,n.touchingSliceAt].forEach(function(a){a.x+=t;a.y+=l})})}a.prototype.drawDataLabels.apply(this,arguments)};g.prototype.pointAttribs=function(f){var b=a.prototype.pointAttribs.apply(this,arguments),c=this.options;this.chart.is3d()&&!this.chart.styledMode&&(b.stroke=c.edgeColor||f.color||this.color,b["stroke-width"]=A(c.edgeWidth,1));return b};g.prototype.translate=function(){a.prototype.translate.apply(this,arguments);if(this.chart.is3d()){var f=this,b=f.options,c=b.depth||0,g=f.chart.options.chart.options3d,
k=g.alpha,n=g.beta,l=b.stacking?(b.stack||0)*c:f._i*c;l+=c/2;!1!==b.grouping&&(l=0);f.data.forEach(function(a){var g=a.shapeArgs;a.shapeType="arc3d";g.z=l;g.depth=.75*c;g.alpha=k;g.beta=n;g.center=f.center;g=(g.end+g.start)/2;a.slicedTranslation={translateX:Math.round(Math.cos(g)*b.slicedOffset*Math.cos(k*m)),translateY:Math.round(Math.sin(g)*b.slicedOffset*Math.cos(k*m))}})}};g.prototype.drawTracker=function(){a.prototype.drawTracker.apply(this,arguments);this.chart.is3d()&&this.points.forEach(function(a){a.graphic&&
["out","inn","side1","side2"].forEach(function(b){a.graphic&&(a.graphic[b].element.point=a)})})};return g}(t.seriesTypes.pie);a(t.prototype,{pointClass:z});"";return t});D(a,"Series/Pie3D/Pie3DComposition.js",[a["Series/Pie3D/Pie3DPoint.js"],a["Series/Pie3D/Pie3DSeries.js"],a["Core/Series/SeriesRegistry.js"]],function(a,z,t){t.seriesTypes.pie.prototype.pointClass.prototype.haloPath=a.prototype.haloPath;t.seriesTypes.pie=z});D(a,"Series/Scatter3D/Scatter3DPoint.js",[a["Series/Scatter/ScatterSeries.js"],
a["Core/Utilities.js"]],function(a,z){var t=this&&this.__extends||function(){function a(m,n){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,g){a.__proto__=g}||function(a,g){for(var f in g)Object.prototype.hasOwnProperty.call(g,f)&&(a[f]=g[f])};return a(m,n)}return function(m,n){function t(){this.constructor=m}if("function"!==typeof n&&null!==n)throw new TypeError("Class extends value "+String(n)+" is not a constructor or null");a(m,n);m.prototype=null===n?Object.create(n):(t.prototype=
n.prototype,new t)}}(),A=z.defined;return function(a){function m(){var m=null!==a&&a.apply(this,arguments)||this;m.options=void 0;m.series=void 0;return m}t(m,a);m.prototype.applyOptions=function(){a.prototype.applyOptions.apply(this,arguments);A(this.z)||(this.z=0);return this};return m}(a.prototype.pointClass)});D(a,"Series/Scatter3D/Scatter3DSeries.js",[a["Core/Math3D.js"],a["Series/Scatter3D/Scatter3DPoint.js"],a["Series/Scatter/ScatterSeries.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],
function(a,z,t,C,n){var m=this&&this.__extends||function(){function a(f,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};return a(f,b)}return function(f,b){function c(){this.constructor=f}if("function"!==typeof b&&null!==b)throw new TypeError("Class extends value "+String(b)+" is not a constructor or null");a(f,b);f.prototype=null===b?Object.create(b):(c.prototype=b.prototype,
new c)}}(),A=a.pointCameraDistance;a=n.extend;var y=n.merge;n=function(a){function f(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}m(f,a);f.prototype.pointAttribs=function(b){var c=a.prototype.pointAttribs.apply(this,arguments);this.chart.is3d()&&b&&(c.zIndex=A(b,this.chart));return c};f.defaultOptions=y(t.defaultOptions,{tooltip:{pointFormat:"x: <b>{point.x}</b><br/>y: <b>{point.y}</b><br/>z: <b>{point.z}</b><br/>"}});return f}(t);a(n.prototype,
{axisTypes:["xAxis","yAxis","zAxis"],directTouch:!0,parallelArrays:["x","y","z"],pointArrayMap:["x","y","z"],pointClass:z});C.registerSeriesType("scatter3d",n);"";return n});D(a,"masters/highcharts-3d.src.js",[a["Core/Globals.js"],a["Core/Renderer/SVG/SVGRenderer3D.js"],a["Core/Chart/Chart3D.js"],a["Core/Axis/ZAxis.js"],a["Core/Axis/Axis3DComposition.js"],a["Series/Area3D/Area3DSeries.js"]],function(a,z,t,C,n,m){z.compose(a.SVGRenderer);t.compose(a.Chart,a.Fx);C.compose(a.Chart);n.compose(a.Axis,
a.Tick);m.compose(a.seriesTypes.area)})});//# sourceMappingURL=highcharts-3d.js.map