/*
 Highcharts JS v11.1.0 (2023-08-20)

 Annotations module

 (c) 2009-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/annotations",["highcharts"],function(l){c(l);c.Highcharts=l;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function l(c,g,v,k){c.hasOwnProperty(g)||(c[g]=k.apply(null,v),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:g,module:c[g]}})))}c=c?c._modules:
{};l(c,"Extensions/Annotations/AnnotationChart.js",[c["Core/Utilities.js"]],function(c){function g(a,b){a=this.initAnnotation(a);this.options.annotations.push(a.options);q(b,!0)&&(a.redraw(),a.graphic.attr({opacity:1}));return a}function p(){var a=this;a.plotBoxClip=this.renderer.clipRect(this.plotBox);a.controlPointsGroup=a.renderer.g("control-points").attr({zIndex:99}).clip(a.plotBoxClip).add();a.options.annotations.forEach(function(b,e){if(!a.annotations.some(function(a){return a.options===b})){var d=
a.initAnnotation(b);a.options.annotations[e]=d.options}});a.drawAnnotations();b(a,"redraw",a.drawAnnotations);b(a,"destroy",function(){a.plotBoxClip.destroy();a.controlPointsGroup.destroy()});b(a,"exportData",function(b){function e(a){if(d){var b=d(a);if(!1!==b)return b}b=f+" "+a;return q?{columnTitle:b,topLevelColumnTitle:b}:b}var d=(this.options.exporting&&this.options.exporting.csv||{}).columnHeaderFormatter,q=!b.dataRows[1].xValues,f=a.options.lang&&a.options.lang.exportData&&a.options.lang.exportData.annotationHeader,
J=b.dataRows[0].length,t=a.options.exporting&&a.options.exporting.csv&&a.options.exporting.csv.annotations&&a.options.exporting.csv.annotations.itemDelimiter,c=a.options.exporting&&a.options.exporting.csv&&a.options.exporting.csv.annotations&&a.options.exporting.csv.annotations.join;a.annotations.forEach(function(a){a.options.labelOptions&&a.options.labelOptions.includeInDataExport&&a.labels.forEach(function(a){if(a.options.text){var e=a.options.text;a.points.forEach(function(a){var d=a.x,q=a.series.xAxis?
a.series.xAxis.index:-1,f=!1;if(-1===q){a=b.dataRows[0].length;for(var n=Array(a),r=0;r<a;++r)n[r]="";n.push(e);n.xValues=[];n.xValues[q]=d;b.dataRows.push(n);f=!0}f||b.dataRows.forEach(function(a){!f&&a.xValues&&void 0!==q&&d===a.xValues[q]&&(c&&a.length>J?a[a.length-1]+=t+e:a.push(e),f=!0)});if(!f){a=b.dataRows[0].length;n=Array(a);for(r=0;r<a;++r)n[r]="";n[0]=d;n.push(e);n.xValues=[];void 0!==q&&(n.xValues[q]=d);b.dataRows.push(n)}})}})});var m=0;b.dataRows.forEach(function(a){m=Math.max(m,a.length)});
for(var z=m-b.dataRows[0].length,h=0;h<z;h++){var H=e(h+1);q?(b.dataRows[0].push(H.topLevelColumnTitle),b.dataRows[1].push(H.columnTitle)):b.dataRows[0].push(H)}})}function k(){this.plotBoxClip.attr(this.plotBox);this.annotations.forEach(function(a){a.redraw();a.graphic.animate({opacity:1},a.animationConfig)})}function h(a){var b=this.annotations,d="annotations"===a.coll?a:f(b,function(b){return b.options.id===a});d&&(J(d,"remove"),e(this.options.annotations,d.options),e(b,d),d.destroy())}function d(){this.annotations=
[];this.options.annotations||(this.options.annotations=[])}function a(a){this.chart.hasDraggedAnnotation||a.apply(this,Array.prototype.slice.call(arguments,1))}var b=c.addEvent,e=c.erase,f=c.find,J=c.fireEvent,q=c.pick,y=c.wrap,z=[],m;(function(e){e.compose=function(e,q,f){c.pushUnique(z,q)&&(b(q,"afterInit",d),q=q.prototype,q.addAnnotation=g,q.callbacks.push(p),q.collectionsWithInit.annotations=[g],q.collectionsWithUpdate.push("annotations"),q.drawAnnotations=k,q.removeAnnotation=h,q.initAnnotation=
function(a){a=new (e.types[a.type]||e)(this,a);this.annotations.push(a);return a});c.pushUnique(z,f)&&y(f.prototype,"onContainerMouseDown",a)}})(m||(m={}));return m});l(c,"Extensions/Annotations/AnnotationDefaults.js",[c["Core/Utilities.js"]],function(c){var g=c.defined;return{visible:!0,animation:{},crop:!0,draggable:"xy",labelOptions:{align:"center",allowOverlap:!1,backgroundColor:"rgba(0, 0, 0, 0.75)",borderColor:"#000000",borderRadius:3,borderWidth:1,className:"highcharts-no-tooltip",crop:!1,
formatter:function(){return g(this.y)?""+this.y:"Annotation label"},includeInDataExport:!0,overflow:"justify",padding:5,shadow:!1,shape:"callout",style:{fontSize:"0.7em",fontWeight:"normal",color:"contrast"},useHTML:!1,verticalAlign:"bottom",x:0,y:-16},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1,fill:"rgba(0, 0, 0, 0.75)",r:0,snap:2},controlPointOptions:{events:{},style:{cursor:"pointer",fill:"#ffffff",stroke:"#000000","stroke-width":2},height:10,symbol:"circle",visible:!1,width:10},
events:{},zIndex:6}});l(c,"Extensions/Annotations/EventEmitter.js",[c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,g){var p=c.doc,k=c.isTouchDevice,h=g.addEvent,d=g.fireEvent,a=g.objectEach,b=g.pick,e=g.removeEvent;return function(){function f(){}f.prototype.addEvents=function(){function b(a){h(a,k?"touchstart":"mousedown",function(a){e.onMouseDown(a)},{passive:!1})}var e=this;b(this.graphic.element);(e.labels||[]).forEach(function(a){a.options.useHTML&&a.graphic.text&&b(a.graphic.text.element)});
a(e.options.events,function(a,b){function d(d){"click"===b&&e.cancelClick||a.call(e,e.chart.pointer.normalize(d),e.target)}if(-1===(e.nonDOMEvents||[]).indexOf(b))e.graphic.on(b,d);else h(e,b,d,{passive:!1})});if(e.options.draggable&&(h(e,"drag",e.onDrag),!e.graphic.renderer.styledMode)){var f={cursor:{x:"ew-resize",y:"ns-resize",xy:"move"}[e.options.draggable]};e.graphic.css(f);(e.labels||[]).forEach(function(a){a.options.useHTML&&a.graphic.text&&a.graphic.text.css(f)})}e.isUpdating||d(e,"add")};
f.prototype.destroy=function(){this.removeDocEvents();e(this);this.hcEvents=null};f.prototype.mouseMoveToRadians=function(a,b,e){var d=a.prevChartY-e,f=a.prevChartX-b;e=a.chartY-e;a=a.chartX-b;this.chart.inverted&&(b=f,f=d,d=b,b=a,a=e,e=b);return Math.atan2(e,a)-Math.atan2(d,f)};f.prototype.mouseMoveToScale=function(a,b,e){b=(a.chartX-b||1)/(a.prevChartX-b||1);a=(a.chartY-e||1)/(a.prevChartY-e||1);this.chart.inverted&&(e=a,a=b,b=e);return{x:b,y:a}};f.prototype.mouseMoveToTranslation=function(a){var b=
a.chartX-a.prevChartX;a=a.chartY-a.prevChartY;if(this.chart.inverted){var e=a;a=b;b=e}return{x:b,y:a}};f.prototype.onDrag=function(a){if(this.chart.isInsidePlot(a.chartX-this.chart.plotLeft,a.chartY-this.chart.plotTop,{visiblePlotOnly:!0})){var b=this.mouseMoveToTranslation(a);"x"===this.options.draggable&&(b.y=0);"y"===this.options.draggable&&(b.x=0);this.points.length?this.translate(b.x,b.y):(this.shapes.forEach(function(a){return a.translate(b.x,b.y)}),this.labels.forEach(function(a){return a.translate(b.x,
b.y)}));this.redraw(!1)}};f.prototype.onMouseDown=function(a){a.preventDefault&&a.preventDefault();if(2!==a.button){var e=this,f=e.chart.pointer;a=f.normalize(a);var c=a.chartX,m=a.chartY;e.cancelClick=!1;e.chart.hasDraggedAnnotation=!0;e.removeDrag=h(p,k?"touchmove":"mousemove",function(a){e.hasDragged=!0;a=f.normalize(a);a.prevChartX=c;a.prevChartY=m;d(e,"drag",a);c=a.chartX;m=a.chartY},k?{passive:!1}:void 0);e.removeMouseUp=h(p,k?"touchend":"mouseup",function(a){var f=b(e.target&&e.target.annotation,
e.target);f&&(f.cancelClick=e.hasDragged);e.cancelClick=e.hasDragged;e.hasDragged=!1;e.chart.hasDraggedAnnotation=!1;d(b(f,e),"afterUpdate");e.onMouseUp(a)},k?{passive:!1}:void 0)}};f.prototype.onMouseUp=function(){var a=this.chart,b=this.target||this,e=a.options.annotations;a=a.annotations.indexOf(b);this.removeDocEvents();e[a]=b.options};f.prototype.removeDocEvents=function(){this.removeDrag&&(this.removeDrag=this.removeDrag());this.removeMouseUp&&(this.removeMouseUp=this.removeMouseUp())};return f}()});
l(c,"Extensions/Annotations/ControlPoint.js",[c["Extensions/Annotations/EventEmitter.js"],c["Core/Utilities.js"]],function(c,g){var p=this&&this.__extends||function(){function d(a,b){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var e in b)Object.prototype.hasOwnProperty.call(b,e)&&(a[e]=b[e])};return d(a,b)}return function(a,b){function e(){this.constructor=a}if("function"!==typeof b&&null!==b)throw new TypeError("Class extends value "+String(b)+
" is not a constructor or null");d(a,b);a.prototype=null===b?Object.create(b):(e.prototype=b.prototype,new e)}}(),k=g.merge,h=g.pick;c=function(d){function a(a,e,f,c){var b=d.call(this)||this;b.graphic=void 0;b.nonDOMEvents=["drag"];b.chart=a;b.target=e;b.options=f;b.index=h(f.index,c);return b}p(a,d);a.prototype.destroy=function(){d.prototype.destroy.call(this);this.graphic&&(this.graphic=this.graphic.destroy());this.options=this.target=this.chart=null};a.prototype.redraw=function(a){this.graphic[a?
"animate":"attr"](this.options.positioner.call(this,this.target))};a.prototype.render=function(){var a=this.chart,e=this.options;this.graphic=a.renderer.symbol(e.symbol,0,0,e.width,e.height).add(a.controlPointsGroup).css(e.style);this.setVisibility(e.visible);this.addEvents()};a.prototype.setVisibility=function(a){this.graphic[a?"show":"hide"]();this.options.visible=a};a.prototype.update=function(a){var b=this.chart,d=this.target,c=this.index;a=k(!0,this.options,a);this.destroy();this.constructor(b,
d,a,c);this.render(b.controlPointsGroup);this.redraw()};return a}(c);"";return c});l(c,"Extensions/Annotations/MockPoint.js",[c["Core/Series/SeriesRegistry.js"],c["Core/Utilities.js"]],function(c,g){var p=c.series.prototype,k=g.defined,h=g.fireEvent;c=function(){function d(a,b,e){this.plotY=this.plotX=void 0;this.mock=!0;this.series={visible:!0,chart:a,getPlotBox:p.getPlotBox};this.target=b||null;this.options=e;this.applyOptions(this.getOptions())}d.fromPoint=function(a){return new d(a.series.chart,
null,{x:a.x,y:a.y,xAxis:a.series.xAxis,yAxis:a.series.yAxis})};d.pointToPixels=function(a,b){var e=a.series,d=e.chart,c=a.plotX||0,h=a.plotY||0;d.inverted&&(a.mock?(c=a.plotY,h=a.plotX):(c=d.plotWidth-(a.plotY||0),h=d.plotHeight-(a.plotX||0)));e&&!b&&(a=e.getPlotBox(),c+=a.translateX,h+=a.translateY);return{x:c,y:h}};d.pointToOptions=function(a){return{x:a.x,y:a.y,xAxis:a.series.xAxis,yAxis:a.series.yAxis}};d.prototype.applyOptions=function(a){this.command=a.command;this.setAxis(a,"x");this.setAxis(a,
"y");this.refresh()};d.prototype.getLabelConfig=function(){return{x:this.x,y:this.y,point:this}};d.prototype.getOptions=function(){return this.hasDynamicOptions()?this.options(this.target):this.options};d.prototype.hasDynamicOptions=function(){return"function"===typeof this.options};d.prototype.isInsidePlot=function(){var a=this.plotX,b=this.plotY,e=this.series.xAxis,d=this.series.yAxis,c={x:a,y:b,isInsidePlot:!0,options:{}};e&&(c.isInsidePlot=k(a)&&0<=a&&a<=e.len);d&&(c.isInsidePlot=c.isInsidePlot&&
k(b)&&0<=b&&b<=d.len);h(this.series.chart,"afterIsInsidePlot",c);return c.isInsidePlot};d.prototype.refresh=function(){var a=this.series,b=a.xAxis;a=a.yAxis;var e=this.getOptions();b?(this.x=e.x,this.plotX=b.toPixels(e.x,!0)):(this.x=void 0,this.plotX=e.x);a?(this.y=e.y,this.plotY=a.toPixels(e.y,!0)):(this.y=null,this.plotY=e.y);this.isInside=this.isInsidePlot()};d.prototype.refreshOptions=function(){var a=this.series,b=a.xAxis;a=a.yAxis;this.x=this.options.x=b?this.options.x=b.toValue(this.plotX,
!0):this.plotX;this.y=this.options.y=a?a.toValue(this.plotY,!0):this.plotY};d.prototype.rotate=function(a,b,e){if(!this.hasDynamicOptions()){var d=Math.cos(e);e=Math.sin(e);var c=this.plotX-a,h=this.plotY-b;this.plotX=c*d-h*e+a;this.plotY=c*e+h*d+b;this.refreshOptions()}};d.prototype.scale=function(a,b,e,d){if(!this.hasDynamicOptions()){var c=this.plotY*d;this.plotX=(1-e)*a+this.plotX*e;this.plotY=(1-d)*b+c;this.refreshOptions()}};d.prototype.setAxis=function(a,b){b+="Axis";a=a[b];var e=this.series.chart;
this.series[b]="object"===typeof a?a:k(a)?e[b][a]||e.get(a):null};d.prototype.toAnchor=function(){var a=[this.plotX,this.plotY,0,0];this.series.chart.inverted&&(a[0]=this.plotY,a[1]=this.plotX);return a};d.prototype.translate=function(a,b,e,d){this.hasDynamicOptions()||(this.plotX+=e,this.plotY+=d,this.refreshOptions())};return d}();"";return c});l(c,"Extensions/Annotations/ControlTarget.js",[c["Extensions/Annotations/ControlPoint.js"],c["Extensions/Annotations/MockPoint.js"],c["Core/Utilities.js"]],
function(c,g,v){var k;(function(h){function d(){var a=this,b=this.controlPoints,e=this.options.controlPoints||[];e.forEach(function(d,f){d=v.merge(a.options.controlPointOptions,d);d.index||(d.index=f);e[f]=d;b.push(new c(a.chart,a,d))})}function a(a){var b=a.series.getPlotBox(),e=a.series.chart,d=a.mock?a.toAnchor():e.tooltip&&e.tooltip.getAnchor.call({chart:a.series.chart},a)||[0,0,0,0];d={x:d[0]+(this.options.x||0),y:d[1]+(this.options.y||0),height:d[2]||0,width:d[3]||0};return{relativePosition:d,
absolutePosition:v.merge(d,{x:d.x+(a.mock?b.translateX:e.plotLeft),y:d.y+(a.mock?b.translateY:e.plotTop)})}}function b(){this.controlPoints.forEach(function(a){return a.destroy()});this.options=this.points=this.controlPoints=this.chart=null;this.annotation&&(this.annotation=null)}function e(){var a=this.options;return a.points||a.point&&v.splat(a.point)}function f(){var a=this.getPointsOptions(),b=this.points,e=a&&a.length||0,d;for(d=0;d<e;d++){var c=this.point(a[d],b[d]);if(!c){b.length=0;return}c.mock&&
c.refresh();b[d]=c}return b}function k(a,b){if(a&&a.series)return a;b&&null!==b.series||(v.isObject(a)?b=new g(this.chart,this,a):v.isString(a)?b=this.chart.get(a)||null:"function"===typeof a&&(b=a.call(b,this),b=b.series?b:new g(this.chart,this,a)));return b}function q(a){this.controlPoints.forEach(function(b){return b.redraw(a)})}function y(){this.controlPoints.forEach(function(a){return a.render()})}function z(a,b,e,d,c){var f=this;if(this.chart.inverted){var m=b;b=e;e=m}this.points.forEach(function(m,
h){return f.transformPoint(a,b,e,d,c,h)},this)}function m(a,b,e,d,c,f){var m=this.points[f];m.mock||(m=this.points[f]=g.fromPoint(m));m[a](b,e,d,c)}function t(a,b){this.transform("translate",null,null,a,b)}function E(a,b,e){this.transformPoint("translate",null,null,a,b,e)}var B=[];h.compose=function(c){v.pushUnique(B,c)&&v.merge(!0,c.prototype,{addControlPoints:d,anchor:a,destroyControlTarget:b,getPointsOptions:e,linkPoints:f,point:k,redrawControlPoints:q,renderControlPoints:y,transform:z,transformPoint:m,
translate:t,translatePoint:E})}})(k||(k={}));return k});l(c,"Extensions/Annotations/Controllables/Controllable.js",[c["Extensions/Annotations/ControlTarget.js"],c["Core/Utilities.js"]],function(c,g){var p=g.merge;g=function(){function c(c,d,a,b){this.graphic=void 0;this.annotation=c;this.chart=c.chart;this.collection="label"===b?"labels":"shapes";this.controlPoints=[];this.options=d;this.points=[];this.index=a;this.itemType=b;this.init(c,d,a)}c.prototype.attr=function(){for(var c=0;c<arguments.length;c++);
this.graphic.attr.apply(this.graphic,arguments)};c.prototype.attrsFromOptions=function(c){var d=this.constructor.attrsMap,a={},b=this.chart.styledMode,e;for(e in c){var f=d[e];"undefined"===typeof d[e]||b&&-1!==["fill","stroke","stroke-width"].indexOf(f)||(a[f]=c[e])}return a};c.prototype.destroy=function(){this.graphic&&(this.graphic=this.graphic.destroy());this.tracker&&(this.tracker=this.tracker.destroy());this.destroyControlTarget()};c.prototype.init=function(c,d,a){this.annotation=c;this.chart=
c.chart;this.options=d;this.points=[];this.controlPoints=[];this.index=a;this.linkPoints();this.addControlPoints()};c.prototype.redraw=function(c){this.redrawControlPoints(c)};c.prototype.render=function(){this.renderControlPoints()};c.prototype.rotate=function(c,d,a){this.transform("rotate",c,d,a)};c.prototype.scale=function(c,d,a,b){this.transform("scale",c,d,a,b)};c.prototype.setControlPointsVisibility=function(c){this.controlPoints.forEach(function(d){d.setVisibility(c)})};c.prototype.shouldBeDrawn=
function(){return!!this.points.length};c.prototype.translateShape=function(c,d,a){var b=this.annotation.chart,e=this.annotation.userOptions,f=b.annotations.indexOf(this.annotation);b=b.options.annotations[f];this.translatePoint(c,d,0);a&&this.translatePoint(c,d,1);b[this.collection][this.index].point=this.options.point;e[this.collection][this.index].point=this.options.point};c.prototype.update=function(c){var d=this.annotation,a=p(!0,this.options,c);c=this.graphic.parentGroup;var b=this.constructor;
this.destroy();d=new b(d,a,this.index,this.itemType);p(!0,this,d);this.render(c);this.redraw()};return c}();c.compose(g);"";return g});l(c,"Extensions/Annotations/Controllables/ControllableDefaults.js",[],function(){return{defaultMarkers:{arrow:{tagName:"marker",attributes:{id:"arrow",refY:5,refX:9,markerWidth:10,markerHeight:10},children:[{tagName:"path",attributes:{d:"M 0 0 L 10 5 L 0 10 Z","stroke-width":0}}]},"reverse-arrow":{tagName:"marker",attributes:{id:"reverse-arrow",refY:5,refX:1,markerWidth:10,
markerHeight:10},children:[{tagName:"path",attributes:{d:"M 0 5 L 10 0 L 10 10 Z","stroke-width":0}}]}}}});l(c,"Extensions/Annotations/Controllables/ControllablePath.js",[c["Extensions/Annotations/Controllables/Controllable.js"],c["Extensions/Annotations/Controllables/ControllableDefaults.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,g,v,k){function h(a){return function(b){this.attr(a,"url(#"+b+")")}}function d(){this.options.defs=y(e,this.options.defs||{})}function a(a,b){var e={attributes:{id:a}},
d={stroke:b.color||"none",fill:b.color||"rgba(0, 0, 0, 0.75)"};e.children=b.children&&b.children.map(function(a){return y(d,a)});b=y(!0,{attributes:{markerWidth:20,markerHeight:20,refX:0,refY:0,orient:"auto"}},b,e);b=this.definition(b);b.id=a;return b}var b=this&&this.__extends||function(){function a(b,e){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var e in b)Object.prototype.hasOwnProperty.call(b,e)&&(a[e]=b[e])};return a(b,e)}return function(b,
e){function d(){this.constructor=b}if("function"!==typeof e&&null!==e)throw new TypeError("Class extends value "+String(e)+" is not a constructor or null");a(b,e);b.prototype=null===e?Object.create(e):(d.prototype=e.prototype,new d)}}(),e=g.defaultMarkers,f=k.addEvent,J=k.defined,q=k.extend,y=k.merge,z=k.uniqueKey,m=[],t=h("marker-end"),E=h("marker-start"),B="rgba(192,192,192,"+(v.svg?.0001:.002)+")";return function(e){function c(a,b,d){a=e.call(this,a,b,d,"shape")||this;a.type="path";return a}b(c,
e);c.compose=function(b,e){k.pushUnique(m,b)&&f(b,"afterGetContainer",d);k.pushUnique(m,e)&&(e.prototype.addMarker=a)};c.prototype.toD=function(){var a=this.options.d;if(a)return"function"===typeof a?a.call(this):a;a=this.points;var b=a.length,e=[],d=b,c=a[0],f=d&&this.anchor(c).absolutePosition,m=0;if(f)for(e.push(["M",f.x,f.y]);++m<b&&d;)c=a[m],d=c.command||"L",f=this.anchor(c).absolutePosition,"M"===d?e.push([d,f.x,f.y]):"L"===d?e.push([d,f.x,f.y]):"Z"===d&&e.push([d]),d=c.series.visible;return d&&
this.graphic?this.chart.renderer.crispLine(e,this.graphic.strokeWidth()):null};c.prototype.shouldBeDrawn=function(){return e.prototype.shouldBeDrawn.call(this)||!!this.options.d};c.prototype.render=function(a){var b=this.options,d=this.attrsFromOptions(b);this.graphic=this.annotation.chart.renderer.path([["M",0,0]]).attr(d).add(a);b.className&&this.graphic.addClass(b.className);this.tracker=this.annotation.chart.renderer.path([["M",0,0]]).addClass("highcharts-tracker-line").attr({zIndex:2}).add(a);
this.annotation.chart.styledMode||this.tracker.attr({"stroke-linejoin":"round",stroke:B,fill:B,"stroke-width":this.graphic.strokeWidth()+2*b.snap});e.prototype.render.call(this);q(this.graphic,{markerStartSetter:E,markerEndSetter:t});this.setMarkers(this)};c.prototype.redraw=function(a){if(this.graphic){var b=this.toD(),d=a?"animate":"attr";b?(this.graphic[d]({d:b}),this.tracker[d]({d:b})):(this.graphic.attr({d:"M 0 -9000000000"}),this.tracker.attr({d:"M 0 -9000000000"}));this.graphic.placed=this.tracker.placed=
!!b}e.prototype.redraw.call(this,a)};c.prototype.setMarkers=function(a){var b=a.options,e=a.chart,d=e.options.defs,c=b.fill,f=J(c)&&"none"!==c?c:b.stroke;["markerStart","markerEnd"].forEach(function(c){var m=b[c],n;if(m){for(n in d){var u=d[n];if((m===(u.attributes&&u.attributes.id)||m===u.id)&&"marker"===u.tagName){var t=u;break}}t&&(m=a[c]=e.renderer.addMarker((b.id||z())+"-"+m,y(t,{color:f})),a.attr(c,m.getAttribute("id")))}})};c.attrsMap={dashStyle:"dashstyle",strokeWidth:"stroke-width",stroke:"stroke",
fill:"fill",zIndex:"zIndex"};return c}(c)});l(c,"Extensions/Annotations/Controllables/ControllableRect.js",[c["Extensions/Annotations/Controllables/Controllable.js"],c["Extensions/Annotations/Controllables/ControllablePath.js"],c["Core/Utilities.js"]],function(c,g,v){var k=this&&this.__extends||function(){function d(a,b){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var e in b)Object.prototype.hasOwnProperty.call(b,e)&&(a[e]=b[e])};return d(a,
b)}return function(a,b){function e(){this.constructor=a}if("function"!==typeof b&&null!==b)throw new TypeError("Class extends value "+String(b)+" is not a constructor or null");d(a,b);a.prototype=null===b?Object.create(b):(e.prototype=b.prototype,new e)}}(),h=v.merge;return function(d){function a(a,e,c){a=d.call(this,a,e,c,"shape")||this;a.type="rect";a.translate=d.prototype.translateShape;return a}k(a,d);a.prototype.render=function(a){var b=this.attrsFromOptions(this.options);this.graphic=this.annotation.chart.renderer.rect(0,
-9E9,0,0).attr(b).add(a);d.prototype.render.call(this)};a.prototype.redraw=function(a){if(this.graphic){var b=this.anchor(this.points[0]).absolutePosition;if(b)this.graphic[a?"animate":"attr"]({x:b.x,y:b.y,width:this.options.width,height:this.options.height});else this.attr({x:0,y:-9E9});this.graphic.placed=!!b}d.prototype.redraw.call(this,a)};a.attrsMap=h(g.attrsMap,{width:"width",height:"height"});return a}(c)});l(c,"Extensions/Annotations/Controllables/ControllableCircle.js",[c["Extensions/Annotations/Controllables/Controllable.js"],
c["Extensions/Annotations/Controllables/ControllablePath.js"],c["Core/Utilities.js"]],function(c,g,v){var k=this&&this.__extends||function(){function d(a,b){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var e in b)Object.prototype.hasOwnProperty.call(b,e)&&(a[e]=b[e])};return d(a,b)}return function(a,b){function e(){this.constructor=a}if("function"!==typeof b&&null!==b)throw new TypeError("Class extends value "+String(b)+" is not a constructor or null");
d(a,b);a.prototype=null===b?Object.create(b):(e.prototype=b.prototype,new e)}}(),h=v.merge;return function(d){function a(a,e,c){a=d.call(this,a,e,c,"shape")||this;a.type="circle";a.translate=d.prototype.translateShape;return a}k(a,d);a.prototype.redraw=function(a){if(this.graphic){var b=this.anchor(this.points[0]).absolutePosition;if(b)this.graphic[a?"animate":"attr"]({x:b.x,y:b.y,r:this.options.r});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!b}d.prototype.redraw.call(this,a)};a.prototype.render=
function(a){var b=this.attrsFromOptions(this.options);this.graphic=this.annotation.chart.renderer.circle(0,-9E9,0).attr(b).add(a);d.prototype.render.call(this)};a.prototype.setRadius=function(a){this.options.r=a};a.attrsMap=h(g.attrsMap,{r:"r"});return a}(c)});l(c,"Extensions/Annotations/Controllables/ControllableEllipse.js",[c["Extensions/Annotations/Controllables/Controllable.js"],c["Extensions/Annotations/Controllables/ControllablePath.js"],c["Core/Utilities.js"]],function(c,g,v){var k=this&&this.__extends||
function(){function a(b,e){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var e in b)Object.prototype.hasOwnProperty.call(b,e)&&(a[e]=b[e])};return a(b,e)}return function(b,e){function d(){this.constructor=b}if("function"!==typeof e&&null!==e)throw new TypeError("Class extends value "+String(e)+" is not a constructor or null");a(b,e);b.prototype=null===e?Object.create(e):(d.prototype=e.prototype,new d)}}(),h=v.merge,d=v.defined;return function(a){function b(b,
d,c){b=a.call(this,b,d,c,"shape")||this;b.type="ellipse";return b}k(b,a);b.prototype.init=function(b,c,h){d(c.yAxis)&&c.points.forEach(function(a){a.yAxis=c.yAxis});d(c.xAxis)&&c.points.forEach(function(a){a.xAxis=c.xAxis});a.prototype.init.call(this,b,c,h)};b.prototype.render=function(b){this.graphic=this.annotation.chart.renderer.createElement("ellipse").attr(this.attrsFromOptions(this.options)).add(b);a.prototype.render.call(this)};b.prototype.translate=function(b,d){a.prototype.translateShape.call(this,
b,d,!0)};b.prototype.getDistanceFromLine=function(a,b,d,c){return Math.abs((b.y-a.y)*d-(b.x-a.x)*c+b.x*a.y-b.y*a.x)/Math.sqrt((b.y-a.y)*(b.y-a.y)+(b.x-a.x)*(b.x-a.x))};b.prototype.getAttrs=function(a,b){var d=a.x,e=a.y,c=b.x,f=b.y;b=(d+c)/2;a=(e+f)/2;var m=Math.sqrt((d-c)*(d-c)/4+(e-f)*(e-f)/4);e=180*Math.atan((f-e)/(c-d))/Math.PI;b<d&&(e+=180);d=this.getRY();return{cx:b,cy:a,rx:m,ry:d,angle:e}};b.prototype.getRY=function(){var a=this.getYAxis();return d(a)?Math.abs(a.toPixels(this.options.ry)-a.toPixels(0)):
this.options.ry};b.prototype.getYAxis=function(){return this.chart.yAxis[this.options.yAxis]};b.prototype.getAbsolutePosition=function(a){return this.anchor(a).absolutePosition};b.prototype.redraw=function(b){if(this.graphic){var d=this.getAbsolutePosition(this.points[0]),e=this.getAbsolutePosition(this.points[1]);e=this.getAttrs(d,e);if(d)this.graphic[b?"animate":"attr"]({cx:e.cx,cy:e.cy,rx:e.rx,ry:e.ry,rotation:e.angle,rotationOriginX:e.cx,rotationOriginY:e.cy});else this.graphic.attr({x:0,y:-9E9});
this.graphic.placed=!!d}a.prototype.redraw.call(this,b)};b.prototype.setYRadius=function(a){var b=this.annotation.userOptions.shapes;this.options.ry=a;b&&b[0]&&(b[0].ry=a,b[0].ry=a)};b.attrsMap=h(g.attrsMap,{ry:"ry"});return b}(c)});l(c,"Extensions/Annotations/Controllables/ControllableLabel.js",[c["Extensions/Annotations/Controllables/Controllable.js"],c["Core/Templating.js"],c["Extensions/Annotations/MockPoint.js"],c["Core/Utilities.js"]],function(c,g,v,k){function h(a,b,d,c,f){var m=f&&f.anchorX;
f=f&&f.anchorY;var t=d/2;if(e(m)&&e(f)){var h=[["M",m,f]];var k=b-f;0>k&&(k=-c-k);k<d&&(t=m<a+d/2?k:d-k);f>b+c?h.push(["L",a+t,b+c]):f<b?h.push(["L",a+t,b]):m<a?h.push(["L",a,b+c/2]):m>a+d&&h.push(["L",a+d,b+c/2])}return h||[]}var d=this&&this.__extends||function(){function a(b,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var d in b)Object.prototype.hasOwnProperty.call(b,d)&&(a[d]=b[d])};return a(b,d)}return function(b,d){function e(){this.constructor=
b}if("function"!==typeof d&&null!==d)throw new TypeError("Class extends value "+String(d)+" is not a constructor or null");a(b,d);b.prototype=null===d?Object.create(d):(e.prototype=d.prototype,new e)}}(),a=g.format,b=k.extend,e=k.isNumber,f=k.pick,p=[];return function(e){function c(a,b,d){return e.call(this,a,b,d,"label")||this}d(c,e);c.alignedPosition=function(a,b){var d=a.align,c=a.verticalAlign,e=(b.x||0)+(a.x||0),f=(b.y||0)+(a.y||0),m,h;"right"===d?m=1:"center"===d&&(m=2);m&&(e+=(b.width-(a.width||
0))/m);"bottom"===c?h=1:"middle"===c&&(h=2);h&&(f+=(b.height-(a.height||0))/h);return{x:Math.round(e),y:Math.round(f)}};c.compose=function(a){k.pushUnique(p,a)&&(a.prototype.symbols.connector=h)};c.justifiedOptions=function(a,b,d,c){var e=d.align,f=d.verticalAlign,m=b.box?0:b.padding||0,h=b.getBBox();b={align:e,verticalAlign:f,x:d.x,y:d.y,width:b.width,height:b.height};d=(c.x||0)-a.plotLeft;c=(c.y||0)-a.plotTop;var k=d+m;0>k&&("right"===e?b.align="left":b.x=(b.x||0)-k);k=d+h.width-m;k>a.plotWidth&&
("left"===e?b.align="right":b.x=(b.x||0)+a.plotWidth-k);k=c+m;0>k&&("bottom"===f?b.verticalAlign="top":b.y=(b.y||0)-k);k=c+h.height-m;k>a.plotHeight&&("top"===f?b.verticalAlign="bottom":b.y=(b.y||0)+a.plotHeight-k);return b};c.prototype.translatePoint=function(a,b){e.prototype.translatePoint.call(this,a,b,0)};c.prototype.translate=function(a,b){var d=this.annotation.chart,c=this.annotation.userOptions,e=d.annotations.indexOf(this.annotation);e=d.options.annotations[e];d.inverted&&(d=a,a=b,b=d);this.options.x+=
a;this.options.y+=b;e[this.collection][this.index].x=this.options.x;e[this.collection][this.index].y=this.options.y;c[this.collection][this.index].x=this.options.x;c[this.collection][this.index].y=this.options.y};c.prototype.render=function(a){var b=this.options,d=this.attrsFromOptions(b),f=b.style;this.graphic=this.annotation.chart.renderer.label("",0,-9999,b.shape,null,null,b.useHTML,null,"annotation-label").attr(d).add(a);this.annotation.chart.styledMode||("contrast"===f.color&&(f.color=this.annotation.chart.renderer.getContrast(-1<
c.shapesWithoutBackground.indexOf(b.shape)?"#FFFFFF":b.backgroundColor)),this.graphic.css(b.style).shadow(b.shadow));b.className&&this.graphic.addClass(b.className);this.graphic.labelrank=b.labelrank;e.prototype.render.call(this)};c.prototype.redraw=function(b){var d=this.options,c=this.text||d.format||d.text,f=this.graphic,h=this.points[0];f?(f.attr({text:c?a(String(c),h.getLabelConfig(),this.annotation.chart):d.formatter.call(h,this)}),d=this.anchor(h),(c=this.position(d))?(f.alignAttr=c,c.anchorX=
d.absolutePosition.x,c.anchorY=d.absolutePosition.y,f[b?"animate":"attr"](c)):f.attr({x:0,y:-9999}),f.placed=!!c,e.prototype.redraw.call(this,b)):this.redraw(b)};c.prototype.anchor=function(a){var b=e.prototype.anchor.apply(this,arguments),d=this.options.x||0,c=this.options.y||0;b.absolutePosition.x-=d;b.absolutePosition.y-=c;b.relativePosition.x-=d;b.relativePosition.y-=c;return b};c.prototype.position=function(a){var d=this.graphic,e=this.annotation.chart,h=e.tooltip,k=this.points[0],g=this.options,
p=a.absolutePosition,q=a.relativePosition,F=k.series.visible&&v.prototype.isInsidePlot.call(k);if(d&&F){var w=d.width;a=void 0===w?0:w;w=d.height;var y=void 0===w?0:w;g.distance&&h?w=h.getPosition.call({chart:e,distance:f(g.distance,16),getPlayingField:h.getPlayingField},a,y,{plotX:q.x,plotY:q.y,negative:k.negative,ttBelow:k.ttBelow,h:q.height||q.width}):g.positioner?w=g.positioner.call(this):(h={x:p.x,y:p.y,width:0,height:0},w=c.alignedPosition(b(g,{width:a,height:y}),h),"justify"===this.options.overflow&&
(w=c.alignedPosition(c.justifiedOptions(e,d,g,w),h)));g.crop&&(d=w.x-e.plotLeft,g=w.y-e.plotTop,F=e.isInsidePlot(d,g)&&e.isInsidePlot(d+a,g+y))}return F?w:null};c.attrsMap={backgroundColor:"fill",borderColor:"stroke",borderWidth:"stroke-width",zIndex:"zIndex",borderRadius:"r",padding:"padding"};c.shapesWithoutBackground=["connector"];return c}(c)});l(c,"Extensions/Annotations/Controllables/ControllableImage.js",[c["Extensions/Annotations/Controllables/Controllable.js"],c["Extensions/Annotations/Controllables/ControllableLabel.js"]],
function(c,g){var p=this&&this.__extends||function(){function c(h,d){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var d in b)Object.prototype.hasOwnProperty.call(b,d)&&(a[d]=b[d])};return c(h,d)}return function(h,d){function a(){this.constructor=h}if("function"!==typeof d&&null!==d)throw new TypeError("Class extends value "+String(d)+" is not a constructor or null");c(h,d);h.prototype=null===d?Object.create(d):(a.prototype=d.prototype,new a)}}();
return function(c){function h(d,a,b){d=c.call(this,d,a,b,"shape")||this;d.type="image";d.translate=c.prototype.translateShape;return d}p(h,c);h.prototype.render=function(d){var a=this.attrsFromOptions(this.options),b=this.options;this.graphic=this.annotation.chart.renderer.image(b.src,0,-9E9,b.width,b.height).attr(a).add(d);this.graphic.width=b.width;this.graphic.height=b.height;c.prototype.render.call(this)};h.prototype.redraw=function(d){if(this.graphic){var a=this.anchor(this.points[0]);if(a=g.prototype.position.call(this,
a))this.graphic[d?"animate":"attr"]({x:a.x,y:a.y});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!a}c.prototype.redraw.call(this,d)};h.attrsMap={width:"width",height:"height",zIndex:"zIndex"};return h}(c)});l(c,"Core/Chart/ChartNavigationComposition.js",[],function(){var c;(function(c){c.compose=function(c){c.navigation||(c.navigation=new g(c));return c};var g=function(){function c(c){this.updates=[];this.chart=c}c.prototype.addUpdate=function(c){this.chart.navigation.updates.push(c)};
c.prototype.update=function(c,d){var a=this;this.updates.forEach(function(b){b.call(a.chart,c,d)})};return c}();c.Additions=g})(c||(c={}));return c});l(c,"Extensions/Annotations/NavigationBindingsUtilities.js",[c["Core/Utilities.js"]],function(c){var g=c.defined,p=c.isNumber,k=c.pick,h={backgroundColor:"string",borderColor:"string",borderRadius:"string",color:"string",fill:"string",fontSize:"string",labels:"string",name:"string",stroke:"string",title:"string"};return{annotationsFieldsTypes:h,getAssignedAxis:function(d){return d.filter(function(a){var b=
a.axis.getExtremes(),d=b.min;b=b.max;var c=k(a.axis.minPointOffset,0);return p(d)&&p(b)&&a.value>=d-c&&a.value<=b+c&&!a.axis.options.isInternal})[0]},getFieldType:function(d,a){d=h[d];a=typeof a;g(d)&&(a=d);return{string:"text",number:"number","boolean":"checkbox"}[a]}}});l(c,"Extensions/Annotations/NavigationBindingsDefaults.js",[c["Extensions/Annotations/NavigationBindingsUtilities.js"],c["Core/Utilities.js"]],function(c,g){var p=c.getAssignedAxis,k=g.isNumber,h=g.merge;return{lang:{navigation:{popup:{simpleShapes:"Simple shapes",
lines:"Lines",circle:"Circle",ellipse:"Ellipse",rectangle:"Rectangle",label:"Label",shapeOptions:"Shape options",typeOptions:"Details",fill:"Fill",format:"Text",strokeWidth:"Line width",stroke:"Line color",title:"Title",name:"Name",labelOptions:"Label options",labels:"Labels",backgroundColor:"Background color",backgroundColors:"Background colors",borderColor:"Border color",borderRadius:"Border radius",borderWidth:"Border width",style:"Style",padding:"Padding",fontSize:"Font size",color:"Color",height:"Height",
shapes:"Shape options"}}},navigation:{bindingsClassName:"highcharts-bindings-container",bindings:{circleAnnotation:{className:"highcharts-circle-annotation",start:function(d){var a=this.chart.pointer.getCoordinates(d);d=p(a.xAxis);a=p(a.yAxis);var b=this.chart.options.navigation;if(d&&a)return this.chart.addAnnotation(h({langKey:"circle",type:"basicAnnotation",shapes:[{type:"circle",point:{x:d.value,y:a.value,xAxis:d.axis.index,yAxis:a.axis.index},r:5}]},b.annotationsOptions,b.bindings.circleAnnotation.annotationsOptions))},
steps:[function(d,a){var b=a.options.shapes;b=b&&b[0]&&b[0].point||{};if(k(b.xAxis)&&k(b.yAxis)){var c=this.chart.inverted;var f=this.chart.xAxis[b.xAxis].toPixels(b.x);b=this.chart.yAxis[b.yAxis].toPixels(b.y);c=Math.max(Math.sqrt(Math.pow(c?b-d.chartX:f-d.chartX,2)+Math.pow(c?f-d.chartY:b-d.chartY,2)),5)}a.update({shapes:[{r:c}]})}]},ellipseAnnotation:{className:"highcharts-ellipse-annotation",start:function(d){var a=this.chart.pointer.getCoordinates(d);d=p(a.xAxis);a=p(a.yAxis);var b=this.chart.options.navigation;
if(d&&a)return this.chart.addAnnotation(h({langKey:"ellipse",type:"basicAnnotation",shapes:[{type:"ellipse",xAxis:d.axis.index,yAxis:a.axis.index,points:[{x:d.value,y:a.value},{x:d.value,y:a.value}],ry:1}]},b.annotationsOptions,b.bindings.ellipseAnnotation.annotationOptions))},steps:[function(d,a){a=a.shapes[0];var b=a.getAbsolutePosition(a.points[1]);a.translatePoint(d.chartX-b.x,d.chartY-b.y,1);a.redraw(!1)},function(d,a){a=a.shapes[0];var b=a.getAbsolutePosition(a.points[0]),c=a.getAbsolutePosition(a.points[1]);
d=a.getDistanceFromLine(b,c,d.chartX,d.chartY);b=a.getYAxis();d=Math.abs(b.toValue(0)-b.toValue(d));a.setYRadius(d);a.redraw(!1)}]},rectangleAnnotation:{className:"highcharts-rectangle-annotation",start:function(d){d=this.chart.pointer.getCoordinates(d);var a=p(d.xAxis),b=p(d.yAxis);if(a&&b){d=a.value;var c=b.value;a=a.axis.index;b=b.axis.index;var f=this.chart.options.navigation;return this.chart.addAnnotation(h({langKey:"rectangle",type:"basicAnnotation",shapes:[{type:"path",points:[{xAxis:a,yAxis:b,
x:d,y:c},{xAxis:a,yAxis:b,x:d,y:c},{xAxis:a,yAxis:b,x:d,y:c},{xAxis:a,yAxis:b,x:d,y:c},{command:"Z"}]}]},f.annotationsOptions,f.bindings.rectangleAnnotation.annotationsOptions))}},steps:[function(c,a){var b=a.options.shapes;b=b&&b[0]&&b[0].points||[];var d=this.chart.pointer.getCoordinates(c);c=p(d.xAxis);d=p(d.yAxis);c&&d&&(c=c.value,d=d.value,b[1].x=c,b[2].x=c,b[2].y=d,b[3].y=d,a.update({shapes:[{points:b}]}))}]},labelAnnotation:{className:"highcharts-label-annotation",start:function(c){var a=this.chart.pointer.getCoordinates(c);
c=p(a.xAxis);a=p(a.yAxis);var b=this.chart.options.navigation;if(c&&a)return this.chart.addAnnotation(h({langKey:"label",type:"basicAnnotation",labelOptions:{format:"{y:.2f}",overflow:"none",crop:!0},labels:[{point:{xAxis:c.axis.index,yAxis:a.axis.index,x:c.value,y:a.value}}]},b.annotationsOptions,b.bindings.labelAnnotation.annotationsOptions))}}},events:{},annotationsOptions:{animation:{defer:0}}}}});l(c,"Extensions/Annotations/NavigationBindings.js",[c["Core/Chart/ChartNavigationComposition.js"],
c["Core/Defaults.js"],c["Core/Templating.js"],c["Core/Globals.js"],c["Extensions/Annotations/NavigationBindingsDefaults.js"],c["Extensions/Annotations/NavigationBindingsUtilities.js"],c["Core/Utilities.js"]],function(c,g,v,k,h,d,a){function b(a,b){var c=r.Element.prototype,d=c.matches||c.msMatchesSelector||c.webkitMatchesSelector,e=null;if(c.closest)e=c.closest.call(a,b);else{do{if(d.call(a,b))return a;a=a.parentElement||a.parentNode}while(null!==a&&1===a.nodeType)}return e}function e(){this.chart.navigationBindings&&
this.chart.navigationBindings.deselectAnnotation()}function f(){this.navigationBindings&&this.navigationBindings.destroy()}function p(){var a=this.options;a&&a.navigation&&a.navigation.bindings&&(this.navigationBindings=new M(this,a.navigation),this.navigationBindings.initEvents(),this.navigationBindings.initUpdate())}function q(){var a=this.navigationBindings;if(this&&a){var b=!1;this.series.forEach(function(a){!a.options.isInternal&&a.visible&&(b=!0)});if(this.navigationBindings&&this.navigationBindings.container&&
this.navigationBindings.container[0]){var c=this.navigationBindings.container[0];u(a.boundClassNames,function(a,d){if(d=c.querySelectorAll("."+d))for(var e=0;e<d.length;e++){var n=d[e],f=n.className;"normal"===a.noDataState?-1!==f.indexOf("highcharts-disabled-btn")&&n.classList.remove("highcharts-disabled-btn"):b?-1!==f.indexOf("highcharts-disabled-btn")&&n.classList.remove("highcharts-disabled-btn"):-1===f.indexOf("highcharts-disabled-btn")&&(n.className+=" highcharts-disabled-btn")}})}}}function y(){this.deselectAnnotation()}
function z(){this.selectedButtonElement=null}function m(a){function b(a){var b=this,d=b.chart.navigationBindings,e=d.activeAnnotation;c&&c.call(b,a);e!==b?(d.deselectAnnotation(),d.activeAnnotation=b,b.setControlPointsVisibility(!0),l(d,"showPopup",{annotation:b,formType:"annotation-toolbar",options:d.annotationToFields(b),onSubmit:function(a){if("remove"===a.actionType)d.activeAnnotation=!1,d.chart.removeAnnotation(b);else{var c={};d.fieldsToOptions(a.fields,c);d.deselectAnnotation();a=c.typeOptions;
"measure"===b.options.type&&(a.crosshairY.enabled=0!==a.crosshairY.strokeWidth,a.crosshairX.enabled=0!==a.crosshairX.strokeWidth);b.update(c)}}})):l(d,"closePopup");a.activeAnnotation=!0}var c=a.prototype.defaultOptions.events&&a.prototype.defaultOptions.events.click,d,e;n(!0,a.prototype.defaultOptions.events,{click:b,touchstart:function(a){d=a.touches[0].clientX;e=a.touches[0].clientY},touchend:function(a){d&&4<=Math.sqrt(Math.pow(d-a.changedTouches[0].clientX,2)+Math.pow(e-a.changedTouches[0].clientY,
2))||b.call(this,a)}})}var t=g.setOptions,E=v.format,B=k.doc,r=k.win,I=d.getFieldType,x=a.addEvent,F=a.attr,w=a.defined,l=a.fireEvent,D=a.isArray,K=a.isFunction,C=a.isNumber,H=a.isObject,n=a.merge,u=a.objectEach,A=a.pick,L=[],M=function(){function d(a,b){this.selectedButton=this.boundClassNames=void 0;this.chart=a;this.options=b;this.eventsToUnbind=[];this.container=this.chart.container.getElementsByClassName(this.options.bindingsClassName||"");this.container.length||(this.container=B.getElementsByClassName(this.options.bindingsClassName||
""))}d.compose=function(b,c){a.pushUnique(L,b)&&(x(b,"remove",e),m(b),u(b.types,function(a){m(a)}));a.pushUnique(L,c)&&(x(c,"destroy",f),x(c,"load",p),x(c,"render",q));a.pushUnique(L,d)&&(x(d,"closePopup",y),x(d,"deselectButton",z));a.pushUnique(L,t)&&t(h)};d.prototype.initEvents=function(){var a=this,b=a.chart,d=a.container,c=a.options;a.boundClassNames={};u(c.bindings||{},function(b){a.boundClassNames[b.className]=b});[].forEach.call(d,function(b){a.eventsToUnbind.push(x(b,"click",function(d){var c=
a.getButtonEvents(b,d);c&&!c.button.classList.contains("highcharts-disabled-btn")&&a.bindingsButtonClick(c.button,c.events,d)}))});u(c.events||{},function(b,c){K(b)&&a.eventsToUnbind.push(x(a,c,b,{passive:!1}))});a.eventsToUnbind.push(x(b.container,"click",function(c){!b.cancelClick&&b.isInsidePlot(c.chartX-b.plotLeft,c.chartY-b.plotTop,{visiblePlotOnly:!0})&&a.bindingsChartClick(this,c)}));a.eventsToUnbind.push(x(b.container,k.isTouchDevice?"touchmove":"mousemove",function(b){a.bindingsContainerMouseMove(this,
b)},k.isTouchDevice?{passive:!1}:void 0))};d.prototype.initUpdate=function(){var a=this;c.compose(this.chart).navigation.addUpdate(function(b){a.update(b)})};d.prototype.bindingsButtonClick=function(a,b,c){var d=this.chart,e=d.renderer.boxWrapper,n=!0;this.selectedButtonElement&&(this.selectedButtonElement.classList===a.classList&&(n=!1),l(this,"deselectButton",{button:this.selectedButtonElement}),this.nextEvent&&(this.currentUserDetails&&"annotations"===this.currentUserDetails.coll&&d.removeAnnotation(this.currentUserDetails),
this.mouseMoveEvent=this.nextEvent=!1));n?(this.selectedButton=b,this.selectedButtonElement=a,l(this,"selectButton",{button:a}),b.init&&b.init.call(this,a,c),(b.start||b.steps)&&d.renderer.boxWrapper.addClass("highcharts-draw-mode")):(d.stockTools&&d.stockTools.toggleButtonActiveClass(a),e.removeClass("highcharts-draw-mode"),this.mouseMoveEvent=this.nextEvent=!1,this.selectedButton=null)};d.prototype.bindingsChartClick=function(a,c){a=this.chart;var d=this.activeAnnotation,e=this.selectedButton;a=
a.renderer.boxWrapper;d&&(d.cancelClick||c.activeAnnotation||!c.target.parentNode||b(c.target,".highcharts-popup")?d.cancelClick&&setTimeout(function(){d.cancelClick=!1},0):l(this,"closePopup"));e&&e.start&&(this.nextEvent?(this.nextEvent(c,this.currentUserDetails),this.steps&&(this.stepIndex++,e.steps[this.stepIndex]?this.mouseMoveEvent=this.nextEvent=e.steps[this.stepIndex]:(l(this,"deselectButton",{button:this.selectedButtonElement}),a.removeClass("highcharts-draw-mode"),e.end&&e.end.call(this,
c,this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1,this.selectedButton=null))):(this.currentUserDetails=e.start.call(this,c))&&e.steps?(this.stepIndex=0,this.steps=!0,this.mouseMoveEvent=this.nextEvent=e.steps[this.stepIndex]):(l(this,"deselectButton",{button:this.selectedButtonElement}),a.removeClass("highcharts-draw-mode"),this.steps=!1,this.selectedButton=null,e.end&&e.end.call(this,c,this.currentUserDetails)))};d.prototype.bindingsContainerMouseMove=function(a,b){this.mouseMoveEvent&&
this.mouseMoveEvent(b,this.currentUserDetails)};d.prototype.fieldsToOptions=function(a,b){u(a,function(a,c){var d=parseFloat(a),e=c.split("."),n=e.length-1;!C(d)||a.match(/px|em/g)||c.match(/format/g)||(a=d);if("undefined"!==a){var f=b;e.forEach(function(b,c){var d=A(e[c+1],"");n===c?f[b]=a:(f[b]||(f[b]=d.match(/\d/g)?[]:{}),f=f[b])})}});return b};d.prototype.deselectAnnotation=function(){this.activeAnnotation&&(this.activeAnnotation.setControlPointsVisibility(!1),this.activeAnnotation=!1)};d.prototype.annotationToFields=
function(a){function b(c,d,e,f,A){if(e&&w(c)&&-1===h.indexOf(d)&&(0<=(e.indexOf&&e.indexOf(d))||e[d]||!0===e))if(D(c))f[d]=[],c.forEach(function(a,c){H(a)?(f[d][c]={},u(a,function(a,e){b(a,e,n[d],f[d][c],d)})):b(a,0,n[d],f[d],d)});else if(H(c)){var g={};D(f)?(f.push(g),g[d]={},g=g[d]):f[d]=g;u(c,function(a,c){b(a,c,0===d?e:n[d],g,d)})}else"format"===d?f[d]=[E(c,a.labels[0].points[0]).toString(),"text"]:D(f)?f.push([c,I(A,c)]):f[d]=[c,I(d,c)]}var c=a.options,e=d.annotationsEditable,n=e.nestedOptions,
f=A(c.type,c.shapes&&c.shapes[0]&&c.shapes[0].type,c.labels&&c.labels[0]&&c.labels[0].type,"label"),h=d.annotationsNonEditable[c.langKey]||[],g={langKey:c.langKey,type:f};u(c,function(a,d){"typeOptions"===d?(g[d]={},u(c[d],function(a,c){b(a,c,n,g[d],c)})):b(a,d,e[f],g,d)});return g};d.prototype.getClickedClassNames=function(a,b){var c=b.target;b=[];for(var d;c&&c.tagName&&((d=F(c,"class"))&&(b=b.concat(d.split(" ").map(function(a){return[a,c]}))),c=c.parentNode,c!==a););return b};d.prototype.getButtonEvents=
function(a,b){var c=this,d;this.getClickedClassNames(a,b).forEach(function(a){c.boundClassNames[a[0]]&&!d&&(d={events:c.boundClassNames[a[0]],button:a[1]})});return d};d.prototype.update=function(a){this.options=n(!0,this.options,a);this.removeEvents();this.initEvents()};d.prototype.removeEvents=function(){this.eventsToUnbind.forEach(function(a){return a()})};d.prototype.destroy=function(){this.removeEvents()};d.annotationsEditable={nestedOptions:{labelOptions:["style","format","backgroundColor"],
labels:["style"],label:["style"],style:["fontSize","color"],background:["fill","strokeWidth","stroke"],innerBackground:["fill","strokeWidth","stroke"],outerBackground:["fill","strokeWidth","stroke"],shapeOptions:["fill","strokeWidth","stroke"],shapes:["fill","strokeWidth","stroke"],line:["strokeWidth","stroke"],backgroundColors:[!0],connector:["fill","strokeWidth","stroke"],crosshairX:["strokeWidth","stroke"],crosshairY:["strokeWidth","stroke"]},circle:["shapes"],ellipse:["shapes"],verticalLine:[],
label:["labelOptions"],measure:["background","crosshairY","crosshairX"],fibonacci:[],tunnel:["background","line","height"],pitchfork:["innerBackground","outerBackground"],rect:["shapes"],crookedLine:[],basicAnnotation:["shapes","labelOptions"]};d.annotationsNonEditable={rectangle:["crosshairX","crosshairY","labelOptions"],ellipse:["labelOptions"],circle:["labelOptions"]};return d}();"";return M});l(c,"Shared/BaseForm.js",[c["Core/Renderer/HTML/AST.js"],c["Core/Utilities.js"]],function(c,g){var p=
g.addEvent,k=g.createElement;return function(){function h(c,a){this.iconsURL=a;this.container=this.createPopupContainer(c);this.closeButton=this.addCloseButton()}h.prototype.createPopupContainer=function(c,a){void 0===a&&(a="highcharts-popup highcharts-no-tooltip");return k("div",{className:a},void 0,c)};h.prototype.addCloseButton=function(c){void 0===c&&(c="highcharts-popup-close");var a=this,b=this.iconsURL,d=k("div",{className:c},void 0,this.container);d.style["background-image"]="url("+(b.match(/png|svg|jpeg|jpg|gif/ig)?
b:b+"close.svg")+")";["click","touchstart"].forEach(function(b){p(d,b,a.closeButtonEvents.bind(a))});return d};h.prototype.closeButtonEvents=function(){this.closePopup()};h.prototype.showPopup=function(d){void 0===d&&(d="highcharts-annotation-toolbar");var a=this.container,b=this.closeButton;this.type=void 0;a.innerHTML=c.emptyHTML;0<=a.className.indexOf(d)&&(a.classList.remove(d),a.removeAttribute("style"));a.appendChild(b);a.style.display="block";a.style.height=""};h.prototype.closePopup=function(){this.container.style.display=
"none"};return h}()});l(c,"Extensions/Annotations/Popup/PopupAnnotations.js",[c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,g){function p(c,f,g,m,t,E){var B=this;if(f){var r=this.addInput,q=this.lang,x,y;e(m,function(d,e){x=""!==g?g+"."+e:e;b(d)&&(!a(d)||a(d)&&b(d[0])?(y=q[e]||e,y.match(/\d/g)||t.push([!0,y,c]),p.call(B,c,f,x,d,t,!1)):t.push([B,x,"annotation",c,d]))});E&&(l(t,function(a){return a[1].match(/format/g)?-1:1}),h&&t.reverse(),t.forEach(function(a){!0===a[0]?d("span",{className:"highcharts-annotation-title"},
void 0,a[2]).appendChild(k.createTextNode(a[1])):(a[4]={value:a[4][0],type:a[4][1]},r.apply(a[0],a.splice(1)))}))}}var k=c.doc,h=c.isFirefox,d=g.createElement,a=g.isArray,b=g.isObject,e=g.objectEach,f=g.pick,l=g.stableSort;return{addForm:function(a,b,c,e){if(a){var f=this.container,h=this.lang,g=d("h2",{className:"highcharts-popup-main-title"},void 0,f);g.appendChild(k.createTextNode(h[b.langKey]||b.langKey||""));g=d("div",{className:"highcharts-popup-lhs-col highcharts-popup-lhs-full"},void 0,f);
var m=d("div",{className:"highcharts-popup-bottom-row"},void 0,f);p.call(this,g,a,"",b,[],!0);this.addButton(m,e?h.addButton||"Add":h.saveButton||"Save",e?"add":"save",f,c)}},addToolbar:function(a,b,c){var e=this,h=this.lang,g=this.container,p=this.showForm;-1===g.className.indexOf("highcharts-annotation-toolbar")&&(g.className+=" highcharts-annotation-toolbar");a&&(g.style.top=a.plotTop+10+"px");d("span",void 0,void 0,g).appendChild(k.createTextNode(f(h[b.langKey]||b.langKey,b.shapes&&b.shapes[0].type,
"")));var r=this.addButton(g,h.removeButton||"Remove","remove",g,c);r.className+=" highcharts-annotation-remove-button";r.style["background-image"]="url("+this.iconsURL+"destroy.svg)";r=this.addButton(g,h.editButton||"Edit","edit",g,function(){p.call(e,"annotation-edit",a,b,c)});r.className+=" highcharts-annotation-edit-button";r.style["background-image"]="url("+this.iconsURL+"edit.svg)"}}});l(c,"Extensions/Annotations/Popup/PopupIndicators.js",[c["Core/Renderer/HTML/AST.js"],c["Core/Globals.js"],
c["Extensions/Annotations/NavigationBindingsUtilities.js"],c["Core/Series/SeriesRegistry.js"],c["Core/Utilities.js"]],function(c,g,l,k,h){function d(a){var b=r("div",{className:"highcharts-popup-lhs-col"},void 0,a);a=r("div",{className:"highcharts-popup-rhs-col"},void 0,a);r("div",{className:"highcharts-popup-rhs-col-wrapper"},void 0,a);return{lhsCol:b,rhsCol:a}}function a(a,d,e,f){var n=this,h=n.lang,u=d.querySelectorAll(".highcharts-popup-lhs-col")[0];d=d.querySelectorAll(".highcharts-popup-rhs-col")[0];
var g="edit"===e;e=g?a.series:a.options.plotOptions||{};if(a||!e){var H,k=[];g||x(e)?x(e)&&(k=v.call(this,e)):k=q.call(this,e,f);G(k,function(a,b){a=a.indicatorFullName.toLowerCase();b=b.indicatorFullName.toLowerCase();return a<b?-1:a>b?1:0});u.children[1]&&u.children[1].remove();var p=r("ul",{className:"highcharts-indicator-list"},void 0,u),C=d.querySelectorAll(".highcharts-popup-rhs-col-wrapper")[0];k.forEach(function(d){var e=d.indicatorFullName,f=d.indicatorType,u=d.series;H=r("li",{className:"highcharts-indicator-list"},
void 0,p);H.appendChild(t.createTextNode(e));["click","touchstart"].forEach(function(d){B(H,d,function(){var d=C.parentNode.children[1],e=u.params||u.options.params;C.innerHTML=c.emptyHTML;r("h3",{className:"highcharts-indicator-title"},void 0,C).appendChild(t.createTextNode(z(u,f).indicatorFullName));r("input",{type:"hidden",name:"highcharts-type-"+f,value:f},void 0,C);m.call(n,f,"series",a,C,u,u.linkedParent&&u.linkedParent.options.id);e.volumeSeriesID&&m.call(n,f,"volume",a,C,u,u.linkedParent&&
e.volumeSeriesID);b.call(n,a,"params",e,f,C);d&&(d.style.display="block");g&&u.options&&r("input",{type:"hidden",name:"highcharts-id-"+f,value:u.options.id},void 0,C).setAttribute("highcharts-data-series-id",u.options.id)})})});0<p.childNodes.length?p.childNodes[0].click():g||(c.setElementHTML(C.parentNode.children[0],h.noFilterMatch||""),C.parentNode.children[1].style.display="none")}}function b(a,c,d,e,g){var n=this;if(a){var u=this.addInput;w(d,function(d,h){var A=c+"."+h;I(d)&&A&&(F(d)&&(u.call(n,
A,e,g,{}),b.call(n,a,A,d,e,g)),A in D?(A=f.call(n,e,A,g),p.call(n,a,c,A,e,h,d)):"params.volumeSeriesID"===A||x(d)||u.call(n,A,e,g,{value:d,type:"number"}))})}}function e(b,c){var d=this,e=c.querySelectorAll(".highcharts-popup-lhs-col")[0];c=this.lang.clearFilter;e=r("div",{className:"highcharts-input-wrapper"},void 0,e);var f=this.addInput("searchIndicators","input",e,{value:"",type:"text",htmlFor:"search-indicators",labelClassName:"highcharts-input-search-indicators-label"}),g=r("a",{textContent:c},
void 0,e);f.classList.add("highcharts-input-search-indicators");g.classList.add("clear-filter-button");B(f,"input",function(){a.call(d,b,d.container,"add",this.value);g.style.display=this.value.length?"inline-block":"none"});["click","touchstart"].forEach(function(c){B(g,c,function(){f.value="";a.call(d,b,d.container,"add","");g.style.display="none"})})}function f(a,b,c){var d=b.split(".");d=d[d.length-1];a="highcharts-"+b+"-type-"+a;var e=this.lang;r("label",{htmlFor:a},null,c).appendChild(t.createTextNode(e[d]||
b));c=r("select",{name:a,className:"highcharts-popup-field",id:"highcharts-select-"+b},null,c);c.setAttribute("id","highcharts-select-"+b);return c}function p(a,b,c,d,e,f,g){"series"===b||"volume"===b?a.series.forEach(function(a){var d=a.options,e=d.name||d.params?a.name:d.id||"";"highcharts-navigator-series"!==d.id&&d.id!==(g&&g.options&&g.options.id)&&(I(f)||"volume"!==b||"column"!==a.type||(f=d.id),r("option",{value:d.id},void 0,c).appendChild(t.createTextNode(e)))}):d&&e&&K[e+"-"+d].forEach(function(a){r("option",
{value:a},void 0,c).appendChild(t.createTextNode(a))});I(f)&&(c.value=f)}function q(a,b){var c=this.chart&&this.chart.options.lang,d=c&&c.navigation&&c.navigation.popup&&c.navigation.popup.indicatorAliases,e=[],f;w(a,function(a,c){var n=a&&a.options;if(a.params||n&&n.params)if(n=z(a,c),c=n.indicatorFullName,n=n.indicatorType,b){var g=b.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");g=new RegExp(g,"i");var h=d&&d[n]&&d[n].join(" ")||"";if(c.match(g)||h.match(g))f={indicatorFullName:c,indicatorType:n,series:a},
e.push(f)}else f={indicatorFullName:c,indicatorType:n,series:a},e.push(f)});return e}function v(a){var b=[];a.forEach(function(a){a.is("sma")&&b.push({indicatorFullName:a.name,indicatorType:a.type,series:a})});return b}function z(a,b){var c=a.options,d=E[b]&&E[b].prototype.nameBase||b.toUpperCase();c&&c.type&&(b=a.options.type,d=a.name);return{indicatorFullName:d,indicatorType:b}}function m(a,b,c,d,e,g){c&&(a=f.call(this,a,b,d),p.call(this,c,b,a,void 0,void 0,void 0,e),I(g)&&(a.value=g))}var t=g.doc,
E=k.seriesTypes,B=h.addEvent,r=h.createElement,I=h.defined,x=h.isArray,F=h.isObject,w=h.objectEach,G=h.stableSort,D;(function(a){a[a["params.algorithm"]=0]="params.algorithm";a[a["params.average"]=1]="params.average"})(D||(D={}));var K={"algorithm-pivotpoints":["standard","fibonacci","camarilla"],"average-disparityindex":["sma","ema","dema","tema","wma"]};return{addForm:function(b,c,f){c=this.lang;if(b){this.tabs.init.call(this,b);var n=this.container.querySelectorAll(".highcharts-tab-item-content");
d(n[0]);e.call(this,b,n[0]);a.call(this,b,n[0],"add");var g=n[0].querySelectorAll(".highcharts-popup-rhs-col")[0];this.addButton(g,c.addButton||"add","add",g,f);d(n[1]);a.call(this,b,n[1],"edit");g=n[1].querySelectorAll(".highcharts-popup-rhs-col")[0];this.addButton(g,c.saveButton||"save","edit",g,f);this.addButton(g,c.removeButton||"remove","remove",g,f)}},getAmount:function(){var a=0;this.series.forEach(function(b){(b.params||b.options.params)&&a++});return a}}});l(c,"Extensions/Annotations/Popup/PopupTabs.js",
[c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,g){function p(){return e("div",{className:"highcharts-tab-item-content highcharts-no-mousewheel"},void 0,this.container)}function k(b,c){var d=this.container,f=this.lang,g="highcharts-tab-item";0===c&&(g+=" highcharts-tab-disabled");c=e("span",{className:g},void 0,d);c.appendChild(a.createTextNode(f[b+"Button"]||b));c.setAttribute("highcharts-data-tab-type",b);return c}function h(a,b){var c=this.container.querySelectorAll(".highcharts-tab-item-content");
a.className+=" highcharts-tab-item-active";c[b].className+=" highcharts-tab-item-show"}function d(a){var c=this;this.container.querySelectorAll(".highcharts-tab-item").forEach(function(d,e){0===a&&"edit"===d.getAttribute("highcharts-data-tab-type")||["click","touchstart"].forEach(function(a){b(d,a,function(){var a=c.container,b=a.querySelectorAll(".highcharts-tab-item");a=a.querySelectorAll(".highcharts-tab-item-content");for(var d=0;d<b.length;d++)b[d].classList.remove("highcharts-tab-item-active"),
a[d].classList.remove("highcharts-tab-item-show");h.call(c,this,e)})})})}var a=c.doc,b=g.addEvent,e=g.createElement;return{init:function(a){if(a){a=this.indicators.getAmount.call(a);var b=k.call(this,"add");k.call(this,"edit",a);p.call(this);p.call(this);d.call(this,a);h.call(this,b,0)}}}});l(c,"Extensions/Annotations/Popup/Popup.js",[c["Shared/BaseForm.js"],c["Core/Globals.js"],c["Core/Defaults.js"],c["Extensions/Annotations/Popup/PopupAnnotations.js"],c["Extensions/Annotations/Popup/PopupIndicators.js"],
c["Extensions/Annotations/Popup/PopupTabs.js"],c["Core/Utilities.js"]],function(c,g,l,k,h,d,a){function b(a,b){var c=Array.prototype.slice.call(a.querySelectorAll("input")),d=Array.prototype.slice.call(a.querySelectorAll("select")),e=a.querySelectorAll("#highcharts-select-series > option:checked")[0];a=a.querySelectorAll("#highcharts-select-volume > option:checked")[0];var f={actionType:b,linkedTo:e&&e.getAttribute("value")||"",fields:{}};c.forEach(function(a){var b=a.getAttribute("highcharts-data-name");
a.getAttribute("highcharts-data-series-id")?f.seriesId=a.value:b?f.fields[b]=a.value:f.type=a.value});d.forEach(function(a){var b=a.id;"highcharts-select-series"!==b&&"highcharts-select-volume"!==b&&(b=b.split("highcharts-select-")[1],f.fields[b]=a.value)});a&&(f.fields["params.volumeSeriesID"]=a.getAttribute("value")||"");return f}var e=this&&this.__extends||function(){function a(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,
c)&&(a[c]=b[c])};return a(b,c)}return function(b,c){function d(){this.constructor=b}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),f=g.doc,p=l.getOptions,q=a.addEvent,v=a.createElement;g=a.extend;var z=a.fireEvent,m=a.pick;c=function(a){function c(b,c,d){b=a.call(this,b,c)||this;b.chart=d;b.lang=(p().lang.navigation||{}).popup||{};q(b.container,
"mousedown",function(){var a=d&&d.navigationBindings&&d.navigationBindings.activeAnnotation;if(a){a.cancelClick=!0;var b=q(f,"click",function(){setTimeout(function(){a.cancelClick=!1},0);b()})}});return b}e(c,a);c.prototype.addInput=function(a,b,c,d){var e=a.split(".");e=e[e.length-1];var g=this.lang;b="highcharts-"+b+"-"+m(d.htmlFor,e);e.match(/^\d+$/)||v("label",{htmlFor:b,className:d.labelClassName},void 0,c).appendChild(f.createTextNode(g[e]||e));c=v("input",{name:b,value:d.value,type:d.type,
className:"highcharts-popup-field"},void 0,c);c.setAttribute("highcharts-data-name",a);return c};c.prototype.closeButtonEvents=function(){if(this.chart){var b=this.chart.navigationBindings;z(b,"closePopup");b&&b.selectedButtonElement&&z(b,"deselectButton",{button:b.selectedButtonElement})}else a.prototype.closeButtonEvents.call(this)};c.prototype.addButton=function(a,c,d,e,g){var h=this,k=v("button",void 0,void 0,a);k.appendChild(f.createTextNode(c));g&&["click","touchstart"].forEach(function(a){q(k,
a,function(){h.closePopup();return g(b(e,d))})});return k};c.prototype.showForm=function(a,b,c,d){b&&(this.showPopup(),"indicators"===a&&this.indicators.addForm.call(this,b,c,d),"annotation-toolbar"===a&&this.annotations.addToolbar.call(this,b,c,d),"annotation-edit"===a&&this.annotations.addForm.call(this,b,c,d),"flag"===a&&this.annotations.addForm.call(this,b,c,d,!0),this.type=a,this.container.style.height=this.container.offsetHeight+"px")};return c}(c);g(c.prototype,{annotations:k,indicators:h,
tabs:d});return c});l(c,"Extensions/Annotations/Popup/PopupComposition.js",[c["Extensions/Annotations/Popup/Popup.js"],c["Core/Utilities.js"]],function(c,g){function p(){this.popup&&this.popup.closePopup()}function k(a){this.popup||(this.popup=new c(this.chart.container,this.chart.options.navigation.iconsURL||this.chart.options.stockTools&&this.chart.options.stockTools.gui.iconsURL||"https://code.highcharts.com/11.1.0/gfx/stock-icons/",this.chart));this.popup.showForm(a.formType,this.chart,a.options,
a.onSubmit)}function h(a,b){this.inClass(b.target,"highcharts-popup")||a.apply(this,Array.prototype.slice.call(arguments,1))}var d=g.addEvent,a=g.wrap,b=[];return{compose:function(c,f){g.pushUnique(b,c)&&(d(c,"closePopup",p),d(c,"showPopup",k));g.pushUnique(b,f)&&a(f.prototype,"onContainerMouseDown",h)}}});l(c,"Extensions/Annotations/Annotation.js",[c["Core/Animation/AnimationUtilities.js"],c["Extensions/Annotations/AnnotationChart.js"],c["Extensions/Annotations/AnnotationDefaults.js"],c["Extensions/Annotations/Controllables/ControllableRect.js"],
c["Extensions/Annotations/Controllables/ControllableCircle.js"],c["Extensions/Annotations/Controllables/ControllableEllipse.js"],c["Extensions/Annotations/Controllables/ControllablePath.js"],c["Extensions/Annotations/Controllables/ControllableImage.js"],c["Extensions/Annotations/Controllables/ControllableLabel.js"],c["Extensions/Annotations/ControlPoint.js"],c["Extensions/Annotations/ControlTarget.js"],c["Extensions/Annotations/EventEmitter.js"],c["Extensions/Annotations/MockPoint.js"],c["Extensions/Annotations/NavigationBindings.js"],
c["Extensions/Annotations/Popup/PopupComposition.js"],c["Core/Utilities.js"]],function(c,g,l,k,h,d,a,b,e,f,J,q,y,z,m,t){function p(a){var b=a.graphic;a=a.points.some(function(a){return!1!==a.series.visible&&!1!==a.visible});b&&(a?"hidden"===b.visibility&&b.show():b.hide())}function v(a,b){var c={};["labels","shapes"].forEach(function(d){var e=a[d];e&&(c[d]=b[d]?K(b[d]).map(function(a,b){return G(e[b],a)}):a[d])});return c}var r=this&&this.__extends||function(){function a(b,c){a=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};return a(b,c)}return function(b,c){function d(){this.constructor=b}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),I=c.getDeferredAnimation,x=t.destroyObjectProperties,F=t.erase,w=t.fireEvent,G=t.merge,
D=t.pick,K=t.splat;c=function(c){function l(a,b){var d=c.call(this)||this;d.animationConfig=void 0;d.graphic=void 0;d.group=void 0;d.labelCollector=void 0;d.labelsGroup=void 0;d.shapesGroup=void 0;d.chart=a;d.points=[];d.controlPoints=[];d.coll="annotations";d.index=-1;d.labels=[];d.shapes=[];d.options=G(d.defaultOptions,b);d.userOptions=b;b=v(d.options,b);d.options.labels=b.labels;d.options.shapes=b.shapes;d.init(a,d.options);return d}r(l,c);l.compose=function(b,c,d){g.compose(l,b,c);e.compose(d);
a.compose(b,d);z.compose(l,b);m.compose(z,c)};l.prototype.addClipPaths=function(){this.setClipAxes();this.clipXAxis&&this.clipYAxis&&this.options.crop&&(this.clipRect=this.chart.renderer.clipRect(this.getClipBox()))};l.prototype.addLabels=function(){var a=this,b=this.options.labels||[];b.forEach(function(c,d){c=a.initLabel(c,d);G(!0,b[d],c.options)})};l.prototype.addShapes=function(){var a=this,b=this.options.shapes||[];b.forEach(function(c,d){c=a.initShape(c,d);G(!0,b[d],c.options)})};l.prototype.destroy=
function(){function a(a){a.destroy()}var b=this.chart;this.labels.forEach(a);this.shapes.forEach(a);this.clipYAxis=this.clipXAxis=null;F(b.labelCollectors,this.labelCollector);c.prototype.destroy.call(this);this.destroyControlTarget();x(this,b)};l.prototype.destroyItem=function(a){F(this[a.itemType+"s"],a);a.destroy()};l.prototype.getClipBox=function(){if(this.clipXAxis&&this.clipYAxis)return{x:this.clipXAxis.left,y:this.clipYAxis.top,width:this.clipXAxis.width,height:this.clipYAxis.height}};l.prototype.initProperties=
function(a,b){this.setOptions(b);var c=v(this.options,b);this.options.labels=c.labels;this.options.shapes=c.shapes;this.chart=a;this.points=[];this.controlPoints=[];this.coll="annotations";this.userOptions=b;this.labels=[];this.shapes=[]};l.prototype.init=function(a,b,c){void 0===c&&(c=this.index);a=this.chart;b=this.options.animation;this.index=c;this.linkPoints();this.addControlPoints();this.addShapes();this.addLabels();this.setLabelCollector();this.animationConfig=I(a,b)};l.prototype.initLabel=
function(a,b){a=G(this.options.labelOptions,{controlPointOptions:this.options.controlPointOptions},a);b=new e(this,a,b);b.itemType="label";this.labels.push(b);return b};l.prototype.initShape=function(a,b){a=G(this.options.shapeOptions,{controlPointOptions:this.options.controlPointOptions},a);b=new l.shapesMap[a.type](this,a,b);b.itemType="shape";this.shapes.push(b);return b};l.prototype.redraw=function(a){this.linkPoints();this.graphic||this.render();this.clipRect&&this.clipRect.animate(this.getClipBox());
this.redrawItems(this.shapes,a);this.redrawItems(this.labels,a);this.redrawControlPoints(a)};l.prototype.redrawItem=function(a,b){a.linkPoints();a.shouldBeDrawn()?(a.graphic||this.renderItem(a),a.redraw(D(b,!0)&&a.graphic.placed),a.points.length&&p(a)):this.destroyItem(a)};l.prototype.redrawItems=function(a,b){for(var c=a.length;c--;)this.redrawItem(a[c],b)};l.prototype.remove=function(){return this.chart.removeAnnotation(this)};l.prototype.render=function(){var a=this.chart.renderer;this.graphic=
a.g("annotation").attr({opacity:0,zIndex:this.options.zIndex,visibility:this.options.visible?"inherit":"hidden"}).add();this.shapesGroup=a.g("annotation-shapes").add(this.graphic);this.options.crop&&this.shapesGroup.clip(this.chart.plotBoxClip);this.labelsGroup=a.g("annotation-labels").attr({translateX:0,translateY:0}).add(this.graphic);this.addClipPaths();this.clipRect&&this.graphic.clip(this.clipRect);this.renderItems(this.shapes);this.renderItems(this.labels);this.addEvents();this.renderControlPoints()};
l.prototype.renderItem=function(a){a.render("label"===a.itemType?this.labelsGroup:this.shapesGroup)};l.prototype.renderItems=function(a){for(var b=a.length;b--;)this.renderItem(a[b])};l.prototype.setClipAxes=function(){var a=this.chart.xAxis,b=this.chart.yAxis,c=(this.options.labels||[]).concat(this.options.shapes||[]).reduce(function(c,d){d=d&&(d.point||d.points&&d.points[0]);return[a[d&&d.xAxis]||c[0],b[d&&d.yAxis]||c[1]]},[]);this.clipXAxis=c[0];this.clipYAxis=c[1]};l.prototype.setControlPointsVisibility=
function(a){function b(b){b.setControlPointsVisibility(a)}this.controlPoints.forEach(function(b){b.setVisibility(a)});this.shapes.forEach(b);this.labels.forEach(b)};l.prototype.setLabelCollector=function(){var a=this;a.labelCollector=function(){return a.labels.reduce(function(a,b){b.options.allowOverlap||a.push(b.graphic);return a},[])};a.chart.labelCollectors.push(a.labelCollector)};l.prototype.setOptions=function(a){this.options=G(this.defaultOptions,a)};l.prototype.setVisibility=function(a){var b=
this.options,c=this.chart.navigationBindings,d=D(a,!b.visible);this.graphic.attr("visibility",d?"inherit":"hidden");d||(a=function(a){a.setControlPointsVisibility(d)},this.shapes.forEach(a),this.labels.forEach(a),c.activeAnnotation===this&&c.popup&&"annotation-toolbar"===c.popup.type&&w(c,"closePopup"));b.visible=d};l.prototype.update=function(a,b){var c=this.chart,d=v(this.userOptions,a),e=c.annotations.indexOf(this);a=G(!0,this.userOptions,a);a.labels=d.labels;a.shapes=d.shapes;this.destroy();this.initProperties(c,
a);this.init(c,a);c.options.annotations[e]=a;this.isUpdating=!0;D(b,!0)&&c.redraw();w(this,"afterUpdate");this.isUpdating=!1};l.ControlPoint=f;l.MockPoint=y;l.shapesMap={rect:k,circle:h,ellipse:d,path:a,image:b};l.types={};return l}(q);c.prototype.defaultOptions=l;c.prototype.nonDOMEvents=["add","afterUpdate","drag","remove"];J.compose(c);"";return c});l(c,"masters/modules/annotations.src.js",[c["Core/Globals.js"],c["Extensions/Annotations/Annotation.js"]],function(c,g){c.Annotation=g;g.compose(c.Chart,
c.Pointer,c.SVGRenderer)})});//# sourceMappingURL=annotations.js.map