/*
 Highcharts JS v11.1.0 (2023-08-20)

 ColorAxis module

 (c) 2012-2021 Pawel Potaczek

 License: www.highcharts.com/license
*/
'use strict';(function(d){"object"===typeof module&&module.exports?(d["default"]=d,module.exports=d):"function"===typeof define&&define.amd?define("highcharts/modules/color-axis",["highcharts"],function(m){d(m);d.Highcharts=m;return d}):d("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(d){function m(d,k,x,p){d.hasOwnProperty(k)||(d[k]=p.apply(null,x),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:k,module:d[k]}})))}d=d?d._modules:
{};m(d,"Core/Axis/Color/ColorAxisComposition.js",[d["Core/Color/Color.js"],d["Core/Utilities.js"]],function(d,k){var q=d.parse,p=k.addEvent,m=k.extend,A=k.merge,t=k.pick,D=k.splat,r;(function(d){function r(){var a=this,b=this.options;this.colorAxis=[];b.colorAxis&&(b.colorAxis=D(b.colorAxis),b.colorAxis.forEach(function(b){new y(a,b)}))}function x(a){function b(b){b=a.allItems.indexOf(b);-1!==b&&(f.destroyItem(a.allItems[b]),a.allItems.splice(b,1))}var f=this,c=[],l,h;(this.chart.colorAxis||[]).forEach(function(a){(l=
a.options)&&l.showInLegend&&(l.dataClasses&&l.visible?c=c.concat(a.getDataClassLegendSymbols()):l.visible&&c.push(a),a.series.forEach(function(a){if(!a.options.showInLegend||l.dataClasses)"point"===a.options.legendType?a.points.forEach(function(a){b(a)}):b(a)}))});for(h=c.length;h--;)a.allItems.unshift(c[h])}function B(a){a.visible&&a.item.legendColor&&a.item.legendItem.symbol.attr({fill:a.item.legendColor})}function z(){var a=this.chart.colorAxis;a&&a.forEach(function(a,b,c){a.update({},c)})}function n(){(this.chart.colorAxis&&
this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()}function G(){var a=this.axisTypes;a?-1===a.indexOf("colorAxis")&&a.push("colorAxis"):this.axisTypes=["colorAxis"]}function e(a){var b=this,c=a?"show":"hide";b.visible=b.options.visible=!!a;["graphic","dataLabel"].forEach(function(a){if(b[a])b[a][c]()});this.series.buildKDTree()}function b(){var a=this,b=this.options.nullColor,c=this.colorAxis,f=this.colorKey;(this.data.length?this.data:this.points).forEach(function(h){var g=h.getNestedProperty(f);
(g=h.options.color||(h.isNull||null===h.value?b:c&&"undefined"!==typeof g?c.toColor(g,h):h.color||a.color))&&h.color!==g&&(h.color=g,"point"===a.options.legendType&&h.legendItem&&h.legendItem.label&&a.chart.legend.colorizeItem(h,h.visible))})}function a(a){var b=a.prototype.createAxis;a.prototype.createAxis=function(a,c){if("colorAxis"!==a)return b.apply(this,arguments);var f=new y(this,A(c.axis,{index:this[a].length,isX:!1}));this.isDirtyLegend=!0;this.axes.forEach(function(a){a.series=[]});this.series.forEach(function(a){a.bindAxes();
a.isDirtyData=!0});t(c.redraw,!0)&&this.redraw(c.animation);return f}}function c(){this.elem.attr("fill",q(this.start).tweenTo(q(this.end),this.pos),void 0,!0)}function f(){this.elem.attr("stroke",q(this.start).tweenTo(q(this.end),this.pos),void 0,!0)}var h=[],y;d.compose=function(l,g,d,v,w){y||(y=l);k.pushUnique(h,g)&&(l=g.prototype,l.collectionsWithUpdate.push("colorAxis"),l.collectionsWithInit.colorAxis=[l.addColorAxis],p(g,"afterGetAxes",r),a(g));k.pushUnique(h,d)&&(g=d.prototype,g.fillSetter=
c,g.strokeSetter=f);k.pushUnique(h,v)&&(p(v,"afterGetAllItems",x),p(v,"afterColorizeItem",B),p(v,"afterUpdate",z));k.pushUnique(h,w)&&(m(w.prototype,{optionalAxis:"colorAxis",translateColors:b}),m(w.prototype.pointClass.prototype,{setVisible:e}),p(w,"afterTranslate",n,{order:1}),p(w,"bindAxes",G))};d.pointSetVisible=e})(r||(r={}));return r});m(d,"Core/Axis/Color/ColorAxisDefaults.js",[],function(){return{lineWidth:0,minPadding:0,maxPadding:0,gridLineColor:"#ffffff",gridLineWidth:1,tickPixelInterval:72,
startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:"#999999"},labels:{distance:8,overflow:"justify",rotation:0},minColor:"#e6e9ff",maxColor:"#0022ff",tickLength:5,showInLegend:!0}});m(d,"Core/Axis/Color/ColorAxis.js",[d["Core/Axis/Axis.js"],d["Core/Color/Color.js"],d["Core/Axis/Color/ColorAxisComposition.js"],d["Core/Axis/Color/ColorAxisDefaults.js"],d["Core/Legend/LegendSymbol.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,k,m,p,C,A,t){var q=
this&&this.__extends||function(){function d(e,b){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};return d(e,b)}return function(e,b){function a(){this.constructor=e}if("function"!==typeof b&&null!==b)throw new TypeError("Class extends value "+String(b)+" is not a constructor or null");d(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),r=k.parse,x=
A.series,E=t.extend,F=t.isArray,B=t.isNumber,z=t.merge,n=t.pick;k=function(d){function e(b,a){var c=d.call(this,b,a)||this;c.beforePadding=!1;c.chart=void 0;c.coll="colorAxis";c.dataClasses=void 0;c.options=void 0;c.stops=void 0;c.visible=!0;c.init(b,a);return c}q(e,d);e.compose=function(b,a,c,f){m.compose(e,b,a,c,f)};e.prototype.init=function(b,a){var c=b.options.legend||{},f=a.layout?"vertical"!==a.layout:"vertical"!==c.layout,h=a.visible;c=z(e.defaultColorAxisOptions,a,{showEmpty:!1,title:null,
visible:c.enabled&&!1!==h});this.side=a.side||f?2:1;this.reversed=a.reversed||!f;this.opposite=!f;d.prototype.init.call(this,b,c,"colorAxis");this.userOptions=a;F(b.userOptions.colorAxis)&&(b.userOptions.colorAxis[this.index]=a);a.dataClasses&&this.initDataClasses(a);this.initStops();this.horiz=f;this.zoomEnabled=!1};e.prototype.initDataClasses=function(b){var a=this.chart,c=this.legendItem=this.legendItem||{},f=b.dataClasses.length,h=this.options,d,e=0,g=a.options.chart.colorCount;this.dataClasses=
d=[];c.labels=[];(b.dataClasses||[]).forEach(function(b,c){b=z(b);d.push(b);if(a.styledMode||!b.color)"category"===h.dataClassColor?(a.styledMode||(c=a.options.colors,g=c.length,b.color=c[e]),b.colorIndex=e,e++,e===g&&(e=0)):b.color=r(h.minColor).tweenTo(r(h.maxColor),2>f?.5:c/(f-1))})};e.prototype.hasData=function(){return!!(this.tickPositions||[]).length};e.prototype.setTickPositions=function(){if(!this.dataClasses)return d.prototype.setTickPositions.call(this)};e.prototype.initStops=function(){this.stops=
this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(b){b.color=r(b[1])})};e.prototype.setOptions=function(b){d.prototype.setOptions.call(this,b);this.options.crosshair=this.options.marker};e.prototype.setAxisSize=function(){var b=this.legendItem&&this.legendItem.symbol,a=this.chart,c=a.options.legend||{},f,h;b?(this.left=c=b.attr("x"),this.top=f=b.attr("y"),this.width=h=b.attr("width"),this.height=b=b.attr("height"),this.right=a.chartWidth-c-h,this.bottom=
a.chartHeight-f-b,this.len=this.horiz?h:b,this.pos=this.horiz?c:f):this.len=(this.horiz?c.symbolWidth:c.symbolHeight)||e.defaultLegendLength};e.prototype.normalizedValue=function(b){this.logarithmic&&(b=this.logarithmic.log2lin(b));return 1-(this.max-b)/(this.max-this.min||1)};e.prototype.toColor=function(b,a){var c=this.dataClasses,f=this.stops,h;if(c)for(h=c.length;h--;){var d=c[h];var e=d.from;f=d.to;if(("undefined"===typeof e||b>=e)&&("undefined"===typeof f||b<=f)){var g=d.color;a&&(a.dataClass=
h,a.colorIndex=d.colorIndex);break}}else{b=this.normalizedValue(b);for(h=f.length;h--&&!(b>f[h][0]););e=f[h]||f[h+1];f=f[h+1]||e;b=1-(f[0]-b)/(f[0]-e[0]||1);g=e.color.tweenTo(f.color,b)}return g};e.prototype.getOffset=function(){var b=this.legendItem&&this.legendItem.group,a=this.chart.axisOffset[this.side];if(b){this.axisParent=b;d.prototype.getOffset.call(this);var c=this.chart.legend;c.allItems.forEach(function(a){a instanceof e&&a.drawLegendSymbol(c,a)});c.render();this.chart.getMargins(!0);this.added||
(this.added=!0,this.labelLeft=0,this.labelRight=this.width);this.chart.axisOffset[this.side]=a}};e.prototype.setLegendColor=function(){var b=this.reversed,a=b?1:0;b=b?0:1;a=this.horiz?[a,0,b,0]:[0,b,0,a];this.legendColor={linearGradient:{x1:a[0],y1:a[1],x2:a[2],y2:a[3]},stops:this.stops}};e.prototype.drawLegendSymbol=function(b,a){var c;a=a.legendItem||{};var f=b.padding,d=b.options,k=this.options.labels,l=n(d.itemDistance,10),g=this.horiz,u=n(d.symbolWidth,g?e.defaultLegendLength:12),v=n(d.symbolHeight,
g?12:e.defaultLegendLength),w=n(d.labelPadding,g?16:30);this.setLegendColor();a.symbol||(a.symbol=this.chart.renderer.symbol("roundedRect",0,b.baseline-11,u,v,{r:null!==(c=d.symbolRadius)&&void 0!==c?c:3}).attr({zIndex:1}).add(a.group));a.labelWidth=u+f+(g?l:n(k.x,k.distance)+this.maxLabelLength);a.labelHeight=v+f+(g?w:0)};e.prototype.setState=function(b){this.series.forEach(function(a){a.setState(b)})};e.prototype.setVisible=function(){};e.prototype.getSeriesExtremes=function(){var b=this.series,
a=b.length,c;this.dataMin=Infinity;for(this.dataMax=-Infinity;a--;){var f=b[a];var d=f.colorKey=n(f.options.colorKey,f.colorKey,f.pointValKey,f.zoneAxis,"y");var e=f.pointArrayMap;var k=f[d+"Min"]&&f[d+"Max"];if(f[d+"Data"])var g=f[d+"Data"];else if(e){g=[];e=e.indexOf(d);var u=f.yData;if(0<=e&&u)for(c=0;c<u.length;c++)g.push(n(u[c][e],u[c]))}else g=f.yData;k?(f.minColorValue=f[d+"Min"],f.maxColorValue=f[d+"Max"]):(g=x.prototype.getExtremes.call(f,g),f.minColorValue=g.dataMin,f.maxColorValue=g.dataMax);
"undefined"!==typeof f.minColorValue&&(this.dataMin=Math.min(this.dataMin,f.minColorValue),this.dataMax=Math.max(this.dataMax,f.maxColorValue));k||x.prototype.applyExtremes.call(f)}};e.prototype.drawCrosshair=function(b,a){var c=this.legendItem||{},f=a&&a.plotX,e=a&&a.plotY,k=this.pos,l=this.len;if(a){var g=this.toPixels(a.getNestedProperty(a.series.colorKey));g<k?g=k-2:g>k+l&&(g=k+l+2);a.plotX=g;a.plotY=this.len-g;d.prototype.drawCrosshair.call(this,b,a);a.plotX=f;a.plotY=e;this.cross&&!this.cross.addedToColorAxis&&
c.group&&(this.cross.addClass("highcharts-coloraxis-marker").add(c.group),this.cross.addedToColorAxis=!0,this.chart.styledMode||"object"!==typeof this.crosshair||this.cross.attr({fill:this.crosshair.color}))}};e.prototype.getPlotLinePath=function(b){var a=this.left,c=b.translatedValue,f=this.top;return B(c)?this.horiz?[["M",c-4,f-6],["L",c+4,f-6],["L",c,f],["Z"]]:[["M",a,c],["L",a-6,c+6],["L",a-6,c-6],["Z"]]:d.prototype.getPlotLinePath.call(this,b)};e.prototype.update=function(b,a){var c=this.chart.legend;
this.series.forEach(function(a){a.isDirtyData=!0});(b.dataClasses&&c.allItems||this.dataClasses)&&this.destroyItems();d.prototype.update.call(this,b,a);this.legendItem&&this.legendItem.label&&(this.setLegendColor(),c.colorizeItem(this,!0))};e.prototype.destroyItems=function(){var b=this.chart,a=this.legendItem||{};if(a.label)b.legend.destroyItem(this);else if(a.labels){var c=0;for(a=a.labels;c<a.length;c++)b.legend.destroyItem(a[c])}b.isDirtyLegend=!0};e.prototype.destroy=function(){this.chart.isDirtyLegend=
!0;this.destroyItems();d.prototype.destroy.apply(this,[].slice.call(arguments))};e.prototype.remove=function(b){this.destroyItems();d.prototype.remove.call(this,b)};e.prototype.getDataClassLegendSymbols=function(){function b(b){return a.series.reduce(function(a,c){a.push.apply(a,c.points.filter(function(a){return a.dataClass===b}));return a},[])}var a=this,c=a.chart,d=a.legendItem&&a.legendItem.labels||[],e=c.options.legend,k=n(e.valueDecimals,-1),l=n(e.valueSuffix,""),g;d.length||a.dataClasses.forEach(function(e,
f){var h=e.from,m=e.to,q=c.numberFormatter,n=!0;g="";"undefined"===typeof h?g="< ":"undefined"===typeof m&&(g="> ");"undefined"!==typeof h&&(g+=q(h,k)+l);"undefined"!==typeof h&&"undefined"!==typeof m&&(g+=" - ");"undefined"!==typeof m&&(g+=q(m,k)+l);d.push(E({chart:c,name:g,options:{},drawLegendSymbol:C.rectangle,visible:!0,isDataClass:!0,setState:function(a){for(var c=0,d=b(f);c<d.length;c++)d[c].setState(a)},setVisible:function(){this.visible=n=a.visible=!n;for(var d=0,e=b(f);d<e.length;d++)e[d].setVisible(n);
c.legend.colorizeItem(this,n)}},e))});return d};e.defaultColorAxisOptions=p;e.defaultLegendLength=200;e.keepProps=["legendItem"];return e}(d);Array.prototype.push.apply(d.keepProps,k.keepProps);"";return k});m(d,"masters/modules/coloraxis.src.js",[d["Core/Globals.js"],d["Core/Axis/Color/ColorAxis.js"]],function(d,k){d.ColorAxis=k;k.compose(d.Chart,d.Fx,d.Legend,d.Series)})});//# sourceMappingURL=coloraxis.js.map