/*
 Highcharts JS v11.1.0 (2023-08-20)

 Highcharts Drilldown module

 Author: Torstein Honsi
 License: www.highcharts.com/license

*/
'use strict';(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/drilldown",["highcharts"],function(r){a(r);a.Highcharts=r;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function r(a,t,p,m){a.hasOwnProperty(t)||(a[t]=m.apply(null,p),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:t,module:a[t]}})))}a=a?a._modules:
{};r(a,"Extensions/Breadcrumbs/BreadcrumbsDefaults.js",[],function(){return{lang:{mainBreadcrumb:"Main"},options:{buttonTheme:{fill:"none",height:18,padding:2,"stroke-width":0,zIndex:7,states:{select:{fill:"none"}},style:{color:"#334eff"}},buttonSpacing:5,floating:!1,format:void 0,relativeTo:"plotBox",rtl:!1,position:{align:"left",verticalAlign:"top",x:0,y:void 0},separator:{text:"/",style:{color:"#666666",fontSize:"0.8em"}},showFullPath:!0,style:{},useHTML:!1,zIndex:7}}});r(a,"Extensions/Breadcrumbs/Breadcrumbs.js",
[a["Extensions/Breadcrumbs/BreadcrumbsDefaults.js"],a["Core/Chart/Chart.js"],a["Core/Templating.js"],a["Core/Utilities.js"]],function(a,t,p,m){function v(){if(this.breadcrumbs){var a=this.resetZoomButton&&this.resetZoomButton.getBBox(),e=this.breadcrumbs.options;a&&"right"===e.position.align&&"plotBox"===e.relativeTo&&this.breadcrumbs.alignBreadcrumbsGroup(-a.width-e.buttonSpacing)}}function r(){this.breadcrumbs&&(this.breadcrumbs.destroy(),this.breadcrumbs=void 0)}function H(){var a=this.breadcrumbs;
if(a&&!a.options.floating&&a.level){var e=a.options,d=e.buttonTheme;d=(d.height||0)+2*(d.padding||0)+e.buttonSpacing;e=e.position.verticalAlign;"bottom"===e?(this.marginBottom=(this.marginBottom||0)+d,a.yOffset=d):"middle"!==e?(this.plotTop+=d,a.yOffset=-d):a.yOffset=void 0}}function w(){this.breadcrumbs&&this.breadcrumbs.redraw()}function E(a){!0===a.resetSelection&&this.breadcrumbs&&this.breadcrumbs.alignBreadcrumbsGroup()}var I=p.format,x=m.addEvent,F=m.defined,n=m.extend,G=m.fireEvent,N=m.isString,
y=m.merge,C=m.objectEach,D=m.pick,z=[];p=function(){function h(e,d){this.elementList={};this.isDirty=!0;this.level=0;this.list=[];d=y(e.options.drilldown&&e.options.drilldown.drillUpButton,h.defaultOptions,e.options.navigation&&e.options.navigation.breadcrumbs,d);this.chart=e;this.options=d||{}}h.compose=function(e,d){m.pushUnique(z,e)&&(x(t,"destroy",r),x(t,"afterShowResetZoom",v),x(t,"getMargins",H),x(t,"redraw",w),x(t,"selection",E));m.pushUnique(z,d)&&n(d.lang,a.lang)};h.prototype.updateProperties=
function(e){this.setList(e);this.setLevel();this.isDirty=!0};h.prototype.setList=function(e){this.list=e};h.prototype.setLevel=function(){this.level=this.list.length&&this.list.length-1};h.prototype.getLevel=function(){return this.level};h.prototype.getButtonText=function(e){var d=this.chart,a=this.options,f=d.options.lang,h=D(a.format,a.showFullPath?"{level.name}":"\u2190 {level.name}");f=f&&D(f.drillUpText,f.mainBreadcrumb);e=a.formatter&&a.formatter(e)||I(h,{level:e.levelOptions},d)||"";(N(e)&&
!e.length||"\u2190 "===e)&&F(f)&&(e=a.showFullPath?f:"\u2190 "+f);return e};h.prototype.redraw=function(){this.isDirty&&this.render();this.group&&this.group.align();this.isDirty=!1};h.prototype.render=function(){var e=this.chart,d=this.options;!this.group&&d&&(this.group=e.renderer.g("breadcrumbs-group").addClass("highcharts-no-tooltip highcharts-breadcrumbs").attr({zIndex:d.zIndex}).add());d.showFullPath?this.renderFullPathButtons():this.renderSingleButton();this.alignBreadcrumbsGroup()};h.prototype.renderFullPathButtons=
function(){this.destroySingleButton();this.resetElementListState();this.updateListElements();this.destroyListElements()};h.prototype.renderSingleButton=function(){var e=this.chart,d=this.list,a=this.options.buttonSpacing;this.destroyListElements();var f=this.group?this.group.getBBox().width:a;d=d[d.length-2];!e.drillUpButton&&0<this.level?e.drillUpButton=this.renderButton(d,f,a):e.drillUpButton&&(0<this.level?this.updateSingleButton():this.destroySingleButton())};h.prototype.alignBreadcrumbsGroup=
function(e){if(this.group){var d=this.options,a=d.buttonTheme,f=d.position,h="chart"===d.relativeTo||"spacingBox"===d.relativeTo?void 0:"scrollablePlotBox",k=this.group.getBBox();d=2*(a.padding||0)+d.buttonSpacing;f.width=k.width+d;f.height=k.height+d;k=y(f);e&&(k.x+=e);this.options.rtl&&(k.x+=f.width);k.y=D(k.y,this.yOffset,0);this.group.align(k,!0,h)}};h.prototype.renderButton=function(e,d,a){var f=this,h=this.chart,k=f.options,p=y(k.buttonTheme);d=h.renderer.button(f.getButtonText(e),d,a,function(d){var a=
k.events&&k.events.click,h;a&&(h=a.call(f,d,e));!1!==h&&(d.newLevel=k.showFullPath?e.level:f.level-1,G(f,"up",d))},p).addClass("highcharts-breadcrumbs-button").add(f.group);h.styledMode||d.attr(k.style);return d};h.prototype.renderSeparator=function(a,d){var e=this.chart,f=this.options.separator;a=e.renderer.label(f.text,a,d,void 0,void 0,void 0,!1).addClass("highcharts-breadcrumbs-separator").add(this.group);e.styledMode||a.css(f.style);return a};h.prototype.update=function(a){y(!0,this.options,
a);this.destroy();this.isDirty=!0};h.prototype.updateSingleButton=function(){var a=this.chart,d=this.list[this.level-1];a.drillUpButton&&a.drillUpButton.attr({text:this.getButtonText(d)})};h.prototype.destroy=function(){this.destroySingleButton();this.destroyListElements(!0);this.group&&this.group.destroy();this.group=void 0};h.prototype.destroyListElements=function(a){var d=this.elementList;C(d,function(e,f){if(a||!d[f].updated)e=d[f],e.button&&e.button.destroy(),e.separator&&e.separator.destroy(),
delete e.button,delete e.separator,delete d[f]});a&&(this.elementList={})};h.prototype.destroySingleButton=function(){this.chart.drillUpButton&&(this.chart.drillUpButton.destroy(),this.chart.drillUpButton=void 0)};h.prototype.resetElementListState=function(){C(this.elementList,function(a){a.updated=!1})};h.prototype.updateListElements=function(){function a(b,c,a){b.translate(c-b.getBBox().width,a)}function d(b,c){return t*b.getBBox().width+t*c}for(var h=this.elementList,f=this.options.buttonSpacing,
p=this.list,k=this.options.rtl,t=k?-1:1,n=this.group?d(this.group,f):f,q,m,v=0,r=p.length;v<r;++v){var c=v===r-1,b=void 0;q=void 0;m=p[v];h[m.level]?(q=h[m.level],b=q.button,q.separator||c?q.separator&&c&&(q.separator.destroy(),delete q.separator):(n+=t*f,q.separator=this.renderSeparator(n,f),k&&a(q.separator,n,f),n+=d(q.separator,f)),h[m.level].updated=!0):(b=this.renderButton(m,n,f),k&&a(b,n,f),n+=d(b,f),c||(q=this.renderSeparator(n,f),k&&a(q,n,f),n+=d(q,f)),h[m.level]={button:b,separator:q,updated:!0});
b&&b.setState(c?2:0)}};h.defaultOptions=a.options;return h}();"";return p});r(a,"Extensions/Drilldown.js",[a["Core/Animation/AnimationUtilities.js"],a["Core/Axis/Axis.js"],a["Core/Chart/Chart.js"],a["Core/Color/Color.js"],a["Series/Column/ColumnSeries.js"],a["Core/Globals.js"],a["Core/Defaults.js"],a["Core/Series/Point.js"],a["Core/Series/Series.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Axis/Tick.js"],a["Core/Utilities.js"],a["Extensions/Breadcrumbs/Breadcrumbs.js"]],
function(a,t,p,m,r,M,H,w,E,I,x,F,n,G){function v(c,b,g,a){c[g?"addClass":"removeClass"]("highcharts-drilldown-point");a||c.css({cursor:b})}function y(c){var b=this.series;b.xAxis&&!1===b.chart.options.drilldown.allowPointDrilldown?b.xAxis.drilldownCategory(this.x,c):this.runDrilldown(void 0,void 0,c)}function C(c){var b=[];(c=c.drilldownLevels)&&c.length&&(b[0]||b.push({level:0,levelOptions:c[0].seriesOptions}),c.forEach(function(c){c.levelNumber+1>b[b.length-1].level&&b.push({level:c.levelNumber+
1,levelOptions:B({name:c.lowerSeries.name},c.pointOptions)})}));return b}function D(c){var b=z(this.chart.options.drilldown.animation);c&&(c.hide(),K(function(){c&&c.added&&c.fadeIn()},Math.max(b.duration-50,0)))}var z=a.animObject,h=M.noop,e=H.defaultOptions;a=I.seriesTypes;var d=n.addEvent,O=n.defined,f=n.diffObjects,A=n.extend,k=n.fireEvent,B=n.merge,P=n.objectEach,q=n.pick,Q=n.removeEvent,K=n.syncTimeout;n=a.pie;a=a.map;var L=1;A(e.lang,{});e.drilldown={activeAxisLabelStyle:{cursor:"pointer",
color:"#0022ff",fontWeight:"bold",textDecoration:"underline"},activeDataLabelStyle:{cursor:"pointer",color:"#0022ff",fontWeight:"bold",textDecoration:"underline"},animation:{duration:500},drillUpButton:{position:{align:"right",x:-10,y:10}},mapZooming:!0};x.prototype.Element.prototype.fadeIn=function(c){this.attr({opacity:.1,visibility:"inherit"}).animate({opacity:q(this.newOpacity,1)},c||{duration:250})};p.prototype.addSeriesAsDrilldown=function(c,b){var g=this;if(g.mapView){c.series.isDrilling=!0;
g.series.forEach(function(b){var c;b.options.inactiveOtherPoints=!0;null===(c=b.dataLabelsGroup)||void 0===c?void 0:c.destroy();delete b.dataLabelsGroup});if(g.options.drilldown&&!g.mapView.projection.hasGeoProjection&&e.drilldown){var a=f(g.options.drilldown,e.drilldown);O(a.mapZooming)||(g.options.drilldown.mapZooming=!1)}if(g.options.drilldown&&g.options.drilldown.animation&&g.options.drilldown.mapZooming){g.mapView.allowTransformAnimation=!0;a=z(g.options.drilldown.animation);if("boolean"!==typeof a){var d=
a.complete,R=function(a){a&&a.applyDrilldown&&g.mapView&&(g.addSingleSeriesAsDrilldown(c,b),g.applyDrilldown(),g.mapView.allowTransformAnimation=!1)};a.complete=function(){d&&d.apply(this,arguments);R.apply(this,arguments)}}c.zoomTo(a)}else g.addSingleSeriesAsDrilldown(c,b),g.applyDrilldown()}else g.addSingleSeriesAsDrilldown(c,b),g.applyDrilldown()};p.prototype.addSingleSeriesAsDrilldown=function(c,b){var a=c.series,l=a.xAxis,d=a.yAxis,e=[],f=[],u;var k=this.styledMode?{colorIndex:q(c.colorIndex,
a.colorIndex)}:{color:c.color||a.color};this.drilldownLevels||(this.drilldownLevels=[]);var n=a.options._levelNumber||0;(u=this.drilldownLevels[this.drilldownLevels.length-1])&&u.levelNumber!==n&&(u=void 0);b=A(A({_ddSeriesId:L++},k),b);var p=a.points.indexOf(c);a.chart.series.forEach(function(b){b.xAxis===l&&(b.options._ddSeriesId=b.options._ddSeriesId||L++,b.options.colorIndex=b.colorIndex,b.options._levelNumber=b.options._levelNumber||n,u?(e=u.levelSeries,f=u.levelSeriesOptions):(e.push(b),b.purgedOptions=
B({_ddSeriesId:b.options._ddSeriesId,_levelNumber:b.options._levelNumber,selected:b.options.selected},b.userOptions),f.push(b.purgedOptions)))});c=A({levelNumber:n,seriesOptions:a.options,seriesPurgedOptions:a.purgedOptions,levelSeriesOptions:f,levelSeries:e,shapeArgs:c.shapeArgs,bBox:c.graphic?c.graphic.getBBox():{},color:c.isNull?m.parse(k.color).setOpacity(0).get():k.color,lowerSeriesOptions:b,pointOptions:a.options.data[p],pointIndex:p,oldExtremes:{xMin:l&&l.userMin,xMax:l&&l.userMax,yMin:d&&
d.userMin,yMax:d&&d.userMax},resetZoomButton:u&&u.levelNumber===n?void 0:this.resetZoomButton},k);this.drilldownLevels.push(c);l&&l.names&&(l.names.length=0);b=c.lowerSeries=this.addSeries(b,!1);b.options._levelNumber=n+1;l&&(l.oldPos=l.pos,l.userMin=l.userMax=null,d.userMin=d.userMax=null);b.isDrilling=!0;a.type===b.type&&(b.animate=b.animateDrilldown||h,b.options.animation=!0)};p.prototype.applyDrilldown=function(){var c=this,b=this.drilldownLevels;if(b&&0<b.length){var a=b[b.length-1].levelNumber;
this.drilldownLevels.forEach(function(b){c.mapView&&c.options.drilldown&&c.options.drilldown.mapZooming&&(c.redraw(),b.lowerSeries.isDrilling=!1,c.mapView.fitToBounds(b.lowerSeries.bounds),b.lowerSeries.isDrilling=!0);b.levelNumber===a&&b.levelSeries.forEach(function(g){if(!c.mapView)g.options&&g.options._levelNumber===a&&g.remove(!1);else if(g.options&&g.options._levelNumber===a&&g.group){var d={};c.options.drilldown&&(d=c.options.drilldown.animation);g.group.animate({opacity:0},d,function(){g.remove(!1);
b.levelSeries.filter(function(b){return Object.keys(b).length}).length||(c.resetZoomButton&&(c.resetZoomButton.hide(),delete c.resetZoomButton),c.pointer.reset(),k(c,"afterDrilldown"),c.mapView&&(c.series.forEach(function(b){b.isDirtyData=!0;b.isDrilling=!1}),c.mapView.fitToBounds(void 0,void 0)),k(c,"afterApplyDrilldown"))})}})})}c.mapView||(this.resetZoomButton&&(this.resetZoomButton.hide(),delete this.resetZoomButton),this.pointer.reset(),k(this,"afterDrilldown"),this.redraw(),k(this,"afterApplyDrilldown"))};
p.prototype.drillUp=function(c){if(this.drilldownLevels&&0!==this.drilldownLevels.length){k(this,"beforeDrillUp");var b=this,a=b.drilldownLevels,d=a[a.length-1].levelNumber,e=b.series,f=b.drilldownLevels.length,h=function(c,a){e.forEach(function(b){b.options._ddSeriesId===c._ddSeriesId&&(g=b)});var g=g||b.addSeries(c,!1);g.type===a.type&&g.animateDrillupTo&&(g.animate=g.animateDrillupTo);if(c===m.seriesPurgedOptions)return g},u=function(c){c.remove(!1);b.series.forEach(function(b){b.colorAxis&&(b.isDirtyData=
!0);b.options.inactiveOtherPoints=!1});b.redraw()},n=a.length,p,m,q;b.symbolCounter=b.colorCounter=0;for(var t=function(){var g;m=a[n];if(m.levelNumber===d){a.pop();var l=m.lowerSeries;if(!l.chart)for(p=e.length;p--;)if(e[p].options.id===m.lowerSeriesOptions.id&&e[p].options._levelNumber===d+1){l=e[p];break}l.xData=[];l.xAxis&&l.xAxis.names&&(0===f||n===f)&&(l.xAxis.names.length=0);m.levelSeriesOptions.forEach(function(b){(b=h(b,l))&&(g=b)});k(b,"drillup",{seriesOptions:m.seriesPurgedOptions||m.seriesOptions});
g&&(g.type===l.type&&(g.drilldownLevel=m,g.options.animation=b.options.drilldown.animation,l.animateDrillupFrom&&l.chart&&l.animateDrillupFrom(m)),g.options._levelNumber=d);b.mapView||l.remove(!1);g&&g.xAxis&&(q=m.oldExtremes,g.xAxis.setExtremes(q.xMin,q.xMax,!1),g.yAxis.setExtremes(q.yMin,q.yMax,!1));m.resetZoomButton&&(b.resetZoomButton=m.resetZoomButton);if(r.mapView){var J=b.options.drilldown&&b.options.drilldown.animation&&b.options.drilldown.mapZooming;m.levelNumber===d&&c?l.remove(!1):(l.dataLabelsGroup&&
(l.dataLabelsGroup.destroy(),delete l.dataLabelsGroup),b.mapView&&g&&(J&&(l.isDrilling=!0,g.isDrilling=!0,b.redraw(!1),b.mapView.fitToBounds(l.bounds,void 0,!0,!1)),b.mapView.allowTransformAnimation=!0,k(b,"afterDrillUp",{seriesOptions:g?g.userOptions:void 0}),J?b.mapView.setView(void 0,1,!0,{complete:function(){Object.prototype.hasOwnProperty.call(this,"complete")&&u(l)}}):(b.mapView.allowTransformAnimation=!1,l.group?l.group.animate({opacity:0},b.options.drilldown.animation,function(){u(l);b.mapView&&
(b.mapView.allowTransformAnimation=!0)}):(u(l),b.mapView.allowTransformAnimation=!0)),g.isDrilling=!1,b.ddDupes&&(b.ddDupes.length=0),k(b,"drillupall")))}else k(b,"afterDrillUp"),r.redraw(),r.ddDupes&&(r.ddDupes.length=0),k(b,"drillupall")}},r=this;n--;)t()}};d(p,"afterInit",function(){var c=this;c.drilldown={chart:c,fadeInGroup:D,update:function(b,a){B(!0,c.options.drilldown,b);q(a,!0)&&c.redraw()}}});d(p,"render",function(){(this.xAxis||[]).forEach(function(c){c.ddPoints={};c.series.forEach(function(b){var a,
d=b.xData||[],e=b.points;for(a=0;a<d.length;a++){var f=b.options.data[a];"number"!==typeof f&&(f=b.pointClass.prototype.optionsToObject.call({series:b},f),f.drilldown&&(c.ddPoints[d[a]]||(c.ddPoints[d[a]]=[]),f=a-(b.cropStart||0),c.ddPoints[d[a]].push(e&&0<=f&&f<e.length?e[f]:!0)))}});P(c.ticks,F.prototype.drillable)})});d(G,"up",function(c){var b=this.chart;c=this.getLevel()-c.newLevel;for(var a=1<c,d=0;d<c;d++)d===c-1&&(a=!1),b.drillUp(a)});d(p,"afterDrilldown",function(){var a=this.options.drilldown;
a=a&&a.breadcrumbs;this.breadcrumbs||(this.breadcrumbs=new G(this,a));this.breadcrumbs.updateProperties(C(this))});d(p,"afterDrillUp",function(){this.breadcrumbs&&this.breadcrumbs.updateProperties(C(this))});d(p,"update",function(a){var b=this.breadcrumbs,c=a.options.drilldown&&a.options.drilldown.breadcrumbs;b&&c&&b.update(a.options.drilldown.breadcrumbs)});r.prototype.animateDrillupTo=function(a){if(!a){var b=this,c=b.drilldownLevel;this.points.forEach(function(b){var a=b.dataLabel;b.graphic&&b.graphic.hide();
a&&(a.hidden="hidden"===a.attr("visibility"),a.hidden||(a.hide(),b.connector&&b.connector.hide()))});K(function(){if(b.points){var a=[];b.data.forEach(function(b){a.push(b)});b.nodes&&(a=a.concat(b.nodes));a.forEach(function(b,a){a=a===(c&&c.pointIndex)?"show":"fadeIn";var d="show"===a?!0:void 0,g=b.dataLabel;if(b.graphic&&b.visible)b.graphic[a](d);g&&!g.hidden&&(g.fadeIn(),b.connector&&b.connector.fadeIn())})}},Math.max(this.chart.options.drilldown.animation.duration-50,0));delete this.animate}};
r.prototype.animateDrilldown=function(a){var b=this,c=this.chart,d=c.drilldownLevels,e,f=z(c.options.drilldown.animation),h=this.xAxis,k=c.styledMode;a||(d.forEach(function(a){b.options._ddSeriesId===a.lowerSeriesOptions._ddSeriesId&&(e=a.shapeArgs,k||(e.fill=a.color))}),e.x+=q(h.oldPos,h.pos)-h.pos,this.points.forEach(function(a){var c=a.shapeArgs;k||(c.fill=a.color);a.graphic&&a.graphic.attr(e).animate(A(a.shapeArgs,{fill:a.color||b.color}),f)}),c.drilldown&&c.drilldown.fadeInGroup(this.dataLabelsGroup),
delete this.animate)};r.prototype.animateDrillupFrom=function(a){var b=z(this.chart.options.drilldown.animation),c=this.group,d=c!==this.chart.columnGroup,e=this;e.trackerGroups.forEach(function(b){if(e[b])e[b].on("mouseover")});d&&delete this.group;this.points.forEach(function(g){function l(){f.destroy();c&&d&&(c=c.destroy())}var f=g.graphic,h=a.shapeArgs;f&&h&&(delete g.graphic,e.chart.styledMode||(h.fill=a.color),b.duration?f.animate(h,B(b,{complete:l})):(f.attr(h),l()))})};n&&A(n.prototype,{animateDrillupTo:r.prototype.animateDrillupTo,
animateDrillupFrom:r.prototype.animateDrillupFrom,animateDrilldown:function(a){var b=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],c=this.chart.options.drilldown.animation;this.is("item")&&(c.duration=0);if(this.center){var d=b.shapeArgs,e=d.start,f=(d.end-e)/this.points.length,h=this.chart.styledMode;a||(this.points.forEach(function(a,g){var l=a.shapeArgs;h||(d.fill=b.color,l.fill=a.color);if(a.graphic)a.graphic.attr(B(d,{start:e+g*f,end:e+(g+1)*f}))[c?"animate":"attr"](l,c)}),
this.chart.drilldown&&this.chart.drilldown.fadeInGroup(this.dataLabelsGroup),delete this.animate)}}});a&&A(a.prototype,{animateDrilldown:function(a){var b=this,c=this.chart,d=this.group;c&&d&&b.options&&(a&&c.mapView?(d.attr({opacity:.01}),c.mapView.allowTransformAnimation=!1,b.options.inactiveOtherPoints=!0,b.options.enableMouseTracking=!1):(d.animate({opacity:1},c.options.drilldown.animation,function(){b.options&&(b.options.inactiveOtherPoints=!1,b.options.enableMouseTracking=q(b.userOptions&&b.userOptions.enableMouseTracking,
!0),b.isDirty=!0,c.redraw())}),c.drilldown&&c.drilldown.fadeInGroup(this.dataLabelsGroup)))},animateDrillupFrom:function(){var a=this.chart;a&&a.mapView&&(a.mapView.allowTransformAnimation=!1);this.options&&(this.options.inactiveOtherPoints=!0)},animateDrillupTo:function(a){var b=this.chart,c=this.group;b&&c&&(a?(c.attr({opacity:.01}),this.options&&(this.options.inactiveOtherPoints=!0)):(c.animate({opacity:1},b.options.drilldown.animation),b.drilldown&&b.drilldown.fadeInGroup(this.dataLabelsGroup)))}});
w.prototype.doDrilldown=function(){this.runDrilldown()};w.prototype.runDrilldown=function(a,b,d){var c=this.series.chart,e=c.options.drilldown,g=(e.series||[]).length;c.ddDupes||(c.ddDupes=[]);for(c.colorCounter=c.symbolCounter=0;g--&&!f;)if(e.series[g].id===this.drilldown&&-1===c.ddDupes.indexOf(this.drilldown)){var f=e.series[g];c.ddDupes.push(this.drilldown)}k(c,"drilldown",{point:this,seriesOptions:f,category:b,originalEvent:d,points:"undefined"!==typeof b&&this.series.xAxis.getDDPoints(b).slice(0)},
function(b){var c=b.point.series&&b.point.series.chart,d=b.seriesOptions;c&&d&&(a?c.addSingleSeriesAsDrilldown(b.point,d):c.addSeriesAsDrilldown(b.point,d))})};t.prototype.drilldownCategory=function(a,b){this.getDDPoints(a).forEach(function(c){c&&c.series&&c.series.visible&&c.runDrilldown&&c.runDrilldown(!0,a,b)});this.chart.applyDrilldown()};t.prototype.getDDPoints=function(a){return this.ddPoints&&this.ddPoints[a]||[]};F.prototype.drillable=function(){var a=this.pos,b=this.label,e=this.axis,f="xAxis"===
e.coll&&e.getDDPoints,h=f&&e.getDDPoints(a),k=e.chart.styledMode;f&&(b&&h&&h.length?(b.drillable=!0,b.basicStyles||k||(b.basicStyles=B(b.styles)),b.addClass("highcharts-drilldown-axis-label"),b.removeOnDrillableClick&&Q(b.element,"click"),b.removeOnDrillableClick=d(b.element,"click",function(b){b.preventDefault();e.drilldownCategory(a,b)}),k||b.css(e.chart.options.drilldown.activeAxisLabelStyle)):b&&b.drillable&&b.removeOnDrillableClick&&(k||(b.styles={},b.element.removeAttribute("style"),b.css(b.basicStyles)),
b.removeOnDrillableClick(),b.removeClass("highcharts-drilldown-axis-label")))};d(w,"afterInit",function(){this.drilldown&&!this.unbindDrilldownClick&&(this.unbindDrilldownClick=d(this,"click",y));return this});d(w,"update",function(a){a=a.options||{};a.drilldown&&!this.unbindDrilldownClick?this.unbindDrilldownClick=d(this,"click",y):!a.drilldown&&void 0!==a.drilldown&&this.unbindDrilldownClick&&(this.unbindDrilldownClick=this.unbindDrilldownClick())});d(E,"afterDrawDataLabels",function(){var a=this.chart.options.drilldown.activeDataLabelStyle,
b=this.chart.renderer,d=this.chart.styledMode;this.points.forEach(function(c){var e=c.options.dataLabels,f=q(c.dlOptions,e&&e.style,{});c.drilldown&&c.dataLabel&&("contrast"!==a.color||d||(f.color=b.getContrast(c.color||this.color)),e&&e.color&&(f.color=e.color),c.dataLabel.addClass("highcharts-drilldown-data-label"),d||c.dataLabel.css(a).css(f))},this)});d(E,"afterDrawTracker",function(){var a=this.chart.styledMode;this.points.forEach(function(b){b.drilldown&&b.graphic&&v(b.graphic,"pointer",!0,
a)})});d(w,"afterSetState",function(){var a=this.series.chart.styledMode;this.drilldown&&this.series.halo&&"hover"===this.state?v(this.series.halo,"pointer",!0,a):this.series.halo&&v(this.series.halo,"auto",!1,a)});d(p,"drillup",function(){this.resetZoomButton&&(this.resetZoomButton=this.resetZoomButton.destroy())});d(p,"drillupall",function(){this.resetZoomButton&&this.showResetZoom()})});r(a,"masters/modules/drilldown.src.js",[a["Core/Globals.js"],a["Extensions/Breadcrumbs/Breadcrumbs.js"]],function(a,
r){a.Breadcrumbs=r;r.compose(a.Chart,a.defaultOptions)})});//# sourceMappingURL=drilldown.js.map