/*
 Highcharts JS v11.1.0 (2023-08-20)

 (c) 2009-2022

 License: www.highcharts.com/license
*/
'use strict';(function(d){"object"===typeof module&&module.exports?(d["default"]=d,module.exports=d):"function"===typeof define&&define.amd?define("highcharts/modules/flowmap",["highcharts"],function(t){d(t);d.Highcharts=t;return d}):d("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(d){function t(h,c,k,a){h.hasOwnProperty(c)||(h[c]=a.apply(null,k),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:c,module:h[c]}})))}d=d?d._modules:
{};t(d,"Series/FlowMap/FlowMapPoint.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(h,c){var k=this&&this.__extends||function(){function b(a,e){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var g in a)Object.prototype.hasOwnProperty.call(a,g)&&(b[g]=a[g])};return b(a,e)}return function(a,e){function f(){this.constructor=a}if("function"!==typeof e&&null!==e)throw new TypeError("Class extends value "+String(e)+" is not a constructor or null");
b(a,e);a.prototype=null===e?Object.create(e):(f.prototype=e.prototype,new f)}}(),a=c.pick,b=c.isString,e=c.isNumber;return function(f){function c(){var a=null!==f&&f.apply(this,arguments)||this;a.options=void 0;a.series=void 0;return a}k(c,f);c.prototype.isValid=function(){var f=!(!this.options.to||!this.options.from);[this.options.to,this.options.from].forEach(function(c){f=!!(f&&c&&(b(c)||e(a(c[0],c.lat))&&e(a(c[1],c.lon))))});return f};return c}(h.seriesTypes.mapline.prototype.pointClass)});t(d,
"Series/ColorMapComposition.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(h,c){var k=h.seriesTypes.column.prototype,a=c.addEvent,b=c.defined,e;(function(e){function f(a){this.moveToTopOnHover&&this.graphic&&this.graphic.attr({zIndex:a&&"hover"===a.state?1:0})}var h=[];e.pointMembers={dataLabelOnNull:!0,moveToTopOnHover:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value&&(void 0===this.value||!isNaN(this.value))}};e.seriesMembers=
{colorKey:"value",axisTypes:["xAxis","yAxis","colorAxis"],parallelArrays:["x","y","value"],pointArrayMap:["value"],trackerGroups:["group","markerGroup","dataLabelsGroup"],colorAttribs:function(a){var e={};!b(a.color)||a.state&&"normal"!==a.state||(e[this.colorProp||"fill"]=a.color);return e},pointAttribs:k.pointAttribs};e.compose=function(e){var b=e.prototype.pointClass;c.pushUnique(h,b)&&a(b,"afterSetState",f);return e}})(e||(e={}));return e});t(d,"Maps/MapSymbols.js",[d["Core/Renderer/SVG/SVGRenderer.js"]],
function(h){var c=h.prototype.symbols;c.bottombutton=function(k,a,b,e,f){if(f){var h=(null===f||void 0===f?void 0:f.r)||0;f.brBoxY=a-h;f.brBoxHeight=e+h}return c.roundedRect(k,a,b,e,f)};c.topbutton=function(k,a,b,e,f){f&&(f.brBoxHeight=e+((null===f||void 0===f?void 0:f.r)||0));return c.roundedRect(k,a,b,e,f)};return c});t(d,"Core/Chart/MapChart.js",[d["Core/Chart/Chart.js"],d["Core/Defaults.js"],d["Core/Renderer/SVG/SVGRenderer.js"],d["Core/Utilities.js"]],function(h,c,k,a){var b=this&&this.__extends||
function(){function a(e,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(g,l){g.__proto__=l}||function(g,l){for(var a in l)Object.prototype.hasOwnProperty.call(l,a)&&(g[a]=l[a])};return a(e,b)}return function(e,b){function g(){this.constructor=e}if("function"!==typeof b&&null!==b)throw new TypeError("Class extends value "+String(b)+" is not a constructor or null");a(e,b);e.prototype=null===b?Object.create(b):(g.prototype=b.prototype,new g)}}(),e=c.getOptions,f=a.merge,d=a.pick;
h=function(a){function c(){return null!==a&&a.apply(this,arguments)||this}b(c,a);c.prototype.init=function(b,g){var l=e().credits;b=f({chart:{panning:{enabled:!0,type:"xy"},type:"map"},credits:{mapText:d(l.mapText,' \u00a9 <a href="{geojson.copyrightUrl}">{geojson.copyrightShort}</a>'),mapTextFull:d(l.mapTextFull,"{geojson.copyright}")},mapView:{},tooltip:{followTouchMove:!1}},b);a.prototype.init.call(this,b,g)};return c}(h);(function(a){a.maps={};a.mapChart=function(b,e,g){return new a(b,e,g)};a.splitPath=
function(a){"string"===typeof a&&(a=a.replace(/([A-Za-z])/g," $1 ").replace(/^\s*/,"").replace(/\s*$/,""),a=a.split(/[ ,;]+/).map(function(a){return/[A-za-z]/.test(a)?a:parseFloat(a)}));return k.prototype.pathToSegments(a)}})(h||(h={}));return h});t(d,"Maps/MapUtilities.js",[],function(){return{boundsFromPath:function(h){var c=-Number.MAX_VALUE,k=Number.MAX_VALUE,a=-Number.MAX_VALUE,b=Number.MAX_VALUE,e;h.forEach(function(f){var h=f[f.length-2];f=f[f.length-1];"number"===typeof h&&"number"===typeof f&&
(k=Math.min(k,h),c=Math.max(c,h),b=Math.min(b,f),a=Math.max(a,f),e=!0)});if(e)return{x1:k,y1:b,x2:c,y2:a}},pointInPolygon:function(h,c){var k,a=!1,b=h.x,e=h.y;h=0;for(k=c.length-1;h<c.length;k=h++){var f=c[h][1]>e;var d=c[k][1]>e;f!==d&&b<(c[k][0]-c[h][0])*(e-c[h][1])/(c[k][1]-c[h][1])+c[h][0]&&(a=!a)}return a}}});t(d,"Series/Map/MapPoint.js",[d["Series/ColorMapComposition.js"],d["Maps/MapUtilities.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(h,c,k,a){var b=this&&this.__extends||
function(){function a(b,g){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(g,a){g.__proto__=a}||function(g,a){for(var l in a)Object.prototype.hasOwnProperty.call(a,l)&&(g[l]=a[l])};return a(b,g)}return function(b,g){function l(){this.constructor=b}if("function"!==typeof g&&null!==g)throw new TypeError("Class extends value "+String(g)+" is not a constructor or null");a(b,g);b.prototype=null===g?Object.create(g):(l.prototype=g.prototype,new l)}}(),e=c.boundsFromPath,f=a.extend,d=a.isNumber,
D=a.pick;c=function(c){function h(){var g=null!==c&&c.apply(this,arguments)||this;g.options=void 0;g.path=void 0;g.series=void 0;return g}b(h,c);h.getProjectedPath=function(g,a){g.projectedPath||(a&&g.geometry?(a.hasCoordinates=!0,g.projectedPath=a.path(g.geometry)):g.projectedPath=g.path);return g.projectedPath||[]};h.prototype.applyOptions=function(g,a){var l=this.series;g=c.prototype.applyOptions.call(this,g,a);a=l.joinBy;l.mapData&&l.mapMap&&(a=c.prototype.getNestedProperty.call(g,a[1]),(a="undefined"!==
typeof a&&l.mapMap[a])?f(g,a):-1!==l.pointArrayMap.indexOf("value")&&(g.value=g.value||null));return g};h.prototype.getProjectedBounds=function(g){var a=h.getProjectedPath(this,g);a=e(a);var b=this.properties,c=this.series.chart.mapView;if(a){var f=b&&b["hc-middle-lon"],E=b&&b["hc-middle-lat"];c&&d(f)&&d(E)?(g=g.forward([f,E]),a.midX=g[0],a.midY=g[1]):(g=b&&b["hc-middle-x"],b=b&&b["hc-middle-y"],a.midX=a.x1+(a.x2-a.x1)*D(this.middleX,d(g)?g:.5),g=D(this.middleY,d(b)?b:.5),this.geometry||(g=1-g),a.midY=
a.y2-(a.y2-a.y1)*g);return a}};h.prototype.onMouseOver=function(g){a.clearTimeout(this.colorInterval);if(!this.isNull&&this.visible||this.series.options.nullInteraction)c.prototype.onMouseOver.call(this,g);else this.series.onMouseOut(g)};h.prototype.setVisible=function(g){var a=g?"show":"hide";this.visible=this.options.visible=!!g;if(this.dataLabel)this.dataLabel[a]();this.graphic&&this.graphic.attr(this.series.pointAttribs(this))};h.prototype.zoomTo=function(g){var a=this.series.chart,b=a.mapView,
e=this.bounds;if(b&&e){var c=d(this.insetIndex)&&b.insets[this.insetIndex];if(c){var f=c.projectedUnitsToPixels({x:e.x1,y:e.y1});e=c.projectedUnitsToPixels({x:e.x2,y:e.y2});f=b.pixelsToProjectedUnits({x:f.x,y:f.y});e=b.pixelsToProjectedUnits({x:e.x,y:e.y});e={x1:f.x,y1:f.y,x2:e.x,y2:e.y}}b.fitToBounds(e,void 0,!1);this.series.isDirty=!0;a.redraw(g)}};return h}(k.seriesTypes.scatter.prototype.pointClass);f(c.prototype,{dataLabelOnNull:h.pointMembers.dataLabelOnNull,moveToTopOnHover:h.pointMembers.moveToTopOnHover,
isValid:h.pointMembers.isValid});return c});t(d,"Maps/MapViewOptionsDefault.js",[],function(){return{center:[0,0],fitToGeometry:void 0,maxZoom:void 0,padding:0,projection:{name:void 0,parallels:void 0,rotation:void 0},zoom:void 0}});t(d,"Maps/MapViewInsetsOptionsDefault.js",[],function(){return{borderColor:"#cccccc",borderWidth:1,center:[0,0],padding:"10%",relativeTo:"mapBoundingBox",units:"percent"}});t(d,"Extensions/GeoJSON.js",[d["Core/Chart/Chart.js"],d["Core/Templating.js"],d["Core/Globals.js"],
d["Core/Utilities.js"]],function(h,c,d,a){function b(g,a){function b(a){return"number"===typeof a[0]?a.reduce(function(a,g,b){var l=0>g?e[~g]:e[g];0>g?(l=l.slice(0,0===b?l.length:l.length-1),l.reverse()):b&&(l=l.slice(1));return a.concat(l)},[]):a.map(b)}a||(a=Object.keys(g.objects)[0]);a=g.objects[a];if(a["hc-decoded-geojson"])return a["hc-decoded-geojson"];var e=g.arcs;if(g.transform){var l=g.transform,c=l.scale,f=l.translate;e=g.arcs.map(function(a){var g=0,b=0;return a.map(function(a){a=a.slice();
a[0]=(g+=a[0])*c[0]+f[0];a[1]=(b+=a[1])*c[1]+f[1];return a})})}l=a.geometries.map(function(a){return{type:"Feature",properties:a.properties,geometry:{type:a.type,coordinates:a.coordinates||b(a.arcs)}}});g={type:"FeatureCollection",copyright:g.copyright,copyrightShort:g.copyrightShort,copyrightUrl:g.copyrightUrl,features:l,"hc-recommended-mapview":a["hc-recommended-mapview"],bbox:g.bbox,title:g.title};return a["hc-decoded-geojson"]=g}function e(a,e,c){void 0===e&&(e="map");var g=[];a="Topology"===
a.type?b(a):a;a.features.forEach(function(a){var b=a.geometry||{},l=b.type;b=b.coordinates;a=a.properties;var c;"map"!==e&&"mapbubble"!==e||"Polygon"!==l&&"MultiPolygon"!==l?"mapline"!==e||"LineString"!==l&&"MultiLineString"!==l?"mappoint"===e&&"Point"===l&&b.length&&(c={geometry:{coordinates:b,type:l}}):b.length&&(c={geometry:{coordinates:b,type:l}}):b.length&&(c={geometry:{coordinates:b,type:l}});if(c){l=a&&(a.name||a.NAME);b=a&&a.lon;var f=a&&a.lat;g.push(p(c,{lat:"number"===typeof f?f:void 0,
lon:"number"===typeof b?b:void 0,name:"string"===typeof l?l:void 0,properties:a}))}});c&&a.copyrightShort&&(c.chart.mapCredits=f(c.chart.options.credits.mapText,{geojson:a}),c.chart.mapCreditsFull=f(c.chart.options.credits.mapTextFull,{geojson:a}));return g}var f=c.format,k=d.win,D=a.error,p=a.extend,v=a.merge;c=a.wrap;"";h.prototype.transformFromLatLon=function(a,b){var g=this.options.chart.proj4||k.proj4;if(g){var e=b.jsonmarginX;e=void 0===e?0:e;var c=b.jsonmarginY;c=void 0===c?0:c;var l=b.jsonres;
l=void 0===l?1:l;var f=b.scale;f=void 0===f?1:f;var h=b.xoffset;h=void 0===h?0:h;var d=b.xpan;d=void 0===d?0:d;var m=b.yoffset;m=void 0===m?0:m;var n=b.ypan;n=void 0===n?0:n;a=g(b.crs,[a.lon,a.lat]);g=b.cosAngle||b.rotation&&Math.cos(b.rotation);var r=b.sinAngle||b.rotation&&Math.sin(b.rotation);b=b.rotation?[a[0]*g+a[1]*r,-a[0]*r+a[1]*g]:a;return{x:((b[0]-h)*f+d)*l+e,y:-(((m-b[1])*f+n)*l-c)}}D(21,!1,this)};h.prototype.transformToLatLon=function(a,b){var g=this.options.chart.proj4||k.proj4;if(!g)D(21,
!1,this);else if(null!==a.y){var e=b.jsonmarginX,c=b.jsonmarginY,f=b.jsonres;f=void 0===f?1:f;var l=b.scale;l=void 0===l?1:l;var h=b.xoffset,d=b.xpan,m=b.yoffset,n=b.ypan;a={x:((a.x-(void 0===e?0:e))/f-(void 0===d?0:d))/l+(void 0===h?0:h),y:((a.y-(void 0===c?0:c))/f+(void 0===n?0:n))/l+(void 0===m?0:m)};e=b.cosAngle||b.rotation&&Math.cos(b.rotation);c=b.sinAngle||b.rotation&&Math.sin(b.rotation);b=g(b.crs,"WGS84",b.rotation?{x:a.x*e+a.y*-c,y:a.x*c+a.y*e}:a);return{lat:b.y,lon:b.x}}};h.prototype.fromPointToLatLon=
function(a){return this.mapView&&this.mapView.projectedUnitsToLonLat(a)};h.prototype.fromLatLonToPoint=function(a){return this.mapView&&this.mapView.lonLatToProjectedUnits(a)};c(h.prototype,"addCredits",function(a,b){b=v(!0,this.options.credits,b);this.mapCredits&&(b.href=null);a.call(this,b);this.credits&&this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})});d.geojson=e;d.topo2geo=b;return{geojson:e,topo2geo:b}});t(d,"Core/Geometry/PolygonClip.js",[],function(){function h(a,b,e,c){var f=
[a[0]-b[0],a[1]-b[1]],h=[e[0]-c[0],e[1]-c[1]];a=a[0]*b[1]-a[1]*b[0];e=e[0]*c[1]-e[1]*c[0];c=1/(f[0]*h[1]-f[1]*h[0]);f=[(a*h[0]-e*f[0])*c,(a*h[1]-e*f[1])*c];f.isIntersection=!0;return f}function c(a,b,e){return(b[0]-a[0])*(e[1]-a[1])>(b[1]-a[1])*(e[0]-a[0])}var d;(function(a){a.clipLineString=function(b,e){var c=[];b=a.clipPolygon(b,e,!1);for(e=1;e<b.length;e++)b[e].isIntersection&&b[e-1].isIntersection&&(c.push(b.splice(0,e)),e=0),e===b.length-1&&c.push(b);return c};a.clipPolygon=function(a,e,f){void 0===
f&&(f=!0);for(var b=e[e.length-1],d,k,v=a,g=0;g<e.length;g++){var l=v;a=e[g];v=[];d=f?l[l.length-1]:l[0];for(var G=0;G<l.length;G++)k=l[G],c(b,a,k)?(c(b,a,d)||v.push(h(b,a,d,k)),v.push(k)):c(b,a,d)&&v.push(h(b,a,d,k)),d=k;b=a}return v}})(d||(d={}));return d});t(d,"Maps/Projections/LambertConformalConic.js",[],function(){var h=Math.sign||function(a){return 0===a?0:0<a?1:-1},c=Math.PI/180,d=Math.PI/2;return function(){function a(a){var b,f=(a.parallels||[]).map(function(a){return a*c}),k=f[0]||0;f=
null!==(b=f[1])&&void 0!==b?b:k;b=Math.cos(k);"object"===typeof a.projectedBounds&&(this.projectedBounds=a.projectedBounds);a=k===f?Math.sin(k):Math.log(b/Math.cos(f))/Math.log(Math.tan((d+f)/2)/Math.tan((d+k)/2));1e-10>Math.abs(a)&&(a=1e-10*(h(a)||1));this.n=a;this.c=b*Math.pow(Math.tan((d+k)/2),a)/a}a.prototype.forward=function(a){var b=a[0]*c,f=this.c,h=this.n,k=this.projectedBounds;a=a[1]*c;0<f?a<-d+.000001&&(a=-d+.000001):a>d-.000001&&(a=d-.000001);var p=f/Math.pow(Math.tan((d+a)/2),h);a=p*Math.sin(h*
b)*63.78137;b=63.78137*(f-p*Math.cos(h*b));f=[a,b];k&&(a<k.x1||a>k.x2||b<k.y1||b>k.y2)&&(f.outside=!0);return f};a.prototype.inverse=function(a){var b=a[0]/63.78137,f=this.c,k=this.n;a=f-a[1]/63.78137;var t=h(k)*Math.sqrt(b*b+a*a),p=Math.atan2(b,Math.abs(a))*h(a);0>a*k&&(p-=Math.PI*h(b)*h(a));return[p/k/c,(2*Math.atan(Math.pow(f/t,1/k))-d)/c]};return a}()});t(d,"Maps/Projections/EqualEarth.js",[],function(){var d=Math.sqrt(3)/2;return function(){function c(){this.bounds={x1:-200.37508342789243,x2:200.37508342789243,
y1:-97.52595454902263,y2:97.52595454902263}}c.prototype.forward=function(c){var a=Math.PI/180,b=Math.asin(d*Math.sin(c[1]*a)),e=b*b,f=e*e*e;return[c[0]*a*Math.cos(b)*74.03120656864502/(d*(1.340264+3*-.081106*e+f*(7*.000893+.034164*e))),74.03120656864502*b*(1.340264+-.081106*e+f*(.000893+.003796*e))]};c.prototype.inverse=function(c){var a=c[0]/74.03120656864502;c=c[1]/74.03120656864502;var b=180/Math.PI,e=c,f;for(f=0;12>f;++f){var h=e*e;var k=h*h*h;var p=e*(1.340264+-.081106*h+k*(.000893+.003796*h))-
c;h=1.340264+3*-.081106*h+k*(7*.000893+.034164*h);e-=p/=h;if(1e-9>Math.abs(p))break}h=e*e;return[b*d*a*(1.340264+3*-.081106*h+h*h*h*(7*.000893+.034164*h))/Math.cos(e),b*Math.asin(Math.sin(e)/d)]};return c}()});t(d,"Maps/Projections/Miller.js",[],function(){var h=Math.PI/4,c=Math.PI/180;return function(){function d(){this.bounds={x1:-200.37508342789243,x2:200.37508342789243,y1:-146.91480769173063,y2:146.91480769173063}}d.prototype.forward=function(a){return[a[0]*c*63.78137,79.7267125*Math.log(Math.tan(h+
.4*a[1]*c))]};d.prototype.inverse=function(a){return[a[0]/63.78137/c,2.5*(Math.atan(Math.exp(a[1]/63.78137*.8))-h)/c]};return d}()});t(d,"Maps/Projections/Orthographic.js",[],function(){var d=Math.PI/180;return function(){function c(){this.antimeridianCutting=!1;this.bounds={x1:-63.78460826781007,x2:63.78460826781007,y1:-63.78460826781007,y2:63.78460826781007}}c.prototype.forward=function(c){var a=c[0];c=c[1]*d;c=[Math.cos(c)*Math.sin(a*d)*63.78460826781007,63.78460826781007*Math.sin(c)];if(-90>a||
90<a)c.outside=!0;return c};c.prototype.inverse=function(c){var a=c[0]/63.78460826781007;c=c[1]/63.78460826781007;var b=Math.sqrt(a*a+c*c),e=Math.asin(b),f=Math.sin(e);return[Math.atan2(a*f,b*Math.cos(e))/d,Math.asin(b&&c*f/b)/d]};return c}()});t(d,"Maps/Projections/WebMercator.js",[],function(){var d=Math.PI/180;return function(){function c(){this.bounds={x1:-200.37508342789243,x2:200.37508342789243,y1:-200.3750834278071,y2:200.3750834278071};this.maxLatitude=85.0511287798}c.prototype.forward=function(c){var a=
Math.sin(c[1]*d);a=[63.78137*c[0]*d,63.78137*Math.log((1+a)/(1-a))/2];85.0511287798<Math.abs(c[1])&&(a.outside=!0);return a};c.prototype.inverse=function(c){return[c[0]/(63.78137*d),(2*Math.atan(Math.exp(c[1]/63.78137))-Math.PI/2)/d]};return c}()});t(d,"Maps/Projections/ProjectionRegistry.js",[d["Maps/Projections/LambertConformalConic.js"],d["Maps/Projections/EqualEarth.js"],d["Maps/Projections/Miller.js"],d["Maps/Projections/Orthographic.js"],d["Maps/Projections/WebMercator.js"]],function(d,c,k,
a,b){return{EqualEarth:c,LambertConformalConic:d,Miller:k,Orthographic:a,WebMercator:b}});t(d,"Maps/Projection.js",[d["Core/Geometry/PolygonClip.js"],d["Maps/Projections/ProjectionRegistry.js"],d["Core/Utilities.js"]],function(d,c,k){function a(a){-180>a&&(a+=360);180<a&&(a-=360);return a}var b=this&&this.__spreadArray||function(a,b,c){if(c||2===arguments.length)for(var g=0,e=b.length,d;g<e;g++)!d&&g in b||(d||(d=Array.prototype.slice.call(b,0,g)),d[g]=b[g]);return a.concat(d||Array.prototype.slice.call(b))},
e=d.clipLineString,f=d.clipPolygon,h=k.clamp,t=k.erase,p=2*Math.PI/360;return function(){function d(a){void 0===a&&(a={});this.hasGeoProjection=this.hasCoordinates=!1;this.maxLatitude=90;this.options=a;var b=a.name,c=a.projectedBounds,g=a.rotation;this.rotator=g?this.getRotator(g):void 0;if(b=b?d.registry[b]:void 0)this.def=new b(a);var e=this.def,f=this.rotator;e&&(this.maxLatitude=e.maxLatitude||90,this.hasGeoProjection=!0);f&&e?(this.forward=function(a){return e.forward(f.forward(a))},this.inverse=
function(a){return f.inverse(e.inverse(a))}):e?(this.forward=function(a){return e.forward(a)},this.inverse=function(a){return e.inverse(a)}):f&&(this.forward=f.forward,this.inverse=f.inverse);this.bounds="world"===c?e&&e.bounds:c}d.add=function(a,b){d.registry[a]=b};d.greatCircle=function(a,b,c){var g=Math.atan2,d=Math.cos,e=Math.sin,f=Math.sqrt,h=a[1]*p,l=a[0]*p,m=b[1]*p,n=b[0]*p,r=m-h,y=n-l;r=e(r/2)*e(r/2)+d(h)*d(m)*e(y/2)*e(y/2);r=2*g(f(r),f(1-r));var C=Math.round(6371E3*r/5E5);y=[];c&&y.push(a);
if(1<C)for(C=a=1/C;.999>C;C+=a){var k=e((1-C)*r)/e(r),H=e(C*r)/e(r),q=k*d(h)*d(l)+H*d(m)*d(n),w=k*d(h)*e(l)+H*d(m)*e(n);k=k*e(h)+H*e(m);k=g(k,f(q*q+w*w));q=g(w,q);y.push([q/p,k/p])}c&&y.push(b);return y};d.insertGreatCircles=function(a){for(var c=a.length-1;c--;)if(10<Math.max(Math.abs(a[c][0]-a[c+1][0]),Math.abs(a[c][1]-a[c+1][1]))){var g=d.greatCircle(a[c],a[c+1]);g.length&&a.splice.apply(a,b([c+1,0],g,!1))}};d.toString=function(a){a=a||{};var b=a.rotation;return[a.name,b&&b.join(",")].join(";")};
d.prototype.lineIntersectsBounds=function(a){function b(a,b,c){var d=a[0];a=a[1];var e=b?0:1;if("number"===typeof c&&d[b]>=c!==a[b]>=c)return d=d[e]+(c-d[b])/(a[b]-d[b])*(a[e]-d[e]),b?[d,c]:[c,d]}var c=this.bounds||{},d=c.x2,e=c.y1,g=c.y2,f=a[0];if(c=b(a,0,c.x1))f=c,a[1]=c;else if(c=b(a,0,d))f=c,a[1]=c;if(c=b(a,1,e))f=c;else if(c=b(a,1,g))f=c;return f};d.prototype.getRotator=function(a){var b=a[0]*p,c=(a[1]||0)*p;a=(a[2]||0)*p;var d=Math.cos(c),e=Math.sin(c),g=Math.cos(a),f=Math.sin(a);if(0!==b||
0!==c||0!==a)return{forward:function(a){var c=a[0]*p+b,m=a[1]*p,h=Math.cos(m);a=Math.cos(c)*h;c=Math.sin(c)*h;m=Math.sin(m);h=m*d+a*e;return[Math.atan2(c*g-h*f,a*d-m*e)/p,Math.asin(h*g+c*f)/p]},inverse:function(a){var c=a[0]*p,h=a[1]*p,n=Math.cos(h);a=Math.cos(c)*n;c=Math.sin(c)*n;h=Math.sin(h);n=h*g-c*f;return[(Math.atan2(c*g+h*f,a*d+n*e)-b)/p,Math.asin(n*d-a*e)/p]}}};d.prototype.forward=function(a){return a};d.prototype.inverse=function(a){return a};d.prototype.cutOnAntimeridian=function(c,e){var f=
[],g=[c];c.forEach(function(a,b){var d=c[b-1];if(!b){if(!e)return;d=c[c.length-1]}var g=d[0],q=a[0];(-90>g||90<g)&&(-90>q||90<q)&&0<g!==0<q&&(q=h((180-(g+360)%360)/((q+360)%360-(g+360)%360),0,1),f.push({i:b,lat:d[1]+q*(a[1]-d[1]),direction:0>g?1:-1,previousLonLat:d,lonLat:a}))});if(f.length)if(e){if(1===f.length%2){var l=f.slice().sort(function(a,b){return Math.abs(b.lat)-Math.abs(a.lat)})[0];t(f,l)}for(var k=f.length-2;0<=k;){var p=f[k].i,u=a(180+.000001*f[k].direction),x=a(180-.000001*f[k].direction);
p=c.splice.apply(c,b([p,f[k+1].i-p],d.greatCircle([u,f[k].lat],[u,f[k+1].lat],!0),!1));p.push.apply(p,d.greatCircle([x,f[k+1].lat],[x,f[k].lat],!0));g.push(p);k-=2}if(l)for(u=0;u<g.length;u++){k=l.direction;var m=l.lat;x=g[u];p=x.indexOf(l.lonLat);if(-1<p){u=(0>m?-1:1)*this.maxLatitude;var n=a(180+.000001*k),r=a(180-.000001*k);m=d.greatCircle([n,m],[n,u],!0);for(n+=120*k;-180<n&&180>n;n+=120*k)m.push([n,u]);m.push.apply(m,d.greatCircle([r,u],[r,l.lat],!0));x.splice.apply(x,b([p,0],m,!1));break}}}else for(k=
f.length;k--;)p=f[k].i,p=c.splice(p,c.length,[a(180+.000001*f[k].direction),f[k].lat]),p.unshift([a(180-.000001*f[k].direction),f[k].lat]),g.push(p);return g};d.prototype.path=function(a){function b(a){a=a.map(function(a){if(m){n&&(a=n.forward(a));var b=a[0];.000001>Math.abs(b-180)&&(b=180>b?179.999999:180.000001);a=[b,a[1]]}return a});var b=[a];x&&(d.insertGreatCircles(a),m&&(b=c.cutOnAntimeridian(a,u)));b.forEach(function(a){if(!(2>a.length)){var b=!1,c=!1,J=function(a){b?p.push(["L",a[0],a[1]]):
(p.push(["M",a[0],a[1]]),b=!0)},A=!1,F=!1,K=a.map(function(a){a=r.forward(a);a.outside?A=!0:F=!0;Infinity===a[1]?a[1]=1E10:-Infinity===a[1]&&(a[1]=-1E10);return a});if(m){u&&K.push(K[0]);if(A){if(!F)return;if(y)if(u)K=f(K,y);else if(g){e(K,y).forEach(function(a){b=!1;a.forEach(J)});return}}K.forEach(J)}else for(var h=0;h<K.length;h++){var z=a[h],n=K[h];if(n.outside)c=!0;else{if(u&&!k){var k=z;a.push(z);K.push(n)}c&&H&&(u&&x?d.greatCircle(H,z).forEach(function(a){return J(r.forward(a))}):b=!1);J(n);
var H=z;c=!1}}}})}var c=this,g=this.bounds,h=this.def,k=this.rotator,p=[],u="Polygon"===a.type||"MultiPolygon"===a.type,x=this.hasGeoProjection,m=!h||!1!==h.antimeridianCutting,n=m?k:void 0,r=m?h||this:this,y;g&&(y=[[g.x1,g.y1],[g.x2,g.y1],[g.x2,g.y2],[g.x1,g.y2]]);"LineString"===a.type?b(a.coordinates):"MultiLineString"===a.type?a.coordinates.forEach(function(a){return b(a)}):"Polygon"===a.type?(a.coordinates.forEach(function(a){return b(a)}),p.length&&p.push(["Z"])):"MultiPolygon"===a.type&&(a.coordinates.forEach(function(a){a.forEach(function(a){return b(a)})}),
p.length&&p.push(["Z"]));return p};d.registry=c;return d}()});t(d,"Maps/MapView.js",[d["Maps/MapViewOptionsDefault.js"],d["Maps/MapViewInsetsOptionsDefault.js"],d["Extensions/GeoJSON.js"],d["Core/Chart/MapChart.js"],d["Maps/MapUtilities.js"],d["Maps/Projection.js"],d["Core/Utilities.js"]],function(d,c,k,a,b,e,f){function h(a,b){return Math.log(400.979322/Math.max((a.x2-a.x1)/(b.width/256),(a.y2-a.y1)/(b.height/256)))/Math.log(2)}var t=this&&this.__extends||function(){function a(b,c){a=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};return a(b,c)}return function(b,c){function d(){this.constructor=b}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),p=this&&this.__spreadArray||function(a,b,c){if(c||2===arguments.length)for(var d=0,q=
b.length,e;d<q;d++)!e&&d in b||(e||(e=Array.prototype.slice.call(b,0,d)),e[d]=b[d]);return a.concat(e||Array.prototype.slice.call(b))},v=k.topo2geo,g=a.maps,l=b.boundsFromPath,G=b.pointInPolygon,B=f.addEvent,L=f.clamp,E=f.fireEvent,M=f.isArray,u=f.isNumber,x=f.isObject,m=f.isString,n=f.merge,r=f.pick,y=f.relativeLength,C=function(){function a(b,c){var q=this;this.allowTransformAnimation=!0;this.insets=[];this.padding=[0,0,0,0];this.eventsToUnbind=[];var A;if(!(this instanceof O)){var w=p([b.options.chart.map],
(b.options.series||[]).map(function(a){return a.mapData}),!0).map(function(a){return q.getGeoMap(a)}),f=[];w.forEach(function(a){a&&(h||(h=a["hc-recommended-mapview"]),a.bbox&&(a=a.bbox,f.push({x1:a[0],y1:a[1],x2:a[2],y2:a[3]})))});var g=f.length&&a.compositeBounds(f);E(b,"beforeMapViewInit",{geoBounds:g},function(){if(g){var a=g.x1,b=g.y1,c=g.x2,d=g.y2;A=180<c-a&&90<d-b?{name:"EqualEarth"}:{name:"LambertConformalConic",parallels:[b,d],rotation:[-(a+c)/2]}}});this.geoMap=w[0]}this.userOptions=c||
{};if(b.options.mapView&&b.options.mapView.recommendedMapView)var h=b.options.mapView.recommendedMapView;w=n(d,{projection:A},h,c);var m=h&&h.insets;c=c&&c.insets;m&&c&&(w.insets=a.mergeInsets(m,c));this.chart=b;this.center=w.center;this.options=w;this.projection=new e(w.projection);this.playingField=b.plotBox;this.zoom=w.zoom||0;this.minZoom=w.minZoom;this.createInsets();this.eventsToUnbind.push(B(b,"afterSetChartSize",function(){q.playingField=q.getField();if(void 0===q.minZoom||q.minZoom===q.zoom)q.fitToBounds(void 0,
void 0,!1),!q.chart.hasRendered&&u(q.userOptions.zoom)&&(q.zoom=q.userOptions.zoom),q.userOptions.center&&n(!0,q.center,q.userOptions.center)}));this.setUpEvents()}a.mergeInsets=function(a,b){function c(a){var b={};a.forEach(function(a,c){b[a&&a.id||"i".concat(c)]=a});return b}var d=n(c(a),c(b));return Object.keys(d).map(function(a){return d[a]})};a.prototype.createInsets=function(){var a=this,b=this.options,c=b.insets;c&&c.forEach(function(c){c=new O(a,n(b.insetOptions,c));a.insets.push(c)})};a.prototype.fitToBounds=
function(a,b,c,d){void 0===c&&(c=!0);var e=a||this.getProjectedBounds();if(e){var q=r(b,a?0:this.options.padding);b=this.getField(!1);q=M(q)?q:[q,q,q,q];this.padding=[y(q[0],b.height),y(q[1],b.width),y(q[2],b.height),y(q[3],b.width)];this.playingField=this.getField();b=h(e,this.playingField);a||(this.minZoom=b);a=this.projection.inverse([(e.x2+e.x1)/2,(e.y2+e.y1)/2]);this.setView(a,b,c,d)}};a.prototype.getField=function(a){void 0===a&&(a=!0);a=a?this.padding:[0,0,0,0];return{x:a[3],y:a[0],width:this.chart.plotWidth-
a[1]-a[3],height:this.chart.plotHeight-a[0]-a[2]}};a.prototype.getGeoMap=function(a){if(m(a))return g[a]&&"Topology"===g[a].type?v(g[a]):g[a];if(x(a,!0)){if("FeatureCollection"===a.type)return a;if("Topology"===a.type)return v(a)}};a.prototype.getMapBBox=function(){var a=this.getProjectedBounds(),b=this.getScale();if(a){var c=this.padding,d=this.projectedUnitsToPixels({x:a.x1,y:a.y2});return{width:(a.x2-a.x1)*b+c[1]+c[3],height:(a.y2-a.y1)*b+c[0]+c[2],x:d.x-c[3],y:d.y-c[0]}}};a.prototype.getProjectedBounds=
function(){var b=this.projection,c=this.chart.series.reduce(function(a,b){var c=b.getProjectedBounds&&b.getProjectedBounds();c&&!1!==b.options.affectsMapView&&a.push(c);return a},[]),d=this.options.fitToGeometry;return d?(this.fitToGeometryCache||("MultiPoint"===d.type?(d=d.coordinates.map(function(a){return b.forward(a)}),c=d.map(function(a){return a[0]}),d=d.map(function(a){return a[1]}),this.fitToGeometryCache={x1:Math.min.apply(0,c),x2:Math.max.apply(0,c),y1:Math.min.apply(0,d),y2:Math.max.apply(0,
d)}):this.fitToGeometryCache=l(b.path(d))),this.fitToGeometryCache):this.projection.bounds||a.compositeBounds(c)};a.prototype.getScale=function(){return 256/400.979322*Math.pow(2,this.zoom)};a.prototype.getSVGTransform=function(){var a=this.playingField,b=a.x,c=a.y,d=a.width;a=a.height;var e=this.projection.forward(this.center),f=this.projection.hasCoordinates?-1:1,g=this.getScale();f*=g;return{scaleX:g,scaleY:f,translateX:b+d/2-e[0]*g,translateY:c+a/2-e[1]*f}};a.prototype.lonLatToPixels=function(a){if(a=
this.lonLatToProjectedUnits(a))return this.projectedUnitsToPixels(a)};a.prototype.lonLatToProjectedUnits=function(a){var b=this.chart,c=b.mapTransforms;if(c){for(var d in c)if(Object.hasOwnProperty.call(c,d)&&c[d].hitZone){var e=b.transformFromLatLon(a,c[d]);if(e&&G(e,c[d].hitZone.coordinates[0]))return e}return b.transformFromLatLon(a,c["default"])}c=0;for(d=this.insets;c<d.length;c++)if(b=d[c],b.options.geoBounds&&G({x:a.lon,y:a.lat},b.options.geoBounds.coordinates[0]))return a=b.projection.forward([a.lon,
a.lat]),a=b.projectedUnitsToPixels({x:a[0],y:a[1]}),this.pixelsToProjectedUnits(a);a=this.projection.forward([a.lon,a.lat]);if(!a.outside)return{x:a[0],y:a[1]}};a.prototype.projectedUnitsToLonLat=function(a){var b=this.chart,c=b.mapTransforms;if(c){for(var d in c)if(Object.hasOwnProperty.call(c,d)&&c[d].hitZone&&G(a,c[d].hitZone.coordinates[0]))return b.transformToLatLon(a,c[d]);return b.transformToLatLon(a,c["default"])}c=this.projectedUnitsToPixels(a);d=0;for(var e=this.insets;d<e.length;d++)if(b=
e[d],b.hitZone&&G(c,b.hitZone.coordinates[0]))return a=b.pixelsToProjectedUnits(c),a=b.projection.inverse([a.x,a.y]),{lon:a[0],lat:a[1]};a=this.projection.inverse([a.x,a.y]);return{lon:a[0],lat:a[1]}};a.prototype.redraw=function(a){this.chart.series.forEach(function(a){a.useMapGeometry&&(a.isDirty=!0)});this.chart.redraw(a)};a.prototype.setView=function(a,b,c,d){void 0===c&&(c=!0);a&&(this.center=a);"number"===typeof b&&("number"===typeof this.minZoom&&(b=Math.max(b,this.minZoom)),"number"===typeof this.options.maxZoom&&
(b=Math.min(b,this.options.maxZoom)),u(b)&&(this.zoom=b));var e=this.getProjectedBounds();if(e){a=this.projection.forward(this.center);var f=this.playingField;b=f.x;var g=f.y,h=f.width;f=f.height;var A=this.getScale(),w=this.projectedUnitsToPixels({x:e.x1,y:e.y1}),m=this.projectedUnitsToPixels({x:e.x2,y:e.y2});e=[(e.x1+e.x2)/2,(e.y1+e.y2)/2];if(!this.chart.series.some(function(a){return a.isDrilling})){var J=w.x,q=m.y;m=m.x;w=w.y;m-J<h?a[0]=e[0]:J<b&&m<b+h?a[0]+=Math.max(J-b,m-h-b)/A:m>b+h&&J>b&&
(a[0]+=Math.min(m-h-b,J-b)/A);w-q<f?a[1]=e[1]:q<g&&w<g+f?a[1]-=Math.max(q-g,w-f-g)/A:w>g+f&&q>g&&(a[1]-=Math.min(w-f-g,q-g)/A);this.center=this.projection.inverse(a)}this.insets.forEach(function(a){a.options.field&&(a.hitZone=a.getHitZone(),a.playingField=a.getField())});this.render()}E(this,"afterSetView");c&&this.redraw(d)};a.prototype.projectedUnitsToPixels=function(a){var b=this.getScale(),c=this.projection.forward(this.center),d=this.playingField;return{x:d.x+d.width/2-b*(c[0]-a.x),y:d.y+d.height/
2+b*(c[1]-a.y)}};a.prototype.pixelsToLonLat=function(a){return this.projectedUnitsToLonLat(this.pixelsToProjectedUnits(a))};a.prototype.pixelsToProjectedUnits=function(a){var b=a.x;a=a.y;var c=this.getScale(),d=this.projection.forward(this.center),e=this.playingField;return{x:d[0]+(b-(e.x+e.width/2))/c,y:d[1]-(a-(e.y+e.height/2))/c}};a.prototype.setUpEvents=function(){function a(a){var g=c.pointer.pinchDown,A=b.projection,m=c.mouseDownX,F=c.mouseDownY;1===g.length&&(m=g[0].chartX,F=g[0].chartY);if("number"===
typeof m&&"number"===typeof F){var n="".concat(m,",").concat(F),w=a.originalEvent;g=w.chartX;w=w.chartY;n!==e&&(e=n,d=b.projection.forward(b.center),f=(b.projection.options.rotation||[0,0]).slice());n=(n=A.def&&A.def.bounds)&&h(n,b.playingField)||-Infinity;"Orthographic"===A.options.name&&(b.minZoom||Infinity)<1.3*n?(A=440/(b.getScale()*Math.min(c.plotWidth,c.plotHeight)),f&&(m=(m-g)*A-f[0],F=L(-f[1]-(F-w)*A,-80,80),g=b.zoom,b.update({projection:{rotation:[-m,-F]}},!1),b.fitToBounds(void 0,void 0,
!1),b.zoom=g,c.redraw(!1))):u(g)&&u(w)&&(A=b.getScale(),F=b.projection.inverse([d[0]+(m-g)/A,d[1]-(F-w)/A*(b.projection.hasCoordinates?1:-1)]),b.setView(F,void 0,!0,!1));a.preventDefault()}}var b=this,c=this.chart,d,e,f;B(c,"pan",a);B(c,"touchpan",a);B(c,"selection",function(a){if(a.resetSelection)b.zoomBy();else{var d=a.x-c.plotLeft,e=a.y-c.plotTop,f=b.pixelsToProjectedUnits({x:d,y:e}),g=f.y;f=f.x;d=b.pixelsToProjectedUnits({x:d+a.width,y:e+a.height});b.fitToBounds({x1:f,y1:g,x2:d.x,y2:d.y},void 0,
!0,a.originalEvent.touches?!1:void 0);/^touch/.test(a.originalEvent.type)||c.showResetZoom();a.preventDefault()}})};a.prototype.render=function(){this.group||(this.group=this.chart.renderer.g("map-view").attr({zIndex:4}).add())};a.prototype.update=function(a,b,c){void 0===b&&(b=!0);var d=a.projection;d=d&&e.toString(d)!==e.toString(this.options.projection);var f=!1;n(!0,this.userOptions,a);n(!0,this.options,a);"insets"in a&&(this.insets.forEach(function(a){return a.destroy()}),this.insets.length=
0,f=!0);(d||"fitToGeometry"in a)&&delete this.fitToGeometryCache;if(d||f)this.chart.series.forEach(function(a){var b=a.transformGroups;a.clearBounds&&a.clearBounds();a.isDirty=!0;a.isDirtyData=!0;if(f&&b)for(;1<b.length;)(a=b.pop())&&a.destroy()}),d&&(this.projection=new e(this.options.projection)),f&&this.createInsets(),a.center||!Object.hasOwnProperty.call(a,"zoom")||u(a.zoom)||this.fitToBounds(void 0,void 0,!1);a.center||u(a.zoom)?this.setView(this.options.center,a.zoom,!1):"fitToGeometry"in a&&
this.fitToBounds(void 0,void 0,!1);b&&this.chart.redraw(c)};a.prototype.zoomBy=function(a,b,c,d){var e=this.chart,f=this.projection.forward(this.center);b=b?this.projection.forward(b):[];var g=b[0],h=b[1];"number"===typeof a?(a=this.zoom+a,b=void 0,c&&(g=c[0],h=c[1],c=this.getScale(),g=g-e.plotLeft-e.plotWidth/2,e=h-e.plotTop-e.plotHeight/2,g=f[0]+g/c,h=f[1]+e/c),"number"===typeof g&&"number"===typeof h&&(c=1-Math.pow(2,this.zoom)/Math.pow(2,a),g=f[0]-g,e=f[1]-h,f[0]-=g*c,f[1]+=e*c,b=this.projection.inverse(f)),
this.setView(b,a,void 0,d)):this.fitToBounds(void 0,void 0,void 0,d)};a.compositeBounds=function(a){if(a.length)return a.slice(1).reduce(function(a,b){a.x1=Math.min(a.x1,b.x1);a.y1=Math.min(a.y1,b.y1);a.x2=Math.max(a.x2,b.x2);a.y2=Math.max(a.y2,b.y2);return a},n(a[0]))};return a}(),O=function(a){function b(b,d){var e=a.call(this,b.chart,d)||this;e.id=d.id;e.mapView=b;e.options=n(c,d);e.allBounds=[];e.options.geoBounds&&(b=b.projection.path(e.options.geoBounds),e.geoBoundsProjectedBox=l(b),e.geoBoundsProjectedPolygon=
b.map(function(a){return[a[1]||0,a[2]||0]}));return e}t(b,a);b.prototype.getField=function(b){void 0===b&&(b=!0);var c=this.hitZone;if(c){var d=b?this.padding:[0,0,0,0];c=c.coordinates[0];var e=c.map(function(a){return a[0]}),f=c.map(function(a){return a[1]});c=Math.min.apply(0,e)+d[3];e=Math.max.apply(0,e)-d[1];var g=Math.min.apply(0,f)+d[0];d=Math.max.apply(0,f)-d[2];if(u(c)&&u(g))return{x:c,y:g,width:e-c,height:d-g}}return a.prototype.getField.call(this,b)};b.prototype.getHitZone=function(){var a=
this.chart,b=this.mapView,c=this.options,d=(c.field||{}).coordinates;if(d){d=d[0];if("percent"===c.units){var e="mapBoundingBox"===c.relativeTo&&b.getMapBBox()||n(a.plotBox,{x:0,y:0});d=d.map(function(a){return[y("".concat(a[0],"%"),e.width,e.x),y("".concat(a[1],"%"),e.height,e.y)]})}return{type:"Polygon",coordinates:[d]}}};b.prototype.getProjectedBounds=function(){return C.compositeBounds(this.allBounds)};b.prototype.isInside=function(a){var b=this.geoBoundsProjectedBox,c=this.geoBoundsProjectedPolygon;
return!!(b&&a.x>=b.x1&&a.x<=b.x2&&a.y>=b.y1&&a.y<=b.y2&&c&&G(a,c))};b.prototype.render=function(){var a=this.chart,b=this.mapView,c=this.options,d=c.borderPath||c.field;if(d&&b.group){var e=!0;this.border||(this.border=a.renderer.path().addClass("highcharts-mapview-inset-border").add(b.group),e=!1);a.styledMode||this.border.attr({stroke:c.borderColor,"stroke-width":c.borderWidth});var f=Math.round(this.border.strokeWidth())%2/2,g="mapBoundingBox"===c.relativeTo&&b.getMapBBox()||b.playingField;b=(d.coordinates||
[]).reduce(function(b,d){return d.reduce(function(b,d,e){var h=d[0];d=d[1];"percent"===c.units&&(h=a.plotLeft+y("".concat(h,"%"),g.width,g.x),d=a.plotTop+y("".concat(d,"%"),g.height,g.y));h=Math.floor(h)+f;d=Math.floor(d)+f;b.push(0===e?["M",h,d]:["L",h,d]);return b},b)},[]);this.border[e?"animate":"attr"]({d:b})}};b.prototype.destroy=function(){this.border&&(this.border=this.border.destroy());this.eventsToUnbind.forEach(function(a){return a()})};b.prototype.setUpEvents=function(){};return b}(C);
B(a,"afterInit",function(){this.mapView=new C(this,this.options.mapView)});return C});t(d,"Series/Map/MapSeries.js",[d["Core/Animation/AnimationUtilities.js"],d["Series/ColorMapComposition.js"],d["Series/CenteredUtilities.js"],d["Core/Globals.js"],d["Core/Chart/MapChart.js"],d["Series/Map/MapPoint.js"],d["Maps/MapView.js"],d["Core/Series/Series.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Renderer/SVG/SVGRenderer.js"],d["Core/Utilities.js"]],function(d,c,k,a,b,e,f,t,D,p,v){var g=this&&this.__extends||
function(){function a(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};return a(b,c)}return function(b,c){function d(){this.constructor=b}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),h=d.animObject,G=d.stop;d=a.noop;
var B=b.splitPath;b=D.seriesTypes;var L=b.column,E=b.scatter;b=v.extend;var M=v.find,u=v.fireEvent,x=v.getNestedProperty,m=v.isArray,n=v.defined,r=v.isNumber,y=v.isObject,C=v.merge,O=v.objectEach,H=v.pick,q=v.splat;v=function(b){function c(){var a=null!==b&&b.apply(this,arguments)||this;a.chart=void 0;a.data=void 0;a.group=void 0;a.joinBy=void 0;a.options=void 0;a.points=void 0;a.processedData=[];return a}g(c,b);c.prototype.animate=function(a){var b=this.chart,c=this.group,d=h(this.options.animation);
a?c.attr({translateX:b.plotLeft+b.plotWidth/2,translateY:b.plotTop+b.plotHeight/2,scaleX:.001,scaleY:.001}):c.animate({translateX:b.plotLeft,translateY:b.plotTop,scaleX:1,scaleY:1},d)};c.prototype.clearBounds=function(){this.points.forEach(function(a){delete a.bounds;delete a.insetIndex;delete a.projectedPath});delete this.bounds};c.prototype.doFullTranslate=function(){return!(!this.isDirtyData&&!this.chart.isResizing&&this.hasRendered)};c.prototype.drawMapDataLabels=function(){t.prototype.drawDataLabels.call(this);
this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)};c.prototype.drawPoints=function(){var a=this,b=this,c=this.chart,d=this.group,e=this.transformGroups,f=void 0===e?[]:e,g=c.mapView,m=c.renderer;g&&(this.transformGroups=f,f[0]||(f[0]=m.g().add(d)),g.insets.forEach(function(a,b){f[b+1]||f.push(m.g().add(d))}),this.doFullTranslate()&&(this.points.forEach(function(b){var d=b.graphic,e=b.shapeArgs;b.group=f["number"===typeof b.insetIndex?b.insetIndex+1:0];d&&d.parentGroup!==b.group&&
d.add(b.group);e&&c.hasRendered&&!c.styledMode&&(e.fill=a.pointAttribs(b,b.state).fill)}),L.prototype.drawPoints.apply(this),this.points.forEach(function(d){var e=d.graphic;if(e){var f=e.animate,g="";d.name&&(g+="highcharts-name-"+d.name.replace(/ /g,"-").toLowerCase());d.properties&&d.properties["hc-key"]&&(g+=" highcharts-key-"+d.properties["hc-key"].toString().toLowerCase());g&&e.addClass(g);c.styledMode&&e.css(a.pointAttribs(d,d.selected&&"select"||void 0));e.animate=function(a,d,g){var h=r(a["stroke-width"])&&
!r(e["stroke-width"]),m=r(e["stroke-width"])&&!r(a["stroke-width"]);if(h||m){var n=H(b.getStrokeWidth(b.options),1)/(c.mapView&&c.mapView.getScale()||1);h&&(e["stroke-width"]=n);m&&(a["stroke-width"]=n)}return f.call(e,a,d,m?function(){e.element.removeAttribute("stroke-width");delete e["stroke-width"];g&&g.apply(this,arguments)}:g)}}})),f.forEach(function(d,e){function f(c){(b.points||[]).forEach(function(b){var d=b.graphic,e;d&&d["stroke-width"]&&(e=a.getStrokeWidth(b.options))&&d.attr({"stroke-width":e/
c})})}var n=(0===e?g:g.insets[e-1]).getSVGTransform(),k=H(a.getStrokeWidth(a.options),1),r=n.scaleX,l=0<n.scaleY?1:-1;if(m.globalAnimation&&c.hasRendered&&g.allowTransformAnimation){var A=Number(d.attr("translateX")),F=Number(d.attr("translateY")),z=Number(d.attr("scaleX")),q=function(a,b){a=z+(r-z)*b.pos;d.attr({translateX:A+(n.translateX-A)*b.pos,translateY:F+(n.translateY-F)*b.pos,scaleX:a,scaleY:a*l,"stroke-width":k/a});f(a)};e=C(h(m.globalAnimation));var y=e.step;e.step=function(a){y&&y.apply(this,
arguments);q.apply(this,arguments)};d.attr({animator:0}).animate({animator:1},e,function(){"boolean"!==typeof m.globalAnimation&&m.globalAnimation.complete&&m.globalAnimation.complete({applyDrilldown:!0})})}else G(d),d.attr(C(n,{"stroke-width":k/r})),f(r)}),this.isDrilling||this.drawMapDataLabels())};c.prototype.getProjectedBounds=function(){if(!this.bounds&&this.chart.mapView){var a=this.chart.mapView,b=a.insets,c=a.projection,d=[];(this.points||[]).forEach(function(a){if(a.path||a.geometry){"string"===
typeof a.path?a.path=B(a.path):m(a.path)&&"M"===a.path[0]&&(a.path=p.prototype.pathToSegments(a.path));if(!a.bounds){var e=a.getProjectedBounds(c);if(e){a.labelrank=H(a.labelrank,(e.x2-e.x1)*(e.y2-e.y1));var f=e.midX,g=e.midY;if(b&&r(f)&&r(g)){var h=M(b,function(a){return a.isInside({x:f,y:g})});h&&(delete a.projectedPath,(e=a.getProjectedBounds(h.projection))&&h.allBounds.push(e),a.insetIndex=b.indexOf(h))}a.bounds=e}}a.bounds&&void 0===a.insetIndex&&d.push(a.bounds)}});this.bounds=f.compositeBounds(d)}return this.bounds};
c.prototype.getStrokeWidth=function(a){var b=this.pointAttrToOptions;return a[b&&b["stroke-width"]||"borderWidth"]};c.prototype.hasData=function(){return!!this.processedXData.length};c.prototype.pointAttribs=function(a,b){var c,d=a.series.chart,e=d.mapView;d=d.styledMode?this.colorAttribs(a):L.prototype.pointAttribs.call(this,a,b);var f=this.getStrokeWidth(a.options);if(b){b=C(this.options.states[b],a.options.states&&a.options.states[b]||{});var g=this.getStrokeWidth(b);n(g)&&(f=g);d.stroke=null!==
(c=b.borderColor)&&void 0!==c?c:a.color}f&&e&&(f/=e.getScale());c=this.getStrokeWidth(this.options);d.dashstyle&&e&&r(c)&&(f=c/e.getScale());a.visible||(d.fill=this.options.nullColor);n(f)?d["stroke-width"]=f:delete d["stroke-width"];d["stroke-linecap"]=d["stroke-linejoin"]=this.options.linecap;return d};c.prototype.updateData=function(){return this.processedData?!1:b.prototype.updateData.apply(this,arguments)};c.prototype.setData=function(a,c,d,e){void 0===c&&(c=!0);delete this.bounds;b.prototype.setData.call(this,
a,!1,void 0,e);this.processData();this.generatePoints();c&&this.chart.redraw(d)};c.prototype.processData=function(){var b=this.options,c=b.data,d=this.chart.options.chart,f=this.joinBy,g=b.keys||this.pointArrayMap,h=[],n={},k=this.chart.mapView;k=k&&(y(b.mapData,!0)?k.getGeoMap(b.mapData):k.geoMap);var l=this.chart.mapTransforms;(this.chart.mapTransforms=l=d.mapTransforms||k&&k["hc-transform"]||l)&&O(l,function(a){a.rotation&&(a.cosAngle=Math.cos(a.rotation),a.sinAngle=Math.sin(a.rotation))});if(m(b.mapData))var q=
b.mapData;else k&&"FeatureCollection"===k.type&&(this.mapTitle=k.title,q=a.geojson(k,this.type,this));var p=this.processedData=[];c&&c.forEach(function(a,d){var h=0;if(r(a))p[d]={value:a};else if(m(a)){p[d]={};!b.keys&&a.length>g.length&&"string"===typeof a[0]&&(p[d]["hc-key"]=a[0],++h);for(var n=0;n<g.length;++n,++h)g[n]&&"undefined"!==typeof a[h]&&(0<g[n].indexOf(".")?e.prototype.setNestedProperty(p[d],a[h],g[n]):p[d][g[n]]=a[h])}else p[d]=c[d];f&&"_i"===f[0]&&(p[d]._i=d)});if(q){this.mapData=q;
this.mapMap={};for(l=0;l<q.length;l++)d=q[l],k=d.properties,d._i=l,f[0]&&k&&k[f[0]]&&(d[f[0]]=k[f[0]]),n[d[f[0]]]=d;this.mapMap=n;if(f[1]){var w=f[1];p.forEach(function(a){a=x(w,a);n[a]&&h.push(n[a])})}if(b.allAreas){if(f[1]){var H=f[1];p.forEach(function(a){h.push(x(H,a))})}var u="|"+h.map(function(a){return a&&a[f[0]]}).join("|")+"|";q.forEach(function(a){f[0]&&-1!==u.indexOf("|"+a[f[0]]+"|")||p.push(C(a,{value:null}))})}}this.processedXData=Array(p.length)};c.prototype.setOptions=function(a){a=
t.prototype.setOptions.call(this,a);var b=a.joinBy;null===b&&(b="_i");b=this.joinBy=q(b);b[1]||(b[1]=b[0]);return a};c.prototype.translate=function(){var a=this.doFullTranslate(),b=this.chart.mapView,c=b&&b.projection;!this.chart.hasRendered||!this.isDirtyData&&this.hasRendered||(this.processData(),this.generatePoints(),delete this.bounds,!b||b.userOptions.center||r(b.userOptions.zoom)||b.zoom!==b.minZoom?this.getProjectedBounds():b.fitToBounds(void 0,void 0,!1));if(b){var d=b.getSVGTransform();this.points.forEach(function(f){var g=
r(f.insetIndex)&&b.insets[f.insetIndex].getSVGTransform()||d;g&&f.bounds&&r(f.bounds.midX)&&r(f.bounds.midY)&&(f.plotX=f.bounds.midX*g.scaleX+g.translateX,f.plotY=f.bounds.midY*g.scaleY+g.translateY);a&&(f.shapeType="path",f.shapeArgs={d:e.getProjectedPath(f,c)});f.projectedPath&&!f.projectedPath.length?f.setVisible(!1):f.visible||f.setVisible(!0)})}u(this,"afterTranslate")};c.defaultOptions=C(E.defaultOptions,{affectsMapView:!0,animation:!1,dataLabels:{crop:!1,formatter:function(){var a=this.series.chart.numberFormatter,
b=this.point.value;return r(b)?a(b,-1):""},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},linecap:"round",marker:null,nullColor:"#f7f7f7",stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:"{point.name}: {point.value}<br/>"},turboThreshold:0,allAreas:!0,borderColor:"#e6e6e6",borderWidth:1,joinBy:"hc-key",states:{hover:{halo:void 0,borderColor:"#666666",borderWidth:2},normal:{animation:!0},select:{color:"#cccccc"}},legendSymbol:"rectangle"});return c}(E);b(v.prototype,{type:"map",axisTypes:c.seriesMembers.axisTypes,
colorAttribs:c.seriesMembers.colorAttribs,colorKey:c.seriesMembers.colorKey,directTouch:!0,drawDataLabels:d,drawGraph:d,forceDL:!0,getCenter:k.getCenter,getExtremesFromAll:!0,getSymbol:d,isCartesian:!1,parallelArrays:c.seriesMembers.parallelArrays,pointArrayMap:c.seriesMembers.pointArrayMap,pointClass:e,preserveAspectRatio:!0,searchPoint:d,trackerGroups:c.seriesMembers.trackerGroups,useMapGeometry:!0});c.compose(v);D.registerSeriesType("map",v);"";return v});t(d,"Series/FlowMap/FlowMapSeries.js",
[d["Series/FlowMap/FlowMapPoint.js"],d["Series/Map/MapSeries.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,c,k,a){var b=this&&this.__extends||function(){function a(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};return a(b,c)}return function(b,c){function d(){this.constructor=b}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+
String(c)+" is not a constructor or null");a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),e=this&&this.__spreadArray||function(a,b,c){if(c||2===arguments.length)for(var d=0,e=b.length,f;d<e;d++)!f&&d in b||(f||(f=Array.prototype.slice.call(b,0,d)),f[d]=b[d]);return a.concat(f||Array.prototype.slice.call(b))},f=k.series.prototype.pointClass,h=k.seriesTypes,t=h.column,p=h.mapline,v=a.addEvent,g=a.arrayMax,l=a.arrayMin,G=a.defined;h=a.extend;var B=a.isArray,L=a.merge,
E=a.pick,M=a.relativeLength;a=function(a){function d(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;b.smallestWeight=void 0;b.greatestWeight=void 0;b.centerOfPoints=void 0;return b}b(d,a);d.getLength=function(a,b){return Math.sqrt(a*a+b*b)};d.normalize=function(a,b){var c=this.getLength(a,b);return[a/c,b/c]};d.markerEndPath=function(a,b,c,d){var e=M(d.width||0,this.getLength(b[0]-a[0],b[1]-a[1])),f=d.markerType||"arrow",g=this.normalize(b[0]-a[0],b[1]-
a[1]);d=g[0];g=g[1];var h=[];if("arrow"===f){var k=a[0],m=a[1];h.push(["L",k-d*e,m-g*e]);h.push(["L",c[0],c[1]]);k=b[0];m=b[1];h.push(["L",k+d*e,m+g*e])}if("mushroom"===f){f=a[0];a=a[1];k=b[0];b=b[1];var n=(k-f)/2+f;m=(b-a)/2+a;n=2*(c[0]-n)+n;c=2*(c[1]-m)+m;h.push(["L",f-d*e,a-g*e]);h.push(["Q",n,c,k+d*e,b+g*e])}return h};d.prototype.animate=function(a){var b=this.points;a||b.forEach(function(a){if(a.shapeArgs&&B(a.shapeArgs.d)&&a.shapeArgs.d.length){var b=a.shapeArgs.d,c=b[0][1],d=b[0][2];if(c&&
d){for(var f=[],g=0;g<b.length;g++){f.push(e([],b[g],!0));for(var h=1;h<b[g].length;h++)f[g][h]=h%2?c:d}a.graphic&&(a.graphic.attr({d:f}),a.graphic.animate({d:b}))}}})};d.prototype.getLinkWidth=function(a){var b=this.options.width,c=a.options.weight||this.options.weight;a.options.weight=c;if(b&&!c)return b;a=this.smallestWeight;b=this.greatestWeight;if(!G(c)||!a||!b)return 0;var d=this.options.minWidth;return(c-a)*(this.options.maxWidth-d)/(b-a||1)+d};d.prototype.autoCurve=function(a,b,c,d,e,f){var g=
c-a,h=d-b;a=(c-a)/2+a-e;b=(d-b)/2+b-f;g=Math.atan2(g*b-h*a,g*a+h*b);g=180*g/Math.PI;0>g&&(g=360+g);g=g*Math.PI/180;return.7*-Math.sin(g)};d.prototype.pointAttribs=function(a,b){b=c.prototype.pointAttribs.call(this,a,b);b.fill=E(a.options.fillColor,a.options.color,"none"===this.options.fillColor?null:this.options.fillColor,this.color);b["fill-opacity"]=E(a.options.fillOpacity,this.options.fillOpacity);b["stroke-width"]=E(a.options.lineWidth,this.options.lineWidth,1);a.options.opacity&&(b.opacity=a.options.opacity);
return b};d.prototype.translate=function(){var a=this;!this.chart.hasRendered||!this.isDirtyData&&this.hasRendered||(this.processData(),this.generatePoints());var b=[],c=0,d=0;this.points.forEach(function(e){function g(a){return B(a)?{lon:a[0],lat:a[1]}:a}function h(a){a=l.get(a);if(a instanceof f&&a.plotX&&a.plotY)return v(a,"update",k),{x:a.plotX,y:a.plotY}}function k(){e.series.isDirty=!0}var l=a.chart,m=l.mapView,n=e.options,p,r;"string"===typeof n.from?p=h(n.from):"object"===typeof n.from&&m&&
(p=m.lonLatToPixels(g(n.from)));"string"===typeof n.to?r=h(n.to):"object"===typeof n.to&&m&&(r=m.lonLatToPixels(g(n.to)));e.fromPos=p;e.toPos=r;p&&r&&(c+=(p.x+r.x)/2,d+=(p.y+r.y)/2);E(e.options.weight,a.options.weight)&&b.push(E(e.options.weight,a.options.weight))});this.smallestWeight=l(b);this.greatestWeight=g(b);this.centerOfPoints={x:c/this.points.length,y:d/this.points.length};this.points.forEach(function(b){a.getLinkWidth(b)?(b.fromPos&&(b.plotX=b.fromPos.x,b.plotY=b.fromPos.y),b.shapeType=
"path",b.shapeArgs=a.getPointShapeArgs(b),b.color=E(b.options.color,b.series.color)):b.shapeArgs={d:[]}})};d.prototype.getPointShapeArgs=function(a){var b,c=a.fromPos,f=a.toPos;if(!c||!f)return{};var g=this.getLinkWidth(a)/2,h=a.options,k=L(this.options.markerEnd,h.markerEnd),l=E(h.growTowards,this.options.growTowards),m=c.x||0,p=c.y||0;c=f.x||0;var t=f.y||0;h=E(h.curveFactor,this.options.curveFactor);var v=k&&k.enabled&&k.height||0;G(h)||(h=this.autoCurve(m,p,c,t,this.centerOfPoints.x,this.centerOfPoints.y));
if(v){v=M(v,4*g);var u=.5*(c-m);var x=.5*(t-p);var z=m+u;x=d.normalize(z+x*h-c,p+x+-u*h-t);z=x[1];c+=x[0]*v;t+=z*v}u=.5*(c-m);var I=.5*(t-p);var B=m+u,D=p+I;z=u;u=I;I=-z;x=d.normalize(u,I);v=x[0];x=x[1];z=1+.25*Math.sqrt(h*h);v*=g*z;x*=g*z;u=B+u*h;h=D+I*h;z=d.normalize(u-m,h-p);I=z[0];B=z[1];z=I;I=B*g;B=-z*g;z=d.normalize(u-c,h-t);D=z[0];var N=z[1];z=D;D=-N*g;N=z*g;l&&(I/=g,B/=g,v/=4,x/=4);g={d:[["M",m-I,p-B],["Q",u-v,h-x,c-D,t-N],["L",c+D,t+N],["Q",u+v,h+x,m+I,p+B],["Z"]]};k&&k.enabled&&g.d&&(f=
d.markerEndPath([c-D,t-N],[c+D,t+N],[f.x,f.y],k),(b=g.d).splice.apply(b,e([2,0],f,!1)));k=a.options.from;f=a.options.to;b=k.lat;k=k.lon;l=f.lat;f=f.lon;b&&k&&(a.options.from="".concat(+b,", ").concat(+k));l&&f&&(a.options.to="".concat(+l,", ").concat(+f));return g};d.defaultOptions=L(p.defaultOptions,{animation:!0,dataLabels:{enabled:!1},fillOpacity:.5,markerEnd:{enabled:!0,height:"40%",width:"40%",markerType:"arrow"},width:1,maxWidth:25,minWidth:5,lineWidth:void 0,tooltip:{headerFormat:'<span style="font-size: 0.8em">{series.name}</span><br/>',
pointFormat:"{point.options.from} \u2192 {point.options.to}: <b>{point.options.weight}</b>"}});return d}(p);h(a.prototype,{pointClass:d,pointArrayMap:["from","to","weight"],drawPoints:t.prototype.drawPoints,useMapGeometry:!0});k.registerSeriesType("flowmap",a);"";return a});t(d,"masters/modules/flowmap.src.js",[],function(){})});//# sourceMappingURL=flowmap.js.map