/*
 Highmaps JS v11.1.0 (2023-08-20)

 (c) 2009-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/heatmap",["highcharts"],function(x){b(x);b.Highcharts=x;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function x(b,f,D,t){b.hasOwnProperty(f)||(b[f]=t.apply(null,D),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:f,module:b[f]}})))}b=b?b._modules:
{};x(b,"Core/Axis/Color/ColorAxisComposition.js",[b["Core/Color/Color.js"],b["Core/Utilities.js"]],function(b,f){var v=b.parse,t=f.addEvent,y=f.extend,r=f.merge,p=f.pick,J=f.splat,u;(function(h){function b(){var l=this,c=this.options;this.colorAxis=[];c.colorAxis&&(c.colorAxis=J(c.colorAxis),c.colorAxis.forEach(function(c){new a(l,c)}))}function u(a){function c(c){c=a.allItems.indexOf(c);-1!==c&&(l.destroyItem(a.allItems[c]),a.allItems.splice(c,1))}var l=this,d=[],e,g;(this.chart.colorAxis||[]).forEach(function(a){(e=
a.options)&&e.showInLegend&&(e.dataClasses&&e.visible?d=d.concat(a.getDataClassLegendSymbols()):e.visible&&d.push(a),a.series.forEach(function(a){if(!a.options.showInLegend||e.dataClasses)"point"===a.options.legendType?a.points.forEach(function(a){c(a)}):c(a)}))});for(g=d.length;g--;)a.allItems.unshift(d[g])}function C(a){a.visible&&a.item.legendColor&&a.item.legendItem.symbol.attr({fill:a.item.legendColor})}function q(){var a=this.chart.colorAxis;a&&a.forEach(function(a,c,d){a.update({},d)})}function w(){(this.chart.colorAxis&&
this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()}function K(){var a=this.axisTypes;a?-1===a.indexOf("colorAxis")&&a.push("colorAxis"):this.axisTypes=["colorAxis"]}function m(a){var c=this,d=a?"show":"hide";c.visible=c.options.visible=!!a;["graphic","dataLabel"].forEach(function(a){if(c[a])c[a][d]()});this.series.buildKDTree()}function d(){var a=this,c=this.options.nullColor,d=this.colorAxis,e=this.colorKey;(this.data.length?this.data:this.points).forEach(function(l){var g=l.getNestedProperty(e);
(g=l.options.color||(l.isNull||null===l.value?c:d&&"undefined"!==typeof g?d.toColor(g,l):l.color||a.color))&&l.color!==g&&(l.color=g,"point"===a.options.legendType&&l.legendItem&&l.legendItem.label&&a.chart.legend.colorizeItem(l,l.visible))})}function c(c){var d=c.prototype.createAxis;c.prototype.createAxis=function(c,e){if("colorAxis"!==c)return d.apply(this,arguments);var l=new a(this,r(e.axis,{index:this[c].length,isX:!1}));this.isDirtyLegend=!0;this.axes.forEach(function(a){a.series=[]});this.series.forEach(function(a){a.bindAxes();
a.isDirtyData=!0});p(e.redraw,!0)&&this.redraw(e.animation);return l}}function g(){this.elem.attr("fill",v(this.start).tweenTo(v(this.end),this.pos),void 0,!0)}function e(){this.elem.attr("stroke",v(this.start).tweenTo(v(this.end),this.pos),void 0,!0)}var k=[],a;h.compose=function(l,n,h,z,G){a||(a=l);f.pushUnique(k,n)&&(l=n.prototype,l.collectionsWithUpdate.push("colorAxis"),l.collectionsWithInit.colorAxis=[l.addColorAxis],t(n,"afterGetAxes",b),c(n));f.pushUnique(k,h)&&(n=h.prototype,n.fillSetter=
g,n.strokeSetter=e);f.pushUnique(k,z)&&(t(z,"afterGetAllItems",u),t(z,"afterColorizeItem",C),t(z,"afterUpdate",q));f.pushUnique(k,G)&&(y(G.prototype,{optionalAxis:"colorAxis",translateColors:d}),y(G.prototype.pointClass.prototype,{setVisible:m}),t(G,"afterTranslate",w,{order:1}),t(G,"bindAxes",K))};h.pointSetVisible=m})(u||(u={}));return u});x(b,"Core/Axis/Color/ColorAxisDefaults.js",[],function(){return{lineWidth:0,minPadding:0,maxPadding:0,gridLineColor:"#ffffff",gridLineWidth:1,tickPixelInterval:72,
startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:"#999999"},labels:{distance:8,overflow:"justify",rotation:0},minColor:"#e6e9ff",maxColor:"#0022ff",tickLength:5,showInLegend:!0}});x(b,"Core/Axis/Color/ColorAxis.js",[b["Core/Axis/Axis.js"],b["Core/Color/Color.js"],b["Core/Axis/Color/ColorAxisComposition.js"],b["Core/Axis/Color/ColorAxisDefaults.js"],b["Core/Legend/LegendSymbol.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,f,D,t,y,r,p){var v=
this&&this.__extends||function(){function h(m,d){h=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,d){c.__proto__=d}||function(c,d){for(var e in d)Object.prototype.hasOwnProperty.call(d,e)&&(c[e]=d[e])};return h(m,d)}return function(m,d){function c(){this.constructor=m}if("function"!==typeof d&&null!==d)throw new TypeError("Class extends value "+String(d)+" is not a constructor or null");h(m,d);m.prototype=null===d?Object.create(d):(c.prototype=d.prototype,new c)}}(),u=f.parse,h=
r.series,z=p.extend,F=p.isArray,C=p.isNumber,q=p.merge,w=p.pick;f=function(b){function m(d,c){var g=b.call(this,d,c)||this;g.beforePadding=!1;g.chart=void 0;g.coll="colorAxis";g.dataClasses=void 0;g.options=void 0;g.stops=void 0;g.visible=!0;g.init(d,c);return g}v(m,b);m.compose=function(d,c,g,e){D.compose(m,d,c,g,e)};m.prototype.init=function(d,c){var g=d.options.legend||{},e=c.layout?"vertical"!==c.layout:"vertical"!==g.layout,k=c.visible;g=q(m.defaultColorAxisOptions,c,{showEmpty:!1,title:null,
visible:g.enabled&&!1!==k});this.side=c.side||e?2:1;this.reversed=c.reversed||!e;this.opposite=!e;b.prototype.init.call(this,d,g,"colorAxis");this.userOptions=c;F(d.userOptions.colorAxis)&&(d.userOptions.colorAxis[this.index]=c);c.dataClasses&&this.initDataClasses(c);this.initStops();this.horiz=e;this.zoomEnabled=!1};m.prototype.initDataClasses=function(d){var c=this.chart,g=this.legendItem=this.legendItem||{},e=d.dataClasses.length,k=this.options,a,l=0,n=c.options.chart.colorCount;this.dataClasses=
a=[];g.labels=[];(d.dataClasses||[]).forEach(function(d,g){d=q(d);a.push(d);if(c.styledMode||!d.color)"category"===k.dataClassColor?(c.styledMode||(g=c.options.colors,n=g.length,d.color=g[l]),d.colorIndex=l,l++,l===n&&(l=0)):d.color=u(k.minColor).tweenTo(u(k.maxColor),2>e?.5:g/(e-1))})};m.prototype.hasData=function(){return!!(this.tickPositions||[]).length};m.prototype.setTickPositions=function(){if(!this.dataClasses)return b.prototype.setTickPositions.call(this)};m.prototype.initStops=function(){this.stops=
this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(d){d.color=u(d[1])})};m.prototype.setOptions=function(d){b.prototype.setOptions.call(this,d);this.options.crosshair=this.options.marker};m.prototype.setAxisSize=function(){var d=this.legendItem&&this.legendItem.symbol,c=this.chart,g=c.options.legend||{},e,k;d?(this.left=g=d.attr("x"),this.top=e=d.attr("y"),this.width=k=d.attr("width"),this.height=d=d.attr("height"),this.right=c.chartWidth-g-k,this.bottom=
c.chartHeight-e-d,this.len=this.horiz?k:d,this.pos=this.horiz?g:e):this.len=(this.horiz?g.symbolWidth:g.symbolHeight)||m.defaultLegendLength};m.prototype.normalizedValue=function(d){this.logarithmic&&(d=this.logarithmic.log2lin(d));return 1-(this.max-d)/(this.max-this.min||1)};m.prototype.toColor=function(d,c){var g=this.dataClasses,e=this.stops,k;if(g)for(k=g.length;k--;){var a=g[k];var l=a.from;e=a.to;if(("undefined"===typeof l||d>=l)&&("undefined"===typeof e||d<=e)){var n=a.color;c&&(c.dataClass=
k,c.colorIndex=a.colorIndex);break}}else{d=this.normalizedValue(d);for(k=e.length;k--&&!(d>e[k][0]););l=e[k]||e[k+1];e=e[k+1]||l;d=1-(e[0]-d)/(e[0]-l[0]||1);n=l.color.tweenTo(e.color,d)}return n};m.prototype.getOffset=function(){var d=this.legendItem&&this.legendItem.group,c=this.chart.axisOffset[this.side];if(d){this.axisParent=d;b.prototype.getOffset.call(this);var g=this.chart.legend;g.allItems.forEach(function(c){c instanceof m&&c.drawLegendSymbol(g,c)});g.render();this.chart.getMargins(!0);this.added||
(this.added=!0,this.labelLeft=0,this.labelRight=this.width);this.chart.axisOffset[this.side]=c}};m.prototype.setLegendColor=function(){var d=this.reversed,c=d?1:0;d=d?0:1;c=this.horiz?[c,0,d,0]:[0,d,0,c];this.legendColor={linearGradient:{x1:c[0],y1:c[1],x2:c[2],y2:c[3]},stops:this.stops}};m.prototype.drawLegendSymbol=function(d,c){var g;c=c.legendItem||{};var e=d.padding,k=d.options,a=this.options.labels,l=w(k.itemDistance,10),n=this.horiz,b=w(k.symbolWidth,n?m.defaultLegendLength:12),h=w(k.symbolHeight,
n?12:m.defaultLegendLength),G=w(k.labelPadding,n?16:30);this.setLegendColor();c.symbol||(c.symbol=this.chart.renderer.symbol("roundedRect",0,d.baseline-11,b,h,{r:null!==(g=k.symbolRadius)&&void 0!==g?g:3}).attr({zIndex:1}).add(c.group));c.labelWidth=b+e+(n?l:w(a.x,a.distance)+this.maxLabelLength);c.labelHeight=h+e+(n?G:0)};m.prototype.setState=function(d){this.series.forEach(function(c){c.setState(d)})};m.prototype.setVisible=function(){};m.prototype.getSeriesExtremes=function(){var d=this.series,
c=d.length,g;this.dataMin=Infinity;for(this.dataMax=-Infinity;c--;){var e=d[c];var k=e.colorKey=w(e.options.colorKey,e.colorKey,e.pointValKey,e.zoneAxis,"y");var a=e.pointArrayMap;var l=e[k+"Min"]&&e[k+"Max"];if(e[k+"Data"])var n=e[k+"Data"];else if(a){n=[];a=a.indexOf(k);var b=e.yData;if(0<=a&&b)for(g=0;g<b.length;g++)n.push(w(b[g][a],b[g]))}else n=e.yData;l?(e.minColorValue=e[k+"Min"],e.maxColorValue=e[k+"Max"]):(n=h.prototype.getExtremes.call(e,n),e.minColorValue=n.dataMin,e.maxColorValue=n.dataMax);
"undefined"!==typeof e.minColorValue&&(this.dataMin=Math.min(this.dataMin,e.minColorValue),this.dataMax=Math.max(this.dataMax,e.maxColorValue));l||h.prototype.applyExtremes.call(e)}};m.prototype.drawCrosshair=function(d,c){var g=this.legendItem||{},e=c&&c.plotX,k=c&&c.plotY,a=this.pos,l=this.len;if(c){var n=this.toPixels(c.getNestedProperty(c.series.colorKey));n<a?n=a-2:n>a+l&&(n=a+l+2);c.plotX=n;c.plotY=this.len-n;b.prototype.drawCrosshair.call(this,d,c);c.plotX=e;c.plotY=k;this.cross&&!this.cross.addedToColorAxis&&
g.group&&(this.cross.addClass("highcharts-coloraxis-marker").add(g.group),this.cross.addedToColorAxis=!0,this.chart.styledMode||"object"!==typeof this.crosshair||this.cross.attr({fill:this.crosshair.color}))}};m.prototype.getPlotLinePath=function(d){var c=this.left,g=d.translatedValue,e=this.top;return C(g)?this.horiz?[["M",g-4,e-6],["L",g+4,e-6],["L",g,e],["Z"]]:[["M",c,g],["L",c-6,g+6],["L",c-6,g-6],["Z"]]:b.prototype.getPlotLinePath.call(this,d)};m.prototype.update=function(d,c){var g=this.chart.legend;
this.series.forEach(function(c){c.isDirtyData=!0});(d.dataClasses&&g.allItems||this.dataClasses)&&this.destroyItems();b.prototype.update.call(this,d,c);this.legendItem&&this.legendItem.label&&(this.setLegendColor(),g.colorizeItem(this,!0))};m.prototype.destroyItems=function(){var d=this.chart,c=this.legendItem||{};if(c.label)d.legend.destroyItem(this);else if(c.labels){var g=0;for(c=c.labels;g<c.length;g++)d.legend.destroyItem(c[g])}d.isDirtyLegend=!0};m.prototype.destroy=function(){this.chart.isDirtyLegend=
!0;this.destroyItems();b.prototype.destroy.apply(this,[].slice.call(arguments))};m.prototype.remove=function(d){this.destroyItems();b.prototype.remove.call(this,d)};m.prototype.getDataClassLegendSymbols=function(){function d(a){return c.series.reduce(function(c,d){c.push.apply(c,d.points.filter(function(c){return c.dataClass===a}));return c},[])}var c=this,g=c.chart,e=c.legendItem&&c.legendItem.labels||[],k=g.options.legend,a=w(k.valueDecimals,-1),l=w(k.valueSuffix,""),n;e.length||c.dataClasses.forEach(function(k,
b){var h=k.from,m=k.to,f=g.numberFormatter,u=!0;n="";"undefined"===typeof h?n="< ":"undefined"===typeof m&&(n="> ");"undefined"!==typeof h&&(n+=f(h,a)+l);"undefined"!==typeof h&&"undefined"!==typeof m&&(n+=" - ");"undefined"!==typeof m&&(n+=f(m,a)+l);e.push(z({chart:g,name:n,options:{},drawLegendSymbol:y.rectangle,visible:!0,isDataClass:!0,setState:function(a){for(var c=0,l=d(b);c<l.length;c++)l[c].setState(a)},setVisible:function(){this.visible=u=c.visible=!u;for(var a=0,l=d(b);a<l.length;a++)l[a].setVisible(u);
g.legend.colorizeItem(this,u)}},k))});return e};m.defaultColorAxisOptions=t;m.defaultLegendLength=200;m.keepProps=["legendItem"];return m}(b);Array.prototype.push.apply(b.keepProps,f.keepProps);"";return f});x(b,"Series/ColorMapComposition.js",[b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,f){var v=b.seriesTypes.column.prototype,t=f.addEvent,y=f.defined,r;(function(b){function p(b){this.moveToTopOnHover&&this.graphic&&this.graphic.attr({zIndex:b&&"hover"===b.state?1:0})}var u=
[];b.pointMembers={dataLabelOnNull:!0,moveToTopOnHover:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value&&(void 0===this.value||!isNaN(this.value))}};b.seriesMembers={colorKey:"value",axisTypes:["xAxis","yAxis","colorAxis"],parallelArrays:["x","y","value"],pointArrayMap:["value"],trackerGroups:["group","markerGroup","dataLabelsGroup"],colorAttribs:function(b){var h={};!y(b.color)||b.state&&"normal"!==b.state||(h[this.colorProp||"fill"]=b.color);return h},
pointAttribs:v.pointAttribs};b.compose=function(b){var h=b.prototype.pointClass;f.pushUnique(u,h)&&t(h,"afterSetState",p);return b}})(r||(r={}));return r});x(b,"Series/Heatmap/HeatmapPoint.js",[b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,f){var v=this&&this.__extends||function(){function b(f,h){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,h){b.__proto__=h}||function(b,h){for(var f in h)Object.prototype.hasOwnProperty.call(h,f)&&(b[f]=h[f])};return b(f,
h)}return function(f,h){function z(){this.constructor=f}if("function"!==typeof h&&null!==h)throw new TypeError("Class extends value "+String(h)+" is not a constructor or null");b(f,h);f.prototype=null===h?Object.create(h):(z.prototype=h.prototype,new z)}}(),t=f.clamp,y=f.defined,r=f.extend,p=f.pick;b=function(b){function f(){var h=null!==b&&b.apply(this,arguments)||this;h.options=void 0;h.series=void 0;h.value=void 0;h.x=void 0;h.y=void 0;return h}v(f,b);f.prototype.applyOptions=function(h,f){(this.isNull||
null===this.value)&&delete this.color;b.prototype.applyOptions.call(this,h,f);this.formatPrefix=this.isNull||null===this.value?"null":"point";return this};f.prototype.getCellAttributes=function(){var b=this.series,f=b.options,u=(f.colsize||1)/2,v=(f.rowsize||1)/2,q=b.xAxis,w=b.yAxis,r=this.options.marker||b.options.marker;b=b.pointPlacementToXValue();var m=p(this.pointPadding,f.pointPadding,0),d={x1:t(Math.round(q.len-q.translate(this.x-u,!1,!0,!1,!0,-b)),-q.len,2*q.len),x2:t(Math.round(q.len-q.translate(this.x+
u,!1,!0,!1,!0,-b)),-q.len,2*q.len),y1:t(Math.round(w.translate(this.y-v,!1,!0,!1,!0)),-w.len,2*w.len),y2:t(Math.round(w.translate(this.y+v,!1,!0,!1,!0)),-w.len,2*w.len)};[["width","x"],["height","y"]].forEach(function(c){var b=c[0];c=c[1];var e=c+"1",k=c+"2",a=Math.abs(d[e]-d[k]),l=r&&r.lineWidth||0,n=Math.abs(d[e]+d[k])/2;b=r&&r[b];y(b)&&b<a&&(b=b/2+l/2,d[e]=n-b,d[k]=n+b);if(m){if("x"===c&&q.reversed||"y"===c&&!w.reversed)e=k,k=c+"1";d[e]+=m;d[k]-=m}});return d};f.prototype.haloPath=function(b){if(!b)return[];
var f=this.shapeArgs||{},h=f.x;h=void 0===h?0:h;var p=f.y;p=void 0===p?0:p;var q=f.width;q=void 0===q?0:q;f=f.height;f=void 0===f?0:f;return[["M",h-b,p-b],["L",h-b,p+f+b],["L",h+q+b,p+f+b],["L",h+q+b,p-b],["Z"]]};f.prototype.isValid=function(){return Infinity!==this.value&&-Infinity!==this.value};return f}(b.seriesTypes.scatter.prototype.pointClass);r(b.prototype,{dataLabelOnNull:!0,moveToTopOnHover:!0,ttBelow:!1});return b});x(b,"Series/Heatmap/HeatmapSeries.js",[b["Core/Color/Color.js"],b["Series/ColorMapComposition.js"],
b["Core/Globals.js"],b["Series/Heatmap/HeatmapPoint.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Renderer/SVG/SVGRenderer.js"],b["Core/Utilities.js"]],function(b,f,x,t,y,r,p){var v=this&&this.__extends||function(){function c(b,a){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)Object.prototype.hasOwnProperty.call(c,b)&&(a[b]=c[b])};return c(b,a)}return function(b,a){function d(){this.constructor=b}if("function"!==typeof a&&null!==
a)throw new TypeError("Class extends value "+String(a)+" is not a constructor or null");c(b,a);b.prototype=null===a?Object.create(a):(d.prototype=a.prototype,new d)}}(),u=this&&this.__assign||function(){u=Object.assign||function(c){for(var b,a=1,d=arguments.length;a<d;a++){b=arguments[a];for(var e in b)Object.prototype.hasOwnProperty.call(b,e)&&(c[e]=b[e])}return c};return u.apply(this,arguments)},h=x.doc,z=y.series,F=y.seriesTypes;x=F.column;var C=F.scatter,q=r.prototype.symbols,w=p.clamp;r=p.extend;
var D=p.fireEvent,m=p.isNumber,d=p.merge,c=p.pick,g=p.defined;p=function(e){function f(){var a=null!==e&&e.apply(this,arguments)||this;a.canvas=void 0;a.colorAxis=void 0;a.context=void 0;a.data=void 0;a.options=void 0;a.points=void 0;a.valueMax=NaN;a.valueMin=NaN;return a}v(f,e);f.prototype.drawPoints=function(){var a=this,b=a.options,d=b.marker||{};if(b.interpolation){d=a.image;var e=a.chart,f=a.xAxis,h=a.yAxis,m=a.points,k=m.length-1,p=f.len,q=f.reversed,v=h.len,t=h.reversed,r=f.getExtremes(),x=
r.min,y=r.max;h=h.getExtremes();var C=h.min,D=h.max;b=[c(b.colsize,1),c(b.rowsize,1)];h=b[0];r=b[1];var H=e.inverted,A=h/2;b=f.userOptions.minPadding;var B=g(b)&&!(0<b);b=H||B;A=B&&A||0;A=[x-A,y+2*A,x+h].map(function(b){return w(Math.round(f.len-f.translate(b,!1,!0,!1,!0,-a.pointPlacementToXValue())),-f.len,2*f.len)});B=A[0];var E=A[1];E=q?[E,B]:[B,E];B=E[0];E=E[1];A=p/A[2]/2/2/2;p=H?{width:p,height:v,x:0,y:0}:{x:B-A,width:E-A,height:v,y:0};if(!d||a.isDirtyData){var F=e.colorAxis&&e.colorAxis[0];
v=a.getContext();if((H=a.canvas)&&v&&F){var I=H.width=~~((y-x)/h)+1;h=H.height=~~((D-C)/r)+1;r=I*h;A=new Uint8ClampedArray(4*r);var L=I-(b&&1||0),M=h-1;b=function(a){a=F.toColor(a.value||0,c(a)).split(")")[0].split("(")[1].split(",").map(function(a){return c(parseFloat(a),parseInt(a,10))});a[3]=255*c(a[3],1);return a};var J=q?function(a){return L-a}:function(a){return a},K=t?function(a){return M-a}:function(a){return a};q=function(a,b){return Math.ceil(I*K(~~((M-0)/(D-C)*(D-b-C)))+J(~~((L-0)/(y-x)*
(a-x))))};a.buildKDTree();a.directTouch=!1;for(t=0;t<r;t++)B=m[~~((k-0)/(A.length-4)*t*4)],E=new Uint8ClampedArray(b(B)),A.set(E,4*q(B.x,B.y));v.putImageData(new ImageData(A,I,h),0,0);d?d.attr(u(u({},p),{href:H.toDataURL()})):a.image=e.renderer.image(H.toDataURL()).attr(p).add(a.group)}}else d.width===p.width&&d.height===p.height||d.attr(p)}else if(d.enabled||a._hasPointMarkers)z.prototype.drawPoints.call(a),a.points.forEach(function(b){b.graphic&&(b.graphic[a.chart.styledMode?"css":"animate"](a.colorAttribs(b)),
null===b.value&&b.graphic.addClass("highcharts-null-point"))})};f.prototype.getContext=function(){var a=this.canvas,b=this.context;if(a&&b)b.clearRect(0,0,a.width,a.height);else return this.canvas=h.createElement("canvas"),this.context=this.canvas.getContext("2d")||void 0;return b};f.prototype.getExtremes=function(){var a=z.prototype.getExtremes.call(this,this.valueData),b=a.dataMin;a=a.dataMax;m(b)&&(this.valueMin=b);m(a)&&(this.valueMax=a);return z.prototype.getExtremes.call(this)};f.prototype.getValidPoints=
function(a,b){return z.prototype.getValidPoints.call(this,a,b,!0)};f.prototype.hasData=function(){return!!this.processedXData.length};f.prototype.init=function(){e.prototype.init.apply(this,arguments);var a=this.options;a.pointRange=c(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=a.rowsize||1;q.ellipse=q.circle;a.marker&&m(a.borderRadius)&&(a.marker.r=a.borderRadius)};f.prototype.markerAttribs=function(a,b){var c=a.shapeArgs||{};if(a.hasImage)return{x:a.plotX,y:a.plotY};if(b&&"normal"!==b){var d=
a.options.marker||{};a=this.options.marker||{};a=a.states&&a.states[b]||{};d=d.states&&d.states[b]||{};b=(d.width||a.width||c.width||0)+(d.widthPlus||a.widthPlus||0);a=(d.height||a.height||c.height||0)+(d.heightPlus||a.heightPlus||0);return{x:(c.x||0)+((c.width||0)-b)/2,y:(c.y||0)+((c.height||0)-a)/2,width:b,height:a}}return c};f.prototype.pointAttribs=function(a,c){var e=z.prototype.pointAttribs.call(this,a,c),f=this.options||{},g=this.chart.options.plotOptions||{},h=g.series||{},l=g.heatmap||{};
g=a&&a.options.borderColor||f.borderColor||l.borderColor||h.borderColor;h=a&&a.options.borderWidth||f.borderWidth||l.borderWidth||h.borderWidth||e["stroke-width"];e.stroke=a&&a.marker&&a.marker.lineColor||f.marker&&f.marker.lineColor||g||this.color;e["stroke-width"]=h;c&&"normal"!==c&&(a=d(f.states&&f.states[c],f.marker&&f.marker.states&&f.marker.states[c],a&&a.options.states&&a.options.states[c]||{}),e.fill=a.color||b.parse(e.fill).brighten(a.brightness||0).get(),e.stroke=a.lineColor||e.stroke);
return e};f.prototype.translate=function(){var a=this.options,b=a.borderRadius,c=(a=a.marker)&&a.symbol||"rect",e=q[c]?c:"rect",f=-1!==["circle","square"].indexOf(e);this.generatePoints();this.points.forEach(function(a){var g=a.getCellAttributes(),h=Math.min(g.x1,g.x2),l=Math.min(g.y1,g.y2),k=Math.max(Math.abs(g.x2-g.x1),0),n=Math.max(Math.abs(g.y2-g.y1),0);a.hasImage=0===(a.marker&&a.marker.symbol||c||"").indexOf("url");f&&(l=Math.abs(k-n),h=Math.min(g.x1,g.x2)+(k<n?0:l/2),l=Math.min(g.y1,g.y2)+
(k<n?l/2:0),k=n=Math.min(k,n));a.hasImage&&(a.marker={width:k,height:n});a.plotX=a.clientX=(g.x1+g.x2)/2;a.plotY=(g.y1+g.y2)/2;a.shapeType="path";a.shapeArgs=d(!0,{x:h,y:l,width:k,height:n},{d:q[e](h,l,k,n,{r:m(b)?b:0})})});D(this,"afterTranslate")};f.defaultOptions=d(C.defaultOptions,{animation:!1,borderRadius:0,borderWidth:0,interpolation:!1,nullColor:"#f7f7f7",dataLabels:{formatter:function(){var a=this.series.chart.numberFormatter,b=this.point.value;return m(b)?a(b,-1):""},inside:!0,verticalAlign:"middle",
crop:!1,overflow:"allow",padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},select:{}}},clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,brightness:.2}},legendSymbol:"rectangle"});return f}(C);r(p.prototype,{axisTypes:f.seriesMembers.axisTypes,colorKey:f.seriesMembers.colorKey,directTouch:!0,getExtremesFromAll:!0,parallelArrays:f.seriesMembers.parallelArrays,pointArrayMap:["y","value"],pointClass:t,
specialGroup:"group",trackerGroups:f.seriesMembers.trackerGroups,alignDataLabel:x.prototype.alignDataLabel,colorAttribs:f.seriesMembers.colorAttribs,getSymbol:z.prototype.getSymbol});f.compose(p);y.registerSeriesType("heatmap",p);"";"";return p});x(b,"masters/modules/heatmap.src.js",[b["Core/Globals.js"],b["Core/Axis/Color/ColorAxis.js"]],function(b,f){b.ColorAxis=f;f.compose(b.Chart,b.Fx,b.Legend,b.Series)})});//# sourceMappingURL=heatmap.js.map