/*
 Highmaps JS v11.1.0 (2023-08-20)

 Highmaps as a plugin for Highcharts or Highcharts Stock.

 (c) 2011-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/map",["highcharts"],function(x){b(x);b.Highcharts=x;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function x(b,f,q,m){b.hasOwnProperty(f)||(b[f]=m.apply(null,q),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:f,module:b[f]}})))}b=b?b._modules:
{};x(b,"Core/Axis/Color/ColorAxisComposition.js",[b["Core/Color/Color.js"],b["Core/Utilities.js"]],function(b,f){var q=b.parse,m=f.addEvent,p=f.extend,l=f.merge,e=f.pick,y=f.splat,w;(function(h){function r(){var n=this,a=this.options;this.colorAxis=[];a.colorAxis&&(a.colorAxis=y(a.colorAxis),a.colorAxis.forEach(function(a){new t(n,a)}))}function c(a){function n(v){v=a.allItems.indexOf(v);-1!==v&&(d.destroyItem(a.allItems[v]),a.allItems.splice(v,1))}var d=this,c=[],v,g;(this.chart.colorAxis||[]).forEach(function(a){(v=
a.options)&&v.showInLegend&&(v.dataClasses&&v.visible?c=c.concat(a.getDataClassLegendSymbols()):v.visible&&c.push(a),a.series.forEach(function(a){if(!a.options.showInLegend||v.dataClasses)"point"===a.options.legendType?a.points.forEach(function(v){n(v)}):n(a)}))});for(g=c.length;g--;)a.allItems.unshift(c[g])}function a(a){a.visible&&a.item.legendColor&&a.item.legendItem.symbol.attr({fill:a.item.legendColor})}function d(){var a=this.chart.colorAxis;a&&a.forEach(function(a,n,d){a.update({},d)})}function u(){(this.chart.colorAxis&&
this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()}function k(){var a=this.axisTypes;a?-1===a.indexOf("colorAxis")&&a.push("colorAxis"):this.axisTypes=["colorAxis"]}function g(a){var n=this,d=a?"show":"hide";n.visible=n.options.visible=!!a;["graphic","dataLabel"].forEach(function(a){if(n[a])n[a][d]()});this.series.buildKDTree()}function C(){var a=this,n=this.options.nullColor,d=this.colorAxis,c=this.colorKey;(this.data.length?this.data:this.points).forEach(function(v){var g=v.getNestedProperty(c);
(g=v.options.color||(v.isNull||null===v.value?n:d&&"undefined"!==typeof g?d.toColor(g,v):v.color||a.color))&&v.color!==g&&(v.color=g,"point"===a.options.legendType&&v.legendItem&&v.legendItem.label&&a.chart.legend.colorizeItem(v,v.visible))})}function n(a){var n=a.prototype.createAxis;a.prototype.createAxis=function(a,d){if("colorAxis"!==a)return n.apply(this,arguments);var v=new t(this,l(d.axis,{index:this[a].length,isX:!1}));this.isDirtyLegend=!0;this.axes.forEach(function(a){a.series=[]});this.series.forEach(function(a){a.bindAxes();
a.isDirtyData=!0});e(d.redraw,!0)&&this.redraw(d.animation);return v}}function H(){this.elem.attr("fill",q(this.start).tweenTo(q(this.end),this.pos),void 0,!0)}function B(){this.elem.attr("stroke",q(this.start).tweenTo(q(this.end),this.pos),void 0,!0)}var A=[],t;h.compose=function(z,h,e,l,v){t||(t=z);f.pushUnique(A,h)&&(z=h.prototype,z.collectionsWithUpdate.push("colorAxis"),z.collectionsWithInit.colorAxis=[z.addColorAxis],m(h,"afterGetAxes",r),n(h));f.pushUnique(A,e)&&(h=e.prototype,h.fillSetter=
H,h.strokeSetter=B);f.pushUnique(A,l)&&(m(l,"afterGetAllItems",c),m(l,"afterColorizeItem",a),m(l,"afterUpdate",d));f.pushUnique(A,v)&&(p(v.prototype,{optionalAxis:"colorAxis",translateColors:C}),p(v.prototype.pointClass.prototype,{setVisible:g}),m(v,"afterTranslate",u,{order:1}),m(v,"bindAxes",k))};h.pointSetVisible=g})(w||(w={}));return w});x(b,"Core/Axis/Color/ColorAxisDefaults.js",[],function(){return{lineWidth:0,minPadding:0,maxPadding:0,gridLineColor:"#ffffff",gridLineWidth:1,tickPixelInterval:72,
startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:"#999999"},labels:{distance:8,overflow:"justify",rotation:0},minColor:"#e6e9ff",maxColor:"#0022ff",tickLength:5,showInLegend:!0}});x(b,"Core/Axis/Color/ColorAxis.js",[b["Core/Axis/Axis.js"],b["Core/Color/Color.js"],b["Core/Axis/Color/ColorAxisComposition.js"],b["Core/Axis/Color/ColorAxisDefaults.js"],b["Core/Legend/LegendSymbol.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,f,q,m,p,l,e){var y=
this&&this.__extends||function(){function a(d,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,d){a.__proto__=d}||function(a,d){for(var n in d)Object.prototype.hasOwnProperty.call(d,n)&&(a[n]=d[n])};return a(d,c)}return function(d,c){function n(){this.constructor=d}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");a(d,c);d.prototype=null===c?Object.create(c):(n.prototype=c.prototype,new n)}}(),w=f.parse,h=
l.series,r=e.extend,c=e.isArray,a=e.isNumber,d=e.merge,u=e.pick;f=function(k){function g(a,d){var n=k.call(this,a,d)||this;n.beforePadding=!1;n.chart=void 0;n.coll="colorAxis";n.dataClasses=void 0;n.options=void 0;n.stops=void 0;n.visible=!0;n.init(a,d);return n}y(g,k);g.compose=function(a,d,c,u){q.compose(g,a,d,c,u)};g.prototype.init=function(a,n){var u=a.options.legend||{},C=n.layout?"vertical"!==n.layout:"vertical"!==u.layout,h=n.visible;u=d(g.defaultColorAxisOptions,n,{showEmpty:!1,title:null,
visible:u.enabled&&!1!==h});this.side=n.side||C?2:1;this.reversed=n.reversed||!C;this.opposite=!C;k.prototype.init.call(this,a,u,"colorAxis");this.userOptions=n;c(a.userOptions.colorAxis)&&(a.userOptions.colorAxis[this.index]=n);n.dataClasses&&this.initDataClasses(n);this.initStops();this.horiz=C;this.zoomEnabled=!1};g.prototype.initDataClasses=function(a){var n=this.chart,c=this.legendItem=this.legendItem||{},u=a.dataClasses.length,g=this.options,t,k=0,C=n.options.chart.colorCount;this.dataClasses=
t=[];c.labels=[];(a.dataClasses||[]).forEach(function(a,c){a=d(a);t.push(a);if(n.styledMode||!a.color)"category"===g.dataClassColor?(n.styledMode||(c=n.options.colors,C=c.length,a.color=c[k]),a.colorIndex=k,k++,k===C&&(k=0)):a.color=w(g.minColor).tweenTo(w(g.maxColor),2>u?.5:c/(u-1))})};g.prototype.hasData=function(){return!!(this.tickPositions||[]).length};g.prototype.setTickPositions=function(){if(!this.dataClasses)return k.prototype.setTickPositions.call(this)};g.prototype.initStops=function(){this.stops=
this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(a){a.color=w(a[1])})};g.prototype.setOptions=function(a){k.prototype.setOptions.call(this,a);this.options.crosshair=this.options.marker};g.prototype.setAxisSize=function(){var a=this.legendItem&&this.legendItem.symbol,d=this.chart,c=d.options.legend||{},u,k;a?(this.left=c=a.attr("x"),this.top=u=a.attr("y"),this.width=k=a.attr("width"),this.height=a=a.attr("height"),this.right=d.chartWidth-c-k,this.bottom=
d.chartHeight-u-a,this.len=this.horiz?k:a,this.pos=this.horiz?c:u):this.len=(this.horiz?c.symbolWidth:c.symbolHeight)||g.defaultLegendLength};g.prototype.normalizedValue=function(a){this.logarithmic&&(a=this.logarithmic.log2lin(a));return 1-(this.max-a)/(this.max-this.min||1)};g.prototype.toColor=function(a,d){var c=this.dataClasses,n=this.stops,u;if(c)for(u=c.length;u--;){var g=c[u];var k=g.from;n=g.to;if(("undefined"===typeof k||a>=k)&&("undefined"===typeof n||a<=n)){var h=g.color;d&&(d.dataClass=
u,d.colorIndex=g.colorIndex);break}}else{a=this.normalizedValue(a);for(u=n.length;u--&&!(a>n[u][0]););k=n[u]||n[u+1];n=n[u+1]||k;a=1-(n[0]-a)/(n[0]-k[0]||1);h=k.color.tweenTo(n.color,a)}return h};g.prototype.getOffset=function(){var a=this.legendItem&&this.legendItem.group,d=this.chart.axisOffset[this.side];if(a){this.axisParent=a;k.prototype.getOffset.call(this);var c=this.chart.legend;c.allItems.forEach(function(a){a instanceof g&&a.drawLegendSymbol(c,a)});c.render();this.chart.getMargins(!0);this.added||
(this.added=!0,this.labelLeft=0,this.labelRight=this.width);this.chart.axisOffset[this.side]=d}};g.prototype.setLegendColor=function(){var a=this.reversed,d=a?1:0;a=a?0:1;d=this.horiz?[d,0,a,0]:[0,a,0,d];this.legendColor={linearGradient:{x1:d[0],y1:d[1],x2:d[2],y2:d[3]},stops:this.stops}};g.prototype.drawLegendSymbol=function(a,d){var c;d=d.legendItem||{};var n=a.padding,k=a.options,t=this.options.labels,h=u(k.itemDistance,10),e=this.horiz,r=u(k.symbolWidth,e?g.defaultLegendLength:12),C=u(k.symbolHeight,
e?12:g.defaultLegendLength),v=u(k.labelPadding,e?16:30);this.setLegendColor();d.symbol||(d.symbol=this.chart.renderer.symbol("roundedRect",0,a.baseline-11,r,C,{r:null!==(c=k.symbolRadius)&&void 0!==c?c:3}).attr({zIndex:1}).add(d.group));d.labelWidth=r+n+(e?h:u(t.x,t.distance)+this.maxLabelLength);d.labelHeight=C+n+(e?v:0)};g.prototype.setState=function(a){this.series.forEach(function(d){d.setState(a)})};g.prototype.setVisible=function(){};g.prototype.getSeriesExtremes=function(){var a=this.series,
d=a.length,c;this.dataMin=Infinity;for(this.dataMax=-Infinity;d--;){var g=a[d];var k=g.colorKey=u(g.options.colorKey,g.colorKey,g.pointValKey,g.zoneAxis,"y");var t=g.pointArrayMap;var e=g[k+"Min"]&&g[k+"Max"];if(g[k+"Data"])var r=g[k+"Data"];else if(t){r=[];t=t.indexOf(k);var l=g.yData;if(0<=t&&l)for(c=0;c<l.length;c++)r.push(u(l[c][t],l[c]))}else r=g.yData;e?(g.minColorValue=g[k+"Min"],g.maxColorValue=g[k+"Max"]):(r=h.prototype.getExtremes.call(g,r),g.minColorValue=r.dataMin,g.maxColorValue=r.dataMax);
"undefined"!==typeof g.minColorValue&&(this.dataMin=Math.min(this.dataMin,g.minColorValue),this.dataMax=Math.max(this.dataMax,g.maxColorValue));e||h.prototype.applyExtremes.call(g)}};g.prototype.drawCrosshair=function(a,d){var c=this.legendItem||{},g=d&&d.plotX,u=d&&d.plotY,n=this.pos,h=this.len;if(d){var e=this.toPixels(d.getNestedProperty(d.series.colorKey));e<n?e=n-2:e>n+h&&(e=n+h+2);d.plotX=e;d.plotY=this.len-e;k.prototype.drawCrosshair.call(this,a,d);d.plotX=g;d.plotY=u;this.cross&&!this.cross.addedToColorAxis&&
c.group&&(this.cross.addClass("highcharts-coloraxis-marker").add(c.group),this.cross.addedToColorAxis=!0,this.chart.styledMode||"object"!==typeof this.crosshair||this.cross.attr({fill:this.crosshair.color}))}};g.prototype.getPlotLinePath=function(d){var c=this.left,g=d.translatedValue,u=this.top;return a(g)?this.horiz?[["M",g-4,u-6],["L",g+4,u-6],["L",g,u],["Z"]]:[["M",c,g],["L",c-6,g+6],["L",c-6,g-6],["Z"]]:k.prototype.getPlotLinePath.call(this,d)};g.prototype.update=function(a,d){var c=this.chart.legend;
this.series.forEach(function(a){a.isDirtyData=!0});(a.dataClasses&&c.allItems||this.dataClasses)&&this.destroyItems();k.prototype.update.call(this,a,d);this.legendItem&&this.legendItem.label&&(this.setLegendColor(),c.colorizeItem(this,!0))};g.prototype.destroyItems=function(){var a=this.chart,d=this.legendItem||{};if(d.label)a.legend.destroyItem(this);else if(d.labels){var c=0;for(d=d.labels;c<d.length;c++)a.legend.destroyItem(d[c])}a.isDirtyLegend=!0};g.prototype.destroy=function(){this.chart.isDirtyLegend=
!0;this.destroyItems();k.prototype.destroy.apply(this,[].slice.call(arguments))};g.prototype.remove=function(a){this.destroyItems();k.prototype.remove.call(this,a)};g.prototype.getDataClassLegendSymbols=function(){function a(a){return d.series.reduce(function(d,c){d.push.apply(d,c.points.filter(function(d){return d.dataClass===a}));return d},[])}var d=this,c=d.chart,g=d.legendItem&&d.legendItem.labels||[],k=c.options.legend,t=u(k.valueDecimals,-1),h=u(k.valueSuffix,""),e;g.length||d.dataClasses.forEach(function(u,
k){var v=u.from,n=u.to,O=c.numberFormatter,L=!0;e="";"undefined"===typeof v?e="< ":"undefined"===typeof n&&(e="> ");"undefined"!==typeof v&&(e+=O(v,t)+h);"undefined"!==typeof v&&"undefined"!==typeof n&&(e+=" - ");"undefined"!==typeof n&&(e+=O(n,t)+h);g.push(r({chart:c,name:e,options:{},drawLegendSymbol:p.rectangle,visible:!0,isDataClass:!0,setState:function(d){for(var c=0,v=a(k);c<v.length;c++)v[c].setState(d)},setVisible:function(){this.visible=L=d.visible=!L;for(var v=0,g=a(k);v<g.length;v++)g[v].setVisible(L);
c.legend.colorizeItem(this,L)}},u))});return g};g.defaultColorAxisOptions=m;g.defaultLegendLength=200;g.keepProps=["legendItem"];return g}(b);Array.prototype.push.apply(b.keepProps,f.keepProps);"";return f});x(b,"Maps/MapNavigationDefaults.js",[b["Core/Defaults.js"],b["Core/Utilities.js"]],function(b,f){f=f.extend;var q={buttonOptions:{alignTo:"plotBox",align:"left",verticalAlign:"top",x:0,width:18,height:18,padding:5,style:{color:"#666666",fontSize:"1em",fontWeight:"bold"},theme:{fill:"#ffffff",
stroke:"#e6e6e6","stroke-width":1,"text-align":"center"}},buttons:{zoomIn:{onclick:function(){this.mapZoom(.5)},text:"+",y:0},zoomOut:{onclick:function(){this.mapZoom(2)},text:"-",y:28}},mouseWheelSensitivity:1.1};f(b.defaultOptions.lang,{zoomIn:"Zoom in",zoomOut:"Zoom out"});return b.defaultOptions.mapNavigation=q});x(b,"Maps/MapNavigation.js",[b["Core/Chart/Chart.js"],b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,f,q){function m(a){a&&(a.preventDefault&&a.preventDefault(),a.stopPropagation&&
a.stopPropagation(),a.cancelBubble=!0)}function p(a){this.navButtons=[];this.init(a)}var l=f.doc,e=q.addEvent,y=q.extend,w=q.isNumber,h=q.merge,r=q.objectEach,c=q.pick;p.prototype.init=function(a){this.chart=a};p.prototype.update=function(a){function d(a){this.handler.call(k,a);m(a)}var u=this,k=this.chart,g=k.options.mapNavigation,l,n=u.navButtons;a&&(g=k.options.mapNavigation=h(k.options.mapNavigation,a));for(;n.length;)n.pop().destroy();c(g.enableButtons,g.enabled)&&!k.renderer.forExport&&(u.navButtonsGroup||
(u.navButtonsGroup=k.renderer.g().attr({zIndex:4}).add()),r(g.buttons,function(a,c){var r;a=h(g.buttonOptions,a);!k.styledMode&&a.theme&&(l=a.theme,l.style=h(a.theme.style,a.style));var t=a.text,z=a.width,p=void 0===z?0:z;z=a.height;z=void 0===z?0:z;var b=a.padding;b=void 0===b?0:b;var w=k.renderer.button("+"!==t&&"-"!==t&&t||"",0,0,d,l,void 0,void 0,void 0,"zoomIn"===c?"topbutton":"bottombutton").addClass("highcharts-map-navigation highcharts-"+{zoomIn:"zoom-in",zoomOut:"zoom-out"}[c]).attr({width:p,
height:z,title:k.options.lang[c],padding:a.padding,zIndex:5}).add(u.navButtonsGroup);if("+"===t||"-"===t)c=p+1,p=[["M",b+3,b+z/2],["L",b+c-3,b+z/2]],"+"===t&&p.push(["M",b+c/2,b+3],["L",b+c/2,b+z-3]),k.renderer.path(p).addClass("highcharts-button-symbol").attr(k.styledMode?{}:{stroke:null===(r=a.style)||void 0===r?void 0:r.color,"stroke-width":3,"stroke-linecap":"round"}).add(w);w.handler=a.onclick;e(w.element,"dblclick",m);n.push(w);y(a,{width:w.width,height:2*w.height});if(k.hasLoaded)w.align(a,
!1,a.alignTo);else var v=e(k,"load",function(){w.element&&w.align(a,!1,a.alignTo);v()})}),a=function(){var a=k.exportingGroup&&k.exportingGroup.getBBox();if(a){var d=u.navButtonsGroup.getBBox();if(!(d.x>=a.x+a.width||d.x+d.width<=a.x||d.y>=a.y+a.height||d.y+d.height<=a.y)){var c=-d.y-d.height+a.y-5;a=a.y+a.height-d.y+5;u.navButtonsGroup.attr({translateY:"bottom"===(g.buttonOptions&&g.buttonOptions.verticalAlign)?c:a})}}},k.hasLoaded||e(k,"render",a));this.updateEvents(g)};p.prototype.updateEvents=
function(a){var d=this.chart;c(a.enableDoubleClickZoom,a.enabled)||a.enableDoubleClickZoomTo?this.unbindDblClick=this.unbindDblClick||e(d.container,"dblclick",function(a){d.pointer.onContainerDblClick(a)}):this.unbindDblClick&&(this.unbindDblClick=this.unbindDblClick());c(a.enableMouseWheelZoom,a.enabled)?this.unbindMouseWheel=this.unbindMouseWheel||e(d.container,void 0!==l.onwheel?"wheel":void 0!==l.onmousewheel?"mousewheel":"DOMMouseScroll",function(a){d.pointer.inClass(a.target,"highcharts-no-mousewheel")||
(d.pointer.onContainerMouseWheel(a),m(a));return!1}):this.unbindMouseWheel&&(this.unbindMouseWheel=this.unbindMouseWheel())};y(b.prototype,{fitToBox:function(a,d){[["x","width"],["y","height"]].forEach(function(c){var k=c[0];c=c[1];a[k]+a[c]>d[k]+d[c]&&(a[c]>d[c]?(a[c]=d[c],a[k]=d[k]):a[k]=d[k]+d[c]-a[c]);a[c]>d[c]&&(a[c]=d[c]);a[k]<d[k]&&(a[k]=d[k])});return a},mapZoom:function(a,d,c,k,g){this.mapView&&(w(a)&&(a=Math.log(a)/Math.log(.5)),this.mapView.zoomBy(a,w(d)&&w(c)?this.mapView.projection.inverse([d,
c]):void 0,w(k)&&w(g)?[k,g]:void 0))}});e(b,"beforeRender",function(){this.mapNavigation=new p(this);this.mapNavigation.update()});f.MapNavigation=p});x(b,"Maps/MapPointer.js",[b["Core/Pointer.js"],b["Core/Utilities.js"]],function(b,f){var q=f.defined,m=f.extend,p=f.pick;f=f.wrap;var l=b.prototype.normalize,e=0,y;m(b.prototype,{normalize:function(e,h){var r=this.chart;e=l.call(this,e,h);r&&r.mapView&&(h=r.mapView.pixelsToLonLat({x:e.chartX-r.plotLeft,y:e.chartY-r.plotTop}))&&m(e,h);return e},onContainerDblClick:function(e){var h=
this.chart;e=this.normalize(e);h.options.mapNavigation.enableDoubleClickZoomTo?h.pointer.inClass(e.target,"highcharts-tracker")&&h.hoverPoint&&h.hoverPoint.zoomTo():h.isInsidePlot(e.chartX-h.plotLeft,e.chartY-h.plotTop)&&h.mapZoom(.5,void 0,void 0,e.chartX,e.chartY)},onContainerMouseWheel:function(b){var h=this.chart;b=this.normalize(b);var r=q(b.wheelDelta)&&-b.wheelDelta/120||b.deltaY||b.detail;1<=Math.abs(r)&&(e+=Math.abs(r),y&&clearTimeout(y),y=setTimeout(function(){e=0},50));10>e&&h.isInsidePlot(b.chartX-
h.plotLeft,b.chartY-h.plotTop)&&h.mapView&&h.mapView.zoomBy((h.options.mapNavigation.mouseWheelSensitivity-1)*-r,void 0,[b.chartX,b.chartY],1>Math.abs(r)?!1:void 0)}});f(b.prototype,"zoomOption",function(e){var h=this.chart.options.mapNavigation;p(h.enableTouchZoom,h.enabled)&&(this.chart.zooming.pinchType="xy");e.apply(this,[].slice.call(arguments,1))});f(b.prototype,"pinchTranslate",function(e,h,r,c,a,d,u){e.call(this,h,r,c,a,d,u);"map"===this.chart.options.chart.type&&this.hasZoom&&(e=c.scaleX>
c.scaleY,this.pinchTranslateDirection(!e,h,r,c,a,d,u,e?c.scaleX:c.scaleY))})});x(b,"Series/ColorMapComposition.js",[b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,f){var q=b.seriesTypes.column.prototype,m=f.addEvent,p=f.defined,l;(function(e){function b(e){this.moveToTopOnHover&&this.graphic&&this.graphic.attr({zIndex:e&&"hover"===e.state?1:0})}var l=[];e.pointMembers={dataLabelOnNull:!0,moveToTopOnHover:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&
-Infinity!==this.value&&(void 0===this.value||!isNaN(this.value))}};e.seriesMembers={colorKey:"value",axisTypes:["xAxis","yAxis","colorAxis"],parallelArrays:["x","y","value"],pointArrayMap:["value"],trackerGroups:["group","markerGroup","dataLabelsGroup"],colorAttribs:function(e){var h={};!p(e.color)||e.state&&"normal"!==e.state||(h[this.colorProp||"fill"]=e.color);return h},pointAttribs:q.pointAttribs};e.compose=function(e){var h=e.prototype.pointClass;f.pushUnique(l,h)&&m(h,"afterSetState",b);return e}})(l||
(l={}));return l});x(b,"Maps/MapSymbols.js",[b["Core/Renderer/SVG/SVGRenderer.js"]],function(b){var f=b.prototype.symbols;f.bottombutton=function(b,m,p,l,e){if(e){var q=(null===e||void 0===e?void 0:e.r)||0;e.brBoxY=m-q;e.brBoxHeight=l+q}return f.roundedRect(b,m,p,l,e)};f.topbutton=function(b,m,p,l,e){e&&(e.brBoxHeight=l+((null===e||void 0===e?void 0:e.r)||0));return f.roundedRect(b,m,p,l,e)};return f});x(b,"Core/Chart/MapChart.js",[b["Core/Chart/Chart.js"],b["Core/Defaults.js"],b["Core/Renderer/SVG/SVGRenderer.js"],
b["Core/Utilities.js"]],function(b,f,q,m){var p=this&&this.__extends||function(){function e(h,b){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var d in a)Object.prototype.hasOwnProperty.call(a,d)&&(c[d]=a[d])};return e(h,b)}return function(b,r){function c(){this.constructor=b}if("function"!==typeof r&&null!==r)throw new TypeError("Class extends value "+String(r)+" is not a constructor or null");e(b,r);b.prototype=null===r?Object.create(r):
(c.prototype=r.prototype,new c)}}(),l=f.getOptions,e=m.merge,y=m.pick;b=function(b){function h(){return null!==b&&b.apply(this,arguments)||this}p(h,b);h.prototype.init=function(h,c){var a=l().credits;h=e({chart:{panning:{enabled:!0,type:"xy"},type:"map"},credits:{mapText:y(a.mapText,' \u00a9 <a href="{geojson.copyrightUrl}">{geojson.copyrightShort}</a>'),mapTextFull:y(a.mapTextFull,"{geojson.copyright}")},mapView:{},tooltip:{followTouchMove:!1}},h);b.prototype.init.call(this,h,c)};return h}(b);(function(e){e.maps=
{};e.mapChart=function(b,r,c){return new e(b,r,c)};e.splitPath=function(e){"string"===typeof e&&(e=e.replace(/([A-Za-z])/g," $1 ").replace(/^\s*/,"").replace(/\s*$/,""),e=e.split(/[ ,;]+/).map(function(e){return/[A-za-z]/.test(e)?e:parseFloat(e)}));return q.prototype.pathToSegments(e)}})(b||(b={}));return b});x(b,"Maps/MapUtilities.js",[],function(){return{boundsFromPath:function(b){var f=-Number.MAX_VALUE,q=Number.MAX_VALUE,m=-Number.MAX_VALUE,p=Number.MAX_VALUE,l;b.forEach(function(e){var b=e[e.length-
2];e=e[e.length-1];"number"===typeof b&&"number"===typeof e&&(q=Math.min(q,b),f=Math.max(f,b),p=Math.min(p,e),m=Math.max(m,e),l=!0)});if(l)return{x1:q,y1:p,x2:f,y2:m}},pointInPolygon:function(b,f){var q,m=!1,p=b.x,l=b.y;b=0;for(q=f.length-1;b<f.length;q=b++){var e=f[b][1]>l;var y=f[q][1]>l;e!==y&&p<(f[q][0]-f[b][0])*(l-f[b][1])/(f[q][1]-f[b][1])+f[b][0]&&(m=!m)}return m}}});x(b,"Series/Map/MapPoint.js",[b["Series/ColorMapComposition.js"],b["Maps/MapUtilities.js"],b["Core/Series/SeriesRegistry.js"],
b["Core/Utilities.js"]],function(b,f,q,m){var p=this&&this.__extends||function(){function e(b,c){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,d){a.__proto__=d}||function(a,d){for(var c in d)Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])};return e(b,c)}return function(b,c){function a(){this.constructor=b}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");e(b,c);b.prototype=null===c?Object.create(c):
(a.prototype=c.prototype,new a)}}(),l=f.boundsFromPath,e=m.extend,y=m.isNumber,w=m.pick;f=function(b){function h(){var c=null!==b&&b.apply(this,arguments)||this;c.options=void 0;c.path=void 0;c.series=void 0;return c}p(h,b);h.getProjectedPath=function(c,a){c.projectedPath||(a&&c.geometry?(a.hasCoordinates=!0,c.projectedPath=a.path(c.geometry)):c.projectedPath=c.path);return c.projectedPath||[]};h.prototype.applyOptions=function(c,a){var d=this.series;c=b.prototype.applyOptions.call(this,c,a);a=d.joinBy;
d.mapData&&d.mapMap&&(a=b.prototype.getNestedProperty.call(c,a[1]),(a="undefined"!==typeof a&&d.mapMap[a])?e(c,a):-1!==d.pointArrayMap.indexOf("value")&&(c.value=c.value||null));return c};h.prototype.getProjectedBounds=function(c){var a=h.getProjectedPath(this,c);a=l(a);var d=this.properties,e=this.series.chart.mapView;if(a){var k=d&&d["hc-middle-lon"],g=d&&d["hc-middle-lat"];e&&y(k)&&y(g)?(c=c.forward([k,g]),a.midX=c[0],a.midY=c[1]):(c=d&&d["hc-middle-x"],d=d&&d["hc-middle-y"],a.midX=a.x1+(a.x2-
a.x1)*w(this.middleX,y(c)?c:.5),c=w(this.middleY,y(d)?d:.5),this.geometry||(c=1-c),a.midY=a.y2-(a.y2-a.y1)*c);return a}};h.prototype.onMouseOver=function(c){m.clearTimeout(this.colorInterval);if(!this.isNull&&this.visible||this.series.options.nullInteraction)b.prototype.onMouseOver.call(this,c);else this.series.onMouseOut(c)};h.prototype.setVisible=function(c){var a=c?"show":"hide";this.visible=this.options.visible=!!c;if(this.dataLabel)this.dataLabel[a]();this.graphic&&this.graphic.attr(this.series.pointAttribs(this))};
h.prototype.zoomTo=function(c){var a=this.series.chart,d=a.mapView,e=this.bounds;if(d&&e){var k=y(this.insetIndex)&&d.insets[this.insetIndex];if(k){var g=k.projectedUnitsToPixels({x:e.x1,y:e.y1});e=k.projectedUnitsToPixels({x:e.x2,y:e.y2});g=d.pixelsToProjectedUnits({x:g.x,y:g.y});e=d.pixelsToProjectedUnits({x:e.x,y:e.y});e={x1:g.x,y1:g.y,x2:e.x,y2:e.y}}d.fitToBounds(e,void 0,!1);this.series.isDirty=!0;a.redraw(c)}};return h}(q.seriesTypes.scatter.prototype.pointClass);e(f.prototype,{dataLabelOnNull:b.pointMembers.dataLabelOnNull,
moveToTopOnHover:b.pointMembers.moveToTopOnHover,isValid:b.pointMembers.isValid});return f});x(b,"Maps/MapViewOptionsDefault.js",[],function(){return{center:[0,0],fitToGeometry:void 0,maxZoom:void 0,padding:0,projection:{name:void 0,parallels:void 0,rotation:void 0},zoom:void 0}});x(b,"Maps/MapViewInsetsOptionsDefault.js",[],function(){return{borderColor:"#cccccc",borderWidth:1,center:[0,0],padding:"10%",relativeTo:"mapBoundingBox",units:"percent"}});x(b,"Extensions/GeoJSON.js",[b["Core/Chart/Chart.js"],
b["Core/Templating.js"],b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,f,q,m){function p(c,a){function d(a){return"number"===typeof a[0]?a.reduce(function(a,d,c){var g=0>d?e[~d]:e[d];0>d?(g=g.slice(0,0===c?g.length:g.length-1),g.reverse()):c&&(g=g.slice(1));return a.concat(g)},[]):a.map(d)}a||(a=Object.keys(c.objects)[0]);a=c.objects[a];if(a["hc-decoded-geojson"])return a["hc-decoded-geojson"];var e=c.arcs;if(c.transform){var k=c.transform,g=k.scale,b=k.translate;e=c.arcs.map(function(a){var d=
0,c=0;return a.map(function(a){a=a.slice();a[0]=(d+=a[0])*g[0]+b[0];a[1]=(c+=a[1])*g[1]+b[1];return a})})}k=a.geometries.map(function(a){return{type:"Feature",properties:a.properties,geometry:{type:a.type,coordinates:a.coordinates||d(a.arcs)}}});c={type:"FeatureCollection",copyright:c.copyright,copyrightShort:c.copyrightShort,copyrightUrl:c.copyrightUrl,features:k,"hc-recommended-mapview":a["hc-recommended-mapview"],bbox:c.bbox,title:c.title};return a["hc-decoded-geojson"]=c}function l(c,a,d){void 0===
a&&(a="map");var b=[];c="Topology"===c.type?p(c):c;c.features.forEach(function(d){var c=d.geometry||{},e=c.type;c=c.coordinates;d=d.properties;var k;"map"!==a&&"mapbubble"!==a||"Polygon"!==e&&"MultiPolygon"!==e?"mapline"!==a||"LineString"!==e&&"MultiLineString"!==e?"mappoint"===a&&"Point"===e&&c.length&&(k={geometry:{coordinates:c,type:e}}):c.length&&(k={geometry:{coordinates:c,type:e}}):c.length&&(k={geometry:{coordinates:c,type:e}});if(k){e=d&&(d.name||d.NAME);c=d&&d.lon;var u=d&&d.lat;b.push(h(k,
{lat:"number"===typeof u?u:void 0,lon:"number"===typeof c?c:void 0,name:"string"===typeof e?e:void 0,properties:d}))}});d&&c.copyrightShort&&(d.chart.mapCredits=e(d.chart.options.credits.mapText,{geojson:c}),d.chart.mapCreditsFull=e(d.chart.options.credits.mapTextFull,{geojson:c}));return b}var e=f.format,y=q.win,w=m.error,h=m.extend,r=m.merge;f=m.wrap;"";b.prototype.transformFromLatLon=function(c,a){var d=this.options.chart.proj4||y.proj4;if(d){var e=a.jsonmarginX;e=void 0===e?0:e;var k=a.jsonmarginY;
k=void 0===k?0:k;var g=a.jsonres;g=void 0===g?1:g;var b=a.scale;b=void 0===b?1:b;var n=a.xoffset;n=void 0===n?0:n;var h=a.xpan;h=void 0===h?0:h;var l=a.yoffset;l=void 0===l?0:l;var p=a.ypan;p=void 0===p?0:p;c=d(a.crs,[c.lon,c.lat]);d=a.cosAngle||a.rotation&&Math.cos(a.rotation);var t=a.sinAngle||a.rotation&&Math.sin(a.rotation);a=a.rotation?[c[0]*d+c[1]*t,-c[0]*t+c[1]*d]:c;return{x:((a[0]-n)*b+h)*g+e,y:-(((l-a[1])*b+p)*g-k)}}w(21,!1,this)};b.prototype.transformToLatLon=function(c,a){var d=this.options.chart.proj4||
y.proj4;if(!d)w(21,!1,this);else if(null!==c.y){var e=a.jsonmarginX,k=a.jsonmarginY,g=a.jsonres;g=void 0===g?1:g;var b=a.scale;b=void 0===b?1:b;var n=a.xoffset,h=a.xpan,l=a.yoffset,p=a.ypan;c={x:((c.x-(void 0===e?0:e))/g-(void 0===h?0:h))/b+(void 0===n?0:n),y:((c.y-(void 0===k?0:k))/g+(void 0===p?0:p))/b+(void 0===l?0:l)};e=a.cosAngle||a.rotation&&Math.cos(a.rotation);k=a.sinAngle||a.rotation&&Math.sin(a.rotation);a=d(a.crs,"WGS84",a.rotation?{x:c.x*e+c.y*-k,y:c.x*k+c.y*e}:c);return{lat:a.y,lon:a.x}}};
b.prototype.fromPointToLatLon=function(c){return this.mapView&&this.mapView.projectedUnitsToLonLat(c)};b.prototype.fromLatLonToPoint=function(c){return this.mapView&&this.mapView.lonLatToProjectedUnits(c)};f(b.prototype,"addCredits",function(c,a){a=r(!0,this.options.credits,a);this.mapCredits&&(a.href=null);c.call(this,a);this.credits&&this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})});q.geojson=l;q.topo2geo=p;return{geojson:l,topo2geo:p}});x(b,"Core/Geometry/PolygonClip.js",[],
function(){function b(b,p,l,e){var f=[b[0]-p[0],b[1]-p[1]],m=[l[0]-e[0],l[1]-e[1]];b=b[0]*p[1]-b[1]*p[0];l=l[0]*e[1]-l[1]*e[0];e=1/(f[0]*m[1]-f[1]*m[0]);f=[(b*m[0]-l*f[0])*e,(b*m[1]-l*f[1])*e];f.isIntersection=!0;return f}function f(b,p,l){return(p[0]-b[0])*(l[1]-b[1])>(p[1]-b[1])*(l[0]-b[0])}var q;(function(m){m.clipLineString=function(b,l){var e=[];b=m.clipPolygon(b,l,!1);for(l=1;l<b.length;l++)b[l].isIntersection&&b[l-1].isIntersection&&(e.push(b.splice(0,l)),l=0),l===b.length-1&&e.push(b);return e};
m.clipPolygon=function(p,l,e){void 0===e&&(e=!0);for(var m=l[l.length-1],q,h,r=p,c=0;c<l.length;c++){var a=r;p=l[c];r=[];q=e?a[a.length-1]:a[0];for(var d=0;d<a.length;d++)h=a[d],f(m,p,h)?(f(m,p,q)||r.push(b(m,p,q,h)),r.push(h)):f(m,p,q)&&r.push(b(m,p,q,h)),q=h;m=p}return r}})(q||(q={}));return q});x(b,"Maps/Projections/LambertConformalConic.js",[],function(){var b=Math.sign||function(b){return 0===b?0:0<b?1:-1},f=Math.PI/180,q=Math.PI/2;return function(){function m(p){var l,e=(p.parallels||[]).map(function(e){return e*
f}),m=e[0]||0;e=null!==(l=e[1])&&void 0!==l?l:m;l=Math.cos(m);"object"===typeof p.projectedBounds&&(this.projectedBounds=p.projectedBounds);p=m===e?Math.sin(m):Math.log(l/Math.cos(e))/Math.log(Math.tan((q+e)/2)/Math.tan((q+m)/2));1e-10>Math.abs(p)&&(p=1e-10*(b(p)||1));this.n=p;this.c=l*Math.pow(Math.tan((q+m)/2),p)/p}m.prototype.forward=function(b){var l=b[0]*f,e=this.c,p=this.n,m=this.projectedBounds;b=b[1]*f;0<e?b<-q+.000001&&(b=-q+.000001):b>q-.000001&&(b=q-.000001);var h=e/Math.pow(Math.tan((q+
b)/2),p);b=h*Math.sin(p*l)*63.78137;l=63.78137*(e-h*Math.cos(p*l));e=[b,l];m&&(b<m.x1||b>m.x2||l<m.y1||l>m.y2)&&(e.outside=!0);return e};m.prototype.inverse=function(p){var l=p[0]/63.78137,e=this.c,m=this.n;p=e-p[1]/63.78137;var w=b(m)*Math.sqrt(l*l+p*p),h=Math.atan2(l,Math.abs(p))*b(p);0>p*m&&(h-=Math.PI*b(l)*b(p));return[h/m/f,(2*Math.atan(Math.pow(e/w,1/m))-q)/f]};return m}()});x(b,"Maps/Projections/EqualEarth.js",[],function(){var b=Math.sqrt(3)/2;return function(){function f(){this.bounds={x1:-200.37508342789243,
x2:200.37508342789243,y1:-97.52595454902263,y2:97.52595454902263}}f.prototype.forward=function(f){var m=Math.PI/180,p=Math.asin(b*Math.sin(f[1]*m)),l=p*p,e=l*l*l;return[f[0]*m*Math.cos(p)*74.03120656864502/(b*(1.340264+3*-.081106*l+e*(7*.000893+.034164*l))),74.03120656864502*p*(1.340264+-.081106*l+e*(.000893+.003796*l))]};f.prototype.inverse=function(f){var m=f[0]/74.03120656864502;f=f[1]/74.03120656864502;var p=180/Math.PI,l=f,e;for(e=0;12>e;++e){var q=l*l;var w=q*q*q;var h=l*(1.340264+-.081106*
q+w*(.000893+.003796*q))-f;q=1.340264+3*-.081106*q+w*(7*.000893+.034164*q);l-=h/=q;if(1e-9>Math.abs(h))break}q=l*l;return[p*b*m*(1.340264+3*-.081106*q+q*q*q*(7*.000893+.034164*q))/Math.cos(l),p*Math.asin(Math.sin(l)/b)]};return f}()});x(b,"Maps/Projections/Miller.js",[],function(){var b=Math.PI/4,f=Math.PI/180;return function(){function q(){this.bounds={x1:-200.37508342789243,x2:200.37508342789243,y1:-146.91480769173063,y2:146.91480769173063}}q.prototype.forward=function(m){return[m[0]*f*63.78137,
79.7267125*Math.log(Math.tan(b+.4*m[1]*f))]};q.prototype.inverse=function(m){return[m[0]/63.78137/f,2.5*(Math.atan(Math.exp(m[1]/63.78137*.8))-b)/f]};return q}()});x(b,"Maps/Projections/Orthographic.js",[],function(){var b=Math.PI/180;return function(){function f(){this.antimeridianCutting=!1;this.bounds={x1:-63.78460826781007,x2:63.78460826781007,y1:-63.78460826781007,y2:63.78460826781007}}f.prototype.forward=function(f){var m=f[0];f=f[1]*b;f=[Math.cos(f)*Math.sin(m*b)*63.78460826781007,63.78460826781007*
Math.sin(f)];if(-90>m||90<m)f.outside=!0;return f};f.prototype.inverse=function(f){var m=f[0]/63.78460826781007;f=f[1]/63.78460826781007;var p=Math.sqrt(m*m+f*f),l=Math.asin(p),e=Math.sin(l);return[Math.atan2(m*e,p*Math.cos(l))/b,Math.asin(p&&f*e/p)/b]};return f}()});x(b,"Maps/Projections/WebMercator.js",[],function(){var b=Math.PI/180;return function(){function f(){this.bounds={x1:-200.37508342789243,x2:200.37508342789243,y1:-200.3750834278071,y2:200.3750834278071};this.maxLatitude=85.0511287798}
f.prototype.forward=function(f){var m=Math.sin(f[1]*b);m=[63.78137*f[0]*b,63.78137*Math.log((1+m)/(1-m))/2];85.0511287798<Math.abs(f[1])&&(m.outside=!0);return m};f.prototype.inverse=function(f){return[f[0]/(63.78137*b),(2*Math.atan(Math.exp(f[1]/63.78137))-Math.PI/2)/b]};return f}()});x(b,"Maps/Projections/ProjectionRegistry.js",[b["Maps/Projections/LambertConformalConic.js"],b["Maps/Projections/EqualEarth.js"],b["Maps/Projections/Miller.js"],b["Maps/Projections/Orthographic.js"],b["Maps/Projections/WebMercator.js"]],
function(b,f,q,m,p){return{EqualEarth:f,LambertConformalConic:b,Miller:q,Orthographic:m,WebMercator:p}});x(b,"Maps/Projection.js",[b["Core/Geometry/PolygonClip.js"],b["Maps/Projections/ProjectionRegistry.js"],b["Core/Utilities.js"]],function(b,f,q){function m(b){-180>b&&(b+=360);180<b&&(b-=360);return b}var p=this&&this.__spreadArray||function(b,c,a){if(a||2===arguments.length)for(var d=0,e=c.length,k;d<e;d++)!k&&d in c||(k||(k=Array.prototype.slice.call(c,0,d)),k[d]=c[d]);return b.concat(k||Array.prototype.slice.call(c))},
l=b.clipLineString,e=b.clipPolygon,y=q.clamp,w=q.erase,h=2*Math.PI/360;return function(){function b(c){void 0===c&&(c={});this.hasGeoProjection=this.hasCoordinates=!1;this.maxLatitude=90;this.options=c;var a=c.name,d=c.projectedBounds,e=c.rotation;this.rotator=e?this.getRotator(e):void 0;if(a=a?b.registry[a]:void 0)this.def=new a(c);var k=this.def,g=this.rotator;k&&(this.maxLatitude=k.maxLatitude||90,this.hasGeoProjection=!0);g&&k?(this.forward=function(a){return k.forward(g.forward(a))},this.inverse=
function(a){return g.inverse(k.inverse(a))}):k?(this.forward=function(a){return k.forward(a)},this.inverse=function(a){return k.inverse(a)}):g&&(this.forward=g.forward,this.inverse=g.inverse);this.bounds="world"===d?k&&k.bounds:d}b.add=function(c,a){b.registry[c]=a};b.greatCircle=function(c,a,d){var b=Math.atan2,e=Math.cos,g=Math.sin,l=Math.sqrt,n=c[1]*h,f=c[0]*h,m=a[1]*h,p=a[0]*h,t=m-n,z=p-f;t=g(t/2)*g(t/2)+e(n)*e(m)*g(z/2)*g(z/2);t=2*b(l(t),l(1-t));var r=Math.round(6371E3*t/5E5);z=[];d&&z.push(c);
if(1<r)for(r=c=1/r;.999>r;r+=c){var q=g((1-r)*t)/g(t),w=g(r*t)/g(t),v=q*e(n)*e(f)+w*e(m)*e(p),G=q*e(n)*g(f)+w*e(m)*g(p);q=q*g(n)+w*g(m);q=b(q,l(v*v+G*G));v=b(G,v);z.push([v/h,q/h])}d&&z.push(a);return z};b.insertGreatCircles=function(c){for(var a=c.length-1;a--;)if(10<Math.max(Math.abs(c[a][0]-c[a+1][0]),Math.abs(c[a][1]-c[a+1][1]))){var d=b.greatCircle(c[a],c[a+1]);d.length&&c.splice.apply(c,p([a+1,0],d,!1))}};b.toString=function(c){c=c||{};var a=c.rotation;return[c.name,a&&a.join(",")].join(";")};
b.prototype.lineIntersectsBounds=function(c){function a(a,d,c){var b=a[0];a=a[1];var e=d?0:1;if("number"===typeof c&&b[d]>=c!==a[d]>=c)return b=b[e]+(c-b[d])/(a[d]-b[d])*(a[e]-b[e]),d?[b,c]:[c,b]}var d=this.bounds||{},b=d.x2,e=d.y1,g=d.y2,h=c[0];if(d=a(c,0,d.x1))h=d,c[1]=d;else if(d=a(c,0,b))h=d,c[1]=d;if(d=a(c,1,e))h=d;else if(d=a(c,1,g))h=d;return h};b.prototype.getRotator=function(c){var a=c[0]*h,d=(c[1]||0)*h;c=(c[2]||0)*h;var b=Math.cos(d),e=Math.sin(d),g=Math.cos(c),l=Math.sin(c);if(0!==a||
0!==d||0!==c)return{forward:function(d){var c=d[0]*h+a,k=d[1]*h,n=Math.cos(k);d=Math.cos(c)*n;c=Math.sin(c)*n;k=Math.sin(k);n=k*b+d*e;return[Math.atan2(c*g-n*l,d*b-k*e)/h,Math.asin(n*g+c*l)/h]},inverse:function(d){var c=d[0]*h,k=d[1]*h,n=Math.cos(k);d=Math.cos(c)*n;c=Math.sin(c)*n;k=Math.sin(k);n=k*g-c*l;return[(Math.atan2(c*g+k*l,d*b+n*e)-a)/h,Math.asin(n*b-d*e)/h]}}};b.prototype.forward=function(c){return c};b.prototype.inverse=function(c){return c};b.prototype.cutOnAntimeridian=function(c,a){var d=
[],e=[c];c.forEach(function(b,e){var g=c[e-1];if(!e){if(!a)return;g=c[c.length-1]}var k=g[0],v=b[0];(-90>k||90<k)&&(-90>v||90<v)&&0<k!==0<v&&(v=y((180-(k+360)%360)/((v+360)%360-(k+360)%360),0,1),d.push({i:e,lat:g[1]+v*(b[1]-g[1]),direction:0>k?1:-1,previousLonLat:g,lonLat:b}))});if(d.length)if(a){if(1===d.length%2){var k=d.slice().sort(function(a,d){return Math.abs(d.lat)-Math.abs(a.lat)})[0];w(d,k)}for(var g=d.length-2;0<=g;){var h=d[g].i,n=m(180+.000001*d[g].direction),l=m(180-.000001*d[g].direction);
h=c.splice.apply(c,p([h,d[g+1].i-h],b.greatCircle([n,d[g].lat],[n,d[g+1].lat],!0),!1));h.push.apply(h,b.greatCircle([l,d[g+1].lat],[l,d[g].lat],!0));e.push(h);g-=2}if(k)for(n=0;n<e.length;n++){g=k.direction;var f=k.lat;l=e[n];h=l.indexOf(k.lonLat);if(-1<h){n=(0>f?-1:1)*this.maxLatitude;var r=m(180+.000001*g),t=m(180-.000001*g);f=b.greatCircle([r,f],[r,n],!0);for(r+=120*g;-180<r&&180>r;r+=120*g)f.push([r,n]);f.push.apply(f,b.greatCircle([t,n],[t,k.lat],!0));l.splice.apply(l,p([h,0],f,!1));break}}}else for(g=
d.length;g--;)h=d[g].i,h=c.splice(h,c.length,[m(180+.000001*d[g].direction),d[g].lat]),h.unshift([m(180-.000001*d[g].direction),d[g].lat]),e.push(h);return e};b.prototype.path=function(c){function a(a){a=a.map(function(a){if(p){r&&(a=r.forward(a));var d=a[0];.000001>Math.abs(d-180)&&(d=180>d?179.999999:180.000001);a=[d,a[1]]}return a});var c=[a];m&&(b.insertGreatCircles(a),p&&(c=d.cutOnAntimeridian(a,n)));c.forEach(function(a){if(!(2>a.length)){var d=!1,c=!1,g=function(a){d?f.push(["L",a[0],a[1]]):
(f.push(["M",a[0],a[1]]),d=!0)},k=!1,u=!1,r=a.map(function(a){a=t.forward(a);a.outside?k=!0:u=!0;Infinity===a[1]?a[1]=1E10:-Infinity===a[1]&&(a[1]=-1E10);return a});if(p){n&&r.push(r[0]);if(k){if(!u)return;if(z)if(n)r=e(r,z);else if(h){l(r,z).forEach(function(a){d=!1;a.forEach(g)});return}}r.forEach(g)}else for(var q=0;q<r.length;q++){var M=a[q],w=r[q];if(w.outside)c=!0;else{if(n&&!E){var E=M;a.push(M);r.push(w)}c&&A&&(n&&m?b.greatCircle(A,M).forEach(function(a){return g(t.forward(a))}):d=!1);g(w);
var A=M;c=!1}}}})}var d=this,h=this.bounds,k=this.def,g=this.rotator,f=[],n="Polygon"===c.type||"MultiPolygon"===c.type,m=this.hasGeoProjection,p=!k||!1!==k.antimeridianCutting,r=p?g:void 0,t=p?k||this:this,z;h&&(z=[[h.x1,h.y1],[h.x2,h.y1],[h.x2,h.y2],[h.x1,h.y2]]);"LineString"===c.type?a(c.coordinates):"MultiLineString"===c.type?c.coordinates.forEach(function(d){return a(d)}):"Polygon"===c.type?(c.coordinates.forEach(function(d){return a(d)}),f.length&&f.push(["Z"])):"MultiPolygon"===c.type&&(c.coordinates.forEach(function(d){d.forEach(function(d){return a(d)})}),
f.length&&f.push(["Z"]));return f};b.registry=f;return b}()});x(b,"Maps/MapView.js",[b["Maps/MapViewOptionsDefault.js"],b["Maps/MapViewInsetsOptionsDefault.js"],b["Extensions/GeoJSON.js"],b["Core/Chart/MapChart.js"],b["Maps/MapUtilities.js"],b["Maps/Projection.js"],b["Core/Utilities.js"]],function(b,f,q,m,p,l,e){function y(a,d){return Math.log(400.979322/Math.max((a.x2-a.x1)/(d.width/256),(a.y2-a.y1)/(d.height/256)))/Math.log(2)}var w=this&&this.__extends||function(){function a(d,c){a=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(a,d){a.__proto__=d}||function(a,d){for(var c in d)Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])};return a(d,c)}return function(d,c){function b(){this.constructor=d}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");a(d,c);d.prototype=null===c?Object.create(c):(b.prototype=c.prototype,new b)}}(),h=this&&this.__spreadArray||function(a,d,c){if(c||2===arguments.length)for(var b=0,e=
d.length,g;b<e;b++)!g&&b in d||(g||(g=Array.prototype.slice.call(d,0,b)),g[b]=d[b]);return a.concat(g||Array.prototype.slice.call(d))},r=q.topo2geo,c=m.maps,a=p.boundsFromPath,d=p.pointInPolygon,u=e.addEvent,k=e.clamp,g=e.fireEvent,C=e.isArray,n=e.isNumber,H=e.isObject,B=e.isString,A=e.merge,t=e.pick,z=e.relativeLength,E=function(){function e(a,d){var c=this;this.allowTransformAnimation=!0;this.insets=[];this.padding=[0,0,0,0];this.eventsToUnbind=[];var v;if(!(this instanceof K)){var k=h([a.options.chart.map],
(a.options.series||[]).map(function(a){return a.mapData}),!0).map(function(a){return c.getGeoMap(a)}),t=[];k.forEach(function(a){a&&(G||(G=a["hc-recommended-mapview"]),a.bbox&&(a=a.bbox,t.push({x1:a[0],y1:a[1],x2:a[2],y2:a[3]})))});var f=t.length&&e.compositeBounds(t);g(a,"beforeMapViewInit",{geoBounds:f},function(){if(f){var a=f.x1,d=f.y1,c=f.x2,b=f.y2;v=180<c-a&&90<b-d?{name:"EqualEarth"}:{name:"LambertConformalConic",parallels:[d,b],rotation:[-(a+c)/2]}}});this.geoMap=k[0]}this.userOptions=d||
{};if(a.options.mapView&&a.options.mapView.recommendedMapView)var G=a.options.mapView.recommendedMapView;k=A(b,{projection:v},G,d);var m=G&&G.insets;d=d&&d.insets;m&&d&&(k.insets=e.mergeInsets(m,d));this.chart=a;this.center=k.center;this.options=k;this.projection=new l(k.projection);this.playingField=a.plotBox;this.zoom=k.zoom||0;this.minZoom=k.minZoom;this.createInsets();this.eventsToUnbind.push(u(a,"afterSetChartSize",function(){c.playingField=c.getField();if(void 0===c.minZoom||c.minZoom===c.zoom)c.fitToBounds(void 0,
void 0,!1),!c.chart.hasRendered&&n(c.userOptions.zoom)&&(c.zoom=c.userOptions.zoom),c.userOptions.center&&A(!0,c.center,c.userOptions.center)}));this.setUpEvents()}e.mergeInsets=function(a,d){function c(a){var d={};a.forEach(function(a,c){d[a&&a.id||"i".concat(c)]=a});return d}var b=A(c(a),c(d));return Object.keys(b).map(function(a){return b[a]})};e.prototype.createInsets=function(){var a=this,d=this.options,c=d.insets;c&&c.forEach(function(c){c=new K(a,A(d.insetOptions,c));a.insets.push(c)})};e.prototype.fitToBounds=
function(a,d,c,b){void 0===c&&(c=!0);var e=a||this.getProjectedBounds();if(e){var g=t(d,a?0:this.options.padding);d=this.getField(!1);g=C(g)?g:[g,g,g,g];this.padding=[z(g[0],d.height),z(g[1],d.width),z(g[2],d.height),z(g[3],d.width)];this.playingField=this.getField();d=y(e,this.playingField);a||(this.minZoom=d);a=this.projection.inverse([(e.x2+e.x1)/2,(e.y2+e.y1)/2]);this.setView(a,d,c,b)}};e.prototype.getField=function(a){void 0===a&&(a=!0);a=a?this.padding:[0,0,0,0];return{x:a[3],y:a[0],width:this.chart.plotWidth-
a[1]-a[3],height:this.chart.plotHeight-a[0]-a[2]}};e.prototype.getGeoMap=function(a){if(B(a))return c[a]&&"Topology"===c[a].type?r(c[a]):c[a];if(H(a,!0)){if("FeatureCollection"===a.type)return a;if("Topology"===a.type)return r(a)}};e.prototype.getMapBBox=function(){var a=this.getProjectedBounds(),d=this.getScale();if(a){var c=this.padding,b=this.projectedUnitsToPixels({x:a.x1,y:a.y2});return{width:(a.x2-a.x1)*d+c[1]+c[3],height:(a.y2-a.y1)*d+c[0]+c[2],x:b.x-c[3],y:b.y-c[0]}}};e.prototype.getProjectedBounds=
function(){var d=this.projection,c=this.chart.series.reduce(function(a,d){var c=d.getProjectedBounds&&d.getProjectedBounds();c&&!1!==d.options.affectsMapView&&a.push(c);return a},[]),b=this.options.fitToGeometry;return b?(this.fitToGeometryCache||("MultiPoint"===b.type?(b=b.coordinates.map(function(a){return d.forward(a)}),c=b.map(function(a){return a[0]}),b=b.map(function(a){return a[1]}),this.fitToGeometryCache={x1:Math.min.apply(0,c),x2:Math.max.apply(0,c),y1:Math.min.apply(0,b),y2:Math.max.apply(0,
b)}):this.fitToGeometryCache=a(d.path(b))),this.fitToGeometryCache):this.projection.bounds||e.compositeBounds(c)};e.prototype.getScale=function(){return 256/400.979322*Math.pow(2,this.zoom)};e.prototype.getSVGTransform=function(){var a=this.playingField,d=a.x,c=a.y,b=a.width;a=a.height;var e=this.projection.forward(this.center),g=this.projection.hasCoordinates?-1:1,k=this.getScale();g*=k;return{scaleX:k,scaleY:g,translateX:d+b/2-e[0]*k,translateY:c+a/2-e[1]*g}};e.prototype.lonLatToPixels=function(a){if(a=
this.lonLatToProjectedUnits(a))return this.projectedUnitsToPixels(a)};e.prototype.lonLatToProjectedUnits=function(a){var c=this.chart,b=c.mapTransforms;if(b){for(var e in b)if(Object.hasOwnProperty.call(b,e)&&b[e].hitZone){var g=c.transformFromLatLon(a,b[e]);if(g&&d(g,b[e].hitZone.coordinates[0]))return g}return c.transformFromLatLon(a,b["default"])}b=0;for(e=this.insets;b<e.length;b++)if(c=e[b],c.options.geoBounds&&d({x:a.lon,y:a.lat},c.options.geoBounds.coordinates[0]))return a=c.projection.forward([a.lon,
a.lat]),a=c.projectedUnitsToPixels({x:a[0],y:a[1]}),this.pixelsToProjectedUnits(a);a=this.projection.forward([a.lon,a.lat]);if(!a.outside)return{x:a[0],y:a[1]}};e.prototype.projectedUnitsToLonLat=function(a){var c=this.chart,b=c.mapTransforms;if(b){for(var e in b)if(Object.hasOwnProperty.call(b,e)&&b[e].hitZone&&d(a,b[e].hitZone.coordinates[0]))return c.transformToLatLon(a,b[e]);return c.transformToLatLon(a,b["default"])}b=this.projectedUnitsToPixels(a);e=0;for(var g=this.insets;e<g.length;e++)if(c=
g[e],c.hitZone&&d(b,c.hitZone.coordinates[0]))return a=c.pixelsToProjectedUnits(b),a=c.projection.inverse([a.x,a.y]),{lon:a[0],lat:a[1]};a=this.projection.inverse([a.x,a.y]);return{lon:a[0],lat:a[1]}};e.prototype.redraw=function(a){this.chart.series.forEach(function(a){a.useMapGeometry&&(a.isDirty=!0)});this.chart.redraw(a)};e.prototype.setView=function(a,d,c,b){void 0===c&&(c=!0);a&&(this.center=a);"number"===typeof d&&("number"===typeof this.minZoom&&(d=Math.max(d,this.minZoom)),"number"===typeof this.options.maxZoom&&
(d=Math.min(d,this.options.maxZoom)),n(d)&&(this.zoom=d));var e=this.getProjectedBounds();if(e){a=this.projection.forward(this.center);var k=this.playingField;d=k.x;var h=k.y,t=k.width;k=k.height;var f=this.getScale(),l=this.projectedUnitsToPixels({x:e.x1,y:e.y1}),u=this.projectedUnitsToPixels({x:e.x2,y:e.y2});e=[(e.x1+e.x2)/2,(e.y1+e.y2)/2];if(!this.chart.series.some(function(a){return a.isDrilling})){var m=l.x,v=u.y;u=u.x;l=l.y;u-m<t?a[0]=e[0]:m<d&&u<d+t?a[0]+=Math.max(m-d,u-t-d)/f:u>d+t&&m>d&&
(a[0]+=Math.min(u-t-d,m-d)/f);l-v<k?a[1]=e[1]:v<h&&l<h+k?a[1]-=Math.max(v-h,l-k-h)/f:l>h+k&&v>h&&(a[1]-=Math.min(l-k-h,v-h)/f);this.center=this.projection.inverse(a)}this.insets.forEach(function(a){a.options.field&&(a.hitZone=a.getHitZone(),a.playingField=a.getField())});this.render()}g(this,"afterSetView");c&&this.redraw(b)};e.prototype.projectedUnitsToPixels=function(a){var d=this.getScale(),c=this.projection.forward(this.center),b=this.playingField;return{x:b.x+b.width/2-d*(c[0]-a.x),y:b.y+b.height/
2+d*(c[1]-a.y)}};e.prototype.pixelsToLonLat=function(a){return this.projectedUnitsToLonLat(this.pixelsToProjectedUnits(a))};e.prototype.pixelsToProjectedUnits=function(a){var d=a.x;a=a.y;var c=this.getScale(),b=this.projection.forward(this.center),e=this.playingField;return{x:b[0]+(d-(e.x+e.width/2))/c,y:b[1]-(a-(e.y+e.height/2))/c}};e.prototype.setUpEvents=function(){function a(a){var h=c.pointer.pinchDown,t=d.projection,f=c.mouseDownX,l=c.mouseDownY;1===h.length&&(f=h[0].chartX,l=h[0].chartY);if("number"===
typeof f&&"number"===typeof l){var u="".concat(f,",").concat(l),m=a.originalEvent;h=m.chartX;m=m.chartY;u!==e&&(e=u,b=d.projection.forward(d.center),g=(d.projection.options.rotation||[0,0]).slice());u=(u=t.def&&t.def.bounds)&&y(u,d.playingField)||-Infinity;"Orthographic"===t.options.name&&(d.minZoom||Infinity)<1.3*u?(t=440/(d.getScale()*Math.min(c.plotWidth,c.plotHeight)),g&&(f=(f-h)*t-g[0],l=k(-g[1]-(l-m)*t,-80,80),h=d.zoom,d.update({projection:{rotation:[-f,-l]}},!1),d.fitToBounds(void 0,void 0,
!1),d.zoom=h,c.redraw(!1))):n(h)&&n(m)&&(t=d.getScale(),l=d.projection.inverse([b[0]+(f-h)/t,b[1]-(l-m)/t*(d.projection.hasCoordinates?1:-1)]),d.setView(l,void 0,!0,!1));a.preventDefault()}}var d=this,c=this.chart,b,e,g;u(c,"pan",a);u(c,"touchpan",a);u(c,"selection",function(a){if(a.resetSelection)d.zoomBy();else{var b=a.x-c.plotLeft,e=a.y-c.plotTop,g=d.pixelsToProjectedUnits({x:b,y:e}),k=g.y;g=g.x;b=d.pixelsToProjectedUnits({x:b+a.width,y:e+a.height});d.fitToBounds({x1:g,y1:k,x2:b.x,y2:b.y},void 0,
!0,a.originalEvent.touches?!1:void 0);/^touch/.test(a.originalEvent.type)||c.showResetZoom();a.preventDefault()}})};e.prototype.render=function(){this.group||(this.group=this.chart.renderer.g("map-view").attr({zIndex:4}).add())};e.prototype.update=function(a,d,c){void 0===d&&(d=!0);var b=a.projection;b=b&&l.toString(b)!==l.toString(this.options.projection);var e=!1;A(!0,this.userOptions,a);A(!0,this.options,a);"insets"in a&&(this.insets.forEach(function(a){return a.destroy()}),this.insets.length=
0,e=!0);(b||"fitToGeometry"in a)&&delete this.fitToGeometryCache;if(b||e)this.chart.series.forEach(function(a){var d=a.transformGroups;a.clearBounds&&a.clearBounds();a.isDirty=!0;a.isDirtyData=!0;if(e&&d)for(;1<d.length;)(a=d.pop())&&a.destroy()}),b&&(this.projection=new l(this.options.projection)),e&&this.createInsets(),a.center||!Object.hasOwnProperty.call(a,"zoom")||n(a.zoom)||this.fitToBounds(void 0,void 0,!1);a.center||n(a.zoom)?this.setView(this.options.center,a.zoom,!1):"fitToGeometry"in a&&
this.fitToBounds(void 0,void 0,!1);d&&this.chart.redraw(c)};e.prototype.zoomBy=function(a,d,c,b){var e=this.chart,g=this.projection.forward(this.center);d=d?this.projection.forward(d):[];var k=d[0],h=d[1];"number"===typeof a?(a=this.zoom+a,d=void 0,c&&(k=c[0],h=c[1],c=this.getScale(),k=k-e.plotLeft-e.plotWidth/2,e=h-e.plotTop-e.plotHeight/2,k=g[0]+k/c,h=g[1]+e/c),"number"===typeof k&&"number"===typeof h&&(c=1-Math.pow(2,this.zoom)/Math.pow(2,a),k=g[0]-k,e=g[1]-h,g[0]-=k*c,g[1]+=e*c,d=this.projection.inverse(g)),
this.setView(d,a,void 0,b)):this.fitToBounds(void 0,void 0,void 0,b)};e.compositeBounds=function(a){if(a.length)return a.slice(1).reduce(function(a,d){a.x1=Math.min(a.x1,d.x1);a.y1=Math.min(a.y1,d.y1);a.x2=Math.max(a.x2,d.x2);a.y2=Math.max(a.y2,d.y2);return a},A(a[0]))};return e}(),K=function(c){function b(d,b){var e=c.call(this,d.chart,b)||this;e.id=b.id;e.mapView=d;e.options=A(f,b);e.allBounds=[];e.options.geoBounds&&(d=d.projection.path(e.options.geoBounds),e.geoBoundsProjectedBox=a(d),e.geoBoundsProjectedPolygon=
d.map(function(a){return[a[1]||0,a[2]||0]}));return e}w(b,c);b.prototype.getField=function(a){void 0===a&&(a=!0);var d=this.hitZone;if(d){var b=a?this.padding:[0,0,0,0];d=d.coordinates[0];var e=d.map(function(a){return a[0]}),g=d.map(function(a){return a[1]});d=Math.min.apply(0,e)+b[3];e=Math.max.apply(0,e)-b[1];var k=Math.min.apply(0,g)+b[0];b=Math.max.apply(0,g)-b[2];if(n(d)&&n(k))return{x:d,y:k,width:e-d,height:b-k}}return c.prototype.getField.call(this,a)};b.prototype.getHitZone=function(){var a=
this.chart,d=this.mapView,c=this.options,b=(c.field||{}).coordinates;if(b){b=b[0];if("percent"===c.units){var e="mapBoundingBox"===c.relativeTo&&d.getMapBBox()||A(a.plotBox,{x:0,y:0});b=b.map(function(a){return[z("".concat(a[0],"%"),e.width,e.x),z("".concat(a[1],"%"),e.height,e.y)]})}return{type:"Polygon",coordinates:[b]}}};b.prototype.getProjectedBounds=function(){return E.compositeBounds(this.allBounds)};b.prototype.isInside=function(a){var c=this.geoBoundsProjectedBox,b=this.geoBoundsProjectedPolygon;
return!!(c&&a.x>=c.x1&&a.x<=c.x2&&a.y>=c.y1&&a.y<=c.y2&&b&&d(a,b))};b.prototype.render=function(){var a=this.chart,d=this.mapView,c=this.options,b=c.borderPath||c.field;if(b&&d.group){var e=!0;this.border||(this.border=a.renderer.path().addClass("highcharts-mapview-inset-border").add(d.group),e=!1);a.styledMode||this.border.attr({stroke:c.borderColor,"stroke-width":c.borderWidth});var g=Math.round(this.border.strokeWidth())%2/2,k="mapBoundingBox"===c.relativeTo&&d.getMapBBox()||d.playingField;d=(b.coordinates||
[]).reduce(function(d,b){return b.reduce(function(d,b,e){var h=b[0];b=b[1];"percent"===c.units&&(h=a.plotLeft+z("".concat(h,"%"),k.width,k.x),b=a.plotTop+z("".concat(b,"%"),k.height,k.y));h=Math.floor(h)+g;b=Math.floor(b)+g;d.push(0===e?["M",h,b]:["L",h,b]);return d},d)},[]);this.border[e?"animate":"attr"]({d:d})}};b.prototype.destroy=function(){this.border&&(this.border=this.border.destroy());this.eventsToUnbind.forEach(function(a){return a()})};b.prototype.setUpEvents=function(){};return b}(E);
u(m,"afterInit",function(){this.mapView=new E(this,this.options.mapView)});return E});x(b,"Series/Map/MapSeries.js",[b["Core/Animation/AnimationUtilities.js"],b["Series/ColorMapComposition.js"],b["Series/CenteredUtilities.js"],b["Core/Globals.js"],b["Core/Chart/MapChart.js"],b["Series/Map/MapPoint.js"],b["Maps/MapView.js"],b["Core/Series/Series.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Renderer/SVG/SVGRenderer.js"],b["Core/Utilities.js"]],function(b,f,q,m,p,l,e,y,w,h,r){var c=this&&this.__extends||
function(){function a(d,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,d){a.__proto__=d}||function(a,d){for(var c in d)Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])};return a(d,c)}return function(d,c){function b(){this.constructor=d}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");a(d,c);d.prototype=null===c?Object.create(c):(b.prototype=c.prototype,new b)}}(),a=b.animObject,d=b.stop;b=m.noop;
var u=p.splitPath;p=w.seriesTypes;var k=p.column,g=p.scatter;p=r.extend;var C=r.find,n=r.fireEvent,H=r.getNestedProperty,B=r.isArray,A=r.defined,t=r.isNumber,z=r.isObject,E=r.merge,K=r.objectEach,J=r.pick,v=r.splat;r=function(b){function f(){var a=null!==b&&b.apply(this,arguments)||this;a.chart=void 0;a.data=void 0;a.group=void 0;a.joinBy=void 0;a.options=void 0;a.points=void 0;a.processedData=[];return a}c(f,b);f.prototype.animate=function(d){var c=this.chart,b=this.group,e=a(this.options.animation);
d?b.attr({translateX:c.plotLeft+c.plotWidth/2,translateY:c.plotTop+c.plotHeight/2,scaleX:.001,scaleY:.001}):b.animate({translateX:c.plotLeft,translateY:c.plotTop,scaleX:1,scaleY:1},e)};f.prototype.clearBounds=function(){this.points.forEach(function(a){delete a.bounds;delete a.insetIndex;delete a.projectedPath});delete this.bounds};f.prototype.doFullTranslate=function(){return!(!this.isDirtyData&&!this.chart.isResizing&&this.hasRendered)};f.prototype.drawMapDataLabels=function(){y.prototype.drawDataLabels.call(this);
this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)};f.prototype.drawPoints=function(){var c=this,b=this,e=this.chart,g=this.group,h=this.transformGroups,f=void 0===h?[]:h,n=e.mapView,l=e.renderer;n&&(this.transformGroups=f,f[0]||(f[0]=l.g().add(g)),n.insets.forEach(function(a,d){f[d+1]||f.push(l.g().add(g))}),this.doFullTranslate()&&(this.points.forEach(function(a){var d=a.graphic,b=a.shapeArgs;a.group=f["number"===typeof a.insetIndex?a.insetIndex+1:0];d&&d.parentGroup!==a.group&&
d.add(a.group);b&&e.hasRendered&&!e.styledMode&&(b.fill=c.pointAttribs(a,a.state).fill)}),k.prototype.drawPoints.apply(this),this.points.forEach(function(a){var d=a.graphic;if(d){var g=d.animate,k="";a.name&&(k+="highcharts-name-"+a.name.replace(/ /g,"-").toLowerCase());a.properties&&a.properties["hc-key"]&&(k+=" highcharts-key-"+a.properties["hc-key"].toString().toLowerCase());k&&d.addClass(k);e.styledMode&&d.css(c.pointAttribs(a,a.selected&&"select"||void 0));d.animate=function(a,c,k){var h=t(a["stroke-width"])&&
!t(d["stroke-width"]),f=t(d["stroke-width"])&&!t(a["stroke-width"]);if(h||f){var n=J(b.getStrokeWidth(b.options),1)/(e.mapView&&e.mapView.getScale()||1);h&&(d["stroke-width"]=n);f&&(a["stroke-width"]=n)}return g.call(d,a,c,f?function(){d.element.removeAttribute("stroke-width");delete d["stroke-width"];k&&k.apply(this,arguments)}:k)}}})),f.forEach(function(g,k){function h(a){(b.points||[]).forEach(function(d){var b=d.graphic,e;b&&b["stroke-width"]&&(e=c.getStrokeWidth(d.options))&&b.attr({"stroke-width":e/
a})})}var f=(0===k?n:n.insets[k-1]).getSVGTransform(),t=J(c.getStrokeWidth(c.options),1),u=f.scaleX,m=0<f.scaleY?1:-1;if(l.globalAnimation&&e.hasRendered&&n.allowTransformAnimation){var p=Number(g.attr("translateX")),r=Number(g.attr("translateY")),z=Number(g.attr("scaleX")),q=function(a,d){a=z+(u-z)*d.pos;g.attr({translateX:p+(f.translateX-p)*d.pos,translateY:r+(f.translateY-r)*d.pos,scaleX:a,scaleY:a*m,"stroke-width":t/a});h(a)};k=E(a(l.globalAnimation));var v=k.step;k.step=function(a){v&&v.apply(this,
arguments);q.apply(this,arguments)};g.attr({animator:0}).animate({animator:1},k,function(){"boolean"!==typeof l.globalAnimation&&l.globalAnimation.complete&&l.globalAnimation.complete({applyDrilldown:!0})})}else d(g),g.attr(E(f,{"stroke-width":t/u})),h(u)}),this.isDrilling||this.drawMapDataLabels())};f.prototype.getProjectedBounds=function(){if(!this.bounds&&this.chart.mapView){var a=this.chart.mapView,d=a.insets,c=a.projection,b=[];(this.points||[]).forEach(function(a){if(a.path||a.geometry){"string"===
typeof a.path?a.path=u(a.path):B(a.path)&&"M"===a.path[0]&&(a.path=h.prototype.pathToSegments(a.path));if(!a.bounds){var e=a.getProjectedBounds(c);if(e){a.labelrank=J(a.labelrank,(e.x2-e.x1)*(e.y2-e.y1));var g=e.midX,k=e.midY;if(d&&t(g)&&t(k)){var f=C(d,function(a){return a.isInside({x:g,y:k})});f&&(delete a.projectedPath,(e=a.getProjectedBounds(f.projection))&&f.allBounds.push(e),a.insetIndex=d.indexOf(f))}a.bounds=e}}a.bounds&&void 0===a.insetIndex&&b.push(a.bounds)}});this.bounds=e.compositeBounds(b)}return this.bounds};
f.prototype.getStrokeWidth=function(a){var d=this.pointAttrToOptions;return a[d&&d["stroke-width"]||"borderWidth"]};f.prototype.hasData=function(){return!!this.processedXData.length};f.prototype.pointAttribs=function(a,d){var c,b=a.series.chart,e=b.mapView;b=b.styledMode?this.colorAttribs(a):k.prototype.pointAttribs.call(this,a,d);var g=this.getStrokeWidth(a.options);if(d){d=E(this.options.states[d],a.options.states&&a.options.states[d]||{});var h=this.getStrokeWidth(d);A(h)&&(g=h);b.stroke=null!==
(c=d.borderColor)&&void 0!==c?c:a.color}g&&e&&(g/=e.getScale());c=this.getStrokeWidth(this.options);b.dashstyle&&e&&t(c)&&(g=c/e.getScale());a.visible||(b.fill=this.options.nullColor);A(g)?b["stroke-width"]=g:delete b["stroke-width"];b["stroke-linecap"]=b["stroke-linejoin"]=this.options.linecap;return b};f.prototype.updateData=function(){return this.processedData?!1:b.prototype.updateData.apply(this,arguments)};f.prototype.setData=function(a,d,c,e){void 0===d&&(d=!0);delete this.bounds;b.prototype.setData.call(this,
a,!1,void 0,e);this.processData();this.generatePoints();d&&this.chart.redraw(c)};f.prototype.processData=function(){var a=this.options,d=a.data,c=this.chart.options.chart,b=this.joinBy,e=a.keys||this.pointArrayMap,g=[],k={},h=this.chart.mapView;h=h&&(z(a.mapData,!0)?h.getGeoMap(a.mapData):h.geoMap);var f=this.chart.mapTransforms;(this.chart.mapTransforms=f=c.mapTransforms||h&&h["hc-transform"]||f)&&K(f,function(a){a.rotation&&(a.cosAngle=Math.cos(a.rotation),a.sinAngle=Math.sin(a.rotation))});if(B(a.mapData))var n=
a.mapData;else h&&"FeatureCollection"===h.type&&(this.mapTitle=h.title,n=m.geojson(h,this.type,this));var u=this.processedData=[];d&&d.forEach(function(c,g){var k=0;if(t(c))u[g]={value:c};else if(B(c)){u[g]={};!a.keys&&c.length>e.length&&"string"===typeof c[0]&&(u[g]["hc-key"]=c[0],++k);for(var h=0;h<e.length;++h,++k)e[h]&&"undefined"!==typeof c[k]&&(0<e[h].indexOf(".")?l.prototype.setNestedProperty(u[g],c[k],e[h]):u[g][e[h]]=c[k])}else u[g]=d[g];b&&"_i"===b[0]&&(u[g]._i=g)});if(n){this.mapData=n;
this.mapMap={};for(f=0;f<n.length;f++)c=n[f],h=c.properties,c._i=f,b[0]&&h&&h[b[0]]&&(c[b[0]]=h[b[0]]),k[c[b[0]]]=c;this.mapMap=k;if(b[1]){var p=b[1];u.forEach(function(a){a=H(p,a);k[a]&&g.push(k[a])})}if(a.allAreas){if(b[1]){var r=b[1];u.forEach(function(a){g.push(H(r,a))})}var q="|"+g.map(function(a){return a&&a[b[0]]}).join("|")+"|";n.forEach(function(a){b[0]&&-1!==q.indexOf("|"+a[b[0]]+"|")||u.push(E(a,{value:null}))})}}this.processedXData=Array(u.length)};f.prototype.setOptions=function(a){a=
y.prototype.setOptions.call(this,a);var d=a.joinBy;null===d&&(d="_i");d=this.joinBy=v(d);d[1]||(d[1]=d[0]);return a};f.prototype.translate=function(){var a=this.doFullTranslate(),d=this.chart.mapView,c=d&&d.projection;!this.chart.hasRendered||!this.isDirtyData&&this.hasRendered||(this.processData(),this.generatePoints(),delete this.bounds,!d||d.userOptions.center||t(d.userOptions.zoom)||d.zoom!==d.minZoom?this.getProjectedBounds():d.fitToBounds(void 0,void 0,!1));if(d){var b=d.getSVGTransform();this.points.forEach(function(e){var g=
t(e.insetIndex)&&d.insets[e.insetIndex].getSVGTransform()||b;g&&e.bounds&&t(e.bounds.midX)&&t(e.bounds.midY)&&(e.plotX=e.bounds.midX*g.scaleX+g.translateX,e.plotY=e.bounds.midY*g.scaleY+g.translateY);a&&(e.shapeType="path",e.shapeArgs={d:l.getProjectedPath(e,c)});e.projectedPath&&!e.projectedPath.length?e.setVisible(!1):e.visible||e.setVisible(!0)})}n(this,"afterTranslate")};f.defaultOptions=E(g.defaultOptions,{affectsMapView:!0,animation:!1,dataLabels:{crop:!1,formatter:function(){var a=this.series.chart.numberFormatter,
d=this.point.value;return t(d)?a(d,-1):""},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},linecap:"round",marker:null,nullColor:"#f7f7f7",stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:"{point.name}: {point.value}<br/>"},turboThreshold:0,allAreas:!0,borderColor:"#e6e6e6",borderWidth:1,joinBy:"hc-key",states:{hover:{halo:void 0,borderColor:"#666666",borderWidth:2},normal:{animation:!0},select:{color:"#cccccc"}},legendSymbol:"rectangle"});return f}(g);p(r.prototype,{type:"map",axisTypes:f.seriesMembers.axisTypes,
colorAttribs:f.seriesMembers.colorAttribs,colorKey:f.seriesMembers.colorKey,directTouch:!0,drawDataLabels:b,drawGraph:b,forceDL:!0,getCenter:q.getCenter,getExtremesFromAll:!0,getSymbol:b,isCartesian:!1,parallelArrays:f.seriesMembers.parallelArrays,pointArrayMap:f.seriesMembers.pointArrayMap,pointClass:l,preserveAspectRatio:!0,searchPoint:b,trackerGroups:f.seriesMembers.trackerGroups,useMapGeometry:!0});f.compose(r);w.registerSeriesType("map",r);"";return r});x(b,"Series/MapLine/MapLineSeries.js",
[b["Series/Map/MapSeries.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,f,q){var m=this&&this.__extends||function(){function b(e,f){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,e){b.__proto__=e}||function(b,e){for(var c in e)Object.prototype.hasOwnProperty.call(e,c)&&(b[c]=e[c])};return b(e,f)}return function(e,f){function h(){this.constructor=e}if("function"!==typeof f&&null!==f)throw new TypeError("Class extends value "+String(f)+" is not a constructor or null");
b(e,f);e.prototype=null===f?Object.create(f):(h.prototype=f.prototype,new h)}}(),p=q.extend,l=q.merge;q=function(e){function f(){var b=null!==e&&e.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}m(f,e);f.prototype.pointAttribs=function(e,h){e=b.prototype.pointAttribs.call(this,e,h);e.fill=this.options.fillColor;return e};f.defaultOptions=l(b.defaultOptions,{lineWidth:1,fillColor:"none",legendSymbol:"lineMarker"});return f}(b);p(q.prototype,{type:"mapline",colorProp:"stroke",
pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"}});f.registerSeriesType("mapline",q);"";return q});x(b,"Series/MapPoint/MapPointPoint.js",[b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,f){var q=this&&this.__extends||function(){function b(f,e){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,e){b.__proto__=e}||function(b,e){for(var h in e)Object.prototype.hasOwnProperty.call(e,h)&&(b[h]=e[h])};return b(f,e)}return function(f,e){function l(){this.constructor=
f}if("function"!==typeof e&&null!==e)throw new TypeError("Class extends value "+String(e)+" is not a constructor or null");b(f,e);f.prototype=null===e?Object.create(e):(l.prototype=e.prototype,new l)}}(),m=f.isNumber;return function(b){function f(){var e=null!==b&&b.apply(this,arguments)||this;e.options=void 0;e.series=void 0;return e}q(f,b);f.prototype.isValid=function(){return!!(this.options.geometry||m(this.x)&&m(this.y)||m(this.options.lon)&&m(this.options.lat))};return f}(b.seriesTypes.scatter.prototype.pointClass)});
x(b,"Series/MapPoint/MapPointSeries.js",[b["Core/Globals.js"],b["Series/MapPoint/MapPointPoint.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Renderer/SVG/SVGRenderer.js"],b["Core/Utilities.js"]],function(b,f,q,m,p){var l=this&&this.__extends||function(){function a(d,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,d){a.__proto__=d}||function(a,d){for(var b in d)Object.prototype.hasOwnProperty.call(d,b)&&(a[b]=d[b])};return a(d,b)}return function(d,b){function c(){this.constructor=
d}if("function"!==typeof b&&null!==b)throw new TypeError("Class extends value "+String(b)+" is not a constructor or null");a(d,b);d.prototype=null===b?Object.create(b):(c.prototype=b.prototype,new c)}}();b=b.noop;var e=q.seriesTypes,y=e.map,w=e.scatter;e=p.extend;var h=p.fireEvent,r=p.isNumber,c=p.merge;p=function(a){function d(){var d=null!==a&&a.apply(this,arguments)||this;d.chart=void 0;d.data=void 0;d.options=void 0;d.points=void 0;d.clearBounds=y.prototype.clearBounds;return d}l(d,a);d.prototype.drawDataLabels=
function(){a.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)};d.prototype.projectPoint=function(a){var d=this.chart.mapView;if(d){var b=a.geometry,c=a.lon;a=a.lat;b=b&&"Point"===b.type&&b.coordinates;r(c)&&r(a)&&(b=[c,a]);if(b)return d.lonLatToProjectedUnits({lon:b[0],lat:b[1]})}};d.prototype.translate=function(){var a=this,d=this.chart.mapView;this.processedXData||this.processData();this.generatePoints();this.getProjectedBounds&&this.isDirtyData&&
(delete this.bounds,this.getProjectedBounds());if(d){var b=d.getSVGTransform(),c=d.projection.hasCoordinates;this.points.forEach(function(e){var g=e.x;g=void 0===g?void 0:g;var k=e.y;k=void 0===k?void 0:k;var h=r(e.insetIndex)&&d.insets[e.insetIndex].getSVGTransform()||b,f=a.projectPoint(e.options)||e.properties&&a.projectPoint(e.properties);if(f)g=f.x,k=f.y;else if(e.bounds&&(g=e.bounds.midX,k=e.bounds.midY,h&&r(g)&&r(k))){e.plotX=g*h.scaleX+h.translateX;e.plotY=k*h.scaleY+h.translateY;var n=!0}r(g)&&
r(k)?n||(n=d.projectedUnitsToPixels({x:g,y:k}),e.plotX=n.x,e.plotY=c?n.y:a.chart.plotHeight-n.y):e.y=e.plotX=e.plotY=void 0;e.isInside=a.isPointInside(e);e.zone=a.zones.length?e.getZone():void 0})}h(this,"afterTranslate")};d.defaultOptions=c(w.defaultOptions,{dataLabels:{crop:!1,defer:!1,enabled:!0,formatter:function(){return this.point.name},overflow:!1,style:{color:"#000000"}},legendSymbol:"lineMarker"});return d}(w);m.prototype.symbols.mapmarker=function(a,d,b,c,e){var g=e&&"legend"===e.context;
g?(a+=b/2,e=d+c):e&&"number"===typeof e.anchorX&&"number"===typeof e.anchorY?(a=e.anchorX,e=e.anchorY):(a+=b/2,e=d+c/2,d-=c);c=g?c/3:c/2;return[["M",a,e],["C",a,e,a-c,d+1.5*c,a-c,d+c],["A",c,c,1,1,1,a+c,d+c],["C",a+c,d+1.5*c,a,e,a,e],["Z"]]};e(p.prototype,{type:"mappoint",axisTypes:["colorAxis"],forceDL:!0,isCartesian:!1,pointClass:f,searchPoint:b,useMapGeometry:!0});q.registerSeriesType("mappoint",p);"";return p});x(b,"Series/Bubble/BubbleLegendDefaults.js",[],function(){return{borderColor:void 0,
borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:"0.9em",color:"#000000"},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}});x(b,"Series/Bubble/BubbleLegendItem.js",[b["Core/Color/Color.js"],
b["Core/Templating.js"],b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,f,q,m){var p=b.parse,l=q.noop,e=m.arrayMax,y=m.arrayMin,w=m.isNumber,h=m.merge,r=m.pick,c=m.stableSort;b=function(){function a(a,b){this.options=this.symbols=this.visible=this.selected=this.ranges=this.movementX=this.maxLabel=this.legend=this.chart=void 0;this.setState=l;this.init(a,b)}a.prototype.init=function(a,b){this.options=a;this.visible=!0;this.chart=b.chart;this.legend=b};a.prototype.addToLegend=function(a){a.splice(this.options.legendIndex,
0,this)};a.prototype.drawLegendSymbol=function(a){var d=r(a.options.itemDistance,20),b=this.legendItem||{},e=this.options,h=e.ranges,f=e.connectorDistance;if(h&&h.length&&w(h[0].value)){c(h,function(a,d){return d.value-a.value});this.ranges=h;this.setOptions();this.render();a=this.getMaxLabelSize();var l=this.ranges[0].radius;h=2*l;f=f-l+a.width;f=0<f?f:0;this.maxLabel=a;this.movementX="left"===e.labels.align?f:0;b.labelWidth=h+f+d;b.labelHeight=h+a.height/2}else a.options.bubbleLegend.autoRanges=
!0};a.prototype.setOptions=function(){var a=this.ranges,b=this.options,c=this.chart.series[b.seriesIndex],e=this.legend.baseline,f={zIndex:b.zIndex,"stroke-width":b.borderWidth},n={zIndex:b.zIndex,"stroke-width":b.connectorWidth},l={align:this.legend.options.rtl||"left"===b.labels.align?"right":"left",zIndex:b.zIndex},m=c.options.marker.fillOpacity,q=this.chart.styledMode;a.forEach(function(d,g){q||(f.stroke=r(d.borderColor,b.borderColor,c.color),f.fill=r(d.color,b.color,1!==m?p(c.color).setOpacity(m).get("rgba"):
c.color),n.stroke=r(d.connectorColor,b.connectorColor,c.color));a[g].radius=this.getRangeRadius(d.value);a[g]=h(a[g],{center:a[0].radius-a[g].radius+e});q||h(!0,a[g],{bubbleAttribs:h(f),connectorAttribs:h(n),labelAttribs:l})},this)};a.prototype.getRangeRadius=function(a){var d=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,d.ranges[d.ranges.length-1].value,d.ranges[0].value,d.minSize,d.maxSize,a)};a.prototype.render=function(){var a=this.legendItem||{},b=this.chart.renderer,
c=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});a.symbol=b.g("bubble-legend");a.label=b.g("bubble-legend-item").css(this.legend.itemStyle||{});a.symbol.translateX=0;a.symbol.translateY=0;a.symbol.add(a.label);a.label.add(a.group);a=0;for(b=this.ranges;a<b.length;a++){var e=b[a];e.value>=c&&this.renderRange(e)}this.hideOverlappingLabels()};a.prototype.renderRange=function(a){var b=this.options,d=b.labels,c=this.chart,e=c.series[b.seriesIndex],h=c.renderer,
f=this.symbols;c=f.labels;var l=a.center,m=Math.abs(a.radius),t=b.connectorDistance||0,p=d.align,r=b.connectorWidth,q=this.ranges[0].radius||0,w=l-m-b.borderWidth/2+r/2,v=h.styledMode;t=this.legend.options.rtl||"left"===p?-t:t;"center"===p&&(t=0,b.connectorDistance=0,a.labelAttribs.align="center");f.bubbleItems.push(h.circle(q,l+((w%1?1:.5)-(r%2?0:.5)),m).attr(v?{}:a.bubbleAttribs).addClass((v?"highcharts-color-"+e.colorIndex+" ":"")+"highcharts-bubble-legend-symbol "+(b.className||"")).add(this.legendItem.symbol));
f.connectors.push(h.path(h.crispLine([["M",q,w],["L",q+t,w]],b.connectorWidth)).attr(v?{}:a.connectorAttribs).addClass((v?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(b.connectorClassName||"")).add(this.legendItem.symbol));a=h.text(this.formatLabel(a)).attr(v?{}:a.labelAttribs).css(v?{}:d.style).addClass("highcharts-bubble-legend-labels "+(b.labels.className||"")).add(this.legendItem.symbol);b={x:q+t+b.labels.x,y:w+b.labels.y+.4*a.getBBox().height};
a.attr(b);c.push(a);a.placed=!0;a.alignAttr=b};a.prototype.getMaxLabelSize=function(){var a,b;this.symbols.labels.forEach(function(d){b=d.getBBox(!0);a=a?b.width>a.width?b:a:b});return a||{}};a.prototype.formatLabel=function(a){var b=this.options,d=b.labels.formatter;b=b.labels.format;var c=this.chart.numberFormatter;return b?f.format(b,a):d?d.call(a):c(a.value,1)};a.prototype.hideOverlappingLabels=function(){var a=this.chart,b=this.symbols;!this.options.labels.allowOverlap&&b&&(a.hideOverlappingLabels(b.labels),
b.labels.forEach(function(a,d){a.newOpacity?a.newOpacity!==a.oldOpacity&&b.connectors[d].show():b.connectors[d].hide()}))};a.prototype.getRanges=function(){var a=this.legend.bubbleLegend,b=a.options.ranges,c,g=Number.MAX_VALUE,f=-Number.MAX_VALUE;a.chart.series.forEach(function(a){a.isBubble&&!a.ignoreSeries&&(c=a.zData.filter(w),c.length&&(g=r(a.options.zMin,Math.min(g,Math.max(y(c),!1===a.options.displayNegative?a.options.zThreshold:-Number.MAX_VALUE))),f=r(a.options.zMax,Math.max(f,e(c)))))});
var l=g===f?[{value:f}]:[{value:g},{value:(g+f)/2},{value:f,autoRanges:!0}];b.length&&b[0].radius&&l.reverse();l.forEach(function(a,d){b&&b[d]&&(l[d]=h(b[d],a))});return l};a.prototype.predictBubbleSizes=function(){var a=this.chart,b=a.legend.options,c=b.floating,e=(b="horizontal"===b.layout)?a.legend.lastLineHeight:0,f=a.plotSizeX,h=a.plotSizeY,l=a.series[this.options.seriesIndex],m=l.getPxExtremes();a=Math.ceil(m.minPxSize);m=Math.ceil(m.maxPxSize);var p=Math.min(h,f);l=l.options.maxSize;if(c||
!/%$/.test(l))c=m;else if(l=parseFloat(l),c=(p+e)*l/100/(l/100+1),b&&h-c>=f||!b&&f-c>=h)c=m;return[a,Math.ceil(c)]};a.prototype.updateRanges=function(a,b){var c=this.legend.options.bubbleLegend;c.minSize=a;c.maxSize=b;c.ranges=this.getRanges()};a.prototype.correctSizes=function(){var a=this.legend,b=this.chart.series[this.options.seriesIndex].getPxExtremes();1<Math.abs(Math.ceil(b.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,b.maxPxSize),a.render())};return a}();"";return b});
x(b,"Series/Bubble/BubbleLegendComposition.js",[b["Series/Bubble/BubbleLegendDefaults.js"],b["Series/Bubble/BubbleLegendItem.js"],b["Core/Defaults.js"],b["Core/Utilities.js"]],function(b,f,q,m){function p(b,c,d){var g=this.legend,f=0<=l(this),k;if(g&&g.options.enabled&&g.bubbleLegend&&g.options.bubbleLegend.autoRanges&&f){var m=g.bubbleLegend.options;f=g.bubbleLegend.predictBubbleSizes();g.bubbleLegend.updateRanges(f[0],f[1]);m.placed||(g.group.placed=!1,g.allItems.forEach(function(a){k=a.legendItem||
{};k.group&&(k.group.translateY=null)}));g.render();this.getMargins();this.axes.forEach(function(b){b.visible&&b.render();m.placed||(b.setScale(),b.updateNames(),a(b.ticks,function(a){a.isNew=!0;a.isNewLabel=!0}))});m.placed=!0;this.getMargins();b.call(this,c,d);g.bubbleLegend.correctSizes();h(g,e(g))}else b.call(this,c,d),g&&g.options.enabled&&g.bubbleLegend&&(g.render(),h(g,e(g)))}function l(a){a=a.series;for(var b=0;b<a.length;){if(a[b]&&a[b].isBubble&&a[b].visible&&a[b].zData.length)return b;
b++}return-1}function e(a){a=a.allItems;var b=[],c=a.length,d,e=0;for(d=0;d<c;d++){var f=a[d].legendItem||{};var h=(a[d+1]||{}).legendItem||{};f.labelHeight&&(a[d].itemHeight=f.labelHeight);if(a[d]===a[c-1]||f.y!==h.y){b.push({height:0});f=b[b.length-1];for(e;e<=d;e++)a[e].itemHeight>f.height&&(f.height=a[e].itemHeight);f.step=d}}return b}function y(a){var b=this.bubbleLegend,c=this.options,d=c.bubbleLegend,e=l(this.chart);b&&b.ranges&&b.ranges.length&&(d.ranges.length&&(d.autoRanges=!!d.ranges[0].autoRanges),
this.destroyItem(b));0<=e&&c.enabled&&d.enabled&&(d.seriesIndex=e,this.bubbleLegend=new f(d,this),this.bubbleLegend.addToLegend(a.allItems))}function w(a){if(a.defaultPrevented)return!1;var b=this.chart;a=this.visible;var c=this.chart.legend;c&&c.bubbleLegend&&(this.visible=!a,this.ignoreSeries=a,b=0<=l(b),c.bubbleLegend.visible!==b&&(c.update({bubbleLegend:{enabled:b}}),c.bubbleLegend.visible=b),this.visible=a)}function h(a,b){var c=a.options.rtl,d,e,g,f,h=0;a.allItems.forEach(function(a,k){f=a.legendItem||
{};if(f.group){d=f.group.translateX||0;e=f.y||0;if((g=a.movementX)||c&&a.ranges)g=c?d-a.options.maxSize/2:d+g,f.group.attr({translateX:g});k>b[h].step&&h++;f.group.attr({translateY:Math.round(e+b[h].height/2)});f.y=e+b[h].height/2}})}var r=q.setOptions,c=m.addEvent,a=m.objectEach,d=m.wrap,u=[];return{compose:function(a,e,f){m.pushUnique(u,a)&&(r({legend:{bubbleLegend:b}}),d(a.prototype,"drawChartBox",p));m.pushUnique(u,e)&&c(e,"afterGetAllItems",y);m.pushUnique(u,f)&&c(f,"legendItemClick",w)}}});
x(b,"Series/Bubble/BubblePoint.js",[b["Core/Series/Point.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,f,q){var m=this&&this.__extends||function(){function b(f,e){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,e){b.__proto__=e}||function(b,e){for(var f in e)Object.prototype.hasOwnProperty.call(e,f)&&(b[f]=e[f])};return b(f,e)}return function(f,e){function l(){this.constructor=f}if("function"!==typeof e&&null!==e)throw new TypeError("Class extends value "+
String(e)+" is not a constructor or null");b(f,e);f.prototype=null===e?Object.create(e):(l.prototype=e.prototype,new l)}}();q=q.extend;f=function(f){function l(){var b=null!==f&&f.apply(this,arguments)||this;b.options=void 0;b.series=void 0;return b}m(l,f);l.prototype.haloPath=function(e){return b.prototype.haloPath.call(this,0===e?0:(this.marker?this.marker.radius||0:0)+e)};return l}(f.seriesTypes.scatter.prototype.pointClass);q(f.prototype,{ttBelow:!1});return f});x(b,"Series/Bubble/BubbleSeries.js",
[b["Series/Bubble/BubbleLegendComposition.js"],b["Series/Bubble/BubblePoint.js"],b["Core/Color/Color.js"],b["Core/Globals.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,f,q,m,p,l){function e(){var a=this,b=this.len,c=this.chart,d=this.isXAxis,e=d?"xData":"yData",f=this.min,h=this.max-f,k=0,l=b,m=b/h,r;this.series.forEach(function(b){if(b.bubblePadding&&(b.visible||!c.options.chart.ignoreHiddenSeries)){r=a.allowZoomOutside=!0;var t=b[e];d&&((b.onPoint||b).getRadii(0,0,b),
b.onPoint&&(b.radii=b.onPoint.radii));if(0<h)for(var n=t.length;n--;)if(g(t[n])&&a.dataMin<=t[n]&&t[n]<=a.max){var p=b.radii&&b.radii[n]||0;k=Math.min((t[n]-f)*m-p,k);l=Math.max((t[n]-f)*m+p,l)}}});r&&0<h&&!this.logarithmic&&(l-=b,m*=(b+Math.max(0,k)-Math.min(l,b))/b,[["min","userMin",k],["max","userMax",l]].forEach(function(b){"undefined"===typeof n(a.options[b[0]],a[b[1]])&&(a[b[0]]+=b[2]/m)}))}var y=this&&this.__extends||function(){function a(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof
Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};return a(b,c)}return function(b,c){function d(){this.constructor=b}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),w=q.parse;q=m.noop;var h=p.series,r=p.seriesTypes;m=r.column.prototype;var c=r.scatter;r=l.addEvent;var a=l.arrayMax,
d=l.arrayMin,u=l.clamp,k=l.extend,g=l.isNumber,x=l.merge,n=l.pick,J=[],B=function(f){function t(){var a=null!==f&&f.apply(this,arguments)||this;a.data=void 0;a.maxPxSize=void 0;a.minPxSize=void 0;a.options=void 0;a.points=void 0;a.radii=void 0;a.yData=void 0;a.zData=void 0;return a}y(t,f);t.compose=function(a,c,d,f){b.compose(c,d,f);l.pushUnique(J,a)&&(a.prototype.beforePadding=e)};t.prototype.animate=function(a){!a&&this.points.length<this.options.animationLimit&&this.points.forEach(function(a){var b=
a.graphic;b&&b.width&&(this.hasRendered||b.attr({x:a.plotX,y:a.plotY,width:1,height:1}),b.animate(this.markerAttribs(a),this.options.animation))},this)};t.prototype.getRadii=function(){var a=this,b=this.zData,c=this.yData,d=[],e=this.chart.bubbleZExtremes;var f=this.getPxExtremes();var g=f.minPxSize,h=f.maxPxSize;if(!e){var k=Number.MAX_VALUE,l=-Number.MAX_VALUE,t;this.chart.series.forEach(function(b){b.bubblePadding&&(b.visible||!a.chart.options.chart.ignoreHiddenSeries)&&(b=(b.onPoint||b).getZExtremes())&&
(k=Math.min(n(k,b.zMin),b.zMin),l=Math.max(n(l,b.zMax),b.zMax),t=!0)});t?(e={zMin:k,zMax:l},this.chart.bubbleZExtremes=e):e={zMin:0,zMax:0}}var m=0;for(f=b.length;m<f;m++){var r=b[m];d.push(this.getRadius(e.zMin,e.zMax,g,h,r,c&&c[m]))}this.radii=d};t.prototype.getRadius=function(a,b,c,d,e,f){var h=this.options,k="width"!==h.sizeBy,l=h.zThreshold,m=b-a,t=.5;if(null===f||null===e)return null;if(g(e)){h.sizeByAbsoluteValue&&(e=Math.abs(e-l),m=Math.max(b-l,Math.abs(a-l)),a=0);if(e<a)return c/2-1;0<m&&
(t=(e-a)/m)}k&&0<=t&&(t=Math.sqrt(t));return Math.ceil(c+t*(d-c))/2};t.prototype.hasData=function(){return!!this.processedXData.length};t.prototype.pointAttribs=function(a,b){var c=this.options.marker.fillOpacity;a=h.prototype.pointAttribs.call(this,a,b);1!==c&&(a.fill=w(a.fill).setOpacity(c).get("rgba"));return a};t.prototype.translate=function(){f.prototype.translate.call(this);this.getRadii();this.translateBubble()};t.prototype.translateBubble=function(){for(var a=this.data,b=this.options,c=this.radii,
d=this.getPxExtremes().minPxSize,e=a.length;e--;){var f=a[e],h=c?c[e]:0;"z"===this.zoneAxis&&(f.negative=(f.z||0)<(b.zThreshold||0));g(h)&&h>=d/2?(f.marker=k(f.marker,{radius:h,width:2*h,height:2*h}),f.dlBox={x:f.plotX-h,y:f.plotY-h,width:2*h,height:2*h}):(f.shapeArgs=f.plotY=f.dlBox=void 0,f.isInside=!1)}};t.prototype.getPxExtremes=function(){function a(a){if("string"===typeof a){var c=/%$/.test(a);a=parseInt(a,10)}return c?b*a/100:a}var b=Math.min(this.chart.plotWidth,this.chart.plotHeight),c=a(n(this.options.minSize,
8)),d=Math.max(a(n(this.options.maxSize,"20%")),c);return{minPxSize:c,maxPxSize:d}};t.prototype.getZExtremes=function(){var b=this.options,c=(this.zData||[]).filter(g);if(c.length){var e=n(b.zMin,u(d(c),!1===b.displayNegative?b.zThreshold||0:-Number.MAX_VALUE,Number.MAX_VALUE));b=n(b.zMax,a(c));if(g(e)&&g(b))return{zMin:e,zMax:b}}};t.defaultOptions=x(c.defaultOptions,{dataLabels:{formatter:function(){var a=this.series.chart.numberFormatter,b=this.point.z;return g(b)?a(b,-1):""},inside:!0,verticalAlign:"middle"},
animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"});return t}(c);k(B.prototype,{alignDataLabel:m.alignDataLabel,applyZones:q,bubblePadding:!0,buildKDTree:q,directTouch:!0,isBubble:!0,pointArrayMap:["y","z"],pointClass:f,parallelArrays:["x","y",
"z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",zoneAxis:"z"});r(B,"updatedData",function(a){delete a.target.chart.bubbleZExtremes});r(B,"remove",function(a){delete a.target.chart.bubbleZExtremes});p.registerSeriesType("bubble",B);"";"";return B});x(b,"Series/MapBubble/MapBubblePoint.js",[b["Series/Bubble/BubblePoint.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,f,q){var m=this&&this.__extends||function(){function b(f,e){b=Object.setPrototypeOf||{__proto__:[]}instanceof
Array&&function(b,e){b.__proto__=e}||function(b,e){for(var f in e)Object.prototype.hasOwnProperty.call(e,f)&&(b[f]=e[f])};return b(f,e)}return function(f,e){function l(){this.constructor=f}if("function"!==typeof e&&null!==e)throw new TypeError("Class extends value "+String(e)+" is not a constructor or null");b(f,e);f.prototype=null===e?Object.create(e):(l.prototype=e.prototype,new l)}}();f=f.seriesTypes.map.prototype.pointClass.prototype;q=q.extend;b=function(b){function f(){return null!==b&&b.apply(this,
arguments)||this}m(f,b);f.prototype.isValid=function(){return"number"===typeof this.z};return f}(b);q(b.prototype,{applyOptions:f.applyOptions,getProjectedBounds:f.getProjectedBounds});return b});x(b,"Series/MapBubble/MapBubbleSeries.js",[b["Series/Bubble/BubbleSeries.js"],b["Series/MapBubble/MapBubblePoint.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,f,q,m){var p=this&&this.__extends||function(){function b(e,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&
function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};return b(e,c)}return function(e,c){function a(){this.constructor=e}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");b(e,c);e.prototype=null===c?Object.create(c):(a.prototype=c.prototype,new a)}}(),l=q.seriesTypes,e=l.map.prototype,y=l.mappoint.prototype;l=m.extend;var w=m.merge;m=function(f){function h(){var b=null!==
f&&f.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;b.clearBounds=e.clearBounds;return b}p(h,f);h.prototype.searchPoint=function(b,a){return this.searchKDTree({clientX:b.chartX-this.chart.plotLeft,plotY:b.chartY-this.chart.plotTop},a,b)};h.prototype.translate=function(){y.translate.call(this);this.getRadii();this.translateBubble()};h.prototype.updateParallelArrays=function(b,a,d){f.prototype.updateParallelArrays.call(this,b,a,d);b=this.processedXData;a=this.xData;b&&a&&
(b.length=a.length)};h.defaultOptions=w(b.defaultOptions,{lineWidth:0,animationLimit:500,joinBy:"hc-key",tooltip:{pointFormat:"{point.name}: {point.z}"}});return h}(b);l(m.prototype,{type:"mapbubble",axisTypes:["colorAxis"],getProjectedBounds:e.getProjectedBounds,isCartesian:!1,pointArrayMap:["z"],pointClass:f,processData:e.processData,projectPoint:y.projectPoint,setData:e.setData,setOptions:e.setOptions,updateData:e.updateData,useMapGeometry:!0,xyFromShape:!0});q.registerSeriesType("mapbubble",m);
"";return m});x(b,"Series/Heatmap/HeatmapPoint.js",[b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,f){var q=this&&this.__extends||function(){function b(e,f){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,c){b.__proto__=c}||function(b,c){for(var a in c)Object.prototype.hasOwnProperty.call(c,a)&&(b[a]=c[a])};return b(e,f)}return function(e,f){function h(){this.constructor=e}if("function"!==typeof f&&null!==f)throw new TypeError("Class extends value "+String(f)+
" is not a constructor or null");b(e,f);e.prototype=null===f?Object.create(f):(h.prototype=f.prototype,new h)}}(),m=f.clamp,p=f.defined,l=f.extend,e=f.pick;b=function(b){function f(){var e=null!==b&&b.apply(this,arguments)||this;e.options=void 0;e.series=void 0;e.value=void 0;e.x=void 0;e.y=void 0;return e}q(f,b);f.prototype.applyOptions=function(e,f){(this.isNull||null===this.value)&&delete this.color;b.prototype.applyOptions.call(this,e,f);this.formatPrefix=this.isNull||null===this.value?"null":
"point";return this};f.prototype.getCellAttributes=function(){var b=this.series,f=b.options,c=(f.colsize||1)/2,a=(f.rowsize||1)/2,d=b.xAxis,l=b.yAxis,k=this.options.marker||b.options.marker;b=b.pointPlacementToXValue();var g=e(this.pointPadding,f.pointPadding,0),q={x1:m(Math.round(d.len-d.translate(this.x-c,!1,!0,!1,!0,-b)),-d.len,2*d.len),x2:m(Math.round(d.len-d.translate(this.x+c,!1,!0,!1,!0,-b)),-d.len,2*d.len),y1:m(Math.round(l.translate(this.y-a,!1,!0,!1,!0)),-l.len,2*l.len),y2:m(Math.round(l.translate(this.y+
a,!1,!0,!1,!0)),-l.len,2*l.len)};[["width","x"],["height","y"]].forEach(function(a){var b=a[0];a=a[1];var c=a+"1",e=a+"2",f=Math.abs(q[c]-q[e]),h=k&&k.lineWidth||0,m=Math.abs(q[c]+q[e])/2;b=k&&k[b];p(b)&&b<f&&(b=b/2+h/2,q[c]=m-b,q[e]=m+b);if(g){if("x"===a&&d.reversed||"y"===a&&!l.reversed)c=e,e=a+"1";q[c]+=g;q[e]-=g}});return q};f.prototype.haloPath=function(b){if(!b)return[];var e=this.shapeArgs||{},c=e.x;c=void 0===c?0:c;var a=e.y;a=void 0===a?0:a;var d=e.width;d=void 0===d?0:d;e=e.height;e=void 0===
e?0:e;return[["M",c-b,a-b],["L",c-b,a+e+b],["L",c+d+b,a+e+b],["L",c+d+b,a-b],["Z"]]};f.prototype.isValid=function(){return Infinity!==this.value&&-Infinity!==this.value};return f}(b.seriesTypes.scatter.prototype.pointClass);l(b.prototype,{dataLabelOnNull:!0,moveToTopOnHover:!0,ttBelow:!1});return b});x(b,"Series/Heatmap/HeatmapSeries.js",[b["Core/Color/Color.js"],b["Series/ColorMapComposition.js"],b["Core/Globals.js"],b["Series/Heatmap/HeatmapPoint.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Renderer/SVG/SVGRenderer.js"],
b["Core/Utilities.js"]],function(b,f,q,m,p,l,e){var y=this&&this.__extends||function(){function a(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};return a(b,c)}return function(b,c){function d(){this.constructor=b}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");a(b,c);b.prototype=null===c?Object.create(c):
(d.prototype=c.prototype,new d)}}(),w=this&&this.__assign||function(){w=Object.assign||function(a){for(var b,c=1,d=arguments.length;c<d;c++){b=arguments[c];for(var e in b)Object.prototype.hasOwnProperty.call(b,e)&&(a[e]=b[e])}return a};return w.apply(this,arguments)},h=q.doc,r=p.series,c=p.seriesTypes;q=c.column;var a=c.scatter,d=l.prototype.symbols,u=e.clamp;l=e.extend;var k=e.fireEvent,g=e.isNumber,x=e.merge,n=e.pick,J=e.defined;e=function(c){function e(){var a=null!==c&&c.apply(this,arguments)||
this;a.canvas=void 0;a.colorAxis=void 0;a.context=void 0;a.data=void 0;a.options=void 0;a.points=void 0;a.valueMax=NaN;a.valueMin=NaN;return a}y(e,c);e.prototype.drawPoints=function(){var a=this,b=a.options,c=b.marker||{};if(b.interpolation){c=a.image;var e=a.chart,d=a.xAxis,f=a.yAxis,g=a.points,h=g.length-1,k=d.len,l=d.reversed,m=f.len,q=f.reversed,p=d.getExtremes(),x=p.min,y=p.max;f=f.getExtremes();var A=f.min,C=f.max;b=[n(b.colsize,1),n(b.rowsize,1)];f=b[0];p=b[1];var B=e.inverted,D=f/2;b=d.userOptions.minPadding;
var F=J(b)&&!(0<b);b=B||F;D=F&&D||0;D=[x-D,y+2*D,x+f].map(function(b){return u(Math.round(d.len-d.translate(b,!1,!0,!1,!0,-a.pointPlacementToXValue())),-d.len,2*d.len)});F=D[0];var I=D[1];I=l?[I,F]:[F,I];F=I[0];I=I[1];D=k/D[2]/2/2/2;k=B?{width:k,height:m,x:0,y:0}:{x:F-D,width:I-D,height:m,y:0};if(!c||a.isDirtyData){var H=e.colorAxis&&e.colorAxis[0];m=a.getContext();if((B=a.canvas)&&m&&H){var N=B.width=~~((y-x)/f)+1;f=B.height=~~((C-A)/p)+1;p=N*f;D=new Uint8ClampedArray(4*p);var P=N-(b&&1||0),Q=f-
1;b=function(a){a=H.toColor(a.value||0,n(a)).split(")")[0].split("(")[1].split(",").map(function(a){return n(parseFloat(a),parseInt(a,10))});a[3]=255*n(a[3],1);return a};var R=l?function(a){return P-a}:function(a){return a},S=q?function(a){return Q-a}:function(a){return a};l=function(a,b){return Math.ceil(N*S(~~((Q-0)/(C-A)*(C-b-A)))+R(~~((P-0)/(y-x)*(a-x))))};a.buildKDTree();a.directTouch=!1;for(q=0;q<p;q++)F=g[~~((h-0)/(D.length-4)*q*4)],I=new Uint8ClampedArray(b(F)),D.set(I,4*l(F.x,F.y));m.putImageData(new ImageData(D,
N,f),0,0);c?c.attr(w(w({},k),{href:B.toDataURL()})):a.image=e.renderer.image(B.toDataURL()).attr(k).add(a.group)}}else c.width===k.width&&c.height===k.height||c.attr(k)}else if(c.enabled||a._hasPointMarkers)r.prototype.drawPoints.call(a),a.points.forEach(function(b){b.graphic&&(b.graphic[a.chart.styledMode?"css":"animate"](a.colorAttribs(b)),null===b.value&&b.graphic.addClass("highcharts-null-point"))})};e.prototype.getContext=function(){var a=this.canvas,b=this.context;if(a&&b)b.clearRect(0,0,a.width,
a.height);else return this.canvas=h.createElement("canvas"),this.context=this.canvas.getContext("2d")||void 0;return b};e.prototype.getExtremes=function(){var a=r.prototype.getExtremes.call(this,this.valueData),b=a.dataMin;a=a.dataMax;g(b)&&(this.valueMin=b);g(a)&&(this.valueMax=a);return r.prototype.getExtremes.call(this)};e.prototype.getValidPoints=function(a,b){return r.prototype.getValidPoints.call(this,a,b,!0)};e.prototype.hasData=function(){return!!this.processedXData.length};e.prototype.init=
function(){c.prototype.init.apply(this,arguments);var a=this.options;a.pointRange=n(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=a.rowsize||1;d.ellipse=d.circle;a.marker&&g(a.borderRadius)&&(a.marker.r=a.borderRadius)};e.prototype.markerAttribs=function(a,b){var c=a.shapeArgs||{};if(a.hasImage)return{x:a.plotX,y:a.plotY};if(b&&"normal"!==b){var d=a.options.marker||{};a=this.options.marker||{};a=a.states&&a.states[b]||{};d=d.states&&d.states[b]||{};b=(d.width||a.width||c.width||0)+(d.widthPlus||
a.widthPlus||0);a=(d.height||a.height||c.height||0)+(d.heightPlus||a.heightPlus||0);return{x:(c.x||0)+((c.width||0)-b)/2,y:(c.y||0)+((c.height||0)-a)/2,width:b,height:a}}return c};e.prototype.pointAttribs=function(a,c){var d=r.prototype.pointAttribs.call(this,a,c),e=this.options||{},f=this.chart.options.plotOptions||{},g=f.series||{},h=f.heatmap||{};f=a&&a.options.borderColor||e.borderColor||h.borderColor||g.borderColor;g=a&&a.options.borderWidth||e.borderWidth||h.borderWidth||g.borderWidth||d["stroke-width"];
d.stroke=a&&a.marker&&a.marker.lineColor||e.marker&&e.marker.lineColor||f||this.color;d["stroke-width"]=g;c&&"normal"!==c&&(a=x(e.states&&e.states[c],e.marker&&e.marker.states&&e.marker.states[c],a&&a.options.states&&a.options.states[c]||{}),d.fill=a.color||b.parse(d.fill).brighten(a.brightness||0).get(),d.stroke=a.lineColor||d.stroke);return d};e.prototype.translate=function(){var a=this.options,b=a.borderRadius,c=(a=a.marker)&&a.symbol||"rect",e=d[c]?c:"rect",f=-1!==["circle","square"].indexOf(e);
this.generatePoints();this.points.forEach(function(a){var h=a.getCellAttributes(),k=Math.min(h.x1,h.x2),l=Math.min(h.y1,h.y2),m=Math.max(Math.abs(h.x2-h.x1),0),n=Math.max(Math.abs(h.y2-h.y1),0);a.hasImage=0===(a.marker&&a.marker.symbol||c||"").indexOf("url");f&&(l=Math.abs(m-n),k=Math.min(h.x1,h.x2)+(m<n?0:l/2),l=Math.min(h.y1,h.y2)+(m<n?l/2:0),m=n=Math.min(m,n));a.hasImage&&(a.marker={width:m,height:n});a.plotX=a.clientX=(h.x1+h.x2)/2;a.plotY=(h.y1+h.y2)/2;a.shapeType="path";a.shapeArgs=x(!0,{x:k,
y:l,width:m,height:n},{d:d[e](k,l,m,n,{r:g(b)?b:0})})});k(this,"afterTranslate")};e.defaultOptions=x(a.defaultOptions,{animation:!1,borderRadius:0,borderWidth:0,interpolation:!1,nullColor:"#f7f7f7",dataLabels:{formatter:function(){var a=this.series.chart.numberFormatter,b=this.point.value;return g(b)?a(b,-1):""},inside:!0,verticalAlign:"middle",crop:!1,overflow:"allow",padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},select:{}}},clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},
states:{hover:{halo:!1,brightness:.2}},legendSymbol:"rectangle"});return e}(a);l(e.prototype,{axisTypes:f.seriesMembers.axisTypes,colorKey:f.seriesMembers.colorKey,directTouch:!0,getExtremesFromAll:!0,parallelArrays:f.seriesMembers.parallelArrays,pointArrayMap:["y","value"],pointClass:m,specialGroup:"group",trackerGroups:f.seriesMembers.trackerGroups,alignDataLabel:q.prototype.alignDataLabel,colorAttribs:f.seriesMembers.colorAttribs,getSymbol:r.prototype.getSymbol});f.compose(e);p.registerSeriesType("heatmap",
e);"";"";return e});x(b,"masters/modules/map.src.js",[b["Core/Globals.js"],b["Core/Axis/Color/ColorAxis.js"],b["Series/MapBubble/MapBubbleSeries.js"],b["Core/Chart/MapChart.js"],b["Maps/MapView.js"],b["Maps/Projection.js"]],function(b,f,q,m,p,l){b.ColorAxis=f;b.MapChart=m;b.mapChart=b.Map=m.mapChart;b.MapView=p;b.maps=m.maps;b.Projection=l;f.compose(b.Chart,b.Fx,b.Legend,b.Series);q.compose(b.Axis,b.Chart,b.Legend,b.Series)})});//# sourceMappingURL=map.js.map