/*
 Highcharts JS v11.1.0 (2023-08-20)

 Sankey diagram module

 (c) 2010-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/sankey",["highcharts"],function(r){b(r);b.Highcharts=r;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function r(b,h,l,k){b.hasOwnProperty(h)||(b[h]=k.apply(null,l),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:h,module:b[h]}})))}b=b?b._modules:
{};r(b,"Series/NodesComposition.js",[b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,h){b=b.series;var l=b.prototype,k=b.prototype.pointClass.prototype,y=h.defined,w=h.extend,g=h.find,c=h.merge,f=h.pick,a;(function(a){function d(){this.data=[].concat(this.points||[],this.nodes);return l.destroy.apply(this,arguments)}function b(){this.nodes&&(this.nodes.forEach(function(a){a.destroy()}),this.nodes.length=0);l.setData.apply(this,arguments)}function x(a){var c=arguments,f=this.isNode?
this.linksTo.concat(this.linksFrom):[this.fromNode,this.toNode];"select"!==a&&f.forEach(function(a){a&&a.series&&(k.setState.apply(a,c),a.isNode||(a.fromNode.graphic&&k.setState.apply(a.fromNode,c),a.toNode&&a.toNode.graphic&&k.setState.apply(a.toNode,c)))});k.setState.apply(this,c)}function v(a,d,b,e){var n=this,m=this.series.options.nodes,z=this.series.options.data,C=z&&z.length||0,E=z&&z[this.index];k.update.call(this,a,this.isNode?!1:d,b,e);this.isNode&&(a=(m||[]).reduce(function(m,a,c){return n.id===
a.id?c:m},-1),e=c(m&&m[a]||{},z&&z[this.index]||{}),z&&(E?z[this.index]=E:z.length=C),m?0<=a?m[a]=e:m.push(e):this.series.options.nodes=[e],f(d,!0)&&this.series.chart.redraw(b))}var p=[];a.compose=function(a,c){h.pushUnique(p,a)&&(a=a.prototype,a.setNodeState=x,a.setState=x,a.update=v);h.pushUnique(p,c)&&(a=c.prototype,a.destroy=d,a.setData=b);return c};a.createNode=function(a){function c(a,c){return g(a,function(a){return a.id===c})}var d=this.pointClass,e=c(this.nodes,a);if(!e){e=this.options.nodes&&
c(this.options.nodes,a);var n=(new d).init(this,w({className:"highcharts-node",isNode:!0,id:a,y:1},e));n.linksTo=[];n.linksFrom=[];n.getSum=function(){var a=0,c=0;n.linksTo.forEach(function(m){a+=m.weight||0});n.linksFrom.forEach(function(a){c+=a.weight||0});return Math.max(a,c)};n.offset=function(a,c){for(var m=0,f=0;f<n[c].length;f++){if(n[c][f]===a)return m;m+=n[c][f].weight}};n.hasShape=function(){var a=0;n.linksTo.forEach(function(m){m.outgoing&&a++});return!n.linksTo.length||a!==n.linksTo.length};
n.index=this.nodes.push(n)-1;e=n}e.formatPrefix="node";e.name=e.name||e.options.id||"";e.mass=f(e.options.mass,e.options.marker&&e.options.marker.radius,this.options.marker&&this.options.marker.radius,4);return e};a.destroy=d;a.generatePoints=function(){var a=this,c=this.chart,d={};l.generatePoints.call(this);this.nodes||(this.nodes=[]);this.colorCounter=0;this.nodes.forEach(function(a){a.linksFrom.length=0;a.linksTo.length=0;a.level=a.options.level});this.points.forEach(function(e){y(e.from)&&(d[e.from]||
(d[e.from]=a.createNode(e.from)),d[e.from].linksFrom.push(e),e.fromNode=d[e.from],c.styledMode?e.colorIndex=f(e.options.colorIndex,d[e.from].colorIndex):e.color=e.options.color||d[e.from].color);y(e.to)&&(d[e.to]||(d[e.to]=a.createNode(e.to)),d[e.to].linksTo.push(e),e.toNode=d[e.to]);e.name=e.name||e.id},this);this.nodeLookup=d};a.setNodeState=x;a.updateNode=v})(a||(a={}));return a});r(b,"Series/Sankey/SankeyPoint.js",[b["Core/Series/Point.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],
function(b,h,l){var k=this&&this.__extends||function(){function b(g,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var d in a)Object.prototype.hasOwnProperty.call(a,d)&&(c[d]=a[d])};return b(g,c)}return function(g,c){function f(){this.constructor=g}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");b(g,c);g.prototype=null===c?Object.create(c):(f.prototype=c.prototype,
new f)}}(),y=l.defined;return function(h){function g(){var c=null!==h&&h.apply(this,arguments)||this;c.className=void 0;c.fromNode=void 0;c.level=void 0;c.linkBase=void 0;c.linksFrom=void 0;c.linksTo=void 0;c.mass=void 0;c.nodeX=void 0;c.nodeY=void 0;c.options=void 0;c.series=void 0;c.toNode=void 0;return c}k(g,h);g.prototype.applyOptions=function(c,f){b.prototype.applyOptions.call(this,c,f);y(this.options.level)&&(this.options.column=this.column=this.options.level);return this};g.prototype.getClassName=
function(){return(this.isNode?"highcharts-node ":"highcharts-link ")+b.prototype.getClassName.call(this)};g.prototype.getFromNode=function(){for(var c=-1,f,a=0;a<this.linksTo.length;a++){var d=this.linksTo[a];d.fromNode.column>c&&d.fromNode!==this&&(f=d.fromNode,c=f.column)}return{fromNode:f,fromColumn:c}};g.prototype.setNodeColumn=function(){y(this.options.column)||(this.column=0===this.linksTo.length?0:this.getFromNode().fromColumn+1)};g.prototype.isValid=function(){return this.isNode||"number"===
typeof this.weight};return g}(h.seriesTypes.column.prototype.pointClass)});r(b,"Series/Sankey/SankeySeriesDefaults.js",[],function(){"";return{borderWidth:0,colorByPoint:!0,curveFactor:.33,dataLabels:{enabled:!0,backgroundColor:"none",crop:!1,nodeFormat:void 0,nodeFormatter:function(){return this.point.name},format:void 0,formatter:function(){},inside:!0},inactiveOtherPoints:!0,linkOpacity:.5,opacity:1,minLinkWidth:0,nodeAlignment:"center",nodeWidth:20,nodePadding:10,showInLegend:!1,states:{hover:{linkOpacity:1,
opacity:1},inactive:{linkOpacity:.1,opacity:.1,animation:{duration:50}}},tooltip:{followPointer:!0,headerFormat:'<span style="font-size: 0.8em">{series.name}</span><br/>',pointFormat:"{point.fromNode.name} \u2192 {point.toNode.name}: <b>{point.weight}</b><br/>",nodeFormat:"{point.name}: <b>{point.sum}</b><br/>"}}});r(b,"Series/Sankey/SankeyColumnComposition.js",[b["Core/Utilities.js"]],function(b){var h=b.defined,l=b.relativeLength,k;(function(b){b.compose=function(b,c){b.sankeyColumn=new k(b,c);
return b};var k=function(){function b(c,b){this.points=c;this.series=b}b.prototype.getTranslationFactor=function(c){for(var b=this.points,a=b.slice(),d=c.options.minLinkWidth||0,u=0,h,g=(c.chart.plotSizeY||0)-(c.options.borderWidth||0)-(b.length-1)*c.nodePadding;b.length;){u=g/b.sankeyColumn.sum();c=!1;for(h=b.length;h--;)b[h].getSum()*u<d&&(b.splice(h,1),g=Math.max(0,g-d),c=!0);if(!c)break}b.length=0;a.forEach(function(a){b.push(a)});return u};b.prototype.top=function(c){var b=this.series,a=b.nodePadding,
d=this.points.reduce(function(d,f){0<d&&(d+=a);f=Math.max(f.getSum()*c,b.options.minLinkWidth||0);return d+f},0);return{top:0,center:.5,bottom:1}[b.options.nodeAlignment||"center"]*((b.chart.plotSizeY||0)-d)};b.prototype.left=function(c){var b=this.series,a=b.chart,d=b.options.equalNodes,h=a.inverted?a.plotHeight:a.plotWidth,g=b.nodePadding,k=this.points.reduce(function(a,f){0<a&&(a+=g);f=d?h/f.series.nodes.length-g:Math.max(f.getSum()*c,b.options.minLinkWidth||0);return a+f},0);return((a.plotSizeX||
0)-Math.round(k))/2};b.prototype.sum=function(){return this.points.reduce(function(b,f){return b+f.getSum()},0)};b.prototype.offset=function(b,f){var a=this.points,c=this.series,g=c.nodePadding,k=0;if(c.is("organization")&&b.hangsFrom)return{absoluteTop:b.hangsFrom.nodeY};for(var x=0;x<a.length;x++){var v=a[x].getSum();var p=Math.max(v*f,c.options.minLinkWidth||0),q=b.options[c.chart.inverted?"offsetHorizontal":"offsetVertical"],t=b.options.offset||0;v=v?p+g:0;if(a[x]===b)return{relativeTop:k+(h(q)?
l(q,p):l(t,v))};k+=v}};return b}();b.SankeyColumnAdditions=k})(k||(k={}));return k});r(b,"Series/TreeUtilities.js",[b["Core/Color/Color.js"],b["Core/Utilities.js"]],function(b,h){function l(a,b){var c=b.before,d=b.idRoot,h=b.mapIdToNode[d],g=b.points[a.i],p=g&&g.options||{},q=[],t=0;a.levelDynamic=a.level-(!1!==b.levelIsConstant?0:h.level);a.name=f(g&&g.name,"");a.visible=d===a.id||!0===b.visible;"function"===typeof c&&(a=c(a,b));a.children.forEach(function(c,d){var e=k({},b);k(e,{index:d,siblings:a.children.length,
visible:a.visible});c=l(c,e);q.push(c);c.visible&&(t+=c.val)});c=f(p.value,t);a.visible=0<=c&&(0<t||a.visible);a.children=q;a.childrenTotal=t;a.isLeaf=a.visible&&!t;a.val=c;return a}var k=h.extend,r=h.isArray,w=h.isNumber,g=h.isObject,c=h.merge,f=h.pick;return{getColor:function(a,c){var d=c.index,g=c.mapOptionsToLevel,h=c.parentColor,k=c.parentColorIndex,p=c.series,q=c.colors,t=c.siblings,l=p.points,e=p.chart.options.chart,n;if(a){l=l[a.i];a=g[a.level]||{};if(g=l&&a.colorByPoint){var m=l.index%(q?
q.length:e.colorCount);var z=q&&q[m]}if(!p.chart.styledMode){q=l&&l.options.color;e=a&&a.color;if(n=h)n=(n=a&&a.colorVariation)&&"brightness"===n.key&&d&&t?b.parse(h).brighten(d/t*n.to).get():h;n=f(q,e,z,n,p.color)}var C=f(l&&l.options.colorIndex,a&&a.colorIndex,m,k,c.colorIndex)}return{color:n,colorIndex:C}},getLevelOptions:function(a){var b={};if(g(a)){var h=w(a.from)?a.from:1;var k=a.levels;var l={};var v=g(a.defaults)?a.defaults:{};r(k)&&(l=k.reduce(function(a,b){if(g(b)&&w(b.level)){var d=c({},
b);var k=f(d.levelIsConstant,v.levelIsConstant);delete d.levelIsConstant;delete d.level;b=b.level+(k?0:h-1);g(a[b])?c(!0,a[b],d):a[b]=d}return a},{}));k=w(a.to)?a.to:1;for(a=0;a<=k;a++)b[a]=c({},v,g(l[a])?l[a]:{})}return b},setTreeValues:l,updateRootId:function(a){if(g(a)){var b=g(a.options)?a.options:{};b=f(a.rootNode,b.rootId,"");g(a.userOptions)&&(a.userOptions.rootId=b);a.rootNode=b}return b}}});r(b,"Series/Sankey/SankeySeries.js",[b["Core/Color/Color.js"],b["Core/Globals.js"],b["Series/NodesComposition.js"],
b["Series/Sankey/SankeyPoint.js"],b["Series/Sankey/SankeySeriesDefaults.js"],b["Core/Series/SeriesRegistry.js"],b["Series/Sankey/SankeyColumnComposition.js"],b["Series/TreeUtilities.js"],b["Core/Utilities.js"]],function(b,h,l,k,r,w,g,c,f){var a=this&&this.__extends||function(){function a(b,m){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var m in b)Object.prototype.hasOwnProperty.call(b,m)&&(a[m]=b[m])};return a(b,m)}return function(b,m){function c(){this.constructor=
b}if("function"!==typeof m&&null!==m)throw new TypeError("Class extends value "+String(m)+" is not a constructor or null");a(b,m);b.prototype=null===m?Object.create(m):(c.prototype=m.prototype,new c)}}(),d=w.series,u=w.seriesTypes.column,y=c.getLevelOptions,x=f.clamp;c=f.extend;var v=f.isObject,p=f.merge,q=f.pick,t=f.relativeLength,K=f.stableSort;f=function(c){function d(){var a=null!==c&&c.apply(this,arguments)||this;a.colDistance=void 0;a.data=void 0;a.group=void 0;a.nodeLookup=void 0;a.nodePadding=
void 0;a.nodes=void 0;a.nodeWidth=void 0;a.options=void 0;a.points=void 0;a.translationFactor=void 0;return a}a(d,c);d.getDLOptions=function(a){var b=v(a.optionsPoint)?a.optionsPoint.dataLabels:{};a=v(a.level)?a.level.dataLabels:{};return p({style:{}},a,b)};d.prototype.createNodeColumns=function(){var a=[];this.nodes.forEach(function(b){b.setNodeColumn();a[b.column]||(a[b.column]=g.compose([],this));a[b.column].push(b)},this);for(var b=0;b<a.length;b++)"undefined"===typeof a[b]&&(a[b]=g.compose([],
this));return a};d.prototype.order=function(a,b){var c=this;"undefined"===typeof a.level&&(a.level=b,a.linksFrom.forEach(function(a){a.toNode&&c.order(a.toNode,b+1)}))};d.prototype.generatePoints=function(){l.generatePoints.apply(this,arguments);var a=this;this.orderNodes&&(this.nodes.filter(function(a){return 0===a.linksTo.length}).forEach(function(b){a.order(b,0)}),K(this.nodes,function(a,b){return a.level-b.level}))};d.prototype.getNodePadding=function(){var a=this.options.nodePadding||0;if(this.nodeColumns){var b=
this.nodeColumns.reduce(function(a,b){return Math.max(a,b.length)},0);b*a>this.chart.plotSizeY&&(a=this.chart.plotSizeY/b)}return a};d.prototype.hasData=function(){return!!this.processedXData.length};d.prototype.pointAttribs=function(a,c){if(!a)return{};var m=this,d=m.mapOptionsToLevel[(a.isNode?a.level:a.fromNode.level)||0]||{},f=a.options,e=d.states&&d.states[c||""]||{};c=["colorByPoint","borderColor","borderWidth","linkOpacity","opacity"].reduce(function(a,b){a[b]=q(e[b],f[b],d[b],m.options[b]);
return a},{});var F=q(e.color,f.color,c.colorByPoint?a.color:d.color);return a.isNode?{fill:F,stroke:c.borderColor,"stroke-width":c.borderWidth,opacity:c.opacity}:{fill:b.parse(F).setOpacity(c.linkOpacity).get()}};d.prototype.drawTracker=function(){u.prototype.drawTracker.call(this,this.points);u.prototype.drawTracker.call(this,this.nodes)};d.prototype.drawPoints=function(){u.prototype.drawPoints.call(this,this.points);u.prototype.drawPoints.call(this,this.nodes)};d.prototype.drawDataLabels=function(){u.prototype.drawDataLabels.call(this,
this.points);u.prototype.drawDataLabels.call(this,this.nodes)};d.prototype.translate=function(){this.processedXData||this.processData();this.generatePoints();this.nodeColumns=this.createNodeColumns();this.nodeWidth=t(this.options.nodeWidth,this.chart.plotSizeX);var a=this,b=this.chart,c=this.options,d=this.nodeWidth,f=this.nodeColumns;this.nodePadding=this.getNodePadding();this.translationFactor=f.reduce(function(b,c){return Math.min(b,c.sankeyColumn.getTranslationFactor(a))},Infinity);this.colDistance=
(b.plotSizeX-d-c.borderWidth)/Math.max(1,f.length-1);a.mapOptionsToLevel=y({from:1,levels:c.levels,to:f.length-1,defaults:{borderColor:c.borderColor,borderRadius:c.borderRadius,borderWidth:c.borderWidth,color:a.color,colorByPoint:c.colorByPoint,levelIsConstant:!0,linkColor:c.linkColor,linkLineWidth:c.linkLineWidth,linkOpacity:c.linkOpacity,states:c.states}});f.forEach(function(b){b.forEach(function(c){a.translateNode(c,b)})},this);this.nodes.forEach(function(b){b.linksFrom.forEach(function(b){(b.weight||
b.isNull)&&b.to&&(a.translateLink(b),b.allowShadow=!1)})})};d.prototype.translateLink=function(a){function b(b,c){c=b.offset(a,c)*m;return Math.min(b.nodeY+c,b.nodeY+(b.shapeArgs&&b.shapeArgs.height||0)-e)}var c=a.fromNode,d=a.toNode,f=this.chart,m=this.translationFactor,e=Math.max(a.weight*m,this.options.minLinkWidth),h=(f.inverted?-this.colDistance:this.colDistance)*this.options.curveFactor,g=b(c,"linksFrom"),k=b(d,"linksTo"),l=c.nodeX,n=this.nodeWidth;d=d.nodeX;var q=a.outgoing,p=d>l+n;f.inverted&&
(g=f.plotSizeY-g,k=(f.plotSizeY||0)-k,n=-n,e=-e,p=l>d);a.shapeType="path";a.linkBase=[g,g+e,k,k+e];if(p&&"number"===typeof k)a.shapeArgs={d:[["M",l+n,g],["C",l+n+h,g,d-h,k,d,k],["L",d+(q?n:0),k+e/2],["L",d,k+e],["C",d-h,k+e,l+n+h,g+e,l+n,g+e],["Z"]]};else if("number"===typeof k){h=d-20-e;q=d-20;p=l+n;var r=p+20,t=r+e,v=g,u=g+e,x=u+20,w=x+(f.plotHeight-g-e),A=w+20,y=A+e,D=k,B=D+e,G=B+20,H=A+.7*e,I=d-.7*e,J=p+.7*e;a.shapeArgs={d:[["M",p,v],["C",J,v,t,u-.7*e,t,x],["L",t,w],["C",t,H,J,y,p,y],["L",d,y],
["C",I,y,h,H,h,w],["L",h,G],["C",h,B-.7*e,I,D,d,D],["L",d,B],["C",q,B,q,B,q,G],["L",q,w],["C",q,A,q,A,d,A],["L",p,A],["C",r,A,r,A,r,w],["L",r,x],["C",r,u,r,u,p,u],["Z"]]}}a.dlBox={x:l+(d-l+n)/2,y:g+(k-g)/2,height:e,width:0};a.tooltipPos=f.inverted?[f.plotSizeY-a.dlBox.y-e/2,f.plotSizeX-a.dlBox.x]:[a.dlBox.x,a.dlBox.y+e/2];a.y=a.plotY=1;a.x=a.plotX=1;a.color||(a.color=c.color)};d.prototype.translateNode=function(a,b){var c=this.translationFactor,e=this.chart,f=this.options,g=f.borderRadius,h=f.borderWidth,
k=void 0===h?0:h,l=a.getSum();h=Math.max(Math.round(l*c),this.options.minLinkWidth);var n=Math.round(this.nodeWidth),m=Math.round(k)%2/2,p=b.sankeyColumn.offset(a,c);b=Math.floor(q(p.absoluteTop,b.sankeyColumn.top(c)+p.relativeTop))+m;c=Math.floor(this.colDistance*a.column+k/2)+t(a.options.offsetHorizontal||0,n)+m;c=e.inverted?e.plotSizeX-c:c;(a.sum=l)?(a.shapeType="roundedRect",a.nodeX=c,a.nodeY=b,l=c,k=b,m=a.options.width||f.width||n,p=a.options.height||f.height||h,g=x(t("object"===typeof g?g.radius:
g||0,m),0,h/2),e.inverted&&(l=c-n,k=e.plotSizeY-b-h,m=a.options.height||f.height||n,p=a.options.width||f.width||h),a.dlOptions=d.getDLOptions({level:this.mapOptionsToLevel[a.level],optionsPoint:a.options}),a.plotX=1,a.plotY=1,a.tooltipPos=e.inverted?[e.plotSizeY-k-p/2,e.plotSizeX-l-m/2]:[l+m/2,k+p/2],a.shapeArgs={x:l,y:k,width:m,height:p,r:g,display:a.hasShape()?"":"none"}):a.dlOptions={enabled:!1}};d.defaultOptions=p(u.defaultOptions,r);return d}(u);l.compose(k,f);c(f.prototype,{animate:d.prototype.animate,
createNode:l.createNode,forceDL:!0,invertible:!0,isCartesian:!1,orderNodes:!0,noSharedTooltip:!0,pointArrayMap:["from","to","weight"],pointClass:k,searchPoint:h.noop});w.registerSeriesType("sankey",f);"";return f});r(b,"masters/modules/sankey.src.js",[],function(){})});//# sourceMappingURL=sankey.js.map