/*
 Highcharts JS v11.1.0 (2023-08-20)

 Wind barb series module

 (c) 2010-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/windbarb",["highcharts"],function(g){a(g);a.Highcharts=g;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function g(a,k,f,g){a.hasOwnProperty(k)||(a[k]=g.apply(null,f),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:k,module:a[k]}})))}a=a?a._modules:
{};g(a,"Extensions/DataGrouping/ApproximationRegistry.js",[],function(){return{}});g(a,"Series/OnSeriesComposition.js",[a["Series/Column/ColumnSeries.js"],a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,k,f){var g=a.prototype,p=k.prototype,b=f.defined,h=f.stableSort,m;(function(a){function m(a){return p.getPlotBox.call(this.options.onSeries&&this.chart.get(this.options.onSeries)||this,a)}function k(){g.translate.apply(this);var a=this,l=a.options,u=a.chart,c=a.points,e=l.onSeries,d=
(e=e&&u.get(e))&&e.options.step,v=e&&e.points,q=u.inverted,m=a.xAxis,k=a.yAxis;u=c.length-1;var p;l=l.onKey||"y";var f=v&&v.length,w=0,t;if(e&&e.visible&&f){w=(e.pointXOffset||0)+(e.barW||0)/2;var n=e.currentDataGrouping;var y=v[f-1].x+(n?n.totalRange:0);h(c,function(c,d){return c.x-d.x});for(l="plot"+l[0].toUpperCase()+l.substr(1);f--&&c[u];){var r=v[f];n=c[u];n.y=r.y;if(r.x<=n.x&&"undefined"!==typeof r[l]){if(n.x<=y&&(n.plotY=r[l],r.x<n.x&&!d&&(t=v[f+1])&&"undefined"!==typeof t[l])){var x=(n.x-
r.x)/(t.x-r.x);n.plotY+=x*(t[l]-r[l]);n.y+=x*(t.y-r.y)}u--;f++;if(0>u)break}}}c.forEach(function(d,e){d.plotX+=w;if("undefined"===typeof d.plotY||q)0<=d.plotX&&d.plotX<=m.len?q?(d.plotY=m.translate(d.x,0,1,0,1),d.plotX=b(d.y)?k.translate(d.y,0,0,0,1):0):d.plotY=(m.opposite?0:a.yAxis.len)+m.offset:d.shapeArgs={};if((p=c[e-1])&&p.plotX===d.plotX){"undefined"===typeof p.stackIndex&&(p.stackIndex=0);var v=p.stackIndex+1}d.stackIndex=v});this.onSeries=e}var w=[];a.compose=function(a){if(f.pushUnique(w,
a)){var l=a.prototype;l.getPlotBox=m;l.translate=k}return a};a.getPlotBox=m;a.translate=k})(m||(m={}));return m});g(a,"Series/Windbarb/WindbarbPoint.js",[a["Core/Utilities.js"],a["Series/Column/ColumnSeries.js"]],function(a,k){var f=this&&this.__extends||function(){function a(b,h){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var h in b)Object.prototype.hasOwnProperty.call(b,h)&&(a[h]=b[h])};return a(b,h)}return function(b,h){function f(){this.constructor=
b}if("function"!==typeof h&&null!==h)throw new TypeError("Class extends value "+String(h)+" is not a constructor or null");a(b,h);b.prototype=null===h?Object.create(h):(f.prototype=h.prototype,new f)}}(),g=a.isNumber;return function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.beaufort=void 0;b.beaufortLevel=void 0;b.direction=void 0;b.options=void 0;b.series=void 0;return b}f(b,a);b.prototype.isValid=function(){return g(this.value)&&0<=this.value};return b}(k.prototype.pointClass)});
g(a,"Series/Windbarb/WindbarbSeries.js",[a["Core/Animation/AnimationUtilities.js"],a["Extensions/DataGrouping/ApproximationRegistry.js"],a["Core/Globals.js"],a["Series/OnSeriesComposition.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"],a["Series/Windbarb/WindbarbPoint.js"]],function(a,k,f,g,p,b,h){var m=this&&this.__extends||function(){function a(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,d){a.__proto__=d}||function(a,d){for(var c in d)Object.prototype.hasOwnProperty.call(d,
c)&&(a[c]=d[c])};return a(b,c)}return function(b,c){function e(){this.constructor=b}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");a(b,c);b.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),w=a.animObject,t=p.series,x=p.seriesTypes.column;a=b.extend;var A=b.merge,z=b.pick;b=function(a){function b(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;return c}m(b,
a);b.registerApproximation=function(){k.windbarb||(k.windbarb=function(a,b){var d=0,c=0,e,g=a.length;for(e=0;e<g;e++)d+=a[e]*Math.cos(b[e]*f.deg2rad),c+=a[e]*Math.sin(b[e]*f.deg2rad);return[a.reduce(function(a,d){return a+d},0)/a.length,Math.atan2(c,d)/f.deg2rad]})};b.prototype.init=function(a,e){b.registerApproximation();t.prototype.init.call(this,a,e)};b.prototype.pointAttribs=function(a,b){var d=this.options;a=a.color||this.color;var c=this.options.lineWidth;b&&(a=d.states[b].color||a,c=(d.states[b].lineWidth||
c)+(d.states[b].lineWidthPlus||0));return{stroke:a,"stroke-width":c}};b.prototype.windArrow=function(a){var b=1.943844*a.value,d=this.options.vectorLength/20,c=-10;if(a.isNull)return[];if(0===a.beaufortLevel)return this.chart.renderer.symbols.circle(-10*d,-10*d,20*d,20*d);a=[["M",0,7*d],["L",-1.5*d,7*d],["L",0,10*d],["L",1.5*d,7*d],["L",0,7*d],["L",0,-10*d]];var q=(b-b%50)/50;if(0<q)for(;q--;)a.push(-10===c?["L",0,c*d]:["M",0,c*d],["L",5*d,c*d+2],["L",0,c*d+4]),b-=50,c+=7;q=(b-b%10)/10;if(0<q)for(;q--;)a.push(-10===
c?["L",0,c*d]:["M",0,c*d],["L",7*d,c*d]),b-=10,c+=3;q=(b-b%5)/5;if(0<q)for(;q--;)a.push(-10===c?["L",0,c*d]:["M",0,c*d],["L",4*d,c*d]),b-=5,c+=3;return a};b.prototype.drawPoints=function(){var a=this.chart,b=this.yAxis,d=a.inverted,f=this.options.vectorLength/2;this.points.forEach(function(c){var e=c.plotX,g=c.plotY;!1===this.options.clip||a.isInsidePlot(e,0)?(c.graphic||(c.graphic=this.chart.renderer.path().add(this.markerGroup).addClass("highcharts-point highcharts-color-"+z(c.colorIndex,c.series.colorIndex))),
c.graphic.attr({d:this.windArrow(c),translateX:e+this.options.xOffset,translateY:g+this.options.yOffset,rotation:c.direction}),this.chart.styledMode||c.graphic.attr(this.pointAttribs(c))):c.graphic&&(c.graphic=c.graphic.destroy());c.tooltipPos=[e+this.options.xOffset+(d&&!this.onSeries?f:0),g+this.options.yOffset-(d?0:f+b.pos-a.plotTop)]},this)};b.prototype.animate=function(a){a?this.markerGroup.attr({opacity:.01}):this.markerGroup.animate({opacity:1},w(this.options.animation))};b.prototype.markerAttribs=
function(){return{}};b.prototype.getExtremes=function(){return{}};b.prototype.shouldShowTooltip=function(b,e,d){void 0===d&&(d={});d.ignoreX=this.chart.inverted;d.ignoreY=!d.ignoreX;return a.prototype.shouldShowTooltip.call(this,b,e,d)};b.defaultOptions=A(x.defaultOptions,{dataGrouping:{enabled:!0,approximation:"windbarb",groupPixelWidth:30},lineWidth:2,onSeries:null,states:{hover:{lineWidthPlus:0}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.value}</b> ({point.beaufort})<br/>'},
vectorLength:20,colorKey:"value",yOffset:-20,xOffset:0});return b}(x);g.compose(b);a(b.prototype,{beaufortFloor:[0,.3,1.6,3.4,5.5,8,10.8,13.9,17.2,20.8,24.5,28.5,32.7],beaufortName:"Calm;Light air;Light breeze;Gentle breeze;Moderate breeze;Fresh breeze;Strong breeze;Near gale;Gale;Strong gale;Storm;Violent storm;Hurricane".split(";"),invertible:!1,parallelArrays:["x","value","direction"],pointArrayMap:["value","direction"],pointClass:h,trackerGroups:["markerGroup"],translate:function(){var a=this.beaufortFloor,
b=this.beaufortName;g.translate.call(this);this.points.forEach(function(c){for(var e=0;e<a.length&&!(a[e]>c.value);e++);c.beaufortLevel=e-1;c.beaufort=b[e-1]})}});b.registerApproximation();p.registerSeriesType("windbarb",b);"";return b});g(a,"masters/modules/windbarb.src.js",[],function(){})});//# sourceMappingURL=windbarb.js.map