/*
 Highcharts JS v11.1.0 (2023-08-20)

 (c) 2016-2021 Highsoft AS
 Authors: Jon Arild Nygard

 License: www.highcharts.com/license
*/
'use strict';(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/wordcloud",["highcharts"],function(k){b(k);b.Highcharts=k;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function k(b,e,f,p){b.hasOwnProperty(e)||(b[e]=p.apply(null,f),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:e,module:b[e]}})))}b=b?b._modules:
{};k(b,"Series/DrawPointUtilities.js",[b["Core/Utilities.js"]],function(){var b=this&&this.__assign||function(){b=Object.assign||function(b){for(var f,e=1,l=arguments.length;e<l;e++){f=arguments[e];for(var n in f)Object.prototype.hasOwnProperty.call(f,n)&&(b[n]=f[n])}return b};return b.apply(this,arguments)};return{draw:function(e,f){var p=f.animatableAttribs,l=f.onComplete,n=f.css,g=f.renderer,A=e.series&&e.series.chart.hasRendered?void 0:e.series&&e.series.options.animation,h=e.graphic;f.attribs=
b(b({},f.attribs),{"class":e.getClassName()})||{};if(e.shouldDraw())h||(h="text"===f.shapeType?g.text():"image"===f.shapeType?g.image(f.imageUrl||"").attr(f.shapeArgs||{}):g[f.shapeType](f.shapeArgs||{}),e.graphic=h,h.add(f.group)),n&&h.css(n),h.attr(f.attribs).animate(p,f.isNew?!1:A,l);else if(h){var k=function(){e.graphic=h=h&&h.destroy();"function"===typeof l&&l()};Object.keys(p).length?h.animate(p,void 0,function(){return k()}):k()}}}});k(b,"Series/Wordcloud/WordcloudPoint.js",[b["Core/Series/SeriesRegistry.js"],
b["Core/Utilities.js"]],function(b,e){var f=this&&this.__extends||function(){function b(e,f){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,e){b.__proto__=e}||function(b,e){for(var f in e)Object.prototype.hasOwnProperty.call(e,f)&&(b[f]=e[f])};return b(e,f)}return function(e,f){function g(){this.constructor=e}if("function"!==typeof f&&null!==f)throw new TypeError("Class extends value "+String(f)+" is not a constructor or null");b(e,f);e.prototype=null===f?Object.create(f):(g.prototype=
f.prototype,new g)}}();e=e.extend;b=function(b){function e(){var e=null!==b&&b.apply(this,arguments)||this;e.dimensions=void 0;e.options=void 0;e.polygon=void 0;e.rect=void 0;e.series=void 0;return e}f(e,b);e.prototype.isValid=function(){return!0};return e}(b.seriesTypes.column.prototype.pointClass);e(b.prototype,{weight:1});return b});k(b,"Series/Wordcloud/WordcloudUtils.js",[b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,e){function f(a,c){return!(c.left>a.right||c.right<a.left||c.top>
a.bottom||c.bottom<a.top)}function k(a,c){var d=c[0]-a[0];a=c[1]-a[1];return[[-a,d],[a,-d]]}function l(a){var c=a.axes||[];if(!c.length){c=[];var d=d=a.concat([a[0]]);d.reduce(function(a,d){var b=k(a,d)[0];B(c,function(a){return a[0]===b[0]&&a[1]===b[1]})||c.push(b);return d});a.axes=c}return c}function n(a,c){a=a.map(function(a){return a[0]*c[0]+a[1]*c[1]});return{min:Math.min.apply(this,a),max:Math.max.apply(this,a)}}function g(a,c){var d=l(a),b=l(c);d=d.concat(b);return!B(d,function(d){var b=n(a,
d);d=n(c,d);return!!(d.min>b.max||d.max<b.min)})}function A(a,c){function d(c){var d=f(e,c.rect);d&&(a.rotation%90||c.rotation%90)&&(d=g(w,c.polygon));return d}var b=!1,e=a.rect,w=a.polygon,h=a.lastCollidedWith;h&&((b=d(h))||delete a.lastCollidedWith);b||(b=!!B(c,function(c){var b=d(c);b&&(a.lastCollidedWith=c);return b}));return b}function h(a){var c=4*a,d=Math.ceil((Math.sqrt(c)-1)/2),b=2*d+1,e=Math.pow(b,2),f=!1;--b;1E4>=a&&("boolean"===typeof f&&c>=e-b&&(f={x:d-(e-c),y:-d}),e-=b,"boolean"===typeof f&&
c>=e-b&&(f={x:-d,y:-d+(e-c)}),e-=b,"boolean"===typeof f&&(f=c>=e-b?{x:-d+(e-c),y:d}:{x:d,y:d-(e-c-b)}),f.x*=5,f.y*=5);return f}function r(a,c){var d=c.width/2,b=-(c.height/2),e=c.height/2;return!(-(c.width/2)<a.left&&d>a.right&&b<a.top&&e>a.bottom)}function u(a,c,d){return d.map(function(d){return[d[0]+a,d[1]+c]})}function x(a,c){c=m(c)?c:14;c=Math.pow(10,c);return Math.round(a*c)/c}function v(a,c){var d=a[0];a=a[1];var b=y*-c;c=Math.cos(b);b=Math.sin(b);return[x(d*c-a*b),x(d*b+a*c)]}function C(a,
c,d){a=v([a[0]-c[0],a[1]-c[1]],d);return[a[0]+c[0],a[1]+c[1]]}var y=b.deg2rad,E=e.extend,B=e.find,m=e.isNumber,D=e.isObject,z=e.merge;return{archimedeanSpiral:function(a,c){var d=c.field;c=!1;d=d.width*d.width+d.height*d.height;var b=.8*a;1E4>=a&&(c={x:b*Math.cos(b),y:b*Math.sin(b)},Math.min(Math.abs(c.x),Math.abs(c.y))<d||(c=!1));return c},extendPlayingField:function(a,c){if(D(a)&&D(c)){var d=c.bottom-c.top;var b=c.right-c.left;c=a.ratioX;var e=a.ratioY;d=b*c>d*e?b:d;a=z(a,{width:a.width+d*c*2,height:a.height+
d*e*2})}return a},getBoundingBoxFromPolygon:function(a){return a.reduce(function(a,d){var c=d[0];d=d[1];a.left=Math.min(c,a.left);a.right=Math.max(c,a.right);a.bottom=Math.max(d,a.bottom);a.top=Math.min(d,a.top);return a},{left:Number.MAX_VALUE,right:-Number.MAX_VALUE,bottom:-Number.MAX_VALUE,top:Number.MAX_VALUE})},getPlayingField:function(a,c,d){d=d.reduce(function(a,c){c=c.dimensions;var b=Math.max(c.width,c.height);a.maxHeight=Math.max(a.maxHeight,c.height);a.maxWidth=Math.max(a.maxWidth,c.width);
a.area+=b*b;return a},{maxHeight:0,maxWidth:0,area:0});d=Math.max(d.maxHeight,d.maxWidth,.85*Math.sqrt(d.area));var b=a>c?a/c:1;a=c>a?c/a:1;return{width:d*b,height:d*a,ratioX:b,ratioY:a}},getPolygon:function(a,c,b,e,f){var d=[a,c],g=a-b/2;a+=b/2;b=c-e/2;c+=e/2;return[[g,b],[a,b],[a,c],[g,c]].map(function(a){return C(a,d,-f)})},getRandomPosition:function(a){return Math.round(a*(Math.random()+.5)/2)},getRotation:function(a,c,b,e){var d=!1;m(a)&&m(c)&&m(b)&&m(e)&&0<a&&-1<c&&e>b&&(d=b+c%a*((e-b)/(a-1||
1)));return d},getScale:function(a,c,b){var d=2*Math.max(Math.abs(b.top),Math.abs(b.bottom));b=2*Math.max(Math.abs(b.left),Math.abs(b.right));return Math.min(0<b?1/b*a:1,0<d?1/d*c:1)},getSpiral:function(a,c){var b,e=[];for(b=1;1E4>b;b++)e.push(a(b,c));return function(a){return 1E4>=a?e[a-1]:!1}},intersectionTesting:function(a,c){var b=c.placed,e=c.field,f=c.rectangle,g=c.polygon,h=c.spiral,l=1,k={x:0,y:0},n=a.rect=E({},f);a.polygon=g;for(a.rotation=c.rotation;!1!==k&&(A(a,b)||r(n,e));)k=h(l),D(k)&&
(n.left=f.left+k.x,n.right=f.right+k.x,n.top=f.top+k.y,n.bottom=f.bottom+k.y,a.polygon=u(k.x,k.y,g)),l++;return k},isPolygonsColliding:g,isRectanglesIntersecting:f,rectangularSpiral:function(a,b){a=h(a,b);b=b.field;a&&(a.x*=b.ratioX,a.y*=b.ratioY);return a},rotate2DToOrigin:v,rotate2DToPoint:C,squareSpiral:h,updateFieldBoundaries:function(a,b){if(!m(a.left)||a.left>b.left)a.left=b.left;if(!m(a.right)||a.right<b.right)a.right=b.right;if(!m(a.top)||a.top>b.top)a.top=b.top;if(!m(a.bottom)||a.bottom<
b.bottom)a.bottom=b.bottom;return a}}});k(b,"Series/Wordcloud/WordcloudSeries.js",[b["Series/DrawPointUtilities.js"],b["Core/Globals.js"],b["Core/Series/Series.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"],b["Series/Wordcloud/WordcloudPoint.js"],b["Series/Wordcloud/WordcloudUtils.js"]],function(b,e,f,k,l,n,g){var p=this&&this.__extends||function(){function a(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,
c)&&(a[c]=b[c])};return a(b,c)}return function(b,c){function d(){this.constructor=b}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),h=e.noop,r=k.seriesTypes.column,u=l.extend,x=l.isArray,v=l.isNumber,C=l.isObject,y=l.merge;l=g.archimedeanSpiral;var E=g.extendPlayingField,B=g.getBoundingBoxFromPolygon,m=g.getPlayingField,D=g.getPolygon,z=g.getRandomPosition,
a=g.getRotation,c=g.getScale,d=g.getSpiral,G=g.intersectionTesting,I=g.isPolygonsColliding,w=g.rectangularSpiral,J=g.rotate2DToOrigin,K=g.rotate2DToPoint,L=g.squareSpiral,M=g.updateFieldBoundaries;g=function(a){function g(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}p(g,a);g.prototype.bindAxes=function(){var a={endOnTick:!1,gridLineWidth:0,lineWidth:0,maxPadding:0,startOnTick:!1,title:void 0,tickPositions:[]};f.prototype.bindAxes.call(this);
u(this.yAxis.options,a);u(this.xAxis.options,a)};g.prototype.pointAttribs=function(a,b){a=e.seriesTypes.column.prototype.pointAttribs.call(this,a,b);delete a.stroke;delete a["stroke-width"];return a};g.prototype.deriveFontSize=function(a,b,c){a=v(a)?a:0;b=v(b)?b:1;c=v(c)?c:1;return Math.floor(Math.max(c,a*b))};g.prototype.drawPoints=function(){var a=this,e=a.hasRendered,f=a.xAxis,g=a.yAxis,k=a.group,h=a.options,l=h.animation,n=h.allowExtendPlayingField,H=a.chart.renderer,p=H.text().add(k),r=[],x=
a.placementStrategy[h.placementStrategy],z=h.rotation,A=a.points.map(function(a){return a.weight}),w=Math.max.apply(null,A),F=a.points.concat().sort(function(a,b){return b.weight-a.weight});a.group.attr({scaleX:1,scaleY:1});F.forEach(function(b){var c=a.deriveFontSize(1/w*b.weight,h.maxFontSize,h.minFontSize);c=u({fontSize:c+"px"},h.style);p.css(c).attr({x:0,y:0,text:b.name});c=p.getBBox(!0);b.dimensions={height:c.height,width:c.width}});var t=m(f.len,g.len,F);var y=d(a.spirals[h.spiral],{field:t});
F.forEach(function(c){var d=a.deriveFontSize(1/w*c.weight,h.maxFontSize,h.minFontSize);d=u({fontSize:d+"px"},h.style);var f=x(c,{data:F,field:t,placed:r,rotation:z}),g=u(a.pointAttribs(c,c.selected&&"select"),{align:"center","alignment-baseline":"middle","dominant-baseline":"middle",x:f.x,y:f.y,text:c.name,rotation:v(f.rotation)?f.rotation:void 0}),p=D(f.x,f.y,c.dimensions.width,c.dimensions.height,f.rotation),q=B(p),m=G(c,{rectangle:q,polygon:p,field:t,placed:r,spiral:y,rotation:f.rotation});!m&&
n&&(t=E(t,q),m=G(c,{rectangle:q,polygon:p,field:t,placed:r,spiral:y,rotation:f.rotation}));C(m)?(g.x=(g.x||0)+m.x,g.y=(g.y||0)+m.y,q.left+=m.x,q.right+=m.x,q.top+=m.y,q.bottom+=m.y,t=M(t,q),r.push(c),c.isNull=!1,c.isInside=!0):c.isNull=!0;if(l){var N={x:g.x,y:g.y};e?(delete g.x,delete g.y):(g.x=0,g.y=0)}b.draw(c,{animatableAttribs:N,attribs:g,css:d,group:k,renderer:H,shapeArgs:void 0,shapeType:"text"})});p=p.destroy();f=c(f.len,g.len,t);a.group.attr({scaleX:f,scaleY:f})};g.prototype.hasData=function(){return C(this)&&
!0===this.visible&&x(this.points)&&0<this.points.length};g.prototype.getPlotBox=function(){var a=this.chart,b=a.inverted,c=this[b?"yAxis":"xAxis"];b=this[b?"xAxis":"yAxis"];return{translateX:(c?c.left:a.plotLeft)+(c?c.len:a.plotWidth)/2,translateY:(b?b.top:a.plotTop)+(b?b.len:a.plotHeight)/2,scaleX:1,scaleY:1}};g.defaultOptions=y(r.defaultOptions,{allowExtendPlayingField:!0,animation:{duration:500},borderWidth:0,clip:!1,colorByPoint:!0,cropThreshold:Infinity,minFontSize:1,maxFontSize:25,placementStrategy:"center",
rotation:{from:0,orientations:2,to:90},showInLegend:!1,spiral:"rectangular",style:{fontFamily:"sans-serif",fontWeight:"900",whiteSpace:"nowrap"},tooltip:{followPointer:!0,pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.weight}</b><br/>'}});return g}(r);u(g.prototype,{animate:h,animateDrilldown:h,animateDrillupFrom:h,pointClass:n,setClip:h,placementStrategy:{random:function(b,c){var d=c.field;c=c.rotation;return{x:z(d.width)-d.width/2,y:z(d.height)-d.height/2,
rotation:a(c.orientations,b.index,c.from,c.to)}},center:function(b,c){c=c.rotation;return{x:0,y:0,rotation:a(c.orientations,b.index,c.from,c.to)}}},pointArrayMap:["weight"],spirals:{archimedean:l,rectangular:w,square:L},utils:{extendPlayingField:E,getRotation:a,isPolygonsColliding:I,rotate2DToOrigin:J,rotate2DToPoint:K}});k.registerSeriesType("wordcloud",g);"";return g});k(b,"masters/modules/wordcloud.src.js",[],function(){})});//# sourceMappingURL=wordcloud.js.map